### ISSUE TITLE
Occasional UT failure in SchemaTest.TTLtest

### ISSUE THREAD

**Issue by dutor** [vesoft-inc/nebula#1000]
> 21:13:14 [ RUN      ] SchemaTest.TTLtest
> 21:13:14 I0928 21:13:02.395555 125346 ExecutionPlan.cpp:15] Parsing query: SHOW HOSTS
> 21:13:14 I0928 21:13:02.395696 125332 MetaClient.cpp:311] Send request to meta [127.0.0.1:2498]
> 21:13:14 I0928 21:13:02.396891 127029 AdminClient.cpp:445] Get leader for host [127.0.0.1:17149]
> 21:13:14 /var/lib/jenkins/workspace/Nebula-Graph-UnitTest/src/graph/test/SchemaTest.cpp:672: Failure
> 21:13:14 Value of: verifyResult(resp, expected)
> 21:13:14   Actual: false ([127.0.0.1, 17149, online, 9, space 1: 9, ] vs. [127.0.0.1, 17149, online, 0, , ])
> 21:13:14 Expected: true
> 21:13:14 [  FAILED  ] SchemaTest.TTLtest (3 ms)
> 21:13:14 [----------] 3 tests from SchemaTest (30412 ms total)

**Comment by dangleptr** [comment]
It is due to the last UT has not finished before next UT start.

**Comment by critical27** [comment]
Exactly, the meta client in ut is global, so I have add a sleep at the ending of previous UT.

**Comment by jude-zhu** [comment]
#1306
