### ISSUE TITLE
Several common graph query scenarios

### ISSUE THREAD

**Issue by yanchaoguo** [vesoft-inc/nebula#1010]
1：怎么进行逆序查找 就是给定一个节点 找出前面的所有节点；2：如何快速获取图的每层节点数量
1. How to make a reverse search? If a certain vertex is specified, how to find all the vertices in front of it?
2. How to get each layer's vertex number of the graph?

**Comment by whitewum** [comment]
1是支持的，有个reverse指令。2图的“每层节点数量“是什么意思？是从一个点开始，一跳邻居数量，二跳邻居数量，三跳邻居数量？这个可以用 count 命令来取

**Comment by yanchaoguo** [comment]
> 1是支持的，有个reverse指令。2图的“每层节点数量“是什么意思？是从一个点开始，一跳邻居数量，二跳邻居数量，三跳邻居数量？这个可以用 count 命令来取

第二个问题的意思是 如何获取一个大图中 每层节点数量 ，比如图的最大层数是7层 那么如何随机获取第6层 、第二层的节点数量

**Comment by whitewum** [comment]
如果是个树（或者DAG）我能理解，图是有环的，怎么定义第7层？a->b->c->a 谁算第一层？

**Comment by yanchaoguo** [comment]
> 如果是个树（或者DAG）我能理解，图是有环的，怎么定义第7层？a->b->c->a 谁算第一层？

对 是个有向无环图

**Comment by yanchaoguo** [comment]
reverse 指令 beta版支持吗 。有没有一个例子

**Comment by dutor** [comment]
> reverse 指令 beta版支持吗 。有没有一个例子

`GO REVERSELY` is being in progress. Coming soon.
