### ISSUE TITLE
product introduction

### ISSUE THREAD

**Issue by yuqin11** [vesoft-inc/nebula#1036]
is there any doc about  how whole system work? whats the function of each part when i get-started as the get-start.md says.  how could i build a cluster with the docker?

**Comment by Amber1990Zhang** [comment]
> is there any doc about how whole system work? whats the function of each part when i get-started as the get-start.md says. how could i build a cluster with the docker?

1. Please refer [Product Introduction](https://mp.weixin.qq.com/s/3kSnMdbaY3Q_XamFtaZXVQ), hoping that's what you want.
2. Please refer [Deploy Clusters on Docker
](https://github.com/vesoft-inc/nebula/blob/master/docs/get-started/deploy-cluster-on-docker.md)

**Comment by yuqin11** [comment]
Note: This is for testing only. DO NOT USE in production.

**Comment by yuqin11** [comment]
1. what's the disadvantage of doing like this?
2. if we want to deploy a cluster in production or a cluster more stable ,how could we do it?

**Comment by Amber1990Zhang** [comment]
> Note: This is for testing only. DO NOT USE in production.

Do you mean to use docker in production? It's the same way to deploy.

**Comment by yuqin11** [comment]
thanks for your patient. i guess you mean you do not recommend to use docker in production? just build and start in multi server and then a cluster work?

**Comment by Amber1990Zhang** [comment]
> thanks for your patient. i guess you mean you do not recommend to use docker in production? just build and start in multi server and then a cluster work?

Thanks for your issue. I didn't mean you can't use docker in production, actually, lots cloud use Docker in production. @yixinglu Please help with this issue.

**Comment by yuqin11** [comment]
and i have another question: do nebula support restful operation? @Amber1990Zhang

**Comment by yixinglu** [comment]
> 1. what's the disadvantage of doing like this?
> 2. if we want to deploy a cluster in production or a cluster more stable ,how could we do it?

@yuqin11 
We don't recommend the deployment way in [the document](https://github.com/vesoft-inc/nebula/blob/master/docs/get-started/deploy-cluster-on-docker.md) since the `vesoft/nebula-graph` docker image only for testing. You could find out that all nebula services are installed in same docker image `vesoft/nebula-graph`, that's not a good practice. If you want to deploy nebula with docker in k8s or docker swarm cluster, you should refer the following docker images: [vesoft/nebula-graphd](https://hub.docker.com/r/vesoft/nebula-graphd),  [vesoft/nebula-metad](https://hub.docker.com/r/vesoft/nebula-metad), [vesoft/nebula-storaged](https://hub.docker.com/r/vesoft/nebula-storaged). However, only `nightly` version are supported for them. And we will publish related stable tags for the images after next nebula release.

**Comment by yuqin11** [comment]
1. As your [product introduction ](https://mp.weixin.qq.com/s/3kSnMdbaY3Q_XamFtaZXVQ) mentioned: one edge has In-Edge-Key and Out-Edge-Key, In-Edge-Key has been stored in the same partition with the vertex the edge direct to. So where are the Out-Edge-Key and its value stored?

**Comment by whitewum** [comment]
> 1. As your [product introduction ](https://mp.weixin.qq.com/s/3kSnMdbaY3Q_XamFtaZXVQ) mentioned: one edge has In-Edge-Key and Out-Edge-Key, In-Edge-Key has been stored in the same partition with the vertex the edge direct to. So where are the Out-Edge-Key and its value stored?

Out-Edge-Key  ared stored in the same partition with the src vertex.

**Comment by yuqin11** [comment]
I tried as your get-started instructed, but i have some questions:
1. how could i create a graph from my data from csv/json format file, which is a little bit large, such as 40G. Is there any bulk load method?
2. I have tried your nGQL, it's great, but how could i get data with other program language, such as go/python/java? Is there any method to connect nebula by socket or restful?
3. I did not see your index build part. how to guarantee the latent when the number of vertex and edge is very large, could you please explain for me?

**Comment by yuqin11** [comment]
here i want to submit a probable bug: when restart nebula cluster in docker with `/usr/local/nebula/scripts/nebula.service start all` and use `exit` to quit container,  the bash comand line did not work.

**Comment by whitewum** [comment]
> 1. how could i create a graph from my data from csv/json format file, which is a little bit large, such as 40G. Is there any bulk load method?

https://github.com/vesoft-inc/nebula/tree/master/src/tools/importer

40G is a proper size.

2. I have tried your nGQL, it's great, but how could i get data with other program languages, such as go/python/java? Is there any method to connect nebula by socket or restful?

We'll provide some example code soon. For now, can you take look (for cpp dev), it's a cpp example

 https://github.com/vesoft-inc/nebula/tree/master/src/console

3. I did not see your index build part. how to guarantee the latent when the number of vertex and edge is very large, could you please explain for me?

We now still have some minor problems for the index feature. For now, there is a simple walkaround:
make the property as a vertex and pointing to your vertex.

**Comment by whitewum** [comment]
> here i want to submit a probable bug: when restart nebula cluster in docker with `/usr/local/nebula/scripts/nebula.service start all` and use `exit` to quit container, the bash comand line did not work.

Can you paste the screen shot?

**Comment by yuqin11** [comment]
![image](https://user-images.githubusercontent.com/32193605/66634577-f3452300-ec3f-11e9-9fb7-c761af9dc5c8.png)

**Comment by yuqin11** [comment]
Have you ever tested nebula on any big dataset which has dozens of billions of vertices (nodes) and trillions of edges, is there any benchmark result?

**Comment by yuqin11** [comment]
> > 1. what's the disadvantage of doing like this?
> > 2. if we want to deploy a cluster in production or a cluster more stable ,how could we do it?
> 
> @yuqin11
> We don't recommend the deployment way in [the document](https://github.com/vesoft-inc/nebula/blob/master/docs/get-started/deploy-cluster-on-docker.md) since the `vesoft/nebula-graph` docker image only for testing. You could find out that all nebula services are installed in same docker image `vesoft/nebula-graph`, that's not a good practice. If you want to deploy nebula with docker in k8s or docker swarm cluster, you should refer the following docker images: [vesoft/nebula-graphd](https://hub.docker.com/r/vesoft/nebula-graphd), [vesoft/nebula-metad](https://hub.docker.com/r/vesoft/nebula-metad), [vesoft/nebula-storaged](https://hub.docker.com/r/vesoft/nebula-storaged). However, only `nightly` version are supported for them at present. And we will publish related stable tags for the images after next nebula release.

Realy eager to try next nebula release, and build cluster with new images.

**Comment by yuqin11** [comment]
Can you give me your contact information ?my  email is 1130255696@qq.com, i'd like to learn more about nebula and learn your plan on nebula, we want to try nebula in production
