### ISSUE TITLE
Include basic data importer in docker image

### ISSUE THREAD

**Issue by yuqin11** [vesoft-inc/nebula#1045]
when i use `docker pull vesoft/nebula-graph:latest` this image to start a container and want to import data with [importer](https://github.com/vesoft-inc/nebula/tree/master/src/tools/importer),

i suggest you to include the importer tool in the docker images and include an example of how to prepare and import 100-200G data

**Comment by whitewum** [comment]
For that data size, I think it's better to build by source code and run in a physical machine (SSD):

https://github.com/vesoft-inc/nebula/blob/master/docs/how-to-build.md

**Comment by jude-zhu** [comment]
ref to https://github.com/vesoft-inc/nebula-go
