### ISSUE TITLE
[doc] reorganize  doc structures 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1056]
1. some the files under nebula/docs/ looks redundant (e.g. nGQL.md, nGQL-tutorial.md, get-started.md, manual-example-graph.md) 

I'll combine them into a new get-started.md under overview/ directory

2. the files in nebula/docs/overview are not well sorted. I'll re-order and re-arrange the files.

3. I'll move  all the files about deployment & build into a  new directory.

**Comment by Amber1990Zhang** [comment]
> 1. some the files under nebula/docs/ looks redundant (e.g. nGQL.md, nGQL-tutorial.md, get-started.md, manual-example-graph.md)
> 
> I'll combine them into a new get-started.md under overview/ directory
> 
> 1. the files in nebula/docs/overview are not well sorted. I'll re-order and re-arrange the files.
> 2. I'll move  all the files about deployment & build into a  new directory.

I think nGQL.md is not in use anymore, maybe we should delete it?
