### ISSUE TITLE
[Bug]Graphd no response

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1060]
I deployed cluster with 3 hosts, then killed 2, then tried to query, but graphd is timeout with no response, I think there may be a bug here:
![image](https://user-images.githubusercontent.com/42762957/66699821-7176f780-ed1c-11e9-9d00-92b7e0e7d91c.png)

**Comment by dangleptr** [comment]
For show hosts,  metad will blocked if storaged crashed, because it will get the leader information synchronously.

We should fix the problem.
