### ISSUE TITLE
[console] support -e "command" as non-interactive  mode

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1087]
for example

mysql -h${HOSTNAME}  -P${PORT}  -u${USERNAME} -p${PASSWORD} ${DBNAME} -e"${insert_sql}"

or source a .sql file

mysql> source xxx.sql

BTW. (better to combine data-importor to console like mysql)

mysql -uroot -p < SeCount.sql

**Comment by wey-gu** [comment]
Please note it's supported in nebula-console v2.
