### ISSUE TITLE
[Discuss]Support count function for Tag/Edge

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#1106]
**Is your feature request related to a problem? Please describe.**
DA wants to count the number of records in TAG/EDGE.

**Describe the solution you'd like**
Syntax like:
SELECT count(\*) FROM TAG tag_name [WHERE CLAUSE];
SELECT count(\*) FROM EDGE edge_name [WHERE CLAUSE];

**Comment by whitewum** [comment]
Can you explain the use case or scenario and the priority?

**Comment by zlcook** [comment]
> Can you explain the use case or scenario and the priority?
Verify that the amount of data in a TAG/EDGE matches expectations or not after some operations.  Or just want to know the scale of business data. It is necessary in actual project.

**Comment by jude-zhu** [comment]
refer to https://docs.nebula-graph.io/2.0/3.ngql-guide/7.general-query-statements/6.show/14.show-stats/
