### ISSUE TITLE
Timestamp can't return UTC time

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1114]
Bug as the title.
![image](https://user-images.githubusercontent.com/42762957/67010571-7bd03180-f120-11e9-874f-0f0a379dcde2.png)

**Comment by whitewum** [comment]
Interesting.

BTW,

When I seek to manual timestamp.md and functions-and-operator-reference.md,
the return type of now() and all others are not given (is it timestamp? int? string?).

**Comment by Amber1990Zhang** [comment]
> Interesting.
> 
> BTW,
> 
> When I seek to manual timestamp.md and functions-and-operator-reference.md,
> the return type of now() and all others are not given (is it timestamp? int? string? is it UTC). Please fix the omit.

now( ) returns an int for now, that's why I think it's a bug.

**Comment by Amber1990Zhang** [comment]
> Interesting.
> 
> BTW,
> 
> When I seek to manual timestamp.md and functions-and-operator-reference.md,
> the return type of now() and all others are not given (is it timestamp? int? string? is it UTC). Please fix the omit.

will add a new column on the

**Comment by jude-zhu** [comment]
It's not a bug, it returns the current time in second. 

![1](https://user-images.githubusercontent.com/51590253/70294472-8f457200-181e-11ea-8baf-f44ed6eee44b.jpg)
