### ISSUE TITLE
Does nebula plan to support parallel raft to improve write performance?

### ISSUE THREAD

**Issue by windshg** [vesoft-inc/nebula#1119]
refer to polardb's implementation:
http://www.vldb.org/pvldb/vol11/p1849-cao.pdf

**Comment by Amber1990Zhang** [comment]
Please help with this issue. @whitewum

**Comment by yixinglu** [comment]
CC @dangleptr

**Comment by critical27** [comment]
In my humble opinion, if we want to use as a general raft,  we should not support parallel raft (especially commit out of order), it require raft know some inner process logic between different logs. If not as a general raft, maybe worth a try, but not now.
