### ISSUE TITLE
when start service after killing them, metad crash

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1133]
I killed the `storaged`, then `metad` service. Then restart it, `metad` crash. And commit id is "6838c8b21854c7ee6e0b1b9f17ccf66d4bdb392f"

![2](https://user-images.githubusercontent.com/51590253/67369439-96d0f480-f5ab-11e9-9c82-6cbb6aae520a.png)

 Detail is :

![1](https://user-images.githubusercontent.com/51590253/67369453-9d5f6c00-f5ab-11e9-9a00-f7a0c5458c9f.png)

After delete the files under /data/, it can be restarted successfully

**Comment by critical27** [comment]
![image](https://user-images.githubusercontent.com/13706157/67733707-15111900-fa3a-11e9-99bf-43aef647c74b.png)
It seems the sst file of meta is not there anymore, and after you delete files under data/, you can restart successfully
