### ISSUE TITLE
time: how to store time earlier than 1970-01-01 00:00:00

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1155]
The doc says timestamp ranges 
![image](https://user-images.githubusercontent.com/42762957/67670522-0af60880-f9af-11e9-8713-0c869d879c75.png)

What if I want to insert time earlier than that range? For now the result is:
![image](https://user-images.githubusercontent.com/42762957/67670580-26611380-f9af-11e9-8188-9757aef192bf.png)

**Comment by whitewum** [comment]
I check mysql manual: 

https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

The valid range of argument values is the same as for the TIMESTAMP data type: '1970-01-01 00:00:01.000000' UTC to '2038-01-19 03:14:07.999999' UTC. If you pass an out-of-range date to UNIX_TIMESTAMP(), it returns 0.

but currently, return Invalid is also OK.

You can reference mysql's bevavior, but not reference what R do.

**Comment by Amber1990Zhang** [comment]
> I check mysql manual:
> 
> https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html
> 
> The valid range of argument values is the same as for the TIMESTAMP data type: '1970-01-01 00:00:01.000000' UTC to '2038-01-19 03:14:07.999999' UTC. If you pass an out-of-range date to UNIX_TIMESTAMP(), it returns 0.
> 
> but currently, return Invalid is also OK.
> 
> You can reference mysql's bevavior, but not reference what R do.

Thanks for your kind response.
