### ISSUE TITLE
`FETCH PRO ON` returns nothing with non-existed vertex

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1166]
If I fetch properties on non-existed vertex, nothing will return, will nebula check if the vertex really exists and tell me?
![image](https://user-images.githubusercontent.com/42762957/67747559-f3c52280-fa63-11e9-9274-91488a1c92ad.png)

**Comment by darionyaphet** [comment]
It seems the vertex doesn't exist. IMO return an empty result set is reasonable. It's ok.

**Comment by whitewum** [comment]
please report if it behaves differently from MySQL. I think the current behavior is ok.
