### ISSUE TITLE
Improve heartbeat of storage.

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula#1173]
We can add more info in heartbeat from storage to meta, such as leader/follower/learner count and so on. So we can avoid block in meta service.

After #1086 merged in, I will change the interface.

**Comment by zhangguoqing** [comment]
good idea!

**Comment by dangleptr** [comment]
Close #1060

**Comment by dangleptr** [comment]
Besides that,  we could optimize the load data logic inside meta client.
