### ISSUE TITLE
Some feature questions about nGQL query

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula#1174]
**Is your feature request related to a problem? Please describe.**
I have some questions about nGQL query, which may be not supported now:
- Query only match vertexes under some conditions like Neo4j's match (This may be in your plan)
- ~~Query match edge types which is related to one or multiple vertexes. Now, I can get all edge types by code `SHOW EDGES`, I want to add some condition filter to the result.~~
- Query a vertex Tag? Can I get the which tag the selected vertex belongs to? Or I need to add this type prop in my vertex data myself?
Thanks.

**Comment by Amber1990Zhang** [comment]
For your third question, I don't think there is a way to get a certain vertex's tag.

**Comment by nianiaJR** [comment]
> For your third question, I don't think there is a way to get a certain vertex's tag.

Ok, and there is another question. If I only know the vertex id,  can I query the vertex's props by [Fetch Syntax](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md), it now seems to require `Vertex TAG`.

**Comment by Amber1990Zhang** [comment]
> > For your third question, I don't think there is a way to get a certain vertex's tag.
> 
> Ok, and there is another question. If I only know the vertex id, can I query the vertex's props by [Fetch Syntax](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md), it now seems to require `Vertex TAG`.

Unfortunately, you can't. To fetch vertex properties, you need to know the tag.

**Comment by nianiaJR** [comment]
> > > For your third question, I don't think there is a way to get a certain vertex's tag.
> > 
> > 
> > Ok, and there is another question. If I only know the vertex id, can I query the vertex's props by [Fetch Syntax](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md), it now seems to require `Vertex TAG`.
> 
> Unfortunately, you can't. To fetch vertex properties, you need to know the tag.

I think it can be supported lately，because the id is uuid in nebula and it can be done. thx.

**Comment by Amber1990Zhang** [comment]
> > > > For your third question, I don't think there is a way to get a certain vertex's tag.
> > > 
> > > 
> > > Ok, and there is another question. If I only know the vertex id, can I query the vertex's props by [Fetch Syntax](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md), it now seems to require `Vertex TAG`.
> > 
> > 
> > Unfortunately, you can't. To fetch vertex properties, you need to know the tag.
> 
> I think it can be supported lately，because the id is uuid in nebula and it can be done. thx.

Thanks for your issue, nebula will support fetching vertex without tag in the future.

**Comment by whitewum** [comment]
> **Is your feature request related to a problem? Please describe.**
> I have some questions about nGQL query, which may be not supported now:
> 
> * Query only match vertexes under some conditions like Neo4j's match (This may be in your plan)

Yes, it's on developing now.

> * ~Query match edge types which is related to one or multiple vertexes. Now, I can get all edge types by code `SHOW EDGES`, I want to add some condition filter to the result.~
> * Query a vertex Tag? Can I get the which tag the selected vertex belongs to? Or I need to add this type prop in my vertex data myself?

You should provide the Tag for now. 

>   Thanks.
