### ISSUE TITLE
Docker compose server crashes  DELETE VERTEX not in use

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1187]
As title, crashed during use.
![image](https://user-images.githubusercontent.com/42762957/67930587-0b82df00-fbfb-11e9-8878-ee84748363e5.png)
Restart service and everything is OK until I run the query ` DELETE VERTEX 402`
![image](https://user-images.githubusercontent.com/42762957/67931472-daa3a980-fbfc-11e9-81fb-21e37636293b.png)

**Comment by Amber1990Zhang** [comment]
I changed to compiled nebula, and `DELETE VERTEX` won't work either. I think maybe the `DELETE VERTEX` syntax is the crash reason.
![image](https://user-images.githubusercontent.com/42762957/67931969-f8254300-fbfd-11e9-8961-3f035fdab580.png)

**Comment by whitewum** [comment]
check the check()

**Comment by Amber1990Zhang** [comment]
> check the check()


Sorry I don't get your point.
