### ISSUE TITLE
Traverse multiple edges can't get edge property

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1192]
As title.
![image](https://user-images.githubusercontent.com/42762957/67941707-35df9700-fc11-11e9-9775-fc329cc048bb.png)

**Comment by whitewum** [comment]
add one more prove: 
go from 100 over like yield like.likeness;
go from 100 over serve yield serve.end_year

**Comment by Amber1990Zhang** [comment]
> try:
> go from 100 over like yield like.likeness;
> go from 100 over serve yield serve.end_year
> try:
> go from 100 over * yield *

I tried your suggestions and they all works, but traverse multiple edges won't.
