### ISSUE TITLE
Could not create logging file

### ISSUE THREAD

**Issue by wilsonyou** [vesoft-inc/nebula#1213]
When I created a new graph space, the following error occurred:

![image](https://user-images.githubusercontent.com/40747875/68259834-eb797280-0075-11ea-9585-aa147ec76d5e.png)

**Comment by critical27** [comment]
Thanks for feeding back. Maybe you need to reset your max open files by `ulimit -n`.

**Comment by whitewum** [comment]
@wilsonyou can u add some `trouble shooting`
