### ISSUE TITLE
BalanceIntegrationTest.BalanceTest failed occasionally

### ISSUE THREAD

**Issue by zhangguoqing** [vesoft-inc/nebula#1214]
`# ./src/meta/test/_build/balance_integration_test --gtest_filter=BalanceIntegrationTest.BalanceTest`

![image](https://user-images.githubusercontent.com/5643942/68262417-35665680-007e-11ea-9848-3ccced8d9433.png)

**Comment by critical27** [comment]
Yeah, it will be fixed in #1205

**Comment by zhangguoqing** [comment]
> Yeah, it will be fixed in #1205

Sometimes, the PR #1205 may not work!
