### ISSUE TITLE
Properties order problem when inserting a vertex

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#1215]
**Describe the bug(__must be provided__)**
Inserting a vertex will results in an error if the order of the inserted properties does not match the order in which they were created.

**How To Reproduce(__must be provided__)**
* The order of properties of merchatn Tag
```
(user@xxx) [graph]> describe Tag merchant;
=========================
| Field        | Type   |
=========================
| merchantNo   | string |
-------------------------
| merchantName | string |
-------------------------
```
* success and  failure
```
(user@xxx) [graph]> INSERT VERTEX merchant(merchantNo, merchantName) VALUES uuid("merchant_beijingbus123"):("beijingbus123", "beijingbus");
Execution succeeded (Time spent: 3502/4472 us)

(user@xxx) [graph]> INSERT VERTEX merchant(merchantName, merchantNo) VALUES uuid("merchant_beijingbus123"):("beijingbus", "beijingbus123");
[ERROR (-8)]: Input field name `merchantName' is wrong
```

**Comment by Amber1990Zhang** [comment]
Currently, you need to make the property order the same with the tag.

**Comment by zlcook** [comment]
> Currently, you need to make the property order the same with the tag.

Yep,  now we do as you said

**Comment by laura-ding** [comment]
Yeah, this is unreasonable. I think the default value can do it together, but the default value has not been added. so I will fix it
