### ISSUE TITLE
The memory of nebula-storaged is so large.

### ISSUE THREAD

**Issue by tong-hao** [vesoft-inc/nebula#1216]
**Describe the bug(__must be provided__)**
The nebula-storaged service  occupies 4g of memory.
![Selection_008](https://user-images.githubusercontent.com/28890406/68286226-b263f100-00bb-11ea-9fff-09b6d440684c.png)

**Your Environments(__must be provided__)**
  * OS: Linux ht-dev 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  * Compliler: g++ (GCC) 8.2.0
  * CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

**How To Reproduce(__must be provided__)**
  1. I create a space. Then I create some tags and edges. 
  2. Then I insert less than 10 vertexes and edges.
  3. I execute some quering such as GO xxx and FETCH xxx

**Expected behavior**
NA

**Additional context**
NA

**Comment by whitewum** [comment]
Nebula is mainly designed to run on a db server cluster (256GB/512GB mem). So its default parameters are not tuned for a pc. You can try to reduce mem usage if you're familiar with rocksdb parameters.  
Anyway, thank you for your report/suggestion. We can provide another set of parameters for small mem.

**Comment by tong-hao** [comment]
The log files  occupies 205g. Is it normal?
![Selection_009](https://user-images.githubusercontent.com/28890406/68352804-948d9f00-0142-11ea-8ea7-02a8d2f924db.png)

**Comment by yixinglu** [comment]
you can stop all nebula services and then clean the logs folder. After that, goto /usr/local/nebula/etc directory, update storage/meta configure option `--v=0` and `--minloglevel=2` to reduce logs output

**Comment by whitewum** [comment]
According to my experience,  a partition will consume about 64MB memory.
