### ISSUE TITLE
[bug] No response when connecting nebula

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1222]
As title, when I try to connect to nebula, no error or any response is returned. And I'm sure the services are all running. Will someone help me?
![image](https://user-images.githubusercontent.com/42762957/68364824-0b8a5e00-016a-11ea-938d-e368f53295c7.png)

**Comment by Amber1990Zhang** [comment]
I updated the code and recompile but the error remains.

**Comment by Amber1990Zhang** [comment]
@whitewum I think this is terrible. I'm expecting a success connection or errors thrown rather than nothing even I may have missed something here.

**Comment by whitewum** [comment]
emmm, It seems that we should provide some log for the client/console. It's too hard to predicte the error by the screen shot.

**Comment by darionyaphet** [comment]
Not easy to judge what happened. Could you support more detail ?

**Comment by Amber1990Zhang** [comment]
> Not easy to judge what happened. Could you support more detail ?
I updated the code then recompiled and it works.

**Comment by critical27** [comment]
Just close it? @Amber1990Zhang

**Comment by Amber1990Zhang** [comment]
> Just close it? @Amber1990Zhang

I guess so because I don't know how to reproduce.

**Comment by whitewum** [comment]
I think it's due to the port occupied, or storaged failover-replay problem
