### ISSUE TITLE
Support list the partition specified in console

### ISSUE THREAD

**Issue by zhangguoqing** [vesoft-inc/nebula#1226]
**Is your feature request related to a problem? Please describe.**
It 's maybe a subtask of the PR #1086, that from the [discussion](https://github.com/vesoft-inc/nebula/pull/1086#discussion_r341891011).

**Describe the solution you'd like**

1. The specified partition ID as the parameter.
        (user@ip) [space]> SHOW PART **666**;
2. The result is sorted by partition IDs, so it maybe use the **LIMIT** clause easily.
        (user@ip) [space]>  SHOW PARTS **| LIMIT 666, 1**
3.  Both of the above are implemented.

Which solution should we choose?

**Comment by dangleptr** [comment]
I think we could support "show part $ID" firstly.  It is more useful.

**Comment by zhangguoqing** [comment]
> I think we could support "show part $ID" firstly. It is more useful.

OK, it will be implemented after the Issue #1173 is fixed. The leader distribution of partition is get from meta server directly.

**Comment by Amber1990Zhang** [comment]
Definitely, I think `SHOW PARTS` can be used with `LIMIT` is reasonable, after all, I'm not expecting a part list as long as 1024.

**Comment by critical27** [comment]
I guess `SHOW PART 666` is enough for now.

**Comment by zhangguoqing** [comment]
@jude-zhu This issue is support `show part $ID` rather than `show parts` command!
