### ISSUE TITLE
Can't compile with the latest code

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1228]
As title. Nebula throws an error when I run the command `make`.
![image](https://user-images.githubusercontent.com/42762957/68373045-fb2fae80-017c-11ea-9257-eb5dc4cf9324.png)

**Comment by whitewum** [comment]
please provide commit id

**Comment by Amber1990Zhang** [comment]
> please provide commit id

![image](https://user-images.githubusercontent.com/42762957/68374205-667a8000-017f-11ea-9155-41bf242a6214.png)

**Comment by Amber1990Zhang** [comment]
> please provide commit id

![image](https://user-images.githubusercontent.com/42762957/68376717-063a0d00-0184-11ea-8fa1-eb4fcb4d3f0b.png)

**Comment by Amber1990Zhang** [comment]
commit e0e2530ca00c1d35a67ea407b80668a8cff8ed9b
Author: zhangguoqing <zhangguoqingas@gmail.com>
Date:   Thu Nov 7 13:46:31 2019 +0800

    Support "show parts" command (#1086)

    close #930
