### ISSUE TITLE
The scripts to manage process is not useful.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#1229]
**Describe the bug(__must be provided__)**

`./scripts/nebula.service stop all` don't work in fact.
```bash
[root@901edd6d2bee nebula]# ./scripts/nebula.service status all
[INFO] nebula-metad: Exited
[INFO] nebula-graphd: Exited
[INFO] nebula-storaged: Exited
[root@901edd6d2bee nebula]# ps -aux | grep nebula
root      4774  2.5  0.0 1484700 41376 ?       Ssl  08:25   0:30 /usr/local/nebula/bin/nebula-metad --flagfile /usr/local/nebula/etc/nebula-metad.conf
root      4846  0.5  0.0 971764 32820 ?        Ssl  08:25   0:06 /usr/local/nebula/bin/nebula-graphd --flagfile /usr/local/nebula/etc/nebula-graphd.conf
root      8222  0.0  0.0   9104   872 pts/0    S+   08:45   0:00 grep --color=auto nebula
[root@901edd6d2bee nebula]# ps -aux | grep nebula
root      4774  2.4  0.0 1484700 41380 ?       Ssl  08:25   0:31 /usr/local/nebula/bin/nebula-metad --flagfile /usr/local/nebula/etc/nebula-metad.conf
root      4846  0.5  0.0 971764 32984 ?        Ssl  08:25   0:06 /usr/local/nebula/bin/nebula-graphd --flagfile /usr/local/nebula/etc/nebula-graphd.conf
root      8224  0.0  0.0   9104   856 pts/0    S+   08:46   0:00 grep --color=auto nebula
[root@901edd6d2bee nebula]# 
```

**Your Environments(__must be provided__)**

vesoft/nebula-dev:latest

**How To Reproduce(__must be provided__)**
1.`./scripts/nebula.service start all`
2.`./scripts/nebula.service stop all`

**Expected behavior**

All process are killed.

**Additional context**

**Comment by Amber1990Zhang** [comment]
Please run the `ps -aux | grep nebula` seconds later after the processes are killed.

**Comment by critical27** [comment]
stop is not kill -9, just kill, it would take while to quit.

**Comment by porscheme** [comment]
Nebula Cluster: v3.2.0

We are getting below error when trying to check the status of Nebula services.
```
[root@nebula-cluster-storaged-0 nebula]# sh scripts/nebula.service -v status all
/usr/local/nebula/scripts/utils.sh: line 159: /usr/local/nebula/bin/nebula-metad: No such file or directory
☺☻[ERROR]☺☻ /usr/local/nebula/etc/nebula-metad.conf not found
```

**Step to reproduce**
- List all the pods of Nebula Service by running below command
```
kubectl get pods <Nebula_K8S_Namespace>
```
- Log on to any storaged pod by running below command
```
kubectl exec -it <Any_Nebula_Storage_Pod> -n <Nebula_K8S_Namespace> -- bash
```

- Run nebula.service script to repro the error
```
cd /usr/local/nebula
./scripts/nebula.service -v status all
```

**Comment by wey-gu** [comment]
> Nebula Cluster: v3.2.0
> 
> 
> 
> We are getting below error when trying to check the status of Nebula services.
> 
> We followed this [documentation](https://docs.nebula-graph.io/3.2.0/2.quick-start/5.start-stop-service) to test
> 
> 
> 
> ```
> 
> [root@nebula-cluster-storaged-0 nebula]# sh scripts/nebula.service -v status all
> 
> /usr/local/nebula/scripts/utils.sh: line 159: /usr/local/nebula/bin/nebula-metad: No such file or directory
> 
> ☺☻[ERROR]☺☻ /usr/local/nebula/etc/nebula-metad.conf not found
> 
> ```
> 
> 
> 
> **Step to reproduce**
> 
> - List all the pods of Nebula Service by running below command
> 
> ```
> 
> kubectl get pods <Nebula_K8S_Namespace>
> 
> ```
> 
> - Log on to any storaged pod by running below command
> 
> ```
> 
> kubectl exec -it <Any_Nebula_Storage_Pod> -n <Nebula_K8S_Namespace> -- bash
> 
> ```
> 
> 
> 
> - Run nebula.service script to repro the error
> 
> ```
> 
> cd /usr/local/nebula
> 
> ./scripts/nebula.service -v status all
> 
> ```
> 
> 
> 
> - List files in /usr/local/nebula/etc directory and notice only nebula-storaged.conf file present
> 
> ```
> 
> [root@nebula-cluster-storaged-0 nebula]# cd /usr/local/nebula/etc/
> 
> [root@nebula-cluster-storaged-0 etc]# ls
> 
> nebula-storaged.conf
> 
> ```
> 
> 
> 
> 

@porscheme the script is for binary package/deb/rpm not for container deployment.
