### ISSUE TITLE
Strengthen Update vertex/edge function

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#1232]
**Describe the bug(__must be provided__)**
Currently, `Update` vertex/edge function exists the following problems:
* Update  syntax doesn't support `now()` function
* Updating the no-existing properties or no-existing tag doesn't cause an error message
* Updating a no-existing vertex doesn't cause an error message

**Comment by zhangguoqing** [comment]
OK, I will fix it as soon as possible.
