### ISSUE TITLE
Client examples and a RESTful interface

### ISSUE THREAD

**Issue by doublex** [vesoft-inc/nebula#1245]
The nebula-docs are very clear. What would help using nebula:
* some client examples (we use C++)
* a RESTful interface (best: `http2` multiplexed over a single connection)

**Comment by Amber1990Zhang** [comment]
Thanks for your suggestion we're working on it.

**Comment by doublex** [comment]
Thanks a lot!
We could test `nebula` using the CLI interface (it looks very promising).

**Comment by whitewum** [comment]
Currently (RC2), go & python clients are available.  C++/Java clients will be released due to Dec. And I think REST will be later.

If you are trying by C++, you can take an example from CLI.

**Comment by doublex** [comment]
@whitewum 
Great news

**Comment by whitewum** [comment]
> @whitewum
> Great news

You can find roadmap at https://github.com/vesoft-inc/nebula/wiki

BTW, can you star Nebula if you like it?

**Comment by doublex** [comment]
Of course I like Nebula.    :+1: 
Your database is unique. Fast, slim, written in C++.
Only features you need (a graph database is always a secondary database)
