### ISSUE TITLE
I hope to support more dsl languages, such as sql

### ISSUE THREAD

**Issue by chinawangyu** [vesoft-inc/nebula#1254]
I am using the graphics database for the first time.  

I try to learn to use it, in our user network. But I found that I still have to learn a specific dsl language.   I think if our nebula can support similar sql, I think I will use it more easily.

Thank you for your open source product.

**Comment by whitewum** [comment]
The Nebula query language is similar to SQL (group by, order by, etc). But I admit that there are some differences, e.g., GO/MATCH, Pipe)

I think the most frequently used statements are:

GO - graph traverse
FETCH - GET PROPERTY
PIPE(|)  - statements composition
