### ISSUE TITLE
can't change log severity level with commands in doc

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1258]
![image](https://user-images.githubusercontent.com/42762957/68638493-b1f4ab80-053c-11ea-8a5a-dbe1968b674a.png)
![image](https://user-images.githubusercontent.com/42762957/68638524-ccc72000-053c-11ea-9e8a-fc49144a6a3b.png)
All the processes are running, but can't change the log level with commands, will modify the config files work in the same way?

**Comment by whitewum** [comment]
can't reproduce.

**Comment by whitewum** [comment]
please reopen if you can reproduce it.
