### ISSUE TITLE
Will nebula support ID number in `SHOW SPACES` and `DESCRIBE TAG/EDGE`?

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1259]
I noted that nebula supports showing ID in show tags and edges in #1206, will it support ID number in `SHOW SPACES` and `DESCRIBE TAG/EDGE` as well?

**Comment by darionyaphet** [comment]
Maybe we should support ID in  `SHOW SPACES `.  `DESCRIBE TAG/EDGE` I'm not sure.
