### ISSUE TITLE
Where is the nebula configuration file set? 

### ISSUE THREAD

**Issue by zdYng** [vesoft-inc/nebula#1296]
How to set the port number, ip address, user name and login password in the configuration file？
I haven't found the configuration file yet.

**Comment by Amber1990Zhang** [comment]
Are you using Docker or source code?
`For source code`
You can find the configuration files in directory `/usr/local/nebula/etc`
![image](https://user-images.githubusercontent.com/42762957/69215132-cf142480-0ba3-11ea-8e9f-4538edb6531e.png)
You can find the default port number and ip address here.

**Comment by zdYng** [comment]
yes,
I found it！
Just the configuration file is very strange here.

**Comment by zdYng** [comment]
These files can be copied to the outside of docker and then mapped to the etc in the docker.

**Comment by zdYng** [comment]
I suggest that you can put the ips in these configuration files together, it will be a lot easier.

**Comment by Amber1990Zhang** [comment]
> I suggest that you can put the ips in these configuration files together, it will be a lot easier.

Thanks for your kind suggestion.

**Comment by zdYng** [comment]
Meta Server：x.x.x.x:45500，
local port 3699
--ws_http_port=13000
--ws_h2_port=13002
Excuse me, docker is not the main need to open 3699 to the external client side call just fine

**Comment by yixinglu** [comment]
@zdYng 

Yes, you can connect to graph server by above `32868` port. And if you don't want to change the port each time, you can update the port exported format of  `graph` service in `docker-compose.yaml` file like:

```yaml
services:
  ...
  graphd:
     ports:
        - "3699:3699"
```

Then you can always use `3699` to access nebula later.

**Comment by yixinglu** [comment]
I will improve this docker compose configuration, always to export `3699` port. Thanks for your feedback.

**Comment by zdYng** [comment]
thx ：）

**Comment by yixinglu** [comment]
> thx ：）

Fixed it in https://github.com/vesoft-inc/nebula-docker-compose/pull/20
