### ISSUE TITLE
Java graph client compilation failed

### ISSUE THREAD

**Issue by zhangguoqing** [vesoft-inc/nebula#1297]
The git log commit id is  5ace754b6d64ca94e2511ad228581549e6182c7c
[root@xxx java]# pwd
/path/nebula/src/client/java
[root@xxx java]# mvn clean package
....  ....
....  ....
![image](https://user-images.githubusercontent.com/5643942/69220439-f1ac3a80-0baf-11ea-9d82-5eeab6e7586a.png)

Should we add unit testing for java-related code by `make test`?

**Comment by jude-zhu** [comment]
java client move to  https://github.com/vesoft-inc/nebula-java

**Comment by jude-zhu** [comment]
check guava version under your `.m2/repository/com/google/guava/guava` dir, is 27.0.1-jre inclued?
since version 20, `getHost()` is used instead of `getHostText()`
