### ISSUE TITLE
Storaged process is running, but 44500 port is not be listened for a long time

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#1315]
**Describe the bug(__must be provided__)**
(1). I start services, and the storaged 44500 port is not been listened:
![image](https://user-images.githubusercontent.com/38901892/69408468-e7ba4100-0d41-11ea-946a-a5f424b28a52.png)
(2). loop up the listening port, and port 44500 is not in the listening list:
```bash
ss -lntp | grep nebula
```
![image](https://user-images.githubusercontent.com/38901892/69408525-19330c80-0d42-11ea-896e-16daea395acb.png)
(3). 
![image](https://user-images.githubusercontent.com/38901892/69408603-51d2e600-0d42-11ea-876d-dc20dcb6d807.png)
(4).
![image](https://user-images.githubusercontent.com/38901892/69408726-8181ee00-0d42-11ea-9dd2-ddefc90e3c85.png)

**Your Environments(__must be provided__)**
  on the test machine root@192.168.8.205

**Comment by Shylock-Hg** [comment]
I don't think your log information indicate the 44500 is not listened by storaged, try `lsof -i:44500`?

**Comment by jievince** [comment]
> I don't think your log information indicate the 44500 is not listened by storaged, try `lsof -i:44500`?

I am sure 44500 port has not listened for a long time. I execute `lsof -i:44500` and it has no output.
