### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ouzensang** [vesoft-inc/nebula#1316]
**Describe the bug(__must be provided__)**
I deploy Nebula on a cluster of 3 machines(Centos7), when I import data from csv by using https://github.com/vesoft-inc/nebula-importer. I met some error info, but I can't find any solution to solve it. 

**Your Environments(__must be provided__)**
  * OS: Centos7.6
  * Compliler: gcc version 4.8.5
  * CPU: 

**How To Reproduce(__must be provided__)**
  1. deploy Nebula cluster
  2. define config
  3. run command to import data

**Expected behavior**
Import csv files successfully

**Additional context**
My config file: 
[config.txt](https://github.com/vesoft-inc/nebula/files/3878623/config.txt)
My command:
go run importer.go --config ../example/config.txt
My error:
![image](https://user-images.githubusercontent.com/30515579/69410766-a5dfc980-0d46-11ea-836f-b6f97aa9d113.png)

**Comment by jievince** [comment]
![image](https://user-images.githubusercontent.com/38901892/69411790-95305300-0d48-11ea-9b18-d65ee48bb2dc.png)
The config file format is .yaml(config.txt is wrong)and make sure you have the right config.yaml in the path that --path appoints to.

**Comment by ouzensang** [comment]
@jievince Thanks for your kindly advice! I know the config file format is .yaml, but .yaml file can't upload to this issue, so I change its format. But actually I run it in a correct formal like this...
![image](https://user-images.githubusercontent.com/30515579/69416347-65d21400-0d51-11ea-86d4-1c3d84a334e0.png)

**Comment by whitewum** [comment]
some possible solutions:

## 1 check log

can you paste some log message:
the importer log can  be found in `logPath: ./err/test.log`
the server log can be found in `/usr/local/nebula/log/nebula-graphd.INFO`


## 2 check schema
the `E_SYNTAX_ERROR` looks like your csv file schema is inconsistent with server side. 

Can you run the nebula console to verify your schema is correct.
```
/usr/local/nebula/bin/nebula -u user -p password
> use xxx --- your space name, maybe test
> describe tag tag_xxx_name  --- your tag name
```
and 
```
head your_csv_file
```
to make sure the csv file, the `config.yaml`, and your server side schema are consistent with each other.

## 3  we chart

You are welcome to add we chart friend `NebulaGraphBot`. So we can contact you to help.

**Comment by whitewum** [comment]
Thank you for your report.

**Comment by yixinglu** [comment]
Hi @ouzensang , I have checked your configuration file and don't find any syntax errors. So, I guess the problem you are experiencing should be that the order of the props of the schema in configuration file is inconsistent with the order of the data columns in the csv file.

**Comment by ouzensang** [comment]
@whitewum Thanks for your kindly reply! :)
Actually, there is no some special info in its logs.
1. the info in the importer log is :2019/11/23 16:20:30 cmd.go:25: Finish import data, consume time: 0.00s
2. the file /usr/local/nebula/logs/nebula-graphd.INFO is empty
3. my schema
![image](https://user-images.githubusercontent.com/30515579/69476049-c162d700-0e0f-11ea-9de4-bb180ca1abc4.png)
my data file
![image](https://user-images.githubusercontent.com/30515579/69476053-d50e3d80-0e0f-11ea-8f73-cab2a87a2669.png)

When I first read the doc of nebula-importer, I can't understand the preparation work "Schema is created" whether means I need to create this schema in Nebula shell first, so I didn't create it.
I thought maybe I need to define the schema of data first. But when I create it successfully and reimport my data, the same error still exists. So I have some questions:
1. Whether the identified id of data need to be defined in the schema or config file. Actually, I didn't define it.
2. Whether there are some keywords that user can't use to define attributes.
3. The parameter "concurrency" whether  means the number of machines in cluster and "address" whether is the address of one machine in cluster.

I even change the order of data file in the file, but the same error still exists.  =.=

**Comment by ouzensang** [comment]
When I ran the example which nebula-importer provided, I met the same error. And I just changed the address parameter in th config file.
![image](https://user-images.githubusercontent.com/30515579/69476441-df7f0600-0e14-11ea-9fdf-874ef65cd434.png)

**Comment by whitewum** [comment]
## 1.

There might be some new changes in the nebula-importer (or the configuration and sample files). So @yixinglu please check them again. Sorry for the inconvenient. 

## 2. possbile solution

I think there might be an inconsistency  between  your csv file (comment.csv) and graph schema:

you have **8** columns in the csv file:
```
(8122360, 9, 4947802324993, 2011-08-17....
```
but **7** columns in the graph schema (by `>descible tag comment`), and **7** columns in the `config.yaml`

```
lable:int, id:string, creationDate:string
```

I think the first column `e.g, 8122360` is your **identified_id**, so the schema might be as follows:

```plain
             - identified-id
                type: int
             - name: label
                type: int
              - name: id
                type: string
              - name: creationDate
                type: string
......
```

And you can recreate a new space, with tTAG `comment` sth like:

```ngql
nebula> CREATE TAG course(identified-id int, label int, id string, creationDate string ....)
```

Besides, I suggest you to test only one file (e.g. `comment.csv`) first.

## Answers to your questions:

1. Whether the identified id of data need to be defined in the schema or config file. Actually, I didn't define it.

csv file without header: YES. -- There must be a column of identified-id in the csv file (and also in the graph schema definition)

1. Whether there are some keywords that user can't use to define attributes.

Yes. there are some reserved keywords to name an attribute. But the namings in your `config.yaml` looks good. (`id` is not a reserved keywords. but 'timestamp', 'int', etc, are keywords.)

1. The parameter "concurrency" whether means the number of machines in cluster and "address" whether is the address of one machine in cluster.

in your `config.yaml`, (`  concurrency: 3 # number of graph clients`), it means there are three writing-threads to write to the server(192.168.2.9:3699).

## P. S .

We're working on a web UI to improve the importer progress. The config.yaml and command line are quite error-prone.
@nianiaJR

**Comment by whitewum** [comment]
## 1. Sorry for the inconvenient. 

There might be some new changes in the nebula-importer (or the configuration and sample files). So @yixinglu @wilsonyou  please check them again ( the code, the md, the csv, etc). 

## 2. possible solution

to open log:

```
> curl "http://127.0.0.1:13000/set_flags?flag=v&value=2"
> curl "http://127.0.0.1:13000/set_flags?flag=minloglevel&value=0"
```

to close log 

```
> curl "http://127.0.0.1:13000/set_flags?flag=v&value=0"
> curl "http://127.0.0.1:13000/set_flags?flag=minloglevel&value=1"
```



can you try to import the `comment.csv` first. 

## Answers to your questions:


1. Whether there are some keywords that user can't use to define attributes.

Yes. there are some reserved keywords to name an attribute. But the namings in your `config.yaml` looks good. (`id` is not a reserved keywords. but 'timestamp', 'int', etc, are keywords.)

1. The parameter "concurrency" whether means the number of machines in cluster and "address" whether is the address of one machine in cluster.

in your `config.yaml`, (`  concurrency: 3 # number of graph clients`), it means there are three writing-threads to write to the server(192.168.2.9:3699).

## P. S .

We're working on a web UI to improve the importer progress. The config.yaml and command line are quite error-prone.
@nianiaJR

**Comment by ouzensang** [comment]
@whitewum Thanks for your help! :)

**Comment by wilsonyou** [comment]
@ouzensang Please refer to the following link which provides step-by-step guide to import csv files:
https://github.com/wilsonyou/nebula/blob/importer2/docs/manual-EN/1.overview/2.quick-start/4.import-csv-file.md

**Comment by whitewum** [comment]
> @whitewum Thanks for your help! :)

BTW，can you star Nebula if you like it.

**Comment by ouzensang** [comment]
@wilsonyou Thanks for your kindly help! 
I reinstalled the newest version of Nebula and imported example data successfully :). I will try to import my own data again!

**Comment by ouzensang** [comment]
@whitewum No problem! I have solved my problem successfully! Thank you again! :)

**Comment by whitewum** [comment]
> @wilsonyou Thanks for your kindly help!
> I reinstalled the newest version of Nebula and imported example data successfully :). I will try to import my own data again!

You are welcome to contact us for any questions.

**Comment by wilsonyou** [comment]
@ouzensang No problem. Glad to hear that you made it! Congratulations!
