### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1320]
![image](https://user-images.githubusercontent.com/13991775/69477534-5373db00-0e22-11ea-8e48-0a71907beada.png)

nebula-storaged.conf：
![image](https://user-images.githubusercontent.com/13991775/69477680-fe38c900-0e23-11ea-85de-1d8ef3685663.png)

partition：
CREATE SPACE test(partition_num=1024, replica_factor=1);

edge：
100 million

**Your Environments(__must be provided__)**
  * OS: CentOS Linux release 7.4.1708

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/69478512-5674c880-0e2e-11ea-893b-f6b7c1af8169.png)

**Comment by whitewum** [comment]
This is due to raft memory usage.

**Comment by zhangguoqing** [comment]
> This is due to raft memory usage.

nebula-storaged.conf  FYI.
```
--part_man_type=memory
--part_type=simple
```

**Comment by critical27** [comment]
See #1324, we have adjust default memory usage.
