### ISSUE TITLE
server crashes.

### ISSUE THREAD

**Issue by lgaren** [vesoft-inc/nebula#1325]
Scheme :  

create space test_space ; 
use test_space ;
create tag tag1(prop1 int, prop2 string , prop3 timestamp) ;
create tag tag2(prop1 int , prop2 string , prop3 double , prop4 int , prop5 int );
create tag tag3(prop1 int , prop2 string , prop3 string ,prop4 string, prop5 string );
create edge edge1(prop1 string , prop2 int); 
create edge edge2(); 
create edge edge3(); 

NGQL : 

 GO  FROM 1000002563422 ,1000013327874 ,1000019030185 ,1000022051769  OVER edge1 WHERE edge1._rank >= 20191109 AND edge1._rank < 20191118 YIELD  $^.tag1.prop1 AS tag1_prop1  , $^.tag1.prop2 AS tag1_prop2  , $^.tag1.prop3 AS tag1_prop3  ,edge1.prop1 AS edge1_prop1  ,edge1.prop2 AS edge1_prop2  ,$$.tag2.prop1 AS tag2_prop1  ,$$.tag2.prop2 AS tag2_prop2  ,$$.tag2.prop3 AS tag2_prop3  ,$$.tag2.prop4 AS tag2_prop4  ,$$.tag2.prop5 AS tag2_prop5  ,edge1._dst  AS tag2_vid |  GO  FROM $-.tag2_vid OVER edge2 YIELD $-.tag1_prop1 ,$-.tag1_prop2 ,$-.tag1_prop3 ,$-.edge1_prop1 ,$-.edge1_prop2 ,$-.tag2_prop1 ,$-.tag2_prop2 ,$-.tag2_prop3 ,$-.tag2_prop4 ,$-.tag2_prop5 ,$$.tag3.prop1 AS tag3_prop1  ,$$.tag3.prop2 AS tag3_prop2  ,$$.tag3.prop3 AS tag3_prop3  ,$$.tag3.prop4 AS tag3_prop4  ,$$.tag3.prop5 AS tag3_prop5  | yield  $-.tag1_prop1 ,$-.tag1_prop2 ,$-.tag1_prop3 ,$-.edge1_prop1 ,$-.edge1_prop2 ,$-.tag2_prop1 ,$-.tag2_prop2 ,$-.tag2_prop3 ,$-.tag2_prop4 ,$-.tag2_prop5  where $-.tag1_prop1 > 111

ERROR:
E1125 07:22:23.436230  1553 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.
[ERROR (-3)]:

执行这个查新会导致 nebula-graphd 服务死掉；

docker 镜像是  11月25号的镜像

**Comment by whitewum** [comment]
Got it
@CPWstatic

**Comment by CPWstatic** [comment]
We had implement the YIELD sentence in pr#745 which was merges on 30 Oct. Please try the latest version.
