### ISSUE TITLE
Download hdfs-file failed.

### ISSUE THREAD

**Issue by tong-hao** [vesoft-inc/nebula#1336]
**Describe the bug(__must be provided__)**
It's failed when I executed the following cmd.
```
DOWNLOAD HDFS "hdfs://localhost:9000/tmp/test/10";
```
Latter on. I try it again. It's success.

![Screenshot from 2019-11-26 15-52-06](https://user-images.githubusercontent.com/28890406/69612898-94aafb80-106b-11ea-8d36-fce2214d5f94.png)

Log：
```
E1126 16:09:46.415304 16650 StorageHttpDownloadHandler.cpp:173] Can't found space: 1, part: 1
E1126 16:09:46.415304 16651 StorageHttpDownloadHandler.cpp:173] Can't found space: 1, part: 2

```

**Your Environments(__must be provided__)**
  * OS: ubuntu 1804
  * Compliler: g++ (GCC) 8.2.0
  * CPU: `lscpu`

**How To Reproduce(__must be provided__)**

**Expected behavior**

**Additional context**

**Comment by Shylock-Hg** [comment]
A newly started server?

**Comment by dangleptr** [comment]
Please take a look  @darionyaphet
