### ISSUE TITLE
Ingest Failed: Not implemented: Files have overlapping ranges

### ISSUE THREAD

**Issue by tong-hao** [vesoft-inc/nebula#1337]
**Describe the bug(__must be provided__)**
I executed `DOWNLOAD HDFS "hdfs://localhost:9000/tmp/test/10"` successfully.
And then, I executed `ingest`. It's failed.

LOG:
```
RocksEngine.cpp:366] Ingest Failed: Not implemented: Files have overlapping ranges
```

May be our racksdb cannot implement this feature.
https://github.com/facebook/rocksdb/pull/5539

**Your Environments(__must be provided__)**
  * OS: ubuntu 1804
  * Compliler: g++ (GCC) 8.2.0
  * CPU: `lscpu`

**Comment by Amber1990Zhang** [comment]
What is your data size?  If you have a large dataset, `INGEST` will block RocksDB, please avoid running the command at requirement peak. Let me know if this reply helps you.

**Comment by tong-hao** [comment]
The num of vertex and edge is less than 100.  
[download.tar.gz](https://github.com/vesoft-inc/nebula/files/3890964/download.tar.gz)

**Comment by dangleptr** [comment]
we have fixed it in #1265
could you retry with the master branch?

**Comment by tong-hao** [comment]
I reinstalled  it. And I executed `ingest` successfully.
But I cannot fetch anything by my vertex id.

**How many vertexes and edges are ingested?
How do I fetch vertexes or edges without id?**

```
(user@127.0.0.1) [idmapping]> ingest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    27  100    27    0     0   1500      0 --:--:-- --:--:-- --:--:--  1588
Execution succeeded (Time spent: 50233/50966 us)

(user@127.0.0.1) [idmapping]> fetch prop on pin 3681517981201367768;
Execution succeeded (Time spent: 4429/5350 us)
```

**Comment by tong-hao** [comment]
The data of download still exist after I executed `ingest`.

```
root@ht-dev:/usr/local/nebula# ll data/storage/nebula/9/download/1/
总用量 16
drwxr-xr-x 2 root root 4096 11月 27 14:29 ./
drwxr-xr-x 4 root root 4096 11月 27 14:29 ../
-rw-r--r-- 1 root root  800 11月 27 14:29 edge-01000000D882B82F1961173301000040FFFFFFFFFFFFFFFF1AB4D4B4078F17080100000000000000.sst
-rw-r--r-- 1 root root  820 11月 27 14:29 vertex-010000001AB4D4B4078F1708010000000100000000000000.sst


root@ht-dev:/usr/local/nebula# ll data/storage/nebula/9/download/2
总用量 16
drwxr-xr-x 2 root root 4096 11月 27 14:29 ./
drwxr-xr-x 4 root root 4096 11月 27 14:29 ../
-rw-r--r-- 1 root root  749 11月 27 14:29 edge-01010000F187B82F1964173301000040FFFFFFFFFFFFFFFF2D22BDB40718FC070100000000000000.sst
-rw-r--r-- 1 root root  781 11月 27 14:29 vertex-010100002D22BDB40718FC07010000000100000000000000.sst
```

**Comment by darionyaphet** [comment]
Could you check the schema ? Is the field consistent ?

**Comment by tong-hao** [comment]
I got it.

partitionId = vertexId % partitionNum  + 1;
