### ISSUE TITLE
Duplicate spaces created when running jepsen test

### ISSUE THREAD

**Issue by wfystx** [vesoft-inc/nebula#1352]
This issue happened when I run Jepsen test.   
The first step I did was to create a space for the test. But because it was in Jepsen framework, the create command was executed more than one time. As the result, two spaces with the same name "test" were created.  
Screenshot is attached.  
![20191128160701](https://user-images.githubusercontent.com/37495301/69788355-4a578500-11f9-11ea-9cb9-67a03fe65e81.jpg)

**Comment by whitewum** [comment]
> use test; 
what happend.

**Comment by Amber1990Zhang** [comment]
If you want to create a space that already existed, the right thing is nebula reminds you of "Space XXX already existed!"

**Comment by wfystx** [comment]
> > use test;
> > what happend.

That would success. as the pic shows:
<img width="343" alt="屏幕快照 2019-11-29 上午9 59 29" src="https://user-images.githubusercontent.com/37495301/69838550-044d0080-128f-11ea-911d-d672e12fd02a.png">

And if I "desc space test", it gives me the information of the second one

**Comment by wfystx** [comment]
> If you want to create a space that already existed, the right thing is nebula reminds you of "Space XXX already existed!"

Yeah I know, this problem is happened when Jepson runs the same "create" command at nearly the same time many times.

**Comment by Shylock-Hg** [comment]
#1356 
Maybe caused by this issue. The One CreateSpace request process function exit but the `id` not insert(async) before the follow CreateSpace request so there are one space name with different `id`(automatic generate) finally.

**Comment by Shylock-Hg** [comment]
#1356 
Maybe caused by this issue. The One CreateSpace request process function exit but the `name` not commit to db(async) before the follow CreateSpace request so there is one space name with different `id`(automatic generate) finally.
