### ISSUE TITLE
Storaged latency increased by 10 times when importing csv data

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#1357]
I use nebula-importer to import 210 million data to the nebula cluster. The cluster has 3 hosts, each of them starts all three services. When I first import the data, the latency is about 13ms. When importing finished, I use curl to force flush and compact just on one of the host of the cluster. Because the data has no duplicate data, the compact op has no effect. So I didn't do the compact op on other two host of the cluster. Then, I use nebula-importer to import the same data, the latency becomes to  180ms.

**Comment by jude-zhu** [comment]
#1837
