### ISSUE TITLE
change reverse query to return the source vertex of the edge

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1358]
vertexA -> [relationship] -> vertexB

Without specifying the return props, `Go from vertexB over relationship reversely;` returns the dst of the edge, which is vertexB. Should we return the src of the edge for the reverse query?

![1](https://user-images.githubusercontent.com/51590253/69854832-08941080-12c5-11ea-841a-f4893990cf08.jpg)

**Comment by ffisherr** [comment]
@jude-zhu, can i help with this issue? Seems pretty easy. I'm new to this project, so, what should i start with?

**Comment by Shylock-Hg** [comment]
> @jude-zhu, can i help with this issue? Seems pretty easy. I'm new to this project, so, what should i start with?

Welcome of course. You can solve any issue you want if nobody assigned.
I think you should read the nGQL syntax from the `docs` first.
