### ISSUE TITLE
go from vid over *  reversely leads graphd server to crash

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#1364]

**Comment by jievince** [comment]
logs/nebula-graphd.ERROR
```
Log file created at: 2019/12/02 16:16:12
Running on machine: localhost.localdomain
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1202 16:16:12.468133 39624 GoExecutor.cpp:1316] Check failed: iter != edges_.end()
```

**Comment by Amber1990Zhang** [comment]
go from vid over edge1, edge2
go form vid over *
both works. So I guess it's the `REVERSELY` that matters.

**Comment by jievince** [comment]
In my test, ` go from hash("叶莉") over relation reversely` works well, while `go from hash("叶莉") over reversely` will lead graphd server to crash.

**Comment by Amber1990Zhang** [comment]
![image](https://user-images.githubusercontent.com/42762957/69945319-4642a480-1524-11ea-9e6f-74a12fd1313d.png)
