### ISSUE TITLE
Takes too much hard disk space

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1375]
![image](https://user-images.githubusercontent.com/13991775/70124879-aa926f00-16b0-11ea-9b80-73ecb1a5ba00.png)

partition_num=100
replica_factor=1

**Comment by whitewum** [comment]
dynamically change wal_ttl

**Comment by Shylock-Hg** [comment]
> dynamically change wal_ttl

The WAL seems only cleaned when partition start.
