### ISSUE TITLE
insert tag(timestamp) return wrong status message

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#1386]
![image](https://user-images.githubusercontent.com/38901892/70302893-2a4b4580-1839-11ea-99f2-b327cb3a8c04.png)

**Comment by Amber1990Zhang** [comment]
```
nebula> INSERT VERTEX hello(time) VALUES 205:("1970-XXXXXXXXXXXXXX22:35:57")
[ERROR (-8)]: OK
```
Thanks for reporting. As we can see, inserting wrong data type returns wrong ERROR MESSAGE which should not have happened here. Suggestion: `Wrong data type!`.

**Comment by Amber1990Zhang** [comment]
In fact, if you insert wrong data types, all the ERROR MESSAGE is OK here.

**Comment by Shylock-Hg** [comment]
Yes, a bug in InsertVertex that return the mistake status.

**Comment by laura-ding** [comment]
#1399 has resolved it
