### ISSUE TITLE
[UT Failed] 20:40:38 	 82 - snapshot_command_test (Failed)

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#1390]
http://ci.vesoft.com/job/Nebula-Graph-UnitTest/3078/console

**Comment by bright-starry-sky** [comment]
This is an unstable test cases. This problem occurs if `wal` file does not exist when create hard link for wal.  Let me stabilize it.

**Comment by bright-starry-sky** [comment]
#1391 will be fix this unstable test case.

**Comment by Shylock-Hg** [comment]
> This is an unstable test cases. This problem occurs if `wal` file does not exist when create hard link for wal. Let me stabilize it.

It seems caused by the snapshot data folder already exist according to the log of testing?

**Comment by jude-zhu** [comment]
relate to #1391
