### ISSUE TITLE
[doc] doc of Storage Metrics needs to be updated

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1396]
Actually, metrics of storage have a prefix, which is "storage_".

https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md

![1](https://user-images.githubusercontent.com/51590253/70402391-29e7c000-1a6e-11ea-8648-b74cec8aebc3.png)

**Comment by Amber1990Zhang** [comment]
Thanks for your kind mention, pr WIP now.

**Comment by Amber1990Zhang** [comment]
#1406
