### ISSUE TITLE
uuid doesn't support chinese value

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#1398]
![image](https://user-images.githubusercontent.com/12572857/70402814-a038f200-1a6f-11ea-8ebe-1829383ff914.png)

**Comment by Shylock-Hg** [comment]
Seems not caused by chinese characters according to my testing. Which version are you using?

**Comment by zlcook** [comment]
> Seems not caused by chinese characters according to my testing. Which version are you using?

This problem is unreasonable, Hold on, I will try to give more details.
