### ISSUE TITLE
Make the testing executable dynamic linking.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#1401]
**Is your feature request related to a problem? Please describe.**
The testing executables disk consumption is too large to development and CI/CD.

**Describe the solution you'd like**
Make testing dynamic link.

**Describe alternatives you've considered**

**Additional context**
Block the coverage because the action disk consumption over.

**Comment by whitewum** [comment]
what's the minimum disk capacity required?

**Comment by dutor** [comment]
> what's the minimum disk capacity required?

#1332 reduces the build size from 28GB to about 5GB, in the _Debug_ mode.

**Comment by dutor** [comment]
It is the debug info that makes the executables huge, instead of code:
```
----------------------------------------
_build/nebula-graphd
----------------------------------------
.debug_info                79.5MB  39.2%
.debug_loc                 47.2MB  23.3%
.debug_str                 20.8MB  10.3%
.text                      13.4MB   6.6%
.debug_ranges              11.3MB   5.6%
.debug_line                9.30MB   4.6%
.strtab                    6.45MB   3.2%
.dynstr                    4.29MB   2.1%
.eh_frame                  2.04MB   1.0%
.debug_abbrev              1.79MB   0.9%
.symtab                    1.59MB   0.8%
.rodata                    1.48MB   0.7%
.dynsym                    1.05MB   0.5%
.gcc_except_table           588KB   0.3%
.data.rel.ro                470KB   0.2%
.eh_frame_hdr               372KB   0.2%
.gnu.hash                   338KB   0.2%
.hash                       308KB   0.1%
.debug_aranges              250KB   0.1%
TOTAL                       203MB 100.0%
----------------------------------------
```

Considering the build size has been reduced a lot in #1332, I will close this issue for now.

BTW. I have to mention that to link third party libraries dynamically could further make the build size smaller( by 15% I guess), but it takes a little more effort, which is not worthy for the time being.
