### ISSUE TITLE
The default value for a property does not work when inserting a vertex

### ISSUE THREAD

**Issue by wilsonyou** [vesoft-inc/nebula#1421]
I created a tag with a default value specified for a property.

When I inserted a new vertex for the tag without providing the property value, the following error occurred:

> (user@127.0.0.1) [(none)]> use nba
> Execution succeeded (Time spent: 786/1236 us)
> 
> (user@127.0.0.1) [nba]> create tag test5(age int DEFAULT 10);
> Execution succeeded (Time spent: 2005359/2005767 us)
> 
> (user@127.0.0.1) [nba]> insert vertex test5(age) values 100:();
> E1211 03:08:55.570917     1 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.
> [ERROR (-3)]:
> (user@127.0.0.1) [nba]>
>

**Comment by Amber1990Zhang** [comment]
I reproduced your issue. 
```(user@127.0.0.1) [liverpool]> insert vertex test5(age) values 101:();
E1211 06:10:51.522341     1 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.
[ERROR (-3)]:
```

**Comment by zhaizhifen** [comment]
(user@127.0.0.1) [nba]> 
(user@127.0.0.1) [nba]> insert vertex player(name,age) values 100:("Tim Duncan", 42)
[ERROR (-8)]: Not exist default value
(user@127.0.0.1) [nba]> 
(user@127.0.0.1) [nba]> 
(user@127.0.0.1) [nba]> desc tag player;
==================
| Field | Type   |
==================
| name  | string |
------------------
| aget  | int    |
------------------
Got 2 rows (Time spent: 1135/2201 us)

(user@127.0.0.1) [nba]> insert vertex player(name,age) values 100:("Tim Duncan", 42)
[ERROR (-8)]: Not exist default value
(user@127.0.0.1) [nba]> 
(user@127.0.0.1) [nba]>

**Comment by laura-ding** [comment]
@zhaizhifen, your schema `player`’s column name is `aget` not `age`.

**Comment by laura-ding** [comment]
Fixed, closed
