### ISSUE TITLE
Execute error msg: Internal Error

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1426]
Execute error msg: Internal Error

**Comment by Shylock-Hg** [comment]
Could provide the error log or how to reproduce ?

**Comment by ownthink** [comment]
我在群里说了哈，灵异事件github不太好描述。

**Comment by Shylock-Hg** [comment]
```
E1211 17:12:05.233289 32228 InsertEdgeExecutor.cpp:239] Insert edge failed, error -16, part 9
```

**Comment by dangleptr** [comment]
I have added log for the detail error code in #1427 
You could check the it in the error log of storaged.
