### ISSUE TITLE
虚拟机ubuntu18在构建Debug版本的make过程中出现错误

### ISSUE THREAD

**Issue by doJCHbest** [vesoft-inc/nebula#1429]
#### 再到构建Debug环境的make过程中，出现了以下问题:
![问题](https://user-images.githubusercontent.com/54877997/70620862-45f88680-1c53-11ea-8242-77f720861294.jpg)
#### 请问该如何解决？

**Comment by doJCHbest** [comment]
#### 似乎是因为虚拟机系统容量不够的问题， 扩容了之后可以继续操作QAQ 。

**Comment by Shylock-Hg** [comment]
Duplicate of #1401
