### ISSUE TITLE
Use more detailed cases introduce nGQL

### ISSUE THREAD

**Issue by cmdares** [vesoft-inc/nebula#1441]
In order to better migrate from the gremlin related graph database, I hope that the official can use nGQL syntax to introduce the examples in the gremlin official website reference.
ref:    http://tinkerpop.apache.org/docs/current/reference/
thanks.

**Comment by whitewum** [comment]
Good suggestion.

The full-stack gremlin support is not on our next few months' schedules.

But we can provide some examples and comparisons with the gremlin.

On the other side, nGQL will support OpenCypher in the next releases
