### ISSUE TITLE
请问nebula在单机部署的情况下，最大存储多少结点和边而不会影响查询的效率？

### ISSUE THREAD

**Issue by Qubutol** [vesoft-inc/nebula#1442]
如题所述，在没有多台服务器的情况下，只在一台服务器上部署一个nebula，在不影响查询效率的情况下，最大存储多大的数据量？

**Comment by whitewum** [comment]
1. 如果是单机的话，对硬件有两个建议：1是使用SSD，2是内存：硬盘大约1:5（或者更高）。
1. 一般来说建议使用大约2/3的SSD空间
1.建议数据导入完成后[做compaction](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md)
1.其他对于点和边的数量没有特别限制，并不会影响性能（这个和Neo4j不太一样）
