### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 993526915** [vesoft-inc/nebula#1445]
**错误描述**
根据中文手册命令行运行出现错误

**环境**

* OS: ubuntu18.04
* Compliler: g++ (GCC) 8.2.0
* CPU: Intel® Core™ i7-8550U CPU @ 1.80GHz × 8
* Commit id (c48bcf5)

**步骤**
1.CREATE SPACE myspace_test2(partition_num=1024, replica_factor=1)
2. USE myspace_test2
3.CREATE TAG student(name string, age int, gender string)
4.CREATE EDGE select(grade int)
5. DESCRIBE TAG student
6.INSERT VERTEX student(name, age, gender) VALUES 200:("Monica", 16, "female")

**期望**

显示插入成功

**实际**
(user@127.0.0.1) [myspace_test2]>  INSERT VERTEX course(name, credits),building(name) VALUES 101:("Math", 3, "No5")
[ERROR (-8)]: Internal Error

**Comment by whitewum** [comment]
1. 你可以重试一下
1. `show hosts`
1. `describe tag course`

**Comment by whitewum** [comment]
@Shylock-Hg

**Comment by 993526915** [comment]
还是不行，怎么删除自己创建的space

**Comment by Shylock-Hg** [comment]
这个步骤有误。

**Comment by wilsonyou** [comment]
@993526915 Please refer to this link for a quick start:

https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/1.overview/2.quick-start/1.get-started.md

You can drop your space with the DROP SPACE statement

For example, if you want to drop a space named test, then you can use the following command:

DROP SPACE test;
