### ISSUE TITLE
Support uuid(bussiness_key) in spark

### ISSUE THREAD

**Issue by spacewalkman** [vesoft-inc/nebula#1447]
1. Support using `uuid` expression in vertex & edge  id generation, when business PK field in hive is of non-integer type.
2. Support  string literal prefix to discriminate different hive tables, whose PK fields could have duplicate value.

Consider this:
hive table1 

PK1 | prop1
---|---
abc@abc.com|value1

hive table2 

PK2| prop1 
---|--- 
abc@abc.com|value1

1. PK columns could be non-integer type, we could use `uuid("abc@abc.com")` to generate integer type id 
2. PK1 & PK2 may have duplicated value, When generating id, we use `uuid("table2"+"abc@abc.com")` to keep it unique.

**Comment by Harlan6** [comment]
When generating id, we use uuid an generate same value in PK1 & PK2,  what problem will happen?

**Comment by darionyaphet** [comment]
why PK1 and PK2 generate the same value ?

**Comment by jude-zhu** [comment]
UUID is not supported in v2.x, so I close it.
