### ISSUE TITLE
Product Roadmap 2020 H1

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1454]
• nGQL Features
- [x]  Index (Q1)
- [x] TTL (Q1)
- [x] Support truncate space to delete the data inside a space (Q1)
- [x] bidirectional traversal (Q1)
- [x] Sampling (Q1)
- [x] OpenCypher (Q2) 
- [x] Subgraph (Q2)
- [x] String key (Q2)
- [x] NULL Support (Q2)

• Query Engine
- [x] Profiling (Q2)
- [x] Execution Plan (Q2)

• Storage Engine
- [x] Task Manager (Q2)
- [x] More OLAP Interfaces (Q2)

• Integrations
- [x] Monitor (Q1)
- [x] Kubernetes (Q1)

• SaaS - Nebula Cloud (Q2)
• Nebula Graph Studio 1.1 (Q1)
• Session && ACL (Q1)
• Benchmark (Q1)

Tell us what more you'd like to see happen in 2020!

**Comment by jude-zhu** [comment]
Integrate with Elasticsearch

**Comment by yeliang** [comment]
Algorithm:
 - single-source shortest path
 - multiple-source shortest paths
 - closeness centrality
 - Clustering Coefficient
 - common neighborhood
 - k-core
 - Louvain community detection
 - label propagation
 - weighted label propagation
 - weighted pagerank

**Comment by rebootcode** [comment]
Any possibility for geospatial features and benchmark against dgraph, neo4j database?

**Comment by ansarizafar** [comment]
- Replace RocksDB with more memory efficient KV store.
- Schema definition and migration like EdgeDB https://edgedb.com/docs/edgeql/sdl/index#ref-eql-sdl 
- Real time/Live query support
- Web based Admin UI
- Better documentation

**Comment by whitewum** [comment]
scala client

**Comment by ansarizafar** [comment]
C#  .Net client is required.
