### ISSUE TITLE
Return information is not correct

### ISSUE THREAD

**Issue by wilsonyou** [vesoft-inc/nebula#1478]
I created an edge type named no_property which does not have any properties in Nebula Graph. Then, I inserted one edge for the no_property edge type. Later, I deleted this edge and used the FETCH PROP ON statement to query whether this edge had been deleted.

I expected that the 'Execution succeeded' info would be returned, but the `No props declared` info was returned:

(user@127.0.0.1) [nba]> INSERT EDGE no_property() VALUES 100 -> 101:();
Execution succeeded (Time spent: 662/992 us)

(user@127.0.0.1) [nba]> DELETE EDGE no_property 100 -> 101;
Execution succeeded (Time spent: 648/1671 us)

(user@127.0.0.1) [nba]> FETCH PROP ON no_property 100 -> 101;
[ERROR (-8)]: No props declared.

**Comment by Amber1990Zhang** [comment]
Moreover, if I deleted an edge with no properties, the same error throws also.
![image](https://user-images.githubusercontent.com/42762957/71148283-3b974780-2266-11ea-9b8a-6e5ba5c80cf3.png)
If I deleted an edge with properties, the `FETCH PROP ON` is ok.

**Comment by Amber1990Zhang** [comment]
By the way, the same happens for vertices without properties.

**Comment by Shylock-Hg** [comment]
Return error when no properties maybe not correct response, we'd better return empty result.
