### ISSUE TITLE
floating IP is harmful for nebula raft election 

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1498]
Nebula metad raft election depends on static ips. If ip changes, metad may crash. 
Ip changes is common in cloud environments. In k8s, we can use special cni plugins apply a stable ip for pods.

Maybe we can use Pod domainName for raft election.This is the better way.

**Comment by knightXun** [comment]
@dangleptr

**Comment by critical27** [comment]
This could be a huge project, depends on if we can use rpc by domain + pod.

**Comment by jude-zhu** [comment]
#2113
