### ISSUE TITLE
When graphd fail to resolve dns,It do not exit

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1501]
When graphd init, it will try to resolve metad dns.If dns name fail to resolve, Graphd will not exit. I want graphd restart and retry resolve metad dns name.

**Comment by knightXun** [comment]
/assign knightXun 
@monadbobo @dutor

**Comment by laura-ding** [comment]
Adjust the order in which parameters are initialized and move it to the front of `start WebService`

**Comment by Shylock-Hg** [comment]
> When graphd init, it will try to resolve metad dns.If dns name fail to resolve, Graphd will not exit. I want graphd restart and retry resolve metad dns name.

Seems graphd will exit if resolve failed.

**Comment by laura-ding** [comment]
@Shylock-Hg exit without stop WebService
