### ISSUE TITLE
Output the current datetime whenever the command execution outputs the result

### ISSUE THREAD

**Issue by zhangguoqing** [vesoft-inc/nebula#1518]
As the title, it may easy to track some operations.

**Comment by whitewum** [comment]
in CLI?

**Comment by zhangguoqing** [comment]
> in CLI?

yep, the console prompt!

**Comment by Shylock-Hg** [comment]
> > in CLI?
> 
> yep, the console prompt!

Which time, the machine running console ,  graph or storage?

**Comment by zhangguoqing** [comment]
> machine running console

The machine running console, thx！
