### ISSUE TITLE
DELETE EDGE follow 100 -> 200; ERROR

### ISSUE THREAD

**Issue by gocuntian** [vesoft-inc/nebula#1560]
![image](https://user-images.githubusercontent.com/7857351/71609594-b47e9380-2bc4-11ea-9659-1c2c39100550.png)
(user@127.0.0.1) [nba]> DELETE EDGE follow 100 -> 200;
[ERROR (-7)]: syntax error near `100'

**Comment by Amber1990Zhang** [comment]
Thanks for your issue. Please attach the information of vertices and edge. For example, you can check the vertex 100 with the command `FETCH PROP ON <tag_name> 100` and edge with `FETCH PROP ON follow 100 ->200`.
Do let me know if this works. Thanks.

**Comment by whitewum** [comment]
```
show tags
show edges
```
it looks like edge `follow` doesn't exist.

**Comment by Shylock-Hg** [comment]
Unfortunately, I can't reproduce this issue. Could provide the steps to reproduce this?

**Comment by gocuntian** [comment]
![image](https://user-images.githubusercontent.com/7857351/71617516-67b3b080-2bf6-11ea-88f8-76a1cc2314b5.png)

**Comment by whitewum** [comment]
what's your code version?

**Comment by gocuntian** [comment]
docker run --rm -ti vesoft/nebula-graph bash

**Comment by Shylock-Hg** [comment]
> docker run --rm -ti vesoft/nebula-graph bash

Seems the image not update recently.It's valid in master branch, you can try to build from source.

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/71651009-56cd8100-2d55-11ea-8c42-4f280329d6f6.png)

**Comment by gocuntian** [comment]
Thank you！
