### ISSUE TITLE
 Strange parameter updates

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1611]
I'm using the docker-compose. When I first run the following command, the parameter `storage:rocksdb_column_family_options` is IMMUTABLE. 
![image](https://user-images.githubusercontent.com/42762957/72045774-e3e27e00-32f1-11ea-9473-1b443679ecb2.png)
But when I delete all the data and create a space, it becomes IMMUTABLE
![image](https://user-images.githubusercontent.com/42762957/72045796-f1980380-32f1-11ea-8e66-152a588add8e.png)
I don't think this is logical.

**Comment by Shylock-Hg** [comment]
I think you changed it before. If you delete all data the configuration will be reset when restart.
