### ISSUE TITLE
Docker crashes for no reason

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1612]
I'm using the nebula-compose and web-console docker to try data importing but found docker crashes for no reason.  My mac shows the CPU occupation and the temperature are surprisingly high. It seems nico  @NicolaCage is struggling with the same problem, too.

**Comment by knightXun** [comment]
We use docker to limit nebula cpu/mem usage, If the cpu/mem is overhead the limit, dockerd will kill these containers, And give no error log. you can use `docker events` to see what happened. They will tell some important infomations.
