### ISSUE TITLE
大批量持续插入bug

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1624]
![image](https://user-images.githubusercontent.com/13991775/72253634-f388fc00-363c-11ea-9a49-c66d3d9b472b.png)

![image](https://user-images.githubusercontent.com/13991775/72253648-fbe13700-363c-11ea-875f-b4c07b7564cd.png)

**Comment by knightXun** [comment]
can you provide the steps to reproduce this bug? we will fix this later

**Comment by critical27** [comment]
I've been watching this issue, mark

**Comment by dutor** [comment]
Resolved in #1626
