### ISSUE TITLE
LICENCE file inaccurate

### ISSUE THREAD

**Issue by dpen2000** [vesoft-inc/nebula#1628]
Currently your licence file doesn't refer to Commons Clause. Consequently, GitHub marks this project as licensed under Apache-2.0

Please remove file or amend in a way that makes it clear you're not under unmodified Apache-2.0.
**Edit:** Commons Clause provides one way to format licence file here: https://github.com/fossas/commons-clause

**Comment by williamstein** [comment]
Also, you describe your project as "open source" in the README.md and title, but the [Common Clause FAQ](https://commonsclause.com/) that you link to says:

>  Is this “Open Source”?   **No.**

and goes on to say 

> to avoid confusion, it is best not to call Commons Clause software “open source.”

Thus you might want to change the wording in the description and README as suggested in the FAQ.

**Comment by Amber1990Zhang** [comment]
> Also, you describe your project as "open source" in the README.md and title, but the [Common Clause FAQ](https://commonsclause.com/) that you link to says:
> 
> > Is this “Open Source”?   **No.**
> 
> and goes on to say
> 
> > to avoid confusion, it is best not to call Commons Clause software “open source.”
> 
> Thus you might want to change the wording in the description and README as suggested in the FAQ.

Thanks for your kind issue, will change the word in README.md to avoid confuison.

**Comment by Qix-** [comment]
Commons Clause software is not OSS as per the OSI's definition, but for all intents and purposes, the code remains just as unencumbered as before. The only change the Commons Clause adds is that large companies cannot take advantage of small open source devs by having them developer all their software for free and then selling it at a premium.

I don't think the README needs changing, but the license file should definitely reflect this.
