### ISSUE TITLE
Support Time-to-live (TTL)

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#163]
We should allow users to specify a TTL when creating the tag/edge schema. All expired data should not be returned

**Comment by steppenwolfyuetong** [comment]
@dangleptr， Just like communicating with @sherman-the-tank  offline, because the version in vertex and edge key may be removed later,   TTL implicit mode is not supported at this time.

**Comment by steppenwolfyuetong** [comment]
The supported nGQL is as follows：

```
CREATE tag t2 (a int,  ts timestamp )   ttl_duration=3600, ttl_col=ts;
CREATE edge e2 (a int,  ts timestamp )  ttl_duration=3600, ttl_col=ts;
```
```

alter tag t2 ttl_duration=300；
alter edge e2 ttl_duration=300；
```

Desc tag/edge does not display table-level attributes such as ttl_duration,ttl_col;

show create tag/edge display table-level attributes such as ttl_duration,ttl_col;

**Comment by dangleptr** [comment]
> @dangleptr， Just like communicating with @sherman-the-tank offline, because the version in vertex and edge key may be removed later, TTL implicit mode is not supported at this time.

Make sense

**Comment by steppenwolfyuetong** [comment]
note:
`Create tag/edge`
1) Only allow ttl to be created on `int` columns or `timestamp` columns

2) Currently only supports the displayed ttl mode 
`create tag t(a int) ttl_duration = 100, ttl_col = a;`

`Alter tag/edge`
3) When there is ttl on this column, it is not allowed to delete the column
`Alter tag t drop a;`
Firstly you must remove the ttl attribute and then delete the ttl column.
```
Alter tag t change ttl_col = "", ttl_duration = 0;
Alter tag t drop a;
```
4) When there is ttl on this column, it is not allowed to modify the attributes of the column to other non-int columns.
`Alter tag t change a string;`

**Comment by sherman-the-tank** [comment]
> note:
> `Create tag/edge`
> 
> 1. Only allow ttl to be created on `int` columns or `timestamp` columns
> 2. Currently only supports the displayed ttl mode
>    `create tag t(a int) ttl_duration = 100, ttl_col = a;`
> 
> `Alter tag/edge`
> 3) When there is ttl on this column, it is not allowed to delete the column
> `Alter tag t drop a;`
> Firstly you must remove the ttl attribute and then delete the ttl column.
> 
> ```
> Alter tag t change ttl_col = "", ttl_duration = 0;
> Alter tag t drop a;
> ```
> 
> 1. When there is ttl on this column, it is not allowed to modify the attributes of the column to other non-int columns.
>    `Alter tag t change a string;`

Make sense 👍

**Comment by panda-sheep** [comment]
This issue has been implemented, including the following pr:
Support Time-to-live in query(syntax) #330
Ttl schema #422
support TTL in storage #1584
Check TTL before creating index #1774
