### ISSUE TITLE
LDBC_SNB benchmark for Nebula

### ISSUE THREAD

**Issue by ouzensang** [vesoft-inc/nebula#1631]
Hi, Nebula
    Recently, I am doing some experiments based on ldbc_snb benchmark. And I wan to test Nebula on ldbc. So I want to know if you have implemented ldbc_snb benchmark for Nebula? If so, could you please provide me a solution to run ldbc_snb benchmark on Nebula? If not, now the query language in Nebula whether can support interactive complex and business intelligence queries in LDBC_SNB benchmark(https://ldbc.github.io/ldbc_snb_docs/ldbc-snb-specification.pdf)?
    Thanks for your kindly support and I'm looking forward to your early reply!

**Comment by dutor** [comment]
Sorry about so late to reply.

Recently, we've been working on applying the LDBC SNB workload on Nebula Graph.
Here now I can provide a schema for SNB workload, not the final complete one though:
```
CREATE SPACE IF NOT EXISTS ldbc_snb(PARTITION_NUM = 1024)

USE ldbc_snb

CREATE TAG IF NOT EXISTS person(first_name string, last_name string, gender string, ip string, browser string)
CREATE TAG IF NOT EXISTS place(name string, type string, url string)
CREATE TAG IF NOT EXISTS organization(name string, type string, url string)
CREATE TAG IF NOT EXISTS post(time string, image string, ip string, browser string, language string, content string, length int)
CREATE TAG IF NOT EXISTS comment(time string, ip string, browser string, content string, length int)
CREATE TAG IF NOT EXISTS forum(time string, title string, type string)

CREATE EDGE IF NOT EXISTS knows()
CREATE EDGE IF NOT EXISTS is_part_of()
CREATE EDGE IF NOT EXISTS is_located_in()
CREATE EDGE IF NOT EXISTS study_at(year string)
CREATE EDGE IF NOT EXISTS work_at(year string)
CREATE EDGE IF NOT EXISTS has_post(time string)
CREATE EDGE IF NOT EXISTS has_comment(time string)
CREATE EDGE IF NOT EXISTS likes_post(time string)
CREATE EDGE IF NOT EXISTS likes_comment(time string)
CREATE EDGE IF NOT EXISTS is_reply_of_post(time string)
CREATE EDGE IF NOT EXISTS is_reply_of_comment(time string)
CREATE EDGE IF NOT EXISTS has_member(time string, type string)
```

Besides, we will provide the whole procedure of the testing, along with the import and benchmark tools later.

**Comment by jude-zhu** [comment]
https://github.com/vesoft-inc/nebula-bench
