### ISSUE TITLE
Documentation surrounding how to get an instance working is very sparse

### ISSUE THREAD

**Issue by Qix-** [vesoft-inc/nebula#1640]
I'm very interested in looking into Nebula, but it's incredibly hard to understand how to actually _run_ Nebula.

The getting started documentation - the markdown document linked to by both the Readme and the website - make no mention of how to run or configure Nebula, even for testing purposes. It assumes you already have an instance running.

There are a few links that link to the Docker images for testing, but the main docker image drops you into a shell with a `bin/` folder and no extra information. Running `bin/nebula` asks for a username (no idea what to do there) and running `nebula-graphd` asks for a flagfile (no idea what that is).

Where can I find detailed documentation on configuring and running Nebula?

**Comment by wilsonyou** [comment]
> I'm very interested in looking into Nebula, but it's incredibly hard to understand how to actually _run_ Nebula.
> 
> The getting started documentation - the markdown document linked to by both the Readme and the website - make no mention of how to run or configure Nebula, even for testing purposes. It assumes you already have an instance running.
> 
> There are a few links that link to the Docker images for testing, but the main docker image drops you into a shell with a `bin/` folder and no extra information. Running `bin/nebula` asks for a username (no idea what to do there) and running `nebula-graphd` asks for a flagfile (no idea what that is).
> 
> Where can I find detailed documentation on configuring and running Nebula?

There are some videos that might help you:

https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw

**Comment by Amber1990Zhang** [comment]
The easiest way to try nebula is by using docker: https://github.com/vesoft-inc/nebula-docker-compose

**Comment by Qix-** [comment]
> There are some videos that might help you

In software development, tutorial videos are definitely not the norm. Proper documentation cannot be replaced with tutorial videos.

> The easiest way to try nebula is by using docker

Thank you, that's what I need. It should really be linked to by some of the "getting started" material somewhere, though.

**Comment by Meai** [comment]
yeah I got some kind of connection error even though I started each binary as far as I can tell. I dont like to do make install, it should work in the regular build folder too. How else would you do debugging if it only starts after you do a make install. That is always my test for software, it has to build and work in the normal build directory, not just after all the fancy configs are copied around during installation.

**Comment by whitewum** [comment]
@dutor

**Comment by Amber1990Zhang** [comment]
> yeah I got some kind of connection error even though I started each binary as far as I can tell. I dont like to do make install, it should work in the regular build folder too. How else would you do debugging if it only starts after you do a make install. That is always my test for software, it has to build and work in the normal build directory, not just after all the fancy configs are copied around during installation. Release and debug builds should be identical in my opinion, there is no value in having them use different configs, different directory layouts and so on.

If you are doing make install, you can choose the build type:

```
There are a few building types supported:

* `Debug`, to build with debug info but without optimization, which is by default
* `Release`, to build with optimization but without debug info
* `RelWithDebInfo`, to build with optimization AND debug info
* `MinSizeRel`, to build with optimizations for code size
```
For example:
```
cmake -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE= Release ..
```
Hope this can help you, anyway, please let me know if you need more help.

**Comment by Meai** [comment]
I meant that the standard build doesnt seem to produce something I can successfully run right away:

mkdir mybuild && cd mybuild
cmake .. -DCMAKE_CXX_FLAGS="-Werror" -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/pc/workarea/test/nebula/install
make -j8
cd bin
./nebula 

> pc@mymachine~/workarea/test/nebula/mybuild/bin $ ./nebula --port 3699 --u user --p password 
> Failed to open `/home/pc/workarea/test/nebula/mybuild/bin/../share/resources/completion.json': No such file or directory
> E0120 08:23:59.224479  4275 GraphClient.cpp:54] Thrift rpc call failed: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
> Connection failed

ok so I assume I have to start ./nebula-graphd first, but that requires a "flagfile" apparently. Those dont exist in the build folder, so I first have to copy them manually over. Now:

> pc@mymachine~/workarea/test/nebula/mybuild/bin $ ./nebula-graphd --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-graphd.conf.default 
> Could not create logging file: No such file or directory
> COULD NOT CREATE A LOGGINGFILE 20200120-082638.4333!Could not create logging file: No such file or directory
> COULD NOT CREATE A LOGGINGFILE 20200120-082638.4333!Could not create logging file: No such file or directory
> COULD NOT CREATE A LOGGINGFILE 20200120-082638.4333!E0120 08:26:38.912017  4333 GraphDaemon.cpp:58] Failed to create or open `logs/stdout.log': No such file or directory
> 

ok so I have to create a logs folder.

Now it starts with still one minor error:

> pc@mymachine~/workarea/test/nebula/mybuild/bin $ ./nebula --port 3699 --u user --p password 
> Failed to open `/home/pc/workarea/test/nebula/mybuild/bin/../share/resources/completion.json': No such file or directory
> 
> Welcome to Nebula Graph
> 
> (user@127.0.0.1:3699) [(none)]> 

that error doesnt matter, so I type in the command to do something:

> (user@127.0.0.1:3699) [(none)]> CREATE SPACE nba(partition_num=10, replica_factor=1);
> [ERROR (-8)]: Create space `nba' failed: RPC failure in MetaClient: N6apache6thrift9transport19TTransportExceptionE: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused.
> Mon Jan 20 08:29:54 2020

ok so I assume that I still need to start the nebula-storaged process because I saw that in the tutorial video but the error didnt really tell me that this is the problem:

> ./nebula-storaged --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-storaged.conf.default

ok I try again to create a space, but still the same error. No idea what the problem is. What socket not open? No way to know what is going on. I have nebula, nebula-graphd and nebula-storaged running in the process explorer.

> (user@127.0.0.1:3699) [(none)]> CREATE SPACE nba(partition_num=10, replica_factor=1);
> [ERROR (-8)]: Create space `nba' failed: RPC failure in MetaClient: N6apache6thrift9transport19TTransportExceptionE: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused.
> Mon Jan 20 08:31:38 2020

**Comment by Amber1990Zhang** [comment]
Did you `make install` after `make -j8`? It seems the error message indicates meta is out of service. Please verify with `./scripts/nebula.service status all`, assuming you're in the `/usr/local/nebula` directory.  When connected with nebula, please wait for seconds before creating space. Don't hesitate to let me know if this helps.

**Comment by Meai** [comment]
I dont want to make install, it has to run without special service files because I want to be able to debug it with gdb etc and when I change something in the source code I dont want to make install constantly

**Comment by bright-starry-sky** [comment]
> I dont want to make install, it has to run without special service files because I want to be able to debug it with gdb etc and when I change something in the source code I dont want to make install constantly

Aha, If you want a simple environment for debugging，I have some suggestions as below :

A simple way to write a test case and debug your test case directly.

And a complete example：
- step 1 :  git clone to $workspace
- step 2:  `cd  $workspace && mkdir build && cmake -DENABLE_ASAN=on .. && make -j4`
- step 3:  Some executable files will be generated into directory $workspace/build/bin. such as `nebula-graphd` , `nebula-storaged` and `nebula-metad`
- step 4：Get and modify the configuration files , you can find template in folder $workspace/etc
- step 5: start Start three processes : `nebula-graphd` , `nebula-storaged` and `nebula-metad`, for example : `./nebula-graphd --flagfile=nebula-graphd.conf`
- step 6:  After all three processes start successfully，you can do whatever you want.
-

**Comment by Meai** [comment]
well apart from the ENABLE_ASAN=on I believe I already did that

**Comment by bright-starry-sky** [comment]
> well apart from the ENABLE_ASAN=on I believe I already did that

If so, You can ignore all compilation options， the simplest is `cmake ..`

**Comment by Meai** [comment]
ok I figured it out, the meta process was somehow not working correctly (heartbeat not working). I think the default conf might be wrong, I dont know. If I specify it on the command line, it works:

> ./nebula --port 3699 --u user --p password 
> ./nebula-metad --daemonize=false -port 45500 -data-path data -log_dir logs
> ./nebula-graphd --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-graphd.conf.default
> ./nebula-storaged --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-storaged.conf.default

**Comment by bright-starry-sky** [comment]
> ok I figured it out, the meta process was somehow not working correctly (heartbeat not working). I think the default conf might be wrong, I dont know. If I specify it on the command line, it works:
> 
> > ./nebula --port 3699 --u user --p password
> > ./nebula-metad --daemonize=false -port 45500 -data-path data -log_dir logs
> > ./nebula-graphd --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-graphd.conf.default
> > ./nebula-storaged --flagfile /home/pc/workarea/test/nebula/mybuild/bin/nebula-storaged.conf.default


Good job ! 
About default template of meta , I will verify it.  Any question please bring it up feel free.
