### ISSUE TITLE
A query statement to retrieve a sub-graph

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#166]
We need a new query statement to retrieve the entire sub-graph from one or multiple vertices. The sub-graph needs to include all edges not only starting from the given vertices, but also between any two vertices in the sub-graph

**Comment by jude-zhu** [comment]
fintech ak-nbt

**Comment by laura-ding** [comment]
The syntax for getting subgraph

```
GET SUBGRAPH 2 steps from vid over <edgeTypeList|*> <empty|REVERSELY|BOTH> [WHERE V1.tag_name.prop > 10] [YIELD V0.tag_name.prop, V1.tag_name.prop, V2.tag_name.prop, E1.edge_type.prop, E2.edge_type.prop]
```

**V0** is the starting vertex, **V1**  is the first-degree vertices, **V2** is the second-degree vertices.
**E1** is the first-degree edges, **E2** is the second-degree edges
If not YIELD, return the vertex id and edge type

The result is JSON format, return all paths from the start vertex. The returned data set has redundant data because it is returned by path.

**Comment by jude-zhu** [comment]
FYR, subgraph syntax of cypher is:

```
apoc.path.subgraphAll(startNode <id>Node/list, {minLevel, maxLevel, relationshipFilter, labelFilter, bfs:true, filterStartNode:true, limit:-1}) yield nodes, relationships
```

Example. Expand to local subgraph (and all its relationships) within 4 traversals:

```
MATCH (company:Company) WHERE company.name = "RENTON COLLECTIONS INC."
CALL apoc.path.subgraphAll(company, {maxLevel:4}) YIELD nodes, relationships
RETURN nodes, relationships;
```

Result in table format:

![屏幕快照 2019-12-24 上午11 26 56](https://user-images.githubusercontent.com/51590253/71391734-6efc1c80-2640-11ea-88fd-29cf31b6d312.png)

In text format:

![屏幕快照 2019-12-24 上午11 27 16](https://user-images.githubusercontent.com/51590253/71391746-7b807500-2640-11ea-840a-954cf6e1aad0.png)

In graph format:

![屏幕快照 2019-12-24 上午11 27 28](https://user-images.githubusercontent.com/51590253/71391756-85a27380-2640-11ea-9027-694cc1d50887.png)

**Comment by sherman-the-tank** [comment]
Very good start point. Here are couple things I can think of

1) Instead of keyword "BOTH" in the edge specification, I would suggest to use "BIDIRECTIONALLY" (or abbreviate to "BIDIRECT"). It is more meaningful

2) In the YIELD sentence, I'm afraid V1, V2.. E1, E2.. are insufficient, because some vertices could be the result of multiple hops (ie. a vertex could be the result of 2-hop, and the result of 3-hop), same as the edges
