### ISSUE TITLE
Too many space will make storaged crash

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1684]
We create 60,000 spaces in nebula, storaged oom. It is killed by oom-killer. 
I pick up some logs for /var/log/messages:
```
Jan 20 11:24:41 k8s3 kernel: nebula-storaged invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=-998
Jan 20 11:24:41 k8s3 kernel: nebula-storaged cpuset=docker-301991dfdf74c4ec96fae93de347dbaf77dd325696ac6368bbffe626b4566a18.scope mems_allowed=0-1
```

Limit  the number of spaces may be a better approach.
/kind bug

**Comment by Amber1990Zhang** [comment]
what is the partition_num? A lager partition_num will make it easy to crash.

**Comment by critical27** [comment]
I think rocksdb would take some memory...
