### ISSUE TITLE
after dropping tag, "fetch prop on * vid" crashes graphd service

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1699]
commit ID is `4af19fe1`,  Build Time: Jan 16 2020

node 201 is tagged with `student`，after I dropping tag `student`,  `fetch prop on * 200` crashes the graphd service.

![1](https://user-images.githubusercontent.com/51590253/72864604-96153f00-3d0f-11ea-9fa2-91155eb15323.png)

![1](https://user-images.githubusercontent.com/51590253/72864674-cb219180-3d0f-11ea-88f4-3de119149d21.png)

**Comment by knightXun** [comment]
It seems another issus happened, If I drop tag, The prop of vertex will not be delete immediately.
See: 
![image](https://user-images.githubusercontent.com/8334944/73642092-062aaa00-46ac-11ea-9425-35ecce172fe9.png)

**Comment by knightXun** [comment]
ping @CPWstatic
