### ISSUE TITLE
Newly created graph space with unwanted tags

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1714]
I'm using the compose docker. When I created a new space, I found there are some tags that I never created. I don't know where they come from. 
![image](https://user-images.githubusercontent.com/42762957/73712335-c1068680-4744-11ea-971e-4d6e6b527e93.png)
I believe the schema comes from a space that I deleted before but I have no idea why they appear in my new space.
I drop the space and created a new one, this time there is no unwanted schema. I think this problem is severe but not easy to reproduce.

**Comment by whitewum** [comment]
please provide graph/meta logs next time.

And provide your command to create space & tag, etc. 

So we can check the timeline.
