### ISSUE TITLE
Advanced data modification

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#172]
More complicate data modification, such as

* INSERT NOT EXISTS
* UPDATE ... WHERE (conditional modification)
* DELETE ... WHERE (conditional deletion)

**Comment by zhangguoqing** [comment]
@zlcook's #171 is implementing the **DELETE** statement, so I am implementing the **UPDATE** statement.


#### [Update a vertex](https://github.com/vesoft-inc/nebula/blob/master/docs/nGQL.md#update-a-vertex) 
The following statement updates a vertex

<span style="color:blue">**UPDATE VERTEX**</span>  <vertex\_id> <span style="color:blue">**SET**</span> \<update\_decl\> [<span style="color:blue">**WHERE**</span> <conditions\>] [<span style="color:blue">**YIELD**</span> <field\_list>]

<update\_decl> ::= <update\_form1> | <update\_form2>
<update\_form1> ::= <prop\_name> = <expression\> {,<prop\_name> = <expression\>}+
<update\_form2> ::= (<prop\_list>) = (<value\_list>) | (<prop\_list>) = <var\>

#### [Update an edge](https://github.com/vesoft-inc/nebula/blob/master/docs/nGQL.md#update-an-edge)
The following statement updates an edge

<span style="color:blue">**UPDATE EDGE**</span>  <vertex\_id> -> <vertex\_id> [@<weight\>] <span style="color:blue">**OF**</span> <edge\_type> <span style="color:blue">**SET**</span> <update\_decl> [<span style="color:blue">**WHERE**</span> <conditions\>] [<span style="color:blue">**YIELD**</span> <field\_list>]

**Comment by dangleptr** [comment]
> More complicate data modification, such as
> 
> * INSERT NOT EXISTS
> * UPDATE ... WHERE (conditional modification)
> * DELETE ... WHERE (conditional deletion)

Currently,  we don't support where clause.   For update, we only support update specified edge or vertex
