### ISSUE TITLE
日志配置不生效问题

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1754]
问题一：第一次以--minloglevel=0启动服务，然后关闭服务配置--minloglevel=2，日志配置会不生效。
![image](https://user-images.githubusercontent.com/13991775/74294454-e3b62200-4d78-11ea-851c-d54c98147fa0.png)

![image](https://user-images.githubusercontent.com/13991775/74294425-caad7100-4d78-11ea-8995-24603ce1796d.png)

问题二：使用console配置的日志等级并不会生效（rc2版本之前是，新版本有待验证）。

**Comment by Shylock-Hg** [comment]
目前nebula的配置优先级是：meta > 命令行参数 > 环境变量 > flag文件，
如果要持久化修改可以参考 https://docs.nebula-graph.io/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax/

**Comment by Shylock-Hg** [comment]
如果临时修改可以使用HTTP接口：
`curl localhost:13000/set_flag?flag=minloglevel&value=2`

**Comment by ownthink** [comment]
之前rc2测试，这些方法不生效的------------------ 原始邮件 ------------------
发件人: "Shylock Hg"<notifications@github.com>
发送时间: 2020年2月12日(星期三) 下午3:30
收件人: "vesoft-inc/nebula"<nebula@noreply.github.com>;
抄送: "Yener"<158760520@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vesoft-inc/nebula] 日志配置不生效问题 (#1754)



如果临时修改可以使用HTTP接口：
 curl localhost:13000/set_flag?flag=minloglevel&value=2
 
&mdash;

**Comment by Shylock-Hg** [comment]
> 之前rc2测试，这些方法不生效的------------------ 原始邮件 ------------------ 发件人: "Shylock Hg"<notifications@github.com> 发送时间: 2020年2月12日(星期三) 下午3:30 收件人: "vesoft-inc/nebula"<nebula@noreply.github.com>; 抄送: "Yener"<158760520@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [vesoft-inc/nebula] 日志配置不生效问题 (#1754) 如果临时修改可以使用HTTP接口： curl localhost:13000/set_flag?flag=minloglevel&value=2 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Query修改需要重启生效，HTTP修改应该是立即生效的。

**Comment by Shylock-Hg** [comment]
添加`--local_config=true`也可以使本地配置生效。
