### ISSUE TITLE
how to represent [:REPLY_OF*0..]?

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1762]
First of all. I know how to use the variable sentence. But, I'm not sure how many steps will go to, the parameter (N) is passed in. So I don't know how many variable sentences have to write (since N is unknown)

I want to 

1.  go zero to N steps and get all the nodes; I think GOTO does not meet the requirement.

2.  get the most far away node (the most steps)  from the starting node. But I don't know how many steps. ( A upmost, e.g. 7 is accepted)

Besides, I think `*MIN..MAX` is more expressive and exactly than `UPTO` or `N STEPS`.

[MIN,MAX)  

0 distance means the same node.

I prefer to use query language rather than by programming. 

Any suggestions?

#1631

**Comment by jude-zhu** [comment]
#2091
