### ISSUE TITLE
Copy schema and data

### ISSUE THREAD

**Issue by sartry-night** [vesoft-inc/nebula#1766]
I notice that PR #1710 supports copying schema from another space. But I have some questions:
- Must the target space have the same partition_num and replica_factor with the source space?
- What if the source space contains indexes or default values that I don't need in my target space? Is there an option to specify copying indexes or default values?
- What if I want to copy the exact space? I mean to copy schema and data at the same time.
Look forward to your reply.

**Comment by laura-ding** [comment]
@sartry-night Thanks for your questions. 
> Must the target space have the same partition_num and replica_factor with the source space?

Don't need
> What if the source space contains indexes or default values that I don't need in my target space? Is there an option to specify copying indexes or default values?

- The default values are also copied
- The indexes can be given an option to choose(it will support)

> What if I want to copy the exact space? I mean to copy schema and data at the same time.Look forward to your reply.

We're not going to support it yet
