### ISSUE TITLE
nebula-storaged挂了

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1780]
![image](https://user-images.githubusercontent.com/13991775/74536702-93ef7a80-4f73-11ea-8a2c-0bf369c44c4d.png)

**Comment by jude-zhu** [comment]
using nightly version
https://github.com/vesoft-inc/nebula/actions/runs/1228324

**Comment by critical27** [comment]
It seems you need to set max open files with `ulimit -n`
