### ISSUE TITLE
Does nebula support bitwise operation?

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1787]
Error is thrown when using bitwise:
![image](https://user-images.githubusercontent.com/42762957/74722227-8851cb80-5273-11ea-85b2-d32fde5eeaeb.png)
Thanks @Shylock-Hg

**Comment by Shylock-Hg** [comment]
It's ok now

**Comment by Shylock-Hg** [comment]
But only BIT_XOR, BIT_AND and BIT_OR operator.
