### ISSUE TITLE
端口状态需要做处理，要不服务挂了还一直占用着端口

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1789]
![image](https://user-images.githubusercontent.com/13991775/74751311-04fe9d00-52a8-11ea-9d05-156ec442a988.png)

**Comment by ownthink** [comment]
是先确认退出状态的，并且ps -ef 找不到进程的情况下，端口还被占用的。

**Comment by Shylock-Hg** [comment]
看上去像是web的线程没有回收，可以提供一下版本和复现步骤么？

**Comment by ownthink** [comment]
&nbsp;从ui上线之后的版本基本都会，复现方式是在程序挂掉的时候，不过基本都被修复了。等后面我新发现了，再详细列下复现步骤。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shylock Hg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 晚上10:57
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] 端口状态需要做处理，要不服务挂了还一直占用着端口 (#1789)




看上去像是web的线程没有回收，可以提供一下版本和复现步骤么？

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/77515053-d9785f00-6eb2-11ea-8785-34804173357c.png)
![image](https://user-images.githubusercontent.com/50101159/77515075-e2693080-6eb2-11ea-92b2-c846d3a49c14.png)
