### ISSUE TITLE
[nGQL question] How can i get both vid and property in lookup

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1799]
I notice that 

```
lookup on entity where entity.name=="红色食品" Yield entity.name
```
can return property (i.e., name).

```
And 

```
lookup on entity where entity.name=="红色食品" Yield entity.name  | go from $-.VertexID over relation
```
is ok to pipe VertexID to the next GO-syntax. (that's really a guess, And no Unittest I can find in grap hd code)

But, What if my property name is "VertexID" -- a collision with `$-.VertexID`.

**Comment by bright-starry-sky** [comment]
Is this your expected as below ?
```
CREATE SPACE my_space(partition_num=3, replica_factor=1);
USE my_space;
CREATE TAG lookup_tag_1(col1 string, col2 string, col3 string);
CREATE EDGE lookup_edge_1(col1 string, col2 string, col3 string);
CREATE TAG INDEX t_index_1 ON lookup_tag_1(col1, col2, col3);
LOOKUP ON lookup_tag_1 WHERE lookup_tag_1.col1 == "col1_200" | go from $-.VertexID over lookup_edge_1;
Execution succeeded (Time spent: 7.643/8.796 ms)
```

**Comment by bright-starry-sky** [comment]
> I notice that
> 
> ```
> lookup on entity where entity.name=="红色食品" Yield entity.name
> ```
> 
> can return property (i.e., name).
> 
> ```
> And 
> ```
> 
> lookup on entity where entity.name=="红色食品" Yield entity.name | go from $-.VertexID over relation
> 
> ```
> is ok to pipe VertexID to the next GO-syntax. (that's really a guess, And no Unittest I can find in grap hd code)
> 
> But, What if my property name is "VertexID" -- a collision with `$-.VertexID`. 
> ```

If your column name is "VertexID" , you can using alias to avoid conflict. And other good idea please let me know. Let me  improve it.
