### ISSUE TITLE
modify default log level

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1800]
I write in about 10GB data,  with all default configs.

The log file is about 4GB.+ 

I check the configs: minloglevel & v are both 0.  are they ok as default value?

I can change the configs, but for those who are new to Nebula, the default configs seems not friendly.

**Comment by CPWstatic** [comment]
`v` should be 0, or it would output much more logs. As for `minloglevel`, 0 means `INFO`, i think we need to reduce some unnecessary logs.
