### ISSUE TITLE
[bug] storaged may not fully stopped but script nebula.service tells that it's successfully stopped

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1803]
When I use nebula.service stop/start/restart to stop and start storaged,
I find in some cases (about 1 in 4 or 5 times), the script tells me storaged is stopped, but actually, the storaged process is running (maybe state Z or D).

I think it's because rocksdb is flushing data when exiting (I was doing bulk writing meanwhile stopping storaged), either the port or pid file release sequence is not correct.

**Comment by ownthink** [comment]
可以参考这个，有时候移除停止的时候等待一段时间，也不会退出，https://github.com/vesoft-inc/nebula/issues/1789

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/75135529-bb390b00-571c-11ea-9bf6-c62a922aa904.png)
