### ISSUE TITLE
limit a request' size

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1817]
It's possible that (by mistake) the client sends a large request (especially when the source data is dirty, and a single request is of MB or even GB size)

I don't think it's reasonable that the client or graphd should send this large request to storaged. 

(Maybe a threshold to test the request size)

WDYT?

**Comment by CPWstatic** [comment]
What do you mean `Requests' size`? QPS or data? The size of data can't be estimated now.

**Comment by whitewum** [comment]
> What do you mean `Requests' size`? QPS or data? The size of data can't be estimated now.

data size. 

you can't estimate the read result size. But the client can reject a large insert string request.
