### ISSUE TITLE
Unexpected Metad Start Error

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1821]
Metad Logs look likes below:
++ hostname -i
++ hostname -i
 exec /usr/local/nebula/bin/nebula-metad --flagfile=/usr/local/nebula/etc/nebula-metad.conf --local_ip=192.168.0.227 --v=3 --meta_server_addrs=192.168.0.227:44500 --daemonize=false --minloglevel=2 --ws_ip=0.0.0.0 --log_dir=logs --data_path=data
E0226 09:16:38.374913     1 NebulaStore.cpp:64] Data path invalid: Invalid leading character: "nebula"
E0226 09:16:38.375227     1 MetaDaemon.cpp:86] Nebula store init failed
E0226 09:16:38.380558     1 MetaDaemon.cpp:213] Init kv failed!

**Comment by Shylock-Hg** [comment]
Try `--data-path=data/meta`.
