### ISSUE TITLE
Questions on group by

### ISSUE THREAD

**Issue by sartry-night** [vesoft-inc/nebula#1836]
```
GO FROM hash('jupiter') OVER * YIELD $$.character.name AS Name, $$.character.age as Age, $$.location.name  As LocName| group by $-.Name, $-.Age, $-.LocName | Yield $-.Name, $-.Age, $-.LocName
[ERROR (-7)]: SyntaxError: Yield cols is empty
```
nebula keeps telling me ` Yield cols is empty` but there is `YIELD` in my query. Why is that?

Besides, if I want the distinct name, does the following query make any sense?

```
GO FROM hash('jupiter') OVER * YIELD $$.character.name AS Name, $$.character.age as Age, $$.location.name | \
GROUP BY $-.Name YIELD $-.Name
```

Thanks.

**Comment by laura-ding** [comment]
Thanks for your question!
- `Yield cols is empty` means the `GROUP BY` need with the keyword `YIELD` in the same sentence.
- Your query `GO FROM hash('jupiter') OVER * YIELD $$.character.name AS Name, $$.character.age as Age, $$.location.name | \
GROUP BY $-.Name YIELD $-.Name` can get the distinct name
