### ISSUE TITLE
【稳定性bug】放置一段时间后请求速度会变为原来的100倍，没法使用

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1837]
初始导入数据208G隔一天变为72G，同样的请求查询语句（client子图查询），由0.8秒，变为100秒。

重启后可以由100秒，变为40多秒。

**Comment by laura-ding** [comment]
Thank you for your question. The reason for this problem is that you have used the HDD. In the continuous writing process, the storage will automatically compact the data, but your environment's compaction is slower than write. We do not recommend the use of HDD.
