### ISSUE TITLE
Created index disappears

### ISSUE THREAD

**Issue by back-to-eat** [vesoft-inc/nebula#1839]
I'm using nebula docker and the gods toy graph in your [doc](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/5.appendix/gremlin-ngql.md). I created an **index on character (name, age)** yesterday. But when I try the same query today, nebula throws me an error:
```
(user@127.0.0.1:3699) [gods]> LOOKUP ON character WHERE character.name == 'hercules' YIELD character.name, character.age, character.type;
[ERROR (-8)]: Unknown error(411):
```
I don't understand the error message. When I check if there is still an index, nothing shows up.

```
(user@127.0.0.1:3699) [gods]> show tag indexes
Empty set (Time spent: 1.237/2.482 ms)
```
I just don't know why my index is gone while the other data is still there. Besides, will you make the error message more friendly? Thanks.

**Comment by back-to-eat** [comment]
I tried `SUBMIT JOB COMPACT` but told Leader changed.
```
(user@127.0.0.1:3699) [gods]> SUBMIT JOB COMPACT
[ERROR (-8)]: Unknown error(409): Leader changed!
```
meta error logs:
```
Log file created at: 2020/02/28 05:22:24
Running on machine: 1cf4b1e81320
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0228 05:22:24.151140    35 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 0, Part: 0] The given log id 287712 is out of the range, the wal firstLogId is 460381
```
```
Running on machine: 24f27751ae5c
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0228 05:22:25.272526   106 RaftPart.cpp:361] [Port: 45501, Space: 0, Part: 0] The partition is not a leader: Success [0]
E0228 05:22:25.287063   106 RaftPart.cpp:629] [Port: 45501, Space: 0, Part: 0] Cannot append logs, clean the buffer: Success [0]
E0228 05:22:25.823040    41 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 0, Part: 0] The given log id 287712 is out of the range, the wal firstLogId is 418070
```

**Comment by back-to-eat** [comment]
Is this a COMPACT BUG? What if the compact considers the index as garbage and collected it?

**Comment by bright-starry-sky** [comment]
Could you help

**Comment by bright-starry-sky** [comment]
Thanks for your report.
Could you help provide more  informations for graph, meta and storage?

**Comment by bright-starry-sky** [comment]
The first day is works well, second day is wrong?
