### ISSUE TITLE
If restart storaged, It will crash over and over again

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1847]
I use helm to deploy nebula,  If I delete nebula using helm, and install it again.It will crash over and over again.
See logs below:
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0302 13:29:13.376643    36 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 17044, Part: 3] The given log id 1249590 is out of the range, the wal firstLogId is 1336921
E0302 13:29:27.360796    40 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 17044, Part: 90] The given log id 1251514 is out of the range, the wal firstLogId is 1343426
E0302 13:29:28.561399    35 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 17044, Part: 87] The given log id 1263275 is out of the range, the wal firstLogId is 1319261
E0302 13:29:28.949677    37 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 17044, Part: 9] The given log id 1258736 is out of the range, the wal firstLogId is 1329516
E0302 13:30:03.841329    30 FileBasedWal.cpp:629] [Port: 45501, Space: 3, Part: 40] Rollback target id 0 is not in the range of [6972567,6972619] of WAL
E0302 13:30:03.842048    39 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 3, Part: 40] The given log id 1 is out of the range, the wal firstLogId is 6972567
E0302 13:30:16.154222    39 FileBasedWalIterator.cpp:35] [Port: 45501, Space: 3, Part: 65] The given log id 1 is out of the range, the wal firstLogId is 6787295
E0302 13:30:24.076339    45 FileBasedWal.cpp:505] [Port: 45501, Space: 3, Part: 48] There is a gap in the log id. The last log id is 6580938, and the id being appended is 6580938
E0302 13:30:24.126538    45 FileBasedWal.cpp:584] [Port: 45501, Space: 3, Part: 48] Failed to append log for logId 6580938
E0302 13:30:24.126569    45 RaftPart.cpp:1499] [Port: 45501, Space: 3, Part: 48] Failed to append logs to WAL
E0302 13:30:37.351604    39 FileBasedWal.cpp:505] [Port: 45501, Space: 3, Part: 25] There is a gap in the log id. The last log id is 6685393, and the id being appended is 6685392
E0302 13:30:37.351809    39 FileBasedWal.cpp:584] [Port: 45501, Space: 3, Part: 25] Failed to append log for logId 6685392
E0302 13:30:37.351843    39 RaftPart.cpp:1499] [Port: 45501, Space: 3, Part: 25] Failed to append logs to WAL

**Comment by critical27** [comment]
#1822
