### ISSUE TITLE
Push stats info to 3rd-party stats-base, such as Prometheus or openTSDB

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#185]
Actively push the stats to external monitoring services

**Comment by Shylock-Hg** [comment]
I think we'd better to integrate Prometheus for it's the standard in fact.
The Prometheus is widely used in production, easy to deploy and has rich documents,
active community.
We could integrate it to nebula by the [3rd SDK](https://github.com/jupp0r/prometheus-cpp)
but need 1. fork and change the http server component to `proxygen`, 2. add this
to third-party dependencies.Then we can expose the HTTP endpoint such as `/metrics`
in application to Prometheus server to scrape.

**Comment by jude-zhu** [comment]
ref to https://github.com/vesoft-inc/nebula-stats-exporter

**Comment by knightXun** [comment]
OpenTSDB is too heavy. I want to use thanos.
