### ISSUE TITLE
Change the ttl_col to label typed instead of string

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#1863]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

The column accept label when created, so the ttl_col keep same.

**Additional context**

**Comment by Shylock-Hg** [comment]
Which keep same with the nebula-test

**Comment by panda-sheep** [comment]
I used the `STRING `intentionally here instead of `name_label`
Because deleting the ttl attribute can delete
`alter tag ttl_col = " "` 
With name_label, you cannot do this.
