### ISSUE TITLE
Which version can I use LOOKUP method?  

### ISSUE THREAD

**Issue by Harlan6** [vesoft-inc/nebula#1876]
``` 
[nba]> fetch prop on team hash("huanglong")
==================================
| VertexID           | team.name |
==================================
| 289453977235621413 | 899       |
----------------------------------
Got 1 rows (Time spent: 823/1517 us)

Thu Mar  5 15:22:15 2020
```
```
[nba]> lookup on player where player.name=899
[ERROR (-7)]: SyntaxError: syntax error near `lookup'
Thu Mar  5 15:22:40 2020
```

``````````````````````````````````````````````````````````````````````````````

How to fix it?  What version support?

**Comment by whitewum** [comment]
use == instead of =

**Comment by whitewum** [comment]
use `==` instead of `=`

Check the manual

https://github.com/vesoft-inc/nebula/blob/aedca7ed85a07fb7603421a38dda0b3cd8137681/docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md

**Comment by Harlan6** [comment]
I have used == instead of = ,but  still get this error!  I think maybe my version no support?
`````````````````````````````````````
lookup on player where player.name==899
[ERROR (-7)]: SyntaxError: syntax error near `lookup'
Fri Mar  6 10:40:11 2020

**Comment by Harlan6** [comment]
> use == instead of =

I have used == instead of = ,but still get this error! I think maybe my version no support?

lookup on player where player.name==899
[ERROR (-7)]: SyntaxError: syntax error near `lookup'
Fri Mar  6 10:40:11 2020

**Comment by bright-starry-sky** [comment]
> > use == instead of =
> 
> I have used == instead of = ,but still get this error! I think maybe my version no support?
> 
> lookup on player where player.name==899
> [ERROR (-7)]: SyntaxError: syntax error near `lookup'
> Fri Mar 6 10:40:11 2020

Thanks for your trial . Seems that your version does not support this feature. Which version are you using?  This PR has been merged into the main line.  You can try these two ways:
1 : recompile 
https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
2: Using docker
https://github.com/vesoft-inc/nebula-docker-compose

**Comment by Harlan6** [comment]
thanks! it works well after install the new version
