### ISSUE TITLE
[Doc] User Manual

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#188]
Need a simple but sufficient enough user manual to teach users the concepts, architecture, query language, and administrative operations

**Comment by whitewum** [comment]
My thought about the outline: ( mainly based on Mysql, neo4j, & Janus User Manual)

# Overview (for beginners)

Introduction

Getting Started

Data Model

# Query Language ( for Users)

Language structure: Literal Values

    Schema Object 

    Keywords ( reserved Words)

    Expressions

    Comment

Data Types

Functions and Operations

Statement Syntax

# Topics

Clients & APIs

Storage Engines

Query Engines

Security

Administrations

# Advanced Topics

Backup && Recovery

Optimization

Replication

Alternative Storage Engines

Docker 

Saas

**Comment by Amber1990Zhang** [comment]
My thoughts on Manual Chapter One:
Introduction
Example graph
Get started
Data model
Design and architecture
nGQL overview
@sherman-the-tank @whitewum @jude-zhu
