### ISSUE TITLE
Upsert syntax bug:   shouldn't return an error when conditions fail

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#1888]
![image](https://user-images.githubusercontent.com/12572857/76093730-735b9300-5ffc-11ea-9f73-ee1f90c3c400.png)

As shown in the figure above， It should execute successfully instead of returning an error.

**Comment by zlcook** [comment]
Update syntax has the same problem. @Shylock-Hg

**Comment by Shylock-Hg** [comment]
> Update syntax has the same problem. @Shylock-Hg

What syntax problem. I don't syntax from the screenshot.

**Comment by Shylock-Hg** [comment]
I think return error is ok that alert the user the upsert not affect.

**Comment by zlcook** [comment]
> I think return error is ok that alert the user the upsert not affect.

I think it's unnecessary, refer to mysql UPDATE syntax:
![image](https://user-images.githubusercontent.com/12572857/76195707-ded37980-6223-11ea-96f1-08c11ca0f6a8.png)

**Comment by Shylock-Hg** [comment]
> > I think return error is ok that alert the user the upsert not affect.
> 
> I think it's unnecessary, refer to mysql UPDATE syntax:
> ![image](https://user-images.githubusercontent.com/12572857/76195707-ded37980-6223-11ea-96f1-08c11ca0f6a8.png)

Yes, but mysql provide more detail message(0 rows affcted) for this.
