### ISSUE TITLE
Time Gap bettween Index creating and index using

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1889]
![image](https://user-images.githubusercontent.com/8334944/76131588-0373f980-604a-11ea-9654-e5d2ddb21832.png)

**Comment by bright-starry-sky** [comment]
Is this one duplicate with #1891 ? You should keep only one if duplicated. 
And please provide a more detailed description of this bug.

**Comment by knightXun** [comment]
no, this bug tells me the index doesn't exsit

**Comment by bright-starry-sky** [comment]
sleep(FLAGS_heartbeat_interval_secs) needed after index created. 
the error reason is can't synchronize meta data from meta server to meta client immediate. a time gap is required. 
But this error message needs to be improved in the future. 
Close this issue.
