### ISSUE TITLE
How do I know the rebuilt index is successful?

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1897]
As title. Will nebula support `SHOW TAG INDEX STATUS `?

**Comment by Shylock-Hg** [comment]
It's supported now.

**Comment by whitewum** [comment]
any pr & doc relates to this issue?

**Comment by Amber1990Zhang** [comment]
> any pr & doc relates to this issue?

https://docs.nebula-graph.io/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-index-status/
Here is the doc. I hope it helps.
