### ISSUE TITLE
Access rights control

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#190]
Need to establish the entire access rights control mechanism. Here is the current thoughts

1) There is one **God** user ```admin```, like `root` of Linux systems. ```admin``` is the **only** person who can create a Graph Space 

2) All other access rights are based on Graph Space. There are three types of rights for each Graph Space: ```Admin```, ```User```, ```Guest```

```Admin``` is an administrator for a given Graph Space. An ```Admin``` can delete the Graph Space, can manage the schema in the Graph Space, and can access (read and write) the data in the Graph Space

```User``` is a normal user for a given Graph Space. A ```User``` can access (read and write) the data in the Graph Space

```Guest``` is a read-only role for a given Graph Space. A ```Guest``` **cannot** modify the data in the Graph Space

3) A normal user will associate with a default Graph Space, which is the current Graph Space as soon as the user logs on

4) A normal user can have different access right on different Graph Spaces

**Comment by boshengchen** [comment]
Below is operation and permission define. Any suggestions?

### Operation and permission define:

Operation | GOD | ADMIN | USER | GUEST
------------ | ------------- | ------------- | ------------- | -------------
kGo|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kSet|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kPipe|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kUse|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kMatch|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kAssignment|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kCreateTag|:heavy_check_mark:|:heavy_check_mark:||
kAlterTag|:heavy_check_mark:|:heavy_check_mark:||
kCreateEdge|:heavy_check_mark:|:heavy_check_mark:||
kAlterEdge|:heavy_check_mark:|:heavy_check_mark:||
kDescribeTag|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kDescribeEdge|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kRemoveTag|:heavy_check_mark:|:heavy_check_mark:||
kRemoveEdge|:heavy_check_mark:|:heavy_check_mark:||
kInsertVertex|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
kInsertEdge|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
kShow|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kDeleteVertex|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
kDeleteEdge|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
kFind|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kAddHosts|:heavy_check_mark:|||
kRemoveHosts|:heavy_check_mark:|||
kCreateSpace|:heavy_check_mark:|||
kDropSpace|:heavy_check_mark:|:heavy_check_mark:||
kYield|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kCreateUser|:heavy_check_mark:|||
kDropUser|:heavy_check_mark:|||
kAlterUser|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
kGrant|:heavy_check_mark:|||
kRevoke|:heavy_check_mark:|||
kChangePassword|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:

**Comment by boshengchen** [comment]
### The following pseudocode is the design logic, please give some suggestions. Thanks.

```

#define ACL_Go                 (1<<0)
#define ACL_Set                (1<<1)
#define ACL_Pipe               (1<<2)
#define ACL_Use                (1<<3)
#define ACL_Match              (1<<4)
......
#define ACL_Revoke             (1<<29)
#define ACL_ChangePassword     (1<<30)

int32_t acl_mode(RoleType type) {
   swith(type) {
	case RoleType::GOD :
	    return 0b11111111111111111111111111111111;
	case RoleType::ADMIN:
	    return ......;
	case RoleType::USER:
	    return ......;
	case RoleType::GUEST:
		return (ACL_Go | ACL_Set | ACL_Pipe | ACL_Use | ACL_Match | ACL_Assignment |......);
	defaule
	    return 0;
   }
}

int32_t getACLOp(Kind op) {
	swith(op) {
	case Kind::kGo:
	    return ACL_Go;
	case Kind::kSet:
	    return ACL_Set;
	......
	defaule
	    return 0;
	}
}

int32_t acl_check(RoleType role, Kind op) {
	return acl_mode(role) &  getACLOp(op);
}

cpp2:: ExecCheckPerms(GraphSpaceID spaceID, UserID user, Kind op) {
	role = getRoleFromCache(space, user);
	if(acl_check(role, op) == 0) {
		aclcheck_error(space, user, op);
		return cpp2::ErrorCode ::E_INPROPER_ROLE;
	}
	return cpp2::ErrorCode::SUCCEEDED;
}
```

**Comment by sherman-the-tank** [comment]
@boshengchen Awesome summary 👍 

Just one thought, I think the space admin should be able to grant/revoke access right of its space to or from a user

**Comment by boshengchen** [comment]
Good suggest !
Updated permission sheet, added  grant/revoke access right to role `ADMIN`. The ADMIN can only grant/revoke their own space .

**Comment by sherman-the-tank** [comment]
LGTM 👍

**Comment by boshengchen** [comment]
Created two PR as below :
User manager in meta layer : #400 
User manager in graph layer : #480 

About privileges manager PR will be provided at later.
