### ISSUE TITLE
upsert计数功能支持

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1900]
例如我创建好schema，node和edge，然后edge里面有count默认为0

就是不管原来是否有AB两个点我直接可以upsert进去  A->B 他们计数为1， 如果新upsert一个A->B则计数+=1

**Comment by Shylock-Hg** [comment]
I think it's ok now.

**Comment by ownthink** [comment]
&nbsp;说是有bug，目前实现不了，先提个issue记录下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shylock Hg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 上午10:25
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] upsert计数功能支持 (#1900)





 
I think it's ok now.

**Comment by Shylock-Hg** [comment]
我用今天的nightly版本试了一下，没有遇到文问题。
如果你有问题的话，麻烦给一下版本和复现步骤。

**Comment by ownthink** [comment]
&nbsp;好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shylock Hg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 下午3:47
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] upsert计数功能支持 (#1900)





 
我用今天的nightly版本试了一下，没有遇到文问题。
 如果你有问题的话，麻烦给一下版本和复现步骤。

**Comment by laura-ding** [comment]
Has supported.
