### ISSUE TITLE
list的数据类型支持

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1901]
是否可以提供list的数据类型支持，如果方便set集合也支持下。

**Comment by Shylock-Hg** [comment]
Nebula 2.0 will provide this.

**Comment by Qubutol** [comment]
> Nebula 2.0 will provide this.

When will Nebula 2.0 be released？

**Comment by Shylock-Hg** [comment]
> > Nebula 2.0 will provide this.
> 
> When will Nebula 2.0 be released？

@jude-zhu

**Comment by jude-zhu** [comment]
H1

**Comment by whitewum** [comment]
#1454
