### ISSUE TITLE
Package all three daemons and necessary configuration/scripts

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#191]
We need to support three major flavors of the Linux releases: CentOS (rpm), Ubuntu Server (deb), and debian (deb)

**Comment by sherman-the-tank** [comment]
Make sure all binaries are statically linked

**Comment by darionyaphet** [comment]
Currently `RPM` is working well 👍 .

**Comment by sherman-the-tank** [comment]
Done
