### ISSUE TITLE
 Graph gone surprisingly

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1925]
I use nebula studio and docker-compose to create a space and import data. But when I come back to docker days later, I find my graph is gone!!! This is not easy to reproduce and I encounter this twice! Any ideas?

**Comment by nianiaJR** [comment]
Do you start the nebula with docker? If so, I think you can check whether the  docker volume files
have been deleted unexpectly. It looks like a problem of Nebula and  you can also update your docker-compose.yml by `git pull`.
