### ISSUE TITLE
SHOW STATUS

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1926]
nebula services often crash. I think a statement like `SHOW STATUS` to check the services will be a lot of time-saving.

**Comment by whitewum** [comment]
how about show hosts?

**Comment by Amber1990Zhang** [comment]
> how about show hosts?

The `SHOW HOST` shows the host status. But I want one to show the services. OR I have to use the script `./scripts/nebula.service status all`. I want to check services in the shell. I think the two are not the same or did I miss something?

**Comment by whitewum** [comment]
You're right.

**Comment by Shylock-Hg** [comment]
I remember there been a proposal to `show hosts` to support storage and graph process.

**Comment by Amber1990Zhang** [comment]
> I remember there been a proposal to `show hosts` to support storage and graph process.

`SHOW HOSTS` 列出元服务器注册的所有存储主机。`SHOW HOSTS` 输出以下列：IP 地址、端口号、状态（online/offline）、leader 数量、leader 分布、partition 分布。
```ngql
nebula> SHOW HOSTS;
=============================================================================================
| Ip         | Port  | Status | Leader count | Leader distribution | Partition distribution |
=============================================================================================
| 172.28.2.1 | 44500 | online | 0            | No valid partition  | No valid partition     |
---------------------------------------------------------------------------------------------
| 172.28.2.2 | 44500 | online | 2            | NBA: 1, gods: 1     | NBA: 1, gods: 1        |
---------------------------------------------------------------------------------------------
| 172.28.2.3 | 44500 | online | 0            | No valid partition  | No valid partition     |
---------------------------------------------------------------------------------------------
| Total      |       |        | 2            | gods: 1, NBA: 1     | gods: 1, NBA: 1        |
---------------------------------------------------------------------------------------------
```
**NO SERVICE STATUS**

**Comment by jude-zhu** [comment]
show hosts graph/storage/meta
