### ISSUE TITLE
Reject create duplicate index.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#1931]
**Is your feature request related to a problem? Please describe.**
```
(user@127.0.0.1:3699) [shylock_test]> create tag index test_index on test(id)
Execution succeeded (Time spent: 2.061/2.683 ms)

Tue Mar 17 14:24:31 2020

(user@127.0.0.1:3699) [shylock_test]> create tag index test_index_2 on test(id)
Execution succeeded (Time spent: 3.541/4.912 ms)

Tue Mar 17 14:27:35 2020

(user@127.0.0.1:3699) [shylock_test]> show tag indexes
===========================
| Index ID | Index Name   |
===========================
| 4305     | test_index   |
---------------------------
| 4306     | test_index_2 |
---------------------------
Got 2 rows (Time spent: 2.101/3.307 ms)

Tue Mar 17 14:27:53 2020

```
Now the complete same index could be created multiple times, so I think we'd better reject it.

**Describe the solution you'd like**
Encoding the tag/edge_type name and fields name into index name key.(alert/break)

**Describe alternatives you've considered**
Load all relative index and loop checking.

**Additional context**

**Comment by bright-starry-sky** [comment]
This issue related #1695

**Comment by Amber1990Zhang** [comment]
> This issue related #1695

so currently we only check the index name rather than what's inside the index?

**Comment by Shylock-Hg** [comment]
> > This issue related #1695
> 
> so currently we only check the index name rather than what's inside the index?

Yes.
