### ISSUE TITLE
fetch * returns expired data

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1932]
nebula version Git: daa23e09, Build Time: Feb 26 2020

![1](https://user-images.githubusercontent.com/51590253/76834651-8544fd80-6868-11ea-94b2-63a4ff383537.png)

create two tags with ttl
insert a vertex labeled with these two tags
`fetch * ` returns the tag props which should be expired.

**Comment by bright-starry-sky** [comment]
Ready to review?
