### ISSUE TITLE
[Tool] Implement a Data Exporter

### ISSUE THREAD

**Issue by sherman-the-tank** [vesoft-inc/nebula#194]
We need a diagnosis tool to check the data in RocksDB. This tool should be able to generate proper prefixes and dump all KVs. Even better if the tool can decode the value based on the schema

**Comment by wadeliuyi** [comment]
About to get the schema, can I add a handler to storage webservice to get all the schema and other info stored by the storage service?
The tool connect to the webservice auto, and then get all the schema, then the tool disconnect webservice, and load the sst file, then dump the data?

**Comment by sherman-the-tank** [comment]
@wadeliuyi We should avoid using web service in most of the cases, especially dealing with the data (including meta), because it creates security risk

**Comment by wadeliuyi** [comment]
agreed.

**Comment by wadeliuyi** [comment]
As talk offline with @dangleptr, we will design a binary tool to dump the DB, and depend on MetaClient to get the space/part/schema info, and use parameter like —meta_service_ip —meta_service_port to specify the metaservice info.

**Comment by wadeliuyi** [comment]
after talk offline, first dump data for debug, then dump data to some structure file then can import to other system.
