### ISSUE TITLE
Same tags in Vertex

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1944]
I have no idea about this. Same tags in one vertex. Should forbid this? 
![193D3D8E-AE41-4656-A099-48451F746F98](https://user-images.githubusercontent.com/8334944/77037782-12b15a80-69ed-11ea-8880-abcba76d0fdb.png)

**Comment by bright-starry-sky** [comment]
> I have no idea about this. Same tags in one vertex. Should forbid this?
> ![193D3D8E-AE41-4656-A099-48451F746F98](https://user-images.githubusercontent.com/8334944/77037782-12b15a80-69ed-11ea-8880-abcba76d0fdb.png)

Same or Some ?

**Comment by knightXun** [comment]
something like this.
![B317F325-BA8D-49AB-8FBE-74EBF7818C34](https://user-images.githubusercontent.com/8334944/77039928-ea782a80-69f1-11ea-9129-48cdbc818d85.png)

**Comment by jude-zhu** [comment]
I think it makes sense. Refer to neo4j

```
CREATE (n:Dept { id: 34,name:"hello",name:"world" })
```

a node with props of "id: 34 name: world" will be created.
