### ISSUE TITLE
在 ByteGraph 的数据模型中支持双向边，Nebula是否也将会支持呢？

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#1950]
![image](https://user-images.githubusercontent.com/13991775/77155502-95631400-6ad8-11ea-8cd7-a13a073b104c.png)

参考链接：
https://blog.csdn.net/ByteDanceTech/article/details/104509642/

**Comment by Shylock-Hg** [comment]
I think the edge type in nebula is able to represent the forward relationship and backward relationship (reversely go). And even you use double edge to represent one bidirectional edge.
Which is better depend on your design.
If something can't meet you, please tell me.

**Comment by ownthink** [comment]
&nbsp;从设计上来看的话，有好友、合作啊这种的关系都是双向的比较合适啦。当然没有也是可以用的，只是根据图模型来看，如果有双向的更加合适，就像有向图和无向图一样，双向的就属于无向图。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shylock Hg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午9:54
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] 在 ByteGraph 的数据模型中支持双向边，Nebula是否也将会支持呢？ (#1950)





 
I think the edge type in nebula is able to represent the forward relationship and backward relationship (reversely go). And even you use double edge to represent one bidirectional edge.
 Which is better depend on your design.
 If something can't meet you, please tell me.

**Comment by lvphpwb** [comment]
> I think the edge type in nebula is able to represent the forward relationship , backward relationship (reversely go) and bidirectional relationship(bidirect go). And even you can use double edge to represent one bidirectional edge.
> Which is better depend on your design.
> If something can't meet you, please tell me.

麻烦问一下如何方便的取出这种双向关系的，比如和A相互关注的用户

**Comment by Shylock-Hg** [comment]
> > I think the edge type in nebula is able to represent the forward relationship , backward relationship (reversely go) and bidirectional relationship(bidirect go). And even you can use double edge to represent one bidirectional edge.
> > Which is better depend on your design.
> > If something can't meet you, please tell me.
> 
> 麻烦问一下如何方便的取出这种双向关系的，比如和A相互关注的用户

E.G.
```sql
go 1 step from A over like yield like._dst as dst | go from $-.dst over like where like._dst == A yield like._src
```

**Comment by lvphpwb** [comment]
感谢您的回复， 这个相当于是做了子查询，不知道会不会有性能问题，如果A关注的数量比较庞大，不知道内部是否有机制来做这个筛选，还是说需要业务方自己去实现，比如给like加一个属性both

**Comment by Shylock-Hg** [comment]
> 感谢您的回复， 这个相当于是做了子查询，不知道会不会有性能问题，如果A关注的数量比较庞大，不知道内部是否有机制来做这个筛选，还是说需要业务方自己去实现，比如给like加一个属性both

如果A关注比较多，可以在第一个go里面加一个limit

**Comment by lvphpwb** [comment]
加上limit那数据查询的就不全面了

**Comment by Shylock-Hg** [comment]
> 加上limit那数据查询的就不全面了

一次性要全部数据的场景应该不会很多。

**Comment by lvphpwb** [comment]
其实我们并不是要全量数据，如比A关注了1万个人，A被100个人关注，我们要获取的是和A相互关注的哪些人，如果在第一个go里用limit，这个是不好加的，因为没有人知道和A相互关注的人的排序，除非limit 10000才能保证是全的，如果limit 1000,很可能返回的数据是空的

**Comment by Shylock-Hg** [comment]
> 其实我们并不是要全量数据，如比A关注了1万个人，A被100个人关注，我们要获取的是和A相互关注的哪些人，如果在第一个go里用limit，这个是不好加的，因为没有人知道和A相互关注的人的排序，除非limit 10000才能保证是全的，如果limit 1000,很可能返回的数据是空的

这个在目前的数据存储结构上是可以优化的，主要是在storage这边一次性处理点的出边和入边并且给指向的点取个交集，不过目前的storage查询接口这里还没这样的接口，你可以在论坛里发帖提一下这个优化需求，我们后续会评估。

**Comment by lvphpwb** [comment]
嗯 了解了，感谢耐心的解答~~
