### ISSUE TITLE
Can't access nebula graph on AWS with Public IP address

### ISSUE THREAD

**Issue by gcameo** [vesoft-inc/nebula#1961]
Hi All,

I have run the nebula graph using both the docker-compose and the manual installation steps on an AWS instance. However, I am unable to access the graph-server externally using the public IP address of the server. Is there a configuration that I need to change to make it externally accessible?

**Comment by Shylock-Hg** [comment]
Can you ping to the nebula port ?

**Comment by gcameo** [comment]
The problem was the AWS VPC. I fixed it and it was good. Thanks
