### ISSUE TITLE
Authentication for Java Client and Nebula CLI completely broken.

### ISSUE THREAD

**Issue by gcameo** [vesoft-inc/nebula#1963]
With both  clients, wrong credentials allow access to the database

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Set username and password in Java client to any rubbish
2. Set username and password in CLI to any rubbish

**Expected behavior**
Expecting authentication failure

**Additional context**

Welcome to Nebula Graph (Version 2020.03.23-nightly)

**Comment by bright-starry-sky** [comment]
Thanks for your trial. 
This problem is not caused by client . Please check the configuration parameter of nebula server (in nebula-graphd.conf).
`--enable_authorize=false ` , default the authorize is turn off . you better turn on before start `nebula-graphd`.

**Comment by gcameo** [comment]
Thanks very much. Will make that change but I think it will be better if authentication is enabled by default so customers don't mistakenly expose their data. Security by default is a good principle
