### ISSUE TITLE
Some rocksdb option wrong, storaged upgrade and can't start

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1966]
ERROR:

update rocksdb_column_family_options from {"write_buffer_size":"67108864","max_write_buffer_number":"4","max_bytes_for_level_base":"268435456","bloom_locality":"1"} to {"max_background_compactions":"4","level0_file_num_compaction_trigger":"2","bloom_locality":"1","disable_auto_compactions":"false","max_background_jobs":"8","max_bytes_for_level_base":"268435456","max_write_buffer_number":"4","write_buffer_size":"67108864"}

I upgrade storaged version from Feb.20 to Mar 24.

I've update config several times.

I think it's due to rocksdb options check.

**Comment by critical27** [comment]
What do you mean ERROR, I can't update it in console, `update configs storage:rocksdb_column_family_options = {max_background_compactions=4, level0_file_num_compaction_trigger=2, disable_auto_compactions=false, max_background_jobs=8, max_bytes_for_level_base = 268435456, max_write_buffer_number = 4, bloom_locality = 1, write_buffer_size = 67108864}`

Only some options which can be updated for now, in your example, `bloom_locality` and `write_buffer_size` is not supported.

**Comment by critical27** [comment]
That's because some option can't be set dynamically, in your case, "bloom locality" and "write_buffer_size". And for now we just return error. How about these ones take effact when storage restart?

**Comment by critical27** [comment]
And some option is not the `rocksdb_column_family_options`, that would make the storage
 fail to start when you reboot.

**Comment by whitewum** [comment]
> And some option is not the `rocksdb_column_family_options`, that would make the storage
> fail to start when you reboot. You need to find out which is rocksdb_column_family_options and rocksdb_db_options.

Correct. I mix and didn't look carefully at these two kinds of options.

My suggestion is a warning or error when setting config incorrectly. There are too many options in Rocksdb, and error-prone to set them.

It's better than accept the option when setting and fail to restart. 

So, you can fix this issue later.
