### ISSUE TITLE
edge insert succeeded even without dest vertex

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#1984]
It's confusing that nebula tells me `Execution succeeded` when I try to insert edge for the non-existed vertex.
```
(user@127.0.0.1:3699) [gods]> fetch prop on * 108
Execution succeeded (Time spent: 7.889/10.639 ms)  # Vertex not existed!

(user@127.0.0.1:3699) [gods]> INSERT EDGE e1() VALUES 100->108:()
Execution succeeded (Time spent: 2.537/4.017 ms) # Vertex not existed!
```
 can you make the return message more clear like `Vertex not existed!` rather than `Execution succeeded`? The message is confusing.

**Comment by Shylock-Hg** [comment]
We don't check the vertex when insert edge now.

**Comment by whitewum** [comment]
> We don't check the vertex when insert edge now.

Right, that's Nebula's design.
