### ISSUE TITLE
A compilation error may occur

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula#1986]
**Describe the bug (__must be provided__)**
When not using the -j $ (nproc) parameter, compilation errors may occur, even when using -j1

**Your Environments (__must be provided__)**

* OS: centos7   3.10.0-1062.18.1.el7.x86_64
* Compliler: cmake version 3.15.5
g++ (Nebula Graph Build) 7.5.0
* CPU: intel xeon 8260M
* Commit id 499bbedeb499aefdd8fab8a4e83dcca1f505fa52

**How To Reproduce(__must be provided__)**

1. Step 1
`git clone https://github.com/vesoft-inc/nebula.git`
`cd nebula && mkdir build && cd build`

2. Step 2
`../third-party/install-cmake.sh cmake-install`
`source cmake-install/bin/enable-cmake.sh`
`../third-party/install-gcc.sh --prefix=/opt`
`source /opt/vesoft/toolset/gcc/7.5.0/enable`

3. Step 3
`cmake -DENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX=$PWD/install ..`
`make -j1` or `make`

![image](https://user-images.githubusercontent.com/58841610/77629848-20368980-6f85-11ea-8155-d783058063c7.png)

**Expected behavior**

Compile completed

**Comment by laura-ding** [comment]
I discussed it with @bright-starry-sky . he will solve the problem.

**Comment by bright-starry-sky** [comment]
Fixed via pr #1995
