### ISSUE TITLE
alter tag with [default] not working.

### ISSUE THREAD

**Issue by Qubutol** [vesoft-inc/nebula#1987]
**Describe the bug (__must be provided__)**

 I using alter tag with [default],it’s still not working.

**Your Environments (__must be provided__)**

* OS: `centos7`
* nebula-2020.03.20-nightly.el7-5.x86_64

**How To Reproduce(__must be provided__)**

1. Step 1
```
create tag t2 (name string default "N/A", age int default -1);
INSERT VERTEX t2() VALUES 11:();
fetch prop on t2 11;
```
I got:
![image](https://user-images.githubusercontent.com/46239712/77629476-8a026380-6f84-11ea-9ff3-cfb9b5b12123.png)
2. Step 2
and then,I execute:
```
ALTER tag t2 add (description string default "none");
fetch prop on t2 11
```
I got:
![image](https://user-images.githubusercontent.com/46239712/77629607-c1711000-6f84-11ea-95cb-d3dacd663231.png)
3. Step 3
exectue:
```
INSERT VERTEX t2() VALUES 11:()
```
give me a error message:
```
[ERROR (-8)]: `description' not exist default value
```
**Expected behavior**

t2.description have a default value .

**Comment by Shylock-Hg** [comment]
Same for edge.

**Comment by Shylock-Hg** [comment]
Alter don't write default value.
