### ISSUE TITLE
Can't  "submit job flush; submit job compact;" in one sentence

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#1989]
**Describe the bug (__must be provided__)**

I think in one sentence, two jobs can't be submitted.

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1 
run "submit job flush; submit job compact;" in the command line;
2. Step 2
show jobs
3. Step 3
you can't see the flush job.

**Expected behavior**

I can the see flush job id. or 'flush job' return failed is also acceptable.

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by liuyu85cn** [comment]
not repro on my side (56a9c3c4), may be check later
