### ISSUE TITLE
Can't delete vertex

### ISSUE THREAD

**Issue by Qubutol** [vesoft-inc/nebula#1996]
**Describe the bug (__must be provided__)**
when I delete a vertex,I got:
```
[ERROR (-8)]: SpaceId `98'  is nonexistent
```
**Your Environments (__must be provided__)**

* OS: `centos7`
* version:nebula-2020.03.20-nightly.el7-5.x86_64

**How To Reproduce(__must be provided__)**

1. Step 1
```
use nba
CREATE TAG person(name string, age int);
CREATE TAG INDEX person_index on person(name,age);
```
2. Step 2
```
INSERT VERTEX person(name, age) VALUES 101:("Tony Parker", 36);
```
3. Step 3
```
DELETE VERTEX 101
```
I got:
```
[ERROR (-8)]: SpaceId `98'  is nonexistent
```
but I describe space nba :
```
DESCRIBE SPACE nba
```
![image](https://user-images.githubusercontent.com/46239712/77661664-e7fb6f00-6fb5-11ea-9580-a19c871ea671.png)

**Expected behavior**

delete vertex 101

log:
E0326 22:56:47.638962 30576 ExecutionPlan.cpp:76] Execute failed: SpaceId `98'  is nonexistent

**Comment by jude-zhu** [comment]
(*￣︶￣) we run into this problem yesterday. Simon is working on it.

**Comment by Qubutol** [comment]
> (*￣︶￣) we run into this problem yesterday. Simon is working on it.


Will this bug be fixed today? I see that the corresponding pull request has been read for test. Today's nightly version will merge this part of the code?
