### ISSUE TITLE
Raft成员变更疑问

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#1997]
现在nebula在做负载均衡时，变更raft成员的时候由meta server控制，没有走raft协议，MEMBER_CHANGE_ADD和MEMBER_CHANGE_REMOVE之间不是原子操作，是不是可能存在日志丢失的风险？
假设有一个part包含A/B/C三个副本，A是leader，把B迁移到D。在D的日志追上来后进行MEMBER_CHANGE_ADD。由于负载均衡时不停止写服务，假设有一个客户端向A提交一个改动，由于网络原因A执行raft协议的时候只有B成功了，但是对A来说满足了多数派，所以给客户端响应成功。此时meta server发出MEMBER_CHANGE_REMOVE请求，B被删除后A挂掉了，这样新写的数据就可能丢失了

**Comment by silverdays** [comment]
you're welcome to discuss in the forum https://discuss.nebula-graph.io/

**Comment by whitewum** [comment]
you're welcome to discuss this in the forum.

https://discuss.nebula-graph.io/

**Comment by critical27** [comment]
MEMBER_CHANGE_REMOVE这条日志都谁成功了？

**Comment by wadeliuyi** [comment]
> MEMBER_CHANGE_REMOVE这条日志都谁成功了？由于此时Add已经成功，大多数需要3个节点有这条日志，无论是ABC/ABD/ACD哪种情况，即便A挂了，仍然有其他节点有remove这条日志。

在RaftPart::addPeer中重新RaftPart::updateQuorum的时候，因为当前total是4，所以算出来的quorum_ = (total + 1) / 2; quorum是2，所以提交的改动只要有两个节点响应成功就会返回给客户端成功：如果是A和B成功，在remove peer的时候B被删除了，然后A挂掉了，C/D就没有这个日志了

**Comment by wadeliuyi** [comment]
仔细看了一下代码，我搞错了，nebula实现的成员变更是严格按照raft论文的成员变更步骤做的，点赞
