### ISSUE TITLE
`CREATE TAG` return Permission denied when im a root user

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#1999]
![image](https://user-images.githubusercontent.com/51590253/77711533-46533c80-700c-11ea-82e8-9a9af565b2cf.png)

When I create a tag before using a space， it returns `PermissionError: Permission denied`. However, I logged in as a root user.

**Comment by bright-starry-sky** [comment]
are you use space first?

**Comment by bright-starry-sky** [comment]
if not use space means you don't have any authority.
