### ISSUE TITLE
Insert edge failed,  error: Type Conversion Failed

### ISSUE THREAD

**Issue by Qubutol** [vesoft-inc/nebula#2009]
**Describe the bug (__must be provided__)**

When I execute Insert edge, I got error message : Type Conversion Failed

**Your Environments (__must be provided__)**

* OS: `CentOS7`
* version:nebula-2020.03.26-nightly.el7-5.x86_64

**How To Reproduce(__must be provided__)**

1. Step 1
```
CREATE EDGE IF NOT EXISTS relation(intimacy int default 0,isReversible bool default false,name string default "N/A",startTime timestamp default 0);
CREATE EDGE INDEX IF NOT EXISTS relation_intimacy on relation(intimacy);
CREATE EDGE INDEX IF NOT EXISTS relation_isReversible on relation(isReversible);
CREATE EDGE INDEX IF NOT EXISTS relation_name on relation(name);
CREATE EDGE INDEX IF NOT EXISTS relation_startTime on relation(startTime);
```
2. Step 2
```
INSERT EDGE relation (intimacy) VALUES hash("person.Tom") -> hash("person.Marry")@0:(3);
INSERT EDGE relation (intimacy) VALUES hash("person.Marry") -> hash("person.Tom")@0:(4);
```
then,I got:
```
[ERROR (-8)]: Type Conversion Failed
```
**Expected behavior**

insert success

**Additional context**

I0328 00:15:52.267992 29114 ExecutionPlan.cpp:16] Parsing query: INSERT EDGE relation (intimacy) VALUES hash("person.Marry") -> hash("person.Tom")@0:(4);
E0328 00:15:52.270124 29114 Executor.cpp:448] Conversion to int64_t failed: 
E0328 00:15:52.270243 29114 InsertEdgeExecutor.cpp:247] Insert edge failed, error Type Conversion Failed
E0328 00:15:52.270267 29114 ExecutionPlan.cpp:76] Execute failed: Type Conversion Failed

**Comment by Shylock-Hg** [comment]
The default value bug, I had refactor the default value, it's seems solved in this PR.
TODO:Add to cases.
