### ISSUE TITLE
RC3 update to RC4, lookup can't find the item

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#2017]
update from RC3 (with data) to RC4, and create an index.

![image](https://user-images.githubusercontent.com/51590253/77883370-942ea580-7295-11ea-94e6-06848d0808fb.png)

i rebuilt the index offline.

![image](https://user-images.githubusercontent.com/51590253/77883403-a6104880-7295-11ea-95fa-04ac82e0fffc.png)

```
 > show tag index status
=====================================
| Name           | Tag Index Status |
=====================================
| player_index_0 | SUCCEEDED        |
-------------------------------------
Got 1 rows (Time spent: 2.508/4.191 ms)
```

However, lookup can't find the item.
![image](https://user-images.githubusercontent.com/51590253/77883494-d35cf680-7295-11ea-8bc0-e1822a61d821.png)

**Comment by bright-starry-sky** [comment]
Please check that the index exists before create new index

**Comment by bright-starry-sky** [comment]
This issue seem with #2027 
Please check that the index exists before create new index after upgraded to RC4. 
I was verified lookup work well as below step : 

1. setup rc3 cluster environment.
2. create space; use space; create tag; insert vertices
3. shutdown cluster and upgrade to rc4
4. startup cluster, use space; create tag index; rebuild index;
5. lookup ; <-- now , the lookup works well.

And refer to #2027 , if index created in rc3, the lookup don't work after rebuild index.
