### ISSUE TITLE
Insertting this EDGE data reports error

### ISSUE THREAD

**Issue by Anyzm** [vesoft-inc/nebula#2018]
CREATE EDGE call( \
    earliest_call_time timestamp default 0 , \
    latest_call_time timestamp default 0 , \
    call_out_times int default 0 , \
    call_in_times int default 0 , \
    call_out_period int default 0 , \
    call_in_period int default 0 , \
    fetch_time string default "" , \
    is_mgm bool default false , \
    mgm_time string default ""  \
);

INSERT EDGE call(call_out_times,call_in_times,call_out_period,call_in_period,fetch_time,is_mgm,mgm_time) values uuid("5890ad05f669ec35abdddb67cae1a99a")->uuid("7f290081c4ab9095f6da007cc9ca38c4"):(10,10,10,10,"",false,"");

[ERROR (-8)]: Type Conversion Failed

to insert 9 properties and omit 2 properties which have default values

**Comment by Shylock-Hg** [comment]
Duplicate with #2009
