### ISSUE TITLE
change TTL_DURATION to uint64 

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#2019]
too large negative TTL_DURATION is anti-instinct, `0` is enough to represent never expire

![image](https://user-images.githubusercontent.com/8334944/77891407-7ff1a500-72a3-11ea-88f1-55b86972a58d.png)
![image](https://user-images.githubusercontent.com/8334944/77891437-8a13a380-72a3-11ea-81be-e898ec0b9902.png)

**Comment by panda-sheep** [comment]
I don't think this is a bug. Because it was originally designed like this.
Even if there is an issue, to impove

**Comment by panda-sheep** [comment]
fixed in #2012
