### ISSUE TITLE
wrong error message 

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#2021]
![image](https://user-images.githubusercontent.com/8334944/77891499-a31c5480-72a3-11ea-8555-82061d83919d.png)

**Comment by Shylock-Hg** [comment]
Can't reproduce.
Could provide the version and steps?

**Comment by Shylock-Hg** [comment]
Can't produce.
Could provide the version and steps?

**Comment by Shylock-Hg** [comment]
When edge not exist.
