### ISSUE TITLE
多线程中用ctx->results.size() >= n 更合适

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#2026]
https://github.com/vesoft-inc/nebula/blob/76e2529bbca4042330ab0919391394cc6b74314d/src/common/base/CollectNSucceeded.inl#L61

如果两个线程在判断ctx->nSucceeded == n 同时调用了++ctx->nSucceeded;就会超过n

**Comment by Shylock-Hg** [comment]
I think the atomic will limit it.

**Comment by dangleptr** [comment]
Indeed, it is a problem.  So if you want a thread-safe collectN,  please refer to folly::collectN

**Comment by wadeliuyi** [comment]
I get it, it is my fault, in nebula, the eb is from raft is local thread.
