### ISSUE TITLE
Should forbid `hdfs ls` 

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#2041]
`hdfs dfs -ls` could make namenode crash, we should carefully use this. please use another way.
![image](https://user-images.githubusercontent.com/8334944/78114413-d2fa6200-7433-11ea-84d2-cd68e0c32612.png)

**Comment by imbajin** [comment]
Could u explain why and how `ls` make NN crash ❓ 

And if you don't use ls, what command are you going to use ❔

**Comment by knightXun** [comment]
@imbajin that's long story

**Comment by darionyaphet** [comment]
Single list the directory is safe.
