### ISSUE TITLE
docker pull vesoft/nebula-console:nightly error

### ISSUE THREAD

**Issue by sail0755** [vesoft-inc/nebula#2044]
[admin@errer nebula-docker-compose]$ sudo docker pull vesoft/nebula-console:nightly
Trying to pull repository docker.io/vesoft/nebula-console ...
nightly: Pulling from docker.io/vesoft/nebula-console
ab5ef0e58194: Already exists
9fdb7d5fbf2f: Pulling fs layer
d3b2de6c28d3: Pulling fs layer
error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error

**Comment by nianiaJR** [comment]
you can try again. I think it may be a problem of network.

**Comment by whitewum** [comment]
That's some connection error dockerhub.com

**Comment by whitewum** [comment]
You're welcome to discuss at https://discuss.nebula-graph.io/
