### ISSUE TITLE
go ... step ... where...中的filter只作用于最后一跳，这样是否符合语义？

### ISSUE THREAD

**Issue by xuguruogu** [vesoft-inc/nebula#2048]
https://github.com/vesoft-inc/nebula/blob/eea740763e3d7385588c3e291553d9f9614cea44/src/graph/GoExecutor.cpp#L570-L586

按照一般的理解，filter应该在每一跳中都会起到左右。

**Comment by CPWstatic** [comment]
The `FILTER` applys to the `result` which means the last hop of `GO`. A `GO` statement would always return the result of last hop. And if you want filts the data from the interim, you could use the `PIPE`.
```
 GO ... WHERE ... | GO ... WHERE ...
```

**Comment by whitewum** [comment]
you're welcome to discuss further in https://discuss.nebula-graph.io/
