### ISSUE TITLE
支持 $$.id 返回多条边遍历 顶点id合并

### ISSUE THREAD

**Issue by blacklovebear** [vesoft-inc/nebula#2052]
当通过多条边遍历的时候，想获取多条边遍历的顶点id的时候只能显示为多列。能否合并为一列显示

**Comment by Shylock-Hg** [comment]
为什么要吧不同的边属性合并到一列？这样会丢失一定的信息，作为一个基础的数据库产品，我们不会选择这样做。用户可以在自己的应用软件里根据自己的需求进行列合并。

**Comment by whitewum** [comment]
如果你有更详细的讨论想法，欢迎在论坛上留言，让更多人参与讨论。
https://discuss.nebula-graph.io/
