### ISSUE TITLE
Cant' create space

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#2071]
First show spaces:
```
nebula> SHOW SPACES;
===========
| Name    |
===========
| NBA     |
-----------
| gods    |
-----------
| NBA_doc |
-----------
```

![image](https://user-images.githubusercontent.com/42762957/78975836-94f1f200-7b47-11ea-9430-d0d89e5886f7.png)
Then I create a space named `test`
```
nebula> create space test(partition_num = 1, replica_factor = 1)
Create space `test' failed: existed!.
```

![image](https://user-images.githubusercontent.com/42762957/78976557-f8c8ea80-7b48-11ea-998b-ba501a1d9a93.png)

**Comment by Shylock-Hg** [comment]
Can't reproduce directly, could provide more detail?

**Comment by jude-zhu** [comment]
I gonna close it, you can reopen it when reproduce.
