### ISSUE TITLE
how to use lookup return vertex's prop when search edge

### ISSUE THREAD

**Issue by firepation** [vesoft-inc/nebula#2072]
when use lookup to search edge, the return column is SrcVID,DstVID,Ranking, if i want to yield source and target vertex‘s property, how can i do ?

**Comment by laura-ding** [comment]
LOOKUP ON edgeType WHERE edgeType.col == "XXX" | FETCH prop on tagType $-.SrcVID UNION LOOKUP ON edgeType WHERE edgeType.col == "XXX" | FETCH prop on tagType $-.DstVID

**Comment by laura-ding** [comment]
Better

```
$var = LOOKUP ON edgeType WHERE edgeType.col == "hh";FETCH PROP ON tagType $var.SrcVID UNION FETCH PROP ON tagType $var.DstVID
```
