### ISSUE TITLE
Should return null if  there is not a dst_id from one vertex by some edge

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula#2080]
**Describe the bug (__must be provided__)**
```
// I have this query
GO from 2 over invested, own, employed;
```
output:

invested._dst | own._dst | employed._dst
-- | -- | --
0 | 22 | 0

**Steps to reproduce the behavior:**

Only need to go from one vertex over edge1,egde2,edge3
If there is no dest id, it just return 0 as the default id.

**Expected behavior**

If there is no id, just return null instead of 0.

**Additional context**

**Comment by jude-zhu** [comment]
sorry, we don't support null in Nebula 1.0
