### ISSUE TITLE
submit job compact always fail.

### ISSUE THREAD

**Issue by xuguruogu** [vesoft-inc/nebula#2081]
![image](https://user-images.githubusercontent.com/6092236/79455626-c2471000-801f-11ea-819c-bc4b30bcae8c.png)

pia pia pia.

**Comment by whitewum** [comment]
please provide graphd  and storaged logs.
I've met this error before, and added some logs.

**Comment by liuyu85cn** [comment]
may be the http request blocked by firewall ? 
you my try this manually
curl "http://9.189.131.201:12000/admin?space=finder&op=compact"

**Comment by whitewum** [comment]
#1813

**Comment by xuguruogu** [comment]
Yep, correct after change http listen network.
