### ISSUE TITLE
run ut config_man_test crash

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#2082]
gdb> bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fe141234895 in __GI_abort () at abort.c:79
#2  0x00007fe141234769 in __assert_fail_base (fmt=0x7fe14139bea8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x1a7925b "!ShouldScheduleFlush()", file=0x1a790d8 "/root/nebula-3rdparty/third-party/rocksdb/_build/rocksdb-5.15.10/db/memtable.cc", line=107, function=<optimized out>) at assert.c:92
#3  0x00007fe1412429f6 in __GI___assert_fail (assertion=0x1a7925b "!ShouldScheduleFlush()", file=0x1a790d8 "/root/nebula-3rdparty/third-party/rocksdb/_build/rocksdb-5.15.10/db/memtable.cc", line=107, 
    function=0x1a79d80 <rocksdb::MemTable::MemTable(rocksdb::InternalKeyComparator const&, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::WriteBufferManager*, unsigned long, unsigned int)::__PRETTY_FUNCTION__> "rocksdb::MemTable::MemTable(const rocksdb::InternalKeyComparator&, const rocksdb::ImmutableCFOptions&, const rocksdb::MutableCFOptions&, rocksdb::WriteBufferManager*, rocksdb::SequenceNumber, uint32_t"...) at assert.c:101
#4  0x0000000001087557 in rocksdb::MemTable::MemTable(rocksdb::InternalKeyComparator const&, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::WriteBufferManager*, unsigned long, unsigned int) ()
#5  0x000000000118c5d8 in rocksdb::ColumnFamilyData::ConstructNewMemtable(rocksdb::MutableCFOptions const&, unsigned long) ()
#6  0x000000000100dce3 in rocksdb::DBImpl::SwitchMemtable(rocksdb::ColumnFamilyData*, rocksdb::DBImpl::WriteContext*, rocksdb::FlushReason) ()
#7  0x000000000100ea8d in rocksdb::DBImpl::ScheduleFlushes(rocksdb::DBImpl::WriteContext*) ()
#8  0x000000000100ef67 in rocksdb::DBImpl::PreprocessWrite(rocksdb::WriteOptions const&, bool*, rocksdb::DBImpl::WriteContext*) ()
#9  0x00000000010136e0 in rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*) ()
#10 0x0000000001015351 in rocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*) ()
#11 0x0000000000f82c09 in nebula::kvstore::RocksEngine::commitBatchWrite (this=0x7fe123c02100, batch=..., disableWAL=true) at /home/wade.liu/rd/nebula/src/kvstore/RocksEngine.cpp:126
#12 0x0000000000f7490a in nebula::kvstore::Part::commitLogs (this=0x7fe123c85b10, iter=...) at /home/wade.liu/rd/nebula/src/kvstore/Part.cpp:308
#13 0x0000000000f14446 in nebula::raftex::RaftPart::processAppendLogResponses (this=0x7fe123c85b10, resps=..., eb=0x7fe0eda07000, iter=..., currTerm=1, lastLogId=3, committedId=2, prevLogTerm=1, prevLogId=2, hosts=...) at /home/wade.liu/rd/nebula/src/kvstore/raftex/RaftPart.cpp:881
#14 0x0000000000f132e5 in nebula::raftex::RaftPart::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::operator()(folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > &&) (__closure=0x7fe0ef620c80, result=...) at /home/wade.liu/rd/nebula/src/kvstore/raftex/RaftPart.cpp:817
#15 0x0000000000f258f9 in folly::futures::detail::CoreCallbackState<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >, nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)> >::invoke<folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > >(folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > &&) (this=0x7fe0ef620c80, args#0=...) at /opt/vesoft/third-party/include/folly/futures/Future-inl.h:91
#16 0x0000000000f2593a in folly::futures::detail::detail_msvc_15_7_workaround::invoke<true, folly::futures::detail::CoreCallbackState<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >, nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)> >, std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >, folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&>(folly::futures::detail::CoreCallbackState<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >, nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)> > &, folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > &) (state=..., t=...) at /opt/vesoft/third-party/include/folly/futures/Future-inl.h:288
#17 0x0000000000f2596e in folly::futures::detail::FutureBase<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::<lambda()>::operator()(void) const (this=0x7fe1231fcc70) at /opt/vesoft/third-party/include/folly/futures/Future-inl.h:359
#18 0x0000000000f2bd4b in folly::makeTryWith<folly::futures::detail::FutureBase<T>::thenImplementation(F&&, folly::futures::detail::argResult<isTry, F, Args ...>) [with F = nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)>; R = folly::futures::detail::callableResult<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >, nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)> >; bool isTry = true; Args = {folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&}; T = std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >]::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)> mutable::<lambda()> >(folly::futures::detail::FutureBase<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::<lambda()> &&) (f=...) at /opt/vesoft/third-party/include/folly/Try-inl.h:156
#19 0x0000000000f259ac in folly::futures::detail::FutureBase<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::operator()(folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > &&) (
    this=0x7fe0ef620c80, t=...) at /opt/vesoft/third-party/include/folly/futures/Future-inl.h:357
#20 0x0000000000f40448 in folly::detail::function::FunctionTraits<void(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::callBig<folly::futures::detail::FutureBase<T>::thenImplementation(F&&, folly::futures::detail::argResult<isTry, F, Args ...>) [with F = nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)>; R = folly::futures::detail::callableResult<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >, nebula::raftex::RaftPart::replicateLogs(folly::EventBase*, nebula::raftex::AppendLogsIterator, nebula::TermID, nebula::LogID, nebula::LogID, nebula::TermID, nebula::LogID)::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)> >; bool isTry = true; Args = {folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > > >&&}; T = std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> >]::<lambda(folly::Try<std::vector<std::pair<long unsigned int, nebula::raftex::cpp2::AppendLogResponse> > >&&)> >(folly::detail::function::Data &, folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > > &&) (p=..., args#0=...) at /opt/vesoft/third-party/include/folly/Function.h:319
#21 0x0000000000f3d8c0 in folly::detail::function::FunctionTraits<void (folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >&&)>::operator()(folly::Try<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >&&) (this=0x7fe0ef612b40, args#0=...) at /opt/vesoft/third-party/include/folly/Function.h:328
#22 0x0000000000f389ea in folly::futures::detail::Core<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >::doCallback()::{lambda()#2}::operator()() (this=0x7fe0ef620dd0)
    at /opt/vesoft/third-party/include/folly/futures/detail/Core.h:529
#23 0x0000000000f43009 in folly::detail::function::FunctionTraits<void ()>::callSmall<folly::futures::detail::Core<std::vector<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse>, std::allocator<std::pair<unsigned long, nebula::raftex::cpp2::AppendLogResponse> > > >::doCallback()::{lambda()#2}>(folly::detail::function::Data&) (p=...) at /opt/vesoft/third-party/include/folly/Function.h:313
#24 0x000000000050e035 in folly::detail::function::FunctionTraits<void ()>::operator()() (this=0x7fe0ef620dd0) at /opt/vesoft/third-party/include/folly/Function.h:328
#25 0x00000000004f7db2 in apache::thrift::concurrency::FunctionRunner::run (this=0x7fe0ef620dc0) at /opt/vesoft/third-party/include/thrift/lib/cpp/concurrency/FunctionRunner.h:135
#26 0x00000000004f8d9a in apache::thrift::concurrency::ThreadManager::Task::run (this=0x7fe0f08140c0) at /opt/vesoft/third-party/include/thrift/lib/cpp/concurrency/ThreadManager-impl.h:61
#27 0x000000000056f091 in apache::thrift::concurrency::ThreadManager::ImplT<folly::LifoSemImpl<std::atomic, folly::SaturatingSemaphore<true, std::atomic> > >::Worker<folly::LifoSemImpl<std::atomic, folly::SaturatingSemaphore<true, std::atomic> > >::run (this=0x7fe1407eb3d0)
    at /opt/vesoft/third-party/include/thrift/lib/cpp/concurrency/ThreadManager-inl.h:149
#28 0x000000000131fcc6 in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
#29 0x00007fe1413e058e in start_thread (arg=<optimized out>) at pthread_create.c:486
#30 0x00007fe14130f513 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by critical27** [comment]
Propbaly you need to update the rocksdb version
