### ISSUE TITLE
how to get edgeType by edgeId

### ISSUE THREAD

**Issue by firepation** [vesoft-inc/nebula#2099]

**Comment by darionyaphet** [comment]
Do you mean get edge type by edge name？You can try `desc edge ${edge_name}.`

**Comment by firepation** [comment]
> Do you mean get edge type by edge name？You can try `desc edge ${edge_name}.`

no, the final goal is fetch prop throught edgeId, but i can't know it's type, so i want to know how can i can get edgetype throught edgeid

**Comment by darionyaphet** [comment]
I think `Edge Type` is `Edge ID`.

**Comment by Shylock-Hg** [comment]
The edge id(src->dst) to edge type is one-to-many, it's confused to do this. And now we can't list the all edge type of one edge id.
