### ISSUE TITLE
tag and tag schema support Chinese or UTF-8

### ISSUE THREAD

**Issue by yes7rose** [vesoft-inc/nebula#2120]
create tag 人(name string)
create tag 人(名字 string)

[ERROR (-7)]: SyntaxError: syntax error near `人(name'

**Comment by liuyu85cn** [comment]
currently, we don't support chinese tags

**Comment by ffteen** [comment]
用base64能凑一下不？主要是+ / = 这三个符号能用进去不

**Comment by ffteen** [comment]
用base64能凑一下不？主要是+ / = 这三个符号能用进去不

**Comment by zhang703652632** [comment]
老师，我来了，还是想问下导出数据，用python代码实现的方式可以实现批量导出吗？在nebula-graph-studio中的导出，是导出来探索的数据，查到几条就可以导出几条？代码中也能通过查询的方式导出写入是吗？

**Comment by wey-gu** [comment]
> 老师，我来了，还是想问下导出数据，用python代码实现的方式可以实现批量导出吗？在nebula-graph-studio中的导出，是导出来探索的数据，查到几条就可以导出几条？代码中也能通过查询的方式导出写入是吗？

您这个问题和这个issue 无关，回到论坛回答你。
