### ISSUE TITLE
 some questions for Multi-Raft optimization ? 

### ISSUE THREAD

**Issue by triump2020** [vesoft-inc/nebula#2121]
Hi, nebula contributors !
       
    I  have some questions for raft optimization below:
      1.  Raft can support out-of-order commits  according to some business cases ?
      2.  If Per WAL file Per partion  , one storage server maybe holds thousands of partions, so it has
          thousands of WAL files , It causes a lot of disk random writes ?  Besides, It is not convenient to 
          restore the data when the machine is powered off and restarted ?

**Comment by critical27** [comment]
1. Raft do can support out-of-order commits, just as you said, it acquires raft knows what kind of log entry it is. Since this raft is used for general purpose, we didn't implement this for now.
2. I think wal write is not random writes, it is sequential write of several wal files? When power off and restart, each partition will replay its own wal file.

**Comment by Shylock-Hg** [comment]
> 1. Raft do can support out-of-order commits, just as you said, it acquires raft knows what kind of log entry it is. Since this raft is used for general purpose, we didn't implement this for now.
> 2. I think wal write is not random writes, it is sequential write of several wal files? When power off and restart, each partition will replay its own wal file.

I think the raft log replay must done by leader or there is consistency problem in some cases.

**Comment by triump2020** [comment]
1.   If  Per WAL file Per partion,   when multiple partion raft logs are fsyncing to disk,  the writer  
     have to  jump among  the disks ,   can  leads to a  io latency.  Isn't it ?

**Comment by critical27** [comment]
Yeah, indeed, we do need to jump among different wal files. It is trade off, if all partition share a same wal, all partition need to acquire the lock.

**Comment by triump2020** [comment]
Thanks !
