### ISSUE TITLE
Expose ”Address already in use“ when start the service

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#2127]
when start the service using "nebula.service", it says done. However, when I check the log, "Address already in use"

**Comment by dutor** [comment]
I don't think it's necessary to make `nebula.service start` do what `nebula.service status` does. The daemons work in a kind of async way, that says launch a process, do some simple sanity checks, fork a child process then exit(sucessfuly). The actual service runs in the child process.

So, the `nebula.service` script cannot tell if the child process was properly launched. 

FYI. You could refer to the way how `systemctl` works.

**Comment by jude-zhu** [comment]
relate to #1304
