### ISSUE TITLE
[doc] submit/show job privilege   

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#2178]
please specify the job privilege

![image](https://user-images.githubusercontent.com/50101159/84367902-72dc2500-ac07-11ea-81d8-0c7732893a7a.png)

**Comment by liuyu85cn** [comment]
job manager consider nothing about user privilege, this means for any user may "show jobs",

however, a user has to choose a space before he/she submit a job. 

Which means the privilege to submit a job depends on if the user has access to a space.

**Comment by whitewum** [comment]
@Amber1990Zhang

**Comment by Amber1990Zhang** [comment]
https://github.com/vesoft-inc/nebula-docs/pull/100
