### ISSUE TITLE
nebula的账户密码不管用，随便输入都可以进入

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#2180]
![image](https://user-images.githubusercontent.com/13991775/84489434-4e9a4a00-acd4-11ea-8408-be6af9b136cc.png)

**Comment by bright-starry-sky** [comment]
权限开关开启了吗？

**Comment by ownthink** [comment]
&nbsp;用的默认的配置文件，刚安装好的，没做任何改动。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bright-starry-sky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午5:48
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] nebula的账户密码不管用，随便输入都可以进入 (#2180)





 
权限开关开启了吗？

**Comment by bright-starry-sky** [comment]
> &nbsp;用的默认的配置文件，刚安装好的，没做任何改动。
> […](#)

那应该是权限开关没有开启导致，默认是关闭的，关闭状态不校验用户、密码、权限。
开启方式：在nebula-graphd.conf中修改参数 --enable_authorize=true

**Comment by bright-starry-sky** [comment]
> > 用的默认的配置文件，刚安装好的，没做任何改动。
> > […](#)
> 
> 那应该是权限开关没有开启导致，默认是关闭的，关闭状态不校验用户、密码、权限。
> 开启方式：在nebula-graphd.conf中修改参数 --enable_authorize=true

修改完成后需要重启graphd

**Comment by ownthink** [comment]
好的，多谢

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bright-starry-sky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午5:53
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] nebula的账户密码不管用，随便输入都可以进入 (#2180)





   
用的默认的配置文件，刚安装好的，没做任何改动。
 …
  
那应该是权限开关没有开启导致，默认是关闭的，关闭状态不校验用户、密码、权限。
 开启方式：在nebula-graphd.conf中修改参数 --enable_authorize=true
  
修改完成后需要重启graphd

**Comment by bright-starry-sky** [comment]
> > > 用的默认的配置文件，刚安装好的，没做任何改动。
> > > […](#)
> > 
> > 
> > 那应该是权限开关没有开启导致，默认是关闭的，关闭状态不校验用户、密码、权限。
> > 开启方式：在nebula-graphd.conf中修改参数 --enable_authorize=true
> 
> 修改完成后需要重启graphd

修改成功后，初始用户是 `root` , 密码是 `nebula`

**Comment by ownthink** [comment]
OK

**Comment by bright-starry-sky** [comment]
那我close issuer了？

**Comment by ownthink** [comment]
&nbsp;
好，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bright-starry-sky"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午5:58
收件人:&nbsp;"vesoft-inc/nebula"<nebula@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula] nebula的账户密码不管用，随便输入都可以进入 (#2180)





 
那我close issuer了？
