### ISSUE TITLE
大批量写入数据的时候日志太多，这个能限制保留日志的数量吗？

### ISSUE THREAD

**Issue by HuiHang-Yu** [vesoft-inc/nebula#2189]
大批量写入数据的时候日志太多，虽然现在有文件大小的限制，但是数量目前怎么限制呐？ 这个能限制保留日志的数量吗？

**Comment by liuyu85cn** [comment]
暂时没有, 应该可以把log设一个单独的路径, 然后用cron任务来处理.

**Comment by HuiHang-Yu** [comment]
@liuyu85cn    ok  谢谢
