### ISSUE TITLE
unify naming about ranking & rank

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#2190]
![image](https://user-images.githubusercontent.com/42762957/85377613-ebc66f80-b56b-11ea-97e4-40878f7e2a91.png)
![image](https://user-images.githubusercontent.com/42762957/85377643-fb45b880-b56b-11ea-9330-90b841234e29.png)

**Comment by bright-starry-sky** [comment]
A good point. Thanks . The `_src` , `_dst` and `_rank ` are all convention in the go statement. I don't think it makes sense to use this naming rule in a lookup statement.
But I'll take your advice, and I'll think about how to name it uniformly. Importantly, if we change the column name, we will caused version compatibility issues.

**Comment by bright-starry-sky** [comment]
To avoid version compatibility problem, don't change the column name . So let me close this issue. Please reopen it for any objection.
