### ISSUE TITLE
Add MDBX as a key-value store

### ISSUE THREAD

**Issue by erthink** [vesoft-inc/nebula#2192]
[libmdbx](https://github.com/erthink/libmdbx) is an extremely fast, compact, powerful, embedded, ACID key-value store database, with permissive license. MDBX has a specific set of properties and capabilities, focused on creating unique lightweight solutions with extraordinary performance.

MDBX is a Btree-based database management library modeled loosely on the BerkeleyDB API, but much simplified. The entire database (aka "environment") is exposed in a memory map, and all data fetches return data directly from the mapped memory, so no malloc's or memcpy's occur during data fetches. The library is fully thread-aware and supports concurrent read/write access from multiple processes and threads.

Historically, MDBX is deeply revised and extended descendant of amazing LMDB ([Lightning Memory-Mapped Database](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database)). MDBX inherits all benefits from LMDB, but [resolves some issues and adds set of improvements](https://github.com/erthink/libmdbx#improvements-beyond-lmdb).

---
I suggest adding the MDBX as a storage engine. If you think it is appropriate, just assign this issue to me (and I will try to implement this feature when will I have free time). As the main MDBX developer, I will be happy to answer your questions.

Thanks.
Leonid.

**Comment by dangleptr** [comment]
Very exciting suggestion.  Please feel free to implement the store engine with MDBX. 
For kvstore inside nebula,  the plugin strategy is supported naturally.  To implement another store engine,  just implement the interfaces KVEngine.h, you could take RocksEngine.h as example.

**Comment by avently** [comment]
@erthink do you still plan to implement such feature? Было бы неплохо иметь такую альтернативу

**Comment by CPWstatic** [comment]
How's it going?
