### ISSUE TITLE
Nebula Studio图探索功能

### ISSUE THREAD

**Issue by dengbo22** [vesoft-inc/nebula#2210]
1. 使用图探索对数据进行探索并展现后，能否将图探索的结果以一定的格式导出。
2. 图探索涉及的nGQL能否编辑，有时候查出来数据量太大，又无法自己编辑添加LIMIT语句。

**Comment by whitewum** [comment]
我用的时候也有这个想法

**Comment by nianiaJR** [comment]
> 1. 使用图探索对数据进行探索并展现后，能否将图探索的结果以一定的格式导出。
> 2. 图探索涉及的nGQL能否编辑，有时候查出来数据量太大，又无法自己编辑添加LIMIT语句。

嗯嗯，这个需求我们后面会设计一下，看起来是蛮有意义的

**Comment by jude-zhu** [comment]
move to  https://github.com/vesoft-inc/nebula-web-docker/issues/117 , so I closed it.
