### ISSUE TITLE
Spark writer error when string contains double quotes

### ISSUE THREAD

**Issue by edgar1992** [vesoft-inc/nebula#2213]
record in hive has a field which is a string contains double quotes, when use Spark Writer to load records from hive to nebula, it will fail with SyntaxError like below
![image](https://user-images.githubusercontent.com/8499494/86736443-1df4c880-c066-11ea-83ce-1aba6d447b76.png)

![image](https://user-images.githubusercontent.com/8499494/86737135-9fe4f180-c066-11ea-968a-591cc3f0e251.png)

**Comment by darionyaphet** [comment]
#2230

**Comment by jude-zhu** [comment]
#2230
