### ISSUE TITLE
nebula lists repetitive spaces for no reason.

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#2242]
![image](https://user-images.githubusercontent.com/42762957/88169874-45938580-cc4f-11ea-88c8-754eab4c7ede.png)
As title, there are only 2 spaces in my machine.

**Comment by CPWstatic** [comment]
As far as i know, we don't have the problem in latest nebula1.0 version or nebula2.0. I'll close it firstly, since it's been more than six months.
