### ISSUE TITLE
When querying the vertex of different tags, the non-existent tag is incorrectly assigned a value

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula#2248]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
Vertex 30 only has tag t1, but the value of t2 is 0. It should be null here

![image](https://user-images.githubusercontent.com/58841610/88395743-1ec28400-cdf4-11ea-8000-23f965c19e41.png)

Two tags are used, t1 (name string), t2 (age int), and one tag is assigned to vertex 30 and vertex 31, but the query finds that vertex 30 has two values.
**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by xuguruogu** [comment]
as nebula dont have null type now. I have to use default value to assign to non exist collumn

**Comment by jude-zhu** [comment]
`null` will be supported in `v2.0`
