### ISSUE TITLE
Add which tag relative to current index when describe index

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula#2259]
**Is your feature request related to a problem? Please describe.**
During I develope the GUI tool for nebula look-up, I want to know which the tag is relative to the current index I select. It will help me improve the interaction when user uses our look-up function, for example, he selects on index, then our tool will just provide the relative tags for him to select.

**Describe the solution you'd like**
Nebula has the query like : `Describe Tag index index_demo`.

// current output
|  Field   | Type  |
|  ----  | ----  |
| name  | string |

// idea output
|  Field   | Type  |
|  ----  | ----  |
| {tag}.name  | string |

add which tag the field belongs to.

**Describe alternatives you've considered**
There is another way I can get the relationship between tag and index, but I think it's a little tricky.
![image](https://user-images.githubusercontent.com/8124783/88752597-e7096280-d18c-11ea-9be6-3d848c6907a1.png)

By parsing the `Create Tag index` gql,  I can get the tag name too.

**Comment by jude-zhu** [comment]
u can use `SHOW CREATE TAG INDEX` statement
