### ISSUE TITLE
the yield can`t support the uuid function

### ISSUE THREAD

**Issue by gumupaier** [vesoft-inc/nebula#2263]
related links:
[https://discuss.nebula-graph.com.cn/t/topic/940
](https://discuss.nebula-graph.com.cn/t/topic/940
)

the hash function can work well ,and i think it should be a feature has been forgotten

I hope I can get support

**Comment by jievince** [comment]
感谢反馈，2.0会支持

**Comment by gumupaier** [comment]
搜嘎



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jievince"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 晚上6:00
收件人: "vesoft-inc/nebula"<nebula@noreply.github.com&gt;; 
抄送: "Henson"<henson_wu@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vesoft-inc/nebula] the yield can`t support the uuid function (#2263)





 
感谢反馈，2.0会支持
