### ISSUE TITLE
FETCH PROP ON player, team 100, 201; 提示语法错误

### ISSUE THREAD

**Issue by splendor023** [vesoft-inc/nebula#2279]
按照官方文档安装好以后，在studio中的执行语句FETCH PROP ON player, team 100, 201; 
无法运行。提示 SyntaxError: syntax error near `, team 1'
用的1.0.0版本

**Comment by splendor023** [comment]
使用 FETCH PROP ON * 100, 201; 也不行
参考的文档连接：https://docs.nebula-graph.com.cn/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax/

**Comment by jievince** [comment]
![image](https://user-images.githubusercontent.com/38901892/89614842-dad18380-d8b7-11ea-8217-c50b051f0090.png)

**Comment by jievince** [comment]
我试了下，可以的呀，你看看是不是你哪里弄错了

**Comment by jievince** [comment]
你在console里试过吗？

**Comment by splendor023** [comment]
![image](https://user-images.githubusercontent.com/2344943/89615345-fdb06780-d8b8-11ea-8116-823aa0283d5c.png)

**Comment by jievince** [comment]
其他类型的语句执行结果对吗？

**Comment by splendor023** [comment]
![image](https://user-images.githubusercontent.com/2344943/89615680-b5457980-d8b9-11ea-823f-383f67354c40.png)
是我的安装有问题？ 好奇怪

**Comment by splendor023** [comment]
> 其他类型的语句执行结果对吗？

fetch prop on player 100; 这个就可以执行

**Comment by laura-ding** [comment]
你的版本是旧的，用nightly版本

**Comment by NicolaCage** [comment]
能提供一下版本吗

**Comment by splendor023** [comment]
> 你的版本是旧的，用nightly版本

stable 1.0.0的不支持这种语法？

**Comment by laura-ding** [comment]
> > 你的版本是旧的，用nightly版本
> 
> stable 1.0.0的不支持这种语法？

是的，多个tag是最近两个星期才合入的，你需要用nightly版本

**Comment by splendor023** [comment]
> > > 你的版本是旧的，用nightly版本
> > 
> > 
> > stable 1.0.0的不支持这种语法？
> 
> 是的，多个tag是最近两个星期才合入的，你需要用nightly版本

好吧，了解了，这样的话文档里面最好标注下对应的版本

**Comment by laura-ding** [comment]
> > > > 你的版本是旧的，用nightly版本
> > > 
> > > 
> > > stable 1.0.0的不支持这种语法？
> > 
> > 
> > 是的，多个tag是最近两个星期才合入的，你需要用nightly版本
> 
> 好吧，了解了，这样的话文档里面最好标注下对应的版本

好的，感谢您的反馈，文档这块现在还没有版本管理，我们会不断完善这块。

**Comment by splendor023** [comment]
> > > > > 你的版本是旧的，用nightly版本
> > > > 
> > > > 
> > > > stable 1.0.0的不支持这种语法？
> > > 
> > > 
> > > 是的，多个tag是最近两个星期才合入的，你需要用nightly版本
> > 
> > 
> > 好吧，了解了，这样的话文档里面最好标注下对应的版本
> 
> 好的，感谢您的反馈，文档这块现在还没有版本管理，我们会不断完善这块。

也非常感谢你们的及时解答，我们准备从Janusgraph切换到nebula

**Comment by laura-ding** [comment]
> > > > > > 你的版本是旧的，用nightly版本
> > > > > 
> > > > > 
> > > > > stable 1.0.0的不支持这种语法？
> > > > 
> > > > 
> > > > 是的，多个tag是最近两个星期才合入的，你需要用nightly版本
> > > 
> > > 
> > > 好吧，了解了，这样的话文档里面最好标注下对应的版本
> > 
> > 
> > 好的，感谢您的反馈，文档这块现在还没有版本管理，我们会不断完善这块。
> 
> 也非常感谢你们的及时解答，我们准备从Janusgraph切换到nebula

欢迎使用，有任何问题都可以在 github 提 issue，或者到论坛提问，https://discuss.nebula-graph.com.cn/。我们 OnCall 的同学会及时回答的。
