### ISSUE TITLE
I can not understand this test.

### ISSUE THREAD

**Issue by xuguruogu** [vesoft-inc/nebula#2288]
https://github.com/vesoft-inc/nebula/blob/339d0c575e2dd035814f14b636b13281442f158c/src/graph/test/GoTest.cpp#L2872-L2898

According to my understanding, the result should have 4 records instead of 8 records.

**Comment by Shylock-Hg** [comment]
First the left sentence in pipe get result with 2 records, then right sentence of pipe query from two start vid and get 4 records,
and the result join previous input get 4*2 records.

**Comment by xuguruogu** [comment]
As mentioned in #2227

e1: 1:5
e2: 1:1

`go ... over e1 ... | go ... over e2`, result in 25 records. This seems unexpected.

**Comment by Shylock-Hg** [comment]
> As mentioned in #2227
> 
> e1: 1:5
> e2: 1:1
> 
> `go ... over e1 ... | go ... over e2`, result in 25 records. This seems unexpected.

It follow this process too.
