### ISSUE TITLE
Studio import CSV does not support function, such as now()?

### ISSUE THREAD

**Issue by gumupaier** [vesoft-inc/nebula#2300]
Error when importing CSV using Studio

The technician has reported that the now function is not currently supported

![image](https://user-images.githubusercontent.com/37896380/90225914-c0158680-de44-11ea-85dd-14d98b1273be.png)

![image](https://user-images.githubusercontent.com/37896380/90225956-cdcb0c00-de44-11ea-8036-716ac6a68954.png)

An example of CSV file data is shown below

![image](https://user-images.githubusercontent.com/37896380/90226049-fd7a1400-de44-11ea-945f-0bd9889c8d5b.png)

**Comment by gumupaier** [comment]
Issues related to

https://discuss.nebula-graph.com.cn/t/topic/1029/4

**Comment by NicolaCage** [comment]
now() data import is ok. that's another question  https://github.com/vesoft-inc/nebula/issues/2309
