### ISSUE TITLE
centos7 install nebula-graph-1.0.1-1.x86_64  error

### ISSUE THREAD

**Issue by eleleme** [vesoft-inc/nebula#2301]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

Running transaction
  Installing : nebula-graph-1.0.1-1.x86_64                                                                                          1/1 
Error unpacking rpm package nebula-graph-1.0.1-1.x86_64
error: unpacking of archive failed on file /usr/local/nebula/bin/nebula-storaged;5f36518a: cpio: read
  Verifying  : nebula-graph-1.0.1-1.x86_64                                                                                          1/1 

Failed:
  nebula-graph.x86_64 0:1.0.1-1                                                                                                         

Complete!

**Comment by laura-ding** [comment]
Where did you download the package? We did not support `nebula-graph-1.0.1-1`.
