### ISSUE TITLE
GoExecutor should not return succ by default when completeness not eq 100

### ISSUE THREAD

**Issue by Crazyinging** [vesoft-inc/nebula#2304]
![image](https://user-images.githubusercontent.com/5928054/90366716-3c54d780-e09a-11ea-9502-28bd39873331.png)
As shown, GoExecutor return succ when completeness not eq 100. So it seems that the data received by the caller has the same effect as the missing data!
Reference: https://discuss.nebula-graph.com.cn/t/topic/1005

**Comment by Crazyinging** [comment]
I think GoExecutor should return an exception when completeness not eq 100. And before that, graphd can retry some times on the failed storageds.

To be smarter, after reading the code, I think maybe it can be changed like this:
1. GraphService add interface: 
- future_execute(int64_t sessionId, const std::string& stmt, const RequestConf req_conf);
This interface will deal req_conf and call future_execute(int64_t sessionId, const std::string& stmt);

2. Add: 
class RequestConf {
  private:
    int32_t graphd_retry_times_;    // Value range 0-3. Default is 0.
                                                       // Indicates the number of retries from graphd to storaged.
    bool require_full_data_;            // When graphd can not get the full amount of data, whether to return exception or return the partial data that has been obtained. 
                                                      // True(Default value): return exception when can not get the full amount of data. 
                                                      // False: return the partial data that has been obtained.
};

3. When GoExecutor::stepOut or GoExecutor::fetchVertexProps call storaged failed, retry according to RequestConf.

**Comment by Crazyinging** [comment]
Correspondingly, I use java client and java client should add interface:
```java
public ResultSet executeQuery(String statement, RequestConf requestConf)
            throws ConnectionException, NGQLException, TException;
```

**Comment by dangleptr** [comment]
Do we really need the configuration is on request level?

**Comment by Crazyinging** [comment]
> Do we really need the configuration is on request level?

Indeed, request level may over -designed.
Client level maybe be better, register RequestConf when new client.

In addition, server level may not appropriate, such as adding configuration in the file nebula-graphd.conf, because the same service will have many users, and everyone's demands for stability may be different.

**Comment by CPWstatic** [comment]
This won't be fixed in nebula1.0. We had a configuration for it now in nebula2.0.
