### ISSUE TITLE
leak memory

### ISSUE THREAD

**Issue by linuxpham** [vesoft-inc/nebula#2310]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

Hi admin,

I wonder why is nebula-storage used a lot of memory? Is it leak memory ?

<img width="1648" alt="Screen Shot 2020-08-20 at 10 37 30" src="https://user-images.githubusercontent.com/154762/90714124-28df8180-e2d1-11ea-83be-53f40843d2e1.png">

After restart, use a lot of CPU (a little memory RAM) : 

<img width="1658" alt="Screen Shot 2020-08-20 at 10 39 58" src="https://user-images.githubusercontent.com/154762/90714277-84117400-e2d1-11ea-93cd-70ac808b9cd2.png">

<img width="1654" alt="Screen Shot 2020-08-20 at 10 42 30" src="https://user-images.githubusercontent.com/154762/90714441-dbafdf80-e2d1-11ea-9413-4e2d02f1ca2c.png">

**Your Environments (__must be provided__)**

* OS: `uname -a` => Linux touchee 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: `g++ --version` or `clang++ --version` => g++ (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
* CPU: `lscpu` => 4 cores , Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by jamieliu1023** [comment]
Hi @linuxpham, thanks for raising an issue here. For problems that you encountered when using Nebula Graph, we encourage you to post it on our official forum: https://discuss.nebula-graph.io/ we have devs on call there to answer your questions. Thanks!

**Comment by linuxpham** [comment]
Hi admin,
I created a topic: https://discuss.nebula-graph.io/t/nebula-storage-memory-leak/629
Thanks !

**Comment by linuxpham** [comment]
Hi admin,

I found this problem.

A reason is: there are many spaces in nubela-graph

But i confuse: these spaces are empty (vertex and edge) => that means nebula-graph only takes a little memory ?

Thanks !
