### ISSUE TITLE
Get UUID failed

### ISSUE THREAD

**Issue by Harlan6** [vesoft-inc/nebula#2336]
Here is the error log:

E0903 16:36:00.795754 228340 Expressions.cpp:535] Get UUID failed, error -11, part 128, str id uuid(apply202008031059384454900121)
E0903 16:36:00.795828 228340 InsertVertexExecutor.cpp:240] Insert vertices failed, error Get UUID Failed
E0903 16:36:00.795872 228340 ExecutionPlan.cpp:76] Execute failed: Get UUID Failed

I want to know how it happen  and how to fix it?

**Comment by critical27** [comment]
Probably because leader changed in storage, the error code is -11. Usually, it won't appear after leader is elected.
