### ISSUE TITLE
[Suggest] Don't use github email for promotional

### ISSUE THREAD

**Issue by yang-xiaodong** [vesoft-inc/nebula#2349]
Hello there,

I received the promotion email of this project. For any purpose, I think it is an unethical behavior to scan github personal data and send emails, and it is not allowed by github. 

Please stop !

![image](https://user-images.githubusercontent.com/8205994/93988701-9e9ca880-fdbb-11ea-946c-0def3e80218d.png)

**Comment by whitewum** [comment]
Noticed and thanks.

**Comment by jbjorge** [comment]
I just received an email today, so I guess it was not noted.

**Comment by LER0ever** [comment]
Received the same email 30 min ago... reporting the email and this issue to GitHub.
