### ISSUE TITLE
nebula如何查询已经创建的所有顶点？

### ISSUE THREAD

**Issue by fengsen-neu** [vesoft-inc/nebula#2352]
nebula如何查询已经创建的所有顶点？
类似neo4j：MATCH (n) RETURN n
MySQL: show tables;

**Comment by Nicole00** [comment]
查询已经创建的所有顶点tag：
    SHOW TAGS；
查询已经创建的所有边edge：
    SHOW EDGES；

**Comment by fengsen-neu** [comment]
![image](https://user-images.githubusercontent.com/58256617/94538874-229cd780-0277-11eb-95d3-84bb1bd7f12e.png)

**Comment by fengsen-neu** [comment]
> 查询已经创建的所有顶点tag：
> SHOW TAGS；
> 查询已经创建的所有边edge：
> SHOW EDGES；

我是想查询标签下面有哪些具体的顶点，我发现db_dump工具能满足我的需求，但是不知道ngql有没有这种语法。
![image](https://user-images.githubusercontent.com/58256617/94539768-414f9e00-0278-11eb-88a7-534079822cad.png)

**Comment by jievince** [comment]
语法上还不支持

**Comment by panda-sheep** [comment]
> > 查询已经创建的所有顶点tag：
> > SHOW TAGS；
> > 查询已经创建的所有边edge：
> > SHOW EDGES；
> 
> 我是想查询标签下面有哪些具体的顶点，我发现db_dump工具能满足我的需求，但是不知道ngql有没有这种语法。show tags只能看到有哪几种顶点，看不到某种tag下面有多少个具体的顶点。
> ![image](https://user-images.githubusercontent.com/58256617/94539768-414f9e00-0278-11eb-88a7-534079822cad.png)

你好，
2.0 会支持：
查询某个tag下的所有点，
查询某种edgetype的所有edge，

以及支持：
某个tag下所有点的数量
某个edgetype下面所有边的数量
某个space下所有点的数量
某个space下面所有边的数量。

**Comment by vkill** [comment]
[统计某space某partition下某tag的点数量](https://github.com/bk-rs/nebula-rs/blob/master/demos/async-std/src/count_vertex.rs) ，参考 https://discuss.nebula-graph.com.cn/t/topic/1301

**Comment by fengsen-neu** [comment]
> > > 查询已经创建的所有顶点tag：
> > > SHOW TAGS；
> > > 查询已经创建的所有边edge：
> > > SHOW EDGES；
> > 
> > 
> > 我是想查询标签下面有哪些具体的顶点，我发现db_dump工具能满足我的需求，但是不知道ngql有没有这种语法。show tags只能看到有哪几种顶点，看不到某种tag下面有多少个具体的顶点。
> > ![image](https://user-images.githubusercontent.com/58256617/94539768-414f9e00-0278-11eb-88a7-534079822cad.png)
> 
> 你好，
> 2.0 会支持：
> 查询某个tag下的所有点，
> 查询某种edgetype的所有edge，
> 
> 以及支持：
> 某个tag下所有点的数量
> 某个edgetype下面所有边的数量
> 某个space下所有点的数量
> 某个space下面所有边的数量。
> 
> 功能正在开发中，敬请期待。

好的，十分感谢回答。

**Comment by Kolo7** [comment]
我也在寻找，在1.0中，找到一种类似的方法，先对顶点建index:
CREATE TAG INDEX player_index_0 on player(name);

要查找player下所有的顶点时（在索引上查找name不为空的点）：
LOOKUP ON player WHERE player.name!=""; 

不足点就是name如果为空，就查不到了。
