### ISSUE TITLE
How to blur search properties

### ISSUE THREAD

**Issue by hiqrf** [vesoft-inc/nebula#2357]
I use nebula v1.1.0,I want to search vertex by properties with prefix mode
when i use contains like this LOOKUP ON Person WHERE Person.zjhm contains "Tony Parker" 
i got this error SyntaxError: Unsupported 'CONTAINS' in where clause

gremin useage :g.V().has(label, field, Text.textRegex(text) or g.V().has(label, field, Text.textPrefix(text)

**Comment by Nicole00** [comment]
The “contains” operation is temporarily not supported in the LOOKUP statement. For details about the usage of LOOKUP, please refer to the document. [https://docs.nebula-graph.io/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax/](url)

Currently, blur search does not support "regex match", but only supports "contains" operation, which is used in go statements， such as `GO FROM 107 OVER serve WHERE $$.team.name CONTAINS "riors" \
        YIELD $^.player.name, serve.start_year, serve.end_year, $$.team.name;` 
[https://docs.nebula-graph.io/manual-EN/2.query-language/2.functions-and-operators/string-comparison-functions-and-operators/](url)

**Comment by hiqrf** [comment]
my frist step is find tags by its properties with blur search,。Is there any solution that meets my needs？thx.

**Comment by hiqrf** [comment]
Nebula Graph v2.0.0-alpha
