### ISSUE TITLE
Support Node.js client

### ISSUE THREAD

**Issue by sequoiar** [vesoft-inc/nebula#2369]
**Is your feature request related to a problem? Please describe.**
yes, work natively with node.js

**Describe the solution you'd like**
provide node.js client

**Describe alternatives you've considered**
REST api

**Additional context**

**Comment by Shylock-Hg** [comment]
Thanks for your request. For some reason we will provide a simple node client without official support recently.

**Comment by sliontc** [comment]
> Thanks for your request. For some reason we will provide a simple node client without official support recently.

Does it support nebula 1.0?

**Comment by jievince** [comment]
> > Thanks for your request. For some reason we will provide a simple node client without official support recently.
> 
> Does it support nebula 1.0?

No, it just supports nebula 2.x. And there is no plan to support 2.x.
