### ISSUE TITLE
supplementary code comments about Raft leaderElection

### ISSUE THREAD

**Issue by ystaticy** [vesoft-inc/nebula#2380]
in leaderElection,there is a code comments about Leader A crashed and B,C will begin the election.
the sentence 'Meanwhile C begin the election' .It means there is a situation where C restarts the election after B win.

In fact, there is one condition for C to resume the election after B win.
that is, the heartbeat between B and C has timed out due to pressure and other reasons.

so I will add the describe to the code comments.

**Comment by CPWstatic** [comment]
@dangleptr @critical27

**Comment by dangleptr** [comment]
Well done.  Do you want to give a pr for it.  Thanks

**Comment by CPWstatic** [comment]
How's it going?

**Comment by CPWstatic** [comment]
I'll close it firstly. Please feel free to reopen it if you still have interest in it.
