### ISSUE TITLE
2.0 cluster storage timeout

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#2383]
I’m using 2.0 Docker to deploy a cluster. But the storages are timeout for no reason.
I didn’t mess up with the 1.0 data or create any data yet. The storage just won't work.
Any ideas?
I 've talked to @yixinglu but got no idea.

**Comment by CPWstatic** [comment]
Emmm, i'll close it firstly, since it's been more than 6 months. Please let us know if you still have problem with nebula 2.0.
