### ISSUE TITLE
find shortest path  execute error 

### ISSUE THREAD

**Issue by tercel53** [vesoft-inc/nebula#2387]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
execute "find shortest path form  src_id to end_id over *"   return some error

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.
E1102 17:24:07.144863 24459 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.
[ERROR (-3)]:

**Comment by monadbobo** [comment]
Please check to see if the meta or storage service still exists.

**Comment by CPWstatic** [comment]
Please provide us more infos. I'll close it firstly since it's been more than six months. Please let us know if you still suffer.
