### ISSUE TITLE
  Is there a plan to support. Net clients

### ISSUE THREAD

**Issue by Cloud33** [vesoft-inc/nebula#2397]
**Is your feature request related to a problem? Please describe.**
I'm a. Net developer. I want to use nebula and I hope to have a. Net client

**Describe the solution you'd like**
Increased support for. Net clients

**Comment by laura-ding** [comment]
Thanks for your questions.  Because of the limitations of the RPC framework we rely on, we will not provide the.NET client.

**Comment by Cloud33** [comment]
It's `Thrift RPC`?

https://github.com/apache/thrift

`Thrift` seems to support. Net

**Comment by laura-ding** [comment]
> It's `Thrift RPC`?
> 
> https://github.com/apache/thrift
> 
> `Thrift` seems to support. Net

Nebula Graph use https://github.com/facebook/fbthrift

**Comment by sunsided** [comment]
Sadly facebook/fbthrift#379 states it pretty clearly as well: "We don't plan to support C#." Well, crap.

**Comment by Cloud33** [comment]
What a sad decision😥
