### ISSUE TITLE
spark writer工具支持spark on yarn模式导入数据吗？

### ISSUE THREAD

**Issue by hangjianglaoweng** [vesoft-inc/nebula#2399]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hangjianglaoweng** [comment]
spark on yarn cluster模式

**Comment by jievince** [comment]
@Nicole00

**Comment by xrfinbupt** [comment]
exchange和Spark Writer什么关系？
1. Exchange是由Spark Writer迁移而来，且在Spark Writer的基础上提供了更丰富的数据源，如MySQL、Neo4j、Hive、HBase、Kafka、Pulsar等。
2. 而且Exchange修复了关于hdfs 文件导入时存在的数据类型与Nebula Schema数据类型不匹配的问题（如hdfs文件被Spark读成DataFrame时默认的数据类型均为String，当Nebula 中schema为int、double等类型时无法完成导入）。
3. 后期的维护工作将集中在Exchange上。
建议利用spark进行数据导入时使用Exchange。

我这边用spark导入hive数据进nebula，Mac电脑上用local是可以的，我理解cluster应该也是可以的

**Comment by Nicole00** [comment]
@jievince 支持的
