### ISSUE TITLE
Question about task scheduling

### ISSUE THREAD

**Issue by lushl9301** [vesoft-inc/nebula#2400]
Hi I was looking around in the code base. I wonder if the job scheduling is purely FIFO?

I come out with this hypothesis because the queue is unboundedQueue from Follly (not the PriorityUnboundedQueue)
https://github.com/vesoft-inc/nebula/blob/daab888d7dea235f3d6c04798eb993e66bb8da46/src/meta/processors/jobMan/JobManager.h#L68

May I correct? Do you consider applying different priorities?

Thanks

**Comment by liuyu85cn** [comment]
there is, in nebula 2.0. https://github.com/vesoft-inc/nebula-storage/blob/7b69cf78f9268adaae2ef2e73e107c42c6cdea5e/src/meta/processors/jobMan/JobManager.cpp

**Comment by lushl9301** [comment]
> there is, in nebula 2.0. https://github.com/vesoft-inc/nebula-storage/blob/7b69cf78f9268adaae2ef2e73e107c42c6cdea5e/src/meta/processors/jobMan/JobManager.cpp

very interesting. So Nebular-storage is more like nebula 2.0. and this priority support is added four days ago?

**Comment by liuyu85cn** [comment]
we split nebula 2.0 into 3 repo : nebula-graph , nebula-common and nebula-storage. 
and yes this just supported about 4 days.

**Comment by lushl9301** [comment]
Nice. Thank you. Will look into that.
