### ISSUE TITLE
Raft:a server send 2 vote to different server in one term

### ISSUE THREAD

**Issue by ystaticy** [vesoft-inc/nebula#2405]
In 1.1.0.
proposedTerm_ can be set to a small value in verifyLeader as follows;
But I think it should Increase forever, because it's used to determine whether to vote for others in newest term.

------------------------------------------

if we have 3 nodes: 'A','B','C' 
At a normal state, 'C' is leader term=4,'A','B' is follower. 'C' keep sending appenlog RPC(term 4);

------------------------------------------

at the next monment B become term 5 's leader;
A log OP_TRANS_LEADER in log to commit;
B print log  'Give up my leadership'. B.role_ change to FOLLOWER;

------------------------------------------

at the next monment 'B','C' heartbeat timeout  ,'B' send askVote RPC (term=6) ,and  'C' send askVote RPC(term=6);

------------------------------------------

then 'A' received 'B' askVote RPC，A print ‘will vote for the candidate' (A return SUCCEEDED response to B),
and 'A' set **A.proposedTerm_=term6** ;But 'A'.term_ is still 4(hasn't received the heartbeat from term 5).
(this moment, appendlog RPC(term=4) from C may be still in process )

at the next monment  'A' just execute verifyleader appendlog RPC from C (term 4)
'A' execute :
`term_ = proposedTerm_ = req.get_current_term()`
now **A.proposedTerm_=4**

------------------------------------------

now 'A' received 'C' askVote RPC(term 6) , due to  A.proposedTerm_=4，A vote for C

now there are two leader in term 6，in A,B,C .
------------------------------------------
'A' log as follows
![image](https://user-images.githubusercontent.com/3659421/100064139-172bee00-2e6d-11eb-89da-4eaa812140e7.png)

**Comment by ystaticy** [comment]
the pull request is  https://github.com/vesoft-inc/nebula/pull/2406

**Comment by critical27** [comment]
Thanks for the feedback. It is ok to vote twice to different peer in same term. One key difference in code for now is that, the vote is more like a `prevote`, not vote in the paper. Even though B and C could become leader, A will accept one of B/C in `verifyLeader` when they send appendLogs or heartbeat, depends on which one received first. I agree with you that it could be misleading.

**Comment by ystaticy** [comment]
After 'A vote for B' and 'A vote for C'
finally A accept C
but now B.role_=LEADER  and C.role_=LEADER;

- 'B' log is always print 'Only 0 hosts succeeded, Need to try again...'. because 'A'  and 'C' process B request will execute 'The local term is same as remote term' 
- 'C' log is always print '[Host: hostB:44501] Failed to append logs to the host'.Because 'B' process 'A' request will execute 'The local term is same as remote term'.    But C can appendlog to A success;
- 'A' log is always print 'The local term is same as remote term 6, my role is Follower, reject it!'.

**Comment by ystaticy** [comment]
> Thanks for the feedback. It is ok to vote twice to different peer in same term. One key difference in code for now is that, the vote is more like a `prevote`, not vote in the paper. Even though B and C could become leader (they cannot serve to external until heartbeat has been accepted by majority), A will only accept one of B/C in `verifyLeader` when they send appendLogs or heartbeat, depends on which one received first. I agree with you that it could be misleading.

in etcd raft，it has a real preVote process; the prevote just get the tickets count first ,but not to change the role;
but in nebula，if someone send a askVote request，the response will effect the role immediately

**Comment by critical27** [comment]
Talked offline, the PR won't merge into master.
