### ISSUE TITLE
Range query is not working on timestamp fields

### ISSUE THREAD

**Issue by goranc** [vesoft-inc/nebula#2420]
Have cluster with nebula version 1.2.0
Created new test space, created tag with two properties one string and one timestamp.
Created index for tag using timestamp field.

When executing query 
- with timestamp_field == xx (got results)
- with timestamp_field < xx (got results)  
- with timestamp_field > xx  (got error)

Is this expected, as operand > (.gt.) is not supported or this is bug ?

**Comment by Shinji-IkariG** [comment]
This is in line with expectations.
The lookup on syntax only supports partial filtering, and more filtering functions will be provided in 2.0 in the future.
