### ISSUE TITLE
k8s version installation reports: No such file or directory

### ISSUE THREAD

**Issue by ryanqin01** [vesoft-inc/nebula#2421]
The whole log is as following:

# kubectl logs -f nebula-storaged-0 -n nebula
++ hostname -i
+ exec /usr/local/nebula/bin/nebula-storaged --flagfile=/usr/local/nebula/etc/nebula-storaged.conf --local_ip=10.30.33.42 --v=0 --minloglevel=2 --daemonize=false
E1222 09:36:15.759665     1 FileUtils.cpp:384] Failed to read the directory "/usr/local/nebula/data/storage/nebula" (2): No such file or directory

the configuration is as following:

    ########## storage ##########
    # Root data path, multiple paths should be splitted by comma.
    # One path per instance, if --engine_type is `rocksdb'
    --data_path=/usr/local/nebula/data/storage

I tried relative path before. Also not working

**Comment by ryanqin01** [comment]
the version I used is v1.2.0

**Comment by MegaByte875** [comment]
> the version I used is v1.2.0

Hi,
Please check the storageclass and pvc，you can post it on the comment

**Comment by CPWstatic** [comment]
Has the problem been solved? I'll close this issue first, since it's been six months. Let us know if you still suffer.
