### ISSUE TITLE
Invalid vertex id

### ISSUE THREAD

**Issue by rwer81** [vesoft-inc/nebula#2425]
Hello Team,
I want to set +8 characters vertex id but I get error. Is there a limit? If yes, is there a way to set a vertex id using +8 characters?
Thanks.

**Comment by liuyu85cn** [comment]
is there any error message?

**Comment by rwer81** [comment]
I am sorry I forgot adding it.

This works (8-characters id):
`insert vertex okul(il,adi) values "11c81b39":("Ohio","Hayes Inc");`  


But this does not work (9-characters id);
`insert vertex okul(il,adi) values "11c81b391":("Ohio","Hayes Inc");`

Error:
E1225 02:17:03.122401 17802 QueryStorageExecutor.h:32] InsertVerticesExecutor failed, error E_INVALID_VID, part 6
E1225 02:17:03.122493 17801 QueryInstance.cpp:120] Storage Error: Invalid vid.

**Comment by rwer81** [comment]
I find the solution.
When we create a space, we can set fixed_string value. Default should be 8.

`CREATE SPACE IF NOT EXISTS space30(PARTITION_NUM=20, **vid_type=FIXED_STRING(30)** );`

But it is not mentioned in documentation of `CREATE SPACE` .

Thanks.
