### ISSUE TITLE
如何获取所有relation的值

### ISSUE THREAD

**Issue by sliontc** [vesoft-inc/nebula#2431]
![image](https://user-images.githubusercontent.com/6959147/103499577-8e4c9d00-4e83-11eb-8641-f6d278b0cc4e.png)
如图，怎么获取space中所有relation的值

**Comment by Shinji-IkariG** [comment]
studio中console执行的语句本身限制了返回结果的数量。
如需获取全量数据，请在命令行console中进行查询

**Comment by jude-zhu** [comment]
https://github.com/vesoft-inc/nebula-graph/pull/485 可以通过match 实现
