### ISSUE TITLE
Restore snapshot to cluster with different number of nodes

### ISSUE THREAD

**Issue by goranc** [vesoft-inc/nebula#2435]
As documentation for work with Snapshot/Restore doesn't have details about how to restore from snapshot except one sentence what have to be done. I have few questions about use cases related to restore procedure.

1. restore should be simple to same cluster configuration as one which generated snapshots
    shutdown nodes, copy files from snapshot backup to data directory for each node, start storaged services for cluster

2. is it possible to restore snapshot to cluster with different number of nodes 
    eg. cluster with 5 nodes restore to cluster with 3 nodes
    (something like copy files from nedes1,2 to new-node1, nodes3,4 to new-node2, and node5 to new-node3, and start new cluster)

**Comment by laura-ding** [comment]
Thanks for your question. The snapshot can only be restored in the original cluster at present, and the data cannot be copied to other clusters. Because of the data has the cluster info.

**Comment by goranc** [comment]
It is not supported, so let's close ticket.
