### ISSUE TITLE
I got a ERROR when I try the sample nGQL---Wrong vertex id type: 100

### ISSUE THREAD

**Issue by bwboy** [vesoft-inc/nebula#2436]
I use docker run  Nebula 2.0 Verison.
And when I try the Guide on "https://docs.nebula-graph.com.cn/manual-CN/1.overview/2.quick-start/1.get-started/"
while I input 
```
INSERT VERTEX player(name, age) VALUES 100:("Tim Duncan", 42);
```
I got ERROR info "Wrong vertex id type: 100"
Then , I change my nGQL to 
```
INSERT VERTEX player(name, age) VALUES "100":("Tim Duncan", 42);
```

It's running OK...
Is this Version

**Comment by jievince** [comment]
neubla 2.0's default vid type is  string. If you want to use int type vid in nebula 2.0, you should specify it when creating space: https://docs.nebula-graph.io/2.0/3.ngql-guide/9.space-statements/1.create-space/

**Comment by bwboy** [comment]
> neubla 2.0's default vid type is string. If you want to use int type vid in nebula 2.0, you should specify it when creating space: https://docs.nebula-graph.io/2.0/3.ngql-guide/9.space-statements/1.create-space/

Got it，Thanks
