### ISSUE TITLE
与Flink融合应用场景

### ISSUE THREAD

**Issue by cmdares** [vesoft-inc/nebula#2437]
据了解，当前团队已经适配了flink的source和sink，可参考：https://nebula-graph.com.cn/posts/nebula-flink-connector/
问题：能否结合图库查询分析的能力，示范使用Flink在风控场景针对流数据融合计算的方法与最佳实践。
例如：实时图查询、环检测等实战干货。
感谢。

**Comment by Nicole00** [comment]
与Flink的对接目前没有结合图查询，很感谢你提的这个应用场景很有价值，我们会考虑评估。

**Comment by cmdares** [comment]
感谢，关注！

**Comment by whitewum** [comment]
同关注。
