### ISSUE TITLE
自己编译arm版本安装包在部分机器上出现占用内存过高的情况

### ISSUE THREAD

**Issue by savelove123** [vesoft-inc/nebula#2439]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

你好，我下载了v1.2.0的代码，在arm上进行编译、打包，成功打包了1.2.0的rpm包，我在我开发的机器上，安装、测试这个安装包一切都是正常的内存只占用几个G，但是当我把安装包安装到其他非开发的机器上（256G内存的服务器），就会出现内存被占用了几百G的情况。
通过 sudo /usr/local/nebula/scripts/nebula.service start all 启动服务
就出现了内存占用过高的情况，
top打印如下如下
25895 root      20   0  288.4g 122.5g  16000 S   0.3 48.1   0:14.66 nebula-metad                                                                                                                                                                
25932 root      20   0  114.4g  47.0g  28928 S   0.3 18.5   0:03.85 nebula-storaged                                                                                                                                                             
25911 root      20   0  211.0g  31.0g  26624 S   0.3 12.2   0:03.59 nebula-graphd 

free -g显示结果如下

              total        used        free      shared  buff/cache   available
Mem:            254         212          23           0          18          12
Swap:             0           0           0

**Your Environments (__must be provided__)**

开发和测试安装的机器都有安装了gcc 9.3.0 有的测试机器没有安装g++ 只安装了gcc4.8.5，但是测试机器都是一样的情况占用了几百G内存。
并且我配置了内核的参数 vm.swappiness = 60 发现也不会启动swap分区,swap还是0

* OS: `Linux multiview 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`
* Compliler: `gcc version 9.3.0 (GCC)`
* CPU: `aarch64`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. 编译1.2.0的nebula 包
2. 安装nebula 1.2.0的rpm包
3. sudo /usr/local/nebula/scripts/nebula.service start all
4.free -g

**Expected behavior**
这个是我开发机器显示的内存使用情况
 [root@localhost yum.repos.d]# free -g
              total        used        free      shared  buff/cache   available
Mem:            254          21          30           0         202         192
Swap:             0           0           0

72086 root      20   0  288.4g   5.0g  30784 S   0.3  2.0   0:03.06 nebula-metad
72102 root      20   0  211.0g   2.5g  26816 S   0.3  1.0   0:00.80 nebula-graphd 
72168 root      20   0  114.4g   1.1g  29312 S   0.3  0.4   0:00.36 nebula-storaged 

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by dutor** [comment]
This issue had been discussed in our forum. Please refer to [here](https://discuss.nebula-graph.com.cn/t/topic/2479/17) for more details.
