### ISSUE TITLE
使用 LOOKUP 查询时，IndexNotFound: No valid index found

### ISSUE THREAD

**Issue by Echo0117** [vesoft-inc/nebula#2441]
嗨，你好~我想请问一下关于  IndexNotFound: No valid index found 的问题。

我通过 VertexID 查询 entity.name 属性的时候，是有值的，如下图所示：

![image](https://user-images.githubusercontent.com/54064209/105142648-cfa4a400-5b35-11eb-8a3e-40d0df23ece9.png)

但是当我用 LOOKUP 去查询 entity.name 对应的 VertexID 时，就显示：

![image](https://user-images.githubusercontent.com/54064209/105142741-e9de8200-5b35-11eb-8796-c768dff7c1f1.png)

我又按照官网的示例试了一下重新创建索引然后 LOOKUP，一样的语句和流程，但是还是显示 IndexNotFound: No valid index found，如下图所示:

![image](https://user-images.githubusercontent.com/54064209/105142931-214d2e80-5b36-11eb-90dd-b4b184985330.png)

![image](https://user-images.githubusercontent.com/54064209/105142954-2a3e0000-5b36-11eb-8ad5-b8d100191eb9.png)

请问一下怎么解决这个问题呀~谢谢！

**Comment by bright-starry-sky** [comment]
https://discuss.nebula-graph.com.cn/t/topic/2592/8
