### ISSUE TITLE
有最新版的 k8s 的安装的 yaml

### ISSUE THREAD

**Issue by T-baby** [vesoft-inc/nebula#2443]
按照博客上的方式安装时出现 MountVolume.SetUp failed for volume "config" : configmap "nebula-storaged" not found。
而且里面的写法很奇怪，为什么要写明节点的内网 ip 呢，有最新版本的 k8s 可用的安装文件吗？

**Comment by MegaByte875** [comment]
Hello，您可以到论坛提问https://discuss.nebula-graph.com.cn
configmap nebula-storaged在[文件](https://github.com/vesoft-inc/nebula/blob/e86feb7da5cb6f8960cc72db34ba654464ebb064/kubernetes/helm/templates/configmap.yaml#L64)中有定义，对于写明metad内网IP的问题，我们会优化部署，尽快提供更新后的helm文件

**Comment by nereus-east** [comment]
Why not use Kubernetes' headless service?

**Comment by MegaByte875** [comment]
@nereus-east  New version helm charts using headless [service](https://github.com/vesoft-inc/nebula-docker-compose/blob/master/charts/nebula/templates/service.yaml),  metad and storaged is statefulset，if access them under k8s service clusterIP mode，will cause some mistakes. You can deploy nebula 2.0 then test it.

**Comment by nereus-east** [comment]
> @nereus-east New version helm charts using headless [service](https://github.com/vesoft-inc/nebula-docker-compose/blob/master/charts/nebula/templates/service.yaml), metad and storaged is statefulset，if access them under k8s service clusterIP mode，will cause some mistakes. You can deploy nebula 2.0 then test it.

I see it. Thank you!
