### ISSUE TITLE
HDD磁盘不支持么

### ISSUE THREAD

**Issue by zcw5116** [vesoft-inc/nebula#2444]
我们的主机环境支持SSD在预算上比较有困难，请问下Nebula是不支持HDD磁盘吗？我在HDD的单机上安装Nebula没有啥问题？ 如果使用HDD磁盘会有啥影响吗

**Comment by yixinglu** [comment]
目前是不建议使用 HDD，尤其是大并发量的情况，因为针对这种情况的测试进行的比较少，所以没有针对慢设备做过特殊的优化。

不过针对 nebula 2.0 我们有计划针对慢设备做稳定性的测试和优化，尽可能的来保证可靠性。

**Comment by junyicc** [comment]
@yixinglu 使用 nebula graph 2.0.0-rc1 版本在 HDD 上搭建物理集群，测试过程中在批量导入和查询数据时，发现了一些稳定性问题：https://discuss.nebula-graph.com.cn/t/topic/2800
