### ISSUE TITLE
Support php client

### ISSUE THREAD

**Issue by xxm404** [vesoft-inc/nebula#2445]
Does the official consider support PHP client?  or provide raw HTTP endpoint we can build client ourself.

**Comment by yixinglu** [comment]
Sorry, supporting PHP client is not in our future plan. But you could generate a simple thrift client by changing [the file](https://github.com/vesoft-inc/nebula-common/blob/master/cmake/ThriftGenerate.cmake#L79-L93). 

We will publish a golang project named `nebula-http-gateway` to provide HTTP server for user. The project will receive user's requests and use nebula-go client to access nebula service.

**Comment by nianiaJR** [comment]
Before we open the source code of `nebula-http-gateway`, you can use it's docker image :https://hub.docker.com/r/vesoft/nebula-http-gateway

**Comment by xxm404** [comment]
@yixinglu @nianiaJR Thanks for the reply, we will try it.
Another question we want to migrate from Dgraph to nebula, can provide a tool load rdf file?

**Comment by nianiaJR** [comment]
> Before we open the source code of `nebula-http-gateway`, you can use it's docker image :https://hub.docker.com/r/vesoft/nebula-http-gateway
After our discussion, we've planned to open the nebula-http-gateway source code. But it's now lack of document, which we'll make up later. You can use it directly, if you are good at golang. 

Here is the source code link: https://github.com/vesoft-inc/nebula-http-gateway 🤝

**Comment by yixinglu** [comment]
> @yixinglu @nianiaJR Thanks for the reply, we will try it.
> Another question we want to migrate from Dgraph to nebula, can provide a tool load rdf file?

Hi @xxm404 Nebula don't support to load RDF files directly at present. But you can convert these files to CSV format and then use [nebula-importer](https://github.com/vesoft-inc/nebula-importer) or [nebula-spark-utils](https://github.com/vesoft-inc/nebula-spark-utils) to import csv files to nebula.

there's a similar example to process the knowledge graph data, but this's an chinese blog, maybe it's useful for you: https://nebula-graph.com.cn/posts/import-ownthink-knowledge-graph-data-to-nebula-graph/
