### ISSUE TITLE
有图管理和读写权限的相关实现么

### ISSUE THREAD

**Issue by liansghuaifan** [vesoft-inc/nebula#2446]
有考虑鉴权的实现么？关于图的管理或者图的读写的权限控制，或者更加细粒度的鉴权控制

**Comment by jude-zhu** [comment]
https://docs.nebula-graph.com.cn/manual-CN/3.build-develop-and-administration/4.account-management-statements/built-in-roles/

Since Nebula has acl, could you be more specific about "more granular authorization"？

**Comment by liansghuaifan** [comment]
谢谢，看了相关用户手册，nebula是基于LDAP实现的读写权限
