### ISSUE TITLE
Why is this 0.0.·0.0 and not 0.0.0.0

### ISSUE THREAD

**Issue by nereus-east** [vesoft-inc/nebula#2448]
https://github.com/vesoft-inc/nebula/blob/ad8899e5429f7e3cac4c65291bad898e64209d82/kubernetes/helm/templates/configmap.yaml#L88

**Comment by MegaByte875** [comment]
@nereus-east  The configuration has an error,  it should be 0.0.0.0， we will modify it.

**Comment by nereus-east** [comment]
> @nereus-east The configuration has an error, it should be 0.0.0.0， we will modify it.
