### ISSUE TITLE
Failed to run nebula-metad on Kubernetes

### ISSUE THREAD

**Issue by nereus-east** [vesoft-inc/nebula#2449]
**Describe the bug (__must be provided__)**

I used the [chart](https://github.com/vesoft-inc/nebula/tree/master/kubernetes/helm) provided by the official, but no matter what I do, nebula-metad can't run.

Below is the log of Nebula-Metad when it started

+ exec /usr/local/nebula/bin/nebula-metad --flagfile=/usr/local/nebula/etc/nebula-m.conf --v=3 --minloglevel=0 --daemonize=false
I0225 12:58:43.180016     8 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.180191    10 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.180282     9 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.180145    11 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.180461    12 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.180577    13 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I0225 12:58:43.215413     1 NebulaStore.cpp:44] Start the raft service...
I0225 12:58:43.225898     1 ThriftClientManager.h:29] ThriftClientManager
I0225 12:58:43.226114     1 RaftexService.cpp:65] Init thrift server for raft service.
I0225 12:58:43.226279    52 RaftexService.cpp:99] Starting the Raftex Service
I0225 12:58:43.226447    52 ThriftServer.cpp:266] libevent 2.1.11-stable method epoll
I0225 12:58:43.226498    52 ThriftServer.cpp:397] Using 0 SSL handshake threads
E0225 12:58:43.275363    52 ThriftServer.cpp:440] Got an exception while setting up the server: 98failed to bind to async server socket: 0.0.0.0:44501: Address already in use
E0225 12:58:43.275697    52 RaftexService.cpp:90] Setup the Raftex Service failed, error: 98failed to bind to async server socket: 0.0.0.0:44501: Address already in use
I0225 12:58:43.278589    53 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d209900 in thread 0x7f8f6c409000
I0225 12:58:43.278616    53 Acceptor.cpp:397] Acceptor=0x7f8f6d209900 onEmpty()
I0225 12:58:43.278697    54 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d209c00 in thread 0x7f8f6b608000
I0225 12:58:43.278756    54 Acceptor.cpp:397] Acceptor=0x7f8f6d209c00 onEmpty()
I0225 12:58:43.278826    55 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d209f00 in thread 0x7f8f6a809000
I0225 12:58:43.278856    55 Acceptor.cpp:397] Acceptor=0x7f8f6d209f00 onEmpty()
I0225 12:58:43.278935    56 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20a200 in thread 0x7f8f69a08000
I0225 12:58:43.278964    56 Acceptor.cpp:397] Acceptor=0x7f8f6d20a200 onEmpty()
I0225 12:58:43.279006    57 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20a500 in thread 0x7f8f68c09000
I0225 12:58:43.279031    57 Acceptor.cpp:397] Acceptor=0x7f8f6d20a500 onEmpty()
I0225 12:58:43.279083    58 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20a800 in thread 0x7f8f67e08000
I0225 12:58:43.279105    58 Acceptor.cpp:397] Acceptor=0x7f8f6d20a800 onEmpty()
I0225 12:58:43.279186    59 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20ab00 in thread 0x7f8f67008000
I0225 12:58:43.279217    59 Acceptor.cpp:397] Acceptor=0x7f8f6d20ab00 onEmpty()
I0225 12:58:43.279292    60 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20ae00 in thread 0x7f8f66208000
I0225 12:58:43.279327    60 Acceptor.cpp:397] Acceptor=0x7f8f6d20ae00 onEmpty()
I0225 12:58:43.279376    61 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20b100 in thread 0x7f8f65409000
I0225 12:58:43.279397    61 Acceptor.cpp:397] Acceptor=0x7f8f6d20b100 onEmpty()
I0225 12:58:43.279460    62 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20b400 in thread 0x7f8f64608000
I0225 12:58:43.279482    62 Acceptor.cpp:397] Acceptor=0x7f8f6d20b400 onEmpty()
I0225 12:58:43.279525    63 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20b700 in thread 0x7f8f63808000
I0225 12:58:43.279548    63 Acceptor.cpp:397] Acceptor=0x7f8f6d20b700 onEmpty()
I0225 12:58:43.279590    64 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20ba00 in thread 0x7f8f62a08000
I0225 12:58:43.279978    64 Acceptor.cpp:397] Acceptor=0x7f8f6d20ba00 onEmpty()
I0225 12:58:43.280068    65 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d20bd00 in thread 0x7f8f61c08000
I0225 12:58:43.280104    65 Acceptor.cpp:397] Acceptor=0x7f8f6d20bd00 onEmpty()
I0225 12:58:43.280153    66 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d235000 in thread 0x7f8f60e08000
I0225 12:58:43.280239    66 Acceptor.cpp:397] Acceptor=0x7f8f6d235000 onEmpty()
I0225 12:58:43.280292    67 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d235300 in thread 0x7f8f60008000
I0225 12:58:43.280324    67 Acceptor.cpp:397] Acceptor=0x7f8f6d235300 onEmpty()
I0225 12:58:43.280383    68 Acceptor.cpp:453] Dropping all connections from Acceptor=0x7f8f6d235600 in thread 0x7f8f5f208000
I0225 12:58:43.280409    68 Acceptor.cpp:397] Acceptor=0x7f8f6d235600 onEmpty()
I0225 12:58:43.280809     1 RaftexService.cpp:152] Server thread has stopped. Service on port 0 is ready to be destroyed
E0225 12:58:43.280833     1 NebulaStore.cpp:52] Start the raft service failed
E0225 12:58:43.280849     1 MetaDaemon.cpp:86] Nebula store init failed
I0225 12:58:43.280862     1 NebulaStore.cpp:31] Cut off the relationship with meta client
I0225 12:58:43.280875     1 NebulaStore.cpp:33] Stop the raft service...
I0225 12:58:43.280891     1 NebulaStore.cpp:35] Waiting for the raft service stop...
I0225 12:58:43.281114     1 NebulaStore.cpp:40] ~NebulaStore()
I0225 12:58:43.281132     1 ThriftClientManager.h:25] ~ThriftClientManager
E0225 12:58:43.281180     1 MetaDaemon.cpp:218] Init kv failed!

**Your Environments (__must be provided__)**

* OS: `kubernetes`
* Docker Image: `vesoft/nebula-metad:nightly`, (`DIGEST:sha256:673353927edff9e0d6f3e6d46f9ebfe63ee5a6fd2b706ebb40186a6af142639b`)

**How To Reproduce(__must be provided__)**

1. helm install nebula ./ --debug

**Comment by nereus-east** [comment]
@jude-zhu

**Comment by MegaByte875** [comment]
@nereus-east  I found an error at first line,  --flagfile=/usr/local/nebula/etc/nebula-m.conf，it should be "nebula-metad.conf"， and we provide new version helm [charts](https://github.com/vesoft-inc/nebula-docker-compose/tree/master/charts)，nebula 2.0 supports internal DNS address communication，you cant try it, also the new version charts support host network mode.

**Comment by nereus-east** [comment]
Thank you for your reply. Actually, 'nebula-m.conf' was changed by myself.
As far as I am concerned, the real reason for this issue is ['hostNetwork: true'](https://github.com/vesoft-inc/nebula/blob/ad8899e5429f7e3cac4c65291bad898e64209d82/kubernetes/helm/templates/statefulset.yaml#L26), resulting in port conflict (Address already in use).
Now I've solved it, thank you!
