### ISSUE TITLE
Client for Rust

### ISSUE THREAD

**Issue by pranaypratyush** [vesoft-inc/nebula#2451]
**Is your feature request related to a problem? Please describe.**
My backend is mostly in Typescript/Node.js with a bit of Rust. I don't want to use other languages.

**Describe the solution you'd like**
Need client for Node.js and Rust.

**Describe alternatives you've considered**
Moving to Go or python is possible but just for nebula is a pain. Deal breaker.

**Comment by jamieliu1023** [comment]
@pranaypratyush Here is a simple version of Nodejs client: https://github.com/vesoft-inc/nebula-node/pull/1
Please have a try and let us know if it works for you. Also, welcome to contribute to the client and make it better!
