### ISSUE TITLE
NQL with varia-len traversal steps

### ISSUE THREAD

**Issue by wolfkdy** [vesoft-inc/nebula#2452]
**Is your feature request related to a problem? Please describe.**

from nebula2.0 manual,  traveral grammar is list below.
```
GO [[<M> TO] <N> STEPS ] FROM <vertex_list>
OVER <edge_type_list> [REVERSELY] [BIDIRECT]
[WHERE <expression> [AND | OR expression ...])]
YIELD [DISTINCT] <return_list>
```
It seems N is a number, and can not be a range.

However, Cypher supports range as traversal steps.
quoted from openCypher9 specs
```
MATCH (martin {name: 'Charlie Sheen'})-[:ACTED_IN*1..3]-(movie:Movie)
RETURN movie.title
```
Does nebula support range as step now? If so, could you please comment below the machable query sentence ?
If it is not supported now, could you please give an alternative way for this feature?

**Comment by whitewum** [comment]
Nebula 2.0 supports  var-length path by partially compatible with openCypher 9.

https://docs.nebula-graph.io/2.0/3.ngql-guide/7.general-query-statements/2.match/#match_variable-length_paths

Besides, [[<M> TO] <N> STEPS ]  denotes a range.  i. e., from M to N STEPS, or UPTO N STEPS.
