### ISSUE TITLE
双向遍历时 _src、_dst 的问题

### ISSUE THREAD

**Issue by qinglok** [vesoft-inc/nebula#2457]
不知道为啥在双向遍历时，_src、_dst的值是反的，这是正常的还是Bug？

**Comment by Shinji-IkariG** [comment]
_src表示遍历的起始点，以nba数据集为例，src表示从102点开始，dst为102关注且关注102的点。
![image](https://user-images.githubusercontent.com/58841610/111109833-70439d00-8596-11eb-872b-a92b96670bcd.png)

**Comment by qinglok** [comment]
谢谢
