### ISSUE TITLE
Redundant declaration of properties when inserting vertices

### ISSUE THREAD

**Issue by kindlychung** [vesoft-inc/nebula#2466]
Example:

```
CREATE TAG player(name string, age int);
INSERT VERTEX player(name, age) VALUES "player100":("Tim Duncan", 42);
```

We are basically delaring the player type twice here.

Ideally we should be allowed to do:

```
INSERT VERTEX player VALUES "player100":("Tim Duncan", 42);
```

**Comment by jude-zhu** [comment]
Do u mean, if adding values for all the columns of the table, users do not need to specify the property names?

**Comment by kindlychung** [comment]
> Do u mean, if adding values for all the props of a tag/ an edge, users do not need to specify the property names?

Yeah.

**Comment by CPWstatic** [comment]
Implemented by https://github.com/vesoft-inc/nebula-graph/pull/971
