### ISSUE TITLE
nebula目前无法支持中文的属性和关系名称，为了后期使用方便，我们希望建立中文的属性名称，这个是否能支持一下？

### ISSUE THREAD

**Issue by chenpe32cp** [vesoft-inc/nebula#2467]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jude-zhu** [comment]
Since nebula is about to support comment when creating the schema, Chinese character support is not on the roadmap
