### ISSUE TITLE
document "Nebula Graph CRUD" is wrong?

### ISSUE THREAD

**Issue by HeChuanXUPT** [vesoft-inc/nebula#2470]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

FAQ 404:
https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md

**Describe the bug (__must be provided__)**

![image](https://user-images.githubusercontent.com/5425689/114333188-520f9380-9b7a-11eb-9bdb-0502e60a82a8.png)
example in https://docs.nebula-graph.io/2.0/2.quick-start/4.nebula-graph-crud/
```
nebula> INSERT VERTEX player(name, age) VALUES "player100":("Tim Duncan", 42);
Execution succeeded (time spent 2919/3485 us)
```

got error:
> Storage Error: The VID must be a 64-bit interger or a string.

So the official document is wrong?

**How To Reproduce(__must be provided__)**

1. follow the Nebula Graph CRUD guide

**Comment by randomJoe211** [comment]
Hi there! Thank you for your concern. 

1. The link you provided is out of date. Please find the [FAQ](https://docs.nebula-graph.io/2.0/2.quick-start/0.FAQ/) doc in our doc center.

2. Looks like the Nebula Graph you deployed was the 1.x version, but the docs you read were for the 2.x version. Please find the Nebula Graph 2.x versions on [nebula-graph](https://github.com/vesoft-inc/nebula-graph). In v2.x you can set the VID type (int or string) when creating the space.
    ![image](https://user-images.githubusercontent.com/69501902/114485251-2ce45900-9c3e-11eb-961d-e8cdaa0adaed.png)

Let us know if you have any other questions.

**Comment by HeChuanXUPT** [comment]
@randomJoe211 
Hi, deployed version is v2.1.3-beta, not 1.x
![image](https://user-images.githubusercontent.com/5425689/114492523-55268480-9c4b-11eb-8e36-f80deb05cebd.png)

**Comment by randomJoe211** [comment]
OK. Then string VID should be supported. Please make sure you have followed the doc while creating the graph space. The `vid_type` option is a must if you need string VIDs like the examples in the docs show.

**Comment by HeChuanXUPT** [comment]
```
INSERT VERTEX player2(name, age) VALUES "player10":("Tim Duncan", 42);
success

INSERT VERTEX player2(name, age) VALUES "player100":("Tim Duncan", 42);
error: Storage Error: The VID must be a 64-bit interger or a string.
```
player10 s 8B, player100 s 9B.
VID can support string, but is only most 64bit=8B=8charactors.

**Comment by randomJoe211** [comment]
Try:
CREATE SPACE basketballplayer(partition_num=15, replica_factor=1, vid_type=fixed_string(32));

You'll be able to store 32-character string VIDs.

**Comment by HeChuanXUPT** [comment]
Thanks, it works well for me.
