### ISSUE TITLE
Find Path | Match 非预期的结果

### ISSUE THREAD

**Issue by tbyes** [vesoft-inc/nebula#2471]
**Describe the bug (__must be provided__)**
`FIND NOLOOP PATH FROM A,B,C TO A,B,C OVER call UPTO 15 STEPS 
| RETURN [n IN nodes($-.path) | id(n)] AS vid
| MATCH (v:app) WHERE id(v) IN $-.vid RETURN v.name`

1. A、B、C三个点实际存在，执行到Return [n IN nodes($-.path)]……时，结果如下
![image](https://user-images.githubusercontent.com/2949799/114417962-a4859a00-9be4-11eb-8442-ac4c0845c050.png)

2. 通过管道，继续执行 | MATCH (v:app) WHERE id(v) IN $-.vid RETURN v.name`，竟然就没有任何返回了
![image](https://user-images.githubusercontent.com/2949799/114418138-cb43d080-9be4-11eb-9646-81c28366194c.png)

这里我想查出路径上所有点，并从点的TAG里取如名称之类的字段，但是 FindPath 返回的路径信息不支持直接访问点对应的TAG（体验挺不好其实）

**Your Environments (__must be provided__)**

* OS: `uname -a`：
Darwin liuxingchendeMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
* Compliler: `g++ --version` or `clang++ --version`
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**Expected behavior**

希望能执行，并能够访问路径中每个点的TAG。最终会根据TAG的信息来做聚合再对路径去重。

**Additional context**

None

**Comment by nevermore3** [comment]
目前还不支持 pipe 后面接 match 这样的操作

**Comment by nevermore3** [comment]
你可以先 分两条语句 
1、FIND NOLOOP PATH FROM A,B,C TO A,B,C OVER call UPTO 15 STEPS | RETURN [n IN nodes($-.path) | id(n)] AS vid 
把这个结果取出来
2、再用 fetch prop on app yield app.name
后续我们会对match的性能 进行调优

**Comment by tbyes** [comment]
> 你可以先 分两条语句
> 1、FIND NOLOOP PATH FROM A,B,C TO A,B,C OVER call UPTO 15 STEPS | RETURN [n IN nodes($-.path) | id(n)] AS vid
> 把这个结果取出来
> 2、再用 fetch prop on app yield app.name
> 后续我们会对match的性能 进行调优

好的，感谢
为啥FIND PATH方法返回路径信息中的与点的信息只有ID呢
如果想FIND PATH之后，获得每个路径上每个点的TAG值，感觉找不到什么办法
只能在代码里遍历点的ID，然后一个一个拿
如果能有个像id(vertext)的方法可以直接获得点对象就好了，比如 vertext(vertext_id) 这种，使用上就会非常方便了 @nevermore3

**Comment by nevermore3** [comment]
> > 你可以先 分两条语句
> > 1、FIND NOLOOP PATH FROM A,B,C TO A,B,C OVER call UPTO 15 STEPS | RETURN [n IN nodes($-.path) | id(n)] AS vid
> > 把这个结果取出来
> > 2、再用 fetch prop on app yield app.name
> > 后续我们会对match的性能 进行调优
> 
> 好的，感谢
> 为啥FIND PATH方法返回路径信息中的与点的信息只有ID呢
> 如果想FIND PATH之后，获得每个路径上每个点的TAG值，感觉找不到什么办法
> 只能在代码里遍历点的ID，然后一个一个拿
> 如果能有个像id(vertext)的方法可以直接获得点对象就好了，比如 vertext(vertext_id) 这种，使用上就会非常方便了 @nevermore3

其实find path 返回的path结构里面 存储的是每个点的 vertex结构，只不过现在vertex结构里只写了 ID，其他属性没有填充，已经有PR 会带上路径上点的属性信息了，现在还没有合入，还在review 
https://github.com/vesoft-inc/nebula-graph/pull/433

**Comment by tbyes** [comment]
3KS
