### ISSUE TITLE
nesting collect inside a predicate crashes nebula console

### ISSUE THREAD

**Issue by kindlychung** [vesoft-inc/nebula#2473]
Example code to reproduce the bug:

```
unwind [1, 2, 3, 4, 5] as a return a * 2 as x | return any(n in collect($-.x) where n > 5) as mybool
```

* OS: Linux 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* CPU: 
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           8
Model name:                      AMD Ryzen Threadripper 2990WX 32-Core Processor

* Docker image (v2-nightly) digest: 
```
vesoft/nebula-graphd                                 v2-nightly                      sha256:453a845b98281a92fa0c0168eeda617fbba140ea798c7776411b50e816f648f2   9e108e014450        3 hours ago         284MB
vesoft/nebula-metad                                  v2-nightly                      sha256:0dcce1053e6259277d145293b1d393ac9b1f3919fdca0a7432d823f017297a60   416f3080e14d        4 hours ago         290MB
vesoft/nebula-storaged                               v2-nightly                      sha256:9d4d4706cb38132c0dec70a1b3a0ebbc245ecfe2d7d9c53c3741edc498988f3b   6d47142bd4d5        4 hours ago         291MB
```

**Expected behavior**

```
+--------+
| mybool |
+--------+
| true   |
+--------+
```

Provide logs and configs, or any other context to trace the problem:

```
2021/04/15 00:38:02 [INFO] Successfully reconnect to host: 127.0.0.1, port: 29669
2021/04/15 00:38:02 Loop error, EOF

Bye root!
Thu, 15 Apr 2021 00:38:02 CEST

panic: Loop error, EOF

goroutine 1 [running]:
log.Panicf(0x7906b8, 0xe, 0xc000133e78, 0x1, 0x1)
        /opt/hostedtoolcache/go/1.14.15/x64/src/log/log.go:358 +0xc0
main.main()
        /home/runner/work/nebula-console/nebula-console/main.go:386 +0x4e1
```

**Comment by jievince** [comment]
Hi, thanks for reporting this bug, we‘ll fix it as soon as possible

**Comment by czpmango** [comment]
Fixed in [https://github.com/vesoft-inc/nebula-graph/pull/958](https://github.com/vesoft-inc/nebula-graph/pull/958)
