### ISSUE TITLE
nebula-graphd generates a large number of processes, and excessive use of the number of processes causes further system crashes

### ISSUE THREAD

**Issue by IanLiYi1996** [vesoft-inc/nebula#2474]
Dear developers,
In actual use, we found that the database will automatically start a large number of processes, causing the machine to crash, but we don't know what the cause is. I hope you can help us explore and look forward to solving this problem together.
Good luck and look forward to your early reply
![BA6307DF-8E1C-409F-BA3B-1E28D0397481](https://user-images.githubusercontent.com/25996678/117523168-da524e80-afe9-11eb-8030-a68f89ebe461.png)
[pstree.txt](https://github.com/vesoft-inc/nebula/files/6445028/pstree.txt)

**Comment by CPWstatic** [comment]
Would you please describe how can we reproduce the scenario? We'd appreciate if you could provide us information about your `environment`, `deployment`, `queries`.

**Comment by IanLiYi1996** [comment]
**The machine information used by the deployment map database is as follows**
        _environment：Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-131-generic x86_64)
        deployment:  docker-compose as the document recommended
        queries: None_

When we encountered the above problem, we installed nebula studio to manage the database, and the machine crashed within a day. The cause of the crash was consistent with what I described. It was caused by the abnormal start of too many child processes by the nebula service itself.

By the way, before the machine crashed, we did not perform any data operations

**Comment by dutor** [comment]
What do you mean by __*machine*__ crash, some of the service processes crashed or the OS panic? If it is the panic case, could you provide related logging messages? Normally, you could find the log at /var/log/messages.

**Comment by dutor** [comment]
Otherwise, if the number of processes exceeds `ulimit -u`, you could change it to some larger number

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
