### ISSUE TITLE
下载ubuntu版本报错

### ISSUE THREAD

**Issue by binglinchengxiash** [vesoft-inc/nebula#2475]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
![image](https://user-images.githubusercontent.com/15050040/117956662-d7d65880-b34b-11eb-8f91-cc81793f16ab.png)

3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by wey-gu** [comment]
Thank you @binglinchengxiash  for raising issue here.

Which file are we talking about now?

Is it files from https://github.com/vesoft-inc/nebula-graph/releases ? or?
