### ISSUE TITLE
查询返回数据量过大报错，limit使用无效

### ISSUE THREAD

**Issue by wx-123456** [vesoft-inc/nebula#2477]
在业务查询过程中，起始点通过关系找到对应的点，查询出来的点的数量属于不可控的，数据量过大查询时间长并且会导致报错，不可能每次功能都先测试下这个查询出来结果的数据是否会因为数据量大导致错误。同时根据测试，limit是从全部数据中限制数量，一样的问题数据量过大查询时间长并且会导致报错。
需求：希望能对查询的数据进行限制或者说是支持下推，能够对查询返回部分数据，类似于关系数据的limit。

如果有相关计划，想问下什么时候能够支持这个功能？

**Comment by wey-gu** [comment]
Dear @wx-123456 ,

limit 下推的优化还在进行中，我们在努力做这一块哈。
Thanks!

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
