### ISSUE TITLE
nebula-console reports "authenticate failed: wrong method name"

### ISSUE THREAD

**Issue by caijimin** [vesoft-inc/nebula#2482]
**Describe the bug (__must be provided__)**

./nebula-console -port 9559 -u aaa -p aaa
2021/06/07 22:03:58 [INFO] connection pool is initialized successfully
2021/06/07 22:03:58 Fail to create a new session from connection pool, Authentication fails, authenticate failed: wrong method name
panic: Fail to create a new session from connection pool, Authentication fails, authenticate failed: wrong method name

**Your Environments (__must be provided__)**

* OS:  ubuntu 20.04

**How To Reproduce(__must be provided__)**

Use nebula-graph-2.0.1.ubuntu2004.amd64.deb to install, then "nebula.service start all"

All the conf file are default
nebula-graphd.conf
--enable_authorize=false

./nebula-console -port 9559 -u aaa -p aaa
2021/06/07 22:03:58 [INFO] connection pool is initialized successfully
2021/06/07 22:03:58 Fail to create a new session from connection pool, Authentication fails, authenticate failed: wrong method name
panic: Fail to create a new session from connection pool, Authentication fails, authenticate failed: wrong method name

./nebula-console -port 19669 -u aaa -p aaa
2021/06/07 22:16:48 [INFO] connection pool is initialized successfully
2021/06/07 22:16:49 Fail to create a new session from connection pool, Authentication fails, EOF
panic: Fail to create a new session from connection pool, Authentication fails, EOF

**Expected behavior**

cosole can login

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by jievince** [comment]
It's `-port 9669`, not `9559`

**Comment by caijimin** [comment]
Got it, thanks.
Sorry for my carelessness.
