### ISSUE TITLE
stop time is confused when the job is running 

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#2526]
stop time `1970-01-01` is confused when the job is running.

it may be confused for users.

![image](https://user-images.githubusercontent.com/1726587/129665908-27c2b2b4-41da-4ef5-b7d3-568c2f1b2335.png)

**Comment by Shylock-Hg** [comment]
Yes, better fill empty when before stop.

**Comment by CPWstatic** [comment]
Fixed by #2784.
