### ISSUE TITLE
Piped fetch clause failed reporting error on legal input

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#2545]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: Linux vince.wu-53 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: cmake version 3.15.5, g++ (Nebula Graph Build) 7.5.0
* CPU: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.30GHz
* Commit id `v2-nightly`

**How To Reproduce(__must be provided__)**

![image](https://user-images.githubusercontent.com/451943/130201956-6567c6f0-0b36-4925-ac0b-14c056f70df7.png)

**Expected behavior**

Piped fetch clause should yield correct result.

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by Shylock-Hg** [comment]
It's the expected result. We don't allow multiple input in sentence.

**Comment by kikimo** [comment]
I see, fetch support two types of input:

1. constant list
2. piped column(only one column allowed) 

right? @Shylock-Hg

**Comment by Shylock-Hg** [comment]
> I see, fetch support two types of input:
> 
> 1. constant list
> 2. piped column(only one column allowed)
> 
> right? @Shylock-Hg

Yes.
