### ISSUE TITLE
how to describe the user?

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#2574]
Now i can lookup all users in a space, but i could not find a way to describe a user like this:

```
describe user root;

| user | roles in spaces |
+:----+----------------+
| root | root in nba, admin in sp2 |
```

**Comment by bright-starry-sky** [comment]
as below ?
query = 'SHOW ROLES IN space'
expected_result = [['guest', 'GUEST'],
                   ['user', 'USER'],
                   ['dba', 'DBA'],
                   ['admin', 'ADMIN']]

**Comment by yixinglu** [comment]
> as below ?
> query = 'SHOW ROLES IN space'
> expected_result = [['guest', 'GUEST'],
> ['user', 'USER'],
> ['dba', 'DBA'],
> ['admin', 'ADMIN']]

I know the `show roles in space` usage. Now `SHOW users` only give the name of user. I don't know how to get more information if i am interest in a special user.

**Comment by critical27** [comment]
Could consider later if necessary, not so important
