### ISSUE TITLE
Two different error messages in the same case

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#2578]
Nebula Graph version:

I was testing the index selection feature for `LOOKUP`, but found that when there is no index to use, Nebula Graph shows two different error messages:
`[ERROR (-1005)]: Storage Error: Index not found.` and `[ERROR (-1005)]: There is no index to use at runtime`.

![image](https://user-images.githubusercontent.com/69501902/130398361-08a268f6-527a-48e3-b8a2-b1d976b56ff4.png)

Was this because the storage error code leaked out? They have the same code number `1005`.

**Comment by Sophie-Xie** [comment]
Consistency of functions
