### ISSUE TITLE
Limit push down over filter

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#2583]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__must be provided__)**

See detail in https://discuss.nebula-graph.com.cn/t/topic/5474

And the limit shouldn't perform before filter operation (e.g. filter, dedup and etc.)

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by critical27** [comment]
Same with #2602, this is closed

**Comment by Shylock-Hg** [comment]
Sub job of #2602
