### ISSUE TITLE
[QE]Parameterized statement

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2593]
- [ ] vesoft-inc/nebula-studio#4
- [x] https://github.com/vesoft-inc/nebula-python/issues/162
- [ ] https://github.com/vesoft-inc/nebula-cpp/issues/59
- [ ] https://github.com/vesoft-inc/nebula-go/issues/151
- [ ] https://github.com/vesoft-inc/nebula-java/issues/377

**Comment by czpmango** [comment]
The parameterized index push-down was blocked due to the storage::RocksRangeIterator's open/close interval problem and graph::Optimizer ::boundValue related refactoring. 
Related feature(parameterized index push-down) will be implemented after the above refactoring is complete.
