### ISSUE TITLE
[STO]More test cases to cover the Zone feature

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2605]
test design review: 9.6

**Comment by HarrisChu** [comment]
Generally run zone test cases automatically, refer to https://github.com/HarrisChu/nebula/actions/runs/1282036391
But it would change tck behavior and depend on k8s.

It won't merge to master in v2.6.0, just run a long time, and then merge to master in next milestone.
@Sophie-Xie

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula/pull/2841
