### ISSUE TITLE
[RFC] Plan cache

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#2619]
# Summary
Cache historical execution plans to avoid replanning for the same/similar query.

# Motivation
   Avoid replanning to reduce the overhead of the planner and optimizer.

# Usage explanation
   Invisible to the user.

# Design explanation
   - two-level cache
       - string cache 
          Hash the query statement.
       - AST cache  (match (v{age:18}) <=> match (v) where v.age=18)
          Hash the normalized AST.
   - configs
       - cache size
       - replan_interval : validity period of cached plan
       - statistics_divergence_threshold : tolerance threshold for statistical changes
   - LFU
      Cache elimination strategy.

*Note: schema changes(such as index/constraint creation/removal) will flush the entire query plan cache.*

# Rationale and alternatives

# Drawbacks
This may be a trade-off  in the CBO scenario, which mean It may cause performance degradation of the execution plan.

# Prior art

# Unresolved questions
  - can't apply to CBO scenarios for nebula
  - ...

# Future possibilities
   - supports CBO scenarios
   - ...

**Comment by czpmango** [comment]
> cache the generated plan before CBO stage, and

Setting `statistics_divergence_threshold` to 0 has the same effect.

**Comment by czpmango** [comment]
> Do you consider the explicit usage like the `prepare` statement in sql, e.g. https://www.postgresql.org/docs/9.4/sql-prepare.html ?

Just the same thing. Implicit usage is more user-friendly, I think.

**Comment by Shylock-Hg** [comment]
> > Do you consider the explicit usage like the `prepare` statement in sql, e.g. https://www.postgresql.org/docs/9.4/sql-prepare.html ?
> 
> Just the same thing. Implicit usage is more user-friendly, I think.

Yes, I think could provide both.

**Comment by czpmango** [comment]
> > > Do you consider the explicit usage like the `prepare` statement in sql, e.g. https://www.postgresql.org/docs/9.4/sql-prepare.html ?
> > 
> > 
> > Just the same thing. Implicit usage is more user-friendly, I think.
> 
> Yes, I think could provide both. The implicit mode is enable by flag, the explicit is enable by query directly.

This can be considered, but it will increase the complexity of the syntax.
This RFC mainly refers to the implementation of neo4j.

**Comment by czpmango** [comment]
Out of date.
