### ISSUE TITLE
identifiers support multi characters including chinese

### ISSUE THREAD

**Issue by suntrian** [vesoft-inc/nebula#2624]
`LABEL                       ([a-zA-Z][_a-zA-Z0-9]*)`
the label's define in scanner.lex is too simple, if it could support more characters , including chinese, japanese and any other langs. 
and generally it is called identifier or ident for simple.
reference:
[postgre lex file](https://github.com/postgres/postgres/blob/master/src/backend/parser/scan.l)
[mysql antlr4 lexer](https://github.com/mysql/mysql-workbench/blob/87e1e5e88a99308e9be66be98acbe56fdf9e9367/library/parsers/grammars/MySQLLexer.g4)

**Comment by Sophie-Xie** [comment]
Sorry, we have no plan to support it.
