### ISSUE TITLE
support connecting to clickhouse?

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula#2670]
未来是否有支持clickhouse的计划？

**Comment by wey-gu** [comment]
Clickhouse sink is supported in nebula-exchange now.


ref: https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-exchange
ref: https://docs.nebula-graph.com.cn/2.5.0/nebula-exchange/use-exchange/ex-ug-import-from-clickhouse/
