### ISSUE TITLE
Zone number limit on creating a space on a group does not work

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#2672]
To create a space on a group, the zone number of the group should not be less than the space replica number.

Group `group_1` has only one zone:
![image](https://user-images.githubusercontent.com/69501902/111589512-e5fe7180-87ff-11eb-97f2-88a745239a84.png)

So I should not be able to create a space that has more than 1 replicas on `group_1`, but I created a 3-replica space:
![image](https://user-images.githubusercontent.com/69501902/111589661-1a722d80-8800-11eb-9c1f-c7f2859e700e.png)

**Comment by darionyaphet** [comment]
```
(root@nebula) [(none)]> CREATE SPACE test_2(partition_num=1, replica_factor=2, vid_type=int64) ON g_1
[ERROR (-1005)]: Invalid parm!

Thu, 16 Sep 2021 20:14:07 CST
```

have fixed and close it
