### ISSUE TITLE
Succeeded in creating space on GROUP when GROUP is not created

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#2674]
I created a graph space on a non-existing group `group_1` and succeeded:

![image](https://user-images.githubusercontent.com/69501902/111298328-96963500-8689-11eb-9b7a-aa28de53ab63.png)

`SHOW CREATE SPACE` shows that the space is created on `default`:

![image](https://user-images.githubusercontent.com/69501902/111298412-add52280-8689-11eb-8614-7ea3d409e375.png)

**Comment by darionyaphet** [comment]
```
(root@nebula) [(none)]> CREATE SPACE test_2(partition_num=1, replica_factor=1, vid_type=int64) ON g_2
[ERROR (-1005)]: Group not existed!

Thu, 16 Sep 2021 20:14:45 CST

```

fixed and close
