### ISSUE TITLE
Automatically generate string type vertex ID

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula#2683]
目前的nebula的顶点ID都需要用户手动指定，2.0版本增加了字符串类型，但是需要用户自己来设定字符串长度并控制节点名称的长度，使用起来十分不方便，是否可以在用户层与nebula逻辑层中间加一个自动化的md5类型ID的计算逻辑，用户输入的可以是任意长度的字符串节点名称，经过md5映射后就是一个唯一的长度固定的32位id，从而实现了更便捷的操作和更有效的存储；另外对于用户操作可以将这个md5映射层透明掉，让用户对于这个id的指定后的存储类型无需手动管理

**Comment by Sophie-Xie** [comment]
Pls try to generate int64 VID via hash.

https://docs.nebula-graph.com.cn/2.5.0/1.introduction/3.vid/#vid_3
