### ISSUE TITLE
Leader change often occurs after v2.0.0

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula#2719]
https://discuss.nebula-graph.com.cn/t/topic/3776

**Comment by yout0703** [comment]
请问这个问题还会解决吗，目前我们用的 2.0.1 的客户端和服务端，只要并发高一些就会出现 Leader change ，之后就会导致大量数据写入失败。 如果需要长期才能解决，是否有替代方案呢。谢谢

**Comment by wey-gu** [comment]
@critical27 could we close this via https://github.com/vesoft-inc/nebula-storage/pull/423 ?

**Comment by liebkne** [comment]
使用2.6的时候importer一直报这个错误，请问怎样解决？

**Comment by critical27** [comment]
Check if leader has changed or not in `show hosts`.

**Comment by critical27** [comment]
Fixed in https://github.com/vesoft-inc/nebula-storage/pull/438 already
