### ISSUE TITLE
Unexpected result of getProps

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#2725]
The getProps won't return row of vertex which don't contains the request tag.
e.g. in space nba
If we have 
```
'Spurs'
```
as the request vids.
And 
```
player.age
```
as the request properties.
We will get empty result even if the vid 'Spurs' is existed in space.

**Comment by critical27** [comment]
We will convert to getVertices instead of getTags in 1230

**Comment by Sophie-Xie** [comment]
resolve in：https://github.com/vesoft-inc/nebula/issues/2535
