### ISSUE TITLE
Implicit conversions that increase the default value are saved in accordance with the conversion rules for rowWriterv2

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula#2729]
![Screen Shot 2021-05-27 at 10 47 07](https://user-images.githubusercontent.com/48548375/119758302-e76fa880-bed8-11eb-86cd-7c233f92cd36.png)

**Comment by CPWstatic** [comment]
I don't quite understand what the problem is.

**Comment by critical27** [comment]
Maybe I have understood this problem, I'll check it later

**Comment by critical27** [comment]
I have checked, this is because when insert with integer 15, it will need to convert to `15.0` because the schema is double, this is reasonable I think.

**Comment by critical27** [comment]
Closed for now.
