### ISSUE TITLE
br: storage cannot be stopped or started successfully during the restoration process

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula#2736]
After restoration, the message reads the process is successful. But when I check the status of the Nebula Graph services, the storage is not started. 

![image](https://user-images.githubusercontent.com/61895496/102862360-f2c33180-446b-11eb-91bd-accc6b026342.png)

**Comment by bright-starry-sky** [comment]
Manually verified, the problem no longer exists. 
so can you test again and close this issue if problem no longer exists? @oldLady344 
And please move this issue to BR repo.

**Comment by bright-starry-sky** [comment]
Close this issue. problem solved
