### ISSUE TITLE
Use a lot of memory RAM

### ISSUE THREAD

**Issue by linuxpham** [vesoft-inc/nebula#2740]
Hi admin,

I wonder why is nebula-storage used a lot of memory? Is it leak memory ?

<img width="1648" alt="Screen Shot 2020-08-20 at 10 37 30" src="https://user-images.githubusercontent.com/154762/90714124-28df8180-e2d1-11ea-83be-53f40843d2e1.png">

After restart, use a lot of CPU (a little memory RAM) : 

<img width="1658" alt="Screen Shot 2020-08-20 at 10 39 58" src="https://user-images.githubusercontent.com/154762/90714277-84117400-e2d1-11ea-93cd-70ac808b9cd2.png">

<img width="1654" alt="Screen Shot 2020-08-20 at 10 42 30" src="https://user-images.githubusercontent.com/154762/90714441-dbafdf80-e2d1-11ea-9413-4e2d02f1ca2c.png">

**Comment by critical27** [comment]
Talked long before in forums.
