### ISSUE TITLE
Deb don't   support the specified directory installation

### ISSUE THREAD

**Issue by guici123** [vesoft-inc/nebula#2750]
sudo dpkg -i --instdir=/data nebula-graph-2.0.0.ubuntu1604.amd64.deb 安装失败
![image](https://user-images.githubusercontent.com/26181041/113368160-950a8380-9390-11eb-85dc-337a843a11b1.png)

**Comment by wey-gu** [comment]
Some more mates are querying on status of this issue :-)

https://discuss.nebula-graph.com.cn/t/topic/3374

**Comment by Shylock-Hg** [comment]
We could provide the tar package for this.
