### ISSUE TITLE
`USER` Priviledge of `SHOW TAG INDEX STATUS` is incorrect 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#2751]
When I try the online playground to `SHOW TAG INDEX STATUS;`
it returns nothing.
The privilege is `USER`.

`USER` should have the privilege to show its `index status`.

![image](https://user-images.githubusercontent.com/50101159/131291953-5b0fb0c5-09ec-47e6-9222-fea4a8a113f9.png)
![image](https://user-images.githubusercontent.com/50101159/131291959-3fff8373-a50c-48c5-8bb6-e744a0512312.png)
![image](https://user-images.githubusercontent.com/50101159/131291991-1509130c-08c6-44ab-b7f9-02b173043080.png)
![image](https://user-images.githubusercontent.com/50101159/131292072-b81d993b-b11b-4ef9-ad48-49ee074b9281.png)

**Comment by CPWstatic** [comment]
```
(test@nebula) [nba]> show edge indexes
+--------------------+---------+----------------+
| Index Name         | By Edge | Columns        |
+--------------------+---------+----------------+
| "serve_start_year" | "serve" | ["start_year"] |
+--------------------+---------+----------------+
Got 1 rows (time spent 2015/6943 us)

Fri, 08 Oct 2021 15:09:11 CST

(test@nebula) [nba]> show edge index status
+------------------------+--------------+
| Name                   | Index Status |
+------------------------+--------------+
| "nba_all_edge_indexes" | "FINISHED"   |
+------------------------+--------------+
Got 1 rows (time spent 4298/12849 us)

Fri, 08 Oct 2021 15:09:16 CST

(test@nebula) [nba]> show users
+---------+
| Account |
+---------+
| "root"  |
+---------+
| "test"  |
+---------+
Got 2 rows (time spent 2740/10496 us)

Fri, 08 Oct 2021 15:10:07 CST

(test@nebula) [nba]> show roles in nba
+---------+-----------+
| Account | Role Type |
+---------+-----------+
| "test"  | "USER"    |
+---------+-----------+
Got 1 rows (time spent 3085/10355 us)

Fri, 08 Oct 2021 15:10:57 CST
```

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/136514079-32cbb982-db08-415a-b333-3de35b213d2d.png)

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/136514155-40ce34a5-efa5-4570-a13d-3cedb677ce2f.png)

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/136514325-1215a483-064e-4d3d-9cd8-559702183b38.png)

**Comment by whitewum** [comment]
the console and playground behave different
