### ISSUE TITLE
`ROOT` `SHOW ROLES IN ` returns nothing

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#2752]
when I'm an `admin`, `SHOW ROLES` returns someting

```ngql
nebula> SHOW ROLES in basketballplayer;
+---------+-----------+
| Account | Role Type |
+---------+-----------+
| "user1" | "ADMIN"   |
+---------+-----------+
```

when I'm `ROOT`, `SHOW ROLES` return nothing. It is really strange for `nothing`, but should be everything.
![image](https://user-images.githubusercontent.com/50101159/131292431-396872a2-f650-4fef-acd0-95323fd170ab.png)

**Comment by Shylock-Hg** [comment]
```
➜  nebula-console git:(master) ./nebula-console -u admin -p admin --address 127.0.0.1 --port 9669
2021/09/01 16:05:49 [INFO] connection pool is initialized successfully

Welcome to Nebula Graph!

(admin@nebula) [(none)]> show roles in nba
+---------+-----------+
| Account | Role Type |
+---------+-----------+
| "admin" | "ADMIN"   |
+---------+-----------+
Got 1 rows (time spent 2716/3836 us)

Wed, 01 Sep 2021 16:05:54 CST

(admin@nebula) [(none)]> exit

Bye admin!
Wed, 01 Sep 2021 16:05:57 CST

➜  nebula-console git:(master) ./nebula-console -u root -p nebula --address 127.0.0.1 --port 9669
2021/09/01 16:06:07 [INFO] connection pool is initialized successfully

Welcome to Nebula Graph!

(root@nebula) [(none)]> show roles in nba
+---------+-----------+
| Account | Role Type |
+---------+-----------+
| "admin" | "ADMIN"   |
+---------+-----------+
Got 1 rows (time spent 2657/3249 us)

Wed, 01 Sep 2021 16:06:14 CST
```

What's the version? I can't reproduce in v2.5.0. @whitewum

**Comment by cooper-lzy** [comment]
As user root, you should see not only admin's role type  but also root's role type. Maybe:
+---------+-----------+
| Account | Role Type  |
+---------+-----------+
| "root     " | "GOD"      |
+---------+-----------+
| "admin" | "ADMIN"    |
+---------+-----------+

**Comment by Shylock-Hg** [comment]
> As user root, you should see not only admin's role type but also root's role type. Maybe:
> +---------+-----------+
> | Account | Role Type |
> +---------+-----------+
> | "root " | "GOD" |
> +---------+-----------+
> | "admin" | "ADMIN" |
> +---------+-----------+

GOD is not a role of space, GOD has permission for any operation in all spaces.
