### ISSUE TITLE
Result string is truncated to the fixed index length in LOOKUP clause

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula#2758]
**Describe the bug (__must be provided__)**

As title. This problem only exists in `LOOKUP`, and `MATCH` works well.
Detail: https://discuss.nebula-graph.com.cn/t/topic/3628/10

**Your Environments (__must be provided__)**

v2.5.0

**How To Reproduce(__must be provided__)**

```
CREATE TAG player(name string, age int);
CREATE TAG INDEX name ON player(name(20))
LOOKUP ON player YIELD player.name
```

**Comment by critical27** [comment]
Same with #2745, discuss over there, close for now.
