### ISSUE TITLE
UT index_ttl_test is not stable

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#2761]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

I0831 14:35:11.951799 24317 AdminTaskManager.cpp:90] waiting for incoming task
F0831 14:35:11.951826 24322 RateLimiter.h:43] Check failed: buckets_.find({spaceId, partId}) != buckets_.end() 
*** Check failure stack trace: ***
*** Aborted at 1630391711 (Unix time, try 'date -d @1630391711') ***
*** Signal 6 (SIGABRT) (0x3fd000024d4) received by PID 9428 (pthread TID 0x7ff52cbff700) (linux TID 24322) (maybe from PID 9428, UID 1021) (code: -6), stack trace: ***

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: clang 10
* CPU: `lscpu`
* Commit id : master

**How To Reproduce(__must be provided__)**

Run UT directly.

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by critical27** [comment]
Mark
