### ISSUE TITLE
Time function support  difference, support conversion between string and time format

### ISSUE THREAD

**Issue by kerxyfy** [vesoft-inc/nebula#2767]
Support a method: time difference,requirement precision to seconds. 
Support a method: add a function of to_datetime, aim to solve String("yyyy-MM-dd HH:mm:ss")) or String("yyyyMMddHHmmss")) become a datetime

**Comment by Shylock-Hg** [comment]
You can try `datetime('yyyy-MM-dd HH:mm:ss')`

**Comment by Shylock-Hg** [comment]
For the time computation, now don't support.

**Comment by kerxyfy** [comment]
> You can try `datetime('yyyy-MM-dd HH:mm:ss')`

not support 'YYYY-MM-DD HH:mm:ss', own product support 'YYYY-MM-DDThh:mm:ss'.It lead to a time difference with the local time. Is it possible in the next version？

**Comment by Shylock-Hg** [comment]
> > You can try `datetime('yyyy-MM-dd HH:mm:ss')`
> 
> not support 'YYYY-MM-DD HH:mm:ss', own product support 'YYYY-MM-DDThh:mm:ss'.It lead to a time difference with the local time. Is it possible in the next version？

Done.

**Comment by xiajingchun** [comment]
Functions like datediff() to return the days between two dates are highly demanded by customers. Can we add at least datediff() in the coming release?

**Comment by Shylock-Hg** [comment]
> Functions like datediff() to return the days between two dates are highly demanded by customers. Can we add at least datediff() in the coming release?

Please open individual issue

**Comment by xiajingchun** [comment]
> > Functions like datediff() to return the days between two dates are highly demanded by customers. Can we add at least datediff() in the coming release?
> 
> Please open individual issue

https://github.com/vesoft-inc/requirement-holder/issues/38
