### ISSUE TITLE
parser error in lookup sentence

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#2785]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
```
(root@nebula) [t2]>  lookup on t where t.height<-1.0;
[ERROR (-1004)]: SyntaxError: syntax error near `<-'

(root@nebula) [t2]>  lookup on t where t.height< -1.0;
+----------+
| VertexID |
+----------+
+----------+
```
The second one has one space between `<` and `-`

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by Shylock-Hg** [comment]
It's not a bug but a syntax error. `<-` is the symbol of match pattern, so should add space for less than and negative number.

**Comment by cangfengzhs** [comment]
> It's not a bug but a syntax error. `<-` is the symbol of match pattern, so should add space between less than and negative number.

Maybe there is any way to resolve this grammatical ambiguity

**Comment by CPWstatic** [comment]
As said by @Shylock-Hg , it is a syntax error indeed.
