### ISSUE TITLE
Remove spinlock in MetaClient

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula#2786]
Bottleneck when compaction.  `getTagSchema/getEdgeSchema`. Use either threadlocal or rcu will be fine.

**Comment by cangfengzhs** [comment]
Writing will still block reading, RCU may be a better choice.And using RCU with doublebuffer may further improve performance by reducing cache line invalidation.

**Comment by critical27** [comment]
Talked offline. It is ok to use a threadlocal variable in this case. We only need to block when cache need to update, which is rare case.

**Comment by CPWstatic** [comment]
We had a threadlocal implementation in nebula1.0.

**Comment by critical27** [comment]
It seems it is a great bottleneck when rebuild index. Wait https://github.com/vesoft-inc/nebula-common/pull/440 move to nebula

**Comment by Sophie-Xie** [comment]
@critical27 Will it be resolved in v2.6.0?

**Comment by critical27** [comment]
addressed in 3.0
