### ISSUE TITLE
Create a all-in-one container for user to easier access/play with nebula

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#2791]
As titled, and we had that in 1.x if I recall it correctly :)

One case that makes this necessary is in ARM/M1 Mac the Docker Desktop is not in good enough shape to enable multi-container communication in case it's running x64 container, thus nebula-docker-compose won't work properly.

Thanks.

**Comment by yixinglu** [comment]
I don't want to provide users with such an all in one container. I prefer to build an arm-arch docker image for nebula to solve user problems. Later we can provide an all in one docker compose orchestration file, which can contain our nebula service, studio service or explore service and so on. This makes more sense for users to start all nebula services in one command.

**Comment by wey-gu** [comment]
> I don't want to provide users with such an all in one container. I prefer to build an arm-arch docker image for nebula to solve user problems. Later we can provide an all in one docker compose orchestration file, which can contain our nebula service, studio service or explore service and so on. This makes more sense for users to start all nebula services in one command.

Agreed, even better! That'll be awesome to have one compose file with both core and graphic interface services/observation services with arch64 support!
