### ISSUE TITLE
[TCK] delete vertex error

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#2800]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

```
_______________________________________________________________________________________________________________________________________________ test_delete_int_vid_vertex _______________________________________________________________________________________________________________________________________________
[gw6] linux -- Python 3.7.0 /usr/bin/python3
../../.local/lib/python3.7/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
../../.local/lib/python3.7/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
../../.local/lib/python3.7/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:413: in execution_should_be_succ
    check_resp(rs, stmt)
common/utils.py:329: in check_resp
    assert resp.is_succeeded(), msg
E   AssertionError: Fail to exec: DELETE VERTEX hash("LeBron James"), hash("Dwyane Wade"), hash("Carmelo Anthony");, error: Storage Error: More than one request trying to add/update/delete one edge/vertex at the same time.
```

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by critical27** [comment]
#2795

**Comment by riskgod** [comment]
Same issue, what's the stable version now ?
