### ISSUE TITLE
[STO]optimize job: Show job by space; Control the privilege when using “show all”;

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2815]

**Comment by critical27** [comment]
After some discuss, we will change the default behavior of `show jobs` to only print space related jobs.
And `show all` is useless (we don't have a job which can touch multiple space), we won't support it.

**Comment by panda-sheep** [comment]
Do `stop job` and `recover job `also need to be in the space?
All behaviors of job should be unified.@liuyu85 @critical27

**Comment by liuyu85cn** [comment]
Agree
