### ISSUE TITLE
Change the built-in NBA data set to basketballPlayer

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#2817]
It is recommended to change the built-in NBA data set to basketballPlayer.
Because a user might import an NBA data set and then use the sample command that only works in basketballPlayer.
![image](https://user-images.githubusercontent.com/78672629/132453439-88b17d21-af6b-4ce3-b5fb-5d1e788acca4.png)

**Comment by Shylock-Hg** [comment]
The https://github.com/vesoft-inc/nebula-console should process too.
