### ISSUE TITLE
Execute nGQL error

### ISSUE THREAD

**Issue by Freeself** [vesoft-inc/nebula#2826]
nGQL
```
CREATE TAG IF NOT EXISTS person(`_createTime` STRING,`specific_type` STRING,`key` STRING,`edges` STRING,`name` STRING)
```

error message

```
SyntaxError: syntax error near ``_create'
```

**Comment by wey-gu** [comment]
Sorry @Freeself

It's either not parsed properly or it's not supported (then we should have documented that) the underline cannot be in starting position.

```
(root@nebula) [basketballplayer]> CREATE TAG IF NOT EXISTS person(`createTime` STRING,`specific_type` STRING,`key` STRING,`edges` STRING,`name` STRING)
Execution succeeded (time spent 3066/45961 us)
```

Thanks!

**Comment by wey-gu** [comment]
@czpmango could you kindly help confirm if this is should be documented or fixed(that a prop name starts with `_`)?

**Comment by czpmango** [comment]
> @czpmango could you kindly help confirm if this is should be documented(as naming constraint) or fixed(that a prop name starts with `_`)?

The subsequent implementation will not be changed, and the variable naming rules follow the regular expression `([A-za-z][_A - za-z0-9]*)`.
