### ISSUE TITLE
can't upgrade the version by docker-compose in doc

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2835]
Step1
![image](https://user-images.githubusercontent.com/84560950/132790245-2911815e-81de-4c3b-b902-71f3e583076e.png)

Step2
![image](https://user-images.githubusercontent.com/84560950/132790288-d4dd70e6-b81d-4d3d-a4df-8223d6606ed4.png)

In docker-compose.yaml, the path is "vesoft/nebula-metad:v2.0.0", then I can't get the new version.
After upgrade yaml, then upgrade version is successful.

**Comment by cooper-lzy** [comment]
https://docs.nebula-graph.com.cn/2.5.0/4.deployment-and-installation/3.upgrade-nebula-graph/upgrade-nebula-from-200-to-250/#docker_compose
