### ISSUE TITLE
from v2.5.0, we can show the version, pls modify the doc

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2837]
in doc
![image](https://user-images.githubusercontent.com/84560950/132792174-9b865332-e719-4b77-9498-865e983b2de8.png)

if user gets the "release" version, there is the version id. if user gets the nightly version, there isn't the version id.
like this:
![image](https://user-images.githubusercontent.com/84560950/132792272-9e07ad2c-fd54-472d-a4a5-68fdcd62d50e.png)

**Comment by foesa-yang** [comment]
Docs has been modified.
https://github.com/vesoft-inc/nebula-docs-cn/pull/971
