### ISSUE TITLE
nebula graph timeout

### ISSUE THREAD

**Issue by wzg-zhuo** [vesoft-inc/nebula#2845]
cat graphd-stderr.log,记录如下
Storage Error: part: 5, error: E_RPC_FAILURE(-3)
Request to ip:9779 failed: N6apache6thrift9transport19TTransportExceptionE: Timed Out
每次打开客户端/studio查询，都会出现，过一段时间会好，但这样无法满足实际查询需求（用户查询时间不固定）
增大storage_client_timeout_ms时间无作用

**Comment by wey-gu** [comment]
Can you check whether GraphD got OOM?

https://docs.nebula-graph.com.cn/2.5.0/20.appendix/0.FAQ/#storage_error_e_rpc_failure

**Comment by Sophie-Xie** [comment]
This issue lacks information and has not been dealt with for too long, it will be closed. If there is updated information later, we will continue to discuss.
