### ISSUE TITLE
show default zone and default group

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#2852]
there are some concerns about default zone.

1. if user upgrade from 2.0.1
      * a storage with partitions should be in a default zone and default group?
      * how about a storage without partitions. e.g. `balance remove`

2. if user creates space without group.
      * a storage with partitions should be in a default zone and default group?
      * how about a storage without partitions

it's better to show the default zone and default group, and explain the logic how we consider a storage in default zone or not.

**Comment by Sophie-Xie** [comment]
@critical27 @darionyaphet pls discuss this requirement, is it need be resolved in v2.6.0?

**Comment by HarrisChu** [comment]
```
(root@nebula) [nba]> desc space nba;
+----+-------+------------------+----------------+---------+------------+---------------------+-------------+-----------+---------+
| ID | Name  | Partition Number | Replica Factor | Charset | Collate    | Vid Type            | Atomic Edge | Group     | Comment |
+----+-------+------------------+----------------+---------+------------+---------------------+-------------+-----------+---------+
| 1  | "nba" | 100              | 1              | "utf8"  | "utf8_bin" | "FIXED_STRING(128)" | false       | "default" |         |
+----+-------+------------------+----------------+---------+------------+---------------------+-------------+-----------+---------+
Got 1 rows (time spent 945/7564 us)

Tue, 14 Sep 2021 15:03:10 CST

(root@nebula) [nba]> show groups
+------+------+
| Name | Zone |
+------+------+
+------+------+
Empty set (time spent 1253/7305 us)

Tue, 14 Sep 2021 15:05:02 CST
```

more information

**Comment by critical27** [comment]
You mean show groups return a default group by default?

**Comment by HarrisChu** [comment]
> You mean show groups return a default group by default? But I can't figure out how to fill the `Zone` field...

Yes, that's also my question... If we figure out the zone with `default zone`, how we consider which storage belongs to the `default zone`?

We could have a discussion.

**Comment by critical27** [comment]
We discuss on a meeting, by default we return: (suppose we have n hosts before)
```
default group: [all hosts previously, each host is a zone]
zone 1: [old host 1]
...
zone n: [old host n]
```

WDYT?

**Comment by darionyaphet** [comment]
> You mean show groups return a default group by default? But I can't figure out how to fill the `Zone` field...

Show default group may be a good idea. I agree with you

**Comment by critical27** [comment]
Talked offline with @darionyaphet , we'll print default group when exec `show groups` command, each host will be a separate zone. This is quite reasonable.

But I don't know whether we need to print the host in the `default zone(which is the host itself)`

**Comment by critical27** [comment]
Talked offline, will not support this interface until 3.0. Because a host could both belongs to a default zone and a user create zone, which breaks the invariant.

**Comment by HarrisChu** [comment]
> Talked offline, will not support this interface until 3.0. Because a host could both belongs to a default zone and a user create zone, which breaks the invariant.

agree and then close issue
