### ISSUE TITLE
find path need to enhance

### ISSUE THREAD

**Issue by Reid00** [vesoft-inc/nebula#2864]
**Is your feature request related to a problem? Please describe.**

We plan to use Nebula instead of Neo4j, most of cases nebula work well. Every time we want to create new situation or replace the old with find path, it's failed. 
I do much test, the same data and topology, nebula is much slower than neo4j, is there any possible to enhance this method? 

**Describe the solution you'd like**
enhance the find path. i do some test. neo4j RT 31ms, but nebula need 1164ms, and nebula with more error rate.

![image](https://user-images.githubusercontent.com/38450639/133184743-660b3b4f-dfa7-4c6f-baf5-bdd2c2b0fbbf.png)

![image](https://user-images.githubusercontent.com/38450639/133184773-6cb8b8d0-cf32-4f11-b643-4eae6711c1e9.png)

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by CPWstatic** [comment]
Could you please provide your queries? And do you use the `Use` statement in each test case?

**Comment by Reid00** [comment]
The core stmt is `FIND SHORTEST PATH FROM a TO b OVER c,d,e,f,g UPTO 10 STEPS`
I use `Use SpaceName` before the above stmt.
I have submitted a issue here https://discuss.nebula-graph.com.cn/t/topic/5727/15

**Comment by Reid00** [comment]
close since duplicate with https://github.com/vesoft-inc/nebula/issues/3221
