### ISSUE TITLE
Takes too long time for a cluster to recover from leader crash

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#2866]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

Takes very long time for cluster to recover from leader crash.

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
https://github.com/liuyu85cn/nebula.git 730a39d786b8e835956c0a9232e1b758da7a72f3

**How To Reproduce(__must be provided__)**

1. create a cluster with 3storage + 3graph + 1meta, a space with 3partition + 3replicas
2. keep inserting edges
3. send sigstop to one leader(you can check part leader by typiing `show hosts` in nebula-console)

Despite the fact that nebula storage elect a new leader very quickly, it takes nearly 5min for the cluster to get back to normal.

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by liuyu85cn** [comment]
In one reproduce, raft take 15min do a rollback, and graph client looks stuck.

**Comment by Sophie-Xie** [comment]
> In one reproduce, raft take 15min do a rollback, and graph client looks stuck.

@Aiee Go client, pls check it.

**Comment by Sophie-Xie** [comment]
raft https://github.com/vesoft-inc/nebula/pull/2903

**Comment by critical27** [comment]
This could a be quite complicated case, frankly speaking, I have no idea what will happen when sigstop is sent to thrift server, this may involved system futex. (`raft take 15 min do a rollback`, clearly impossible to blame rollback).

We could discover later.

**Comment by kikimo** [comment]
closed by #3435
