### ISSUE TITLE
Support empty list/set/map

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula#2894]
Neo4j:
<img width="1367" alt="Screen Shot 2021-09-17 at 5 31 49 PM" src="https://user-images.githubusercontent.com/18348405/133760932-93a5e3d1-1e98-4997-899e-8038e8a2fb5b.png">

Nebula:
```
(root@nebula) [nba]> RETURN []
[ERROR (-1004)]: SyntaxError: syntax error near `]'


(root@nebula) [nba]> RETURN [1]
+-----+
| [1] |
+-----+
| [1] |
+-----+
Got 1 rows (time spent 574/922 us)


(root@nebula) [nba]> RETURN {}
[ERROR (-1004)]: SyntaxError: syntax error near `}'


(root@nebula) [nba]> RETURN {a:123}
+----------+
| {a:123}  |
+----------+
| {a: 123} |
+----------+
Got 1 rows (time spent 645/1025 us)
```

```
(root@nebula) [nba]> LOOKUP ON player WHERE player.age in []
[ERROR (-1004)]: SyntaxError: syntax error near `]'
```

**Comment by jievince** [comment]
Empty set has conflict with empty map in the parser syntax

**Comment by CPWstatic** [comment]
This is not supported at the beginning of design.

**Comment by jievince** [comment]
GQL supports `list`, `set`, `multiset`, `map`, its syntax rule is:
```
<multiset value constructor by enumeration> ::=
MULTISET <left brace> <multiset element list> <right brace>
```
For example
```
List{1, 2, 3}
Set{1, 2, 3}
Multiset{1, 2, 2}
Map{a:1, b:2}
```
And empty list, empty set, empty map is:
```
List{}
Set{}
MultiSet{}
Map{}
```
In this way, there will be no grammatical conflict.

**Comment by jievince** [comment]
Since we decided to make gql compatible in versions after 3.0, I recommend that this also could be done in versions after 3.0
