### ISSUE TITLE
without tag in index query will be crash

### ISSUE THREAD

**Issue by Codelone** [vesoft-inc/nebula#2900]
nebula 2.5
when I use query "MATCH (v)-[e]-(v2) where v.age == 31 return v" without tag , the graphd  will be crashed
maybe you can check all the query  of using index ,include edge index .
Details in Chinese Forum https://discuss.nebula-graph.com.cn/t/topic/5823

**Comment by CPWstatic** [comment]
This query is actually not supported. We'll try to reproduce this issue first.

**Comment by fangll** [comment]
same question when i use match (n1)-[r]-(n2) return n1, r,n2

graphd-stderr.log

*** Aborted at 1632882226 (Unix time, try 'date -d @1632882226') ***
*** Signal 11 (SIGSEGV) (0x0) received by PID 8087 (pthread TID 0x7fd6e95fe700) (linux TID 8117) (code: address not mapped to object), stack trace: ***
/usr/local/nebula/bin/nebula-graphd(_ZN5folly10symbolizer17getStackTraceSafeEPmm+0x31)[0x1cd2bb1]
/usr/local/nebula/bin/nebula-graphd(_ZN5folly10symbolizer21SafeStackTracePrinter15printStackTraceEb+0x1b)[0x1ccaa1b]
/usr/local/nebula/bin/nebula-graphd[0x1cc8d67]
/lib64/libpthread.so.0(+0xf62f)[0x7fd6f37ba62f]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph14LabelIndexSeek13pickEdgeIndexEPKNS0_11EdgeContextE+0x601)[0xf286d1]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph14LabelIndexSeek9matchEdgeEPNS0_11EdgeContextE+0x88)[0xf28808]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph18MatchClausePlanner10findStartsEPNS0_18MatchClauseContextERbRmRNS0_7SubPlanE+0x1bf)[0xf1a86f]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph18MatchClausePlanner9transformEPNS0_23CypherClauseContextBaseE+0x93)[0xf1db33]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph12MatchPlanner9transformEPNS0_10AstContextE+0x452)[0xf19d32]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph7Planner6toPlanEPNS0_10AstContextE+0x116)[0xf11586]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph9Validator6toPlanEv+0xee)[0xe669be]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph9Validator8validateEv+0x195)[0xe678c5]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph19SequentialValidator12validateImplEv+0x200)[0xe739e0]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph9Validator8validateEv+0x121)[0xe67851]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph9Validator8validateEPNS_8SentenceEPNS0_12QueryContextE+0x8ff)[0xe6b3cf]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph13QueryInstance19validateAndOptimizeEv+0x49b)[0xe23adb]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph13QueryInstance7executeEv+0x1e)[0xe23e3e]
/usr/local/nebula/bin/nebula-graphd(_ZN6nebula5graph11QueryEngine7executeESt10unique_ptrINS0_14RequestContextINS_17ExecutionResponseEEESt14default_deleteIS5_EE+0x135)[0xe1f925]
/usr/local/nebula/bin/nebula-graphd[0xe03e00]
/usr/local/nebula/bin/nebula-graphd[0x1c3543b]
/usr/local/nebula/bin/nebula-graphd(_ZTv0_n32_N6apache6thrift11concurrency14FunctionRunner3runEv+0x96)[0x1a3db66]
/usr/local/nebula/bin/nebula-graphd(_ZN6apache6thrift11concurrency13ThreadManager4Impl6Worker3runEv+0x152)[0x1b4e2c2]
/usr/local/nebula/bin/nebula-graphd(_ZN6apache6thrift11concurrency13PthreadThread10threadMainEPv+0xcc)[0x1b51f1c]
/lib64/libpthread.so.0(+0x7ea4)[0x7fd6f37b2ea4]
/lib64/libc.so.6(clone+0x6c)[0x7fd6f34db9fc]
(safe mode, symbolizer not available)
