### ISSUE TITLE
Use space poor performance in V2.5.X

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula#2902]
**Is your feature request related to a problem? Please describe.**
In V2.5.X，use space takes about 100-200ms,but in V2.0.1 takes about 10ms.We need to optimize the performance of this statement.

**Comment by CPWstatic** [comment]
I had talk about this with users, performance degradation is due to authentication. This issue is a little duplicated with #2891 . We will redesign this part at the next roadmap.
