### ISSUE TITLE
Bad forward compatibility to rocksdb

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula#2918]
The master RocksDB has a new enum `CompactionReason: kChangeTemperature`. If we compile the current nebula code with master rocksdb, it has a warning of not handling `kChangeTemperature`, and warnings are treated as errors.

**Comment by Shylock-Hg** [comment]
Why don't compile with the rocksdb in thrid-party?

**Comment by wenhaocs** [comment]
> Why don't compile with the rocksdb in thrid-party?

For testing purpose. Need to use new features not existing in the version which nebula is using. In addition, the previous code was not a good practice anyway.

**Comment by Shylock-Hg** [comment]
> > Why don't compile with the rocksdb in thrid-party?
> 
> For testing purpose. Need to use new features not existing in the version which nebula is using. In addition, the previous code was not a good practice anyway.

This force to handle each enumerate instead of return unknown directly.

**Comment by wenhaocs** [comment]
> > > Why don't compile with the rocksdb in thrid-party?
> > 
> > 
> > For testing purpose. Need to use new features not existing in the version which nebula is using. In addition, the previous code was not a good practice anyway.
> 
> This force to handle each enumerate instead of return unknown directly.

I am trying to follow the original logic, where it does return unknown if there is no match. In addition,  other functions in the file are doing the same, like flushReasonString, backgroundErrorReasonString, etc.
