### ISSUE TITLE
Find loop path in "find path" not right

### ISSUE THREAD

**Issue by Codelone** [vesoft-inc/nebula#2923]
nebula v2.5 version
when I use "find path" , and set the same vid, the result is not right.
`FIND ALL PATH FROM "B" TO "B" OVER * BIDIRECT UPTO 10 STEPS;`
the result is nothing
`FIND SHORTEST PATH FROM "B" TO "B" OVER * BIDIRECT UPTO 10 STEPS;`
the result is "A->B<-A" ，This is obviously not a loop path，It seems that the shortest path is found through reverse edge traversal。
It seems not support loop path，maybe you can support to  find  loop path？

**Comment by CPWstatic** [comment]
Fixed by #2773
