### ISSUE TITLE
Figure out a way to compile the source after download directly

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#293]
Open another issue to fix it in the future.

_Originally posted by @dangleptr in https://github.com/vesoft-inc/nebula/pull/276_

**Comment by sherman-the-tank** [comment]
This can be solved by removing the third-party code from the repo (Then we don't need to rely on git-lfs any more)

**Comment by sherman-the-tank** [comment]
Done after third-party being moved out of the repo
