### ISSUE TITLE
`match (v1:member)-[e]->(v2:answer) where id(v2)=='xxx' return count(e)` return empty

### ISSUE THREAD

**Issue by everywan** [vesoft-inc/nebula#2934]
`match (v1:member)-[e:vote]->(v2:answer) where id(v2)=='xxx' return count(e)` return empty,
`go from 'xxx' over vote reversely | limit 10`  has result.

**Comment by CPWstatic** [comment]
Would you please describe the issue  in details which would be helpful for us to reproduce this issue. I had test these queries while all gone well.

**Comment by everywan** [comment]
> Would you please describe the issue in details which would be helpful for us to reproduce this issue. I had test these queries while all gone well.

When i use `go from 'xxx' over edge_temp reversely | limit 10`, nebula return datas. But if i use match, nebula return empty.
Match nGql like this: `match (v1)-[e]->(v2) where id(v2)=='xxx' return e`

**Comment by CPWstatic** [comment]
I'll close this issue first, please open it if you could provide us more info.
