### ISSUE TITLE
Extract the substring that matches the regular expression from the string

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#2985]
https://discuss.nebula-graph.com.cn/t/topic/3181

**Comment by Sophie-Xie** [comment]
concat() and concat_ws() were released in v2.6.0.
extract() need to be developed.

**Comment by wuxiaobai24** [comment]
Hello, maybe I can try to fix it.

**Comment by wey-gu** [comment]
Wow, thanks @wuxiaobai24 Looking forward to your contribution.
cc @Sophie-Xie @CPWstatic

**Comment by yixinglu** [comment]
Fixed by #4098
