### ISSUE TITLE
Cannot balance data after a balance attempt failed on an offline storage host

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#2997]
**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

`2.5.0`

**How To Reproduce(__must be provided__)**

1. offline a storage host
> in this step, the host is still presented in show hosts

2. start a data balance
3. data balance failed
4. storage host was not shown in show host
> Now, host is not shown in `show hosts`

5. balance data

**Then it's observed the old failed job id was returned**

**Expected behavior**

It should start a new balance data job.

**Additional context**

https://nebulagraph.slack.com/archives/CJB79PQG2/p1632827375002600

**Comment by learn2Pro** [comment]
solved
