### ISSUE TITLE
metad service hang

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#3016]
**Please check the FAQ documentation before raising an issue**

metad hang under high load(no response for any further request), and cannot be kill by SIGTERM(raft block on grabbing lock).

we can see from the log:

```txt
4 F0930 18:16:43.111698 117635 ThriftServer.cpp:585] Could not drain active requests within allotted deadline. Deadline value: 30 secs. Abort because undefined behavior is p    ossible. Underlying reasons could be either requests that have never terminated, long running requests, or long queues that could not be fully processed.
```

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by liuyu85cn** [comment]
fixed in https://github.com/vesoft-inc/nebula/pull/3482
