### ISSUE TITLE
When the leader changes, user queries may fail several times because StorageClient uses round robin to obtain the latest leader information

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#3023]
from JIRA https://jira.nebula-graph.io/browse/NG-485

**Comment by critical27** [comment]
This case has been reduced in 2.5.0, we could check if any improvements is needed in the future.

**Comment by Sophie-Xie** [comment]
This case has been reduced in 2.5.0, we could check if any improvements is needed in the future.
