### ISSUE TITLE
Edge prop mismatch and missing edge(including in/out edges) with toss flag turn on

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#3030]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

Edge prop mismatch and missing edge(including in/out edges) under with toss flag turn on

**Your Environments (__must be provided__)**

* OS: Linux vesoft-192-168-15-11 5.4.151-1.el7.elrepo.x86_64 #1 SMP Tue Oct 5 10:21:01 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: g++ (Nebula Graph Build) 7.5.0
* CPU: Model name:            Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
* Commit id e642c056e74ed3cb6c727d80dd642f1a983f8732

**How To Reproduce(__must be provided__)**

1. a cluster 5storage + 1meta + 1graph
2. change leader every 1.5s
3. 1024 concurrent clients with customized client api sdk(in order to switch to newly elected leader quickly) inserting 4096 distinct edges.

**Expected behavior**

4096 edges, with same props on each edge's in/out edges/

**Additional context**

Provide logs and configs, or any other context to trace the problem.

what we found in the result check:

```txt
found 4090 forward edges
found 4090 backward edges
found 4090 edges in total
found 4090 semi-normal edges
prop mismatch in edge: 14->33, forward prop: 334->929, backward: 693->929
prop mismatch in edge: 14->26, forward prop: 243->922, backward: 1013->922
prop mismatch in edge: 13->11, forward prop: 436->843, backward: 31->843
prop mismatch in edge: 14->40, forward prop: 58->936, backward: 226->936
prop mismatch in edge: 10->61, forward prop: 64->701, backward: 990->701
prop mismatch in edge: 18->20, forward prop: 896->1172, backward: 210->1172
prop mismatch in edge: 14->35, forward prop: 694->931, backward: 558->931
prop mismatch in edge: 25->44, forward prop: 427->1644, backward: 400->1644
prop mismatch in edge: 30->27, forward prop: 541->1947, backward: 487->1947
prop mismatch in edge: 18->5, forward prop: 148->1157, backward: 75->1157
prop mismatch in edge: 14->30, forward prop: 357->926, backward: 570->926
prop mismatch in edge: 33->28, forward prop: 654->2140, backward: 978->2140
prop mismatch in edge: 14->37, forward prop: 88->933, backward: 993->933
vertexes: 64
found 6 missing edges:
0->0
0->1
0->2
14->27
14->38
21->40
```

**Comment by liuyu85cn** [comment]
Agree, just write something to explain this is not a big problem in 2.6 (because graph client will cover this).

also trying to fix in 2.6 if possible.
