### ISSUE TITLE
server check version with server

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3035]
https://github.com/vesoft-inc/nebula/issues/2596

1. assume v2.5.1 is in v2.6.0 white list.

and then
1. SDK in v2.5.1 could call v2.6.0 server.
2. graphd in v2.5.1 could also call v2.6.0 metad, as v2.5.1 is in v2.6.0 white list.

for point 2, it's an unreasonable, as graphd, storaged, metad versions should keep consistent.

**Comment by HarrisChu** [comment]
> This feature only check client/server compatibility not server/server.

yes, but we implement it in thrift interface, and the behavior is same in server/server side.

**Comment by CPWstatic** [comment]
As we talked about this offline, the meta-graph/storage should not always keep the same version since we have a rolling upgrade requirement. So we just close this issue first and keep the status quo.
