### ISSUE TITLE
The last host could not be deleted

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3061]
A zone added to a group cannot be deleted. I suggest that if the zone has been added to the group, the last host cannot be deleted.

![image](https://user-images.githubusercontent.com/78672629/137240874-7aacbd79-63f6-40c2-9090-b90172d7c6c6.png)

**Comment by HarrisChu** [comment]
1. if a host has partition, it cannot be dropped from zone.
2. in your case, `drop zone zone2 from group group2` first, then drop zone.

**Comment by darionyaphet** [comment]
if the hosts belonging to one zone have dropped, the zone will be dropped together
