### ISSUE TITLE
openCypher

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#3102]
1.Optional Match
2.Support syntax "(n:label1:label2), -[e:type1|type2]-"
3.Support multiple patterns "Match pattern1, pattern2 ..."
i.e. MATCH (charlie:Person { name: 'Charlie Sheen' }),(rob:Person { name: 'Rob Reiner' })
4.Support multiple match "Match pattern1 Match pattern2 ..."
i.e. MATCH (charlie:Person { name: 'Charlie Sheen' }) Match(rob:Person { name: 'Rob Reiner' })

closed: Support patterns in WHERE clause, such as "WHERE NOT (me)-[:FRIENDS_WITH]->(other)" https://github.com/vesoft-inc/nebula/issues/3083

**Comment by nianiaJR** [comment]
This new queries maybe need to be dealed in GUI products. @Sophie-Xie

**Comment by Sophie-Xie** [comment]
https://github.com/vesoft-inc/nebula/pull/3519
