### ISSUE TITLE
Implement raft prevote to prevent unnecessary leader election/change.

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#3108]
**Is your feature request related to a problem? Please describe.**

There is no prevote in current raft implementation, when network partition happends and recovers later, a rejoin server may disrupt the  cluster by starting a new election.

**Describe the solution you'd like**

On the paper [CONSENSUS: BRIDGING THEORY AND PRACTICE 9.6](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf)(fulll version of raft paper), there describe a way called pre-vote to avoid this situation.

**Describe alternatives you've considered**

**Additional context**

**Comment by critical27** [comment]
I have implemented one more than one year ago, it is almost same as current implementation. The `leaderElection` in our code is a pre-vote.

Will focus on more serious problem of raft in 3.0. Could pick my PR later if really necessary.
