### ISSUE TITLE
enhance tck test framework, using dynamic cluster

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3110]
Currently we launch nebula service via code, and then use the same nebula cluster in tck testing, and we cannot add zone cases in tck testing.

we could launch nebula service in container service, like kubernetes, and there're two types clusters:
1. fixed cluster. the configuration and data are fixed.
2. dynamic cluster.

**Comment by Sophie-Xie** [comment]
https://github.com/vesoft-inc/nebula/pull/3266
