### ISSUE TITLE
WHERE clause in the LOOKUP statement cannot use the properties function

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3117]
The WHERE clause in the GO statement can be determined using the properties function, but the WHERE clause in the LOOKUP statement cannot use the properties function.

![image](https://user-images.githubusercontent.com/78672629/137687924-53f82f13-8e95-4551-b06d-0e3edd64a328.png)

**Comment by nevermore3** [comment]
After discussing with @yee & @Sophie-Xie , we will no longer support the properties function in the where clause of lookup
