### ISSUE TITLE
[Feature] Split the heartbeat line and data transmission line

### ISSUE THREAD

**Issue by bright-starry-sky** [vesoft-inc/nebula#3137]
To optimize cluster stability, ensure independent bandwidth for heartbeat lines. 
The solution is to separate the heartbeat line from the data transmission line

**Comment by critical27** [comment]
Will focus on more serious problem of raft in 3.0

**Comment by critical27** [comment]
After talked offline with @sherman-the-tank, this feature is not so urgent.
