### ISSUE TITLE
General Design question

### ISSUE THREAD

**Issue by lonnietc** [vesoft-inc/nebula#3138]
Hi All,

Hope that everyone is going well today.

I am working on a type of P2P eCommerce store system such that various merchants can run a small single-app node (application) which will effectively join in a cluster of nodes that will store data across nodes and balance data as needed.  

The user application could be an independent application that makes calls to a cluster node, or alternatively if the node has a web UI already built in then perhaps that could be modified to just work within that local node.  I'm still trying to determine the best approach here, but maybe an independent node and independent application UI (i.e. external web service) would be a good approach.

Ultimately I need stability and horizontal scaling as more nodes come online but at the same time some nodes may drop offline and that data should be still available and accessible from within the cluster from an API call.

Currently, I am investigating Graph database solutions and am trying to determine which offers the simplest implementation while still being able to potentially handle millions of graph nodes and edges while also easily allowing me to add more API functionality (Golang payment processing libraries, User & Merchant Authentication, Searching libraries, etc.) by extending the existing graph database API so that the external application just makes simple API calls.

The systems that I have so far seem to hold the most promise for are:   

1. GraphikDB ---- https://github.com/graphikDB/graphik
2. Dgraph ---- https://github.com/dgraph-io/dgraph
3. Nebula ---- https://github.com/vesoft-inc/nebula

Each brings similar graph database functionality to the table but also each is a bit different and unique in their own way so I am trying to get some information and a feel for which might be best to start with for a P2P eCommerce based solution that can grow over time to handle massive physical nodes as well as massive graphs and user/merchant data.

Any feedback or ideas would be greatly appreciated.

Best Regards and have a great day

**Comment by wey-gu** [comment]
Dear @lonnietc ,

>
> I am also still trying to determine exactly which ones are needed for:
>
> - Control Node
> - Data Storage node.

Some refs:
- https://docs.nebula-graph.io/2.5.1/1.introduction/1.what-is-nebula-graph/
- https://docs.nebula-graph.io/2.5.1/1.introduction/3.nebula-graph-architecture/1.architecture-overview/ for a nebula graph cluster there are three services of them the graph-demon, meta-demon, strorage-demon :)

Also for deployment, you can check this out:
- https://github.com/vesoft-inc/nebula-docker-compose the docker compose/swarm repo, where the core services are in docker hub, this one should be where you quickly get started from :)
- https://github.com/vesoft-inc/nebula-operator the k8s operator for nebula graph :-)
- https://docs.nebula-graph.io/2.5.1/4.deployment-and-installation/2.compile-and-install-nebula-graph/2.install-nebula-graph-by-rpm-or-deb/ binary package deployment guide

Thanks!!

**Comment by lonnietc** [comment]
Hello Wey-gu,

Hope that all is well.

The project that I am working on needs to have:

1. Massively scalable (thousands of nodes) capabilities.
2. Role-Based ACL for database users
3. Support different platforms Linux, Windows, Mac, etc..

I am wondering if Nebula Graph will be able to have a Windows version anytime soon?

I know that I could run it in a Docker container, but I need to be able to run it natively on Windows, Linux, and Mac if at all possible.

Any thoughts on this?
Best  Regards

**Comment by wey-gu** [comment]
Dear @lonnietc :)

1. Nebula is excellent at scale, by thousands of nodes do you mean thousands of VMs as storageD/graphD workload machine?

2. RBAC is supported: https://docs.nebula-graph.io/2.6.1/7.data-security/1.authentication/3.role-list/

3. For server side, nebula is released on linux(arm in docker image/x86 in binary and docker image) now. For client side, there are windows/mac version in nebula-console.

I am using a m1 Macbook and I can run it via docker now for the nightly build, do you really need the natively-build for macOS and windows? If that is the case nebula cannot be done so now, but you can raise the issue on this requirements, for most cases, running via docker can fulfill the requirements as i understand :-P.

Thanks!

**Comment by lonnietc** [comment]
Hello @wey-gu ,

Thanks for getting back to me so quickly and I REALLY do like what I have read about Nebula since I think that it holds a huge potential for my use case.

Maybe you can shoot me an email and I can explain more of what I am trying to do away from this list since the core idea is still in development.

Please contact me at Lonnie@outstep.com so that we can chat just a bit more and we what might be possible, ok.

Thanks and have a great night

**Comment by wey-gu** [comment]
Hi @lonnietc ,
I will ping you via slack as I see you there ;-)
Thank you!

**Comment by lonnietc** [comment]
That would be perfect. I will be able to chat more tomorrow as it is getting late here, but really look forward to speaking with you on slack, my friend.  Thanks again.
