### ISSUE TITLE
Show 127.0.0.1 when I use nGQL"SHOW HOSTS GRAPH", can it always show the real ip address?

### ISSUE THREAD

**Issue by xigongdaEricyang** [vesoft-inc/nebula#3148]
As the title mentioned, when I use nGQL to show hosts, it shows the local host is 127.0.0.1. Hope to show the real ip address.

**Comment by CPWstatic** [comment]
Please paste the results that you have.

**Comment by CPWstatic** [comment]
The local ip is now set by yourself in the nebula-graphd.conf and that's the thing shows when you type the commond `SHOW HOSTS GRAPH`.
