### ISSUE TITLE
Data should be deleted, if its prop dropped then add back, even after compaction.

### ISSUE THREAD

**Issue by liuyu85cn** [vesoft-inc/nebula#3159]
version : 2.6.0 (or nightly, whatever, same behavior)

**How To Reproduce(__must be provided__)**

1. Step 1 ALTER TAG <tag_name> DROP   (prop_name)
2. Step 2 ALTER TAG <tag_name> ADD   (prop_name)

**Expected behavior**

old value should be deleted

**Additional context**

Compaction filter not handle this.

**Comment by Sophie-Xie** [comment]
Talked it offline, all schema problem will fixed in 5.x.
