### ISSUE TITLE
Explicitly specify c++ standard and reduce the use of 3rd party libraries

### ISSUE THREAD

**Issue by junaire** [vesoft-inc/nebula#3198]
Currently our code base uses a lot of c++17 core language features, like `if constexpr`and etc, however we still use some 3rd party library components like `boost::any`, `boost:variant`, `folly::optional`... and we still have some backwards compatible codes like 
```
template <typename T>
static constexpr auto is_copy_constructible_v = std::is_copy_constructible<T>::value;
```
These are weird, and I think we should:
- Explicitly specify our c++ standdard in CMakeLists.txt
- As the c++ standard library and 3rd party library all implement the same or similar features, we are supposed to use things in the STL.
- Refactor our current code, use `std::variant`, `std::any` and `std::optional`, remove helper functions like `is_copy_constructible_v` and etc.

I think these work can make our code more clean and robust. However, feel free to close this if you guys think the main tasks now are implementing new features and bugs fixing ;-)

**Comment by jiayuehua** [comment]
@junaire thanks, your pr is updated and merged.

**Comment by junaire** [comment]
> @junaire thanks, your pr is updated and merged.

i'm so grateful that you guys take my little pr so seriously and continue working on it!
