### ISSUE TITLE
Full-text index cannot be queried

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3217]
The Listener is running properly, you cannot use the LOOKUP statement to query by full-text indexes.
How do I check whether data is written to a Listener?

![image](https://user-images.githubusercontent.com/78672629/139011889-4dd7a8eb-dabf-4d15-ac9a-93d47c29e702.png)
![image](https://user-images.githubusercontent.com/78672629/139011935-5eec71a9-5a45-447c-942d-32429029719d.png)
![image](https://user-images.githubusercontent.com/78672629/139011990-382f0ed8-1828-4b38-aa20-8d4dfd607dce.png)
![image](https://user-images.githubusercontent.com/78672629/139012071-db783f37-2ae5-4b30-9ea1-6b19983106e6.png)

**Comment by cangfengzhs** [comment]
This is a bug. We don't create index in es when creating fulltext index in nebula. But if you write any data, es while create corresponding index. So if you create a fulltext index but not write any data, query by fulltext while can not find index in es.

**Comment by MuYiYong** [comment]
I recommend adding a hint to the document of 3.1.0 before modify @whitewum

**Comment by cooper-lzy** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/1886
