### ISSUE TITLE
`SHOW HOSTS` has Inconsistent status for storage and graph servers

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#3218]
`show hosts` shows that all storaged and graphd are offline, in fact, there's only one storaged process exit and all graphd process is healthy.

![image](https://user-images.githubusercontent.com/16240361/139011562-8c49e9f6-2b59-43fe-ad3f-083cec4402c4.png)

![image](https://user-images.githubusercontent.com/16240361/139012001-986948ff-4a93-4e7f-bc80-693f37351959.png)

* env info: 
  *  three metad, three graphd, three storaged

* operation process
  * import data into nebula, one storaged has no space left and this storaged process  exit.

**Comment by critical27** [comment]
Would you post some meta and storage/graph INFO log here, many misused behavior could lead the OFFLINE

**Comment by Nicole00** [comment]
> you post some meta and storage/graph INFO log here, many misused behavior could lead the OFFLINE

I don't have the log info now.  
The point is not the reason that lead storaged OFFLINE, but the info showed by `show hosts` and `show hosts graph`.
