### ISSUE TITLE
Find All PATH enhancement 

### ISSUE THREAD

**Issue by Reid00** [vesoft-inc/nebula#3221]
base this issue:  https://github.com/vesoft-inc/nebula/issues/2864
submit another discussion here about find path: https://discuss.nebula-graph.com.cn/t/topic/6235

**Comment by Reid00** [comment]
ping, is there any plan to enhance the performance?

**Comment by Reid00** [comment]
@wey-gu ping, could you take a look?

**Comment by wey-gu** [comment]
@Sophie-Xie could we prioritize this optimization on FIND PATH as @Reid00 proposed in the forum?

**Comment by Sophie-Xie** [comment]
Sorry. We have more high priority requirements in development. The optimization of find all path need to refactor operators, which is not in the plan now.

**Comment by Reid00** [comment]
we have a service high rely on FIND PATH but the performance is not expected currently, could you pls estimate when your team will work on this?

**Comment by Sophie-Xie** [comment]
> we have a service high rely on FIND PATH but the performance is not expected currently, could you pls estimate when your team will work on this?

After discussion, we add this enhancement to backlog in 2022H1.

**Comment by Reid00** [comment]
Got it, thanks.
