### ISSUE TITLE
Root user should not be reassigned other roles in space

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula#3235]
**Describe the bug (__must be provided__)**
At now root user can be assigned to other roles in a space, it's confused for user which the real access he owns in the space? 

Accoding to my test, if I'm the root user of one nebula db which includes a space `test`
```
$ GRANT ROLE User ON test TO root
```
SHOW ROLES IN test; It's seems that I'm the `user` role of the space `test`, but I can modified the schema becaused of the db root role.

 User Role in space
![image](https://user-images.githubusercontent.com/8124783/139399395-c9005d50-20b0-43ab-91ed-09d4400d2bc0.png)

`Create TAG` is allowed
![image](https://user-images.githubusercontent.com/8124783/139399681-032566da-f576-43bf-9743-7f5de74065fe.png)

**Additional context**
According to the confusing behavior of the role managing, it may cause some problems in applications about nebula.🤝

**Comment by HarrisChu** [comment]
why grant role to `root`? this scenario is not meaningful.

just like in linux system, root is the super admin for nebula cluster.

**Comment by Shylock-Hg** [comment]
Yes, I think we should disable it.

**Comment by CPWstatic** [comment]
Emmm, we also have a role named `GOD`. The total `access control` and `role` are not well designed.

**Comment by Sophie-Xie** [comment]
@slimshadylol0303  Please take a look at this question, you can combine it with role optimization.
