### ISSUE TITLE
Add model for `round` build-in function

### ISSUE THREAD

**Issue by jackwener** [vesoft-inc/nebula#3237]
**Is your feature request related to a problem? Please describe.**
#3178 add feature that that specify the floating point accuracy.

We can further improve the feature by adding mode according to the [doc of neo4j](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/#functions-round3) 

**Describe the solution you'd like**
You can refer to #3178.

What' more, you also refer to the source code of neo4j.

**Additional context**
None

**mentor**
@jackwener 

If you have any question, you can contact me.

**Comment by JayL-zxl** [comment]
hi i am a newbie for nubula. does this issue still need to be done?

**Comment by jackwener** [comment]
You can try to test this function in `neo4j` in its `neo4j sandbox`.

**Comment by harshvardhan-khachane** [comment]
Is anybody working on this issue?

**Comment by Koukyosyumei** [comment]
I am working on this issue!!
