### ISSUE TITLE
SHOW INDEX STATUS display incorrect status

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3243]
For deleted indexes, `SHOW INDEX STATUS` should show `INVALID` or not show in the results.

![image](https://user-images.githubusercontent.com/78672629/139627842-ee39a524-39ea-4692-9fe9-cda99f29a44a.png)

**Comment by CPWstatic** [comment]
I thought the status shows the job status?

**Comment by CPWstatic** [comment]
Emmm, can be improved but not a primary job.

**Comment by heroicNeZha** [comment]
`SHOW TAG INDEX STATUS` shows the status of the rebuild job, not the status of the index. So although the index is droped, this line should exist.
