### ISSUE TITLE
The default order of LOOKUP in 2.6.0 differs from that in 2.5.1

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#3244]
When running `LOOKUP ON player WHERE player.age  > 40;` in 2.6.0, the result is always:

```ngql
> LOOKUP ON player WHERE player.age  > 40;
+-------------+
| VertexID    |
+-------------+
| "player100" |
| "player125" |
| "player127" |
| "player136" |
| "player140" |
| "player141" |
| "player144" |
| "player148" |
+-------------+
```

But in 2.5.1, the result is always:

```ngql
> LOOKUP ON player WHERE player.age  > 40;
+-------------+
| VertexID    |
+-------------+
| "player100" |
+-------------+
| "player148" |
+-------------+
| "player144" |
+-------------+
| "player141" |
+-------------+
| "player140" |
+-------------+
| "player136" |
+-------------+
| "player127" |
+-------------+
| "player125" |
+-------------+
```

Both have 8 rows, but the orders are totally different. Is this the same issue as https://github.com/vesoft-inc/nebula/issues/3242?

**Comment by cangfengzhs** [comment]
I think if the "order by" clause is not given, any order is correct as long as the returned result set is correct.

**Comment by CPWstatic** [comment]
I had explain this for several times, the order of results is not guaranteed since the data are pulling from the distributed system. I'll close this issue first, and the #3242 one. Please talk to me offline if you are truly troubled by this senario.
