### ISSUE TITLE
[License Issue] Request to remove Apache 2.0 License Statement

### ISSUE THREAD

**Issue by wu-sheng** [vesoft-inc/nebula#3247]
Hi Nebula team.

I am Sheng Wu, from the Apache Software Foundation. I noticed this repo includes this license statement, 

```markdown
### Licensing
Nebula Graph is under Apache 2.0 license, so you can freely download, modify, and deploy the source code to meet your
 needs. You can also freely deploy Nebula Graph as a back-end service to support your SaaS deployment.


In order to prevent cloud providers monetizing from the project without contributing back, we added Commons Clause 1.0 to 
the project. As mentioned above, we fully commit to the open source community. We would love to hear your thoughts on 
the licensing model and are willing to make it more suitable for the community.
```

But from the license perspective, this is not correct. 
Apache 2.0 License is defined explicitly from the ASF, and provide project projects and other out-of-foundation projects to use. 

**If you modify it, you are on your own from a legal point of view, and the result is NOT the Apache License, just a new license inspired by ours.**
**This means that the terms 'Apache License', 'Apache', and any similar references to the ASF cannot appear in your modified license, other than to state that it differs from the original..**
**Also, you cannot use 'Apache' in the name of the modified license. Names like "Apache License with such-and-such clause", for example, are not acceptable, as they cause confusion.**

Refer to https://www.apache.org/foundation/license-faq.html#mod-license for more details.

___

According to all above, I am requesting the project owner to remove all **Apache 2.0** statement. 

Notice, whether your new License could be treated as an open source license, mostly is OSI responsibility or community consensus. Typically with `cloud vendor exclusion`, the license is not OSI open source license.

**Comment by jamieliu1023** [comment]
@wu-sheng Thanks for pointing this out! The team will update the License section shortly.

**Comment by wu-sheng** [comment]
Thanks, the header of source files should be updated according.

https://github.com/vesoft-inc/nebula/blob/73bc8259f6813f43c8ccfe2bb7dca2a43d7cdc16/src/codec/Common.h?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L1-L5

**Comment by jamieliu1023** [comment]
Yes of course, which is why we need some time :)
