### ISSUE TITLE
edge loss

### ISSUE THREAD

**Issue by fan0916** [vesoft-inc/nebula#3253]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

edge is expected to store in both vertex partition, but it's observed that some edges exists only on one size

**Your Environments (__must be provided__)**

* OS: Linux FAT_nebula01 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: not build from source
* CPU: Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               2499.998
BogoMIPS:              4999.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni
* Commit id: we use 2.5.1pre-compiled version

**How To Reproduce(__must be provided__)**

run the test code writen in java in attachment 

[NebulaEdgeLostTest.txt](https://github.com/vesoft-inc/nebula/files/7459253/NebulaEdgeLostTest.txt)

**Expected behavior**

test case pass

**Additional context**

Provide logs and configs, or any other context to trace the problem.

![image](https://user-images.githubusercontent.com/22172401/139815374-649612b8-7366-44dd-98f2-b4a29d1e16fc.png)
[only_single_side_edge_exist.log](https://github.com/vesoft-inc/nebula/files/7459196/only_single_side_edge_exist.log)

**Comment by critical27** [comment]
You need to check the result code when execute

**Comment by fan0916** [comment]
oh yes, i did this in method requireSuccessExecute
![image](https://user-images.githubusercontent.com/22172401/141080526-216fb63f-04bf-45ca-a212-980102ba9fb8.png)
