### ISSUE TITLE
I expanded nebula across hosts, the data before the expansion cannot be used and cannot create a snapshot

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#3265]
I expanded Nebula (added a new meta、a new storage、and a new graph) across machines and running `show spaces` showed all the graph spaces that I was created before the expansion, but when running `show hosts`, it didn't show the partition information, the data before expansion can not be used. (I can create spaces and insert data after the expansion).

![image](https://user-images.githubusercontent.com/78209557/140048944-245e4874-49ea-435b-83df-57738a312af2.png)
![image](https://user-images.githubusercontent.com/78209557/140049121-53784d3f-9e90-4132-be6d-f88c7415152e.png)
![image](https://user-images.githubusercontent.com/78209557/140048957-7716f9be-e04c-4ec9-8c0f-bee6cf2df7d5.png)

Also, I cannot create any snapshot
![image](https://user-images.githubusercontent.com/78209557/140050132-1b20be62-64ad-4266-b44d-79367a99c79e.png)

**Comment by critical27** [comment]
> I expanded Nebula (added a new meta、a new storage、and a new graph) across machines
How?

**Comment by panda-sheep** [comment]
The clusterId changed by extending the meta.
It is a new cluster

**Comment by abby-cyber** [comment]
> > I expanded Nebula (added a new meta、a new storage、and a new graph) across machines
> 
> How?

I installed a new nebula graph package on another machine, and then changed the parameter `meta_server_addrs` of all the config files (nebula_graphd/nebula_metad/nebula_storaged.conf) on both machines by adding IPs of the new machines and adding the meta port 9559, and changed the value of the parameter `local_ip` to the corresponding machine IP.
