### ISSUE TITLE
`MATCH` query on a edge without index will crash the graphd

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#3284]
**Your Environments (__required__)**

nebula version: 2.5.0

**How To Reproduce(__required__)**

```
 CREATE SPACE test_space(vid_type=FIXED_STRING(10));
 USE test_space;
 CREATE EDGE like(likeness double);
 MATCH p=(v)-[e]-(v2) WHERE e.likeness >= 90 RETURN p;
```

nebula graphd crash.

reference: https://discuss.nebula-graph.com.cn/t/topic/6394

**Comment by Shylock-Hg** [comment]
Already fix in #2996 , released in v2.6.0
