### ISSUE TITLE
"FETCH PROP ON <edge_type>" problem

### ISSUE THREAD

**Issue by zedzhu** [vesoft-inc/nebula#3294]
**Describe the bug (__required__)**
![image](https://user-images.githubusercontent.com/6426766/140909544-6b9601ee-8a8c-4100-b143-4c0790d1b861.png)

But there is no any edge after I execute nGQL "FETCH PROP ON <edge_type>" using src and dst vid returned from above:
![image](https://user-images.githubusercontent.com/6426766/140909507-0316617f-cbe9-43c1-8a62-b08e57b0bdc7.png)

**Comment by zedzhu** [comment]
Update:
The result is as expected if I use MATCH to find the edge:
![image](https://user-images.githubusercontent.com/6426766/141046486-671a43af-2daf-4dcf-be65-216d8eb4d983.png)

**Comment by CPWstatic** [comment]
The main problem is the `rank`. Try this one:
```
FETCH PROP ON  relate v1->v2@95833330
```
