### ISSUE TITLE
Exchange: Verification  is required when downloading SST files from HDFS

### ISSUE THREAD

**Issue by Jerry319609l** [vesoft-inc/nebula#3327]
Download SST files from HDFS:
1.There are no files in the folder.
2.Wrong HDFS path.

when run the nGQL: download hdfs "hdfs://xxxxx", we got "Execution succeeded",  run "ingest", also get message "Execution succeeded"
![image](https://user-images.githubusercontent.com/88643568/141943279-f9a9d34c-58dd-480c-a473-efaf6ca38db7.png)

This will mislead us，so I think we need a verification mechanism to confirm whether the download is successful.

**Comment by darionyaphet** [comment]
The user is required to confirm whether SST files exist in the directory It is not a bug
