### ISSUE TITLE
Error Importing data

### ISSUE THREAD

**Issue by arstian** [vesoft-inc/nebula#3368]
anyone know how to solve it?
![Screenshot from 2021-11-26 13-14-32](https://user-images.githubusercontent.com/93761414/143535406-135b1d5e-4933-4b8b-8c37-e514f8134326.png)

**Comment by Sophie-Xie** [comment]
Please add more information, thanks.

**Comment by arstian** [comment]
First when i log in to nebula graph studio (localhost/not in a docker) a notification appears "database not connected" , and then i try to import csv file on nebula graph studio (localhost) and a notification appears like the picture above (so I couldn't import)

**Comment by hetao92** [comment]
could you test importing data via nebula-importer. Btw you can see config parameters passed by the import api in the Chrome console

**Comment by Sophie-Xie** [comment]
Need some info, turn it off first, then turn it back on with more info.
