### ISSUE TITLE
Index delete problem

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#3375]
**Describe the bug (__required__)**

Statement `drop tag index` deletes the edge index unexpectedly, and vice versa for the deletion of the tag index.

**Your Environments (__required__)**
Version: v2.6 and previous versions

**How To Reproduce(__required__)**
```
(root@nebula) [nba]> create tag A(a int)
Execution succeeded (time spent 2126/2508 us)

(root@nebula) [nba]> create edge E(a int)
Execution succeeded (time spent 2039/2379 us)

(root@nebula) [nba]> create tag index a_index on A(a)
Execution succeeded (time spent 1959/2310 us)

(root@nebula) [nba]> create edge index e_index on E(a)
Execution succeeded (time spent 2097/2452 us)

(root@nebula) [nba]> drop tag index e_index
Execution succeeded (time spent 1572/1963 us)

(root@nebula) [nba]> drop edge index a_index
Execution succeeded (time spent 1702/2114 us)

```

**Expected behavior**

An error should be reported when trying to delete an edge index with statement `drop tag index e_index`, and vice versa.

**Additional context**
Maybe we should reconsider similar grammatical design to avoid ambiguity and unfriendliness to users.

**Comment by czpmango** [comment]
Additional context
Maybe we should reconsider similar grammatical design to avoid ambiguity and unfriendliness to users.
