### ISSUE TITLE
Tag not found

### ISSUE THREAD

**Issue by SaqlainHussainShah** [vesoft-inc/nebula#3428]
**Storage Error: Tag not found.**

In my space I have created a TAG which can be seen and I can also describe that tag  but while inserting data in it I am getting tag not found error message.

Query is correct as I can insert data into other tags successfully using same query syntax.

**Comment by Shylock-Hg** [comment]
I think you should wait a while after creating schema. In current, need to wait graph/storage get schema information from meta periodically.

**Comment by sworduo** [comment]
Maybe an enhancement can be added that metaClient  send a getTag rpc to metaServer when the schema is not found in the localCache.

**Comment by SaqlainHussainShah** [comment]
> I think you should wait a while after creating schema. In current, need to wait graph/storage get schema information from meta periodically.

Yes this seemed to be the reason.
