### ISSUE TITLE
Some statistical analysis tools for C + + source code

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula#3468]
**Introduction**
At present, the compilation and linking time of C + + code is relatively long. In order to improve efficiency, some tools are needed to analyze the dependency of header files and find root clause.

**Related work**
There is a article about practice of time-consuming.Link below：
https://mp.weixin.qq.com/s?src=11&timestamp=1639452879&ver=3495&signature=gRIGV6bQYg3QC4bQz50Le*VZ8dcynrdneuTlB9ytTcfRb889oNSjFRIqVVAN7VfpK-AWgCkv6TsW7-NqqNyPqjqSgCO4eu6R0BiPVVW4U3zSuPZpkQ3I9kXYQHn*X-*W&new=1

**Comment by Sophie-Xie** [comment]
duplicate https://github.com/vesoft-inc/nebula/issues/3667
