### ISSUE TITLE
a double value can be set to a int32/int64 property successfully

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#3473]
![image](https://user-images.githubusercontent.com/16240361/146134735-233319c0-28c3-4e19-8f31-684f99f1186d.png)

My tag has a property with data type int32, when I insert a double value, the expect result is failure, but the result is succeed.

And the query value is forced changed to int32, which is wrong.

**Comment by jievince** [comment]
- Mysql, tidb, sql server, postgresql allow implicitly convert float to int;
```
my:root@127.0.0.1:4000=> create table test.test (a int);
CREATE TABLE
my:root@127.0.0.1:4000=> insert into test.test values (18.34);
INSERT 1
my:root@127.0.0.1:4000=> select * from test.test;
 a
----
 18
(1 row)
```

**Comment by jievince** [comment]
- CockroachDB will report an error:
```
root@:26257/defaultdb> create table test(a int);
CREATE TABLE

Time: 6ms total (execution 6ms / network 0ms)

root@:26257/defaultdb> insert into test values (18.34);
ERROR: value type decimal doesn't match type int of column "a"
SQLSTATE: 42804
HINT: you will need to rewrite or cast the expression
```

**Comment by jievince** [comment]
- GQL says nothing about it.
![image](https://user-images.githubusercontent.com/38901892/147452950-dc5074e5-b3bd-40f4-a0af-7bec2bf7cfde.png)

**Comment by Nicole00** [comment]
When insert value 1.6 into nebula int32 property, the query result is 1.
![image](https://user-images.githubusercontent.com/16240361/147454577-7e643553-569f-4a92-b9ee-31975e50d32d.png)


When insert value 1.6 into mysql int32 property, the query result is 2, which is rounding.
![image](https://user-images.githubusercontent.com/16240361/147454496-3096761c-218c-4280-984e-d52dc5952619.png)

Should we keep the same behavior with other dbs ?

**Comment by jievince** [comment]
> When insert value 1.6 into nebula int32 property, the query result is 1. ![image](https://user-images.githubusercontent.com/16240361/147454577-7e643553-569f-4a92-b9ee-31975e50d32d.png)
> 
> When insert value 1.6 into mysql int32 property, the query result is 2, which is rounding. ![image](https://user-images.githubusercontent.com/16240361/147454496-3096761c-218c-4280-984e-d52dc5952619.png)
> 
> Should we keep the same behavior with other dbs ?

Good catch. They will round the float.
