### ISSUE TITLE
[UT] failed in index scan

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#3474]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

See detail in https://github.com/vesoft-inc/nebula/runs/4529528865?check_suite_focus=true

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
It did not reappear, close it first, and reopen it if necessary.
