### ISSUE TITLE
To unify the naming of keywords

### ISSUE THREAD

**Issue by dutor** [vesoft-inc/nebula#348]
Such as
  * Replace `OVERWRITE` with `IF NOT EXISTS`
  * In admin queries, use `DROP` instead of `REMOVE`, `CHANGE` instead of `SET`
  * Replace `FIND` with `LOOKUP`

**Comment by sherman-the-tank** [comment]
```register/unregister``` +1

**Comment by dutor** [comment]
`register/unregister` -1

**Comment by dutor** [comment]
> `Host` is a special structure to represent the storage instance and differ from the other.
> 
> `register/unregister` could explain for join and leave the cluster, it's semantics more suitable.
> 
> I like it :) @dangleptr Do you have any suggestions? @dutor

I don't see any specialness in *Host*, please enlighten me. For me, register/unregister have no different meanings with add/drop, neither better nor worse.

**Comment by sherman-the-tank** [comment]
Honestly I don't see big YES or NO here. I'll say let's use ADD/DROP HOST. Here are the reasons

1) They are short, so easy to type
2) Consistent with ADD/DROP USER

**Comment by dangleptr** [comment]
> > `Host` is a special structure to represent the storage instance and differ from the other.
> > `register/unregister` could explain for join and leave the cluster, it's semantics more suitable.
> > I like it :) @dangleptr Do you have any suggestions? @dutor
> 
> I don't see any specialness in _Host_, please enlighten me. For me, register/unregister have no different meanings with add/drop, neither better nor worse.

Actually,  in our system,  the "add/remove hosts " command is not really add/remove a host into our cluster.  It is just register/unregister it in whitelist.  It will be used to filter hosts which send heart beat to Meta service.

So i think the accurate command name for it should be "Register/Unregister host in whitelist" or remove the whitelist and trust our users.





> Honestly I don't see big YES or NO here. I'll say let's use ADD/DROP HOST. Here are the reasons
> 
> 1. They are short, so easy to type
> 2. Consistent with ADD/DROP USER

1. I don't think there is any difference for typing between DROP and REMOVE.  
2. For USER commands,  we use CREATE/DROP now.

**Comment by steppenwolfyuetong** [comment]
I think we can refer to the corresponding sql of the current popular database.

**Comment by sherman-the-tank** [comment]
First we need to make the concept clear. We DO NOT have a white list. What we have is called CLUSTER. The host in the cluster might not serve due to all kinds of reason.

So what we want to do here is not creating a new host, we just want to add a new host to the cluster, or remove a host from the cluster. So I think here ADD and REGISTER means the same thing, and REMOVE/DROP/UNREGISTER have the same meaning as well.

So, in order to keep the keywords simple, we can just use ADD/REMOVE, or ADD/DROP

**Comment by whitewum** [comment]
hi everyone, do you have any conclusions about the namings?
what about the `IF EXISTS` or `IF NOT EXISTS`?

**Comment by sherman-the-tank** [comment]
Done
