### ISSUE TITLE
The result of `show hosts` of the nightly installation package is empty

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3481]
The result of `show hosts` of the nightly installation package is empty, and the storage service cannot be stopped.
The package version is nebula-graph-2021.12.15-nightly.el7.x86_64.rpm.

![image](https://user-images.githubusercontent.com/78672629/146304726-4fab82aa-9a09-4d6f-945c-f972d3d4b798.png)

**Comment by darionyaphet** [comment]
first of all  you should use `add hosts` to append host into cluster

**Comment by cooper-lzy** [comment]
Thanks! After the add operation, it's ok.
