### ISSUE TITLE
Optimization suggestions for add hosts

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3484]
Since we need to register the storaged node through `add hosts`,  it is recommended to add a command to view the host_list that has been communicating with meta but has not been registered. This will facilitate user registration.

**Comment by darionyaphet** [comment]
If the host not registed into meta service, it will not be saved. So it seems could not be distinguish

**Comment by darionyaphet** [comment]
maybe we should support another command to display which hosts have be add into the machine list. It's more useful.

**Comment by Sophie-Xie** [comment]
@MuYiYong @darionyaphet talked it offline, it will not be change in v3.x.
