### ISSUE TITLE
nebula-cluster don't work while VERTEX or Edge program operating 

### ISSUE THREAD

**Issue by huangjie155** [vesoft-inc/nebula#3485]
CentOS Linux release 7.9.2009 (Core)

console :
(root@nebula) [basketballplayer]> show hosts
+---------+------+-----------+--------------+----------------------+------------------------+
| Host    | Port | Status    | Leader count | Leader distribution  | Partition distribution |
+---------+------+-----------+--------------+----------------------+------------------------+
| "m1"    | 9779 | "OFFLINE" | 0            | "No valid partition" | "No valid partition"   |
| "m2"    | 9779 | "OFFLINE" | 0            | "No valid partition" | "No valid partition"   |
| "s1"    | 9779 | "OFFLINE" | 0            | "No valid partition" | "basketballplayer:50"  |
| "s2"    | 9779 | "OFFLINE" | 0            | "No valid partition" | "No valid partition"   |
| "s3"    | 9779 | "OFFLINE" | 0            | "No valid partition" | "No valid partition"   |
| "Total" |      |           | 0            |                      | "basketballplayer:50"  |
+---------+------+-----------+--------------+----------------------+------------------------+

Actually,

[root@m1 ~]# sudo /usr/local/nebula/scripts/nebula.service status all
[INFO] nebula-metad(65fdeed): Running as 21245, Listening on 9559
[INFO] nebula-graphd(65fdeed): Running as 21302, Listening on 9669
[INFO] nebula-storaged(65fdeed): Running as 21329, Listening on 9779

[root@m2 ~]# sudo /usr/local/nebula/scripts/nebula.service status all
[INFO] nebula-metad(65fdeed): Running as 1705, Listening on 9559
[INFO] nebula-graphd(65fdeed): Running as 1764, Listening on 9669
[INFO] nebula-storaged(65fdeed): Running as 1793, Listening on 9779

[root@s1 ~]# sudo /usr/local/nebula/scripts/nebula.service status all
[INFO] nebula-metad(65fdeed): Running as 21427, Listening on 9559
[INFO] nebula-graphd(65fdeed): Running as 21484, Listening on 9669
[INFO] nebula-storaged(65fdeed): Running as 21510, Listening on 9779

[root@s2 ~]# sudo /usr/local/nebula/scripts/nebula.service status all
[INFO] nebula-metad(65fdeed): Running as 18168, Listening on 9559
[INFO] nebula-graphd(65fdeed): Running as 18228, Listening on 9669
[INFO] nebula-storaged(65fdeed): Running as 18256, Listening on 9779

[root@s3 ~]# sudo /usr/local/nebula/scripts/nebula.service status all
[INFO] nebula-metad(65fdeed): Running as 3829, Listening on 9559
[INFO] nebula-graphd(65fdeed): Running as 3886, Listening on 9669
[INFO] nebula-storaged(65fdeed): Running as 3912, Listening on 9779

whart's wrong?怎么回事呀，都2.61了还出现不稳定情况。谁敢用呀！

**Comment by darionyaphet** [comment]
您好，请问您能提供更多的日志信息吗？便于排查问题，谢谢。

**Comment by Sophie-Xie** [comment]
There is no feedback for too long, so close it first. Restart with more info.
