### ISSUE TITLE
BrokenPromiseE

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula#3502]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

refer to https://discuss.nebula-graph.com.cn/t/topic/6578

1. Execute a QUERY sentence, And the useage of memory hit the WaterMark setting
2. wait a minute
3. Execute the same sentence, report the error "BrokenPromiseE"

**Expected behavior**

**Additional context**

**Comment by jievince** [comment]
Same with https://github.com/vesoft-inc/nebula/issues/3562
