### ISSUE TITLE
function to parse json format string prop

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#3513]
context: https://discuss.nebula-graph.com.cn/t/topic/6991

**Comment by jievince** [comment]
Return a map?

**Comment by akshatakulkarni25** [comment]
Hello. I am Akshata Kulkarni. I am interested in working on this issue. Is this issue still open to work on??It would be my first issue. Could you also please guide through this issue.Thanks

**Comment by wey-gu** [comment]
Dear @akshatakulkarni25 ,

Welcome to the community, this issue is still open!

I think a function similar to [JSON_EXTRACT](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract) could be introduced here.

@jievince do you see it as reasonable/feasible?

## why

The motivation of this issue was NebulaGraph doesn't support nested datatype, in some cases, user may like to serialize JSON data in a string as properties of Tag/edgeType, thus, this function would enable data extracting in return expression.
(We should consider stopping user from using it in filter expression, as this will lead to a data full scan. @jievince ? )


## what

- It takes a string and returns a [map](https://docs.nebula-graph.io/3.2.0/3.ngql-guide/3.data-types/8.map/):

```sql
YIELD JSON_EXTRACT('{"a": 1, "b": 2, "c": {"d": 4}}') AS map_foo
+-------------------------+
| map_foo                 |
+-------------------------+
| {a: 1, b: 2, c: {d: 4}} |
+-------------------------+
```
- It takes path as args, too (@jievince do you think this is needed?)
```sql
YIELD JSON_EXTRACT('{"a": 1, "b": 2, "c": {"d": 4}}', '$.c') AS map_foo_dot_c
+-----------+
| map_foo   |
+-----------+
| {d: 4}    |
+-----------+
```

**Comment by jievince** [comment]
> Dear @akshatakulkarni25 ,
> 
> Welcome to the community, this issue is still open!
> 
> I think a function similar to [JSON_EXTRACT](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract) could be introduced here.
> 
> @jievince do you see it as reasonable/feasible?
> 
> ## why
> The motivation of this issue was NebulaGraph doesn't support nested datatype, in some cases, user may like to serialize JSON data in a string as properties of Tag/edgeType, thus, this function would enable data extracting in return expression. (We should consider stopping user from using it in filter expression, as this will lead to a data full scan. @jievince ? )
> 
> ## what
> * It takes a string and returns a [map](https://docs.nebula-graph.io/3.2.0/3.ngql-guide/3.data-types/8.map/):
> 
> ```sql
> YIELD JSON_EXTRACT('{"a": 1, "b": 2, "c": {"d": 4}}') AS map_foo
> +-------------------------+
> | map_foo                 |
> +-------------------------+
> | {a: 1, b: 2, c: {d: 4}} |
> +-------------------------+
> ```
> 
> * It takes path as args, too (@jievince do you think this is needed?, this makes the function a lot more complex to be implemented)
> 
> ```sql
> YIELD JSON_EXTRACT('{"a": 1, "b": 2, "c": {"d": 4}}', '$.c') AS map_foo_dot_c
> +-----------+
> | map_foo   |
> +-----------+
> | {d: 4}    |
> +-----------+
> ```

That's a good point. But it may be a bit troublesome to implement all the json functions in mysql. I suggest you could first implement a simple function, such as convertToMap, which takes a json string, and returns a map value it represents.

**Comment by jievince** [comment]
The implementation of the builtin functions is here: https://github.com/vesoft-inc/nebula/blob/master/src/common/function/FunctionManager.cpp
Looking forward to your contribution.

**Comment by wey-gu** [comment]
also, one PR on introducing functions [here](https://github.com/vesoft-inc/nebula/pull/4526)

**Comment by akshatakulkarni25** [comment]
Respected Sir,

Thank you for your reply. I look forward to learning from and contributing
to the repository.

Could I also reach out to you in case I have any doubts or queries
throughout the process through emails

Thank you.

Regards,
Akshata Kulkarni

**Comment by wey-gu** [comment]
Dear @akshatakulkarni25 ,
Sure, you could mail/slack me when needed :)

**Comment by wey-gu** [comment]
Hi @akshatakulkarni25 

May I know your status on this issue? It's ok if you could not make it, I am trying to prepare a PR on it, and in case yours is ready, we could co-work on yours instead.

Thanks!

**Comment by jinyingsunny** [comment]
checked on 3.3-rc
