### ISSUE TITLE
The type of duration  returns an empty value

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3514]
![image](https://user-images.githubusercontent.com/78672629/146861206-44ba99be-d551-4de7-bb32-32b688d2bd52.png)
![image](https://user-images.githubusercontent.com/78672629/146861231-b5b3b804-0ada-4444-9011-b9d403fdb7d9.png)

**Comment by Shylock-Hg** [comment]
I think it's caused by console don't duration now.
