### ISSUE TITLE
Failed to create session During data import 

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula#3516]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
![image](https://user-images.githubusercontent.com/6930445/146868274-14636895-bd31-450b-866b-b73b2d3beb4c.png)

![DINGTALK_IM_931936447](https://user-images.githubusercontent.com/6930445/146868487-cab5e347-1fa8-4005-8028-a3e9b288ce37.JPG)

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

This phenomenon will occur when the data is imported too fast and the raft‘s cache is full.

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
We limit the session numbers in https://github.com/vesoft-inc/nebula/pull/3729. And we will optimize it in 5.x version。
