### ISSUE TITLE
Unknown function `coalesce'.

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula#3522]
**Please check the FAQ documentation before raising an issue**

```
(root@nebula) [sf1]> return coalesce(1, null);
[ERROR (-1004)]: SyntaxError: Unknown function  near `coalesce'
```

**Comment by wey-gu** [comment]
I am having the same issue today, `coalesce` won't take the second argument.

```
(root@nebula) [amundsen]> """
                       -> MATCH (tbl)-[:`COLUMN`]->(`col`:`Column`)-[USES_WHERE_CLAUSE]->(whr)-[WHERE_CLAUSE_OF]->(wq:`Query`)-[:HAS_EXECUTION]->(whrexec:Execution)
                       ->         WHERE id(tbl) == "hive://gold.test_schema/test_table1"
                       ->         WITH tbl, sum(coalesce(whrexec.execution_count,0)) as where_exec_cnt
                       ->         RETURN tbl, where_exec_cnt
                       -> """
[ERROR (-1004)]: SyntaxError: Unknown function  near `coalesce'
```
(root@nebula) [amundsen]> """
                       -> MATCH (tbl)-[:`COLUMN`]->(`col`:`Column`)-[USES_WHERE_CLAUSE]->(whr)-[WHERE_CLAUSE_OF]->(wq:`Query`)-[:HAS_EXECUTION]->(whrexec:Execution)
                       ->         WHERE id(tbl) == "hive://gold.test_schema/test_table1"
                       ->         WITH tbl, sum(coalesce(whrexec.execution_count)) as where_exec_cnt
                       ->         RETURN tbl, where_exec_cnt
                       -> """
+-----+----------------+
| tbl | where_exec_cnt |
+-----+----------------+
+-----+----------------+
Empty set (time spent 27436/208757 us)
```
