### ISSUE TITLE
Add hosts command does not check if the ip/port is actually in use by nebula process

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula#3529]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

`Add hosts` command does not check if the ip/port is actually in use by nebula process.
For example if I have the Nebula service listening on these ports
![Screen Shot 2021-12-22 at 2 20 54 PM](https://user-images.githubusercontent.com/18348405/147045336-a1ea6780-89c0-408c-9b81-e4b81ddfe769.png)
and execute  `add hosts 127.0.0.1:29562` which adds the ip/port of graph service, the execution is succesful.

**Your Environments (__required__)**
Neubla master branch

**How To Reproduce(__required__)**

1. Open the console
2. run `add hosts 127.0.0.1:12334` (no process is using this port)
3. It shows `Execution succeeded`
![Screen Shot 2021-12-22 at 2 19 07 PM](https://user-images.githubusercontent.com/18348405/147045163-4d0c47a4-4cae-42b2-b568-742f3b79793c.png)

**Expected behavior**

An error should be returned.
**Additional context**

**Comment by darionyaphet** [comment]
You mean the added address is not sure whether it is the real address?

**Comment by darionyaphet** [comment]
I can't check this In fact, this is not a bug

**Comment by Shylock-Hg** [comment]
What' the result of `show hosts`?

**Comment by Aiee** [comment]
> You mean the added address is not sure whether it is the real address?

Yes. In general, I can come up with 2 situations:
1. IP/PORT is used by a non-storage process, like graphd/metad
2. The address is idle and no process is listening on the port

I'm not sure if this is a bug and I was curious if we can make the execution response more sensible.

**Comment by Aiee** [comment]
> What' the result of `show hosts`?

`show hosts` will not print the address added.

**Comment by HarrisChu** [comment]
1. we allow add a storage not running.
2. if add a wrong port, e.g. graph, and it should reject the invalid heartbeat, so `show hosts` shows nothing.
3. although it's already `add hosts`, if there's no available heartbeat, cannot create space.

**Comment by Aiee** [comment]
Update:
After executing `add hosts` with a graphd ip/port, the user is able to run `create space/tag/edge`, but an error occurs when inserting a vertex: `[ERROR (-1005)]: Storage Error: part: 12, error: E_RPC_FAILURE(-3).`

**Comment by darionyaphet** [comment]
add hosts + storage host and ip

just regist the storage node

**Comment by darionyaphet** [comment]
why add hosts with a graphd ip/port it is unnecessary

**Comment by Aiee** [comment]
> why add hosts with a graphd ip/port it is unnecessary

This is a misoperation made by users and it could cause problems that are hard to trace

**Comment by critical27** [comment]
Case closed, it would be hard to prevent misusage
