### ISSUE TITLE
we should change thrift version in master branch

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3543]
currently, the version in common.thrift is still `2.6.0`, and we update the client, e.g. nebula-go, nebula-console.
It will make user confused if he download the latest nebula-import to connect nebula v2.6.0.
https://discuss.nebula-graph.com.cn/t/topic/7006/9

we should update the version, and then when using the latest client, it would raise an incompatible error.

**Comment by HarrisChu** [comment]
as talked offline, won't change the version util release.

**Comment by wey-gu** [comment]
Could we always mark version info in master as something different from the last tag/release to remove the confusion, this applies to all repo including studio, clients, other utils.
