### ISSUE TITLE
support limit push-down in match statement

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#3551]
As title.

**Comment by sarisadi1** [comment]
I have the new attached col, I fixed it up for the same amount of audience of [00]. Let me know if you would like a copy of it.

**Comment by czpmango** [comment]
> I have the new attached col, I fixed it up for the same amount of audience of [00]. Let me know if you would like a copy of it.

I didn't get you. Could you describe it in detail. 
Do you have a pr to fix this issue? Community contributions are highly encouraged.

**Comment by jackwener** [comment]
I can take this task up.

**Comment by Shylock-Hg** [comment]
Duplicate with https://github.com/vesoft-inc/nebula-ent/issues/528
