### ISSUE TITLE
Disallow the delete/kill statement to perform pipe operations in parser

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#3561]
delete/kill sentence is not traverse sentence

https://github.com/vesoft-inc/nebula/blob/eac1e89341e36cc45a8103d00addc7933cb69a62/src/parser/parser.yy#L2845-L2860

**Comment by jievince** [comment]
`traverse_sentence` is indeed the sentence that could be piped. 
The following sentences could be piped, so they are traverse_sentence.
```
    | delete_vertex_sentence { $$ = $1; }
    | delete_tag_sentence { $$ = $1; }
    | delete_edge_sentence { $$ = $1; }
    | show_queries_sentence { $$ = $1; }
    | kill_query_sentence { $$ = $1; }
    | describe_user_sentence { $$ = $1; }
```
