### ISSUE TITLE
New Error nebula 2.6.1

### ISSUE THREAD

**Issue by aminmaghsodi** [vesoft-inc/nebula#3562]
I have upgraded nebula server components from 2.5.0 to 2.6.1 (both server and client versions are upgraded), but I get this new error from server sometimes: `N5folly13BrokenPromiseE: Broken promise for type name nebula::Status`

What is this new error and why is it thrown?

Thanks

**Comment by aminmaghsodi** [comment]
I see this error is at the same time (or just after) I see `Error message Used memory hits the high watermark(0.900000) of total system memory.`, but this `N5folly13BrokenPromiseE` isn't going to be resolved by retrying.

**Comment by wey-gu** [comment]
Thanks @aminmaghsodi for raising it! @jievince is working on it!
