### ISSUE TITLE
To support DESCRIBE on a graph space

### ISSUE THREAD

**Issue by dutor** [vesoft-inc/nebula#357]
In order to retrieve infos of spaces.

**Comment by sherman-the-tank** [comment]
I would suggest to use "SHOW CREATE SPACE xxx" to make it consistent with "SHOW CREATE TAG xxx"

**Comment by darionyaphet** [comment]
I think they are not the same.

`SHOW CREATE` will be similar with `MySQL` and display how to create it ？

**Comment by steppenwolfyuetong** [comment]
> `SHOW CREATE` will be similar with `MySQL` and display how to create it ？

not only create， but also contains the status after alter

**Comment by sherman-the-tank** [comment]
Done
