### ISSUE TITLE
storage did not release memory

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#3601]
**Describe the bug (__required__)**

All of the `Expression` are allocated in `ObjectPool`. And, when creating a tag/edge who contain a prop with a `default value`, the `default value` is stored as an `Expressoin` in Schema.

In graphd, the `ObjectPool` is created in every query, and released after query. But, in `MetaClient`, the pool is created when load schema, and released when reload schema if there is any update about schema. So, if schema is never never updated, the pool will never be released.

When writing any data who has a `default value` and ngql not fill it, storaged will compute `default value`. But, the `Expression` about `default value`  will be clone and allocated in `MetaClient`'s pool. This causes the pool to take up more and more memory, and it will never be released unless the schema is changed.

**Comment by Shylock-Hg** [comment]
`But, the Expression about default value will be clone and allocated in MetaClient's pool. `
Why need clone it?

**Comment by cangfengzhs** [comment]
> 

 I'm not sure if `Expression` is stateful. If it is not, clone is really not needed.

**Comment by Shylock-Hg** [comment]
> > 
> 
> I'm not sure if `Expression` is stateful. If it is not, clone is really not needed.

It's stateful. Expression will store the evaluate result to get performance improvement.

**Comment by cangfengzhs** [comment]
In addition, if the schema is updated and reloaded during the use of the default value, there will be a concurrency safety problem. The memory pointed to by `Expression*` in `default value` may have been released

**Comment by cangfengzhs** [comment]
> It's stateful. Expression will store the evaluate result to get performance improvement.
So, clone is needed. Multi thread may be evaluate expression at same time
