### ISSUE TITLE
duration has wrong PMDT result

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#3602]
**Describe the bug (__required__)**

![image](https://user-images.githubusercontent.com/16240361/147717124-99a543ab-e5ce-4782-abf6-fa2702dea6c5.png)

The result of duration in PMDT format  is not correct. 
1. In the result, days are already  represented in `DT`, but they are recomputed again in `S`. 
2. Microseconds are lost in the result.

**Expected behavior**
expect PMDT result is  `P14M500DT10.00002S`  or `P1Y2M500DT10.00002S`

**Additional context**
if insert the same `duration({years:1,months:2,days:500, seconds:10, microseconds:20})` into neo4j, the query result is `P1Y2M500DT10.00002S`

**Comment by Shylock-Hg** [comment]
We could show the microseconds, but the days will add to seconds because we don't have separate days field which different from neo4j.

**Comment by Nicole00** [comment]
> We could show the microseconds, but the days will add to seconds because we don't have separate days field which different from neo4j.

If we don't separate days field, then the correct result should be `P14M0DT43200010.00002S`.

**Comment by Shylock-Hg** [comment]
> > We could show the microseconds, but the days will add to seconds because we don't have separate days field which different from neo4j.
> 
> If we don't separate days field, then the correct result should be `P14M0DT43200010.00002S`. You cannot use `days` value twice.

Yes, will fix later.

**Comment by jievince** [comment]
Fixed by https://github.com/vesoft-inc/nebula/pull/3608
