### ISSUE TITLE
balance leader command keep running forever

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#3636]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

`balance leader` command keep running forever;

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id ce15bca9edf2863f5a2d7eddc78759a0c98c5582

**How To Reproduce(__required__)**

1. create a cluster with 3storage
2. create a space with 512 parts + 3 replicas
3. add two new storeage and run `balance leader`

we observed that the `balance leader` command run for more than one days and its still running as showed below:

```txt
(root@nebula) [ttos_3p3r]> show jobs;
+--------+------------------+-----------+----------------------------+----------------------------+
| Job Id | Command          | Status    | Start Time                 | Stop Time                  |
+--------+------------------+-----------+----------------------------+----------------------------+
| 5      | "ZONE_BALANCE"   | "QUEUE"   |                            |                            |
| 4      | "DATA_BALANCE"   | "QUEUE"   |                            |                            |
| 3      | "LEADER_BALANCE" | "RUNNING" | 2022-01-04T08:16:03.000000 |                            |
| 2      | "LEADER_BALANCE" | "FAILED"  | 2022-01-04T08:05:19.000000 | 2022-01-04T08:05:24.000000 |
+--------+------------------+-----------+----------------------------+----------------------------+
Got 4 rows (time spent 1677/2182 us)

Wed, 05 Jan 2022 15:01:53 CST
```

**Expected behavior**

**Additional context**

**Comment by critical27** [comment]
Probably same problem with #3742

**Comment by Sophie-Xie** [comment]
fix in https://github.com/vesoft-inc/nebula/pull/3668
