### ISSUE TITLE
a boolean value can be set to a int property successfully

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3640]
Expected return error:
[ERROR (-1005)]: Storage Error: The data type does not meet the requirements. Use the correct type of data.

![image](https://user-images.githubusercontent.com/78672629/148180852-770fdf17-f37b-491c-9e39-1c0cae6f5fa0.png)

**Comment by sworduo** [comment]
It seems that it's a feature. Boolean type value can be transformed as  INT8/16/32/64. See RowWriterV2.cpp. If it's a bug, it's confusing why they use switch instead of if-else.

**Comment by critical27** [comment]
It is transformed indeed, think of a up cast.
