### ISSUE TITLE
After inserting a vertex without a tag, use`show stats`to count the numbers of vertices or edges that cannot be counted

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#3649]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

```bash
(root@nebula) [basketballplayer]> Insert vertex VALUES "1":(),"2":()
Execution succeeded (time spent 1111/1503 us)

Thu, 06 Jan 2022 03:46:54 UTC

(root@nebula) [basketballplayer]>  show stats
+---------+------------+-------+
| Type    | Name       | Count |
+---------+------------+-------+
| "Tag"   | "person"   | 0     |
| "Tag"   | "player"   | 51    |
| "Tag"   | "t2"       | 1     |
| "Tag"   | "team"     | 30    |
| "Edge"  | "follow"   | 81    |
| "Edge"  | "like"     | 0     |
| "Edge"  | "serve"    | 152   |
| "Space" | "vertices" | 82    |
| "Space" | "edges"    | 233   |
+---------+------------+-------+
Got 9 rows (time spent 797/1346 us)

Thu, 06 Jan 2022 03:46:58 UTC

```
**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Insert vertex without Tag.
2. `show stats` to count the numbers of vertices or edges.

**Expected behavior**

**Additional context**

**Comment by critical27** [comment]
What's wrong with the result?
51 + 1 + 30 = 82
81 + 152 = 233

**Comment by foesa-yang** [comment]
I insert a vertex without a tag, why can't I find it with `show stats`?

**Comment by panda-sheep** [comment]
This has something to do with recent changes

When supporting the insertion of vertex without tag, the stats job needs to be compatible

**Comment by czpmango** [comment]
Detailed test!

**Comment by critical27** [comment]
`show stats` only scan tag/edge (`"Space" | "vertices"` is tag sum), we could handle the actual `vertex` in stats job later
