### ISSUE TITLE
The following two statements should output the same content

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#3652]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

```bash
(root@nebula) [nba]> match (v:player{name:"Tony Parker"}) with v as a match p=(o:player{name:"Tim Duncan"})-[]->(a) return o.player.name
+---------------+
| o.player.name |
+---------------+
+---------------+
Empty set (time spent 2825/3306 us)

Thu, 06 Jan 2022 16:43:39 CST

(root@nebula) [nba]> match p=(o:player{name:"Tim Duncan"})-[]->(v:player{name:"Tony Parker"}) return o.player.name
+---------------+
| o.player.name |
+---------------+
| "Tim Duncan"  |
| "Tim Duncan"  |
+---------------+
```
![L1VzZXJzL2ZvZXNhL0xpYnJhcnkvQ2FjaGVzL2NvbS5hbGliYWJhLkRpbmdUYWxrTWFjLzViOTI5YmYzYzA3MmE4MzcwZTZjMWMxNzE0ZjFmNjBlLmpwZw==](https://user-images.githubusercontent.com/35463247/148355876-71f1e949-d55d-46fc-aabe-4539e421aca5.jpg)

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by CPWstatic** [comment]
I test this case, the result is diffrent from yours:
```
(root@nebula) [nba]> profile match (v:player{name:"Tony Parker"}) with v as a match p=(o:player{name:"Tim Duncan"})-[]->(a) return o.player.name
+---------------+
| o.player.name |
+---------------+
| "Tim Duncan"  |
| "Tim Duncan"  |
+---------------+
Got 2 rows (time spent 862799/863599 us)
```

**Comment by foesa-yang** [comment]
![image](https://user-images.githubusercontent.com/35463247/148770076-74c417f8-7f8d-4821-be32-506e4dfd344b.png)
