### ISSUE TITLE
Release on master

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#3661]
**Is your feature request related to a problem? Please describe.**

Now some clients will test on nightly version, but there is a period between nebula bugfix/feature PR to next nightly build. So client test will blocked too.

**Describe the solution you'd like**

Add CI to release when master pushed, and upload packages to OSS, images to Docker.hub

**Describe alternatives you've considered**

**Additional context**

**Comment by Shylock-Hg** [comment]
E.G. this fix https://github.com/vesoft-inc/nebula/pull/3660 block the client testing.

**Comment by Sophie-Xie** [comment]
There are too many changes into master everyday. Add CI to release when master pushed need more runner. 
Maybe you can try rerun nightly workflow of nebula when client test is blocked.
