### ISSUE TITLE
Storage go crazy while balancing data

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#3664]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Storage go crazy while balancing data. We've describe this problem in #3657 , and we've found the situation: 3000+% cpu usage of storage. To reproduce this problem, besides the steps we described in #3657, we also turn on discruption of network partition. 

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by liwenhui-soul** [comment]
fixed in https://github.com/vesoft-inc/nebula/pull/3668
