### ISSUE TITLE
Cannot create schema

### ISSUE THREAD

**Issue by zh3389** [vesoft-inc/nebula#3682]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
Cannot create schema, Even in GUI and console.

**Your Environments (__required__)**

* OS: Linux zh 4.15.0-30deepin-generic SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux
* Compiler: `g++ --version` or `clang++ --version`
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* CPU: `lscpu`
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Stepping:              10
CPU MHz:               4562.244
CPU max MHz:           4700.0000
CPU min MHz:           800.0000
BogoMIPS:              7392.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

* Commit id   zh3389

**How To Reproduce(__required__)**
1. download 2.6.0 docker-compose: https://github.com/vesoft-inc/nebula-docker-compose/tree/v2.6.0
2. run it!
3. Download the corresponding GUI version 3.1.0: https://docs.nebula-graph.com.cn/2.6.0/nebula-studio/deploy-connect/st-ug-deploy/
4. run it!
5. Select GUI or console to create a schema: Console needs to run and log in : `docker run --rm -ti --network nebula-docker-compose_nebula-net \
  --entrypoint=/bin/sh vesoft/nebula-console:v2-nightly`
6. not creat scheam

**Expected behavior**
`CREATE SPACE basketballplayer (partition_num = 100, replica_factor = 1, vid_type = FIXED_STRING(32)) COMMENT = "statistics of basketball palyers"`
Successfully created test sample

**Additional context**

**Comment by zh3389** [comment]
I used the old version 2.5.0 once and succeeded

**Comment by Sophie-Xie** [comment]
What was the error message when you failed to create schema.

**Comment by zh3389** [comment]
> 

error message: Invalid data length

Now I find that I seem to have cloned the wrong docker-compose.    The mirror image is vesoft/nepalmetad:nightly, and the correct clone should be vesoft/nepalmetad:2.6.0

I think can turn off this issues

**Comment by Sophie-Xie** [comment]
> error message: Invalid data length
> 
> Now I find that I seem to have cloned the wrong docker-compose. The mirror image is vesoft/nepalmetad:nightly, and the correct clone should be vesoft/nepalmetad:2.6.0
> 
> I think can turn off this issues

OK
