### ISSUE TITLE
`age` is not a tag, I expect the returned result could be an error.

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#3687]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

`age` is not a tag, I expect the returned result could be an error.

```bash
(root@nebula) [basketballplayer]> match (v) return v.age.name limit 3
+------------+
| v.age.name |
+------------+
| __NULL__   |
| __NULL__   |
| __NULL__   |
+------------+
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by czpmango** [comment]
IMO, it's just reasonable. I test similar statement in neo4j v4.2.4:
```
neo4j@neo4j> match (v) return v.nonExist limit 3;
+------------+
| v.nonExist |
+------------+
| NULL       |
| NULL       |
| NULL       |
+------------+
```
Closed but free to ask.
