### ISSUE TITLE
Redesign scan vertices

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#3688]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Before #3328 we scan vertices by scan tags, but now it's mistake. So we need to redesign scan vertices.

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by cangfengzhs** [comment]
According to the current implementation, tags will be specified in Scan vertex, and only vertexes with these tags will be accessed. If it is traversed according to vertexKey, all points will be traversed. I'm not quite sure if this logic is appropriate.

**Comment by Shylock-Hg** [comment]
> According to the current implementation, tags will be specified in Scan vertex, and only vertexes with these tags will be accessed. If it is traversed according to vertexKey, all points will be traversed. I'm not quite sure if this logic is appropriate.

Yes, current implementation will ignore vertex without any tags.

**Comment by cangfengzhs** [comment]
> Yes, current implementation will ignore vertex without any tags.
So do we have to change it to traverse all the vertices regardless of whether there is a corresponding tag? I'm not sure how much impact this change will have

**Comment by Shylock-Hg** [comment]
> 

Yes, ScanVertices should return one row for each vertex regardless of whether there are any tags on it.

**Comment by xtcyclist** [comment]
I think we shouldn't do any redesign for 3.4. Sounds too big. @Shylock-Hg what do you think?

**Comment by Shylock-Hg** [comment]
> I think we shouldn't do any redesign for 3.4. Sounds too big. @Shylock-Hg what do you think?

It's bug of vertex key, bug now it's removed. I close it. @cangfengzhs
