### ISSUE TITLE
A job cannot be restarted after it is stopped

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3701]
Use the `BALANCE IN ZONE REMOVE'` command to clear the host. After the job is stopped, it cannot be restarted.  The `Running` state is always displayed and the job cannot be stopped again.
![image](https://user-images.githubusercontent.com/78672629/149059641-5095fb0c-158d-455f-9eda-0712bd336e79.png)
![image](https://user-images.githubusercontent.com/78672629/149059962-0c7c0eea-479f-4dce-bc26-e01a16e31e92.png)

**Comment by liwenhui-soul** [comment]
fix in https://github.com/vesoft-inc/nebula/pull/3668
