### ISSUE TITLE
Optimizer rules compatibility

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#3704]
**Describe the bug (__required__)**
This pr (https://github.com/vesoft-inc/nebula/pull/3255) should fix all related optimizer rules, because the expression related processing logic has been changed(VarPropertyExpression/InputPropertyExpression -> LabelTagPropertyExpression). 

**Your Environments (__required__)**
Versions after this pr(https://github.com/vesoft-inc/nebula/pull/3255)

**How To Reproduce(__required__)**
Just check all expression related OptRule code logic.

**Additional context**
1. Some logic of this pr maybe also need been retested
```
(root@nebula) [nba]> with {a:1, b:{c:3, d:{e:5}}} as x return x.b.d.e
[ERROR (-1009)]: SemanticError: The type of `x' should be tag
```

2. Expression design should be reconsidered
    - reconsider data dependency design
    - avoid redundant design of expression types, eg. VarProperty/InputProperty/LabelTagProperty/LabelProperty, etc
    
3. Define the promises to optimizer to avoid errors like this pr
    - what types of plannode/expression should be taken into account (eg. `LabelTagProperty` or `VarProperty` in this pr)
    - data dependency and execution dependency conflict
    - column names should be set before optimization phase (this currently may cause some potential optimization rule bugs)
    - in what scenario dose reuse of executor dataset should be concerned(eg. Filter outputVar)
    - execution plans should be guaranteed to be stateless (eg. `validator` or `planner` setting some context states on which execution plans depend should be disabled)
    - expression conversion to `Value`, which is really different from expression rewriting, needs to be disabled or concerned. (eg. ColumnHints design)
    - clause level and planner's cutting of statements needed to be redesigned(eg. WHERE is not a clause in its own right — rather, it’s part of MATCH, OPTIONAL MATCH, START and WITH), this may improve some code logic related to `DataCollect`
    - ...

**Comment by Shylock-Hg** [comment]
To avoid these happen again, we could add more test case which compare the optimized plan.

**Comment by czpmango** [comment]
> To avoid these happen again, we could add more test cases which compare the optimized plan.

Each optimization rule has a corresponding test case to verify the optimized execution plan. 
This problem is not due to the lack of test cases, but rather the new features break some of the optimizer's guarantees.
