### ISSUE TITLE
submit job to balance a balanced space, job status is FAILED

### ISSUE THREAD

**Issue by kqzh** [vesoft-inc/nebula#3720]
![image](https://user-images.githubusercontent.com/35095889/149458878-aad1e69b-c82c-4040-b408-6de4cc0b3d94.png)

I think if user submit a balance job and have no failed task, job's status should be succeed

**Comment by liwenhui-soul** [comment]
fined in https://github.com/vesoft-inc/nebula/pull/3775

**Comment by liwenhui-soul** [comment]
https://github.com/vesoft-inc/nebula/pull/4017
