### ISSUE TITLE
stability: TOSS

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#3758]

**Comment by xiajingchun** [comment]
@Sophie-Xie there's only one open bug #3030 to be fixed and verifed in v3.1. I suggest to close this one and track that bug in v3.1.

**Comment by Sophie-Xie** [comment]
> @Sophie-Xie there's only one open bug #3030 to be fixed and verifed in v3.1. I suggest to close this one and track that bug in v3.1.

OK, thanks.
