### ISSUE TITLE
Do not automatically truncate the index field when the length exceeds 255

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#3768]
**Describe the background of the requirement**
- now we automatically truncate the index field when the length exceeds 255, users don’t know if the data is too long.

**Describe the detail of the requirement**
- Let users choose whether to truncate or report an error

**Describe the scenarios of the requirement**

the configuration needs to be supported(truncate or error), and the default is truncated.

**Comment by Aiee** [comment]
The problem does not exist anymore.
