### ISSUE TITLE
reduce reinventing the wheel. ie, reduce use of code in src/common, util someday delete this folder totally.

### ISSUE THREAD

**Issue by jiayuehua** [vesoft-inc/nebula#3774]
**Introduction**

src/common contains many code that implemented not very well, that is some bad wheel be reinvented. Should reduce use of code in src/common, use standard lib or thirdparty lib instead.
**Contents**

For example, apply those changes :
concurrent -> boost thread
charset -> boost text or [ztd.text ](https://ztdtext.readthedocs.io/en/latest/)
thread -> boost thread
base/status statusor -> abseil::status abseil::statusor 
network -> boost asio
cpp/helpers.h -> boost noncopyable
time -> chrono 
encryption -> openssl
fs -> std filesystem
...
etc

**Related work**

**Comment by Shylock-Hg** [comment]
The utilities of time are aimed to separate some environment like TZ from system. The standard library don't expose it, so I write new one.

**Comment by jiayuehua** [comment]
https://github.com/HowardHinnant/date merged into c++20, in c++17 can use this lib instead.

**Comment by jiayuehua** [comment]
https://github.com/vesoft-inc/nebula/pull/3867

**Comment by jiayuehua** [comment]
https://github.com/vesoft-inc/nebula/pull/3848
