### ISSUE TITLE
Storaged memory continues to grow until the leader change or OOM

### ISSUE THREAD

**Issue by a516072575** [vesoft-inc/nebula#3779]
**Describe the bug (__required__)**
All storageds memory continues to grow until someone OOM or leader changes by running balance leader command when leader is unblanced in cluster. 
I  used jemalloc to dump malloc, I found many "nebula::ConstantExpression::clone" before OOM. and it disappeared or became less after OOM or Leader changed.

I found that "nebula::ConstantExpression::clone"  was called  by fetching default value of edge property. 
I do not know if it leaked and why it became less after Leader changed. 
Can you give me some ideas on how to check. thanks

**Your Environments (__required__)**

* OS:  Centos 7.5
* Compiler: `g++ --version` :  4.8.5
* CPU: `lscpu`
* Version: 2.6.1
* Commit id : de03025 with pr [add session tool to manage and analysis sessions ](https://github.com/vesoft-inc/nebula/pull/3696) and [Limit number of sessions that are created by same client ip and same user for each graphd](https://github.com/vesoft-inc/nebula/pull/3729)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

![image](https://user-images.githubusercontent.com/4393025/150496547-f6c08957-e855-464d-af1b-ff0266c9adb0.png)

08:35  jeprof top 
![image](https://user-images.githubusercontent.com/4393025/150496848-9d5a433e-6f52-4282-8086-c681b758de7e.png)

08:36  jeprof top
![image](https://user-images.githubusercontent.com/4393025/150496955-0653c17e-72ae-4d5a-91c0-286af2118cbf.png)

08:37  jeprof top
![image](https://user-images.githubusercontent.com/4393025/150497012-2f63d568-2d22-40c6-ac32-3d85338c651b.png)

08:35 call graph
[210835.pdf](https://github.com/vesoft-inc/nebula/files/7911767/210835.pdf)

![image](https://user-images.githubusercontent.com/4393025/150506543-6986355e-ac33-4b73-b524-e411c91528dc.png)

**Comment by cangfengzhs** [comment]
Yes, this is a serious bug.And you create a tag/edge with a default value, right? We have found and fixed it. Look at https://github.com/vesoft-inc/nebula/issues/3601.

**Comment by a516072575** [comment]
> Yes, this is a serious bug.And you create a tag/edge with a default value, right? We have found and fixed it. Look at #3601.

It is great !  I have deleted edge default value,  memory usage is very flat. Thanks!

Another problem that https://github.com/vesoft-inc/nebula/pull/3729 was  create at  last week, there is anyone to review it so far. I think that  it is import to multi-tenant cluster. It can prevent one user's mistake from affecting all other users. Could you review it ?  Thanks !

**Comment by Sophie-Xie** [comment]
> > Yes, this is a serious bug.And you create a tag/edge with a default value, right? We have found and fixed it. Look at #3601.
> 
> It is great ! I have deleted edge default value, memory usage is very flat. Thanks!
> 
> Another problem that #3729 was create at last week, there is anyone to review it so far. I think that it is import to multi-tenant cluster. It can prevent one user's mistake from affecting all other users. Could you review it ? Thanks !

Thanks. I just assigned two reviewers.

**Comment by wey-gu** [comment]
Thanks @a516072575 , great option introduced.
