### ISSUE TITLE
match cannot query the vertex after drop tag, but fetch can

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#3802]
**Describe the bug (__required__)**
![image](https://user-images.githubusercontent.com/16240361/150914796-1f560559-f7a1-458d-91c4-7e4cb9374314.png)
match and fetch have inconsistent result.

![image](https://user-images.githubusercontent.com/16240361/150915104-531bf359-d382-44ad-804d-141f543ad197.png)
And the vertex without tag cannot be counted.

**How To Reproduce(__required__)**
1. `create tag player(name string)`
2. `insert vertex player(name) values "100":("tom")`
3. `drop tag player`

then query the vertex, according to pr https://github.com/vesoft-inc/nebula/pull/3328, we should get the vertex without any tag. But match query returns nothing, fetch query returns the vertex id.

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula/issues/3649

**Comment by critical27** [comment]
Duplicate with #3649

**Comment by HarrisChu** [comment]
1. for `show stats`, duplicate with #3649
2. for `match`, maybe should discuss offline.

**Comment by HarrisChu** [comment]
cc @nevermore3

**Comment by Shylock-Hg** [comment]
Duplicate with #3688
