### ISSUE TITLE
feature: client upward compatible

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#3803]
**Is your feature request related to a problem? Please describe.**
Client connection fails due to version misalignment. ref: [https://discuss.nebula-graph.com.cn/t/topic/6943/](https://discuss.nebula-graph.com.cn/t/topic/6943/)

**Describe the solution you'd like**
In the case of kernel upgrade, try to ensure that the client does not need additional upgrades.

**Comment by Sophie-Xie** [comment]
Nebula Graph Database v3.0.0 don‘t support the most ecosystem tools of v2.x, please upgrade the ecosystem tools.

https://github.com/vesoft-inc/nebula/pull/3741
