### ISSUE TITLE
Are there any benchmark or architecture introduction?

### ISSUE THREAD

**Issue by choleraehyq** [vesoft-inc/nebula#382]
Thanks.

**Comment by pgplus1628** [comment]
SAME!
Great work! 
Looking forward to seeing some brief introductions and examples of "SQL like query language"!

**Comment by Amber1990Zhang** [comment]
Sorry, we don't have benchmark yet, it will come with the beta version.

**Comment by dutor** [comment]
Thank you for asking.

So far Nebula Graph is still in its infant stage. We have been focusing on the core functionalities, thus lacking many testing results and documents on the project.

But please be patient, all of these will be coming soon.

**Comment by sherman-the-tank** [comment]
This is our slack invitation. You are welcome to join and share the link. We could continue our discussion there

https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LWY1YjgzMzBjNjI4YmI0ZGQxY2U5NjdjNzJkZjVhZDNlNjI5NWFhOTRlYjkxNjRhMTQzZjY0ZTI2NDJjY2ZlNDI

**Comment by choleraehyq** [comment]
👌

**Comment by ImVexed** [comment]
Any updates on this?
