### ISSUE TITLE
poor performance caused by using gigabit ethernet

### ISSUE THREAD

**Issue by FangJinhe** [vesoft-inc/nebula#3843]
clusters are configured as follows:
192.168.15.8 - metad, graphd, storaged
192.168.15.9 - metad, graphd, storaged
192.168.15.10 - metad, graphd, storaged

192.168.15.8/192.168.15.9/192.168.15.10 are bound to 10 gigabit ethernet（万兆网卡）, server 192.168.15.9 has a gigabit ethernet（千兆网卡）which has address 192.168.15.201. When the clusters start, nebula services of server 192.168.15.9 use 192.168.15.201, which not configured in conf files(conf files use 192.168.15.9). This causes very poor performance.

**Comment by CPWstatic** [comment]
Which service bound to the wrong ip?
