### ISSUE TITLE
Support import/export data based on HBase 2.x version

### ISSUE THREAD

**Issue by SteNicholas** [vesoft-inc/nebula#385]
Can nebula graph support import/export data based on HBase 2.x version

**Comment by dutor** [comment]
As for now, there are ways to dump data into our database.

For a small quantity of data or realtime insertion, you could use our nGQL via C++/Golang/Java API or a console binary. 

For large amount of data, we provide a package with which you could invoke from inside a MR job to generate a collection of data files, which can be injected into the database directly.

**Comment by sherman-the-tank** [comment]
This is our slack invitation. You are welcome to join and share the link. We could continue our discussion there

https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LWY1YjgzMzBjNjI4YmI0ZGQxY2U5NjdjNzJkZjVhZDNlNjI5NWFhOTRlYjkxNjRhMTQzZjY0ZTI2NDJjY2ZlNDI
