### ISSUE TITLE
cannot backup nebula after upgrader from v2

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3854]
1. db_upgrader would create a metaclient, and send heart beat to meta.
2. option doesn't set host and role.
3. and it would make backup failed.

![image](https://user-images.githubusercontent.com/1726587/152773195-ed195ec4-2d7e-4e56-b95b-735c19aa503b.png)

![image](https://user-images.githubusercontent.com/1726587/152773354-4b5abf6a-5be2-4247-83b1-00d502d329e7.png)
![image](https://user-images.githubusercontent.com/1726587/152773450-3c2d7b2c-7474-49af-ad97-cf14c58de5d6.png)

**Comment by critical27** [comment]
Thx! The `Host("", 0)` has confused me for a long time
