### ISSUE TITLE
kill query should have permission requirements

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3864]
You can run the `KILL QUERY` command with any permission.

![image](https://user-images.githubusercontent.com/78672629/152940424-7fe4e8a3-43be-48c8-a6db-e6f9a45ab960.png)

![image](https://user-images.githubusercontent.com/78672629/152940396-e0fb20e1-3373-477c-baf7-c3a53c8a657c.png)

**Comment by Shylock-Hg** [comment]
GOD could kill all quries, others could kill own queries.
