### ISSUE TITLE
StatsManager is not thread safe

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#3869]
**Describe the bug (__required__)**
```
sm.stats_.emplace(
      counterName,
      std::make_pair(std::make_unique<std::mutex>(),
                     std::make_unique<StatsType>(
                         60,
                         std::initializer_list<StatsType::Duration>(
                             {seconds(5), seconds(60), seconds(600), seconds(3600)}))));
```
`stats_` is a `std::unordered_map`. And some time will read/write without lock

**Comment by Shylock-Hg** [comment]
It's protected by nameMapLock_.

**Comment by cangfengzhs** [comment]
> 

No nameMapLock_ protect another map. You can find some other places where stat_ is used without lock.

**Comment by Shylock-Hg** [comment]
> > 
> 
> No, nameMapLock_ protect another map. You can find some other places where stat_ is used without lock.

It also protects stats_ too, add/delete counter will lock nameMapLock_ firstly.

**Comment by cangfengzhs** [comment]
> 

But reading stat_ doesn't with Lock. If one thread read stat_'s element while another thread insert/erase some element, this may be lead to structure modify of unordered_map. Reading thread will access some released memory.

**Comment by Shylock-Hg** [comment]
> > 
> 
> But reading stat_ doesn't with Lock. If one thread read stat_'s element while another thread insert/erase some element, this may be lead to structure modify of unordered_map. Reading thread will access some released memory.

Yes, read need protection too.

**Comment by cangfengzhs** [comment]
> Yes, read need protection too.
And I think this part requires some complex design rather than simply using read-write locks. The performance of the lock is very poor, and the metric cannot affect the performance of the system.

**Comment by Shylock-Hg** [comment]
> > Yes, read need protection too.
> 
> And I think this part requires some complex design rather than simply using read-write locks. The performance of the lock is very poor, and the metric cannot affect the performance of the system.

Agree, in my mind, static metric is enough.
