### ISSUE TITLE
more readable error when client is incompatible

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3872]
as we add "3.0.0" in `client_white_list`, it's better to use set string in error message

![image](https://user-images.githubusercontent.com/1726587/153169298-e5192dbf-093a-4d24-8093-c7944114a8a7.png)

![image](https://user-images.githubusercontent.com/1726587/153169412-23eeb869-ffe4-4bc9-9b12-07e129b71f27.png)

**Comment by CPWstatic** [comment]
Emm, my bad.
