### ISSUE TITLE
nebula 2.6 ttl int type does not work

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#3923]
**Describe the bug**

The int type field sets the ttl attribute, and it can still be queried after expiration.

Expired data match cannot be queried, but fetch can still be queried.

How to query the setting of ttl, the desc tag cannot be viewed.

**Your Environments (__required__)**

nebula version: 2.6.1

ref: https://discuss.nebula-graph.com.cn/t/topic/7268

**Comment by panda-sheep** [comment]
Use the latest code and test as follows, no problem.
The case is as follows:

```
case one： without ttl，data exists
create tag player1(age int);
show create tag player1;
create tag index player1_index on player1(age);

insert vertex player1(age) values "11":(1); 
insert vertex player1(age) values "22":(2); 
insert vertex player1(age) values "33":(3); 
insert vertex player1(age) values "44":(4); 

rebuild tag index player1_index
FETCH PROP ON player1 "11" yield player1.age;
MATCH (v:player1) return v;
MATCH (v:player1) where v.player1.age == 1 return v;
```


case two: use ttl, data not exists

```
create tag player(age int) ttl_duration= 100, ttl_col = "age";
create tag index player_index on player(age);
show create tag player;

insert vertex player(age) values "11":(1); 
insert vertex player(age) values "22":(2); 
insert vertex player(age) values "33":(3); 
insert vertex player(age) values "44":(4); 

rebuild tag index player_index
FETCH PROP ON player "11" yield player.age;
```
![image](https://user-images.githubusercontent.com/59197347/160322724-4904bc8c-e6d6-4d97-ab70-415925759cee.png)

**Comment by minxinqing** [comment]
> Use the latest code and test as follows, no problem. The case is as follows:
> 
> case one： without ttl，data exists
> 
> ```
> create tag player1(age int);
> show create tag player1;
> create tag index player1_index on player1(age);
> 
> insert vertex player1(age) values "11":(1); 
> insert vertex player1(age) values "22":(2); 
> insert vertex player1(age) values "33":(3); 
> insert vertex player1(age) values "44":(4); 
> 
> rebuild tag index player1_index
> FETCH PROP ON player1 "11" yield player1.age;
> MATCH (v:player1) return v;
> MATCH (v:player1) where v.player1.age == 1 return v;
> ```
> 
> case two: use ttl, data not exists
> 
> ```
> create tag player(age int) ttl_duration= 100, ttl_col = "age";
> create tag index player_index on player(age);
> show create tag player;
> 
> insert vertex player(age) values "11":(1); 
> insert vertex player(age) values "22":(2); 
> insert vertex player(age) values "33":(3); 
> insert vertex player(age) values "44":(4); 
> 
> rebuild tag index player_index
> FETCH PROP ON player "11" yield player.age;
> ```
> 
> ![image](https://user-images.githubusercontent.com/59197347/160322724-4904bc8c-e6d6-4d97-ab70-415925759cee.png)


问题依然存在呀。看截图时间，我把过期时间设置为了10秒，插入数据后，10秒后再查依然能查到，跟你的截图中区别在于，属性值是当前时间。
我对ttl的理解有误？
![image](https://user-images.githubusercontent.com/3809601/171130480-a0ecc314-5536-4c66-a00c-92d35250067c.png)
