### ISSUE TITLE
nebula 2.6.2 fulltext index function does not work well

### ISSUE THREAD

**Issue by zhaochuanyun** [vesoft-inc/nebula#3927]
Describe the bug

When the full-text indexed field value contains Japanese json strings, the full-text index does not work properly, and the failed full-text index request will be retried infinitely to ES.

Your Environments (required)

nebula version: 2.6.2

ref: https://discuss.nebula-graph.com.cn/t/topic/7644

**Comment by rusonding** [comment]
+1

**Comment by cangfengzhs** [comment]
The problem is caused by incomplete truncation of the last utf8 character. To fix this, we need to recognize the encoding of the text and truncate at full characters.
