### ISSUE TITLE
password change after upgrade

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#3928]
**Describe the bug**

After upgrade to v3.0, the password of the root account is automatically changed to the default `nebula`.

**Your Environments**

* Nebula version: v2.0.1 updated to v3.0.0

ref: https://discuss.nebula-graph.com.cn/t/topic/7619/17

**Comment by darionyaphet** [comment]
Update the password in nebula 2.0.1

```
(root@nebula) [(none)]> CHANGE PASSWORD root FROM 'nebula' TO 'nebula12'
Execution succeeded (time spent 3583/4260 us)

Wed, 02 Mar 2022 15:35:50 CST
```

after that, upgrade to nebula 3.0 with old password but it failed.

```
> ./nebula-console -addr=192.168.8.5  --port=1356 --u=root --p=nebula
2022/03/02 15:39:13 Fail to create a new session from connection pool, fail to authenticate, error: Invalid password
panic: Fail to create a new session from connection pool, fail to authenticate, error: Invalid password
```

using the modified password is fine

```
./nebula-console -addr=192.168.8.5  --port=1356 --u=root --p=nebula12

Welcome to Nebula Graph!
```

I guess the `enable_authorize` may be closed.
