### ISSUE TITLE
Rebuild index privilege in the built-in role privileges document

### ISSUE THREAD

**Issue by ArvinLCoder** [vesoft-inc/nebula#3943]
**Introduction**
Not found REBUILD {TAG|EDGE} INDEX in the built-in role privileges document, but found BUILD {TAG|EDGE} INDEX, wonder if it's a confusion.
And the document said only GOD Role can execute BUILD INDEX nGql, but tested that GOD/ADMIN/DBA/USER Role all can execute REBUILD INDEX.
Version 3.0.0.

**Comment by czpmango** [comment]
Fixed in [https://github.com/vesoft-inc/nebula-docs-cn/pull/1516](https://github.com/vesoft-inc/nebula-docs-cn/pull/1516)
