### ISSUE TITLE
Adding a comment when creating an index causes an error  in v3.0.0

### ISSUE THREAD

**Issue by hetao92** [vesoft-inc/nebula#3945]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/18328704/155665199-559debaa-ae3f-4299-8d1f-3b3a3b599caa.png">

**Comment by Shylock-Hg** [comment]
`COMMENT '123'`

**Comment by wey-gu** [comment]
doc updating PR: https://github.com/vesoft-inc/nebula-docs-cn/pull/1507
