### ISSUE TITLE
The use of the symbol = in CREATE syntax

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3949]
1. The comment inside attributes do not use the symbol =, and comments outside attributes use the symbol =.
2. The comment outside attributes in the `create tag` and `create index` is inconsistent.
![image](https://user-images.githubusercontent.com/78672629/155909207-750c0469-08a2-41ed-9c1a-3e3abecda183.png)

**Comment by CPWstatic** [comment]
The `comment` seems quite different inside/outside the attributes parentheses. I think they don't have to use the same syntax. Besides, we are referring to the syntax of SQL. https://dev.mysql.com/doc/refman/8.0/en/create-table.html
