### ISSUE TITLE
It should show normal version info in nightly pacakge,eg: 3.0.0-nightly-aeds5d2

### ISSUE THREAD

**Issue by xigongdaEricyang** [vesoft-inc/nebula#3956]
**Is your feature request related to a problem? Please describe.**

We find when use nightly nebula, the version shows empty string or commit id, we want to add version info.
For example: 3.0.0-nightly-aeds5d2 , the syntax is "[semver version]-[nightly]-[commitid]"
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CPWstatic** [comment]
Would it be helpful if the version name is `nightly-aeds5d2`?

**Comment by Sophie-Xie** [comment]
revert this issue by #4043
