### ISSUE TITLE
result convert to float automatically

### ISSUE THREAD

**Issue by wjcnoob** [vesoft-inc/nebula#3963]
**Introduction**

return 24/48
output: 0

**Contents**

It would be great if the result could be automatically converted to float instead of adding toFloat() every time

**Related work**

**Comment by Shylock-Hg** [comment]
I don't think it's reasonable, not all users want float instead of integer in any scenes.

**Comment by wjcnoob** [comment]
> > But an indicator calculated like that is just wrong.
> 
> `/` in int stands for the mod(取模) and in float, it stands for division(除法).
> 
> You could check this in SQL:
> 
> ```sql
> SELECT 1/2,1.0/2
> ```
> 
> And the result will be: <img alt="Screen Shot 2022-03-02 at 6 32 43 PM" width="948" src="https://user-images.githubusercontent.com/1651790/156344927-3f85c09a-c278-4da0-b133-b2692f5ab591.png">
> 
> You could play with it from here: https://sqliteonline.com/

Well, I'm using hive, and hive returns 0.5. 
OK , it doesn't really matter.

**Comment by wey-gu** [comment]
Aha, thanks @wjcnoob for letting me know it's actually quite normal to treat `/` as division and another expression for the mod, which(like it was done in HIVE), I think is better than the current implicit approach in nGQL/SQL, but this behavior seems to be not possible to change due to it's correct(not the best way though) and will be a breaking change.

Could you please add `toFloat()` to one of the int values only?(sorry for this)

```cypher
(root@nebula) [basketballplayer]> RETURN toFloat(24)/48
+------------------+
| (toFloat(24)/48) |
+------------------+
| 0.5              |
+------------------+
Got 1 rows (time spent 905/23873 us)

Thu, 03 Mar 2022 09:42:09 CST
```

Thanks again!!!

**Comment by wjcnoob** [comment]
> Aha, thanks @wjcnoob for letting me know it's actually quite normal to treat `/` as division and another expression for the mod, which(like it was done in HIVE), I think is better than the current implicit approach in nGQL/SQL, but this behavior seems to be not possible to change due to it's correct(not the best way though) and will be a breaking change.
> 
> Could you please add `toFloat()` to one of the int values only(not as painful as `toFloat()` for all of them)? (sorry for this)
> 
> ```
> (root@nebula) [basketballplayer]> RETURN toFloat(24)/48
> +------------------+
> | (toFloat(24)/48) |
> +------------------+
> | 0.5              |
> +------------------+
> Got 1 rows (time spent 905/23873 us)
> 
> Thu, 03 Mar 2022 09:42:09 CST
> ```
> 
> Thanks again!!!

Of course, it's understandable
