### ISSUE TITLE
cannot inform user balance leader task is failed

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3979]
before we move `balance leader` to job manager, it is synchronous.
if balance failed, user gets the error message, and could run `balance leader` again.

but from v3.0, user should check the job status by themselves.

```
E20220304 01:57:14.036036  5068 MetaJobExecutor.cpp:31] partiton failed to transfer leader
E20220304 01:57:14.036088  5068 JobManager.cpp:186] Job dispatch failed
I20220304 01:57:14.036096  5068 JobManager.cpp:206] jobFinished, jobId=2, result=FAILED
I20220304 01:57:14.036144  5068 JobDescription.cpp:57] p = sf10
I20220304 01:57:14.045600  5068 JobManager.cpp:194] [task] cleanJob 2
```

balance leader failed.
![image](https://user-images.githubusercontent.com/1726587/156685613-e3373bac-ef5c-4129-abce-a45bf52a160f.png)

![image](https://user-images.githubusercontent.com/1726587/156685661-234d0b8f-a941-49d9-9a72-837c0e0b777a.png)

**Comment by critical27** [comment]
Will be fixed later, `show job id` will print the failed reason
