### ISSUE TITLE
Optimize the sleep time in UTs

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#398]
As for these tests, I think there are two ways to make them faster. First, we could have shared the same MockServer instead of launch one per test. Second, seconds is appropriate for a polling interval, but too long for unit testing, while I cannot come up with a better way. But you still could impove it by `usleep(FLAGS_load_data_interval_secs * 1000000 + 100000/*100ms*/)` to save 0.9s per sleep.

Of course, we could leave these work to the next PR.

_Originally posted by @dutor in https://github.com/vesoft-inc/nebula/pull/383_

**Comment by dangleptr** [comment]
duration_test ....................   Passed   11.04 sec
stats_manager_test ...............   Passed   63.02 sec
meta_client_test .................   Passed   16.11 sec
file_based_wal_test ..............   Passed    8.30 sec
log_append_test ..................   Passed   16.29 sec
log_cas_test .....................   Passed   43.20 sec

**Comment by sherman-the-tank** [comment]
Yeah, let's tackle this 👍
