### ISSUE TITLE
The error claused by remove max hop

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#3995]
Both `minHop` and `maxHop ` are optional now. If you don't fill in both, an error will be reported.
![image](https://user-images.githubusercontent.com/78672629/157575501-12038169-55f9-4c26-bb3b-33b9a7cdeec4.png)

**Comment by CPWstatic** [comment]
Thanks for it. But this is not truly a big problem for we had alternative syntax. Besides we are not declared to support this syntax.
