### ISSUE TITLE
`match p=(:foo)-->() return p` returns empty instead of rejecting error on not being able to pushdown

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#3996]
Could we pushdown limit in this pattern now? If not, it should be rejected, right?

In my own test on v3.0.0, it's accepted and resulting in BAD_TYPE.

```cypher
(root@nebula) [amundsen]> match p=(:`User`)-->() return p limit 3
+----------+
| p        |
+----------+
| BAD_TYPE |
| BAD_TYPE |
| BAD_TYPE |
+----------+
Got 3 rows (time spent 7657/54521 us)

Thu, 10 Mar 2022 11:08:12 CST

(root@nebula) [amundsen]> match p=(n:`User`)-->() return p limit 3
[ERROR (-1005)]: Scan vertices or edges need to specify a limit number, or limit number can not push down.

Thu, 10 Mar 2022 11:08:28 CST

(root@nebula) [amundsen]> show hosts graph
+-------------+------+----------+---------+--------------+---------+
| Host        | Port | Status   | Role    | Git Info Sha | Version |
+-------------+------+----------+---------+--------------+---------+
| "127.0.0.1" | 9669 | "ONLINE" | "GRAPH" | "02b2091"    | "3.0.0" |
+-------------+------+----------+---------+--------------+---------+
Got 1 rows (time spent 1647/48999 us)

```
It's reported from below thread as accepted & with empty result:

ref: https://discuss.nebula-graph.com.cn/t/topic/7842/10

**Comment by wey-gu** [comment]
labeled as bug for now, please kindly remove it if it's not the case ;)
Thanks!

**Comment by wey-gu** [comment]
I am working on this.

**Comment by CPWstatic** [comment]
> I am working on this.

Looking forward to your contribution.

**Comment by wey-gu** [comment]
It turned out:

a. `p=(:foo)-->() return p` resulted in `Limit->AppendVertices->Project->ScanEdges` ==>  `Limit->AppendVertices->Project->ScanEdges(Limit)` 

b. `p=(n:foo)-->() return p`  resulted in `Limit->AppendVertices->Project->Traverse->ScanVertices` => cannot be pushed down

I think:

- a. should be corrected as `cannot be pushed down`, right? on which phase should I fix please, then? I guess the existing plan is good(to start from scanEdges rather than scanVertices), so should I fix it in `ScanEdgesExecutor::scanEdges` to check condition on qctx to return Error or?

- we can leave b. as is right?

@CPWstatic @Shylock-Hg 

Thanks!

**Comment by wey-gu** [comment]
#4053
