### ISSUE TITLE
balance data failed with error   "Transfer leader failed, status Unknown code -46"

### ISSUE THREAD

**Issue by zhaojunHouse** [vesoft-inc/nebula#4004]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

when I add a  new storage and "balance data ",  the tasks  are  all failed  with  nebula-metad.ERROR "Transfer leader failed, status Unknown code -46".  what should I do ? ths a lot, guys .   

 

![image](https://user-images.githubusercontent.com/23691202/157658331-a03a0796-5699-4c97-8fed-62512da77c20.png)

<img width="386" alt="image" src="https://user-images.githubusercontent.com/23691202/157657335-cbb3834d-fa69-4165-a4b4-dfac8cb4b0bc.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/23691202/157657637-2602c90a-a1ba-4978-8442-ae51c01c3d46.png">**Your Environments (__required__)**

* OS: `centos x86_64 GNU/Linux`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `x86_64  64-bit`
* Commit id (e.g. `nebula-metad version Git: 761f22b, Build Time: Mar 23 2021 13:52:46`)

**How To Reproduce(__required__)**

1. Step 1   nebula cluster  (1 metad 1 graphd 1 storaged )
<img width="748" alt="image" src="https://user-images.githubusercontent.com/23691202/157657951-b713e246-afcd-47db-ac22-308229bd6287.png">

2. Step 2  add storaged  
3. Step 3  balance data . 

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
Sorry, there are some bugs of `balance data` in 2.0, and we won't fix it. If you need it, you can consider to try enterprise edition 3.1, and you will get more support for `balance data`. Thanks.
