### ISSUE TITLE
worker 1 (pid: 150) died, killed by signal 9 :( trying respawn

### ISSUE THREAD

**Issue by hjing100** [vesoft-inc/nebula#4008]
nebula：2.6.0
使用uwsgi+Django+docker

问题：当下查库都没有问题，过了几个小时再查，就报错，下一个问题查库就会自动重新连接nebula，给出正确答案

报错：
Thu Mar 10 20:44:36 2022 - *** HARAKIRI ON WORKER 1 (pid: 150, try: 1) ***
Thu Mar 10 20:44:36 2022 - HARAKIRI !!! worker 1 status !!!
Thu Mar 10 20:44:36 2022 - HARAKIRI [core 2] 172.17.0.1 - POST /kbqa since 1646916215
Thu Mar 10 20:44:36 2022 - HARAKIRI !!! end of worker 1 status !!!
DAMN ! worker 1 (pid: 150) died, killed by signal 9 :( trying respawn ...

**Comment by hjing100** [comment]
一次连接会话持续 30 分钟。如果超过 30 分钟没有操作，会话即断开，用户需要重新登录数据库。
请问这个需要在哪里设置，改善这种现象

**Comment by Aiee** [comment]
As you stated in the description, the signal was sent to HARAKIRI, it seems you need to check the timeout with `uwsgi`, and the Nebula service seems to not be involved with the information you provided.

And just a note to you, you could change `session_idle_timeout_secs` in the conf file to modify the session timeout of the Nebula service.

**Comment by wey-gu** [comment]
ref: https://discuss.nebula-graph.com.cn/t/topic/7864
