### ISSUE TITLE
Support alter schema in storage layer.

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#404]
Currently, we have supported alter one column's type in meta. 
But we have't supported it yet in storage.

There are some questions must be answered before going on.

1.  How to do StatsQuery on multi version data?  
For example, we want to count sum on one column.  But after the column's type changed,  maybe we have many different types for related data,  how to deal with it.

2.  How to deal with the response in query engine if one column in vertex data  have different types.  Now we don't deal with it. 

3. How to check if the filter is valid.  Now we use the latest version of the schema.

**Comment by sherman-the-tank** [comment]
I think based on the latest schema version is a valid assumption.  So if the old version cannot be properly converted to the latest version during the calculation, we should just ignore that row
