### ISSUE TITLE
MATCH where condition doesn't work

### ISSUE THREAD

**Issue by mizy** [vesoft-inc/nebula#4042]
**Describe the bug (__required__)**
```
MATCH (v1:player)-[e0:`serve`{start_year:2011}]->()
RETURN e0 LIMIT 100
```
<img width="654" alt="image" src="https://user-images.githubusercontent.com/7129229/158731670-2bdc815a-554e-46cb-85f2-a89ed00f8f79.png">

```
MATCH (v1:player)-[e0:`serve`{start_year}]->()
WHERE  ( e0.serve.start_year == 2011) 
RETURN e0 LIMIT 100 
```
has no result

**Your Environments (__required__)**
[docker-compose](https://github.com/vesoft-inc/nebula-docker-compose/tree/v3.0.1)

**How To Reproduce(__required__)**
https://github.com/vesoft-inc/nebula-docs/blob/master/docs-2.0/basketballplayer-2.X.ngql

indexes
<img width="825" alt="截屏2022-03-17 上午11 36 02" src="https://user-images.githubusercontent.com/7129229/158731913-7a604a6b-b07c-458d-9cef-21f52b42c4bb.png">

**Expected behavior**

**Additional context**

```
profile MATCH (v1:player)-[e0:`serve`]->()
WHERE  ( e0.serve.start_year == 2011) 
RETURN e0 LIMIT 100
```
<img width="779" alt="image" src="https://user-images.githubusercontent.com/7129229/158731552-89d32215-797b-4d01-adab-314f1a97f5e9.png">

**Comment by Shylock-Hg** [comment]
Hello mizy.
I think it's a mistake of usage.
You should try:
```
MATCH (v1:player)-[e0:`serve`]->() WHERE  ( e0.start_year == 2011) RETURN e0 LIMIT 100
```
Edge property should follow format like `edge.prop`, so `e0.serve.start_year` will get `NULL` value in you case, so after filter, there are no results.
