### ISSUE TITLE
The 2022.03.16 nightly package has wrong git sha and does not support recently merged features

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#4047]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

The package is nebula-graph-2022.03.16-nightly.ubuntu2004.amd64.tar.gz, which is created on 03.16, but it does not include recently merged PRs such as CLEAR SPACE. 

![image](https://user-images.githubusercontent.com/69501902/158773041-ed5911bd-7d8f-4172-938e-ce4f5744d251.png)

**Your Environments (__required__)**

* OS: ubuntu 20.04

**Comment by randomJoe211** [comment]
@Sophie-Xie Please take a look.

**Comment by zhaohaifei** [comment]
Centos7 has the same problem.

**Comment by Sophie-Xie** [comment]
git info:
March 16, March 13, March 10:  8272768 (it's git info on March 4th)
March 3: d3dbc84（it's git info on Feb 23）
Feb 9, Feb 10, Feb 14, Feb 15, Feb 23 : 602475f（I don’t know what day git info is）
before Feb 9, git info is right.

**Comment by Sophie-Xie** [comment]
Action of nightly was wrong, fixed it.
