### ISSUE TITLE
Match Search, The order of results is inconsistent with the order of Return

### ISSUE THREAD

**Issue by jianan0982** [vesoft-inc/nebula#4049]
**Describe the bug (required)**
Nebula-Graph Version: 2.5

> **Rebuild**

- **Command**
      MATCH p=(v:owl_Class{name:"畜肉类"})<-[e1]-(v2:owl_NamedIndividual)-[e2:relation{name:"有标签"}]->(

     v3:owl_NamedIndividual{name:"高蛋白"}) RETURN v,e1,v2,e2,v3,p limit 20 
- **Correct Result**
     
![IMG20220317-203214752](https://user-images.githubusercontent.com/95118127/158809207-e4c01ab5-87f7-4578-b089-53c5a18cb89a.jpeg)

- **Command**
      MATCH p=(v:owl_Class{name:"畜肉类"})<-[e1]-(v2:owl_NamedIndividual)-[e2:relation{name:"有标签"}]->(

     v3:owl_NamedIndividual{name:"高蛋白"}) RETURN e2,v3,p,v,e1,v2 limit 20 
- **ERROR Result**
![IMG20220317-20305593](https://user-images.githubusercontent.com/95118127/158809622-526a913a-9856-4854-ba63-a41af9ce3926.jpeg)

**Comment by Sophie-Xie** [comment]
We cannot reproduce on nebula 2.5. Can you provide more version info about studio and nebula?


![image](https://user-images.githubusercontent.com/84560950/158927378-8ed4b547-ebcd-478d-9f37-80a2c2654aec.png)

**Comment by jianan0982** [comment]
**Nebula version: 2.5**
![IMG20220318-112238110](https://user-images.githubusercontent.com/95118127/158931687-cb748823-a367-44ad-8533-09739b558d4d.jpeg)

**Nebula Graph Studio:3.0**
![IMG20220318-112321598](https://user-images.githubusercontent.com/95118127/158931792-4d870d52-f640-4957-b45c-9e45dbd83b2a.jpeg)

**Comment by jianan0982** [comment]
**必须加上LIMIT才能复现当前Bug**
MATCH p=(v:owl_Class{name:"畜肉类"})<-[e1]-(v2:owl_NamedIndividual)-[e2:relation{name:"有标签"}]->(v3:owl_NamedIndividual{name:"高蛋白"}) RETURN e2,v3,p,v,e1,v2 **LIMIT 20**
和
MATCH p=(v:owl_Class{name:"畜肉类"})<-[e1]-(v2:owl_NamedIndividual)-[e2:relation{name:"有标签"}]->(v3:owl_NamedIndividual{name:"高蛋白"}) RETURN ,v,e1,v2,e2,v3,p **LIMIT 20**

**Comment by Sophie-Xie** [comment]
> MATCH p=(v:owl_Class{name:"畜肉类"})<-[e1]-(v2:owl_NamedIndividual)-[e2:relation{name:"有标签"}]->(v3:owl_NamedIndividual{name:"高蛋白"}) RETURN e2,v3,p,v,e1,v2 **LIMIT 20**

Thanks. Is is OK if executing nGQL directly on nebula console without Studio?

**Comment by jianan0982** [comment]
在nebula-console运行也是一样的问题
![1647580431430](https://user-images.githubusercontent.com/95118127/158941720-6df38da8-b92d-4205-9281-b089f0e9d426.jpg)
![1647580475645](https://user-images.githubusercontent.com/95118127/158941751-e31fa6fd-74a0-45e9-8678-7b077674c8ef.jpg)

**Comment by jievince** [comment]
Hi @jianan0982 , it might be a bug caused by a bad optimization rule. nebula-graph v2.6.0 has fixed this bug. You could try to upgrade to v2.6.0.
BTW, the version of nebula you are using is `nebula-graph-2021.10.09-nightly` which is not v2.5.0.
