### ISSUE TITLE
import geographic area data by nebula-importer, some area data import failed

### ISSUE THREAD

**Issue by ogmap** [vesoft-inc/nebula#4054]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

系统: 3.10.0-1160.el7.x86_64:
软件版本：nebula-graph-3.0.0.el7.x86_64.rpm

**How To Reproduce(__required__)**

问题描述：
使用Nebula-Import工具，导入csv格式数据，csv中包含geography(polygon)类型字段，共900多万条记录，导入失败3万多条，错误信息提示如下：
![image](https://user-images.githubusercontent.com/102003412/159196904-a50727d5-4f4e-453e-95ce-5aafa30cc936.png)

建图语句如下：
      DROP SPACE IF EXISTS test1;
      CREATE SPACE IF NOT EXISTS test1(PARTITION_NUM = 15, REPLICA_FACTOR = 3, vid_type = fixed_string(36));
      USE test1;
      CREATE TAG IF NOT EXISTS Land(`标识码` string,`要素代码` string,`图斑面积` double,`线状地物面积` double,`零星地物面积` double,`扣除地类面积` double,`图斑地类面积` double,`geomerty` geography(polygon));

详细配置：
yaml格式无法上传，直接改为了txt格式
[text.txt](https://github.com/vesoft-inc/nebula/files/8312748/text.txt)

另外：我将地理类型改为线类型，并修改csv中地理数据，填入区外圈线，导入全部成功，即使用线格式数据导入，不会报错

使用NebulaGraphStudio：
使用Nebula-Graph-Studio工具，单独插入一条报错数据，也一样报错，错误信息和Nebula-Import提示一致
![image](https://user-images.githubusercontent.com/102003412/159197103-0d0f9c63-523d-49b5-b21b-4c491739586e.png)

插入语句：
[插入语句.txt](https://github.com/vesoft-inc/nebula/files/8312743/default.txt)

**Additional context**

**Comment by jievince** [comment]
你上传的原始数据不完整, 我这边测不了. 
插入geo数据的时候会先校验它是否是合法的形状, 你可以通过st_isValid(geog)函数测下它是否合法,
graphd的日志里应该也有报错: Failed to parse an valid Geography instance from the wkt...

**Comment by ogmap** [comment]
> The original data you uploaded is incomplete and I can't test it here. When inserting geo data, nebula will check if it is a legal shape and report an error when it is illegal. You can test whether it is legal by using the st_isValid (geog) function. There should also be an error: `Failed to parse an valid Geography instance from the wkt. in graphd's log`.

graphd's log：
ST_GeogFromText error: Failed to parse an valid Geography instance from the wkt

使用st_isValid 进行测试，错误提示如下：
-1004:SyntaxError: Unterminated string: near `POLYGON((112.47733333399182 27.964394714059676,112.47735032302988 27.96438657675'

所有的wkt字符串，均使用PolygonWrapper生成，此数据在gis软件中也是真实可用的数据，此wkt格式的区为什么会解析失败，能否帮我确定原因？
测试使用的区数据，直接用“插入语句”文本中的区即可
wkt生成代码如下：
String getPolyognString(GeoPolygon geoPolygon){
        Polygon polygon = new Polygon();

        List<List<com.vesoft.nebula.Coordinate>> coordListList = new ArrayList<List<com.vesoft.nebula.Coordinate>>();
        int num = (int)geoPolygon.getCircleNum();

        for (int i=0; i<num; i++){
            Dots dots = geoPolygon.getDots(i);
            List<com.vesoft.nebula.Coordinate> coordList = new ArrayList<com.vesoft.nebula.Coordinate>();

            Dot dot1 = dots.get(0);
            Dot dot2 = dots.get(dots.size()-1);

            //首尾点可能有极小的误差，为保证首尾点完全闭合，进行点相等判断
            boolean bNeedAppend = false;
            if(dot1.getX() != dot2.getX() || dot1.getY() != dot2.getY()){
                bNeedAppend = true;
            }

            for (int j=0; j<dots.size(); j++){
                Dot d = dots.get(j);
                com.vesoft.nebula.Coordinate coordinate = new  com.vesoft.nebula.Coordinate(d.getX(),d.getY());
                coordList.add(coordinate);
            }

            if(bNeedAppend){
                com.vesoft.nebula.Coordinate coordinate = new  com.vesoft.nebula.Coordinate(dot1.getX(),dot1.getY());
                coordList.add(coordinate);
            }

            coordListList.add(coordList);
        }

        polygon.setCoordListList(coordListList);
        PolygonWrapper polygonWrapperr = new PolygonWrapper(polygon);
        String s = polygonWrapperr.toString();
        return s;
    }

**Comment by jievince** [comment]
我用Google的[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions?hl=zh-cn#st_geogfromtext)数据库校验了一下你的数据, 根据报错信息, 你的polygon的第一个loop里有重复的vertex
![image](https://user-images.githubusercontent.com/38901892/159242821-b3adf16c-da00-4123-857e-e7e9f29b046b.png), 你可以用[这个网站](https://clydedacruz.github.io/openstreetmap-wkt-playground/)看下wkt数据可视化后的图形: 

![image](https://user-images.githubusercontent.com/38901892/159243204-d8a42923-2da1-436c-b964-62096da87c44.png)
bigquery和nebula的geo都是用的[google s2库](https://s2geometry.io/),

**Comment by ogmap** [comment]
@jievince 经查证此种类型的区是错误的区，是不符合ogc标准的，感谢。
