### ISSUE TITLE
To fix or improve the dependencies between different modules

### ISSUE THREAD

**Issue by dutor** [vesoft-inc/nebula#406]
The only explicit dependencies we have to specify is the parts regarding the auto generated source files, i.e. *.yy, *.lex, *.thrift, etc. All others shall be resolved automatically by the building system.

Besides, it's the very linking phase of some executable or shared object that requires(depends on) other modules(libraries, objects), rather than the compiling phase of individual objects. 

Besides, generated header files of the thrift files are now missing in the OUTPUT list, I think it might be the root cause of how we reach the current sistuation.

**Comment by laura-ding** [comment]
we should offer a place to save dependence packages.

**Comment by sherman-the-tank** [comment]
Done
