### ISSUE TITLE
why does the database crash when importing data, it is too unstable(v3.0.1)

### ISSUE THREAD

**Issue by skywindy** [vesoft-inc/nebula#4092]
使用3.0.1版本，为什么导入数据，动不动数据库就崩了，太不稳定了

**Comment by Sophie-Xie** [comment]
Can you provide more info on what causes the database to crash? Thanks.

**Comment by Sophie-Xie** [comment]
There is no more info, I'll close it first. You can reopen at any time if needed. Thanks.
