### ISSUE TITLE
order by error

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula#4099]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

```
(root@nebula) [nba]>  go from "Tim Duncan" over * yield dst(edge) as dst, $$.player.age as age |group by $-.dst yield sum($-.age) as age | order by $-.age
+-----+
| age |
+-----+
| 0   |
| 31  |
| 33  |
| 72  |
| 82  |
+-----+
Got 5 rows (time spent 15212/16394 us)
```

```
(root@nebula) [nba]>  go from "Tim Duncan" over * yield dst(edge) as dst, $$.player.age as age |group by $-.dst yield (sum($-.age)+3) as age | order by $-.age
[ERROR (-1009)]: SemanticError: `$-.age', not exist prop `age'
```

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
https://github.com/vesoft-inc/nebula/pull/4128
