### ISSUE TITLE
非保留关键字作为标识符使用的时候不区分大小写

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula#4102]
version 2.6.1

标识符区分大小写、关键字不区分大小写

当把非保留关键字直接作为标识符使用的时候，也不区分大小写了，有冲突。

![image](https://user-images.githubusercontent.com/13991775/160967000-a644b2e8-2dd8-416f-baad-fb1f4c240eae.png)

**Comment by wey-gu** [comment]
Thanks @ownthink :), I guess you figured out that `User` should be escaped with "`", sorry for the confusion caused.

PS. big fan of ownthink btw.

**Comment by ownthink** [comment]
加上"`"可以区分😀
