### ISSUE TITLE
Confusing error message  syntax error near `.age==42` which was actually caused by non-support of filter push-down

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#4109]
![image](https://user-images.githubusercontent.com/78209557/161225668-dc935392-f7b5-43b0-855f-d3bbd77ef019.png)
I used the community nebula(03.30nightly)，after running `MATCH (v:player:actor) where (v:actor.age==42) return v limit 5`, the error `SyntaxError: syntax error near `.age==42'` was displayed.
After I confirmed with @Shylock-Hg, the statement cannot be executed successfully because the community version does not support filter pushdown. 
If so, can we modify the error message instead of showing a syntax like error?

@Sophie-Xie @MuYiYong

**Comment by Shylock-Hg** [comment]
I think you should write `match (v:player:actor) where v.actor.age == 42 return v limit 5` to avoid syntax error.
