### ISSUE TITLE
Disk fault recovery

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#4123]
**Describe the background of the requirement**
- Considering that a node has multiple data paths, there is no need to rebuild the entire node when the disk corresponding to a data path fails.

**Describe the detail of the requirement**
- After the disk corresponding to the data path is repaired, the original part data can be automatically restored to the data path.

**Describe the scenarios of the requirement**
- Disk failback, not node failback

**Describe the priority**
- Urgency: hi
- Importance: hi

**Comment by critical27** [comment]
Try to fix this, for example, a storage start with 2 data paths, say p1, p2.
1. create a space, so both p1 and p2 has some parts
2. stop storage, remove the data on p1
3. restart storage, ideally the deleted parts would start on p1, but based on current implementation, I guess the part will only put to p2.

See `NebulaStore::loadPartFromPartManager()` for details, we won't rebuild the kvengine in p1, so the partitions removed in step2 will only be added to p2

![image](https://user-images.githubusercontent.com/13706157/162412533-43d80309-faeb-40af-88a0-de8053f12cdd.png)

**Comment by wenhaocs** [comment]
How about disk balance feature?

**Comment by Sophie-Xie** [comment]
> 

Maybe in 5.x.

**Comment by Sophie-Xie** [comment]
> How about disk balance feature?


Maybe in 5.x.
