### ISSUE TITLE
session is time-sensitive

### ISSUE THREAD

**Issue by geekCarnegie** [vesoft-inc/nebula#4125]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

backgroud:
1. create schema A（at T0）
2. create session B to query schema A, and put session B into session cache（at T1）
3. update schema A （at T2）

and then, I could not query the newest schema A by using session B, session B is only used to query schema A before update.

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
3. Step 2
5. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
Hello, Please check the doc to confirm whether it is a heartbeat cycle. https://docs.nebula-graph.com.cn/3.0.0/2.quick-start/4.nebula-graph-crud/#_1

**Comment by Sophie-Xie** [comment]
No more updates, close this issue. If there is new information, reopen it.
