### ISSUE TITLE
monitor nebula_graphd_num_active_sessino_sum < 0

### ISSUE THREAD

**Issue by kqzh** [vesoft-inc/nebula#4152]
![image](https://user-images.githubusercontent.com/35095889/163303810-437f932b-b2c3-437b-a82c-6ba762c4f372.png)

**Comment by jievince** [comment]
Did you perform some operations like `signout the session`?

**Comment by kqzh** [comment]
I didn't do it many times, maybe once or twice ? but session count is -30
