### ISSUE TITLE
what does show job Error Code “E_UNKNOWN“ mean

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula#4155]
**Describe the bug (__required__)**
show job Error code show "E_UNKNOWN"，but finally show success

**How To Reproduce(__required__)**

1. submit job stats
2. show job x

![image](https://user-images.githubusercontent.com/72034305/163331571-ea915c3d-1393-4a44-ac85-d17758f26270.png)
![image](https://user-images.githubusercontent.com/72034305/163331621-64359feb-8db7-486c-a7fb-f408659c6b2f.png)

**Expected behavior**
 If thers is no error，the Error Code should be empty

**Additional context**

**Comment by panda-sheep** [comment]
The job status  is running.
And the following error code is `empty`. Is there any difference between `empty` and `E_UNKOWN`?

**Comment by dbacyj** [comment]
E_UNKOWN feels ambiguous，keep empty like Stop Time？

**Comment by panda-sheep** [comment]
> E_UNKOWN feels ambiguous，keep empty like Stop Time？

I don't know if it's better to be `blank` or `E_UNKOWN`.
Because the job has not been executed.

**Comment by dbacyj** [comment]
> > E_UNKOWN feels ambiguous，keep empty like Stop Time？
> 
> I don't know if it's better to be `blank` or `E_UNKOWN`. Because the job has not been executed.

Since E_UNKNOWN has caused confusion for me and several others, I suggest using blank, which can be discussed later.

**Comment by panda-sheep** [comment]
> > > E_UNKOWN feels ambiguous，keep empty like Stop Time？
> > 
> > 
> > I don't know if it's better to be `blank` or `E_UNKOWN`. Because the job has not been executed.
> 
> Since E_UNKNOWN has caused confusion for me and several others, I suggest using blank, which can be discussed later.

Yeah，It can be discussed which form is better.

**Comment by Sophie-Xie** [comment]
Change “E_UNKOWN" to blank
