### ISSUE TITLE
Build docker image from Dockerfile 

### ISSUE THREAD

**Issue by darionyaphet** [vesoft-inc/nebula#417]
Docker can build images automatically by reading the instructions from a `Dockerfile`.

A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image. 

Using `docker build` users can create an automated build that executes several command-line instructions in succession.

**Comment by sherman-the-tank** [comment]
We need to figure out where to store these docker files and some other scripts

**Comment by darionyaphet** [comment]
refer to [pingcap/tidb](https://github.com/pingcap/tidb), we can put it under the root directory.
