### ISSUE TITLE
case insensitive when create tag

### ISSUE THREAD

**Issue by hetao92** [vesoft-inc/nebula#4181]
![E594639D-1328-4F6A-8694-BA3C260AAD1F](https://user-images.githubusercontent.com/18328704/163959399-bbe53e66-2cc4-4be6-9cd7-9c0b17627d12.png)

use nebula console v3.0.0 when connecting nebula v3.0.2

**Comment by Sophie-Xie** [comment]
If fix it, it will be incompatible.  And it exists only with non-reserved keywords.
