### ISSUE TITLE
The match execution result was incorrect

### ISSUE THREAD

**Issue by rustwei** [vesoft-inc/nebula#4193]
**Describe the bug (__required__)**
This is a recommended real-time scenario. Users can buy goods  that are similar to what they buy themselves.

Simple describe
u1 buy g1 g2 g3
u2 buy  g2 g3 g4 g5
u3 buy  g2 g3 g6

Query by u1 can get  g4 g5 or g6

```
explain format = 'dot'
match (u1:person) -->(g1:goods) <--(u2:person)
where id(u1)=='p1'
match (u2)-->(x:goods) 
where id(g1)<>id(x) 
return distinct(x) 
```
![image](https://user-images.githubusercontent.com/7644348/164383294-5c5182e8-07fb-458e-90fd-60a6c342837a.png)

**Your Environments (__required__)**

* OS: Linux xxx 5.15.10-1.el7.elrepo.x86_64 #1 SMP Fri Dec 17 08:57:16 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

* Compiler:  rpm install
* CPU: 
[root@k8smaster ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              60
型号名称：        Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz

* nebula version: 3.0.2

**How To Reproduce(__required__)**

```
match (u1:person) -->(g1:goods) <--(u2:person)
where id(u1)=='p1'
match (u2)-->(x:goods) 
where id(g1)<>id(x) 
return distinct(x)
``

**Expected behavior**
g4,g5,g6

but get none;

**Comment by Sophie-Xie** [comment]
fixed in https://github.com/vesoft-inc/nebula/pull/4143
