### ISSUE TITLE
When inserting edge, the graph does not check whether the length of vid exceeds the limit

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#4199]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
https://discuss.nebula-graph.com.cn/t/topic/8159/24

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
If not ingest sst, it is fixed in https://github.com/vesoft-inc/nebula/pull/4305
