### ISSUE TITLE
show prevent to store data in graphd

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#4203]
1. start nebula graph with address `192.168.8.134:9669`
2. add hosts 192.168.8.134:9669
3. create space

expected:
only store data in storage

actual:
partitions are wrong.

![image](https://user-images.githubusercontent.com/1726587/164688503-8c187ddf-6035-434c-b503-e32457ef0758.png)

when create space, after get the host key, should verify if it is `storaged` role

**Comment by HarrisChu** [comment]
![image](https://user-images.githubusercontent.com/1726587/164689567-6ff85987-1bf7-4e80-a931-d240a7d8de11.png)

**Comment by Sophie-Xie** [comment]
Offline discussion,  we can't check all scenarios and won't fix it. If we have a way in the future, we can reopen it.
