### ISSUE TITLE
Unnecessary v in branch and version names

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#4211]
Why is there a letter v in the branch names, tag names, package names, and version numbers of Nebula Graph and its eco-tools?
![image](https://user-images.githubusercontent.com/69501902/165238443-e8b13082-85f8-45b7-b22e-9a65dbea17a1.png)

Making v part of the version number does not make sense, neither logically nor grammatically. For example, when we refer to a specific version of Nebula Graph, we don't write "Nebula Graph version v3.0.2", but just "Nebula Graph version 3.0.2" or simply "Nebula Graph 3.0.2".

And we don't have a "v" series, such as v-3.0.2 or 3.0.2-v.

Cases in the database industry are:
![C2A8D899-AC77-4ae9-A5F9-F51273DC545D](https://user-images.githubusercontent.com/69501902/165239500-b019f4b6-3583-45ab-be86-f72330212543.png)
![65D21E7B-8481-4213-843F-A9F5108907CB](https://user-images.githubusercontent.com/69501902/165239680-9b284196-2717-4870-a2f1-a9b0d8e159ce.png)
![0D918CB1-49BD-4c45-B049-C2E436F09B81](https://user-images.githubusercontent.com/69501902/165239703-67b2c457-1b07-49e5-a25b-468d4347ab64.png)

**Comment by randomJoe211** [comment]
@Sophie-Xie

**Comment by Sophie-Xie** [comment]
Thanks.
We modified the branch name to avoid misuse of tag and branch, and to ensure that the z version of x.y is on a branch. But we do not plan to change the tag name, in order to keep it consistent with the past. Every community has different definition about tag name, such as k8s (with v).
