### ISSUE TITLE
Wrong behavior of coalesce()

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula#4213]
**Describe the bug (__required__)**

The coalesce() function cannot return the first non-null element in a list.

![image](https://user-images.githubusercontent.com/69501902/165699791-379fde56-3247-4ed8-b469-c33f8f319556.png)

nGQL:
```ngql
WITH [NULL, 4923, 'abc', 521, 487] AS ids RETURN coalesce(ids);
```

**Your Environments (__required__)**

* OS: ubuntu 20.04
* Nebual Graph version: 3.1.0
  ![image](https://user-images.githubusercontent.com/69501902/165700416-bdf5ae6d-e9fc-4cc9-b631-56ce4c84b79c.png)

**Comment by czpmango** [comment]
The function `coalesce()` returns the first non-null value in the given list of expressions not in the given list.

**Comment by czpmango** [comment]
```
(root@nebula) [nba]> WITH [NULL, 4923, 'abc', 521, 487] AS list1 RETURN head([x in list1 where x is not null | x])
+----------------------------------------------------------------+
| head([__VAR_0 IN list1 WHERE $__VAR_0 IS NOT NULL | $__VAR_0]) |
+----------------------------------------------------------------+
| 4923                                                           |
+----------------------------------------------------------------+
```

**Comment by czpmango** [comment]
Closed but free to ask.
