### ISSUE TITLE
version not displayed after running `show hosts`

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#4217]
My nebula graph is the latest 3.1.0 version and installed with the rpm package. When I exected `show hosts`, the version was not displayed.
![image](https://user-images.githubusercontent.com/78209557/165895893-4e8a1e8d-e2db-4224-8b95-eb4a03618e1e.png)

nebula-console version 3.0.0
<img width="542" alt="image" src="https://user-images.githubusercontent.com/78209557/165895998-d87630b1-d24f-45a2-a179-7a433478d8b5.png">

**Comment by HarrisChu** [comment]
offline cannot display version.
