### ISSUE TITLE
show job the Status is FAILED but the Error Code is SUCCEEDED

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula#4232]
**Describe the bug (__required__)**
* balance leader and show job xx :

   <img width="776" alt="image" src="https://user-images.githubusercontent.com/72034305/171137418-b03c4de1-5c22-4934-8ba6-8ef3fa53bc5c.png">

* the meta log 
![image](https://user-images.githubusercontent.com/72034305/167078756-c0e1e763-d0b5-41ef-bba3-55cf916981c9.png)

* version info
![image](https://user-images.githubusercontent.com/72034305/167079244-257a7394-7fec-4b8c-a491-80dc3805c9f3.png)

**Comment by critical27** [comment]
Marked
