### ISSUE TITLE
Here is some problem in `LIMIT in GO`

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#4233]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

**Expected behavior**
```bash
 (root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER * YIELD dst(edge) LIMIT [rand32(5),rand32(5),rand32(5)];
+-----------+
| dst(EDGE) |
+-----------+
+-----------+
Empty set (time spent 2329/2746 us)

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER * YIELD dst(edge) LIMIT [3,1,4];
+-----------+
| dst(EDGE) |
+-----------+
+-----------+
Empty set (time spent 2582/2941 us)

Fri, 06 May 2022 07:03:11 UTC

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER *  YIELD dst(edge) LIMIT [3,3,3];
+-------------+
| dst(EDGE)   |
+-------------+
| "team204"   |
| "team215"   |
| "player100" |
+-------------+
Got 3 rows (time spent 2962/3437 us)

Fri, 06 May 2022 07:04:02 UTC

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER * YIELD dst(edge) LIMIT [4,4,4];
+-------------+
| dst(EDGE)   |
+-------------+
| "team204"   |
| "team215"   |
| "player100" |
| "player102" |
+-------------+
Got 4 rows (time spent 2658/3032 us)

Fri, 06 May 2022 07:04:13 UTC

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER *  YIELD dst(edge) LIMIT [5,5,5];
+-------------+
| dst(EDGE)   |
+-------------+
| "team204"   |
| "team215"   |
| "player100" |
| "player102" |
| "player125" |
+-------------+
Got 5 rows (time spent 2838/3314 us)

Fri, 06 May 2022 07:04:20 UTC

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER * YIELD dst(edge) LIMIT [3,1,1];
+-----------+
| dst(EDGE) |
+-----------+
+-----------+
Empty set (time spent 2880/3398 us)

Fri, 06 May 2022 07:22:06 UTC

(root@nebula) [basketballplayer]> GO 3 STEPS FROM "player102" OVER * YIELD dst(edge) LIMIT [3,3,3];
+-------------+
| dst(EDGE)   |
+-------------+
| "team204"   |
| "team215"   |
| "player100" |
+-------------+
```

**Additional context**
<img width="611" alt="image" src="https://user-images.githubusercontent.com/35463247/167087427-e41822b2-e4b3-4c1b-8e17-e0062c7590aa.png">

**Comment by nevermore3** [comment]
You can try the following example，cross validation

GO FROM "player102" over * YIELD dst(edge) as dst LIMIT [3] | GO FROM $-.dst OVER * YIELD dst(edge) as dst LIMIT [1] | GO FROM $-.dst OVER * YIELD dst(edge)

**Comment by foesa-yang** [comment]
> You can try the following example，cross validation
> 
> GO FROM "player102" over * YIELD dst(edge) as dst LIMIT [3] | GO FROM $-.dst OVER * YIELD dst(edge) as dst LIMIT [1] | GO FROM $-.dst OVER * YIELD dst(edge)

(root@nebula) [basketballplayer]> GO FROM "player102" over * YIELD dst(edge) as dst LIMIT [3] | GO FROM $-.dst OVER * YIELD dst(edge) as dst LIMIT [1] | GO FROM $-.dst OVER * YIELD dst(edge)
+-----------+
| dst(EDGE) |
+-----------+
+-----------+
Empty set (time spent 5246/6589 us)

**Comment by nevermore3** [comment]
This is expected。 because the vid of the second step has not outing edge

**Comment by foesa-yang** [comment]
I've modified documents in the follwing pr.
https://github.com/vesoft-inc/nebula-docs-cn/pull/1771
https://github.com/vesoft-inc/nebula-docs/pull/1332
