### ISSUE TITLE
[UT] leader_transfer_test failed.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#4253]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
See https://github.com/vesoft-inc/nebula/runs/6398765297?check_suite_focus=true

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
The logs for this run have expired and are no longer available.
