### ISSUE TITLE
The job status is failed, but total number of failed or succeed task is 0.

### ISSUE THREAD

**Issue by slimshadylol0303** [vesoft-inc/nebula#4265]
![image](https://user-images.githubusercontent.com/95005615/168974085-8fd9b101-e9d0-480d-adee-3535ce015e32.png)

succeeded, failed, invalid in one column.

**Comment by critical27** [comment]
Has Invalid task, see https://github.com/vesoft-inc/nebula/pull/3254, this is quite old PR, I don't know which version you use.

**Comment by critical27** [comment]
![image](https://user-images.githubusercontent.com/13706157/183323682-97adcb42-de04-460f-bb6c-47e7ac1dad77.png)
