### ISSUE TITLE
The status and start time of tasks is invalid

### ISSUE THREAD

**Issue by slimshadylol0303** [vesoft-inc/nebula#4266]
![image](https://user-images.githubusercontent.com/95005615/168974978-0080483e-e099-4c6a-b54b-96a2346e8b5c.png)

**Comment by critical27** [comment]
![image](https://user-images.githubusercontent.com/13706157/183326274-a5f6a33a-7403-413e-902c-b04c25939c3d.png)

It is empty now, my commit id is cd082a8a,
