### ISSUE TITLE
console should provide a command to suggest current space/user

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#427]
suggest:
yield user()
yield space()
yield server ()

or :
nba >

**Comment by sherman-the-tank** [comment]
👍

**Comment by steppenwolfyuetong** [comment]
👍
HAHA,  Sorry, I didn't notice the issue.
I found this defect  through deployment nebula.

**Comment by jude-zhu** [comment]
#615 is to display the space in use.
![1](https://user-images.githubusercontent.com/51590253/62924297-61a56a80-bde2-11e9-8d31-bab906361530.jpg)

yield user()
yield space()
yield server()
are not supported at this moment
