### ISSUE TITLE
the metrics of "commit_log_latency_us" is abnormal. Too large

### ISSUE THREAD

**Issue by xigongdaEricyang** [vesoft-inc/nebula#4274]
![image](https://user-images.githubusercontent.com/9858560/169739887-857530fb-9366-42e5-b9f1-ff98df4407af.png)

**Comment by liwenhui-soul** [comment]
what's this mean?

**Comment by xigongdaEricyang** [comment]
in stats metrics， the value of commit_log_latency_us is 7841184878, and it means commit log takes almost 7841s. The value is too large, so we think the value is wrong

**Comment by shanlai** [comment]
the same problem exists with the metrics of "append_wal_latency_us", please fix it together

**Comment by jinyingsunny** [comment]
![image](https://user-images.githubusercontent.com/106510322/196430192-2fb3a8e9-6727-425a-bdd5-01cdb71eb35e.png)
checked ent-3.3 when write with speed of 1/s
