### ISSUE TITLE
Incorrect tips 

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#4278]
![image](https://user-images.githubusercontent.com/78209557/169958123-a082a67a-3373-45b9-b29f-944d8f4a6981.png)

As the picture showed above, A function syntax error is perceived as an aliasing error.

When I typed `go from "player100" over serve yield edge(src)`, the system prompted me to add an alias, but the real problem was the edge(src) error, which should be src(edge).

**Comment by CPWstatic** [comment]
This query has two semantic errors, first you should give an alias when using edge(), second src can not be used as parameter for edge. So the previous error report at begin.
