### ISSUE TITLE
recommended partition_num and replica_factor

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#4284]
### Discussed in https://github.com/vesoft-inc/nebula/discussions/4281

<div type='discussions-op-text'>

<sup>Originally posted by **porscheme** May 24, 2022</sup>
We wanted to  ingestion data to our fresh Nebula Graph Cluster.
- Given below details what should be optimal number of partitions and replica factor?
- Does the number of graphd and metad node make sense?

Below are the details
Raw Data Size before ingestion: 1 TB
Cluster Config:
|metad|graphd|storage|
|-------|--------|--------|
|1|3|9|

Each VM Config:
|vCPU|Memory|NVMe Disks|
|------|---------|-------------|
|16|128GB|2 X 2 TB|

@wey-gu </div>

**Comment by wey-gu** [comment]
Closing it as it's being discussed in the discussion: https://github.com/vesoft-inc/nebula/discussions/4281
