### ISSUE TITLE
Lookup limit pushdown might crash storaged when running concurrently

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula#4286]
Prerequisite:
1. set query_concurrently=true in storaged conf.
2. :play nba to create the nba space.

run below shell will crash storaged
```
echo "start to run"
for i in `seq 1 10`
do
    echo $i; ./nebula-console -addr <ip> -port <port> -u root -p nebula -e "use nba; LOOKUP ON like YIELD like.likeness as likeness | ORDER BY \$-.likeness | Limit 2" &
done
wait
echo "done"
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

refer to the description.

**Expected behavior**

Storaged won't crash.

**Additional context**

**Comment by Sophie-Xie** [comment]
Fixed in #4288
