### ISSUE TITLE
Questions about lpad() and rpad() usage

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#4291]
According to the official definition, the third parameter `letters` should be optional.
![image](https://user-images.githubusercontent.com/78672629/171079965-46e8b329-eaaf-48ce-b092-5075b921c1e3.png)
![image](https://user-images.githubusercontent.com/78672629/171080004-b8d662b3-1843-404c-ad1d-5d87e7437918.png)
![image](https://user-images.githubusercontent.com/78672629/171081274-93f2ecba-cddd-4dd5-8e4b-6ac0f0ffe91a.png)

**Comment by CPWstatic** [comment]
Sorry, i checked the source code, it must be provided 3 params. This behavior does not change ever since nebula1.0.
