### ISSUE TITLE
MATCH (v) RETURN v LIMIT n returns -1005:Storage Error: part: 40, error: E_RPC_FAILURE(-3).

### ISSUE THREAD

**Issue by sunkararp** [vesoft-inc/nebula#4296]
### Discussed in https://github.com/vesoft-inc/nebula/discussions/4294

<div type='discussions-op-text'>

<sup>Originally posted by **sunkararp** June  1, 2022</sup>
Hi @wey-gu simple below query fails with the error.

```
MATCH (v:Student) RETURN v LIMIT 10
```
Error
```
-1005:Storage Error: part: 40, error: E_RPC_FAILURE(-3)
```

There are about 10 million Student vertices in the system.

- Is my query timing out? 
- If timing out, per how to resolve [faq](https://docs.nebula-graph.io/3.1.0/20.appendix/0.FAQ/#how_to_resolve_the_error_storage_error_e_rpc_failure) I need to extend the connection timeout of the Storage client by setting --storage_client_timeout_ms=60000 in nebula-graphd.conf file
- Where is nebula-graphd.conf file and how I set --storage_client_timeout_ms in K8S environment?
- Running below command brings up all graphd severs
```
show hosts
```
- I tried to edit nebula-cluster-graphd, but my edits are overridden by resetting graphd
```
kubectl edit configmap nebula-cluster-graphd -n mynamespace
```
</div>

**Comment by wey-gu** [comment]
Let's discuss it in discussion further, closing it first, ok? @sunkararp
