### ISSUE TITLE
"Fetch prop on * " Performance decline very much when there's many tags in graph namespace .

### ISSUE THREAD

**Issue by jiayuehua** [vesoft-inc/nebula#4301]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

https://discuss.nebula-graph.com.cn/t/topic/8993

**Your Environments (__required__)**

* OS: `ubuntu`
* Compiler: `gcc 9.3` 
* CPU: `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz `
* Commit id `3.1`

**How To Reproduce(__required__)**

1. create a graph space , with 100 tag and 10000 vertex
2. go from “vid” over * yield dst(edge) as dst | fetch prop on * $-.dst  (1.97s)
3. create a graph space , with 1000 tag and 10000 vertex
4.  go from “vid” over * yield dst(edge) as dst | fetch prop on * $-.dst (19.79s)

**Expected behavior**

fetch query performance shouldn't affected much by tags number.

**Additional context**

**Comment by Shylock-Hg** [comment]
Related to https://github.com/vesoft-inc/nebula/issues/4063
