### ISSUE TITLE
query crash when typo property name

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#431]
I  typo likenessx (but should likeness) and crashed:

nebula> go from 100 over like yield $^[player].name, $$[player].name, like._dst, like.likenessx                      F0524 18:29:24.830096 28428 NebulaSchemaProvider.cpp:48] Check failed: it != fieldNameIndex_.end() Unknown field "likenessx"                                                                                                              *** Check failure stack trace: ***                                                                                       @          0x1b1faed  google::LogMessage::Fail()                                                                     @          0x1b240fc  google::LogMessage::SendToLog()                                                                @          0x1b1f7ed  google::LogMessage::Flush()                                                                    @          0x1b1ffd9  google::LogMessageFatal::~LogMessageFatal()                                                    @          0x15c2244  nebula::meta::NebulaSchemaProvider::getFieldType()                                             @          0x11dbd27  nebula::storage::QueryBaseProcessor<>::checkAndBuildContexts()                                 @          0x11d941d  nebula::storage::QueryBaseProcessor<>::process()                                               @          0x11d511c  nebula::storage::StorageServiceHandler::future_getOutBound()                                   @          0x12092f9  _ZZN6nebula7storage4cpp218StorageServiceSvIf20async_eb_getOutBoundESt10unique_ptrIN6apache6thrift15HandlerCallbackINS1_13QueryResponseEEESt14default_deleteIS8_EERKNS1_19GetNeighborsRequestEENUlvE_clEv            @          0x120e579  _ZN5folly14makeFutureWithIZN6nebula7storage4cpp218StorageServiceSvIf20async_eb_getOutBoundESt10unique_ptrIN6apache6thrift15HandlerCallbackINS3_13QueryResponseEEESt14default_deleteISA_EERKNS3_19GetNeighborsRequestEEUlvE_EENSt9enable_ifIXsrNS_8isFutureINS_13invoke_resultIT_JEE4typeEEE5valueESN_E4typeEOSL_                         @          0x120b68c  _ZN6apache6thrift6detail2si8async_tmIZN6nebula7storage4cpp218StorageServiceSvIf20async_eb_getOutBoundESt10unique_ptrINS0_15HandlerCallbackINS6_13QueryResponseEEESt14default_deleteISB_EERKNS6_19GetNeighborsRequestEEUlvE_EEvPNS0_15ServerInterfaceES8_INS9_IN5folly9drop_unitINSt9result_ofIFT_vEE4type10value_typeEE4typeEEESC_ISV_EEOSO_                                                                                                                  @          0x120a355  _ZZN6apache6thrift6detail2si8async_ebIZN6nebula7storage4cpp218StorageServiceSvIf20async_eb_getOutBoundESt10unique_ptrINS0_15HandlerCallbackINS6_13QueryResponseEEESt14default_deleteISB_EERKNS6_19GetNeighborsRe

**Comment by dutor** [comment]
Thanks to you users.

At such an infant stage, we are sorry about the confusing and frustrating situations like this. There might be a lot more such errors in terms of typing and schema, on which we are working hard.

Again, appreciated very much.

**Comment by laura-ding** [comment]
We should remove the unreasonable  CHECK in NebulaSchemaProvider

**Comment by darionyaphet** [comment]
Good catch !

Check property name is existed before execution is a good idea？

**Comment by dangleptr** [comment]
@darionyaphet Would you want to fix it?

**Comment by darionyaphet** [comment]
Good ! I will try to fix it ~

**Comment by wadeliuyi** [comment]
I think this is same with #571, should close it?
