### ISSUE TITLE
Inactive indexes should not be selected

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4314]
**Describe the bug (__required__)**
A newly created index that has not been rebuilt is selected causing a query exception.

**Your Environments (__required__)**
version: v3.0

**How To Reproduce(__required__)**
```
(root@nebula) [nba]> match (v:player) return v limit 3
+-------------------------------------------------------+
| v                                                     |
+-------------------------------------------------------+
| ("Dwyane Wade" :player{age: 37, name: "Dwyane Wade"}) |
| ("Tony Parker" :player{age: 36, name: "Tony Parker"}) |
| ("Null2" :player{age: -2, name: __NULL__})            |
+-------------------------------------------------------+
Got 3 rows (time spent 5547/5879 us)

(root@nebula) [nba]> create tag index player_age_index on player(age)
Execution succeeded (time spent 1349/1603 us)

(root@nebula) [nba]> match (v:player) return v limit 3
+---+
| v |
+---+
+---+
Empty set (time spent 4065/4675 us)
```

**Expected behavior**
Ensure the query result is correct.

**Additional context**
Redesign the `create index` statements.

**Comment by Sophie-Xie** [comment]
Discuss with Fang Yang offline. 
Whether it can be judged that the index has been created but has not been rebuilt, and if so, a prompt will be given;
If not, do not change it.
