### ISSUE TITLE
how to take properties to the next hops?

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#432]
for example:

vertex:  player:100,   play:101,   team:200

edge1: player: 100  --like--> player 101

edge2:  player 101  ---serve---> team 20

Two hop query:  go from 100 over like yield $^[player].name as p1, $$[player].age as p2 | go from ($-:id ??) over serve yield (how to get p1 and p2?)

**Comment by dutor** [comment]
Apparently, this is a must feature, which will be available in the beta release.

**Comment by dangleptr** [comment]
We should support $-.prop in YieldClause

**Comment by sherman-the-tank** [comment]
Done
