### ISSUE TITLE
Download sst return success but actually failed

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula#4321]
**Describe the bug (__required__)**
As title

**Your Environments (__required__)**

* Commit id (e.g. `a3ffc7d8`)
![image](https://user-images.githubusercontent.com/72034305/173502910-60b3e6ae-1e60-47f3-b691-b648bdf40243.png)

**How To Reproduce(__required__)**

![image](https://user-images.githubusercontent.com/72034305/173502600-a1f1e5d7-45d2-415a-956f-90bfb242584f.png)

![image](https://user-images.githubusercontent.com/72034305/173502704-4f259572-f53d-425a-89b2-85790ed35642.png)

![image](https://user-images.githubusercontent.com/72034305/173502788-3a404087-ccf4-4c5d-a6a8-5000d4b0aec6.png)

**Expected behavior**

**Additional context**

**Comment by dbacyj** [comment]
The reason the download fails is that the port should be 9000 not 9090

**Comment by critical27** [comment]
How can we tell 9090 is not a correct hdfs port? User should be responsible for what he inputs to nebula.

**Comment by critical27** [comment]
And btw, the log above means that it truly succeed to download from 9090 (Otherwise, it will print error log).

I'll close it for now. Could reopen it if you have different opnions.

**Comment by dbacyj** [comment]
The port number is just to supplement the reason for the failure, the point is that it actually failed, but returned success. Here we can't get the actual success status, right?

**Comment by critical27** [comment]
Yeah, can't get status. Probably same as https://github.com/vesoft-inc/nebula/issues/4382. Not sure if we can address it, will try.

**Comment by critical27** [comment]
Could try it after #4442 merged @dbacyj. If the hdfs address is illegal, it will return a error. But I don't have the hdfs environment, so it has not been totally verified when the address is legal.
