### ISSUE TITLE
the date function is used to filter in ngql statement return incorrect set

### ISSUE THREAD

**Issue by Yungthuis** [vesoft-inc/nebula#4326]
**the date function is used to filter in ngql statement return incorrect set.But Cypher statement return correnct set.**
nGQL:
(root@nebula) [eureka_graph]> lookup on bif_theme where bif_theme.updatetime<date() 
+-----------------------------+
| VertexID                    |
+-----------------------------+
| "0002--149646701377686850"  |
+-----------------------------+
| "0002--1967168143308137034" |
+-----------------------------+
| "0002--3313911048012438412" |
+-----------------------------+
| "0002--5014409660228186714" |
+-----------------------------+
| "0002--6075675756641041273" |
+-----------------------------+
| "0002--6423862493112779759" |
+-----------------------------+
| "0002--6823261347735215104" |
+-----------------------------+
| "0002-5803693150745076069"  |
+-----------------------------+
| "0002-8164197339668919786"  |
+-----------------------------+
Got 9 rows (time spent 1224/1509 us)

Cypher:
(root@nebula) [eureka_graph]> match (n:bif_theme) where n.updatetime<date() return n
Empty set (time spent 18061/18376 us)

Neubla version: 2.0.1

execute plan:

(root@nebula) [eureka_graph]> explain lookup on bif_theme where bif_theme.updatetime<date()
Execution succeeded (time spent 205/557 us)

Execution Plan (optimize time 73 us)

-----+-----------+--------------+----------------+------------------------------------
| id | name      | dependencies | profiling data | operator info                     |
-----+-----------+--------------+----------------+------------------------------------
|  2 | IndexScan | 0            |                | outputVar: [                      |
|    |           |              |                |   {                               |
|    |           |              |                |     "colNames": [                 |
|    |           |              |                |       "VertexID"                  |
|    |           |              |                |     ],                            |
|    |           |              |                |     "name": "__IndexScan_1",      |
|    |           |              |                |     "type": "DATASET"             |
|    |           |              |                |   }                               |
|    |           |              |                | ]                                 |
|    |           |              |                | inputVar:                         |
|    |           |              |                | space: 4254                       |
|    |           |              |                | dedup: false                      |
|    |           |              |                | limit: 9223372036854775807        |
|    |           |              |                | filter:                           |
|    |           |              |                | orderBy: []                       |
|    |           |              |                | schemaId: 7834                    |
|    |           |              |                | isEdge: false                     |
|    |           |              |                | returnCols: [                     |
|    |           |              |                |   "_vid"                          |
|    |           |              |                | ]                                 |
|    |           |              |                | indexCtx: [                       |
|    |           |              |                |   {                               |
|    |           |              |                |     "columnHints": [              |
|    |           |              |                |       {                           |
|    |           |              |                |         "endValue": "2022-06-15", |
|    |           |              |                |         "beginValue": "0-01-01",  |
|    |           |              |                |         "column": "updatetime",   |
|    |           |              |                |         "scanType": "RANGE"       |
|    |           |              |                |       }                           |
|    |           |              |                |     ],                            |
|    |           |              |                |     "index_id": 7840,             |
|    |           |              |                |     "filter": ""                  |
|    |           |              |                |   }                               |
|    |           |              |                | ]                                 |
-----+-----------+--------------+----------------+------------------------------------
|  0 | Start     |              |                | outputVar: [                      |
|    |           |              |                |   {                               |
|    |           |              |                |     "colNames": [],               |
|    |           |              |                |     "name": "__Start_0",          |
|    |           |              |                |     "type": "DATASET"             |
|    |           |              |                |   }                               |
|    |           |              |                | ]                                 |
-----+-----------+--------------+----------------+------------------------------------

Wed, 15 Jun 2022 10:16:55 CST

(root@nebula) [eureka_graph]> explain match (n:bif_theme) where n.updatetime<date() return n
Execution succeeded (time spent 861/1291 us)

Execution Plan (optimize time 111 us)

-----+-------------+--------------+----------------+----------------------------------------------------
| id | name        | dependencies | profiling data | operator info                                     |
-----+-------------+--------------+----------------+----------------------------------------------------
| 10 | Project     | 9            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "n"                                         |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__Project_10",                       |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __Filter_9                              |
|    |             |              |                | columns: [                                        |
|    |             |              |                |   "$n"                                            |
|    |             |              |                | ]                                                 |
-----+-------------+--------------+----------------+----------------------------------------------------
|  9 | Filter      | 8            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "n",                                        |
|    |             |              |                |       "__COL_0"                                   |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__Filter_9",                         |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __Filter_8                              |
|    |             |              |                | condition: ($n.updatetime<date())                 |
-----+-------------+--------------+----------------+----------------------------------------------------
|  8 | Filter      | 7            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "n",                                        |
|    |             |              |                |       "__COL_0"                                   |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__Filter_8",                         |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __Project_7                             |
|    |             |              |                | condition: (hasSameEdgeInPath($-.__COL_0)==false) |
-----+-------------+--------------+----------------+----------------------------------------------------
|  7 | Project     | 6            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "n",                                        |
|    |             |              |                |       "__COL_0"                                   |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__Project_7",                        |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __Project_6                             |
|    |             |              |                | columns: [                                        |
|    |             |              |                |   "startNode($-._path) AS n",                     |
|    |             |              |                |   "reversePath(PathBuild[$-._path]) AS __COL_0"   |
|    |             |              |                | ]                                                 |
-----+-------------+--------------+----------------+----------------------------------------------------
|  6 | Project     | 5            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "_path"                                     |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__Project_6",                        |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __Filter_5                              |
|    |             |              |                | columns: [                                        |
|    |             |              |                |   "PathBuild[VERTEX]"                             |
|    |             |              |                | ]                                                 |
-----+-------------+--------------+----------------+----------------------------------------------------
|  5 | Filter      | 13           |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [],                               |
|    |             |              |                |     "name": "__Filter_5",                         |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __GetVertices_4                         |
|    |             |              |                | condition: ("bif_theme" IN tags(VERTEX))          |
-----+-------------+--------------+----------------+----------------------------------------------------
| 13 | GetVertices | 11           |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [],                               |
|    |             |              |                |     "name": "__GetVertices_4",                    |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar: __IndexScan_1                           |
|    |             |              |                | space: 4254                                       |
|    |             |              |                | dedup: true                                       |
|    |             |              |                | limit: 9223372036854775807                        |
|    |             |              |                | filter:                                           |
|    |             |              |                | orderBy: []                                       |
|    |             |              |                | src: $_vid                                        |
|    |             |              |                | props: [                                          |
|    |             |              |                |   {                                               |
|    |             |              |                |     "props": [                                    |
|    |             |              |                |       "id",                                       |
|    |             |              |                |       "code",                                     |
|    |             |              |                |       "en_name",                                  |
|    |             |              |                |       "cn_name",                                  |
|    |             |              |                |       "updatetime",                               |
|    |             |              |                |       "source",                                   |
|    |             |              |                |       "labels",                                   |
|    |             |              |                |       "type",                                     |
|    |             |              |                |       "_tag"                                      |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "tagId": 7928                                 |
|    |             |              |                |   },                                              |
|    |             |              |                |   {                                               |
|    |             |              |                |     "props": [                                    |
|    |             |              |                |       "id",                                       |
|    |             |              |                |       "labels",                                   |
|    |             |              |                |       "type",                                     |
|    |             |              |                |       "code",                                     |
|    |             |              |                |       "updatetime",                               |
|    |             |              |                |       "en_name",                                  |
|    |             |              |                |       "cn_name",                                  |
|    |             |              |                |       "source",                                   |
|    |             |              |                |       "org_id",                                   |
|    |             |              |                |       "language",                                 |
|    |             |              |                |       "skim_times_cnt_all",                       |
|    |             |              |                |       "authoritative_knowledge_flag",             |
|    |             |              |                |       "url",                                      |
|    |             |              |                |       "author_account",                           |
|    |             |              |                |       "author_name",                              |
|    |             |              |                |       "paragraph_id",                             |
|    |             |              |                |       "anchor_num",                               |
|    |             |              |                |       "_tag"                                      |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "tagId": 9520                                 |
|    |             |              |                |   },                                              |
|    |             |              |                |   {                                               |
|    |             |              |                |     "props": [                                    |
|    |             |              |                |       "labels",                                   |
|    |             |              |                |       "updatetime",                               |
|    |             |              |                |       "type",                                     |
|    |             |              |                |       "dim_code",                                 |
|    |             |              |                |       "dim_cn_name",                              |
|    |             |              |                |       "code",                                     |
|    |             |              |                |       "cn_name",                                  |
|    |             |              |                |       "en_name",                                  |
|    |             |              |                |       "level_no",                                 |
|    |             |              |                |       "level_cname",                              |
|    |             |              |                |       "subject_area",                             |
|    |             |              |                |       "metric_owner",                             |
|    |             |              |                |       "business_definition",                      |
|    |             |              |                |       "valid_period",                             |
|    |             |              |                |       "business_rule_desc",                       |
|    |             |              |                |       "apply_business_domain",                    |
|    |             |              |                |       "_tag"                                      |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "tagId": 4432                                 |
|    |             |              |                |   },                                              |
|    |             |              |                |   {                                               |
|    |             |              |                |     "props": [                                    |
|    |             |              |                |       "id",                                       |
|    |             |              |                |       "code",                                     |
|    |             |              |                |       "en_name",                                  |
|    |             |              |                |       "cn_name",                                  |
|    |             |              |                |       "updatetime",                               |
|    |             |              |                |       "source",                                   |
|    |             |              |                |       "labels",                                   |
|    |             |              |                |       "type",                                     |
|    |             |              |                |       "dept_id",                                  |
|    |             |              |                |       "level",                                    |
|    |             |              |                |       "dept_expense_type_code",                   |
|    |             |              |                |       "dept_expense_type_cn_name",                |
|    |             |              |                |       "dept_expense_type_en_name",                |
|    |             |              |                |       "dept_tag_code",                            |
|    |             |              |                |       "dept_tag_cn_name",                         |
|    |             |              |                |       "dept_tag_en_name",                         |
|    |             |              |                |       "_tag"                                      |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "tagId": 7934                                 |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | exprs: []                                         |
-----+-------------+--------------+----------------+----------------------------------------------------
| 11 | IndexScan   | 0            |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [                                 |
|    |             |              |                |       "_vid"                                      |
|    |             |              |                |     ],                                            |
|    |             |              |                |     "name": "__IndexScan_1",                      |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
|    |             |              |                | inputVar:                                         |
|    |             |              |                | space: 4254                                       |
|    |             |              |                | dedup: false                                      |
|    |             |              |                | limit: 9223372036854775807                        |
|    |             |              |                | filter:                                           |
|    |             |              |                | orderBy: []                                       |
|    |             |              |                | schemaId: 7834                                    |
|    |             |              |                | isEdge: false                                     |
|    |             |              |                | returnCols: [                                     |
|    |             |              |                |   "_vid"                                          |
|    |             |              |                | ]                                                 |
|    |             |              |                | indexCtx: [                                       |
|    |             |              |                |   {                                               |
|    |             |              |                |     "columnHints": [],                            |
|    |             |              |                |     "index_id": 7847,                             |
|    |             |              |                |     "filter": ""                                  |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
-----+-------------+--------------+----------------+----------------------------------------------------
|  0 | Start       |              |                | outputVar: [                                      |
|    |             |              |                |   {                                               |
|    |             |              |                |     "colNames": [],                               |
|    |             |              |                |     "name": "__Start_0",                          |
|    |             |              |                |     "type": "DATASET"                             |
|    |             |              |                |   }                                               |
|    |             |              |                | ]                                                 |
-----+-------------+--------------+----------------+----------------------------------------------------

**Comment by Shylock-Hg** [comment]
Current version had fix it.
