### ISSUE TITLE
 graphd exit when insert  in the console

### ISSUE THREAD

**Issue by AI-Friend** [vesoft-inc/nebula#4335]
nebula graph 版本3.1.0 
console 版本3.0.0

insert 一条官方例子的数据，console马上 not connected, 仔细看，每次都是因为graphd exit了
是因为连了studio吗，关键studio 也没有配置用户名密码，也登录不上

感谢回复！

**Comment by wey-gu** [comment]
可能是 graphd crash 了，能去看看 graphd 的 log 么？是不是硬盘满了啥的？

**Comment by AI-Friend** [comment]
好像是配置studio的问题，请问studio的host:port 怎么配置才能登录呀，用户名和密码我没有设置
studio 服务的端口是不是要和 graphd的端口保持一致呢
![image](https://user-images.githubusercontent.com/45777154/174930070-1418c352-8e5f-45fb-a4c6-87a88e7b94ad.png)

**Comment by Sophie-Xie** [comment]
> 好像是配置studio的问题，请问studio的host:port 怎么配置才能登录呀， 没有设置过用户名和密码，所以就写了ip:9669, root, 123 登录，结果就是 Request Error: 504 Gateway Timeout 请问studio 服务的端口是不是要和 graphd的端口保持一致呢？ ![image](https://user-images.githubusercontent.com/45777154/174930070-1418c352-8e5f-45fb-a4c6-87a88e7b94ad.png)

https://docs.nebula-graph.com.cn/3.1.0/nebula-studio/deploy-connect/st-ug-connect/

If insert by console, it shouldn't be problem of studio.

**Comment by wey-gu** [comment]
> 所以就写了ip:9669, root, 123 登录

需要这个 ip 是 GraphD 的 IP，而且，studio 的后端服务进程可以访问这个 ip

**Comment by wey-gu** [comment]
而且如 @Sophie-Xie 回答，这个问题本身和 studio 没有关系哈。

**Comment by AI-Friend** [comment]
@wey-gu 
是的，感谢，console问题解决了，是因为console的端口问题，
现在studio问题是使用真实graphd ip:9669 登录studio，结果是 Request Error: 504 Gateway Timeout，这个需要，额外配置studio配置文件吗，比如改端口之类的，我使用的虚拟机，虚拟机和我本机都可以ping 通

感谢！

**Comment by wey-gu** [comment]
> 

这个其实是网络问题哈，你的 studio 的后端程序充当了前端访问 graphd 的一个 gateway，所以，你暴露、配置的 graphd 的网络 ip 也需要让 studio 后端可以访问，比如在一个机器上，肯定可以，如果不在，你就需要 graphd 配置一个外部可以访达的地址。
