### ISSUE TITLE
it takes too long to describe a tag after creating it under wsl docker

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#435]
My environment is wsl.

first I create a tag: CREATE TAG player4(name string, age int);

then i have to wait quite a long time ( about 10sec) to successfully describe tag player4.

During this long period, what i can get is [ERROR (-8)]: Schema not found for tag `player4' 

By the way, I know the flag load_data_interval_secs , but i can't find it in the config files in the docker any more.

**Comment by dutor** [comment]
This problem is due the synchronization of the meta infos among our different processes. For now the meta infos are updated through periodic polling.

To address this problem we need to some kind of broadcast mechanism or forced update through a user command.

**Comment by sherman-the-tank** [comment]
This is definitely a bug. When we **DESCRIBE** a tag/edge/etc., we should read it from the meta server

**Comment by dangleptr** [comment]
It is a bug.  Currently,  show space/edge/tag and describe space are fetched from meta server,  but describe tag/edge is fetched from meta client cache.  
We should keep them consistency.  All show/describe should fetch information from server directly.

**Comment by dangleptr** [comment]
@laura-ding Do you want to fix it?

**Comment by whitewum** [comment]
My question is: why 10 seconds? The fetch loop cycle is only 1 or 2 sec.

**Comment by laura-ding** [comment]
I thought the user created a schema, usually read back the schema firstly, then insert the data via the cached schema. So describe uses the cached schema, it can tell the user in advance whether you can insert data.

**Comment by laura-ding** [comment]
@dangleptr I will modify it to get schema by meta server

**Comment by laura-ding** [comment]
Under docker, the default value of load_data_interval_secs is 2min, now all describe command unified get data from metad, it doesn't need to wait.
