### ISSUE TITLE
query is too long when inserting long fields

### ISSUE THREAD

**Issue by nuo-o** [vesoft-inc/nebula#4358]
使用 nebula 2.6.2，我有一个字段是json形式的，特别长。插入的时候会报错。请问应该怎么解决？

使用 nebula importer 报错提示：
ErrMsg: SyntaxError: Query is too large (4628889 > 4194304)., ErrCode: -1004

**Comment by HarrisChu** [comment]
Could modify the default configuration `-max_allowed_query_size`, it's `4194304` by default.

Btw, if the property is too large, it would have poor performance.
Maybe you could save the json in Mongo, and then map the id in nebula.

**Comment by nuo-o** [comment]
> 

感谢～ 调整参数以后确实解决问题了。
但我想请教下，如果不用property做筛选条件，只是单独根据id取该字段的话，也会影响性能吗？

thanks a lot for your reply! it works after enlarging the parameter! 
About your sweet suggestion, i only need the large property after filtering its ID. would it still harm the performance?

**Comment by nuo-o** [comment]
> Could modify the default configuration `--max_allowed_query_size` in graph, it's `4194304` by default.
> 
> Btw, if the property is too large, it would have poor performance. Maybe you could save the json in Mongo, and then map the id in nebula.

感谢～ 调整参数以后确实解决问题了。
但我想请教下，如果不用property做筛选条件，只是单独根据id取该字段的话，也会影响性能吗？

thanks a lot for your reply! it works after enlarging the parameter!
About your sweet suggestion, i only need the large property after filtering its ID. would it still harm the performance?

**Comment by wey-gu** [comment]
> 感谢～ 调整参数以后确实解决问题了。
但我想请教下，如果不用property做筛选条件，只是单独根据id取该字段的话，也会影响性能吗？
> 
> thanks a lot for your reply! it works after enlarging the parameter!
About your sweet suggestion, i only need the large property after filtering its ID. would it still harm the performance?

You would have more idea after reading blog post on nebula's design in underlying the kv. i.e. https://nebula-graph.com.cn/posts/nebula-graph-storage-engine-overview/

Although you don't create indexes for those huge properties, the data itself still need to persist property as the value of the KV storage, it's still costly to have them in the LSM tree.

K-V-separation would help mitigate this cost(search Key-Value separation in docs), but if possible, we should avoid put huge properties in GraphDB.

**Comment by nuo-o** [comment]
> You would have more idea after reading blog post on nebula's design in underlying the kv. i.e. https://nebula-graph.com.cn/posts/nebula-graph-storage-engine-overview/
> 
> Although you don't create indexes for those huge properties, the data itself still need to persist property as the value of the KV storage, it's still costly to have them in the LSM tree(less vertices will be cached), and it's costly to YIELD one or all of the property during the query, too, you have to fetch it(IO) all and then deserialize (CPU) it from binary value blob.
> 
> K-V-separation would help mitigate this cost in some level(search Key-Value separation in docs), but if possible, we should avoid put huge properties in GraphDB.

Got it! Thanks a lot!
