### ISSUE TITLE
some questions about insert vertex

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#436]
1. how to insert a vertex without any property:
CREATE TAG userx();  // ok.
insert vertex userx() values 222:() // syntax error
insert vertex userx() values 222 // syntax error

2. how to insert a vertex with all the properties as default value?
CREATE TAG player(name string, age int);// ok.
insert vertex player(name) values 111:("jaja") //ok.
insert vertex player(age) values 111:(20) //ok.
insert vertex player(age) values 111:("wahaha") // ok.  BUT SHOULD NOT. "wahaha"is a string, not int.
insert vertex player() values 111:() // syntax error. BUT I want to set only the id, with all properties as default value.

**Comment by dutor** [comment]
We haven't support default values by now, but it will be very soon, along with the supports from syntax and scheme management.

**Comment by laura-ding** [comment]
Has finished. So closed.
