### ISSUE TITLE
does nGQL support comments , such as # or // or /* */, and line break, such as 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#437]
for a very very large query, it's common to add some comments, and breaks it into multiple lines.
Think about a 50 lines query.

**Comment by steppenwolfyuetong** [comment]
For comment，
There are column level comment and table level comment.
There are three comment formats in mysql, e.g. `#, /* */, -- `

**Comment by dutor** [comment]
As discussed offline, I will assign this feature request to @laura-ding to accomplish.

**Comment by laura-ding** [comment]
Has supported,  pr is 457

**Comment by whitewum** [comment]
great! like it!
