### ISSUE TITLE
Support DataX

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4379]
**Feature description**
[DataX](https://github.com/alibaba/DataX) is an offline data synchronization framework open sourced by Alibaba Cloud.This framework provides a unified abstraction for data synchronization. Users can implement Reader/Writer plugins to integrate data sources, and each newly accessed data source can communicate with existing data sources in its ecosystem. 
nebula looks forward to supporting DataX.

**TODO list**
- [ ] Configure metadata mapping
- [ ] Support data Reader/Writer plugin
- [ ] Regression testing
- [ ] Documentation

**Additional context**
All aspects related to performance need to be evaluated in detail.

**Comment by czpmango** [comment]
https://github.com/nebula-contrib/DataX

**Comment by VincentSleepless** [comment]
you can write one by sdk,  little code ~~~ but multi version is not supportted~

> https://github.com/nebula-contrib/DataX

**Comment by czpmango** [comment]
The DataX skeleton has been implemented and will be improved later. Close this issue for now.
