### ISSUE TITLE
can nQGL support both the singular and plural form 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#438]
e.g. 

show space(s), tag(s). // it's ok for the xs

go xxx yield(s)  // a bit hard to tell

insert xxx value(s) // what about a single item value or  even empty value?

**Comment by dutor** [comment]
For nouns, yes. For verbs, no.

**Comment by sherman-the-tank** [comment]
> For nouns, yes. For verbs, no.

+1

**Comment by sherman-the-tank** [comment]
Done
