### ISSUE TITLE
Storage Crash when deleting vertex does not exist and vid length more than we define in space.

### ISSUE THREAD

**Issue by Milittle** [vesoft-inc/nebula#4397]
Storage Crash when deleting vertex does not exist and vid length more than we define in space.

**How To Reproduce(__required__)**

Step 1 
Create one space: define vid length is 120.

create tag and create one index.(this bug need indexes in space.)

Step 2 
delete vertex 'xxxx' 

xxx length need more than vid length defined.

the storage will be dead.

I think we should add one verfication in the follow one line just like the second line:

one line: https://github.com/vesoft-inc/nebula/blob/7a7ab68a0497da8f13e1af7c5ca6b080352202a3/src/storage/mutate/DeleteVerticesProcessor.cpp#L117

second line: https://github.com/vesoft-inc/nebula/blob/7a7ab68a0497da8f13e1af7c5ca6b080352202a3/src/storage/mutate/DeleteVerticesProcessor.cpp#L59

**Comment by Milittle** [comment]
> Storage Crash when deleting vertex does not exist and vid length more than we define in space.
> 
> **How To Reproduce(**required**)**
> 
> Steps to reproduce the behavior:
> 
> Step 1 Create one space: define vid length is 120.
> 
> create tag and create one index.(this bug need indexes in space.)
> 
> Step 2 delete vertex 'xxxx'
> 
> xxx length need more than vid length defined.
> 
> the storage will be dead.
> 
> I think we should add one verfication in the follow one line just like the second line:
> 
> one line:
> 
> https://github.com/vesoft-inc/nebula/blob/7a7ab68a0497da8f13e1af7c5ca6b080352202a3/src/storage/mutate/DeleteVerticesProcessor.cpp#L117
> 
> second line:
> 
> https://github.com/vesoft-inc/nebula/blob/7a7ab68a0497da8f13e1af7c5ca6b080352202a3/src/storage/mutate/DeleteVerticesProcessor.cpp#L59

If this worked, can i pull new request for this bug?

**Comment by wey-gu** [comment]
@SuperYoko could you plz take a look at this?

**Comment by SuperYoko** [comment]
Maybe a verify in graph is needed too. Since @Sophie-Xie  has add this to v3.2.0, I think it will be fixed soon. 

(And we have acctually met some crash with vid len check. : D, thanks for your help~)
