### ISSUE TITLE
The Service Crashed when execute http put flags interface.

### ISSUE THREAD

**Issue by Milittle** [vesoft-inc/nebula#4398]
**Describe the bug (__required__)**

When execute the follow command: For graphd and sotraged both have problem.

`curl -X PUT xxx.xxx.xxx.xxx:19559/flags`. this curl command has the empty body.

the service will be crashed.

So I have one solution for this:

Before this line https://github.com/vesoft-inc/nebula/blob/7a7ab68a0497da8f13e1af7c5ca6b080352202a3/src/webservice/SetFlagsHandler.cpp#L42, maybe we should add new verification for the body_, I think we meet the nullptr exception cause the service crashed.

**Comment by wey-gu** [comment]
@xiajingchun is this the one we already know or a new pattern that crashes with WS port?

**Comment by xiajingchun** [comment]
@wey-gu unfortunately this one is not the same. Thanks @Milittle to point it out. We should be able to fix it soon.

**Comment by wey-gu** [comment]
@Milittle would you like to help fix it, one background here is we hopefully to include in 3.2.0 cycle(is about to be released very soon).

**Comment by Milittle** [comment]
> include this in 3.2.0 cycle(is about to be released very soon).

Sure, I will pull new request tonight

**Comment by wey-gu** [comment]
Thank you so much @Milittle!
