### ISSUE TITLE
TTL configured，but vid still can be found after expiration,after compaction looks normal

### ISSUE THREAD

**Issue by shanlai** [vesoft-inc/nebula#4399]
version: 
![image](https://user-images.githubusercontent.com/104358440/178403926-276bf894-930d-439e-b088-05559ef63a4c.png)

**steps**
1. execute ngql: 
```
 CREATE TAG IF NOT EXISTS ttl01 (a timestamp);
 ALTER TAG ttl01 TTL_COL = "a", TTL_DURATION = 60;
 INSERT VERTEX ttl01(a) VALUES "ttl01_01":(now());
 match (v:ttl01) return v limit 1;
 submit job compact
 match (v:ttl01) return v limit 1;
```
Execution plan of nGQL: `match (v:ttl01) return v limit 1;`
![image](https://user-images.githubusercontent.com/104358440/178389475-3d1d2e99-bf95-4a0d-843d-9e00449a2c05.png)

2. The problems found are as follows:
- tag: TTL configured，but vid still can be found after expiration,after compaction looks normal，edge same as tag
<img width="895" alt="image" src="https://user-images.githubusercontent.com/104358440/178388738-75a1afee-22fc-4771-b5ed-4e9c1cb633dc.png">

**Comment by critical27** [comment]
Which version is your kernel? 3.1 enterprise version?

**Comment by shanlai** [comment]
yes 3.1.0-ent

**Comment by HarrisChu** [comment]
for issue 2,  refer https://github.com/vesoft-inc/nebula/issues/3958
we have two times:
* ::time(NULL);
* time::WallClock::fastNowInSec();

`now()` uses the first, and `checkDataExpiredForTTL` uses the second.

how to reduce:

1. start storage
2. change system time, e.g. date -s 04:12:00
3. execute query `insert vertex l1(a) values "101":(now())`

**Comment by critical27** [comment]
> for issue 2, refer #3958 we have two times:
> 
> * ::time(NULL);
> * time::WallClock::fastNowInSec();
> 
> `now()` uses the first, and `checkDataExpiredForTTL` uses the second.
> 
> how to reduce:
> 
> 1. start storage
> 2. change system time, e.g. date -s 04:12:00
> 3. execute query `insert vertex l1(a) values "101":(now())`

👍

**Comment by critical27** [comment]
This need to verified after tagless vertex has been removed. It is expected behavior for the first issue

**Comment by jjsimps** [comment]
How come this was marked as won't fix? I have also encountered this issue. It's rather cumbersome to have to filter out invalid/empty results.

For example, when I iterate over the results, the entry shows up (previous deleted by TTL), but the are no tags associated with it. So when I try to access anything I get errors. Even though I filter specifically on a tag existing.

**Comment by wey-gu** [comment]
> How come this was marked as won't fix? I have also encountered this issue. It's rather cumbersome to have to filter out invalid/empty results.
> 
> For example, when I iterate over the results, the entry shows up (previous deleted by TTL), but the are no tags associated with it. So when I try to access anything I get errors. Even though I filter specifically on a tag existing.

The tagless(bare tag vertex) support will be removed soon, and afterward this issue should be gone(or easier to be handled), right @critical27 ?

**Comment by shanlai** [comment]
After the tagless vertex is removed, if the Vertex has multiple tags, the problem still exists
```
(root@nebula) [nba_ttl]> CREATE SPACE `ttl_test` (partition_num = 100, replica_factor = 1, charset = utf8, collate = utf8_bin, vid_type = FIXED_STRING(32), atomic_edge = false)
Execution succeeded (time spent 3127/17445 us)

Tue, 22 Nov 2022 10:26:03 CST

(root@nebula) [nba_ttl]> use ttl_test
Execution succeeded (time spent 996/14673 us)

Tue, 22 Nov 2022 10:26:13 CST

(root@nebula) [ttl_test]> CREATE TAG IF NOT EXISTS ttl01 (a timestamp);
Execution succeeded (time spent 2504/16683 us)

Tue, 22 Nov 2022 10:27:27 CST

(root@nebula) [ttl_test]>  ALTER TAG ttl01 TTL_COL = "a", TTL_DURATION = 10;
Execution succeeded (time spent 1647/16351 us)

Tue, 22 Nov 2022 10:27:27 CST

(root@nebula) [ttl_test]> CREATE TAG IF NOT EXISTS ttl02 (a timestamp);
Execution succeeded (time spent 2579/19678 us)

Tue, 22 Nov 2022 10:27:28 CST

(root@nebula) [ttl_test]>  INSERT VERTEX ttl02(a) VALUES "ttl01_01":(now());
Execution succeeded (time spent 984/18110 us)

Tue, 22 Nov 2022 10:27:36 CST

(root@nebula) [ttl_test]> INSERT VERTEX ttl01(a) VALUES "ttl01_01":(now());
Execution succeeded (time spent 1215/29407 us)

Tue, 22 Nov 2022 10:27:38 CST

(root@nebula) [ttl_test]> match (v:ttl01) return v limit 1;
+------------------------------------+
| v                                  |
+------------------------------------+
| ("ttl01_01" :ttl02{a: 1669084056}) |
+------------------------------------+
Got 1 rows (time spent 3435/19022 us)

Tue, 22 Nov 2022 10:27:52 CST

```

Cause of the problem: ScanVertices not filtering expired data
![image](https://user-images.githubusercontent.com/104358440/203205601-e1db16fd-e618-42bb-8ea1-86162854e882.png)

**Comment by shanlai** [comment]
fixed in https://github.com/vesoft-inc/nebula-ent/pull/1225
