### ISSUE TITLE
Support displaying online hosts in "SHOW HOSTS" command

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#440]
subtask of #283 

After #425 merged-in,  we create space on real active hosts.  So we expect to show active hosts in "SHOW HOSTS" command, maybe as follows:

```
=============================
|          Ip |  Port | Status |
=============================
| 192.168.8.5 | 65500 | online |
-----------------------
| 192.168.8.1 | 65500 | offline |
-----------------------

```

**Comment by critical27** [comment]
on the fly

**Comment by whitewum** [comment]
@dangleptr  add commands to the nGQL doc pls.

**Comment by whitewum** [comment]
@jude-zhu @Amber1990Zhang can U help to check this command, and add to nGQL doc?

**Comment by Amber1990Zhang** [comment]
> @jude-zhu @Amber1990Zhang can U help to check this command, and add to nGQL doc?

Got it.
