### ISSUE TITLE
submit job compact can be stopped

### ISSUE THREAD

**Issue by Sophie-Xie** [vesoft-inc/nebula#4419]
**Describe the background of the requirement**
- user want to stop the compaction job

**Describe the detail of the requirement**
- just provide a stop command to stop the compaction job

**Describe the scenarios of the requirement**
- the compaction job run a long time and didn't know when it will stop or the compaction affect the performance

from @dbacyj

**Comment by critical27** [comment]
Rocksdb does provide an interface to stop it, it has an `CancelAllBackgroundWork`, but it is used when shutting down.
If we use it as a stop or cancel, upcoming compact will return error like below, even if the server is not shutting down.
```
W20220726 16:00:06.155649 1525392 RocksEngine.cpp:499] CompactAll Failed: Shutdown in progress: Database shutdown
```
