### ISSUE TITLE
Does Nebula Graph support ARM based IOT equipment?

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#442]
I have some ARM based IOT equipments (not x86), such as Raspberry Pi or Edge Computing Controller. And i'd like see if possible to migrate Nebula Graph onto these equipments. 

So Do you have any suggestions?  :-)

**Comment by dutor** [comment]
It might take too long to compile *Nebula* on these boxes, not only *Nebula* itself, but also all it's dependencies.

To fulfill this mission, we could resort to the cross compiling way. But I think this task won't be on our schedule in a short time.

**Comment by darionyaphet** [comment]
It seems could running docker instance on `Raspberry Pi ` . But I haven't tried.

**Comment by whitewum** [comment]
My device is ARM with ubuntu 64bit. Should I rebuild the docker (CPU is quiet different)? or rebuild the source code (how about the depended libraries?)

**Comment by darionyaphet** [comment]
You can install the Docker on your `Raspberry Pi` with command:

`curl -sSL https://get.docker.com | sh`

**Comment by dutor** [comment]
It's definitely a must to rebuild from souce.
