### ISSUE TITLE
The direction of edges queried by nebula console and java client are different

### ISSUE THREAD

**Issue by lanzhoujiaoya** [vesoft-inc/nebula#4423]
![image](https://user-images.githubusercontent.com/31941244/179008778-46907ad0-e8ed-4474-b57c-37eb6040bf6c.png)
![image](https://user-images.githubusercontent.com/31941244/179010819-6505ef7a-4a5a-48d5-a26c-2f5a08e4d3fe.png)
如上图所示，在使用nebula 3.1.0时，使用linux 客户端工具查询的边的方向与通过nebula-java-client 3.0.0查询的边方向不一致

**Comment by wey-gu** [comment]
Thanks for reporting this @lanzhoujiaoya we'll look into this later :)

**Comment by Shylock-Hg** [comment]
It's seems caused by your java code display error, the edge type is negative means it's reverse edge, in short, `src<-dst`.
