### ISSUE TITLE
test_single_shortestpaths3 fails with not found results

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula#4424]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

`E     NotFoundRow: 4: |<("Tim Duncan":bachelor{name:Tim Duncan,speciality:psychology}:player{age:42,name:Tim Duncan})-[:serve@0{end_year:2016,start_year:1997}]->("Spurs":team{name:Spurs})<-[:serve@0{end_year:2019,start_year:2017}]-("Rudy Gay":player{age:32,name:Rudy Gay})-[:serve@0{end_year:2017,start_year:2013}]->("Kings":team{name:Kings})>|`

**Your Environments (__required__)**

* OS: ubuntu 20.04
* Compiler: clang-10
* CPU: `lscpu`
* Commit id: 7981108f509f1e7e5c9134932f6b91fa2c177b9f

**How To Reproduce(__required__)**

1. Step 1
make RM_DIR=false DEBUG=false J=6 tck
or
pytest -k 'test_single_shortestpaths3' .
3. Step 2
4. Step 3

**Expected behavior**

**Additional context**

Not sure whether it's really a bug, or it's just the test results are not deterministic.

**Comment by xtcyclist** [comment]
this turns out to be an expected result. 'match shortestPath()' returns only 1 matching result out of many, the contents of which depend on the execution env. 

thus, the match query in this test case may have multiple valid but different results.

considering changing the test case.

**Comment by czpmango** [comment]
This is cypher's doc [https://neo4j.com/docs/cypher-manual/current/execution-plans/shortestpath-planning/](https://neo4j.com/docs/cypher-manual/current/execution-plans/shortestpath-planning/)

Please test neo4j behavior and align with @nevermore3  the original intention of the implementation.

**Comment by czpmango** [comment]
Fwiw, you can refer to this post to understand the difference between `shortestpath pattern` and `allshortestpath pattern`. 
[Difference between `shortestpath` and `allshortestpaths` in cypher](https://community.neo4j.com/t5/neo4j-graph-platform/what-s-the-difference-between-shortestpath-and-allshortestpaths/m-p/36869)
