### ISSUE TITLE
compaction job  won't fail and keep running in the job management  when one of the nodes stopped  

### ISSUE THREAD

**Issue by henry202108** [vesoft-inc/nebula#4451]
**Please check the FAQ documentation before raising an issue**

When start the compaction job  if one of the nodes stop the job won't fail and will keep running until manally stop.If another job starts,it will be in queue status

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

Linux 192-168-8-191 3.10.0-1160.36.2.el7.x86_64 https://github.com/vesoft-inc/nebula/issues/1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 1

f895632

**How To Reproduce(__required__)**

1. Step 1
start the compaction job
2. Step 2
kill one of the storage services
3. Step 3
the job will not fail and keep running

**Expected behavior**

In the job management,the job should not keep running and fail when one of the nodes stopped

**Additional context**

**Comment by critical27** [comment]
> In the job management,the job should not keep running and fail when one of the nodes stopped

I don't agree:
1. Even if some nodes run the job, it still has meaning, which is not useless.
2. Job Mananger will only run a job in async, it is expected behavior when some nodes failed after the job has started, this is by design.
