### ISSUE TITLE
is 'firstname' or 'user' a reserved keyword in nQGL?

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#447]
it seems that firstname is reserved keyword. 

Got 2 rows (Time spent: 1344/2316 us)
nebula> use shakespeare;
Execution succeeded (Time spent: 521/1779 us)
nebula> create tag xxxxxxxxxx (firstname string)
[ERROR (-7)]: syntax error near `(firstname'
nebula> create tag xxxxxxxxxx(firstname string)
[ERROR (-7)]: syntax error near `xxxxxxxxxx(firstname'
nebula> create tag xxxxxxxxxx (first string)
Execution succeeded (Time spent: 3202/4033 us)
nebula> create tag xxxxxxxxxxx(firstname string)
[ERROR (-7)]: syntax error near `xxxxxxxxxxx(firstname'
nebula> create tag xxxxxxxxxxx (firstname string)    // why syntax error?
[ERROR (-7)]: syntax error near `(firstname'
nebula> create tag xxxxxxxxxxx (firstxxxx string)    // why ok? is firstname a keyword?
Execution succeeded (Time spent: 3012/3988 us)
nebula> create tag xxxxxxxxxxx (firstname1 string)
[ERROR (-8)]: existed!
nebula> create tag xxxxxxxxxxxx (firstname1 string)
Execution succeeded (Time spent: 1442/2082 us)
nebula> create tag xxxxxxxxxxxxx (firstname string)
[ERROR (-7)]: syntax error near `(firstname'
nebula> create tag xxxxxxxxxxxxx (first_name string)
Execution succeeded (Time spent: 1743/2365 us)

**Comment by boshengchen** [comment]
Thanks for your uses . The latest code already supports non-reserved keywords. Please rebase this commit . And feel free to contact me if the problem is still there.
commit Link : 
https://github.com/vesoft-inc/nebula/commit/003b5294663cb868f28cff3e95c7855a35be77af

**Comment by darionyaphet** [comment]
Are you running in `docker`? 

Currently, our docker instance is base on v0.1.0. This PR don't included in it :)
