### ISSUE TITLE
Does Nebula Graph support ACID now？

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula#4506]
I google searched on the website, it says, nebula graph support `C` and `D`, does it support `A` and `I` now? That is ,does nebula graph have full transaction support?

**Comment by wey-gu** [comment]
For now, NebulaGraph doesn't provide transactions of multiple mutations, it was planned for the future though.

There is a configurable option named TOSS(transaction over storage side), which actually enforce the transaction of edge and index mutation(they were written in multiple places).

For now, if really ACID transaction is required in your application, it has to be secured by the application itself :).

**Comment by bithw1** [comment]
Thanks @wey-gu for the helpful answer,understood!
