### ISSUE TITLE
Does Nebula Grapsh storage use KV store

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula#4508]
Hi,

I am reading at https://docs.nebula-graph.com.cn/3.2.0/1.introduction/3.nebula-graph-architecture/4.storage-service/,

it says Nabula Graph is using `自研` KV store.

Somewhere, I heared that Nebula Graph is using HBase or RocksDB, so I want to ask for a clarification, thanks!

**Comment by wey-gu** [comment]
> Hi,
> 
> I am reading at https://docs.nebula-graph.com.cn/3.2.0/1.introduction/3.nebula-graph-architecture/4.storage-service/,
> 
> it says Nabula Graph is using `自研` KV store.
> 
> Somewhere, I heared that Nebula Graph is using HBase or RocksDB, so I want to ask for a clarification, thanks!

NebulaGraph Storage is an in-house thing based on RocksDB, where the raft layer and meta are all created from scratch :).

https://github.com/vesoft-inc/nebula/tree/master/src/storage

**Comment by bithw1** [comment]
> NebulaGraph Storage is an in-house thing based on RocksDB, where the raft layer and meta are all created from scratch :).
> 
> https://github.com/vesoft-inc/nebula/tree/master/src/storage
> 
> PS. Years before we used to support both HBase and RocksDB, then we decided to drop HBase support at some time years ago.

Thanks @wey-gu for the clarification!
