### ISSUE TITLE
Is there benchmark report for bulk loading data into Nebula Graph?

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula#4514]
Hi,

It looks to me that there are serveral options to do bulk load data into nebula graph, such as, importer, exchanger ,spark connector, Java/Go client.

I would ask if there is benchmark report for bulk loading data into Nebula Graph? Eg, how long does it take to load 10 million vertices and 100 million edges into nebula?

**Comment by wey-gu** [comment]
Regarding there diffs, you could read the [docs](https://docs.nebula-graph.com.cn/3.2.0/20.appendix/write-tools/) or [this](https://www.siwei.io/sketches/nebula-data-import-options/).

Regarding benchmark, it depends on the spec and schema/prop of v/e, nebulaGraph's writing performance is one of its advantages, you could benchmark it with https://github.com/vesoft-inc/nebula-bench/ , too.

In nebulagraph Chinese forum or blog(en, cn), many users shared their bulk writing perf result, i.e. the article shared last night: https://mp.weixin.qq.com/s/QCVS6cq1dxg6G9PvuRAnig , OPPO shared their result: 1B v, 10B e to be imported in less than 10h.

> 1、图数据库性能大幅度提升：NebulaGraph 能够支持 10 亿节点 100 亿边的大规模图谱，全量导入时间也不超过 10h，二度查询平均响应时间不超过 50ms，QPS 能够达到 5000+。
