### ISSUE TITLE
Is 'date' a reserved keyword?

### ISSUE THREAD

**Issue by back-to-eat** [vesoft-inc/nebula#452]
nebula> create tag sign_in_date(date date)
[ERROR (-7)]: syntax error near `date'      \\Note: syntax error near 'date'
nebula> create tag sign_in_date(date datetime)
[ERROR (-7)]: syntax error near `datetime'

**Comment by boshengchen** [comment]
Yes,  The `date` is a reserved keyword.

**Comment by back-to-eat** [comment]
Then how do I create a date tag?

boshengchen <notifications@github.com> 于2019年5月28日周二 下午4:19写道：

**Comment by boshengchen** [comment]
Thanks for your trial @back-to-eat 
I am sorry for my previous negligence . `Date` and `Datetime` types are not supported in the alpha release yet . Does the `timestamp` type meet your needs？
for example : ` CREATE TAG tag_name(col_name timestamp) `
