### ISSUE TITLE
Error when inserting data into graph database

### ISSUE THREAD

**Issue by daveewang** [vesoft-inc/nebula#4521]
**Storage Error: More than one request trying to add/update/delete one edge/vertex at he same time**., sql: [  UPSERT EDGE ON self_related "9c8838cbd1b17697" -> "03024448505_b" SET     create_datetime =         case create_datetime             when null                 then timestamp()             else                create_datetime         end ,     update_cnt =         case update_cnt             when null                 then 0             else case when relation_type != "blacklist_update"                 then update_cnt  1             else                 update_cnt         end end ,     update_datetime =         case update_datetime             when null                 then timestamp()             else case when relation_type != "blackist_update"                 then timestamp()             else                 update_datetime         end end ,         relation_type = "blacklist_update"]

**Comment by critical27** [comment]
It is almost literally the error messages say: if two write of same key is executed, one of it will report error.

**Comment by daveewang** [comment]
> It is almost literally the error messages say: if two write of same key is executed, one of it will report error.

how to solve it？or have one way to ensure many write execute successfully.

**Comment by critical27** [comment]
You could retry the UPSERT query if encounter this error.

**Comment by Sophie-Xie** [comment]
Discuss it offline: add some information to the document.

**Comment by abby-cyber** [comment]
> **Storage Error: More than one request trying to add/update/delete one edge/vertex at he same time**.

https://github.com/vesoft-inc/nebula-docs-cn/pull/2103
