### ISSUE TITLE
Must I add some properties to an edge?

### ISSUE THREAD

**Issue by back-to-eat** [vesoft-inc/nebula#453]
nebula> create edge love()
Execution succeeded (Time spent: 1659/2388 us)
nebula> insert edge love() values 001 -> 002
[ERROR (-7)]: syntax error near `love()'

I can create an edge without any properties but can't insert it, note the "syntax error near love'.
If I can create one but why can't use??

**Comment by sherman-the-tank** [comment]
This is definitely a bug. Thanks for finding this @back-to-eat

**Comment by laura-ding** [comment]
The same as the 1 of #436. So close it.
