### ISSUE TITLE
alter drop tag some properties, then add back, old tag properties data exists

### ISSUE THREAD

**Issue by Duanexiao** [vesoft-inc/nebula#4530]
service starts by docker compose, https://github.com/vesoft-inc/nebula-docker-compose.git
version: 2022.06.26:nightly

this occurs too when I update to the latest version release-3.2

**Comment by Sophie-Xie** [comment]
Thanks.
Discuss it offline: we will fix it in next major version.

**Comment by HarrisChu** [comment]
we would forbidden to add the original property
