### ISSUE TITLE
A compound sentences bug: "console> use spaceid; show tags; "

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#456]
nebula>  use myspace_test; show tags;     //ERROR
Please choose a graph space with `USE spaceName' firstly 

nebula>  use myspace_test;                       // use space first;                                                                                                         Execution succeeded (Time spent: 158/925 us)                                                                                                                             nebula>  use myspace_test; show tags;      // then this compound sentence is ok                                                                                                                              ==============                                                                                                                                                           |       Name |

**Comment by laura-ding** [comment]
I will fix it

**Comment by laura-ding** [comment]
When multi sentences input, the code first to do prepare() , if the handler of prepare() dependence previous command result，prepare() will fail. so the prepare() cannot handle depends on the Previous command result. So move the handler to execute()
