### ISSUE TITLE
Storaged crashes due to accessing non-existent property

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4565]
**Describe the bug (__required__)**
Storaged crashes due to accessing non-existent property.

**Environments (__required__)**
nebula 3.2

**How To Reproduce(__required__)**
```
(root@nebula) [test]> create tag V(id int, name string)
Execution succeeded (time spent 1493/1783 us)

(root@nebula) [test]> desc tag V
+--------+----------+-------+---------+---------+
| Field  | Type     | Null  | Default | Comment |
+--------+----------+-------+---------+---------+
| "id"   | "int64"  | "YES" |         |         |
| "name" | "string" | "YES" |         |         |
+--------+----------+-------+---------+---------+
Got 2 rows (time spent 1298/1659 us)

(root@nebula) [test]> CREATE tag index v_id_index on V(id)
Execution succeeded (time spent 1493/1783 us)

(root@nebula) [test]> match (v:V{idx:1})-[]->() return v
+---+
| v |
+---+
+---+
Empty set (time spent 4459/4757 us)

(root@nebula) [test]> rebuild tag index v_id_index
+------------+
| New Job Id |
+------------+
| 16         |
+------------+
Got 1 rows (time spent 1529/1848 us)

(root@nebula) [test]> match (v:V{idx:1})-[]->() return v
[ERROR (-1005)]: Storage Error: part: 11, error: E_RPC_FAILURE(-3).

```

**Expected behavior**
Not crash.

**Comment by critical27** [comment]
Which version do you use? 3.2 community version do not reproduce. I am sure that ent version has this problem because there is an extra filter push down rule called `PushFilterDownAppendVerticesRule`.

**Comment by czpmango** [comment]
I reproduced that on commit `a2de29784`.
I only considered the `first step filter` of the `traverse` node and the `filter` of the `AppendVertices`. Will there be other scenarios to break the test?

**Comment by critical27** [comment]
I'll try it, sync later

**Comment by critical27** [comment]
I can't reproduce with the commit you mentioned. But something must go wrong here, there is a filter in the explained plan, but when storage receive the GetNeighbors request, there is no filter at all.
```
(root@nebula) [nba]> explain match (v:player{invalid_property:1})-[]->() return v
Execution succeeded (time spent 2046/2843 us)

Execution Plan (optimize time 611 us)

-----+----------------+--------------+----------------+----------------------------------------------
| id | name           | dependencies | profiling data | operator info                               |
-----+----------------+--------------+----------------+----------------------------------------------
|  6 | Project        | 5            |                | outputVar: {                                |
|    |                |              |                |   "colNames": [                             |
|    |                |              |                |     "v"                                     |
|    |                |              |                |   ],                                        |
|    |                |              |                |   "name": "__Project_6",                    |
|    |                |              |                |   "type": "DATASET"                         |
|    |                |              |                | }                                           |
|    |                |              |                | inputVar: __Project_5                       |
|    |                |              |                | columns: [                                  |
|    |                |              |                |   "$v"                                      |
|    |                |              |                | ]                                           |
-----+----------------+--------------+----------------+----------------------------------------------
|  5 | Project        | 4            |                | outputVar: {                                |
|    |                |              |                |   "colNames": [                             |
|    |                |              |                |     "v"                                     |
|    |                |              |                |   ],                                        |
|    |                |              |                |   "name": "__Project_5",                    |
|    |                |              |                |   "type": "DATASET"                         |
|    |                |              |                | }                                           |
|    |                |              |                | inputVar: __AppendVertices_4                |
|    |                |              |                | columns: [                                  |
|    |                |              |                |   "$-.v AS v"                               |
|    |                |              |                | ]                                           |
-----+----------------+--------------+----------------+----------------------------------------------
|  4 | AppendVertices | 3            |                | outputVar: {                                |
|    |                |              |                |   "colNames": [                             |
|    |                |              |                |     "v",                                    |
|    |                |              |                |     "__VAR_1",                              |
|    |                |              |                |     "__VAR_0"                               |
|    |                |              |                |   ],                                        |
|    |                |              |                |   "name": "__AppendVertices_4",             |
|    |                |              |                |   "type": "DATASET"                         |
|    |                |              |                | }                                           |
|    |                |              |                | inputVar: __Traverse_3                      |
|    |                |              |                | space: 4                                    |
|    |                |              |                | dedup: true                                 |
|    |                |              |                | limit: -1                                   |
|    |                |              |                | filter:                                     |
|    |                |              |                | orderBy: []                                 |
|    |                |              |                | src: none_direct_dst($-.__VAR_1)            |
|    |                |              |                | props: [                                    |
|    |                |              |                |   {                                         |
|    |                |              |                |     "tagId": 6,                             |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ]                                       |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "age",                                |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ],                                      |
|    |                |              |                |     "tagId": 5                              |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "speciality",                         |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ],                                      |
|    |                |              |                |     "tagId": 7                              |
|    |                |              |                |   }                                         |
|    |                |              |                | ]                                           |
|    |                |              |                | exprs:                                      |
|    |                |              |                | vertex_filter:                              |
|    |                |              |                | if_track_previous_path: true                |
-----+----------------+--------------+----------------+----------------------------------------------
|  3 | Traverse       | 7            |                | outputVar: {                                |
|    |                |              |                |   "colNames": [                             |
|    |                |              |                |     "v",                                    |
|    |                |              |                |     "__VAR_1"                               |
|    |                |              |                |   ],                                        |
|    |                |              |                |   "name": "__Traverse_3",                   |
|    |                |              |                |   "type": "DATASET"                         |
|    |                |              |                | }                                           |
|    |                |              |                | inputVar: __IndexScan_1                     |
|    |                |              |                | space: 4                                    |
|    |                |              |                | dedup: true                                 |
|    |                |              |                | limit: -1                                   |
|    |                |              |                | filter:                                     |
|    |                |              |                | orderBy: []                                 |
|    |                |              |                | src: $_vid                                  |
|    |                |              |                | edgeTypes: []                               |
|    |                |              |                | edgeDirection: OUT_EDGE                     |
|    |                |              |                | vertexProps: [                              |
|    |                |              |                |   {                                         |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ],                                      |
|    |                |              |                |     "tagId": 6                              |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "age",                                |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ],                                      |
|    |                |              |                |     "tagId": 5                              |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "tagId": 7,                             |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "name",                               |
|    |                |              |                |       "speciality",                         |
|    |                |              |                |       "_tag"                                |
|    |                |              |                |     ]                                       |
|    |                |              |                |   }                                         |
|    |                |              |                | ]                                           |
|    |                |              |                | edgeProps: [                                |
|    |                |              |                |   {                                         |
|    |                |              |                |     "type": 10,                             |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "_dst",                               |
|    |                |              |                |       "_rank",                              |
|    |                |              |                |       "_type",                              |
|    |                |              |                |       "_src"                                |
|    |                |              |                |     ]                                       |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "type": 8,                              |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "_dst",                               |
|    |                |              |                |       "_rank",                              |
|    |                |              |                |       "_type",                              |
|    |                |              |                |       "_src"                                |
|    |                |              |                |     ]                                       |
|    |                |              |                |   },                                        |
|    |                |              |                |   {                                         |
|    |                |              |                |     "props": [                              |
|    |                |              |                |       "_dst",                               |
|    |                |              |                |       "_rank",                              |
|    |                |              |                |       "_type",                              |
|    |                |              |                |       "_src"                                |
|    |                |              |                |     ],                                      |
|    |                |              |                |     "type": 9                               |
|    |                |              |                |   }                                         |
|    |                |              |                | ]                                           |
|    |                |              |                | statProps:                                  |
|    |                |              |                | exprs:                                      |
|    |                |              |                | random: false                               |
|    |                |              |                | steps:                                      |
|    |                |              |                | vertex filter: (player.invalid_property==1) |
|    |                |              |                | edge filter:                                |
|    |                |              |                | if_track_previous_path: false               |
|    |                |              |                | first step filter:                          |
-----+----------------+--------------+----------------+----------------------------------------------
|  7 | IndexScan      | 2            |                | outputVar: {                                |
|    |                |              |                |   "colNames": [                             |
|    |                |              |                |     "_vid"                                  |
|    |                |              |                |   ],                                        |
|    |                |              |                |   "type": "DATASET",                        |
|    |                |              |                |   "name": "__IndexScan_1"                   |
|    |                |              |                | }                                           |
|    |                |              |                | inputVar:                                   |
|    |                |              |                | space: 4                                    |
|    |                |              |                | dedup: false                                |
|    |                |              |                | limit: 9223372036854775807                  |
|    |                |              |                | filter:                                     |
|    |                |              |                | orderBy: []                                 |
|    |                |              |                | schemaId: 5                                 |
|    |                |              |                | isEdge: false                               |
|    |                |              |                | returnCols: [                               |
|    |                |              |                |   "_vid"                                    |
|    |                |              |                | ]                                           |
|    |                |              |                | indexCtx: [                                 |
|    |                |              |                |   {                                         |
|    |                |              |                |     "columnHints": [],                      |
|    |                |              |                |     "filter": "",                           |
|    |                |              |                |     "index_id": 11                          |
|    |                |              |                |   }                                         |
|    |                |              |                | ]                                           |
-----+----------------+--------------+----------------+----------------------------------------------
|  2 | Start          |              |                | outputVar: {                                |
|    |                |              |                |   "colNames": [],                           |
|    |                |              |                |   "type": "DATASET",                        |
|    |                |              |                |   "name": "__Start_2"                       |
|    |                |              |                | }                                           |
-----+----------------+--------------+----------------+----------------------------------------------
```

**Comment by critical27** [comment]
Any special flags in graph?

**Comment by Shylock-Hg** [comment]
> I can't reproduce with the commit you mentioned. But something must go wrong here, there is a filter in the explained plan `vertex filter: (player.invalid_property==1)`, but when storage receive the GetNeighbors request, there is no filter at all. And if the storage receives the filter, it indeed will crash.
> 
> ```
> (root@nebula) [nba]> explain match (v:player{invalid_property:1})-[]->() return v
> Execution succeeded (time spent 2046/2843 us)
> 
> Execution Plan (optimize time 611 us)
> 
> -----+----------------+--------------+----------------+----------------------------------------------
> | id | name           | dependencies | profiling data | operator info                               |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  6 | Project        | 5            |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [                             |
> |    |                |              |                |     "v"                                     |
> |    |                |              |                |   ],                                        |
> |    |                |              |                |   "name": "__Project_6",                    |
> |    |                |              |                |   "type": "DATASET"                         |
> |    |                |              |                | }                                           |
> |    |                |              |                | inputVar: __Project_5                       |
> |    |                |              |                | columns: [                                  |
> |    |                |              |                |   "$v"                                      |
> |    |                |              |                | ]                                           |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  5 | Project        | 4            |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [                             |
> |    |                |              |                |     "v"                                     |
> |    |                |              |                |   ],                                        |
> |    |                |              |                |   "name": "__Project_5",                    |
> |    |                |              |                |   "type": "DATASET"                         |
> |    |                |              |                | }                                           |
> |    |                |              |                | inputVar: __AppendVertices_4                |
> |    |                |              |                | columns: [                                  |
> |    |                |              |                |   "$-.v AS v"                               |
> |    |                |              |                | ]                                           |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  4 | AppendVertices | 3            |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [                             |
> |    |                |              |                |     "v",                                    |
> |    |                |              |                |     "__VAR_1",                              |
> |    |                |              |                |     "__VAR_0"                               |
> |    |                |              |                |   ],                                        |
> |    |                |              |                |   "name": "__AppendVertices_4",             |
> |    |                |              |                |   "type": "DATASET"                         |
> |    |                |              |                | }                                           |
> |    |                |              |                | inputVar: __Traverse_3                      |
> |    |                |              |                | space: 4                                    |
> |    |                |              |                | dedup: true                                 |
> |    |                |              |                | limit: -1                                   |
> |    |                |              |                | filter:                                     |
> |    |                |              |                | orderBy: []                                 |
> |    |                |              |                | src: none_direct_dst($-.__VAR_1)            |
> |    |                |              |                | props: [                                    |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "tagId": 6,                             |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ]                                       |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "age",                                |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ],                                      |
> |    |                |              |                |     "tagId": 5                              |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "speciality",                         |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ],                                      |
> |    |                |              |                |     "tagId": 7                              |
> |    |                |              |                |   }                                         |
> |    |                |              |                | ]                                           |
> |    |                |              |                | exprs:                                      |
> |    |                |              |                | vertex_filter:                              |
> |    |                |              |                | if_track_previous_path: true                |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  3 | Traverse       | 7            |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [                             |
> |    |                |              |                |     "v",                                    |
> |    |                |              |                |     "__VAR_1"                               |
> |    |                |              |                |   ],                                        |
> |    |                |              |                |   "name": "__Traverse_3",                   |
> |    |                |              |                |   "type": "DATASET"                         |
> |    |                |              |                | }                                           |
> |    |                |              |                | inputVar: __IndexScan_1                     |
> |    |                |              |                | space: 4                                    |
> |    |                |              |                | dedup: true                                 |
> |    |                |              |                | limit: -1                                   |
> |    |                |              |                | filter:                                     |
> |    |                |              |                | orderBy: []                                 |
> |    |                |              |                | src: $_vid                                  |
> |    |                |              |                | edgeTypes: []                               |
> |    |                |              |                | edgeDirection: OUT_EDGE                     |
> |    |                |              |                | vertexProps: [                              |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ],                                      |
> |    |                |              |                |     "tagId": 6                              |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "age",                                |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ],                                      |
> |    |                |              |                |     "tagId": 5                              |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "tagId": 7,                             |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "name",                               |
> |    |                |              |                |       "speciality",                         |
> |    |                |              |                |       "_tag"                                |
> |    |                |              |                |     ]                                       |
> |    |                |              |                |   }                                         |
> |    |                |              |                | ]                                           |
> |    |                |              |                | edgeProps: [                                |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "type": 10,                             |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "_dst",                               |
> |    |                |              |                |       "_rank",                              |
> |    |                |              |                |       "_type",                              |
> |    |                |              |                |       "_src"                                |
> |    |                |              |                |     ]                                       |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "type": 8,                              |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "_dst",                               |
> |    |                |              |                |       "_rank",                              |
> |    |                |              |                |       "_type",                              |
> |    |                |              |                |       "_src"                                |
> |    |                |              |                |     ]                                       |
> |    |                |              |                |   },                                        |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "props": [                              |
> |    |                |              |                |       "_dst",                               |
> |    |                |              |                |       "_rank",                              |
> |    |                |              |                |       "_type",                              |
> |    |                |              |                |       "_src"                                |
> |    |                |              |                |     ],                                      |
> |    |                |              |                |     "type": 9                               |
> |    |                |              |                |   }                                         |
> |    |                |              |                | ]                                           |
> |    |                |              |                | statProps:                                  |
> |    |                |              |                | exprs:                                      |
> |    |                |              |                | random: false                               |
> |    |                |              |                | steps:                                      |
> |    |                |              |                | vertex filter: (player.invalid_property==1) |
> |    |                |              |                | edge filter:                                |
> |    |                |              |                | if_track_previous_path: false               |
> |    |                |              |                | first step filter:                          |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  7 | IndexScan      | 2            |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [                             |
> |    |                |              |                |     "_vid"                                  |
> |    |                |              |                |   ],                                        |
> |    |                |              |                |   "type": "DATASET",                        |
> |    |                |              |                |   "name": "__IndexScan_1"                   |
> |    |                |              |                | }                                           |
> |    |                |              |                | inputVar:                                   |
> |    |                |              |                | space: 4                                    |
> |    |                |              |                | dedup: false                                |
> |    |                |              |                | limit: 9223372036854775807                  |
> |    |                |              |                | filter:                                     |
> |    |                |              |                | orderBy: []                                 |
> |    |                |              |                | schemaId: 5                                 |
> |    |                |              |                | isEdge: false                               |
> |    |                |              |                | returnCols: [                               |
> |    |                |              |                |   "_vid"                                    |
> |    |                |              |                | ]                                           |
> |    |                |              |                | indexCtx: [                                 |
> |    |                |              |                |   {                                         |
> |    |                |              |                |     "columnHints": [],                      |
> |    |                |              |                |     "filter": "",                           |
> |    |                |              |                |     "index_id": 11                          |
> |    |                |              |                |   }                                         |
> |    |                |              |                | ]                                           |
> -----+----------------+--------------+----------------+----------------------------------------------
> |  2 | Start          |              |                | outputVar: {                                |
> |    |                |              |                |   "colNames": [],                           |
> |    |                |              |                |   "type": "DATASET",                        |
> |    |                |              |                |   "name": "__Start_2"                       |
> |    |                |              |                | }                                           |
> -----+----------------+--------------+----------------+----------------------------------------------
> ```

The field `vertex filter` will not push down to storage.

**Comment by critical27** [comment]
@Shylock-Hg My bad, my optimizer is not turned on. If I turned on, `first step filter` will be pushed down

**Comment by czpmango** [comment]
> @Shylock-Hg My bad, my optimizer is not turned on. If I turned on, `first step filter` will be pushed down

Yep.

**Comment by czpmango** [comment]
All issues have been fixed. Closed.
