### ISSUE TITLE
Support "create index" interface in storage layer

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#458]
Subtask #71 

After receiving the command,  storage will record current timestamp,  and auto-generate index when inserting edges/vertexes.  Meanwhile start a background thread to build index for old data.

**Comment by darionyaphet** [comment]
**Index Key Structure :** 

`SpaceID` + `Type` + `IndexID` + `index-values` + `RowKey`

`SpaceID` and `Type` are use to avoid naming conflict.

Using `IndexID` could save some space and it's fixed size.

Should I save `index` in another `ColumnFamily` ?

I'm  afraid the index key will same with another data's key, although the possibility is very small.

**Comment by dangleptr** [comment]
What's the type meaning?

**Comment by boshengchen** [comment]
I have some questions as below ：
1 . ` index(col1, col2) `is equal to` index(col1) + index(col2)` ?  I mean，a index(col1, col2) exists. I want to filter col2 by where clause , whether a new index(col2) needs to be created?
2.  What is the purpose of RowKey？ Is it used to remove edges and vertexes? Or just for key unique?

**Comment by darionyaphet** [comment]
`type` is use to explain the index is on `vertex` or `edge`. It should be very small.

This's use to support prefix scan for `show tag indexes` and `show edge indexes`.

**Comment by darionyaphet** [comment]
`index(col1, col2)` and `index(col1) + index(col2)` are not equipment .

`index(col1, col2)` could support `col1` and `col1+col2`. This is same with `MySQL`

**Comment by darionyaphet** [comment]
Because using `Index ID` to replace the `Index Name` , `type` is useless .

**Comment by dangleptr** [comment]
> SpaceID + IndexID + index-values + RowKey
 * SpaceId is useless,  because each rocksdb instance belongs to one space.
 * We should use a prefix to indicate this is index key.  For example, use  "_i"  as prefix.

**Comment by darionyaphet** [comment]
Because we append `RowKey` at the end of `IndexKey`, it must not be duplicated.

Is there any use for prefix ?

**Comment by dangleptr** [comment]
Example1:
the index key on Tag1, col1 
**"_i" + Tag1 + Col1 + value + vertexId**
To support "find vertexId where tag1.col1 > 10"

Example2:
index key on Tag1-col1, tag2-col2:
**"_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId**
To support "find vertexId where tag1.col1 > 10 && tag2.col2 > 20"

**Comment by dangleptr** [comment]
Any thoughts about the key design?  @darionyaphet @boshengchen @sherman-the-tank

**Comment by boshengchen** [comment]
Looks good for above design，I have some questions:
1,  How to find the index `rowkey` when want to delete an edge or a vertex? 
2, Instead of `Tag1 or Col1` to `tagID or ColID` is better？because the ID is a fixed length.
3, How do you distribute index data to different parts without PartId?

**Comment by boshengchen** [comment]
Also，We need to consider dropping indexes， So could we change the index key to below ? :
"_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId

**Comment by dangleptr** [comment]
> Also，We need to consider dropping indexes， So could we change the index key to below ? :
> "_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId

How to reuse the index if where condition is only "tag1.col1 > 10"

**Comment by sherman-the-tank** [comment]
@boshengchen I really like your thinking about the compound index across multiple tags. I agree we should design the index with this feature in mind, even though we might not support it in the first release.

**Comment by sherman-the-tank** [comment]
> > Also，We need to consider dropping indexes， So could we change the index key to below ? :
> > "_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId
> 
> How to reuse the index if where condition is only "tag1.col1 > 10"

As long as the condition is the prefix of the index, the index can always be used. That's the nature of the compound index

**Comment by boshengchen** [comment]
> > > Also，We need to consider dropping indexes， So could we change the index key to below ? :
> > > "_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId
> > 
> > 
> > How to reuse the index if where condition is only "tag1.col1 > 10"
> 
> As long as the condition is the prefix of the index, the index can always be used. That's the nature of the compound index

We need to traverse the index metadata in the meta client cache before query is sent to the storage layer. So we can assemble a complete key via index metadata. for example ::
`"tag1.col1 > 10"` : the key should be `"_i" + Tag1 + Col1 + Tag2 + Col2 + value1`
In addition, it is possible to have a situation where a column exists in a different index. such as `index1(tag1.col1, tag1.col2)` and `index2(tag1.col1, tag1.col3)`. if where condition is only `"tag1.col1 > 10"` . We need to use index metadata to choose one of two existing indexes.

**Comment by dangleptr** [comment]
> "_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId

If so,  i suggest we use one indexID to represent Tag1 + Col1 + Tag2 + Col2 ,  and query engine should pass the indexID and query conditions combined to storage layer.  So we could use the exact index without query meta server any more on storage server.

**Comment by darionyaphet** [comment]
Do you really need to support index on multiple tags ? 

It's similar with create an index on different table.   This belongs to the design of table structure.

**Comment by dangleptr** [comment]
> Do you really need to support index on multiple tags ?
> 
> It's similar with create an index on different table. This belongs to the design of table structure.

The key design could be used for index on multi tags if needed.

**Comment by sherman-the-tank** [comment]
> Do you really need to support index on multiple tags ?
> 
> It's similar with create an index on different table. This belongs to the design of table structure.

We probably don't support indices across multiple tags in this release, but some point in the future we might want to support it. We don't want to change the key format when that happens

**Comment by sherman-the-tank** [comment]
> > > > Also，We need to consider dropping indexes， So could we change the index key to below ? :
> > > > "_i" + Tag1 + Col1 + Tag2 + Col2 + value1 + value2 + vertexId
> > > 
> > > 
> > > How to reuse the index if where condition is only "tag1.col1 > 10"
> > 
> > 
> > As long as the condition is the prefix of the index, the index can always be used. That's the nature of the compound index
> 
> We need to traverse the index metadata in the meta client cache before query is sent to the storage layer. So we can assemble a complete key via index metadata. for example ::
> `"tag1.col1 > 10"` : the key should be `"_i" + Tag1 + Col1 + Tag2 + Col2 + value1`
> In addition, it is possible to have a situation where a column exists in a different index. such as `index1(tag1.col1, tag1.col2)` and `index2(tag1.col1, tag1.col3)`. if where condition is only `"tag1.col1 > 10"` . We need to use index metadata to choose one of two existing indexes.

Very good point. That's exactly what the query planner is supposed to do. @dutor

**Comment by boshengchen** [comment]
According to offline discussion with @dangleptr , The index creation logic is as  below, Please help to review and offer your comments or suggestions，Thanks.

1. Execute create index action in graph layer.
2. Create index meta data in meta layer.
3. Distribute index creation requests to each storage engine in meta layer.
4. process index on each storage part in storage layer.
    4.1. GetSnapshot 
    4.2. Prefix scan tag|edge based snapshot by each part.
    4.3. Get keys in batches. 
    4.4. Assemble index key and value.
    4.5. PutBatch index datas.
    4.6. Cycle process the next batch of data
    4.7. Scan WAL and assemble index key | value by newly data since snapshot. This step requires a configuration parameter to determine if index processing approaches WAL. 
    4.8. 	PutBatch again for newly index datas.
5. Collect Response from each part
6. Return status to meta layer
7. Change the index status to normal if all part of index create success.
8. Return status to graph layer via meta client
9. Done

**Comment by bright-starry-sky** [comment]
Referring to performance issues #1140 . Offline discussion with @dangleptr , We need to rethink index. The conclusion is as below：
1，We need to separate the index space from the data space. And, according to the test,Performance is faster with fewer partitions.
2,  Online rebuild index is temporarily not supported.  Because the prerequisite for this capability is transaction isolation.
3,  Need to consider the storage structure and length of the index column.
