### ISSUE TITLE
Support "create index" interface on meta server

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#459]
Subtask #71 

After receiving the command,   meta server should store the index information on it and record current index state "Progressing/Done/Failed" 

Our users could use "show index" to check the index state and information.

**Comment by sherman-the-tank** [comment]
I would suggest the status are ```REPAIRING, NORMAL, ABNORMAL```

**Comment by darionyaphet** [comment]
What does `ABNORMAL` mean?
