### ISSUE TITLE
There are two GOD roles in one space 

### ISSUE THREAD

**Issue by slimshadylol0303** [vesoft-inc/nebula#4591]
Nebula core version: v3.2.0

1. I login with root user,
2. then create two users `user 2` and `user 3`, 
3. and create a space `test`,
4. and then grant role to them with both `GOD ` in space `test,` . It is obvious illegal, but it succeed in console.
 
`create user user2`
`create user user3`
`CREATE SPACE test(partition_num=15, replica_factor=1, vid_type=fixed_string(30));`
`GRANT ROLE GOD ON test TO user2;`
`GRANT ROLE GOD ON test TO user3;`
`SHOW roles IN test;`
![image](https://user-images.githubusercontent.com/95005615/187332125-afad2882-b775-4008-9b2e-705c6c68d611.png)

**Comment by caton-hpg** [comment]
1）GOD cannot be grant. GOD belongs only to root.
2)  Only `god` and `admin` can execute `create user xxx` and `grant rolexxx`
![image](https://user-images.githubusercontent.com/87342612/187823169-b7cdcde5-8677-4785-9f0b-c23160659592.png)

**Comment by slimshadylol0303** [comment]
> 1）GOD cannot be grant. GOD belongs only to root. 2) Only `god` and `admin` can execute `create user xxx` and `grant rolexxx` ![image](https://user-images.githubusercontent.com/87342612/187823169-b7cdcde5-8677-4785-9f0b-c23160659592.png)

The second one has a little mistake, it should be:
only `god` can execute `create user`, and only `god ` and `admin` can execute `grant role`

**Comment by caton-hpg** [comment]
> 2) Only `god` and `admin` can execute `create user xxx` and `grant rolexxx`

The second one is OK. My config is `--enable_authorize=flase`. It should be true.
