### ISSUE TITLE
dataset is rarely treated as __EMPTY__ in test_nested (tck). can't reproduce for now.

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula#4608]
**Describe the bug (__required__)**

![image](https://user-images.githubusercontent.com/7731943/188050955-9d086425-5441-4327-93b0-65665e4a2e3a.png)

While executing `YIELD 1 AS number INTERSECT YIELD 2 AS number;`, the CI may run into the above error, in which an operand is trated as the Type::__EMPTY__. 

**Your Environments (__required__)**

* OS: Linux nebula-dev-84 5.4.0-122-generic
* Compiler: clang++-14
* CPU: Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
* Commit id: 47383316ab1ee5f5e3bcde934a1a866bbd2452a5

**How To Reproduce(__required__)**

To run the test, `pytest -k "test_nested" .`

But this error rarely happens. It cannot be reproduced for now. It should be a real bug. But now sure where the real problem is.

**Expected behavior**

This query should be executed successfully and return an empty resultset.

**Additional context**

**Comment by Shylock-Hg** [comment]
It's a known bug same with https://github.com/vesoft-inc/nebula/issues/4430

**Comment by Sophie-Xie** [comment]
Maybe fixed in https://github.com/vesoft-inc/nebula/pull/4822 ？

**Comment by xtcyclist** [comment]
This test is skipped by https://github.com/vesoft-inc/nebula/pull/4817 for the CI.

It runs ok offline. Cannot reproduce it. Close this for now.
