### ISSUE TITLE
Nebula 3.2.0 when  "BALANCE DATA"  it returns  "-1009:SemanticError: Data balance not support"

### ISSUE THREAD

**Issue by daidai0235** [vesoft-inc/nebula#4632]
Nebula 3.2.0 when  "BALANCE DATA"  it returns  "-1009:SemanticError: Data balance not support"

**Comment by Milittle** [comment]
> Nebula 3.2.0 when "BALANCE DATA" it returns "-1009:SemanticError: Data balance not support"

you need config one experimental configuration named:  `enable_experimental_feature`
