### ISSUE TITLE
UPDATE EDGE with compare-and-swap (CAS).

### ISSUE THREAD

**Issue by pengdaqian2020** [vesoft-inc/nebula#4637]
**General Question**

I notice that https://docs.nebula-graph.io/3.2.0/3.ngql-guide/13.edge-statements/2.update-edge/ say that 
```
In Nebula Graph, UPDATE EDGE supports compare-and-swap (CAS).
```
But I cannot find any extra info about this, How can I update a edge with CAS

**Comment by wey-gu** [comment]
> **General Question**
> 
> 
> 
> 
> 
> I notice that https://docs.nebula-graph.io/3.2.0/3.ngql-guide/13.edge-statements/2.update-edge/ say that 
> 
> ```
> 
> In Nebula Graph, UPDATE EDGE supports compare-and-swap (CAS).
> 
> ```
> 
> But I cannot find any extra info about this, How can I update a edge with CAS

By adding when clause in update:
`WHEN <condition>`.

**Comment by pengdaqian2020** [comment]
But when I use this like
```
UPDATE EDGE ON like "n:1:1:1" -> "n:1:1:2"
SET modify_time = timestamp(), version = version + 1
WHEN version == 1
```
When the version has been changed by other thread. such as it become 2.
it will not return any response about whether this update is succeed

**Comment by pengdaqian2020** [comment]
I find that I can do this  
```
UPDATE EDGE ON like "n:1:1:1" -> "n:1:1:2"
SET modify_time = timestamp(), version = version + 1
WHEN version == 1
YIELD version
```

**Comment by wey-gu** [comment]
> I find that I can do this
> 
> ```
> UPDATE EDGE ON like "n:1:1:1" -> "n:1:1:2"
> SET modify_time = timestamp(), version = version + 1
> WHEN version == 1
> YIELD version
> ```

Sorry for not checking your follow-up questions on time, yes, we could yield any fields and yield version will do the job 👍🏻
