### ISSUE TITLE
Any plan for rust binding?

### ISSUE THREAD

**Issue by xmoeproject** [vesoft-inc/nebula#4638]
**Is your feature request related to a problem? Please describe.**
My backend is written in Rust. 
Moving to other languages is painful.
Since I'm using Rust, I'd better not ffi with c++.

**Describe the solution you'd like**
Native client for Rust

**Describe alternatives you've considered**
Or pure c client can be a better solution for most scenarios.
Also, both c interface and c abi are considered more friendly for ffi than c++.

**Comment by wey-gu** [comment]
Welcome to the community @xmoeproject !

Now the cpp nebulagraph client is ready(https://github.com/vesoft-inc/nebula-cpp) but for rust clients, we don't have the resource to make it ready now(https://github.com/vesoft-inc/nebula-rust).

Are you interested in helping us build nebula-rust? Else, you could consider use cpp client for ffi first?

BR//Wey

**Comment by xmoeproject** [comment]
> Thanks for your reply! When I'm free, I will consider contributing nebula rust client.
