### ISSUE TITLE
getNeighbors return error

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula#4649]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

```
go from "Tony Parker" over like Where $^.player.age > 37 yield $^ as src

Filter $^.player.age > 37  pushdown to storage
```

getNeighbor's result is 
```
 _vid|_stats|_tag:team:_tag:name|_tag:player:_tag:age:name|_tag:bachelor:_tag:name:speciality|_edge:+like:_dst|_expr|
 "Tony Parker"|__EMPTY__|__EMPTY__|[10,36,"Tony Parker"]|__EMPTY__|__EMPTY__|__EMPTY__|

```

```
go from "Tony Parker" over like Where like.likeness > 100 yield $^ as src

Filter like.likeness>100 pushdown to storage
```

getNeighbor's result is 
```
 _vid|_stats|_tag:team:_tag:name|_tag:player:_tag:age:name|_tag:bachelor:_tag:name:speciality|_edge:+like:_dst|_expr|
 "Tony Parker"|__EMPTY__|__EMPTY__|[10,36,"Tony Parker"]|__EMPTY__|__EMPTY__|__EMPTY__|

```
There will be an error when taking the vertex (should not be return)

Expect
`go from "Tony Parker" over like Where $^.player.age > 36 yield $^ as src`

getNeighbor's result is 
```
 _vid|_stats|_tag:team:_tag:name|_tag:player:_tag:age:name|_tag:bachelor:_tag:name:speciality|_edge:+like:_dst|_expr|

```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by critical27** [comment]
Em... GetNeighbors's filter is designed for edge's filter only at the first time...
```
go from "Tony Parker" over like Where $^.player.age > 37 yield $^ as src
```
We could fix it in storage indeed. But how do we handle an expression when contains both tag and edge?

I think there is a way which won't introduce too much changes: only push down edge's filter...

**Comment by nevermore3** [comment]
Logically, we should distinguish whether the tag is not satisfied the condition or the edge is not satisfied the condition, if the tag is not satisfied return nothing else return a record
