### ISSUE TITLE
When Tag/Edge Type drop properties , prop data will not be deleted after compaction 

### ISSUE THREAD

**Issue by VincentSleepless** [vesoft-inc/nebula#4655]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS:  Aliyun ECS
* Linux data-cdh6-test01 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Compiler: Nope
* CPU: 
* Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               2500.002
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

0. the cluster open rock db auto compaction and stastics

1. Step 1 create tag person with two props name and age
2. Step 2  insert 50w record to tag
3. Step 3  look up  the tag, the query is correct with props
4. Step 4  alter tag person drop prop age;
5. Step 5   look up  the tag, the query is correct with unkown prop age
6. Step 6  compaction the space or wait 2 heart beat for auto compaction
7. Step 7  wait the compaction job succ
8. Step 8  alter ta person recreate prop age with same name /type
9. Step 9  look up the tag , the query is abnormal , the prop age will query previous  prop data;

the disscuss address
https://discuss.nebula-graph.com.cn/t/topic/10222

**Expected behavior**
when alter tage drop prop ,  after data  compaction , the prop data should be cleaned !

**Additional context**

**Comment by Sophie-Xie** [comment]
This issue will be fixed in next major version.

**Comment by critical27** [comment]
If you are familiar with rocksdb's compaction, it only provides keep the kv or drop the kv, you can't change the kv during compaction. 

We will forbid `Step 8 alter ta person recreate prop age with same name /type` in the next version.
