### ISSUE TITLE
Support insert with no index

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#466]
Subtask #71 

In some cases when we insert data in batch, we hope to turn off the index and after that rebuild the index.

**Comment by boshengchen** [comment]
Let's discuss this issue offline,  this issue refer to #458 , It seems that we don't need to record timestamps when this issue is available.

**Comment by sherman-the-tank** [comment]
Good one 👍  This is especially useful when bulk load a big chunk of data
