### ISSUE TITLE
Here is some problem in `MATCH` and `properties`

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#4662]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Executing the following sentence returns the result as `UNKNOWN_PROP`, but the name attribute on the vertex `v` has data.
```
$ MACTH (v:player{age:33}) RETURN properties(v).name
```
![image](https://user-images.githubusercontent.com/35463247/191152837-f8e31525-e09e-4d45-b6fe-6938166b840e.png)

```
$ MACTH (v:player{age:33}) RETURN properties(v)
```
![image](https://user-images.githubusercontent.com/35463247/191153495-f8b2583c-62bb-4e4a-8b9d-067f92a8ad4f.png)

**Your Environments (__required__)**

Studio and NebulaGraph version is 3.1.0.
![image](https://user-images.githubusercontent.com/35463247/191153610-b44a8f67-0a59-4ad2-abe7-a747f8d6ed55.png)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
@foesa-yang nebula 3.1.3 fixed it, pls try.
