### ISSUE TITLE
The timestamp obtained by the time::WallClock::fastNowInSec function becomes inaccurate as the deployment time elapses. 

### ISSUE THREAD

**Issue by flymysql** [vesoft-inc/nebula#4682]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
The timestamp obtained by the time::WallClock::fastNowInSec function becomes inaccurate as the deployment time elapses. The longer the deployment time is, the greater the deviation.
![image](https://user-images.githubusercontent.com/37113068/192450455-c3b9f2ca-848c-4f65-9841-b1aa818163b8.png)

![image](https://user-images.githubusercontent.com/37113068/192450545-e2dbc33a-089b-4e7e-ab76-30692b2f1e90.png)

**For services that have been deployed for two weeks, the timestamp deviation is about 40 seconds.**

The timestamp becomes accurate after the service is restarted.

**Your Environments (__required__)**
- os
```
Linux host-7-219-10-133 3.10.0-862.14.1.1.h224.eulerosv2r7.x86_64 #1 SMP Tue Feb 12 00:00:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- g++
```
g++ (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- lscpu
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz
Stepping:              7
CPU MHz:               3000.000
BogoMIPS:              6000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              30976K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```
- commit id: 2e938c7
* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by flymysql** [comment]
![image](https://user-images.githubusercontent.com/37113068/192452437-3b5bfdbc-984d-4045-98f2-c8b1edb918bb.png)
The variable must be of the double type.But that may not be the point.

**Comment by pengweisong** [comment]
@flymysql Is the `nebula-console `and `graphd` in the same machine?

**Comment by flymysql** [comment]
> in the same machine

in the same machine

**Comment by flymysql** [comment]
> @flymysql Are the `nebula-console `and `graphd` in the same machine? Because the `timestamp()` use `std::time(NULL) `now, instead of `time::WallClock`.

This problem is not only with the timestamp function. I noticed that the data TTL expiration check function also uses the time::WallClock::fastNowInSec function, which causes the data TTL to be out of order after a long time of deployment.
![image](https://user-images.githubusercontent.com/37113068/192464249-308d4d3c-15b4-418a-a976-5c6ee4b0f3ef.png)

**Comment by Sophie-Xie** [comment]
fixed in https://github.com/vesoft-inc/nebula-ent/pull/1380
