### ISSUE TITLE
graph crashed when get subgraph with tag filter

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#4694]
**Describe the bug (__required__)**

as title

**Your Environments (__required__)**
```
nebula-graphd version 3.3.0, Git: d67cc4b, Build Time: Oct  3 2022 12:06:30
This source code is licensed under Apache 2.0 License.
```
**How To Reproduce(__required__)**

Executing the following ngql will cause graph crash：
`GET SUBGRAPH WITH PROP FROM 'Tim Duncan' OUT like WHERE $$.player.age > 36 YIELD vertices as v, edges as e`

![image](https://user-images.githubusercontent.com/104358440/194690194-86631887-5d46-4b44-8cc4-729115247430.png)

I think the problem was introduced by the pr: https://github.com/vesoft-inc/nebula-ent/commit/014df23e660dd1dd8e51a7ec2cafdffc8e250001

**Expected behavior**
successfully executed this ngql

**Comment by jinyingsunny** [comment]
3.3.0 已验证
