### ISSUE TITLE
Grahd crash when the tag pointed to by the edge data does not exist

### ISSUE THREAD

**Issue by abbydev** [vesoft-inc/nebula#4697]
**1，环境描述**
nebula 版本：3.2.0
部署方式：单机
安装方式： RPM
是否为线上版本：N
服务器：CentOs-7.9、4cpu cores、16g

**2，问题描述**
使用match查询时，当存在某一条边数据的结束顶点的tag已被删除(属于脏数据)情况下，graphd crash

**3，必现流程**
- 1）创建tag(t1,t2,t3)，创建edgeType(e1,e2)
- 2）添加数据t1,t2,t3 和 e1,e2，其中e2中有边数据指向t3
- 3）删除t3
- 4）match查询导致graphd crash，以下是我的GQL
```
MATCH p=(v:t1)-[e:e1|e2*0..1]-(v2)
WHERE id(v) IN ['t1/-1756172977717531760']
AND ALL ( n IN nodes(p) 
  WHERE (
  head(labels(n)) IN ['t1','t2']
) 
)
AND ALL(r IN e 
  WHERE 1==1
) 
RETURN [n IN nodes(p) | 
  {
      id_:id(n),
      label_:properties(n).entity_,
      schema_:head(tags(n)),
      readable_:(n.entity_reader_ IS NULL 
          OR n.entity_reader_ == ''
      )
  }
] AS vertexList,
[r IN relationships(p) | 
  {
      id_:properties(r).id_,
      schema_:type(r),
      from_:properties(r).from_,
      to_:properties(r).to_
  }
] AS edgeList
LIMIT 2000;
```

**Comment by jievince** [comment]
> 1）创建tag(t1,t2,t3)，创建edgeType(e1,e2)
2）添加数据t1,t2,t3 和 e1,e2，其中e2中有边数据指向t3
3）删除t3
4）match查询导致graphd crash，以下是我的GQL

这部分可以提供能直接运行的语句吗?
我按你这里写的创建的schema没复现出来.

**Comment by Sophie-Xie** [comment]
Closed it first, if you have some new info, you can open the issue again.
