### ISSUE TITLE
PV can‘t be prepared normally when storageClass is deployed on HUAWEI Cloud

### ISSUE THREAD

**Issue by codingknees** [vesoft-inc/nebula#4713]
**General Question**

按照文档https://docs.nebula-graph.com.cn/3.2.1/nebula-operator/3.deploy-nebula-graph-cluster/3.2create-cluster-with-helm/ 在华为云集群上进行安装。替换scName=csi-disk，安装过程卡在metad进程启动阶段。pod状态一直处于pending：
```
NAME             READY   STATUS    RESTARTS   AGE
nebula-metad-0   0/1     Pending   0          63m
nebula-metad-1   0/1     Pending   0          63m
nebula-metad-2   0/1     Pending   0          63m
```
describe 相应pod提示
```
Events:
  Type     Reason             Age                 From                Message
  ----     ------             ----                ----                -------
  Warning  FailedScheduling   52m                 default-scheduler   0/28 nodes are available: 28 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling   52m                 default-scheduler   0/28 nodes are available: 28 pod has unbound immediate PersistentVolumeClaims.
  Normal   NotTriggerScaleUp  2s (x311 over 51m)  cluster-autoscaler  pod didn't trigger scale-up: 1 max node group size reached
```
猜测是sc无法正确地申请到pv导致的。对比以前以sc方式成功制备pv并且启动的statefulset服务，猜测可能是由于volumeClaimTemplates段缺少一些annotation和label导致的：
<img width="501" alt="image" src="https://user-images.githubusercontent.com/61698098/195035854-6acb72a7-02e9-4760-aa2d-f57f541bdf36.png">

请问，有办法可以在nebulaclusters.apps.nebula-graph.io资源中给volumeClaimTemplates指定相应的label和annotation吗？

另外，我们对资源申请管控比较严格，可不可以支持使用非动态制备的方式创建集群？即，直接创建pvc，创建各个实例对象，待运维人员配置好需要的pv之后，完成绑定，集群启动。

**Comment by MegaByte875** [comment]
@codingknees  You can create a pvc with the annotations and labels to verify the problem caused by configuration lost, nebula-operator doesn't supports configure DataVolumeClaim with annotations and labels now.

**Comment by codingknees** [comment]
> @codingknees You can create a pvc with the annotations and labels to verify the problem caused by configuration lost, nebula-operator doesn't supports configure DataVolumeClaim with annotations and labels now.

直接手动创建pvc吗？然后operator这里怎么配置使用这个pvc呢？

**Comment by codingknees** [comment]
我知道到一种办法，是华为云提供的文档：
https://support.huaweicloud.com/intl/zh-cn/usermanual-cce/cce_10_0380.html
做法就是，在华为云提供的provisioner的基础上，包装一个带annotation的sc，然后使用这个sc时，就不需要再带annotation了。
