### ISSUE TITLE
Implement config manager 

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#473]
Just like SchemaManager/PartManager,  we need a ConfigManager to manage all configs for current cluster. 

Please upload your design document here.  @critical27

**Comment by sherman-the-tank** [comment]
Here are some requirements

1. This meant to replace any gflag that might be modified during the runtime. Going forward, the rule is using gflags for any start-up configuration and those configurations should never be changed during the runtime; using CM for any configuration that could be changed during the runtime

1. All configuration in CM should be persisted on the Meta Server and can be restored during the daemon start-up time

1. CM should be as easy as gflags regarding the reading interface

1. The configuration in CM should always affect all hosts in the cluster. *Whether to support only modifying the configuration on one host is a open question

**Comment by critical27** [comment]
Let us look into config key pattern: 
table_prefix + global_flag/spaceId + len(module) + module + len(name) + name + config_type.

With global_flag or spaceId, we can save configuration of different spaces, and "module" is something like "storage" or "graph" to distinguish configurations of same name.

As to config value, I think config_type and value will be enough.

**Comment by critical27** [comment]
Besides, @dangleptr suggests that maybe we can support a level of hosts to support set configuration for one host later. The priority will be host > space > global.

Also, maybe we need a local_mode in config manager to support use configurations of local file for debugging.

**Comment by dangleptr** [comment]
> Besides, @dangleptr suggests that maybe we can support a level of hosts to support set configuration for one host later. The priority will be host > space > global.
> 
> Also, maybe we need a local_mode in config manager to support use configurations of local file for debugging.

If you have host level configurations on meta server,  local_mode is needless.

**Comment by dangleptr** [comment]
> Let us look into config key pattern:
> table_prefix + global_flag/spaceId + len(module) + module + len(name) + name + config_type.
> 
> With global_flag or spaceId, we can save configuration of different spaces, and "module" is something like "storage" or "graph" to distinguish configurations of same name.
> 
> As to config value, I think config_type and value will be enough.

Now, i am thinking about how about saving the default value on meta service

**Comment by sherman-the-tank** [comment]
Since the ConfManager will replace most of the gflags, which are used on the critical path, we need to make sure the READ operation on the ConfManager is fast enough

**Comment by critical27** [comment]
> Since the ConfManager will replace most of the gflags, which are used on the critical path, we need to make sure the READ operation on the ConfManager is fast enough

For now, there are few configs which changes on critical path, I only find something like `load_data_interval_secs` can be changed during the runtime. So what do you mean about "most of gflags"? If we store fixed configs in ConfigManager, which will make us have strong dependency of Meta.

**Comment by dangleptr** [comment]
After talked with @critical27 offline,  this is the final implementation:
 * How to declare a variable?
You could still define a variable with gFlags.  But the gFlags are immutable,  and all of them will be registered on Meta Server when start-up. 

 * How to use a variable?
We define some macros such as GET_CONFIG(xxx) to access the variable.  Inside the macro, it is ConfigManager related interface.  ConfigManager will access local cache for the variable, if the local cache is not ready when start up,  related gFlag will be returned as the default value. 

 * How to change the variable?
All variables in ConfigManager could only be changed through console.   gFlags can't be changed at the runtime.

**Comment by sherman-the-tank** [comment]
> * How to use a variable?
>   We define some macros such as GET_CONFIG(xxx) to access the variable.  Inside the macro, it is ConfigManager related interface.  ConfigManager will access local cache for the variable, if the local cache is not ready when start up,  related gFlag will be returned as the default value.

Why not just let user read gflags? ConfManager can modify the gflag values if necessary
