### ISSUE TITLE
Add a command to release useless sessions manually

### ISSUE THREAD

**Issue by zach-pro** [vesoft-inc/nebula#4747]
**nebula session连接过多时,就只能等待时间过期后,才可以使用重新创建session **

可以增加一个手动关闭nebula session的命令关掉不需要的session

**Describe the solution you'd like**

可以把session时间设置存活时间默认调整短点, 配合空闲时间, 来将长时间不使用的session资源, 服务器端自动释放出来

**Comment by wey-gu** [comment]
@MuYiYong we should consider this, when for some reason, when session context was lost in the client side but persisted in meta, and the number of those sessions exceeded the default 300 (max session per user per IP), it's impossible for clients to create new sessions(user will encounter this issue quite often), add admin query (i.e. kill session) will be quite essential in such cases.

**Comment by wdroste** [comment]
I encounter it quite easily, my only way to recover was to shut it all down change the timeout to 1min and restart the whole cluster.

**Comment by wey-gu** [comment]
cc @MuYiYong

**Comment by wey-gu** [comment]
@wdroste this is planned already :).
