### ISSUE TITLE
Print detailed log of download job failure

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#4752]
**Your Environments (__required__)**
![image](https://user-images.githubusercontent.com/104358440/196843854-3891f6b1-4236-4bf4-aa65-a08c52106251.png)

**How To Reproduce(__required__)**
1. execute the download job twice in the same space, the first time successful, the second time failed
![image](https://user-images.githubusercontent.com/104358440/196844749-cb5bfe68-9e3b-4bd1-ad7f-76bfae689628.png)
2. checking the storage logs, there is no clear reason for the failure, I need to execute the command manually to know the reason for the failure
![image](https://user-images.githubusercontent.com/104358440/196845484-b54cd41e-db01-435d-b199-3e2a84922e19.png)
![image](https://user-images.githubusercontent.com/104358440/196845547-5cc92b69-af27-4bd8-b9be-c67761d54b86.png)

**Expected behavior**
1. when download job Failed， Print detailed failure logs
2. If the download file already exists, should delete it first before executing the download operation

**Comment by shanlai** [comment]
3.3 rc checked
