### ISSUE TITLE
An error is reported using the lookup statement  `-1005:Storage Error: part: 1, error: E_RPC_FAILURE(-3)`.

### ISSUE THREAD

**Issue by LiuTianyou** [vesoft-inc/nebula#4809]
**Describe the bug (__required__)**

An error is reported using the lookup statement  `-1005:Storage Error: part: 1, error: E_RPC_FAILURE(-3)`.

**Your Environments (__required__)**

* OS: `Mac os`
* Use docker-compose deployment
* Nebula version 3.2.0

**How To Reproduce(__required__)**

1. Create a tag, add attributes, and create an index
2. Insert the vertex that uses the tag
3. Add an property to this tag that is not allowed to be null and does not specify a default value
4. Using the lookup statement to query

**Expected behavior**

Users should be prevented from adding property that are allowed to be null and do not specify default values to tags already used by vertex, rather than getting a confusing error when querying

**Comment by jievince** [comment]
Can you use the actual ngql to describe the steps?
