### ISSUE TITLE
It's not supported for LOOKUP on a tag with both order by, skip and limit.

### ISSUE THREAD

**Issue by son2408** [vesoft-inc/nebula#4810]
It's not supported for LOOKUP on a tag with order by, skip and limit.

**Comment by wey-gu** [comment]
> It's not supported for LOOKUP on a tag with order by, skip and limit.

Dear @son2408 

It's possible to do with `| ORDER BY x,y,z... | LIMIT [offset] [limit]`

for example:

```
(root@nebula) [basketballplayer]> LOOKUP ON player YIELD id(vertex), player.name AS name | ORDER BY $-.name | LIMIT 10;
+-------------+---------------------+
| id(VERTEX)  | name                |
+-------------+---------------------+
| "player147" | "Amar'e Stoudemire" |
| "player107" | "Aron Baynes"       |
| "player149" | "Ben Simmons"       |
| "player134" | "Blake Griffin"     |
| "player108" | "Boris Diaw"        |
| "player128" | "Carmelo Anthony"   |
| "player121" | "Chris Paul"        |
| "player110" | "Cory Joseph"       |
| "player135" | "Damian Lillard"    |
| "player105" | "Danny Green"       |
+-------------+---------------------+
Got 10 rows (time spent 4709/99507 us)

Mon, 31 Oct 2022 10:43:36 CST

(root@nebula) [basketballplayer]> LOOKUP ON player YIELD id(vertex), player.name AS name | ORDER BY $-.name | LIMIT 5;
+-------------+---------------------+
| id(VERTEX)  | name                |
+-------------+---------------------+
| "player147" | "Amar'e Stoudemire" |
| "player107" | "Aron Baynes"       |
| "player149" | "Ben Simmons"       |
| "player134" | "Blake Griffin"     |
| "player108" | "Boris Diaw"        |
+-------------+---------------------+
Got 5 rows (time spent 4387/10705 us)

Mon, 31 Oct 2022 10:43:41 CST

(root@nebula) [basketballplayer]> LOOKUP ON player YIELD id(vertex), player.name AS name | ORDER BY $-.name | LIMIT 5,5;
+-------------+-------------------+
| id(VERTEX)  | name              |
+-------------+-------------------+
| "player128" | "Carmelo Anthony" |
| "player121" | "Chris Paul"      |
| "player110" | "Cory Joseph"     |
| "player135" | "Damian Lillard"  |
| "player105" | "Danny Green"     |
+-------------+-------------------+
Got 5 rows (time spent 4216/11640 us)

Mon, 31 Oct 2022 10:43:49 CST
```

ref: https://docs.nebula-graph.io/3.2.1/3.ngql-guide/8.clauses-and-options/limit/#go_limit

**Comment by son2408** [comment]
I have a trouble. When I sort order by DESC If the prop thoiDiemDangKy is null then it's last insted of top.
for example:
(root@nebula) [HCMLIS]> lookup on tinhhinhdangky where tinhhinhdangky.xaId ==26797 yield id(vertex ) as id, tinhhinhdangky.NodeId as nodeId, tinhhinhdangky.thoiDiemDangKy as thoiDiemDangKy | ORDER BY $-.thoiDiemDangKy desc | limit 10
+-----------------------+----------------------------------------+----------------+
| id                    | nodeId                                 | thoiDiemDangKy |
+-----------------------+----------------------------------------+----------------+
| "tinhhinhdangky_1922" | "04655eec-18b6-4b02-af80-4a9e23dea918" | __NULL__       |
| "tinhhinhdangky_2953" | "9052c365-9464-43da-90bf-d0235e6af6b1" | __NULL__       |
| "tinhhinhdangky_5349" | "7845b60e-8637-45e1-8cf5-c68b0af4fd9e" | __NULL__       |
| "tinhhinhdangky_1646" | "0d431f63-d88b-40e5-9b3a-dabc773c8e28" | __NULL__       |
| "tinhhinhdangky_2541" | "3df5a6e3-aa60-430f-9caf-a5cb48587089" | __NULL__       |
| "tinhhinhdangky_2523" | "3edf547d-d4a9-4514-9d3d-e50aefbf12db" | __NULL__       |
| "tinhhinhdangky_6884" | "90d87531-fe0f-46e2-accb-0999a3cf3a5a" | __NULL__       |
| "tinhhinhdangky_6795" | "5a95021b-4b63-408e-b3bc-abbd06b72184" | __NULL__       |
| "tinhhinhdangky_6403" | "3c7155fa-1f86-4639-8b2e-090490723602" | __NULL__       |
| "tinhhinhdangky_6188" | "7da4a864-918e-4d67-8279-2105ff889992" | __NULL__       |
+-----------------------+----------------------------------------+----------------+
Got 10 rows (time spent 631696/634769 us)

The desired result as follow:
(root@nebula) [HCMLIS]> match(v:tinhhinhdangky) where v.tinhhinhdangky.xaId == 26797 and v.tinhhinhdangky.thoiDiemDangKy IS NOT NULL return v.tinhhinhdangky.NodeId as NodeId, v.tinhhinhdangky.thoiDiemDangKy as thoiDiemDangKy order by thoiDiemDangKy desc limit 10;
+----------------------------------------+----------------------------+
| NodeId                                 | thoiDiemDangKy             |
+----------------------------------------+----------------------------+
| "16b6067b-cb6b-4bdb-8495-51429840da1f" | 2022-09-30T00:00:00.000000 |
| "ad4b3757-f433-4bcf-ab0c-46919952a00a" | 2022-09-28T00:00:00.000000 |
| "bcedefb4-49cf-4808-8537-24d85dbdc95f" | 2022-09-23T00:00:00.000000 |
| "b0f7e96d-fd08-4402-9060-51d9516eade8" | 2022-09-15T00:00:00.000000 |
| "d559d655-bca0-4299-91f8-c2852d63a786" | 2022-09-09T00:00:00.000000 |
| "1c991976-2bb3-4e08-ad8b-3005ed06b2c1" | 2022-09-09T00:00:00.000000 |
| "b49a903e-5565-4628-a6f3-3beb0383d2cb" | 2022-08-30T00:00:00.000000 |
| "3ea41452-1545-43d1-85ab-1e22c4ae5819" | 2022-08-30T00:00:00.000000 |
| "a436bcea-719c-4c70-aa54-d49129ba6719" | 2022-08-30T00:00:00.000000 |
| "c7613bc4-0f58-4622-a79a-7e1260d81830" | 2022-08-30T00:00:00.000000 |
|  ...                                                                     |            __NULL__                       |
+----------------------------------------+----------------------------+

**Comment by wey-gu** [comment]
OK, lookup doesn't support IS NOT NULL filter expression now, which is strange to me, move to https://github.com/vesoft-inc/nebula/issues/4811 for further discussion.

**Comment by son2408** [comment]
If I sort prop which contain null value, then the result seems incorrect
[HCMLIS]> match(v:tinhhinhdangky) where v.tinhhinhdangky.xaId == 26797 return v.tinhhinhdangky.NodeId as NodeId, v.tinhhinhdangky.thoiDiemDangKy as thoiDiemDangKy order by thoiDiemDangKy desc limit 10;

```
> +----------------------------------------+----------------+
> | NodeId                                 | thoiDiemDangKy |
> +----------------------------------------+----------------+
> | "a7397ab5-2777-4bf7-8c02-bfd9d5dc2fbb" | __NULL__       |
> | "071451b3-f6a3-46c8-a0b4-aedbd30e3201" | __NULL__       |
> | "1785c378-35a8-4bc5-af3f-e73b6c746798" | __NULL__       |
> | "f17c092b-d9ce-4a81-8100-8ff12e603435" | __NULL__       |
> | "49224766-25c0-4061-8737-34910bb5d372" | __NULL__       |
> | "d86c4656-47ab-4019-b00f-fc18da24de30" | __NULL__       |
> | "e648fc25-b143-493d-a8e7-e92a39d7cb9c" | __NULL__       |
> | "4080f76c-5af7-4073-9deb-4273af0ec8af" | __NULL__       |
> | "828de10b-0236-477c-8c89-b41a78533675" | __NULL__       |
> | "2a0a6c47-d8be-4625-b44b-4110a6054ef9" | __NULL__       |
> +----------------------------------------+----------------+
> Got 10 rows (time spent 279453/288937 us)
> 
> Mon, 31 Oct 2022 14:23:26 +07
```

**Comment by wey-gu** [comment]
> 

I think this is as expected as if you do `ascending sorting` it should be:
- A
- B
- C
- Z
- __NULL__

What is your expectation on this result, plz?

**Comment by son2408** [comment]
@wey-gu I think If I do **descending sorting** it should be:

- Z
- C
- B
- A
- NULL

**Comment by wey-gu** [comment]
> @wey-gu I think If I do **descending sorting** it should be:
> 
> * Z
> * C
> * B
> * A
> * NULL

Yes, NULL could be considered as smaller than 0 and this expectation is indeed reasonable, too, for now we have to add IS NOT NULL to mitigate(but lookup doesn't support such expression, sorry for this...)

**Comment by wey-gu** [comment]
> @wey-gu I think If I do **descending sorting** it should be:
> 
> * Z
> * C
> * B
> * A
> * NULL

Yes, NULL could be considered as smaller than 0 and this expectation is indeed reasonable, too, for now we have to add IS NOT NULL to mitigate(but lookup doesn't support such expression, sorry for this...)

**Comment by son2408** [comment]
I can't add IS NOT NULL beacause it will reduce result return. Field value only sort so that it's true

**Comment by son2408** [comment]
> > @wey-gu I think If I do **descending sorting** it should be:
> > 
> > * Z
> > * C
> > * B
> > * A
> > * NULL
> 
> Yes, NULL could be considered as smaller than 0 and this expectation is indeed reasonable, too, for now we have to add IS NOT NULL to mitigate(but lookup doesn't support such expression, sorry for this...)

@wey-gu Could you support this issuse for next release, plz ?

**Comment by wey-gu** [comment]
I'll raise this in a separate issue.
