### ISSUE TITLE
Query for edge property returns BAD_TYPE

### ISSUE THREAD

**Issue by cdalexndr** [vesoft-inc/nebula#4812]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

`describe edge has`

Field | Type | Null | Default | Comment
-- | -- | -- | -- | --
id | int64 | YES | _EMPTY_ | _EMPTY_

Query for all properties works:

`MATCH (s:category)-[e:has]-(t:product) where id(s) == 'category594997595'  and id(t) == 'product495966995'  RETURN e`
`[:has "product495966995"->"category594997595" @0 {id: -1963010408}]`
^ id is `-1963010408`

Query for only id, returns **BAD_TYPE**:

`MATCH (s:category)-[e:has]-(t:product) where id(s) == 'category594997595'  and id(t) == 'product495966995'  RETURN e.has.id`

e.has.id
**BAD_TYPE**

</body>
</html>

**Your Environments (__required__)**

* OS: `uname -a` docker for windows, nebula-graph 3.2.1
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

Return `-1963010408`, value of id property of edge

**Additional context**

**Comment by jievince** [comment]
For edge, you should return e.id, not e.has.id, which is different from vertex.
