### ISSUE TITLE
The expression's depth exceeds the maximum depth:512

### ISSUE THREAD

**Issue by son2408** [vesoft-inc/nebula#4816]
![image](https://user-images.githubusercontent.com/32300653/199383654-f352b327-9201-4d81-8c96-70d6adca8518.png)

**Comment by wey-gu** [comment]
We could enlarge this configuration from GraphD:

`max_expression_depth`

By default it's indeed 512 :)

**Comment by son2408** [comment]
I don't find max_expression_depth option in this nebula-graphd.conf
![image](https://user-images.githubusercontent.com/32300653/199416898-2f694212-b968-4823-b5d6-bc43b1daecb9.png)

**Comment by son2408** [comment]
> We could enlarge this configuration from GraphD:
> 
> `max_expression_depth`
> 
> By default it's indeed 512 :)

Where is  the configuration GraphD ?

**Comment by Sophie-Xie** [comment]
> > We could enlarge this configuration from GraphD:
> > `max_expression_depth`
> > By default it's indeed 512 :)
> 
> Where is the configuration GraphD ?

`nebula-graphd.conf` is right.  Add `max_expression_depth` in it.

**Comment by wey-gu** [comment]
> I don't find max_expression_depth option in this nebula-graphd.conf ![image](https://user-images.githubusercontent.com/32300653/199416898-2f694212-b968-4823-b5d6-bc43b1daecb9.png)

it's exactly under this file you are showing, not all configurations are listed here, some of them are omit with default values to reduce configuration surface to fresh users.

just add another line like
```
--max_expression_depth=1024
```
