### ISSUE TITLE
should reset session space after `Space not existed`

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#4818]
there're two session, sessionA and sessionB

1. sessionA: create spaceA, and then use space.
2. sessionB: drop the spaceA
3. sessionA: create tag in spaceA

expected result:
1. raise a `Space not existed` error.
2. the space name in resultSet should be ""

actual result:
1. raise a `Space not existed` error.
2. the space name in resultSet is still "spaceA"

![image](https://user-images.githubusercontent.com/1726587/199410738-d7531336-3e80-45fa-94d7-415cb22cbb30.png)

space name is still "spaceA"

**Comment by Aiee** [comment]
We might need to add a new error code to distinguish if the SPACE_NOT_FOUND is returned by a USE statement or other statements.

For example, for query like use space_1; create tag t1(), if space_1 was dropped before executing create tag t1(), the session space should be reset. If space_1 was dropped before executing use space_1, the space should remain the same.

This will be regarded as a known issue for now.

**Comment by Sophie-Xie** [comment]
Discuss it with @MuYiYong @HarrisChu: we will not fix it.
