### ISSUE TITLE
Statement results are not as expected

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula#4831]
![image](https://user-images.githubusercontent.com/78672629/200244513-24ae34c0-c9ac-4c9c-af14-2141c845baa9.png)
![image](https://user-images.githubusercontent.com/78672629/200244578-5d388b37-d220-4bc1-95e9-200ccebca370.png)
![image](https://user-images.githubusercontent.com/78672629/200244634-8cee0b4a-ce02-4502-90d1-f272f9028213.png)

**Comment by czpmango** [comment]
Revert this pr https://github.com/vesoft-inc/nebula-console/pull/181

**Comment by Aiee** [comment]
Closed by https://github.com/vesoft-inc/nebula-console/pull/184
