### ISSUE TITLE
The length() function returns NULLs instead of the length of a path

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#4862]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/78209557/201275023-1b14b24a-011d-4c75-94a2-948bb4524b5b.png">

The length() function returns NULLs instead of the path length when I want to query the name in returned paths.

**Comment by czpmango** [comment]
Just need throw runtime error for incompatible types, this is my test in neo4j 4.2.4:
```
neo4j@neo4j> create (v:player{name:"czp"})-[:like]->();
Added 2 nodes, Created 1 relationships, Set 1 properties, Added 1 labels

neo4j@neo4j> match p=(v:player)--() return length(p),size(v.name),length(v.name);
LENGTH cannot be used on strings

neo4j@neo4j> match p=(v:player)--() return length(p),size(v.name);
+--------------------------+
| length(p) | size(v.name) |
+--------------------------+
| 1         | 3            |
+--------------------------+

neo4j@neo4j> match p=(v:player)--() return length(p),size(v.prop);
+--------------------------+
| length(p) | size(v.prop) |
+--------------------------+
| 1         | NULL         |
+--------------------------+

```

**Comment by Shylock-Hg** [comment]
A bug of properties prune
```
(root@nebula) [nba]> explain match (v) where id(v) == 'Tim Duncan' return length(v.player.name)
Execution succeeded (time spent 4791/6365 us)

Execution Plan (optimize time 2369 us)

-----+----------------+--------------+----------------+--------------------------------
| id | name           | dependencies | profiling data | operator info                 |
-----+----------------+--------------+----------------+--------------------------------
|  6 | Project        | 7            |                | outputVar: {                  |
|    |                |              |                |   "colNames": [               |
|    |                |              |                |     "length(v.player.name)"   |
|    |                |              |                |   ],                          |
|    |                |              |                |   "type": "DATASET",          |
|    |                |              |                |   "name": "__Project_6"       |
|    |                |              |                | }                             |
|    |                |              |                | inputVar: __Project_5         |
|    |                |              |                | columns: [                    |
|    |                |              |                |   "length(v.player.name)"     |
|    |                |              |                | ]                             |
-----+----------------+--------------+----------------+--------------------------------
|  7 | AppendVertices | 2            |                | outputVar: {                  |
|    |                |              |                |   "colNames": [               |
|    |                |              |                |     "v"                       |
|    |                |              |                |   ],                          |
|    |                |              |                |   "type": "DATASET",          |
|    |                |              |                |   "name": "__Project_5"       |
|    |                |              |                | }                             |
|    |                |              |                | inputVar: __Dedup_2           |
|    |                |              |                | space: 2                      |
|    |                |              |                | dedup: true                   |
|    |                |              |                | limit: -1                     |
|    |                |              |                | filter:                       |
|    |                |              |                | orderBy: []                   |
|    |                |              |                | src: $-._vid                  |
|    |                |              |                | props: [                      |
|    |                |              |                |   {                           |
|    |                |              |                |     "props": [                |
|    |                |              |                |       "_tag"                  |
|    |                |              |                |     ],                        |
|    |                |              |                |     "tagId": 9                |
|    |                |              |                |   },                          |
|    |                |              |                |   {                           |
|    |                |              |                |     "tagId": 8,               |
|    |                |              |                |     "props": [                |
|    |                |              |                |       "_tag"                  |
|    |                |              |                |     ]                         |
|    |                |              |                |   },                          |
|    |                |              |                |   {                           |
|    |                |              |                |     "props": [                |
|    |                |              |                |       "_tag"                  |
|    |                |              |                |     ],                        |
|    |                |              |                |     "tagId": 10               |
|    |                |              |                |   }                           |
|    |                |              |                | ]                             |
|    |                |              |                | exprs:                        |
|    |                |              |                | vertex_filter:                |
|    |                |              |                | if_track_previous_path: false |
-----+----------------+--------------+----------------+--------------------------------
|  2 | Dedup          | 1            |                | outputVar: {                  |
|    |                |              |                |   "colNames": [               |
|    |                |              |                |     "_vid"                    |
|    |                |              |                |   ],                          |
|    |                |              |                |   "type": "DATASET",          |
|    |                |              |                |   "name": "__Dedup_2"         |
|    |                |              |                | }                             |
|    |                |              |                | inputVar: __VAR_0             |
-----+----------------+--------------+----------------+--------------------------------
|  1 | PassThrough    | 3            |                | outputVar: {                  |
|    |                |              |                |   "colNames": [               |
|    |                |              |                |     "_vid"                    |
|    |                |              |                |   ],                          |
|    |                |              |                |   "type": "DATASET",          |
|    |                |              |                |   "name": "__VAR_0"           |
|    |                |              |                | }                             |
|    |                |              |                | inputVar:                     |
-----+----------------+--------------+----------------+--------------------------------
|  3 | Start          |              |                | outputVar: {                  |
|    |                |              |                |   "colNames": [],             |
|    |                |              |                |   "name": "__Start_3",        |
|    |                |              |                |   "type": "DATASET"           |
|    |                |              |                | }                             |
-----+----------------+--------------+----------------+--------------------------------

Wed, 16 Nov 2022 10:32:58 CST
```

**Comment by czpmango** [comment]
> A bug of properties prune
> 
> ```
> (root@nebula) [nba]> explain match (v) where id(v) == 'Tim Duncan' return length(v.player.name)
> Execution succeeded (time spent 4791/6365 us)
> 
> Execution Plan (optimize time 2369 us)
> 
> -----+----------------+--------------+----------------+--------------------------------
> | id | name           | dependencies | profiling data | operator info                 |
> -----+----------------+--------------+----------------+--------------------------------
> |  6 | Project        | 7            |                | outputVar: {                  |
> |    |                |              |                |   "colNames": [               |
> |    |                |              |                |     "length(v.player.name)"   |
> |    |                |              |                |   ],                          |
> |    |                |              |                |   "type": "DATASET",          |
> |    |                |              |                |   "name": "__Project_6"       |
> |    |                |              |                | }                             |
> |    |                |              |                | inputVar: __Project_5         |
> |    |                |              |                | columns: [                    |
> |    |                |              |                |   "length(v.player.name)"     |
> |    |                |              |                | ]                             |
> -----+----------------+--------------+----------------+--------------------------------
> |  7 | AppendVertices | 2            |                | outputVar: {                  |
> |    |                |              |                |   "colNames": [               |
> |    |                |              |                |     "v"                       |
> |    |                |              |                |   ],                          |
> |    |                |              |                |   "type": "DATASET",          |
> |    |                |              |                |   "name": "__Project_5"       |
> |    |                |              |                | }                             |
> |    |                |              |                | inputVar: __Dedup_2           |
> |    |                |              |                | space: 2                      |
> |    |                |              |                | dedup: true                   |
> |    |                |              |                | limit: -1                     |
> |    |                |              |                | filter:                       |
> |    |                |              |                | orderBy: []                   |
> |    |                |              |                | src: $-._vid                  |
> |    |                |              |                | props: [                      |
> |    |                |              |                |   {                           |
> |    |                |              |                |     "props": [                |
> |    |                |              |                |       "_tag"                  |
> |    |                |              |                |     ],                        |
> |    |                |              |                |     "tagId": 9                |
> |    |                |              |                |   },                          |
> |    |                |              |                |   {                           |
> |    |                |              |                |     "tagId": 8,               |
> |    |                |              |                |     "props": [                |
> |    |                |              |                |       "_tag"                  |
> |    |                |              |                |     ]                         |
> |    |                |              |                |   },                          |
> |    |                |              |                |   {                           |
> |    |                |              |                |     "props": [                |
> |    |                |              |                |       "_tag"                  |
> |    |                |              |                |     ],                        |
> |    |                |              |                |     "tagId": 10               |
> |    |                |              |                |   }                           |
> |    |                |              |                | ]                             |
> |    |                |              |                | exprs:                        |
> |    |                |              |                | vertex_filter:                |
> |    |                |              |                | if_track_previous_path: false |
> -----+----------------+--------------+----------------+--------------------------------
> |  2 | Dedup          | 1            |                | outputVar: {                  |
> |    |                |              |                |   "colNames": [               |
> |    |                |              |                |     "_vid"                    |
> |    |                |              |                |   ],                          |
> |    |                |              |                |   "type": "DATASET",          |
> |    |                |              |                |   "name": "__Dedup_2"         |
> |    |                |              |                | }                             |
> |    |                |              |                | inputVar: __VAR_0             |
> -----+----------------+--------------+----------------+--------------------------------
> |  1 | PassThrough    | 3            |                | outputVar: {                  |
> |    |                |              |                |   "colNames": [               |
> |    |                |              |                |     "_vid"                    |
> |    |                |              |                |   ],                          |
> |    |                |              |                |   "type": "DATASET",          |
> |    |                |              |                |   "name": "__VAR_0"           |
> |    |                |              |                | }                             |
> |    |                |              |                | inputVar:                     |
> -----+----------------+--------------+----------------+--------------------------------
> |  3 | Start          |              |                | outputVar: {                  |
> |    |                |              |                |   "colNames": [],             |
> |    |                |              |                |   "name": "__Start_3",        |
> |    |                |              |                |   "type": "DATASET"           |
> |    |                |              |                | }                             |
> -----+----------------+--------------+----------------+--------------------------------
> 
> Wed, 16 Nov 2022 10:32:58 CST
> ```

Exactly, but the behavior of the length function is also wrong.

**Comment by Shylock-Hg** [comment]
> > A bug of properties prune
> > ```
> > (root@nebula) [nba]> explain match (v) where id(v) == 'Tim Duncan' return length(v.player.name)
> > Execution succeeded (time spent 4791/6365 us)
> > 
> > Execution Plan (optimize time 2369 us)
> > 
> > -----+----------------+--------------+----------------+--------------------------------
> > | id | name           | dependencies | profiling data | operator info                 |
> > -----+----------------+--------------+----------------+--------------------------------
> > |  6 | Project        | 7            |                | outputVar: {                  |
> > |    |                |              |                |   "colNames": [               |
> > |    |                |              |                |     "length(v.player.name)"   |
> > |    |                |              |                |   ],                          |
> > |    |                |              |                |   "type": "DATASET",          |
> > |    |                |              |                |   "name": "__Project_6"       |
> > |    |                |              |                | }                             |
> > |    |                |              |                | inputVar: __Project_5         |
> > |    |                |              |                | columns: [                    |
> > |    |                |              |                |   "length(v.player.name)"     |
> > |    |                |              |                | ]                             |
> > -----+----------------+--------------+----------------+--------------------------------
> > |  7 | AppendVertices | 2            |                | outputVar: {                  |
> > |    |                |              |                |   "colNames": [               |
> > |    |                |              |                |     "v"                       |
> > |    |                |              |                |   ],                          |
> > |    |                |              |                |   "type": "DATASET",          |
> > |    |                |              |                |   "name": "__Project_5"       |
> > |    |                |              |                | }                             |
> > |    |                |              |                | inputVar: __Dedup_2           |
> > |    |                |              |                | space: 2                      |
> > |    |                |              |                | dedup: true                   |
> > |    |                |              |                | limit: -1                     |
> > |    |                |              |                | filter:                       |
> > |    |                |              |                | orderBy: []                   |
> > |    |                |              |                | src: $-._vid                  |
> > |    |                |              |                | props: [                      |
> > |    |                |              |                |   {                           |
> > |    |                |              |                |     "props": [                |
> > |    |                |              |                |       "_tag"                  |
> > |    |                |              |                |     ],                        |
> > |    |                |              |                |     "tagId": 9                |
> > |    |                |              |                |   },                          |
> > |    |                |              |                |   {                           |
> > |    |                |              |                |     "tagId": 8,               |
> > |    |                |              |                |     "props": [                |
> > |    |                |              |                |       "_tag"                  |
> > |    |                |              |                |     ]                         |
> > |    |                |              |                |   },                          |
> > |    |                |              |                |   {                           |
> > |    |                |              |                |     "props": [                |
> > |    |                |              |                |       "_tag"                  |
> > |    |                |              |                |     ],                        |
> > |    |                |              |                |     "tagId": 10               |
> > |    |                |              |                |   }                           |
> > |    |                |              |                | ]                             |
> > |    |                |              |                | exprs:                        |
> > |    |                |              |                | vertex_filter:                |
> > |    |                |              |                | if_track_previous_path: false |
> > -----+----------------+--------------+----------------+--------------------------------
> > |  2 | Dedup          | 1            |                | outputVar: {                  |
> > |    |                |              |                |   "colNames": [               |
> > |    |                |              |                |     "_vid"                    |
> > |    |                |              |                |   ],                          |
> > |    |                |              |                |   "type": "DATASET",          |
> > |    |                |              |                |   "name": "__Dedup_2"         |
> > |    |                |              |                | }                             |
> > |    |                |              |                | inputVar: __VAR_0             |
> > -----+----------------+--------------+----------------+--------------------------------
> > |  1 | PassThrough    | 3            |                | outputVar: {                  |
> > |    |                |              |                |   "colNames": [               |
> > |    |                |              |                |     "_vid"                    |
> > |    |                |              |                |   ],                          |
> > |    |                |              |                |   "type": "DATASET",          |
> > |    |                |              |                |   "name": "__VAR_0"           |
> > |    |                |              |                | }                             |
> > |    |                |              |                | inputVar:                     |
> > -----+----------------+--------------+----------------+--------------------------------
> > |  3 | Start          |              |                | outputVar: {                  |
> > |    |                |              |                |   "colNames": [],             |
> > |    |                |              |                |   "name": "__Start_3",        |
> > |    |                |              |                |   "type": "DATASET"           |
> > |    |                |              |                | }                             |
> > -----+----------------+--------------+----------------+--------------------------------
> > 
> > Wed, 16 Nov 2022 10:32:58 CST
> > ```
> 
> Exactly, but the behavior of the length function is also wrong.

We support `length(STRING)`

**Comment by czpmango** [comment]
> > > A bug of properties prune
> > > ```
> > > (root@nebula) [nba]> explain match (v) where id(v) == 'Tim Duncan' return length(v.player.name)
> > > Execution succeeded (time spent 4791/6365 us)
> > > 
> > > Execution Plan (optimize time 2369 us)
> > > 
> > > -----+----------------+--------------+----------------+--------------------------------
> > > | id | name           | dependencies | profiling data | operator info                 |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > |  6 | Project        | 7            |                | outputVar: {                  |
> > > |    |                |              |                |   "colNames": [               |
> > > |    |                |              |                |     "length(v.player.name)"   |
> > > |    |                |              |                |   ],                          |
> > > |    |                |              |                |   "type": "DATASET",          |
> > > |    |                |              |                |   "name": "__Project_6"       |
> > > |    |                |              |                | }                             |
> > > |    |                |              |                | inputVar: __Project_5         |
> > > |    |                |              |                | columns: [                    |
> > > |    |                |              |                |   "length(v.player.name)"     |
> > > |    |                |              |                | ]                             |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > |  7 | AppendVertices | 2            |                | outputVar: {                  |
> > > |    |                |              |                |   "colNames": [               |
> > > |    |                |              |                |     "v"                       |
> > > |    |                |              |                |   ],                          |
> > > |    |                |              |                |   "type": "DATASET",          |
> > > |    |                |              |                |   "name": "__Project_5"       |
> > > |    |                |              |                | }                             |
> > > |    |                |              |                | inputVar: __Dedup_2           |
> > > |    |                |              |                | space: 2                      |
> > > |    |                |              |                | dedup: true                   |
> > > |    |                |              |                | limit: -1                     |
> > > |    |                |              |                | filter:                       |
> > > |    |                |              |                | orderBy: []                   |
> > > |    |                |              |                | src: $-._vid                  |
> > > |    |                |              |                | props: [                      |
> > > |    |                |              |                |   {                           |
> > > |    |                |              |                |     "props": [                |
> > > |    |                |              |                |       "_tag"                  |
> > > |    |                |              |                |     ],                        |
> > > |    |                |              |                |     "tagId": 9                |
> > > |    |                |              |                |   },                          |
> > > |    |                |              |                |   {                           |
> > > |    |                |              |                |     "tagId": 8,               |
> > > |    |                |              |                |     "props": [                |
> > > |    |                |              |                |       "_tag"                  |
> > > |    |                |              |                |     ]                         |
> > > |    |                |              |                |   },                          |
> > > |    |                |              |                |   {                           |
> > > |    |                |              |                |     "props": [                |
> > > |    |                |              |                |       "_tag"                  |
> > > |    |                |              |                |     ],                        |
> > > |    |                |              |                |     "tagId": 10               |
> > > |    |                |              |                |   }                           |
> > > |    |                |              |                | ]                             |
> > > |    |                |              |                | exprs:                        |
> > > |    |                |              |                | vertex_filter:                |
> > > |    |                |              |                | if_track_previous_path: false |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > |  2 | Dedup          | 1            |                | outputVar: {                  |
> > > |    |                |              |                |   "colNames": [               |
> > > |    |                |              |                |     "_vid"                    |
> > > |    |                |              |                |   ],                          |
> > > |    |                |              |                |   "type": "DATASET",          |
> > > |    |                |              |                |   "name": "__Dedup_2"         |
> > > |    |                |              |                | }                             |
> > > |    |                |              |                | inputVar: __VAR_0             |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > |  1 | PassThrough    | 3            |                | outputVar: {                  |
> > > |    |                |              |                |   "colNames": [               |
> > > |    |                |              |                |     "_vid"                    |
> > > |    |                |              |                |   ],                          |
> > > |    |                |              |                |   "type": "DATASET",          |
> > > |    |                |              |                |   "name": "__VAR_0"           |
> > > |    |                |              |                | }                             |
> > > |    |                |              |                | inputVar:                     |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > |  3 | Start          |              |                | outputVar: {                  |
> > > |    |                |              |                |   "colNames": [],             |
> > > |    |                |              |                |   "name": "__Start_3",        |
> > > |    |                |              |                |   "type": "DATASET"           |
> > > |    |                |              |                | }                             |
> > > -----+----------------+--------------+----------------+--------------------------------
> > > 
> > > Wed, 16 Nov 2022 10:32:58 CST
> > > ```
> > 
> > 
> > Exactly, but the behavior of the length function is also wrong.
> 
> We support `length(STRING)`

We should not support length(STRING)
