### ISSUE TITLE
Incorrect result of optional match statement

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4869]
**Describe the bug (__required__)**
The predicate in optional match statement is not in effect.

**Your Environments (__required__)**
nebula v3.2

**How To Reproduce(__required__)**
```
(root@nebula) [nba]> optional match (v) where id(v) in ["Tim Duncan","Tony Parker"] and false return id(v)
+---------------+
| id(v)         |
+---------------+
| "Tim Duncan"  |
| "Tony Parker" |
+---------------+
Got 2 rows (time spent 2808/3080 us)
```

**Expected behavior**
```
root@nebula> optional match (v) where false return v;
+------+
| v    |
+------+
| NULL |
+------+

```

**Additional context**
We should provide support for optional semantics at the implementation layer, such as providing corresponding physical operators.

**Comment by Sophie-Xie** [comment]
Discuss it offline with @nevermore3 : it doesn't need to be fixed.

**Comment by czpmango** [comment]
> Discuss it offline with @nevermore3 : it doesn't need to be fixed.

?? why?

**Comment by xtcyclist** [comment]
Partially duplicate with https://github.com/vesoft-inc/nebula-ent/issues/1458

**Comment by HarrisChu** [comment]
> 

why?+1

**Comment by xtcyclist** [comment]
Close optional match related issues.
