### ISSUE TITLE
root can drop herself/himself 

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula#4879]
Is this reasonable?

**Comment by Milittle** [comment]
May i can fix this, if this isn't reasonable

**Comment by wey-gu** [comment]
@Shylock-Hg what do you think ?:)

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg what do you think ?:)

I had fix it.

**Comment by Milittle** [comment]
> 

Great
