### ISSUE TITLE
fulltext index get failed

### ISSUE THREAD

**Issue by son2408** [vesoft-inc/nebula#4880]
how to create fulltext index tag ?
```
(root@nebula) [HCMLIS]> show text search clients;
+-----------------+---------------+------+
| Type            | Host          | Port |
+-----------------+---------------+------+
| "ELASTICSEARCH" | "10.225.0.32" | 9669 |
+-----------------+---------------+------+
Got 1 rows (time spent 1898/4419 us)

Tue, 15 Nov 2022 21:59:05 +07

(root@nebula) [HCMLIS]> ^C
(root@nebula) [HCMLIS]> CREATE FULLTEXT TAG INDEX nebula_index_1 ON thongtinhoso(rootId);
[ERROR (-1005)]: fulltext index get failed : nebula_index_1
```

**Comment by son2408** [comment]
cc @wey-gu Could you let me, plz?

**Comment by wey-gu** [comment]
Dear @son2408 ,

Have you created a native index on thongtinhoso(rootId) before creating full-text index `nebula_index_1`, plz?

**Comment by son2408** [comment]
yes, I created this before creating full-text index.
(root@nebula) [HCMLIS]> describe tag index nebula_index_1
+----------+---------------------+
| Field    | Type                |
+----------+---------------------+
| "rootId" | "fixed_string(100)" |
+----------+---------------------+
Got 1 rows (time spent 1125/4097 us)

**Comment by wey-gu** [comment]
But they are in same index name, maybe you could do this instead?
```
CREATE FULLTEXT TAG INDEX nebula_index_1_es ON thongtinhoso(rootId);
```

**Comment by son2408** [comment]
I tried, but it doesn't work.
```
(root@nebula) [HCMLIS]> CREATE FULLTEXT TAG INDEX nebula_index_1_es ON thongtinhoso(rootId);
[ERROR (-1005)]: fulltext index get failed : nebula_index_1_es
```

**Comment by wey-gu** [comment]
Were the listener and elastic search all deployed properly as the documentation guided?

**Comment by son2408** [comment]
yes, the best way to check deloyed elastic search properly ? @wey-gu

**Comment by wey-gu** [comment]
@Sophie-Xie could anyone help with this? I am not yet familiar with this.

**Comment by Sophie-Xie** [comment]
> But they are in same index name, maybe you could do this instead?
> 
> ```
> CREATE FULLTEXT TAG INDEX nebula_index_1_es ON thongtinhoso(rootId);
> ```

@cangfengzhs pls take a look, thanks.

**Comment by son2408** [comment]
LISTENER offline, could you let me know probable cause of it,plz ? cc @wey-gu, @Sophie-Xie  
(root@nebula) [HCMLIS]> show LISTENER;
+--------+-----------------+----------------------+-----------+
| PartId | Type            | Host                 | Status    |
+--------+-----------------+----------------------+-----------+
| 1      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 2      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 3      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 4      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 5      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 6      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 7      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 8      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 9      | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 10     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 11     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 12     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 13     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 14     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 15     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 16     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 17     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 18     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 19     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 20     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 21     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 22     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 23     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 24     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |
| 25     | "ELASTICSEARCH" | ""10.225.0.32":9669" | "OFFLINE" |

**Comment by cangfengzhs** [comment]
Maybe you can check whether Elasticsearch is working and whether the correct address of Elasticsearch is signed In in NebulaGraph.

**Comment by Sophie-Xie** [comment]
I will close it. If you have any new info, pls reopen it. Thanks.
