### ISSUE TITLE
Match path expression wrong result:

### ISSUE THREAD

**Issue by Milittle** [vesoft-inc/nebula#4889]
**Describe the bug (__required__)**

Import nba space;

when I execute the follow nGQL:
```
(root@nebula) [nba]> MATCH p=(v:player{name: 'Tim Duncan'})-[:like]->() WHERE (v)-[:like]->(:player{name:"Manu Ginobili"}) RETURN p;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| p                                                                                                                                                                                                 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <("Tim Duncan" :player{age: 42, name: "Tim Duncan"} :bachelor{name: "Tim Duncan", speciality: "psychology"})-[:like@0 {likeness: 95}]->("Tony Parker" :player{age: 36, name: "Tony Parker"})>     |
| <("Tim Duncan" :player{age: 42, name: "Tim Duncan"} :bachelor{name: "Tim Duncan", speciality: "psychology"})-[:like@0 {likeness: 95}]->("Manu Ginobili" :player{age: 41, name: "Manu Ginobili"})> |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

I think result should be one records?

**Additional context**

**Comment by wey-gu** [comment]
> I think result should be one records?

I dont think so, in where clause, we only added further constraints to v(that it should :like -> "Manu Ginobili").

Thus if there is path of "Tim Duncan" :like ->  "Manu Ginobili" already, the result should be equivalent to

```
(root@nebula) [nba]> MATCH p=(v:player{name: 'Tim Duncan'})-[:like]->() RETURN p;
```

**Comment by wey-gu** [comment]
cc @czpmango

**Comment by Milittle** [comment]
> > I think result should be one records?
> 
> I dont think so, in where clause, we only added further constraints to v(that it should :like -> "Manu Ginobili").
> 
> Thus if there is path of "Tim Duncan" :like -> "Manu Ginobili" already, the result should be equivalent to
> 
> ```
> (root@nebula) [nba]> MATCH p=(v:player{name: 'Tim Duncan'})-[:like]->() RETURN p;
> ```

I see, thanks indeed.

**Comment by wey-gu** [comment]
Thanks for the issue, closing it @Milittle  :-D
