### ISSUE TITLE
Fold constant for set

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula#4898]
We may need to fold constant for set as the current `eval` of set takes too much cpu.
<img width="696" alt="image" src="https://user-images.githubusercontent.com/19355821/202380466-8af78333-6dcf-4617-b364-5318fe58219f.png">

**Comment by yixinglu** [comment]
@czpmango  After this expression optimization, we can give a InExpression to reduce the overhead of switch when calling eval.

**Comment by czpmango** [comment]
> 



> @czpmango After this expression optimization, we can give a InExpression to reduce the overhead of switch when calling eval.

ACK.
