### ISSUE TITLE
nGQL support operations (properties get, set operation, aggregations)

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#492]
The following operations are most frequently used. Can nGQL support?

# get properties
get a edge/vertex/node property

# set operation
union, intersect, subtract (like sql inner join, union all, left outer join)

# aggregations
sort (order by), limit, group by,

# algo
shortest， all paths

# show/dump/load schema with version

**Comment by sherman-the-tank** [comment]
```GET PROP``` is a must-have

**Comment by sherman-the-tank** [comment]
@dutor What's the status of set op and aggregation statements?

**Comment by whitewum** [comment]
@sherman-the-tank @dutor @dangleptr should I change this issue to beta-release?
