### ISSUE TITLE
MINUS/INTERSECT not supported for MATCH statement

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#4935]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

MINUS/INTERSECT not supported for following MATCH statement

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

```sql
(root@nebula) [sf100]> MATCH (person:Person)-[:KNOWS]-(friend) WHERE id(person) == "p-65504" RETURN person MINUS MATCH (person:Person)-[:KNOWS]-(friend) WHERE id(person) == "p-65504" RETURN person
[ERROR (-1004)]: SyntaxError: syntax error near `MINUS'

Sat, 26 Nov 2022 01:30:58 CST
```

**Expected behavior**

**Additional context**

**Comment by Shylock-Hg** [comment]
I think it's by design. Open Cypher only supports UNION` operation.
