### ISSUE TITLE
How do we define `empty` value

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4942]
**Describe the bug (__required__)**
We need to define the exact semantics of `empty` and `null` to avoid inconsistent statement behavior.

**Your Environments (__required__)**
nebula all versions

**How To Reproduce(__required__)**
```
(root@nebula) [nba]> go from "Tim Duncan" over * yield $$.team.name
+--------------+
| $$.team.name |
+--------------+
|              |
|              |
| "Spurs"      |
|              |
|              |
|              |
|              |
+--------------+
Got 7 rows (time spent 3690/4030 us)

(root@nebula) [nba]> match (v)-[]->(n) where id(v)=="Tim Duncan" return n.team.name
+-------------+
| n.team.name |
+-------------+
| "Spurs"     |
| __NULL__    |
| __NULL__    |
| __NULL__    |
| __NULL__    |
| __NULL__    |
| __NULL__    |
+-------------+
```

**Expected behavior**
The expectation is to ensure consistent behavior of statements

**Additional context**
Similarly, there are other null-compatible value types to consider, such as UNKNOWN_PROP, etc.

**Comment by czpmango** [comment]
@MuYiYong cc

**Comment by czpmango** [comment]
@yixinglu cc

**Comment by xtcyclist** [comment]
This is a good issue. It has broad impacts. Need to make an conclusion on this.

**Comment by Sophie-Xie** [comment]
Discuss it offline with @MuYiYong @yixinglu @HarrisChu: Remain current behavior.
