### ISSUE TITLE
graph should not eat the storaged‘s error code？

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#4958]
**General Question**

When storaged happens `leader change` error, storaged return `E_LEADER_CHANGED`. When graphd get storaged's `E_LEADER_CHANGED`, it return `E_EXECUTION_ERROR` with message `Storage Error: The leader has changed. Try again later.`.
should graphd return `E_LEADER_CHANGED` error code too?

**Comment by HarrisChu** [comment]
prefer a new error code in graphd, graphd should never return error code from storaged.

**Comment by xtcyclist** [comment]
To the graphd and to the user, errors from the storaged like this happen in the execution phase. It is indeed an execution error. Nothing wrong here. And, we shall not simply pass storaged's internal errors to the users, considering that graphd is the upper-most layer.

In 5.0, we will have a new system of reporting errors.
