### ISSUE TITLE
LeftJoin executor outputs the joined columns multi times

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#4960]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Assume the join key of left join is column `a`, it will output two columns called `a`, one comes from the left child, and the other comes from the right child. And because the left join will add a null value for the right side, the two-column `a` may contain a different value.

The inner join will also output two columns `a`, although there is no correctness problem here.

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
has tck tests in pr now
