### ISSUE TITLE
Only check parent dir in RocksEngine

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#499]
As your code,  dataPath_ is the parent dir.   Fine,  open another issue to track it if you don't want to change in this pr.  #405 

_Originally posted by @dangleptr in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI5MDYyNTQ4OA==/pull_request_review_threads/reply_

**Comment by sherman-the-tank** [comment]
Not quite sure about this issue. Let's sync offline
