### ISSUE TITLE
the better way to optimize graph relationship one -to - many

### ISSUE THREAD

**Issue by son2408** [vesoft-inc/nebula#4992]
This my use case, I want return all values both null
![image](https://user-images.githubusercontent.com/32300653/205789549-0da48211-8b99-4e71-b48b-ba37f632368d.png)

**I builded query with optional match but It is very slow and if number of graphs is too many then optional match will too many**
match (v:A) -[e:A_B]-> (v2:B)
optional match(v2:B) -[e:B_E]-> (v3:E)
optional match(v2:B) -[e:B_F]-> (v4:F)
optional match (v:A) -[e:A_C]-> (v5:C)
return v, v2, v3, v4, v5

**Comment by wey-gu** [comment]
For such one to many, if you don't care about the path, you could use GO FROM 1 TO 2 STEPS …, or GET SUBGRAPH
