### ISSUE TITLE
When meta/storage starts for the first time, some error message is printed to the console

### ISSUE THREAD

**Issue by panda-sheep** [vesoft-inc/nebula#4994]
When meta/storage starts for the first time, some error message is printed to the console.
Some error messages should not be printed, as follows:

![image](https://user-images.githubusercontent.com/59197347/205829549-ce68a276-795c-4600-b325-09eb06571c39.png)
```
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20221202-180518.1171190!
```
Same issue as the enterprise version `https://github.com/vesoft-inc/nebula-ent/issues/1813`

**Comment by Sophie-Xie** [comment]
see the detail in PR.
