### ISSUE TITLE
Use deleteRange in removePrefix

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#500]
Fine, open another issue to track it. #405

_Originally posted by @dangleptr in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI5MDYyNTY0NQ==/pull_request_review_threads/reply_

**Comment by sherman-the-tank** [comment]
It's good to see we have an issue to record this.

As I mentioned in #405 , this needs to depend on the version of rocksdb and we need to make sure DeleteRange() is  really suitable here
