### ISSUE TITLE
storage-listener first start some error message are printed

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5004]
first start storage-listener, some error message are printed, it is unneccessary
![image](https://user-images.githubusercontent.com/106510322/205275029-7e6597d0-9e15-4945-81a5-2f00737095d0.png)
```
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20221202-180518.1171190!
```

**Describe the bug (__required__)**

**Your Environments (__required__)**
ent-nightly, commit id :e608339 
![image](https://user-images.githubusercontent.com/106510322/205275168-53a71e63-6c5f-4ef5-94e1-934e7a2510f5.png)

**Expected behavior**

it should be printed into log but not here

**Comment by panda-sheep** [comment]
close this pr, for more details, refer to pr: https://github.com/vesoft-inc/nebula/pull/4993
