### ISSUE TITLE
Push limit into `IndexScan`

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#5023]
**Introduction**

`MATCH (v:player) RETURN v LIMIT 10`
The plan is : IndexScan + AppendVertices + Limit.
The limit is not pushed into indexscan

**Contents**

**Related work**

**Comment by wey-gu** [comment]
@jievince how about `MATCH ()-[e:follow]->() RETURN e LIMIT 10`, please?

**Comment by jievince** [comment]
Not supported.  Better to use lookup

**Comment by wey-gu** [comment]
> Not supported. Better to use lookup

Got it, thanks @jievince
