### ISSUE TITLE
graphd cannot run properly when missing storage service

### ISSUE THREAD

**Issue by alanlinyi** [vesoft-inc/nebula#503]
**Describe the bug(__must be provided__)**
when using console first time and not configuring the storage by "add hosts" command, the graphd process will be down always.

**Your Environments(__must be provided__)**
  * OS: Linux ubuntu-18 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  * Compliler: g++ (GCC) 8.2.0

  * CPU: 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          06/55
Stepping:            2
CPU MHz:             1799.958
BogoMIPS:            3600.06
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti intel_ppin fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt clwb xsaveopt xsavec xgetbv1 xsaves pku ospke

**How To Reproduce(__must be provided__)**
  1. make a new install
  2. create space test; use test; create tag test(id string) 
  3. insert vertex test(id) values 100:("100")

**Expected behavior**
under the circumstances, graphd should not be down 
**Additional context**

**Comment by dutor** [comment]
This issue has already been resolved via disallowing to create space without storage service available or registered.
