### ISSUE TITLE
Can we add a hint that we must use $^ to quote the alias before the pipe operator (|)

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula#5044]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/78209557/206956998-d653db40-a6dc-4b50-b31b-a42df94bccab.png">

**Comment by yixinglu** [comment]
In the nebula kernel, we could not differentiate the vid in above example since the string vid, such as "A", and `$-.A` is valid for the GO sentence. In addition, the two sentences have different meanings, the first one represents the cross join and the second represents the inner join.

**Comment by abby-cyber** [comment]
OK~
