### ISSUE TITLE
session's UpdateTime is wrong

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5059]
**Please check the FAQ documentation before raising an issue**

when I connect to graph, and show sessions, the session's UpdateTime is wrong, it correct when I wait some seconds
UpdateTime is *1970-01-01T00:00:00.000000*

```txt
(root@nebula) [(none)]> show sessions;
+------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
| SessionId        | UserName | SpaceName    | CreateTime                 | UpdateTime                 | GraphAddr            | Timezone | ClientIp        |
+------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
| 1671092534276357 | "root"   | ""           | 2022-12-15T08:22:14.276357 | 2022-12-15T08:22:14.332270 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092523801353 | "root"   | ""           | 2022-12-15T08:22:03.801353 | 2022-12-15T08:22:03.938307 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092564893786 | "root"   | ""           | 2022-12-15T08:22:44.893786 | 2022-12-15T08:22:44.948130 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092575025790 | "root"   | ""           | 2022-12-15T08:22:55.025790 | 2022-12-15T08:22:55.079422 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092534001294 | "root"   | ""           | 2022-12-15T08:22:14.001294 | 2022-12-15T08:22:14.194813 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092544510864 | "root"   | "my_space_2" | 2022-12-15T08:22:24.510864 | 2022-12-15T08:22:24.568660 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671092554754751 | "root"   | "my_space_3" | 2022-12-15T08:22:34.754751 | 2022-12-15T08:22:34.814110 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
| 1671099211381468 | "root"   | ""           | 2022-12-15T10:13:31.381468 | 1970-01-01T00:00:00.000000 | "graph-0.graph:9669" | 0        | "10.60.71.175"  |
| 1671092534385406 | "root"   | ""           | 2022-12-15T08:22:14.385406 | 2022-12-15T08:22:14.440567 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
+------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
Got 9 rows (time spent 600/1133 us)

Thu, 15 Dec 2022 18:13:31 CST
```
**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id v3.1.0 ent and ent-nightly

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by porscheme** [comment]
> **Please check the FAQ documentation before raising an issue**
> 
> when I connect to graph, and show sessions, the session's UpdateTime is wrong, it correct when I wait some seconds UpdateTime is _1970-01-01T00:00:00.000000_
> 
> ```
> (root@nebula) [(none)]> show sessions;
> +------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
> | SessionId        | UserName | SpaceName    | CreateTime                 | UpdateTime                 | GraphAddr            | Timezone | ClientIp        |
> +------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
> | 1671092534276357 | "root"   | ""           | 2022-12-15T08:22:14.276357 | 2022-12-15T08:22:14.332270 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092523801353 | "root"   | ""           | 2022-12-15T08:22:03.801353 | 2022-12-15T08:22:03.938307 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092564893786 | "root"   | ""           | 2022-12-15T08:22:44.893786 | 2022-12-15T08:22:44.948130 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092575025790 | "root"   | ""           | 2022-12-15T08:22:55.025790 | 2022-12-15T08:22:55.079422 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092534001294 | "root"   | ""           | 2022-12-15T08:22:14.001294 | 2022-12-15T08:22:14.194813 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092544510864 | "root"   | "my_space_2" | 2022-12-15T08:22:24.510864 | 2022-12-15T08:22:24.568660 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671092554754751 | "root"   | "my_space_3" | 2022-12-15T08:22:34.754751 | 2022-12-15T08:22:34.814110 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> | 1671099211381468 | "root"   | ""           | 2022-12-15T10:13:31.381468 | 1970-01-01T00:00:00.000000 | "graph-0.graph:9669" | 0        | "10.60.71.175"  |
> | 1671092534385406 | "root"   | ""           | 2022-12-15T08:22:14.385406 | 2022-12-15T08:22:14.440567 | "graph-0.graph:9669" | 0        | "10.60.157.128" |
> +------------------+----------+--------------+----------------------------+----------------------------+----------------------+----------+-----------------+
> Got 9 rows (time spent 600/1133 us)
> 
> Thu, 15 Dec 2022 18:13:31 CST
> ```
> 
> **Describe the bug (**required**)**
> 
> **Your Environments (**required**)**
> 
> * OS: `uname -a`
> * Compiler: `g++ --version` or `clang++ --version`
> * CPU: `lscpu`
> * Commit id v3.1.0 ent and ent-nightly
> 
> **How To Reproduce(**required**)**
> 
> Steps to reproduce the behavior:
> 
> 1. Step 1
> 2. Step 2
> 3. Step 3
> 
> **Expected behavior**
> 
> **Additional context**

Look at the data, how can we tell if a session active?

**Comment by porscheme** [comment]
Looking at the data, how can we tell if a session is still?

**Comment by Aiee** [comment]
> Looking at the data, how can we tell if a session is still?

All sessions you see in the `SHOW SESSIONS` output are alive. Expired sessions will be cleaned periodically.

**Comment by porscheme** [comment]
> > Looking at the data, how can we tell if a session is still?
> 
> All sessions you see in the `SHOW SESSIONS` output are alive. Expired sessions will be cleaned periodically.

We see lot of sessions with below python code snippet, python client SDK. It it a product bug?

```
with connection_pool.session_context(nebula_user, nebula_psw, True) as session:
   resp = session.execute(query)
   # rest of he code
    
```
