### ISSUE TITLE
Logical expression simplification

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#5067]
**Introduction**

e.g.
`xxx or false` should be rewritten into `xxx`,
`xxx or true` should be rewritten into `true`.
Refer to https://github.com/vesoft-inc/nebula/pull/5062#discussion_r1049718493

**Contents**

**Related work**

**Comment by veezhang** [comment]
It's also for `and` ?
`xxx and false` to `false`.
`xxx and true` to `xxx`.

**Comment by jievince** [comment]
> It's also for `and` ? `xxx and false` to `false`. `xxx and true` to `xxx`.

Of course.
