### ISSUE TITLE
When refreshing data every day,  once the index is abnormal, the query of the entire graph will fail

### ISSUE THREAD

**Issue by lisahui** [vesoft-inc/nebula#5071]
Details

- NebulaGraph: v2.6.x

- Machine configuration: 3 physical machines, the order of magnitude is only one million, SSD

Description: I use the asset graph. In practice, I found that the storage and query of asset data in the graph may not be completely compatible. 

Stability problem: When refreshing data every day, once the index is abnormal, the query of the entire graph will fail.

**Comment by Sophie-Xie** [comment]
Close it first, reopen if it reappears.
