### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5072]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
Cannot run nebula as none-root  user

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

Add 1000 nebula user and grant permission to /usr/local/nebula
```
FROM vesoft/nebula-storaged:v3.3.0

ARG BRANCH
ARG REGION
ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=nebula

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME --no-log-init

# SET read, write, and execute
RUN chmod 777 /usr/local/nebula
RUN chown -R $USERNAME /usr/local/nebula

USER $USERNAME
WORKDIR /usr/local/nebula
```

**Expected behavior**

**Additional context**

```
++ hostname
++ hostname
+ exec /usr/local/nebula/bin/nebula-storaged --flagfile=/usr/local/nebula/etc/nebula-storaged.conf --meta_server_addrs=nebula-cluster-metad-0.nebula-cluster-metad-headless.graph.svc.cluster.local:9559,nebula-cluster-metad-1.nebula-cluster-metad-headless.graph.svc.cluster.local:9559,nebula-cluster-metad-2.nebula-cluster-metad-headless.graph.svc.cluster.local:9559 --local_ip=nebula-cluster-storaged-2.nebula-cluster-storaged-headless.graph.svc.cluster.local --ws_ip=nebula-cluster-storaged-2.nebula-cluster-storaged-headless.graph.svc.cluster.local --daemonize=false
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20221216-215655.1!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20221216-215655.1!Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20221216-215655.1!E20221216 21:56:55.942567     1 StorageDaemon.cpp:79] Failed to create or open `logs/storaged-stdout.log': Permission denied
```

**Comment by Shylock-Hg** [comment]
It's seems  in container, I think you could run as root directly.

**Comment by porscheme** [comment]
> It's seems in container, I think you could run as root directly.

Why run the container as root? Running the container as root is a security risk?

**Comment by Shylock-Hg** [comment]
> > It's seems in container, I think you could run as root directly.
> 
> Why run the container as root? Running the container as root is a security risk?

Run as root in container.

**Comment by porscheme** [comment]
> > > It's seems in container, I think you could run as root directly.
> > 
> > 
> > Why run the container as root? Running the container as root is a security risk?
> 
> Run as root in container.

@Shylock-Hg are you suggesting run as root? If yes, do you know its security risk?

**Comment by Shylock-Hg** [comment]
> > > > It's seems in container, I think you could run as root directly.
> > > 
> > > 
> > > Why run the container as root? Running the container as root is a security risk?
> > 
> > 
> > Run as root in container.
> 
> @Shylock-Hg are you suggesting run as root? If yes, do you know its security risk?

Not sure, but I think run as root in container is ok.
