### ISSUE TITLE
Provide a set of smoke test

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#508]
It's better to provide a smoke test set to cover basic functionality.

Start nebula service on one or two host, create a graph space and check basic operations: 
show drop create spaces;
create desc show drop tags/edges;
insert update remove tags/edges;
go ;

With the basic smoke test (and unit test), we could give more minor releases to the urgent users.

**Comment by sherman-the-tank** [comment]
This probably needs a fairly well designed test framework. But I agree, we definitely need this as soon as possible
