### ISSUE TITLE
The backticks do not match.

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula#5092]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

There are many places in the code where the backticks don't match.

Can use `grep -ri "\"'" ./src ` to find it.

For examples:
```
(root@nebula) [nba]> """
                  ->       MATCH (v1:player{name: "Danny Green"}) -[:like_not_exists]- (v2)
                  ->       RETURN v1.player.name AS Name, v2.player.name AS Friend
                  ->       """
[ERROR (-1009)]: SemanticError: `like_not_exists': Unknown edge type
```

It's should be 
```
[ERROR (-1009)]: SemanticError: `like_not_exists': Unknown edge type
=>
[ERROR (-1009)]: SemanticError: `like_not_exists`: Unknown edge type
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
won't fix
