### ISSUE TITLE
graphd report unexpected error `Wrong type result, the type should be NULL, EMPTY, BOOL`

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5097]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Similar to #1574 but that's a fixed issued and we are using the latest master branch.
While executing the following query, graph report an unexpected error:

```txt
(root@nebula) [gdlancer]> MATCH p0 = (v0)-[e0]->()<-[e1:Rel_2]-(v1) WHERE (id(v0) in [13, 11, 20, 21, 2, 23, 28, 27, 9, 14, 19]) AND (e0.Rel_0_0_Bool) UNWIND nodes(p0) AS ua0 WITH e0, ua0.Label_0.Label_0_3_Bool AS pa0, ua0, 0.915546 AS pa1 WHERE ua0.Label_0.Label_0_3_Bool RETURN count(*) as totalRows
[ERROR (-1005)]: Wrong type result, the type should be NULL, EMPTY, BOOL

Mon, 12 Dec 2022 18:52:51 CST

(root@nebula) [gdlancer]>
```

In contrast the same query Neo4j reports no error:

```txt
$ MATCH p0 = (v0)-[e0]->()<-[e1:Rel_2]-(v1) WHERE (v0.id in [13, 11, 20, 21, 2, 23, 28, 27, 9, 14, 19]) AND (e0.Rel_0_0_Bool) UNWIND nodes(p0) AS ua0 WITH e0, ua0.Label_0_3_Bool AS pa0, ua0, 0.915546 AS pa1 WHERE ua0.Label_0_3_Bool RETURN count(*) as totalRows

╒═══════════╕
│"totalRows"│
╞═══════════╡
│1          │
└───────────┘
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 573f7f414 (community edition)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by xtcyclist** [comment]
This is another bug on property prunning.

**Comment by xtcyclist** [comment]
This is related to the usage of `NullType::BAD_TYPE`, which we have decided to keep the status quo. I've improved the error message to remind users to write <boolean condition> == <true/false> to bypass this. Not going to apply further fixes.
