### ISSUE TITLE
graphd crash when executing updateSessionsToMeta

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#5109]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

https://discuss.nebula-graph.com.cn/t/topic/11670/6

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by jiangtao1234ji** [comment]
又出现了这个问题，我发现是在我大规模导数之后就会出现，但不知道是几天后出现，这个时间不固定，但是我只要一导数就一定会出现graphd挂掉的情况，数据量大多都在几亿。
导数后会做compact操作和stats操作。

**Comment by xtcyclist** [comment]
Nothing suspicious found on the crahsed code. Probabaly something went wrong on the memory. Need more infomration on what have been executed on the graphd when the crash happened, and need coredumps on each crash encountered. Need to know whether the graphd crash at the same place everytime.

**Comment by xtcyclist** [comment]
Closed this issue since we haven't got sufficient information since Jan. Please feel free to reopen this if you have more information.
