### ISSUE TITLE
UNION bug

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#5113]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
The following sentence reports a syntax error.
```
    UNWIND [1,2] AS a RETURN a
    UNION ALL
    RETURN 2 AS a
```

While the following could executed successfully:
```
      UNWIND [1,2] AS a RETURN a
      UNION ALL
      UNWIND [2] AS a RETURN a
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
marked as known issue
