### ISSUE TITLE
[TTL] Historical data may never expire

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#5131]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

```
create tag ttl_tag1(age int);
insert vertex ttl_tag1(age) VALUES "1":(10),"2":(20),"3":(30);
alter tag ttl_tag1 add (ttl timestamp default now());
alter tag ttl_tag1 ttl_duration=10, ttl_col="ttl";
insert vertex ttl_tag1(age) VALUES "4":(40);
match (v:ttl_tag1) return v limit 10;
```
After the above series of operations. The `ttl_tag1` of "1", "2" and "3" will never expire.

This is because there is a problem with our definition of `default`. In this case, the default value of `ttl` is `now()`. `now()`, which will be stored in the definition of `ttl` (it is the function `now()`, not the return value of it). 

When we read a `ttl` if the property does not exist in tag1.ttl, it will get the default value from the schema definition. So for `ttl_tag1` of "1", "2" and "3", the latest `now()` will be calculated every time when reading, so they will never expire.

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by cangfengzhs** [comment]
Here is a relatively reasonable repair plan. We define two default values for each property, `default_read_value` and `default_write_value`.

When we define a `DEFAULT`, we assign it to both `default_read_value` and `default_write_value`. However, the difference is that `default_read_value` must be a constant, and `default_write_value` is the actually defined `DEFAULT`.

In the above case, default_read_value stores the actual time (the return value of `now()`) when `ttl` is defined, and default_write_value stores the `now()` function itself.

Later, in the process of using ttl, if it is found that there is no ttl attribute when reading its value, it will be filled with default_read_value. If no ttl value is given when writing, it will be filled with default_write_value.

**Comment by cangfengzhs** [comment]
And, if the value of property `ttl`is `NULL`, tag also never expire.

**Comment by cangfengzhs** [comment]
Another relatively simple repair method is to prohibit the use of "now()" as the default value on the ttl column, and do not allow the value to be NULL

**Comment by cangfengzhs** [comment]
@critical27 @yixinglu

**Comment by cangfengzhs** [comment]
@MuYiYong

**Comment by critical27** [comment]
I suggest forbid use a default value of now, in `alter tag ttl_tag1 add (ttl timestamp default now());`

**Comment by HarrisChu** [comment]
prefer to mark as a known issue.
and we could re-design in v5.0

**Comment by Sophie-Xie** [comment]
@abby-cyber discussed it with @MuYiYong offline: he suggested to update doc.
