### ISSUE TITLE
Desc not existed user should report error

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula#5141]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Found in https://github.com/vesoft-inc/nebula/pull/5139

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
what's the current behavior?

**Comment by Shylock-Hg** [comment]
> what's the current behavior?

Empty result.

**Comment by Milittle** [comment]
Can i try this? thx
