### ISSUE TITLE
[TTL] Data will not be visible when duration+ttl overflow

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#5143]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

```
CREATE TAG ttl_expire_tag01(a timestamp, b int) ttl_duration=9223372036854775807, ttl_col="a";
INSERT VERTEX ttl_expire_tag01(a,b) VALUES "1":(now(),10);
match (v:ttl_expire_tag01) return v limit 10;  // not visiable

```
**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
marked as known issue
