### ISSUE TITLE
Balancer

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#515]
* Balance will generate balance plan according to current active hosts and parts allocation
 * For the plan, we hope after moving the least parts , it will reach a reasonable state.
 * Only one balance plan could be invoked at the same time.
 * Each balance plan has one id,  and we could show the status by "balance id" command and after FO, we could go on the balance plan by type "balance id"
 * Each balance plan contains many balance tasks,  the task represents the minimum movement unit.
 * We save the whole balancePlan state in kvstore to do failover.
 * Each balance task contains serval steps. And it should be executed step by step.  
 * One task failed will result in the whole balance plan failed.  
 * Currently, we hope tasks for the same part could be invoked serially

This is subtask of #182

**Comment by sherman-the-tank** [comment]
I wonder if we want to introduce the **RESOURCE GROUP**/**HOST GROUP** concept. We can talk about it offline

**Comment by dangleptr** [comment]
let's close it now.  The balancer on meta has been finished.
