### ISSUE TITLE
Incorrect result on edge list join query

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#5154]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Look at the query below:

```txt
(root@nebula) [gdlancer]> match (v1)-[e*1..2]->(v2) where id(v1) in [6] match (v2)-[e*1..2]->(v1) return count(*)
+----------+
| count(*) |
+----------+
| 0        |
+----------+
Got 1 rows (time spent 2.736ms/16.574125ms)

Thu, 29 Dec 2022 14:03:49 CST
```

We can see that Nebula return no result, if we change the return clause into `return size(e)`,  it shows that there are 6 rows in the result:

```txt
(root@nebula) [gdlancer]> match (v1)-[e*1..2]->(v2) where id(v1) in [6] match (v2)-[e*1..2]->(v1) return size(e)
+---------+
| size(e) |
+---------+
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
+---------+
Got 6 rows (time spent 2.583ms/18.1315ms)

Thu, 29 Dec 2022 14:05:48 CST
```

 in contrast the same query on the same dataset in Neo4j return 6 rows:

```txt
$ match (v1)-[e*1..2]->(v2) where v1.id in [6] match (v2)-[e*1..2]->(v1) return count(*)

╒══════════╕
│"count(*)"│
╞══════════╡
│6         │
└──────────┘
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 967a8c9e0 (community edition)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by xtcyclist** [comment]
A bug from pruning properties.

**Comment by xtcyclist** [comment]
![image](https://user-images.githubusercontent.com/7731943/209929265-f845998c-f6d3-42af-b88a-869df46780c2.png)

**Comment by xtcyclist** [comment]
Bug from `RemoveAppendVerticesBelowJoinRule`.

**Comment by xtcyclist** [comment]
```
(root@nebula) [test]> match (v1)-[e*1..2]->(v2) where id(v1) in [6] match (v2)-[e*1..2]->(v1) return size(e)
+---------+
| size(e) |
+---------+
| 1       |
| 1       |
| 1       |
| 1       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
| 2       |
+---------+
Got 16 rows (time spent 357346/357603 us)

Thu, 29 Dec 2022 20:57:58 CST

(root@nebula) [test]> match (v1)-[e*1..2]->(v2) where id(v1) in [6] match (v2)-[e*1..2]->(v1) return count(*)
+----------+
| count(*) |
+----------+
| 16       |
+----------+
Got 1 rows (time spent 297718/297931 us)
```

I'm not sure what happened. But the results are ok now. Tring some other data set.

**Comment by xtcyclist** [comment]
@kikimo , please help verify whether this bug still exists....

**Comment by xtcyclist** [comment]
Seems fixed by this PR: https://github.com/vesoft-inc/nebula/commit/a0fc21a0e93efae1249498e5f4d6dbffbfa2e9b8

I'm not sure why.
