### ISSUE TITLE
Why the leader host is empty in response from candidate meta server 

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#5158]
**General Question**

For meta client, it will retry the request when happen leader change error. When retrying, it will obtain the leader information from the response returned by the current server, and to update the connection between the client and the server to resend the request.
But when current server connected by client is CANDIDATE, the leader host in response is Empty. Why? is it by design or a bug.

**Comment by Nicole00** [comment]
related code：
https://github.com/vesoft-inc/nebula/blob/408d731d564837c9fcd156a26048445bf89dae93/src/kvstore/raftex/RaftPart.cpp#L960-L972

**Comment by HarrisChu** [comment]
it is by design, when timeout, should start leader election, and the leader is empty.
