### ISSUE TITLE
desc tag does not show the comment info

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula#5179]
![image](https://user-images.githubusercontent.com/16240361/210296868-4d914ac9-b818-4768-b975-25beac89639c.png)

**Comment by critical27** [comment]
The comment in tag is different from the tag in property. You need to use the query `show create tag t`.

> BTW, it seems we don't support alter comment in property for now

**Comment by critical27** [comment]
![image](https://user-images.githubusercontent.com/13706157/210492989-fea6256f-8ea8-4bea-a620-267cc711359f.png)

**Comment by jinyingsunny** [comment]
prop comment is different from tag comment😊
