### ISSUE TITLE
match two tag can attribute filtering

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5184]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

![1](https://user-images.githubusercontent.com/42446055/210298898-3816c8e4-ba3c-4f73-8bd1-b3d5a03e90e4.png)

this is doc url
[https://docs.nebula-graph.com.cn/master/3.ngql-guide/7.general-query-statements/2.match/](url)

it should be not supported

```txt

(root@nebula) [basketballplayer]> match (v1:player:team) where v1.player.name=="Tim Duncan" return v1 limit 10;
+----+
| v1 |
+----+
+----+
Empty set (time spent 1394/1694 us)

Tue, 03 Jan 2023 11:53:16 CST
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id `86a551c, 3.4.0-ent`

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by xtcyclist** [comment]
This is not a problem with the community version. Close this issue.
