### ISSUE TITLE
 The query returns too much data, causing the console to hang, and the graph log reports an error

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5191]
**Describe the bug (__required__)**

space: sf1000

nGQL:  lookup on Person yield id(vertex) as vid | limit 500000 | go from $-.vid over LIKES  yield distinct LIKES._src as src, LIKES._dst as dst

log:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/72034305/199501414-1bb6fe6b-1cc0-43f1-80fc-ed3080015588.png">

**Comment by Shylock-Hg** [comment]
https://github.com/vesoft-inc/nebula-cpp/blob/ee8d36add01c5e900d813fa9ab107ae114441cc4/src/client/Connection.cpp#L118
cpp client already use `THeaderProtocol`
