### ISSUE TITLE
drop space while rebuilding tag index drop, storage offline

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5217]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
![lQLPJx-i5gmH7BjNBDzNBcOw61FNMIhJo1cDs0-LY4DeAA_1475_1084 png_720x720q90g](https://user-images.githubusercontent.com/42446055/211006267-523be030-6634-4891-bbe0-27fc0bd0bc2d.jpg)

meta can not receive storage's heartbeat
![L1VzZXJzL2d1amlhd2VpL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy8zNTY3MjE0NDJfdjIvSW1hZ2VGaWxlcy8xNjczMDAzNTQ2NDA1XzkyRDcwNTIxLTY3OEQtNDVGRC04QzMwLThDRTEzODAwNEFGQy5wbmc=](https://user-images.githubusercontent.com/42446055/211006298-0812bdff-1d64-44eb-93b3-20ab00683b77.png)

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
Discuss with @critical27 offline: it's ok for open source edition.
