### ISSUE TITLE
Can't match any vertex

### ISSUE THREAD

**Issue by zyxdSTU** [vesoft-inc/nebula#5222]
Hello friends.
I have already create a vertex **关系8_关系9_vertex** , and the tag of it is  **relation_concept**.
But the query sql can't match any things `` match (n:relation_concept) return n limit 3;``
![image](https://user-images.githubusercontent.com/26239665/211253751-90da6a22-4454-4db9-9a9b-d92c0cc07bfc.png)

![image](https://user-images.githubusercontent.com/26239665/211253934-04b85ace-6450-41a2-97f0-a6a827960085.png)

Can someone help me. Thanks.

**Comment by czpmango** [comment]
Please rebuild the tag index on `relation_concept`.

**Comment by zyxdSTU** [comment]
> 

I have already rebuilded the index of ``relation_concept``. The problem is solved.  Thanks.
And I have another question, When need to rebuild the index, the time of index created or the time of index update .

**Comment by wey-gu** [comment]
> > 
> 
> I have already rebuilded the index of `relation_concept`. The problem is solved. Thanks. And I have another question, When need to rebuild the index, the time of index created or the time of index update .

The index data will be created during the data insert/update when its schema(index definition) exists.
For those data inserted before the index definition exists, we need to explicitly let it create with the index rebuild command.
