### ISSUE TITLE
The result of property-accessing expression is incorrect

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#5226]
**Describe the bug (__required__)**
As title.

**Your Environments (__required__)**
nebula v3.3.0

**How To Reproduce(__required__)**
```
(root@nebula) [nba]> match (v:player)-[e]->(n) with {key:v} as m return m.key.player.age limit 3
+------------------+
| m.key.player.age |
+------------------+
| __NULL__         |
| __NULL__         |
| __NULL__         |
+------------------+
Got 3 rows (time spent 17007/17372 us)
```

**Expected behavior**
Get the correct property.

**Comment by czpmango** [comment]
https://github.com/vesoft-inc/nebula/pull/5054

**Comment by czpmango** [comment]
We should consider another way to fix this issue https://github.com/vesoft-inc/nebula/issues/5051

**Comment by xtcyclist** [comment]
The unwind problem as reported in https://github.com/vesoft-inc/nebula/issues/5051 remain fixed by rewriting the expression. Other issues (e.g., ListComprehension) fixed by https://github.com/vesoft-inc/nebula/pull/5054 are going to be opened by https://github.com/vesoft-inc/nebula/pull/5229.

**Comment by xtcyclist** [comment]
```
      MATCH p = (n:player{name:"LeBron James"})-[:like]->(m)
      RETURN nodes(p)[0].player.age AS age1,
             nodes(p)[1].player.age AS age2,
             reduce(x = 10, n IN nodes(p) | n.player.age - x) AS x
```

While fixing this issue, please take a note that queries like the above need to be ok to run.

**Comment by czpmango** [comment]
> MATCH p = (n:player{name:"LeBron James"})-[:like]->(m)
>       RETURN nodes(p)[0].player.age AS age1,
>              nodes(p)[1].player.age AS age2,
>              reduce(x = 10, n IN nodes(p) | n.player.age - x) AS x

Ok.
