### ISSUE TITLE
Graphd crash 

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#5236]
**Your Environments**
nebula 3.3.0

**How To Reproduce**
```
go 3 steps from "Tim Duncan" over like,serve where (serve.start_year>2000 or like.likeness>90) and labels($$)[0]=="player" and $$.player.age>40 yield $$ as v
```

**Expected behavior**
Get the correct query result.

**Comment by xtcyclist** [comment]
We have around 2 days to fix this. I'd like to opt for a quick solution that avoids this crash and similar crashes due to the same reason. Leave a root fix into the later version.

**Comment by xtcyclist** [comment]
A similar crash query provided by @czpmango : `match (v:player) where $$.player.age>40 return v`

**Comment by xtcyclist** [comment]
This will not crash but report a wrong result in the Release mode, as it runs into a `DLOG(FATAL)`.

**Comment by xtcyclist** [comment]
This is a very good catch. Exposed a whole type of problems that we need to address in 3.5 and avoid in 5.0.
