### ISSUE TITLE
Why user's query is persisted in meta?

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#5245]
When I import data recently, I found that QUITE A LOT query is persisted in meta. Why we do that? Here is a wal of **meta**: lots of DML in it. In my env, the size of meta's wal is almost 15G, even bigger than storage... 

![image](https://user-images.githubusercontent.com/13706157/211488529-5a732469-b835-433c-a3be-34ddfb08ef6f.png)

The query is persisted by session.
![image](https://user-images.githubusercontent.com/13706157/211489893-555ffd69-faab-43dc-9d0d-e77c3a84afbc.png)

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula-ent/pull/2240
