### ISSUE TITLE
`IF NOT EXISTS` does not work in `CLONE GRAPH`

### ISSUE THREAD

**Issue by thewkgithub** [vesoft-inc/nebula#5252]
(root@nebula) [basketballplayer]> CREATE SPACE IF NOT EXISTS my_space_1 (vid_type=FIXED_STRING(30));
Execution succeeded (time spent 514µs/715.735µs)

(root@nebula) [basketballplayer]> CREATE SPACE IF NOT EXISTS my_space_2 AS my_space_1;
Execution succeeded (time spent 879µs/1.085528ms)

(root@nebula) [basketballplayer]> CREATE SPACE IF NOT EXISTS my_space_2 AS my_space_1;
[ERROR (-1005)]: Existed!

1. 先创建一个图空间, my_space_1
2. 使用克隆的方式, 去克隆出来my_space_2, 此时my_space_2不存在, 克隆成功.
3. 再克隆一次, 也就是当前图空间中存在my_space_2了, 此时再克隆就报-1005了.. 

说明在克隆图空间的时候, `IF NOT EXISTS`这个选项是无效的.和预期不一致.

**Comment by thewkgithub** [comment]
Version 3.3.0

**Comment by pengweisong** [comment]
@MuYiYong Should we ban the `IF NOT EXISTS` when clone space? Think about the case:
1. We have a Space B, which has different SpaceSpec with Space A
2. Now we execute  `CREATE SPACE IF NOT EXISTS B AS A;` , if we return SUCCESS, it may have some problem: the A and B do not have the same SpaceSpec indeed.

**Comment by thewkgithub** [comment]
确实，哈哈。怎么想都不对。
