### ISSUE TITLE
Is there pyspark api for nebula graph?

### ISSUE THREAD

**Issue by manyfeatures** [vesoft-inc/nebula#5257]
Hi! 
What is the proper way to work with Nebula algorithms on PySpark?
For example if I want to compute nodes centrality and then filter them by some condition, how can it be done?
There seems to be only Scala/Spark/ngql interface

**Comment by wey-gu** [comment]
I'll try a Nebula Algorithm PySpark later when I got bandwidth to do and share here/in algo repo/docs

**Comment by manyfeatures** [comment]
Hi! Is there any update? maybe someone has an example how to use graphframes with nebula-graph?

**Comment by wey-gu** [comment]
> Hi! Is there any update? maybe someone has an example how to use graphframes with nebula-graph?

ref: https://github.com/wey-gu/nebula-up/blob/main/spark/pagerank_example.ipynb

ref: https://github.com/wey-gu/nebulagraph-ai
