### ISSUE TITLE
Support clusterID

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#526]
ClusterID is used to distinguish whether the storage server is belonged to the meta server with the same cluster. 

If storage server connect to the other cluster's meta server,  the request will be rejected.

**Comment by sherman-the-tank** [comment]
> If storage server connect to the other cluster's meta server, the request will be rejected.

Does this mean that the cluster Id has to be globally unique?

**Comment by dangleptr** [comment]
> > If storage server connect to the other cluster's meta server, the request will be rejected.
> 
> Does this mean that the cluster Id has to be globally unique?

Exactly!

**Comment by whitewum** [comment]
does it happen when one data center deploys two nebula service?
so DBA has to remember to change the second nebula-service's default ClusterID?
