### ISSUE TITLE
Support the tck format for the output of EXPLAIN

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula#5274]
An idea from @Shylock-Hg 

In the nebula-console, when explaining the query, support the specification of the tck format, so that the generated outputs could be used in tck feature files directly.

```
      EXPLAIN FORMAT = "TCK" MATCH (v1:player)-[:like*2..2]->(v2)-[e3:like]->(v4) where id(v1) == "Tony Parker"
      OPTIONAL MATCH (v3:player)-[:like]->(v1)<-[e5]-(v4)
      with v1, v2, e3, v4, e5, v3 where id(v3) == "Tim Duncan" or id(v3) is NULL
      return *
```

```
      | id | name           | dependencies | profiling data | operator info |
      | 22 | Project        | 18           |                |               |
      | 18 | Filter         | 14           |                |               |
      | 14 | HashLeftJoin   | 7,13         |                |               |
      | 7  | project        | 6            |                |               |
      | 6  | AppendVertices | 5            |                |               |
      | 5  | Traverse       | 20           |                |               |
      | 20 | Traverse       | 2            |                |               |
      | 2  | Dedup          | 1            |                |               |
      | 1  | PassThrough    | 3            |                |               |
      | 3  | Start          |              |                |               |
      | 13 | Project        | 21           |                |               |
      | 21 | AppendVertices | 11           |                |               |
      | 11 | Traverse       | 10           |                |               |
      | 10 | AppendVertices | 9            |                |               |
      | 9  | Traverse       | 8            |                |               |
      | 8  | Argument       |              |                |               |
```

**Comment by wey-gu** [comment]
ref: other existing formats https://docs.nebula-graph.io/3.3.0/3.ngql-guide/17.query-tuning-statements/1.explain-and-profile/

**Comment by AntiTopQuark** [comment]
Hello, has the task been assigned? If not, can I try it?

**Comment by Shylock-Hg** [comment]
> Hello, has the task been assigned? If not, can I try it?

Welcome!

**Comment by wey-gu** [comment]
Feel free to take it @AntiTopQuark, don't hesitate to ask for helps here :)

**Comment by AntiTopQuark** [comment]
> Feel free to take it @AntiTopQuark, don't hesitate to ask for helps here :)

thx~I will try my best to do this well.

**Comment by swastik959** [comment]
hi i am new to open source and and to contribute to this issue can you please explain and guide me about this issue

**Comment by AntiTopQuark** [comment]
> hi i am new to open source and want to contribute to this issue can you please explain and guide me about this issue

I'm very sorry, but this task has been assigned to me. May I ask if you have already started.

**Comment by swastik959** [comment]
> > hi i am new to open source and want to contribute to this issue can you please explain and guide me about this issue
> 
> I'm very sorry, but this task has been assigned to me. May I ask if you have already started.

@AntiTopQuark no

**Comment by AntiTopQuark** [comment]
I'm very sorry, I've been a bit busy for a while and I've only just finished this pr.
https://github.com/vesoft-inc/nebula/pull/5414
I have a question: When specifying the output in `tck` format, do you still need to print the execution plan
The current situation is as follows：
![2023-03-19-180945](https://user-images.githubusercontent.com/32798045/226172775-eadb83c7-ec63-41c2-a4d4-6caa4706654e.png)

Thank you very much!

**Comment by AntiTopQuark** [comment]
> 
Thank you very much for your response. I would like to confirm the behavior of this requirement again. @xtcyclist @jievince 
- For the case of `explain format = 'tck'`, I think there are two options:
    - Only print the execution plan (although it contradicts the original requirement description), and print the execution plan in row format.
    - Do not support `explain format = 'tck'`.
- For the case of `profile format = 'tck'`, print the execution results in TCK format.Then when printing the execution plan, should we use the TCK format or the row format?

**Comment by jievince** [comment]
I think the format `tck` is not only for `execution plan` but also for `result table`.
So for `explain format = 'tck'`, I think we should print the execution plan in tck fomat,
and for `profile format='tck'`, I think we should print both the result table and the execution plan in tck format.

@AntiTopQuark @xtcyclist @Shylock-Hg , What do you think?

**Comment by jievince** [comment]
> > 
> 
> Thank you very much for your response. I would like to confirm the behavior of this requirement again. @xtcyclist @jievince
> 
> * For the case of `explain format = 'tck'`, I think there are two options:
>   
>   * Only print the execution plan (although it contradicts the original requirement description), and print the execution plan in row format.
>   * Do not support `explain format = 'tck'`.
> * For the case of `profile format = 'tck'`, print the execution results in TCK format.Then when printing the execution plan, should we use the TCK format or the row format?

I think the format `tck` is not only for `execution plan` but also for `result table`.
So for `explain format = 'tck'`, I think we should print the execution plan in tck fomat,
and for `profile format='tck'`, I think we should print both the result table and the execution plan in tck format.

@AntiTopQuark @xtcyclist @Shylock-Hg , What do you think?

**Comment by xtcyclist** [comment]
Yes, I agree with @jievince.

The motivation of this issue is to make it easier for developers to add tck test cases like the following. Currently, a developer has to manually write the contents following the exact format so that the script could recognize. This is very time consuming for complex queries. One has to write more than ~10 lines of the execution plan with the names of all the operators and even some execution contexts in json-like format.

```
  Scenario: Test profiling data format
    When profiling query:
      """
      GO 4 STEPS FROM 'Tim Duncan' OVER like YIELD like._dst AS dst | YIELD count(*)
      """
    Then the result should be, in any order:
      | count(*) |
      | 6        |
    And the execution plan should be:
      | id | name         | dependencies | profiling data                                                                                                                                                  | operator info     |
      | 7  | Aggregate    | 6            | {"version":0, "rows": 1}                                                                                                                                        |                   |
      | 6  | Project      | 5            | {"version":0, "rows": 6}                                                                                                                                        |                   |
      | 5  | GetNeighbors | 4            | {"version":0, "rows": 6, "resp[0]": {"vertices": 3}}                                                                                                            |                   |
      | 4  | Loop         | 0            | [{"version":0, "rows": 1},{"version":1, "rows": 1},{"version":2, "rows": 1},{"version":3, "rows": 1}]                                                           | {"loopBody": "3"} |
      | 3  | Dedup        | 2            | [{"version":0, "rows": 2},{"version":1, "rows": 3},{"version":2, "rows": 3}]                                                                                    |                   |
      | 2  | GetDstBySrc  | 1            | [{"version":0, "rows": 2, "resp[0]": {"vertices": 2}},{"version":1, "rows": 3, "resp[0]":{"vertices": 3}}, {"version":2, "rows": 3, "resp[0]":{"vertices": 3}}] |                   |
      | 1  | Start        |              | [{"version":0, "rows": 0},{"version":1, "rows": 0},{"version":2, "rows": 0}]                                                                                    |                   |
      | 0  | Start        |              | {"version":0, "rows": 0}                                                                                                                                        |                   |
```

**Comment by AntiTopQuark** [comment]
@xtcyclist @jievince 
Thank you very much. I think the behavior you described is the most reasonable. 
I have checked many **`·feature`** files, and most of them do not print **`profile data`**. Only a few operators print some **`operator info`**, as shown in the figure below. 
![image](https://user-images.githubusercontent.com/32798045/226517874-e9f916a6-a9b9-4fcb-8683-fa78952cbee1.png)
![image](https://user-images.githubusercontent.com/32798045/226517992-7d98b781-41d3-421d-bd05-6c6f186f4207.png)
The result of an `explain/profile` query statement when format='row' will print the data in full
![image](https://user-images.githubusercontent.com/32798045/226518272-152c538f-0a8f-4195-9c0a-713c9c874816.png)

Next, I would like to look at the relevant source code of tck testing to determine which specific information will be compared when performing the tck test. Then, I can determine what information needs to be printed when format='tck' is specified. 

I expect to complete this task by this weekend.

**Comment by jievince** [comment]
The operator info written in `xxx.feature`  file means we just care about it and so we just want to verify it.
