### ISSUE TITLE
where a >= b bug

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#529]
CREATE TAG player(name string, age int);
CREATE TAG team(name string);
CREATE EDGE serve (start_year int, end_year int);
CREATE EDGE like (likeness double)；

INSERT VERTEX player(name, age) VALUES 100:("Stoudemire", 36);
INSERT VERTEX player(name) VALUES 101:("Vicenta"); 
INSERT VERTEX player(name) VALUES 102:("jummy");
INSERT VERTEX team(name) VALUES 201:("Magic");

INSERT EDGE like (likeness) VALUES 100 -> 101:(90.02);
INSERT EDGE like (likeness) VALUES 101 -> 102:(10);
INSERT EDGE serve (start_year, end_year) VALUES 101 -> 201:(2002, 2010);

try: 
GO FROM 100 OVER like WHERE likeness >= 92. 
the result should be empty. but i get id 101.

try:
GO FROM 100 OVER like WHERE likeness != 92. 
it;s ok

go from 100 over like yield like.likeness                                                       =================                                                                                       | like.likeness |                                                                                       =================                                                                                       |     90.020000 |                                                                                       -----------------   

nebula> describe edge like                                                                              =====================                                                                                   |    Field |   Type |                                                                                   =====================                                                                                   | likeness | double |            

schema is correct. so maybe ">=" is wrong. 

fix the car pls.

.

**Comment by whitewum** [comment]
please add a unit test to cover the bug.

**Comment by laura-ding** [comment]
likeness is a property of edge, the cmd should be `GO FROM 100 OVER like WHERE like.likeness >= 92`

**Comment by whitewum** [comment]
confusing...

**Comment by whitewum** [comment]
in MySQL, like.likeness or likeness is interpreted as a column name. And if u type A > B (where there are no columns named A and B), mysql return " Unknown column 'A' in 'where clause'   ".

Some examples:

mysql> select * from time_zone_name where A > B limit 10;                                                                                                                                                          ERROR 1054 (42S22): Unknown column 'A' in 'where clause'                                                                                                                                                           mysql> select * from time_zone_name where 1 + 1 > 1 limit 10;   --computing 1+1 vs 1                                                                                                                                                      +--------------------+--------------+                                                                                                                                                                              | Name               | Time_zone_id |                                                                                                                                                                              +--------------------+--------------+                                                                                                                                                                              | Africa/Abidjan     |            1 |                                                                                                                                                                              | Africa/Accra       |            2 |                                                                                                                                                                              | Africa/Addis_Ababa |            3 |                                                                                                                                                                              | Africa/Algiers     |            4 |                                                                                                                                                                              | Africa/Asmara      |            5 |                                                                                                                                                                              | Africa/Asmera      |            6 |                                                                                                                                                                              | Africa/Bamako      |            7 |                                                                                                                                                                              | Africa/Bangui      |            8 |                                                                                                                                                                              | Africa/Banjul      |            9 |                                                                                                                                                                              | Africa/Bissau      |           10 |                                                                                                                                                                              +--------------------+--------------+                                                                                                                                                                              10 rows in set (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                             mysql> select * from time_zone_name where "1 + 1" > 1 limit 10;          -- compare string vs int                                                                                                                                  Empty set, 1 warning (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                       mysql> select * from time_zone_name where "1 + 1" > "1" limit 10;          --- compare two string                                                                                                                                        +--------------------+--------------+                                                                                                                                                                              | Name               | Time_zone_id |                                                                                                                                                                              +--------------------+--------------+                                                                                                                                                                              | Africa/Abidjan     |            1 |                                                                                                                                                                              | Africa/Accra       |            2 |                                                                                                                                                                              | Africa/Addis_Ababa |            3 |                                                                                                                                                                              | Africa/Algiers     |            4 |                                                                                                                                                                              | Africa/Asmara      |            5 |                                                                                                                                                                              | Africa/Asmera      |            6 |                                                                                                                                                                              | Africa/Bamako      |            7 |                                                                                                                                                                              | Africa/Bangui      |            8 |                                                                                                                                                                              | Africa/Banjul      |            9 |                                                                                                                                                                              | Africa/Bissau      |           10 |                                                                                                                                                                              +--------------------+--------------+            
 mysql> select * from time_zone_name where "Name" < "name" limit 10;                                                                                                                                                Empty set (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                                  mysql> select * from time_zone_name where "Name" > "name" limit 10;                                                                                                                                                Empty set (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                                  mysql> select * from time_zone_name where "Name" != "name" limit 10;                                                                                                                                               Empty set (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                                  mysql> select * from time_zone_name where "N" != "n" limit 10;                                                                                                                                                     Empty set (0.00 sec)                                                                                                                                                                                                                                                                                                                                                                                                                  mysql> select * from time_zone_name where "N" == "n" limit 10;                                                                                                                                                     ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== "n" limit 10' at line 1                              mysql> select * from time_zone_name where N == n limit 10;                                                                                                                                                         ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== n limit 10' at line 1                                mysql> select * from time_zone_name where N == n limit 10;                                                                                                                                                         ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== n limit 10' at line 1                                mysql> select * from time_zone_name where N == n limit 10;                                                                                                                                                         ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== n limit 10' at line 1                                mysql> select * from time_zone_name where "N" == "n" limit 10;                                                                                                                                                     ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== "n" limit 10' at line 1                              mysql> select * from time_zone_name where "Name" > A limit 10;                                                                                                                                                     ERROR 1054 (42S22): Unknown column 'A' in 'where clause'                                                                                                                                                           mysql> select * from time_zone_name where "Name" > "A" limit 10;                                                                                                                                                   +--------------------+--------------+                                                                                                                                                                              | Name               | Time_zone_id |                                                                                                                                                                              +--------------------+--------------+                                                                                                                                                                              | Africa/Abidjan     |            1 |                                                                                                                                                                              | Africa/Accra       |            2 |                                                                                                                                                                              | Africa/Addis_Ababa |            3 |                                                                                                                                                                              | Africa/Algiers     |            4 |                                                                                                                                                                              | Africa/Asmara      |            5 |                                                                                                                                                                              | Africa/Asmera      |            6 |                                                                                                                                                                              | Africa/Bamako      |            7 |                                                                                                                                                                              | Africa/Bangui      |            8 |                                                                                                                                                                              | Africa/Banjul      |            9 |                                                                                                                                                                              | Africa/Bissau      |           10 |                                                                                                                                                                              +--------------------+--------------+                                                                                                                                                                              10 rows in set (0.00 sec)
