### ISSUE TITLE
Not able to make standalone nebula graph work

### ISSUE THREAD

**Issue by chiru091096** [vesoft-inc/nebula#5296]
I have installed nebulagraph standalone for linux with the below mentioned installation steps. However I'm not able to make the client work.

Installation steps : [Built from source](https://docs.nebula-graph.io/3.3.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/1.install-nebula-graph-by-compiling-the-source-code/)

1. Nebulagraph (**Standalone**)
$ git clone --branch release-3.3 https://github.com/vesoft-inc/nebula.git
$ cd nebula
$ mkdir build && cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/nebula -DENABLE_TESTING=OFF -DENABLE_STANDALONE_VERSION=on - 
     DCMAKE_BUILD_TYPE=Release .. 
$ make -j2
$ sudo make install

2. Nebula cpp client
$ git clone --branch release-3.3 https://github.com/vesoft-inc/nebula-cpp.git
$ cd nebula-cpp
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make
$ sudo make install
$ sudo ldconfig

3. Start the nebula service 
$ sudo /usr/local/nebula/scripts/nebula.service start all

5. Compile example code [(**SessionExample.cpp**)](https://github.com/vesoft-inc/nebula-cpp/blob/release-3.3/examples/SessionExample.cpp)
$ LIBRARY_PATH=/usr/local/nebula/lib:$LIBRARY_PATH g++ -std=c++11 SessionExample.cpp -I/usr/local/nebula/include -lnebula_graph_client -o session_example

6. Run session_example
$ ./session_example

7. I get the below log after the above step and the program doesn't terminate (gets stuck in ConnectionPool init function)
$ Current address : 127.0.0.1:9669

**Comment by SuperYoko** [comment]
Failed to reproduce the issue in release-3.3, can you please give more info? Like standalone info log or config. Or maybe use gcc to debug your code?

**Comment by chiru091096** [comment]
Thank you for verifying. I tried on a different machine and the issue here seems to be that session.valid() returns false. What can be the reason for this

**Comment by chiru091096** [comment]
additionally Storage client example gives below logs
E0203 14:51:19.760186 23090 MetaClient.cpp:211] Send request to meta"127.0.0.1":9559 failed
E0203 14:51:19.760905 23089 MetaClient.cpp:82] List space failed
E0203 14:51:19.760982 23089 MetaClient.cpp:33] load data failed
E0203 14:51:19.761072 23089 MetaClient.cpp:42] Get space id for nba failed
scan edge...

**Comment by chiru091096** [comment]
Additionally StorageClientExample.cpp gives below logs
E0203 15:10:55.648643 14699 MetaClient.cpp:42] Get space id for nba failed
scan edge...

How can I fix this? Also is there any more documentation for nebula cpp usage to create space, executing nGQL commands etc similar to nebula console?

**Comment by wey-gu** [comment]
@chiru091096 could you try to do things with nebula-console or nebula-studio, looks like things are fine now.

With nebula-console, you could type:
`:play basketballplayer`
Then you will have the graph space named basketballplayer as it was mention the most in the docs.

**Comment by chiru091096** [comment]
Hi @wey-gu , 
I'm able to execute mentioned commands with nebula console and it works fine. I'm even able to create new spaces, create verticies, edges etc. However, how can do the same with the nebula cpp client?

**Comment by wey-gu** [comment]
> Hi @wey-gu , I'm able to execute mentioned commands with nebula console and it works fine. I'm even able to create new spaces, create verticies, edges etc. However, how can I do the same with the nebula cpp client?

Yes, it should be equivalent, but one thing that may confuse you is DDL(schema-related queries, including space creation, tag creation, index creation, etc.) won't take effect after the query is executed, it's async and will need (up to) two heartbeats to take effect.

**Comment by chiru091096** [comment]
okay, @wey-gu  thanks for the information. 
Additionally, is there any example code or documentation I can refer to for executing DDL(schema-related queries, including space creation, tag creation, index creation, etc.) operations with nebula cpp client? If you can share it, it'll be very helpful.

**Comment by chiru091096** [comment]
Hi, 
I'm added below code to create space in SessionExample.cpp file

  `  result = session.execute("CREATE SPACE basketballplayer(partition_num=15, replica_factor=1, vid_type=fixed_string(30));");
    if (result.errorCode != nebula::ErrorCode::SUCCEEDED) {
        std::cout << "Exit with error code: " << static_cast<int>(result.errorCode) << std::endl;
        return static_cast<int>(result.errorCode);
    }
    std::cout << *result.data <<std::endl;`

However, executing it results in segmentation fault with bellow logs

*** Aborted at 1675765960 (Unix time, try 'date -d @1675765960') ***
*** Signal 11 (SIGSEGV) (0x0) received by PID 21393 (pthread TID 0x7f898b685ac0) (linux TID 21393) (code: address not mapped to object), stack trace: ***
/usr/local/nebula/lib/libnebula_graph_client.so(+0x3c53e1)[0x7f898ab5d3e1]
/usr/local/nebula/lib/libnebula_graph_client.so(+0x3bc18b)[0x7f898ab5418b]
/usr/local/nebula/lib/libnebula_graph_client.so(+0x3ba4c7)[0x7f898ab524c7]
/lib/x86_64-linux-gnu/libc.so.6(+0x354bf)[0x7f8989e074bf]
./session_example[0x4033f5]
./session_example(_ZNK6nebula7DataSet8toStringB5cxx11Ev+0x54)[0x402a12]
./session_example[0x402cb7]
./session_example[0x401f57]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xef)[0x7f8989df283f]
./session_example[0x401978]
(safe mode, symbolizer not available)
Segmentation fault (core dumped)

However, the same query works fine with nebula-graph console. How can I fix this

**Comment by wey-gu** [comment]
@Shylock-Hg do you have more ideas on this, please?

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg do you have more ideas on this, please?

A bug, I will check it later.

**Comment by chiru091096** [comment]
@Shylock-Hg thank you for the reply. I removed the statement accessing data field and that crash issue was resolved. 
Further I'm able to create and use space. I'm also able to create Tag. 

Thank you @wey-gu,@Shylock-Hg, @SuperYoko , @Sophie-Xie for the quick help.
