### ISSUE TITLE
the return of session.executeJson

### ISSUE THREAD

**Issue by thewkgithub** [vesoft-inc/nebula#5297]
Version: 3.3.0, Java

我在执行`session.executeJson`命令的时候，一般情况下，都会返回类似这种结构：

{"errors":[{"code":0}],"results":[{"spaceName":"","errors":{"code":0},"latencyInUs":1151}]}

这里面errors和results都是array，但这些array里面，一般只有一条记录。

我的问题是：

在什么情况下（执行什么命令），这些array里面会包含多条记录呢？？

如果每次都是一条记录，为什么要返回一个array呢？

**Comment by wey-gu** [comment]
cc @Aiee

**Comment by Aiee** [comment]
This is saved for possible features later. Currently, only one response will be returned.
