### ISSUE TITLE
Does frequent space switching consume resources?

### ISSUE THREAD

**Issue by 1315577677** [vesoft-inc/nebula#5302]
**Does frequent space switching consume resources?**

假如我有100个图空间需要管理，如果使用目前的SessionPool，就需要每一个space创建一个SessionPool，那么我就需要创建并管理100个SessionPool，这样很浪费。我目前将现有的SessionPool的space改为动态space，但是这样的弊端就是频繁切换space。基本上每次调用execute方法都会切换space，我想问的是切换space消耗性能吗？对系统的影响大吗？与普通的查询相比呢？

**Comment by QingZ11** [comment]
https://discuss.nebula-graph.com.cn/t/topic/12011

论坛也有一样的问题，为了避免一个问题多处需要回复，你可以去论坛那边交流下哈。这个 issue 你方便的话可以关闭掉么？

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
