### ISSUE TITLE
how to expose external entrance to metad service when it is a headless in k8s with nebula-operator

### ISSUE THREAD

**Issue by Gevygg** [vesoft-inc/nebula#5310]
I builded a nebula cluster in k8s with  nebula-operator and found metad was a headless service.
When I wanted to wirte something to nebula ,I had no way to connect to metad servcie.
How should I do ?

**Comment by wey-gu** [comment]
I tried this here https://gist.github.com/wey-gu/699b9a2ef5dff5f0fb5f288d692ddfd5 , by exposing it with services one by one.

Also, I did something else here https://www.siwei.io/apisix-and-nebulagraph/ for your reference, too.
