### ISSUE TITLE
How to install Backup & Restore agent binaries to the cluster resources?

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5313]
**General Question**

@wey-gu 

Per the official BR [docs] (https://docs.nebula-graph.io/3.3.0/backup-and-restore/nebula-br/2.compile-br/)

- We need to install Agent on all metad & storaged nodes. What's is the recommended ways to deploy BR & Agents to all metad and storaged nodes that make up the cluster?

For Example: Our have below nodes
- metad   :  3
- graphd  :  3
- storaged: 5

**Comment by wey-gu** [comment]
NebulaGraph BR for K8s is still WIP, currently, it's not yet supported in container-based deployment, but will be supported in the upcoming months.

It's required to be deployed(like a sidecar) for all meta/storage processes actually.

**Comment by porscheme** [comment]
> NebulaGraph BR for K8s is still WIP, currently, it's not yet supported in container-based deployment, but will be supported in the upcoming months.
> 
> It's required to be deployed(like a sidecar) for all meta/storage processes actually.

Will it be part of v3.4.0? When is v3.4.0 coming?

**Comment by wey-gu** [comment]
No 3.4.0 is being release in these days from today :), we couldnt make it in this cycle :(
