### ISSUE TITLE
Merge host info from kvstore and memory

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula#532]
For now, ActiveHostsMan will load host info from kvstore when it start-up, so it have to wait until kvstore is ready. We can load host info in background thread and merge result from kvstore and memory to update the online/offline status. In that way, we can get rid of sleep when initializing kvstore.

**Comment by dangleptr** [comment]
Very good.

**Comment by andychow01** [comment]
Very good.

**Comment by sherman-the-tank** [comment]
Why do we persist the active host info in kvstore? If this is the cache of the meta information we discussed earlier, we need to store other information as well.

Please shed more light, or we can talk about this offline

**Comment by critical27** [comment]
@sherman-the-tank 
As #440, we add some host status of online/offline. So we persist the host status in kvstore.

**Comment by critical27** [comment]
In #550, @andychow01 fix this by loading info from kvstore lazily, when kvstore is ready, we can merge info from kvstore and memory. The reason of merging is that the host status in kvstore may be outdated because of leadership change.
