### ISSUE TITLE
 `LIMIT` pushdown does not take effect with index scan

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#5323]
* nebulagraph version: v3.3.0
* installation: Docker
* deployment way: stand-alone

* description: a Tag with data volume of 60 million, you can still query the data with `match (v: some_tag) return v limit 10` before building the Tag’s native index, but after creating and rebuilding the index, the query response is extremely slow or an error is reported.

I want to ask you for help, is this situation normal, and is there any better solution to achieve this requirement.

#### service states

![image](https://user-images.githubusercontent.com/38887077/217416506-4900c2d3-d9d1-4025-ad05-6b3d3cf777a3.png)

#### schema infos

![image](https://user-images.githubusercontent.com/38887077/217416553-77a62a25-773c-4d3f-93d5-650b682e4d4b.png)

#### query statement

```
match (v: medical_record) return v limit 10
```

#### index create statement

![image](https://user-images.githubusercontent.com/38887077/217416675-95b12645-397e-4e4e-8301-7a258d7cc799.png)

#### explain result

![image](https://user-images.githubusercontent.com/38887077/217416713-daa03fde-6ad1-4f47-a187-825bfad959d5.png)

![image](https://user-images.githubusercontent.com/38887077/217416735-3bf5e43d-6fe3-4ff6-9ed2-65f6b06182e0.png)

![image](https://user-images.githubusercontent.com/38887077/217416758-7724daf9-188c-43fb-8413-2485a434f405.png)

#### other infos

@czpmango said: "It seems that the limit push-down did not take effect."

#### refer links

from: [https://discuss.nebula-graph.com.cn/t/topic/12080](https://discuss.nebula-graph.com.cn/t/topic/12080)

**Comment by porscheme** [comment]
I thought, limits doesn't push down to storage therefore no effect.

**Comment by wey-gu** [comment]
> I thought, limits doesn't push down to storage therefore no effect.

The situation changed since 3.4.0, it's now pushed down :)

**Comment by wey-gu** [comment]
@porscheme @QingZ11 it's already fixed in 3.4.0 by https://github.com/vesoft-inc/nebula/pull/5019

**Comment by wey-gu** [comment]
We could close this as fixed.

**Comment by porscheme** [comment]
> > I thought, limits doesn't push down to storage therefore no effect.
> 
> The situation changed since 3.4.0, it's now pushed down :)

Awesome, this is good fix,
Does all the limits pushed to storage?

**Comment by wey-gu** [comment]
> > > I thought, limits doesn't push down to storage therefore no effect.
> > 
> > 
> > The situation changed since 3.4.0, it's now pushed down :)
> 
> Awesome, this is good fix, Does all the limits pushed to storage?

The edge indexscan was not yet pushed, but that's a rare case.
