### ISSUE TITLE
`GO...FROM...BIDIRECT` can't work

### ISSUE THREAD

**Issue by aidbang** [vesoft-inc/nebula#5332]
INSERT VERTEX bnc (value) VALUES "player999":(2);
INSERT EDGE follow (degree) VALUES "player102"->"player999":(70);
INSERT VERTEX bnc (value) VALUES "player888":(0);
INSERT EDGE follow (degree) VALUES "player999"->"player888":(90);

go 1 to 3 steps from "player101" over follow
where follow.degree>80 or $$.bnc.value>0
yield edge as e;
检索结果正确
![image](https://user-images.githubusercontent.com/46556007/218014622-b288e1a1-7c01-43d2-9f32-6aa9dbd19a45.png)

go 1 to 3 steps from "player101" over follow BIDIRECT
where follow.degree>80 or $$.bnc.value>0
yield edge as e;
检索结果有问题：1、超过3跳；2、有跟起点不关联的子图。
![image](https://user-images.githubusercontent.com/46556007/218014389-37ee6dd4-d9ce-4d98-b4a7-a22ac760b250.png)

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula/issues/4573

**Comment by nevermore3** [comment]
Discussed with @yixinglu  & @sherman-the-tank  offline, consistent with the previous version
