### ISSUE TITLE
nebula-console can't connect to nebula cluster

### ISSUE THREAD

**Issue by tgy3300** [vesoft-inc/nebula#5334]
集群信息
机器名       ip
a                192.168.1.204
b                192.168.1.205
c                192.168.1.206
三个节点，都安装了graphd，storaged，metad
三个节点的配置文件都修改了
--meta_server_addrs=机器1ip:9559,机器2ip:9559,机器3ip:9559
--local_ip=本机ip
三台服务器的 graphd，storaged，metad 三个进程，也能正常启动

进行，./nebula-console -addr 192.168.1.204 -port 9669 -u root -p root，就报如下错误，报错后，三个节点的graphd进程就会挂掉，

三节个节点之间都能相互ping通，相关的  9559，9669，9779防火墙也放行了，还是不行，错误信息如下：

2023/02/12 10:20:22 Fail to initialize the connection pool, host: 192.168.1.204, port: 9669, failed to open connection, error: failed to open transport, error: dial tcp 192.168.1.204:9669: connect: connection refused 
panic: Fail to initialize the connection pool, host: 192.168.1.204, port: 9669, failed to open connection, error: failed to open transport, error: dial tcp 192.168.1.204:9669: connect: connection refused 

goroutine 1 [running]:
log.Panicf(0xc0000da000, 0xc5, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.4/x64/src/log/log.go:361 +0xc5
main.main()
	/home/runner/work/nebula-console/nebula-console/main.go:532 +0xb10

**Comment by QingZ11** [comment]
部署方式是啥？Docker？

**Comment by tgy3300** [comment]
linux
直接部署

**Comment by tgy3300** [comment]
没人遇到吗，官方的来个人指导下

**Comment by wey-gu** [comment]
三个服务正常启动，用 scripts 里的 nebula.service 看 status 状态是好的么？如果不好重新启动一下，如果还不好看下日志是什么错误

**Comment by wey-gu** [comment]
https://docs.nebula-graph.com.cn/3.4.0/20.appendix/0.FAQ/#_14

文档里有提及哈：

关于连接¶

防火墙中需要开放哪些端口？¶

如果没有修改过配置文件 中预设的端口，请在防火墙中开放如下端口：

服务类型	端口
Meta	9559, 9560, 19559
Graph	9669, 19669
Storage	9777 ~ 9780, 19779
如果修改过配置文件中预设的端口，请找出实际使用的端口并在防火墙中开放它们。

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
