### ISSUE TITLE
tooooooooooo loooooooongggggggggggggggg id/version number over flow

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#534]
what if the id 
insert vertex xxx 100000000000000000000000000000000000000000()
the result is over flow:

nebula> go from 10100000000000000000000000000000000000000000000000000000 over like                                                                    =======================                                                                                                                               |                  id |                                                                                                                               =======================                                                                                                                               | 9223372036854775807 |                                                                                                                               -----------------------                                                                                                                               Got 1 rows (Time spent: 9218/9974 us)          

I don't think over flow is a good idea.

**Comment by laura-ding** [comment]
When the inputText exceeds the max of int64_t, atoll(inputText) converts to the max of int64_t. Here needs to process and validate the string before atoll().
