### ISSUE TITLE
some questions about index and GO

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula#5346]
最近在使用nebula时发现使用上存在一些互斥逻辑：
1. 首先是索引的逻辑：例如不建议使用索引，因为索引会导致数据插入性能严重下降，但是也没提供手动控制增量索引的接口，所以只能尽量不使用索引；但是当我们想使用一些快速节点类型内的属性过滤时不使用索引又无从下手，因为没有起点
2. 其次是go的使用逻辑，必须有一个起点且必须向外走一步才能对下一级节点进行操作，当我们想简单的拿到一个不存在上下级关联的目标节点（并计算节点上的所有tag）时使用go/fetch均无法实现，不知道是不是我对原生语句的理解有问题？

**Comment by nevermore3** [comment]
1、使用openCypher大部分场景时，都会用到索引，所以如果文档中有不建议使用索引的地方，帮忙提个issue，文档同学会帮忙修正。
2、个人理解你的场景应该是求 孤立点，目前还不支持求孤立点。 go的主要语义是在拓展，例如求 一个点3度之内所有朋友中 是否有老师的朋友

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
