### ISSUE TITLE
raft some issue 

### ISSUE THREAD

**Issue by shixiangz** [vesoft-inc/nebula#5352]
![image](https://user-images.githubusercontent.com/122794081/219565894-8e0de560-1811-4698-8eda-500311fa5899.png)
leader_ and isBlindFollower_  act the same， I think isBlindFollower_  == True eq  leader_ == HostAddr("", 0)

We should increase the limit when voting. The follwer host  leader_ != HostAddr("", 0) and leader lease valid recorded by the current host should refuse to vote to prevent split-brain

**Comment by shixiangz** [comment]
isBlindFollower_  maybe cause split brain， A（leader）B（follower） C(followe)， restart B and C， B start election
，C restart ok，dont start election，C vote for B。 B send request to A is lost， B is leader and A is leader

**Comment by liwenhui-soul** [comment]
why does B start election?

**Comment by shixiangz** [comment]
start to election has gap

**Comment by critical27** [comment]
I don't think this is a issue, reopen it if necessary

**Comment by critical27** [comment]
I got your point. 
It won't cause inconsistency. Because at least B or C has same log as A, let's say it is B, only B could be elected as leader at higher term.

Read could be routed to A, but write to A won't be success anymore. So again, no inconsistency happened.

**Comment by qiwei9743** [comment]
It indeed break the linear consistency. nebula implement pure lease read but didn't implement checkquorum and read index as ETCD do. The old leader may read the stale data from old leader after new write over B and C(in shixiang's case). Although it's a small gap, nebula can't declare it implement a strong consistency.

**Comment by critical27** [comment]
> It indeed break the linear consistency. nebula implement pure lease read but didn't implement checkquorum and read index as ETCD does. The old leader may read the stale data from old leader after new write over B and C(in shixiang's case). Although it's a small gap, nebula can't declare it implement a strong consistency.

Perhaps you need to describe in more details how inconsistency happen. Liked I said in https://github.com/vesoft-inc/nebula/issues/5352#issuecomment-1461486012, two leader doesn't mean split brain. Only when two leader of same term is. New leader of B or C can only trigger election after an election timeout passed.

**Comment by critical27** [comment]
Although I agree that blind follower that may break the precondition that election could only after an election timeout passed. 

Need to think a way to address it later
