### ISSUE TITLE
Match edge sentence return two records when we do the follow nGQL

### ISSUE THREAD

**Issue by Milittle** [vesoft-inc/nebula#5367]
**Please check the FAQ documentation before raising an issue**

```sql
(root@nebula) [basketballplayer]> match ()-[e:FileRead]-() return e limit 10;
+------------------------------------------------------------------------------------------------------------------+
| e                                                                                                                |
+------------------------------------------------------------------------------------------------------------------+
| [:FileRead "100"->"101" @0 {event_startTs: 1677132344, file_uuid: "001", host_uuid: "001", process_uuid: "001"}] |
| [:FileRead "100"->"101" @0 {event_startTs: 1677132344, file_uuid: "001", host_uuid: "001", process_uuid: "001"}] |
+------------------------------------------------------------------------------------------------------------------+
```

**Describe the bug (__required__)**

double records for edge indexScan

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
create one edge
2. Step 2
create edge index
3. Step 3
then insert one data

**Expected behavior**

return one records

**Comment by xtcyclist** [comment]
This result is correct. The returned `e` is the shared edge from two different matched patterns. There are two different matched patterns since no conditions on vertices or the direction of edges have been specified in the query.
