### ISSUE TITLE
raft follower should add the judgment of leader lease valid when process askvote to prevent split brain

### ISSUE THREAD

**Issue by shixiangz** [vesoft-inc/nebula#5379]
Current code that process voting election requests may cause split brain (ep: network issue)，I think it would be better to add some judgment

![image](https://user-images.githubusercontent.com/122794081/222428908-6fe34017-b840-4603-8e3f-5538226f023c.png)

**Comment by critical27** [comment]
Would you name one split brain case? What you implemented above is called `leader stickness`, which is generally used in raft, but whether check leader stickness does not impact leader election.

**Comment by shixiangz** [comment]
A(leader， lease 30s) ，B ,（follower） C （follower）, C restart（isBlindFollower, quick election）， send askvotereques to A（lost）, send askvotereques to B，B votes for C，now A is leader， C is leader；

**Comment by shixiangz** [comment]
A(leader， lease 30s) ，B ,（follower） C （follower）,  A rocksdb manual compaction, write stall,  sendheart  only step2(not send log),   A and C network isolation，C can't receive heartbeat， send askvote request to B，B votes for C，now A is leader， C is leader；

**Comment by shixiangz** [comment]
The judgment of role can be removed

**Comment by critical27** [comment]
Same as #5352, close it.
