### ISSUE TITLE
Support 'FLUSH USER_RESOURCES' feature.

### ISSUE THREAD

**Issue by boshengchen** [vesoft-inc/nebula#539]
This issue related to PR #480 and Issue #190 .
Implement  `FLUSH USER_RESOURCES` with reference to mysql.

**Comment by sherman-the-tank** [comment]
@boshengchen Can you shed more light on this issue? What does **USER_RESOURCES** refer to?

BTW, I prefer not to have "_" between keywords

**Comment by bright-starry-sky** [comment]
Permission design has changed, no plan to implement this feature in the near future.
close this issue .
