### ISSUE TITLE
how to set wss for Nebula Graph

### ISSUE THREAD

**Issue by kellyseeme** [vesoft-inc/nebula#5397]
when i use wss for graph,but its not affect,
<img width="685" alt="image" src="https://user-images.githubusercontent.com/535200/224677249-26d3ad98-7484-4830-9c8b-e4d36c3de53b.png">

the error is :
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS
This request has been blocked; this endpoint must be available over WSS.

how can i set the ws to wss?

**Comment by wey-gu** [comment]
NebulaGraph（graphd）comes with no websocket interface the ssl/tls in the configuration was about thrift over tls.

Please refer to the docs instead of the chatgpt when possible, chatgpt is a good start to get pictures of fresh questions though(am using the same way, too, heavily)
