### ISSUE TITLE
Very slow graph walk

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5401]
Version: v3.4.0
@wey-gu 
**Describe the bug (__required__)**
Very slow graph walk...
  - More than 5 minutes
  - Often times crash
  - Not able to run multiple queries this type in parallel

My Query
```
MATCH (p:Student)
WHERE id(p) IN [ ... ]

OPTIONAL MATCH (p)<-[:HAS_COURSE]-(a:CourseCodes)
OPTIONAL MATCH (p)<-[:STUDENT_HAS_SOCIAL]-(s:Social)
OPTIONAL MATCH (p)<-[:HAS_PROCEDURE]-(r:ProcedureCodes)

WITH
  p,
  COLLECT(DISTINCT a.CourseCodes.CodeId) as courses,
  COLLECT(DISTINCT s.Social.AttributeId) as social,
  COLLECT(DISTINCT r.ProcedureCodes.CodeId) as procedures

RETURN 
  p.Student.StudentId as Student, 
  p.Student.Gender as sex, 
  p.Student.Race as race, 
  p.Student.Ethnicity as ethnicity, 
  p.Student.MaritalStatus as maritalstatus,
  diagnosis,
  procedures,
  social
```

**Your Environments (__required__)**

* OS: `uname -a`
Linux nebula-cluster-storaged-2 5.4.0-1103-azure #109~18.04.1-Ubuntu SMP Wed Jan 25 20:53:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 
* Compiler: `g++ --version` or `clang++ --version`
 g++: command not found

* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by wey-gu** [comment]
Could you share the profile of the query?

**Comment by wey-gu** [comment]
```
OPTIONAL MATCH (p)<-[:HAS_COURSE]-(a:CourseCodes)
OPTIONAL MATCH (p)<-[:STUDENT_HAS_SOCIAL]-(s:Social)
OPTIONAL MATCH (p)<-[:HAS_PROCEDURE]-(r:ProcedureCodes)
```

- Always put a tag when it's predictable/known, else, it had to scan for all tags on given `p`.

- explicitly provide props you cared under `p` in the first WITH, which will reduce the data being joined/aggregated.

Also, from the profile log you shared, it's not like 5 mins to me. I think the 5 mins was from studio?

**Comment by porscheme** [comment]
> Also, from the profile log you shared, it's not like 5 mins to me. I think the 5 mins was from studio?
No, Its not from studio. Using python client library.

We use array of size about 200 in the below. its taking about 5 minutes.
'''
MATCH (p:Student)
WHERE id(p) IN [ ... ]
'''
