### ISSUE TITLE
How to skip installing third-party？

### ISSUE THREAD

**Issue by wqh17101** [vesoft-inc/nebula#5406]
I will install the software here https://docs.nebula-graph.com.cn/3.3.0/4.deployment-and-installation/1.resource-preparations/#_2 before building.
So how to skip installing third-party when cmake ?
```
>>>> Configuring third party for 'Nebula Graph' <<<<
-- Downloading prebuilt third party automatically...
-- cxx_cmd: /usr/bin/c++ -D_GLIBCXX_USE_CXX11_ABI=1
Downloading vesoft-third-party-3.3-x86_64-libc-2.17-gcc-10.1.0-abi-11.sh...
```
I do not know why it will download for i have installed the thirdparty softwares it need before cmake.

**Comment by wey-gu** [comment]
You could try with nebula_dev docker build env to avoid those preparation steps, but plz be noted, there are binaries built nightly and per release out there, too, normally we dont have to build on our own.

ref: https://www.siwei.io/nebulagraph-hacking-guide/ (Chinese :P )

**Comment by wqh17101** [comment]
Good.
But i want to install these by myself, so maybe you can add an option to skip for the users who have installed these dependencies?

**Comment by wey-gu** [comment]
@Shinji-IkariG is there any way to bypass install-third-party.sh in cmake, please?

**Comment by wqh17101** [comment]
Also you can offer the doc for the vesoft-third-party.
It is better for you to make users able to choose which way to build third party.
Use your vesoft-third-party or build by theirself.

**Comment by wqh17101** [comment]
Sometimes, users can only get your source code and the other software's installer for some building env limitation.

**Comment by wqh17101** [comment]
Users can use vesoft-third-party-3.0-x86_64-libc-2.28-gcc-9.3.0-abi-11.sh to install them by a click.
Why is this thing  not in the doc?

**Comment by Shinji-IkariG** [comment]
First of all, the third party refers to the upstream projects needed to compile nebula, so they must exist—whether you use the pre-compiled version of vesoft or compile it yourself
Secondly, if you use the code provided by vesoft/nebula-third-party to compile the project yourself, it will be installed in the /opt directory by default, which is also the path that nebula checks by default, so you can continue nebula after compiling the 3rd party The compilation work.
Finally, the third party involves a lot of combinations, determined by the compiler, glibc version, hardware architecture, etc., so there is no one general combination. This is why you will automatically download a certain combination when compiling nebula - we combine the corresponding 3rd party file name based on the relevant information on your current system, and try to download it.

**Comment by QingZ11** [comment]
@wqh17101 Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
