### ISSUE TITLE
download sst FAILED , HdfsCommandHelper.cpp:29] Failed to ls: exited with status 127

### ISSUE THREAD

**Issue by Gevygg** [vesoft-inc/nebula#5408]
I prepared some sst data on hdfs.
when I executed download sst command ，it failed.
You can found error info like this 
HdfsCommandHelper.cpp:29] Failed to ls: exited with status 127
I check the source code  --- ---
![11325df1e5b0f76823375d9e081669d](https://user-images.githubusercontent.com/38530291/225609683-5e1a8ead-99be-4126-a882-d2446d4176b5.png)
The node ,which deployed Metad service,need hadoop envirment ?

**Comment by SuperYoko** [comment]
This helper use a subprocess to execute this command , check command in logs to see if it can execute in your bash environment. If you can run this, then maybe use sudo -e to start nebula so that nebula process will keep your ENV( for example PATH, JAVA_HOME)

**Comment by QingZ11** [comment]
@Gevygg Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
