### ISSUE TITLE
ADD HOSTS by cmd

### ISSUE THREAD

**Issue by wqh17101** [vesoft-inc/nebula#5411]
I found that 
![image](https://user-images.githubusercontent.com/26429138/225865879-c4f79694-37ca-4b47-aa4d-1e5754e368b8.png)
We should use `add hosts` by myself to add, is there any options to add automatically?

**Comment by wey-gu** [comment]
This was intended to add human intervention in storaged service discovery, for those notified metad that they are ready to handle traffic, we need admin to explicitly "add"/activate to proceed.

In NebulaGraph k8s operator, this is not required as the operator will do so automatically.

**Comment by wqh17101** [comment]
> In NebulaGraph k8s operator, this is not required as the operator will do so automatically.

Why? Is there any trick in the dockfile or deployment.yaml to make it work?

**Comment by wey-gu** [comment]
It's just the operator do the work, no workarounds actually, in docker-compose, such things existed, too, but in a silly way:

https://github.com/vesoft-inc/nebula-docker-compose/blob/0d47bbd5300758f80b60b805c035ad04e27cab34/docker-compose.yaml#L327

**Comment by wqh17101** [comment]
Let me see.
Use dockerfile to start service and yaml to add hosts?
@wey-gu

**Comment by wey-gu** [comment]
It just waits for the cluster to be ready, and give a "one-shot" add hosts call at best, as docker-compose is not designed for production, we just leave it as is now.
