### ISSUE TITLE
What is `--containerized=true`?

### ISSUE THREAD

**Issue by wqh17101** [vesoft-inc/nebula#5412]
No doc for this option which occur in  the dockfile

**Comment by wey-gu** [comment]
It's just a flag to allow nebulagraph do things differently when needed, i.e. in `MemoryUtils::hitsHighWatermark()`

We just let it be true when it's actually in containers.

**Comment by wqh17101** [comment]
@wey-gu 

So you mean that  when i build it from source, this option can be used by default?I can use it when i need freely.

**Comment by wey-gu** [comment]
yes, it's not build flag but execute conf

**Comment by QingZ11** [comment]
According to what the developers of memory trakcer explained in the latest article, this parameter `--containerized` is used to show whether the database is running on the container. Btw, the article will be released next week.

cc @wey-gu

**Comment by QingZ11** [comment]
@wqh17101 Hi, I close this issue because it has not been updated for a long time. If you have any updates, it'OK to reopen.

Thanks a lot for your contribution anyway 😊
