### ISSUE TITLE
time series data

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5415]
**General Question**

He @wey-gu 

Is Nebula graph good for time series data?
Has anyone used Nebula for time series data?  if yes, can provide modelling guides?

**Comment by wey-gu** [comment]
You could consider leveraging the rank field with edges.

ref: https://docs.nebula-graph.io/3.4.1/8.service-tuning/2.graph-modeling/#set_temporary_properties_through_self-loop_edges

**Comment by QingZ11** [comment]
@porscheme Hi, I close this issue because it has not been updated for a long time. If you have any updates, it'OK to reopen.

Thanks a lot for your contribution anyway 😊
