### ISSUE TITLE
where is the nebula-third-party-src-5.0.tgz

### ISSUE THREAD

**Issue by wqh17101** [vesoft-inc/nebula#5417]
```
$ build_package=1 $path/build.sh
$ ls
install/ tarballs/  packages/ nebula-third-party-src-5.0.tgz
$ ls packages
vesoft-third-party-5.0-x86_64-libc-xxx-gcc-xxx-abi-11.sh

# You could also specify an install prefix
$ build_package=1 $path/build.sh /opt/vesoft/third-party/5.0
```

**Comment by Shinji-IkariG** [comment]
This issue belongs to https://github.com/vesoft-inc/nebula-third-party not nebula, please note that these are two different projects.
The third party aims to build the 3rd party library needed by nebula. When you clone the latest master branch, set the compiler and environment variables and execute the compilation script, if the source package does not exist locally, it will be automatically obtained from the network.
