### ISSUE TITLE
[DISCUSS] Should we support removing edge/vertex in compaction?

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#542]
Removing edge/vertex in compaction will break our index,   cause in-degree/out-degree changed.  
It is hard to deal with it currently.

IMO,  index/ in-out degree is one configuration for Schema,   it should not be supported when TTL is opened.

**Comment by steppenwolfyuetong** [comment]
I think we can set a threshold:

1) When in less than the critical value, update in-out degree in compaction
2) When it is greater than the critical value, ignore the update in-out degree in compaction, mark the in-out degree in an abnormal state, and then check the in-out degree state , then manually execute to update the in-out degree of all vertices.

**Comment by sherman-the-tank** [comment]
Please **DO NOT** use Chinese punctuation

**Comment by sherman-the-tank** [comment]
I think we've had conclusion. We should be able to maintain the consistency of the index for TTL. We **will not** go ahead to do the in/out degree
