### ISSUE TITLE
3.3.0 Create Edge Bug.

### ISSUE THREAD

**Issue by thewkgithub** [vesoft-inc/nebula#5427]
Version: 3.3.0
操作: 创建一个名字为2的EDGE, 报重复异常. 但实际该图空间中没有这个EDGE.

> CREATE EDGE `2` (`META_START_TIME` DATETIME NULL COMMENT '元数据:开始时间', `META_END_TIME` DATETIME NULL COMMENT '元数据:结束时间', `META_CREATE_TIME` DATETIME NULL COMMENT '元数据:创建时间',`META_UPDATE_TIME` DATETIME NULL COMMENT '元数据:更新时间') COMMENT = '';
[ERROR (-1005)]: Schema with same name exists

Tue, 21 Mar 2023 02:34:18 CST

]> SHOW EDGES;
+-------------+
| Name        |
+-------------+
| "0"         |
| "09"        |
| "1"         |
| "123123"    |
| "23"        |
| "234"       |
| "2344"      |
| "3"         |
| "45"        |
| "4545"      |
| "56"        |
| "6"         |
| "8"         |
+-------------+

**Comment by thewkgithub** [comment]
好像是找到原因了...
因为有一个名字为2的Tag.

这算是BUG,还是本身设计就是如此呢???

**Comment by thewkgithub** [comment]
文档里面提示说

每个图空间内的 Tag 必须是唯一的。
每个图空间内的 Edge type 必须是唯一的。

没说，TAG和EDGE TYPE的名字不能重复啊。。

**Comment by pengweisong** [comment]
为了兼容 Cypher 不得不如此，因为 Cypher 是面向 Label 的。如果 Edge 和 Tag 同名，在 Cypher 语法内，有些语句很容易匹配出非期望结果。
