### ISSUE TITLE
when MetaService leader down, how long does it take to elect the new leader?

### ISSUE THREAD

**Issue by lszChain** [vesoft-inc/nebula#5434]

**Comment by QingZ11** [comment]
你们服务数量是怎么样的？选举的话，遵循的是过半数选举成功，如果你挂掉一台，是偶数的话，也许选举是不会成功的。

**Comment by lszChain** [comment]
> 你们服务数量是怎么样的？选举的话，随从的是过半数选举成功的，如果你挂掉一个台，是偶数的话，也许选举是不会成功的。

我们产品默认是配置3台MetaService，可以正常选择leader的情况下，我们想知道重新选举leader的时间会不会导致图查询业务中断时间过长，所以我们可能想要知道最大成功选举leader时长是多少。另外如果有leader重新选则leader的原理材料就更好了

**Comment by QingZ11** [comment]
选举原理你可以参考下这篇知乎的文章，大家的原理都是类似的：[https://zhuanlan.zhihu.com/p/91288179](https://zhuanlan.zhihu.com/p/91288179)

NebulaGraph 里面的选举时间和 `raft_heartbeat_interval_secs` 这个参数有关。

**Comment by lszChain** [comment]
> 选举原理你可以参考下这篇知乎的文章，大家的原理都是类似的：https://zhuanlan.zhihu.com/p/91288179
> 
> NebulaGraph 里面的选举时间和 `raft_heartbeat_interval_secs` 这个参数有关。

raft_heartbeat_interval_secs我理解是leader发起的心跳间隔时间，election timeout时间是在哪里配置的呢

**Comment by pengweisong** [comment]
> raft_heartbeat_interval_secs我理解是leader发起的心跳间隔时间，election timeout时间是在哪里配置的呢
选举超时就是raft_heartbeat_interval_secs  ，心跳实际上是该值的三分之一左右：https://github.com/vesoft-inc/nebula/blob/master/src/kvstore/raftex/RaftPart.cpp#L1410

**Comment by QingZ11** [comment]
@lszChain 这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
