### ISSUE TITLE
[TTL] Historical data may never get the opportunity to get garbage collected

### ISSUE THREAD

**Issue by luyade** [vesoft-inc/nebula#5438]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

By default, custom_filter_interval_secs is set as 24 * 3600, which means in 24 hours, we will only have one chance to do custom minor compaction. Otherwise, it will go to the default minor compaction.

<img width="736" alt="企业微信截图_107a2bbb-a440-4aa5-9634-7def95070245" src="https://user-images.githubusercontent.com/5063363/227717374-8046dc9d-c668-4e47-92ae-41485eb1a3e9.png">

For historical data, many data will reside in the bottommost level. For the expired data in the bottommost level, it doesn't have many chance to get GC except periodic compaction. However, during daily running, the only custom-compaction chance will most possibly be used by upper level data compaction, such as level0 => level1. So the default 30-days periodic compaction will go through the default minor compaction, without go through custom compaction filter. So the expired data will always be there.

Here is some log I print out in StorageIterator.h:

<img width="817" alt="企业微信截图_12cc53a8-4ba2-473a-8f10-f4438c027c9d" src="https://user-images.githubusercontent.com/5063363/227718071-3dca95f9-9bb8-4979-a257-ef8b04f50349.png">

As you can see, it will read a bunch of expired edges during edge traverse. 

After I fixed the compaction logic, the performance got extremely better.

<img width="1420" alt="企业微信截图_13ab7c92-681c-4d23-aa92-e242a316a553" src="https://user-images.githubusercontent.com/5063363/227718269-a111c27d-914f-42d9-9391-c4810cc8bf15.png">

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by pengweisong** [comment]
In the design now, it indeed depends on user to trigger the compact job to GC the garbage in the bottom level.

**Comment by luyade** [comment]
> In the design now, it indeed depends on user to trigger the compact job to GC the garbage in the bottom level.

As far as I can see, in the current design, the only way user can trigger the compaction of the bottommost level is to submit a compact job, which will then trigger a full compaction. Actually, full compaction is almost unacceptable in production environment.

**Comment by pengweisong** [comment]
If you have any idea to improve this, any contribution are welcomed.

**Comment by luyade** [comment]
> If you have any idea to improve this, any contribution are welcomed.

My idea is simple. see https://github.com/vesoft-inc/nebula/pull/5447
