### ISSUE TITLE
[Optimizer] Optimize variable-length edge predicate execution

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#5441]
**Introduction**
Cypher provides predicate functions to filter all variable-length edges, and the statement is like:
```
MATCH (v:player)-[e:like*2..5]->(n)
WHERE all(i in e where i.likeness > 90)
RETURN n
```
There is room for optimization in the current implementation of nebula, and we can consider embedding the filter expression into the traverse operator, optimized plan is like this:
` Scan -> Traverse(allEdgeFilter_ = e.likeness>90) -> Project`

**Contents**
Add related optimization rules to gain performance benefits.

**Related work**
Some query semantics that are difficult to express in go statements can be replaced by match statement.

**Comment by wey-gu** [comment]
It's exciting to see we started to optimize towards functions that used to be always evaluated after data fetching!

**Comment by Sophie-Xie** [comment]
https://github.com/vesoft-inc/nebula/pull/5464
https://github.com/vesoft-inc/nebula/pull/5470
https://github.com/vesoft-inc/nebula/pull/5481

**Comment by czpmango** [comment]
Only the basic edge all predicate pushdown is supported(predicate is a first-level attribute expression), such as:
```
MATCH (v)-[e*2..5]-(n) where all(i in e where i.prop1 >3 and i.prop2<4) RETURN *
```
Unsupported list:
 1. function predicate like 
```
MATCH (v)-[e*2..5]-(n) where all(i in e where properties(i).prop1 >3 and rank(i).prop2<4) RETURN *
```
 2. double-not expression
```
MATCH (v)-[e*2..5]-(n) where all(i in e where !!(i.prop1 >3) and i.prop2<4) and not not all(i in e where i.prop>4) RETURN *
```
 3. ...
