### ISSUE TITLE
Can I configure the directory of HDFS in `--data_path`

### ISSUE THREAD

**Issue by lszChain** [vesoft-inc/nebula#5442]

**Comment by lszChain** [comment]
> 不支持，是本地的路径哈。

好的，社区支持给力

**Comment by wey-gu** [comment]
因为 NebulaGraph 的存储层自己实现了 raft 其实没有这个必要哈，可以分享一下您期待它的背景、原因哈？

**Comment by lszChain** [comment]
> 因为 NebulaGraph 的存储层自己实现了 raft 其实没有这个必要哈，可以分享一下您期待它的背景、原因哈？

 我们是K8S容器部署，NebulaGraph服务部署在虚拟机  本地磁盘空间很小  想把存储内容挂载到HDFS

**Comment by wey-gu** [comment]
明白了，k8s 上，nebulagraph operator 默认的存储其实是”云盘“，配置的是 "storage class" 哈，不是本地盘哈

**Comment by QingZ11** [comment]
@lszChain 同样的，这个 issue 长时间没有更新。这边会先关闭这个 issue，如果你有任何更新，记得回来重开这个 issue 哈。

谢谢你的反馈 😊
