### ISSUE TITLE
Optimize the fuzzy query of string property

### ISSUE THREAD

**Issue by penghs520** [vesoft-inc/nebula#5469]
在我百万级节点的图空间中，我使用字符串属性分别进行精准匹配查询和模糊匹配查询，性能相差了近万倍，如图：
![image](https://user-images.githubusercontent.com/52020193/229440426-3a2b4314-c5f3-47e3-8c01-8ff1c9b0c4b7.png)
![image](https://user-images.githubusercontent.com/52020193/229440495-36c842f8-1843-431d-b3fc-0350913014b1.png)

**Comment by QingZ11** [comment]
Please prefix the two statements with `PROFILE` to execute and compare the generated execution plans to identify any differences in terms of time consumption.

你可以在这两条语句前面加上 `PROFILE` 执行下，看下生成的生成计划二者到底哪里耗时有差别。

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊


这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
