### ISSUE TITLE
Why NebulaGraph Exchange does 'base level is 3, output level is 4' log

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5497]
@wey-gu 
We we use NebulaGraph Exchange for ingesting data ingo nebula graph.
We see tons below line in the log file? Does anyone know what it means?

'''
Rocksdb compaction completed column family: default because of LevelMaxLevelSize, status: OK, compacted 4 files into 4, base level is 3, output level is 4
'''

This is interesting, please explain
'''
I20230413 23:48:03.560353    80 EventListener.h:21] Rocksdb start compaction column family: default because of ManualCompaction, status: OK, compacted 13 files into 0, base level is 5, output level is 5
'''

thanks

**Comment by wenhaocs** [comment]
This means there are rocksdb compaction job running. 
"base level is 5, output level is 5" indicates the keys are deleted due to overwritten by upper level keys, or expired, etc.

**Comment by QingZ11** [comment]
@porscheme hi, I have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊
