### ISSUE TITLE
Storage costs of properties through self-loop edges

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5499]
@wey-gu 

Sample Schema:
```
# Student node
CREATE TAG IF NOT EXISTS Student(Birthday datetime NULL, Gender string NULL, StudentId string null);

# self-loop edge on Student node
CREATE EDGE IF NOT EXISTS HAS_TOKENS(CommaDelimited string null);
```

Question:
- Since edge properties are usually stored on both source & destination nodes, what happens in case of self-loop edge?

Thanks for the help

**Comment by xtcyclist** [comment]
Not sure if I understood your question clearly.

Self-reflective edges are stored as two different physical edges in their respective partitions. Each such physical edge contains all the properties. When queried upon, depending on the query, the engine would decide whether one such physical edge shall be ignored or not.

**Comment by QingZ11** [comment]
@porscheme hi, I closed this issue because there hasn't been any update in over a month. If your problem is still not resolved, please feel free to reopen the issue and provide more information. We're here to help!
