### ISSUE TITLE
syntax error in manual doc

### ISSUE THREAD

**Issue by bukekangli** [vesoft-inc/nebula#5504]
doc url: https://docs.nebula-graph.com.cn/3.4.0/3.ngql-guide/3.data-types/6.list/

search: nebula> MATCH p = (n:player{name:"Tim Duncan"})-[:follow]->(m)

this case will return:
![image](https://user-images.githubusercontent.com/29880548/232007270-95db534b-dd8c-4f98-ad49-c148db038699.png)

should rewrite to: MATCH p = (n:player{name:"Tim Duncan"})-[:follow]->(m) RETURN [n IN nodes(p) | n.player.age + 100] AS r;

**Comment by QingZ11** [comment]
Thank you for your feedback. You are right that there is an issue with the example in the documentation, and `n.age` is missing a tag name. If you have any other questions or need further assistance, please let me know.

**Comment by abby-cyber** [comment]
The issue has been modified. Thank you.
