### ISSUE TITLE
[DISCUSS]Delete an Vertex

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#551]
* Delete a vertex:
```
DELETE VERTEX vid
```
graph layer need send three requests to delete a vertex:  
1. First request, get all edgeKeys(out-edges and in-edges) of the vertex needed te be deleted.
2. Second request, delete the all edges of the vertex accroding to the edgeKeys.
3. Finally, delete the vertex

- [x] parser
- [x] executor and tests in graphd

**Comment by whitewum** [comment]
1. first delete the surrending edges then delete the vertex (in case of hangling edges)
2. when deleting a huge  vertex ( a lot of in and out edges), the deleting process will be very very long (and may fail).
3. I'd prefer not to save the process in meta-server, and not to provide operation transactions, just let graph-client to check the result (e.g., double vertex delete).
4. maybe hangling edge is also an available option, let user make the choice when deleting.

**Comment by sherman-the-tank** [comment]
Please **DO NOT** use Chinese punctuation

**Comment by zlcook** [comment]
Done
