### ISSUE TITLE
isolated points

### ISSUE THREAD

**Issue by 736008081** [vesoft-inc/nebula#5523]
How to query isolated points？

**Comment by wey-gu** [comment]
```
match (n:player) where not (n)-[]-()
RETURN n
```

**Comment by 736008081** [comment]
version 3.2.0


***@***.***
 
From: Wey Gu
Date: 2023-04-24 10:50
To: vesoft-inc/nebula
CC: Arlen; Author
Subject: Re: [vesoft-inc/nebula] isolated points (Issue #5523)
match (n:player) where not (n)-[]-()
RETURN n

**Comment by QingZ11** [comment]
The query statement provided by wey-gu is also applicable to version 3.2.0. You can give a try, and if you have any new infos, feel free to update the issue.

**Comment by QingZ11** [comment]
@736008081 hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
