### ISSUE TITLE
Prefix performance get very bad after clear data

### ISSUE THREAD

**Issue by luyade** [vesoft-inc/nebula#5524]
**Introduction**

If we have a large amount of data in the backend rocksdb, the prefix performance will get extremely bad after the data is cleared, such as clear space or clear part before sending snapshot. And also this will impact the startup of storaged (see RocksEngine::allParts() implementation), which will even need several hours to finish the startup process.

**Contents**

Set iterate upper bound for read options of prefix operation. I did the testing, after the change, the performance will get almost normal as usual.

**Related work**

**Comment by critical27** [comment]
You'll set upper bound for each interface?

**Comment by critical27** [comment]
BTW, a recent version of RocksDB has claimed to improve performance after DeleteRange, this is a big pitfalls before. But I haven't test it yet.
