### ISSUE TITLE
[Raft]nebula meta： Leader has not been elected, error code is E_RAFT_INVALID_PEER

### ISSUE THREAD

**Issue by FoolishWall** [vesoft-inc/nebula#5529]
**General Question**

nebula-meta.INFO log

I20230427 07:03:06.335533 23613 RaftPart.cpp:1261] [Port: 9560, Space: 0, Part: 0] Start leader election...
I20230427 07:03:06.335579 23613 RaftPart.cpp:1289] [Port: 9560, Space: 0, Part: 0] Sending out an election request (space = 0, part = 0, term = 4690, lastLogId = 111506945, lastLogTerm = 4664, candidateIP = ip, candidatePort = 9560), isPreVote = 1
I20230427 07:03:06.335597 23613 RaftPart.cpp:1311] [Port: 9560, Space: 0, Part: 0] Sending AskForVoteRequest to [Port: 9560, Space: 0,Part: 0] [Host: ip:9560]
I20230427 07:03:06.335633 23613 RaftPart.cpp:1311] [Port: 9560, Space: 0, Part: 0] Sending AskForVoteRequest to [Port: 9560, Space: 0,Part: 0] [Host: ip:9560]
I20230427 07:03:06.335645 23613 RaftPart.cpp:1311] [Port: 9560, Space: 0, Part: 0] Sending AskForVoteRequest to [Port: 9560, Space: 0,Part: 0] [Host: ip:9560]
I20230427 07:03:06.335682 23631 ThriftClientManager-inl.h:47] Getting a client to "ip":9560
I20230427 07:03:06.335757 23631 ThriftClientManager-inl.h:38] Invalid Channel: 0x7f18b6f97500 for host: "ip":9560
I20230427 07:03:06.335763 23631 ThriftClientManager-inl.h:53] There is no existing client to "ip":9560, trying to create one
I20230427 07:03:06.335769 23631 ThriftClientManager-inl.h:74] Connecting to "ip":9560 for 4611 times
I20230427 07:03:06.335867 23631 ThriftClientManager-inl.h:47] Getting a client to "ip":9560
I20230427 07:03:06.336762 23631 AsyncSocket.cpp:2711] this=0x7f18b6f29400, AsyncSocket::handleRead() got 33 bytes
I20230427 07:03:06.336858 23631 AsyncSocket.cpp:2711] this=0x7f18b6f29800, AsyncSocket::handleRead() got 33 bytes
I20230427 07:03:06.863117 23572 MetaDaemonInit.cpp:113] Leader has not been elected, sleep 1s
I20230427 07:03:07.337045 23631 CollectNSucceeded-inl.h:59] Set Value [completed=3, total=3, Result list size=2]
I20230427 07:03:07.337152 23610 RaftPart.cpp:1327] [Port: 9560, Space: 0, Part: 0] AskForVoteRequest has been sent to all peers, waiting for responses
I20230427 07:03:07.337174 23610 RaftPart.cpp:1228] [Port: 9560, Space: 0, Part: 0] Receive response about askForVote from "ip":9560, error code is E_RAFT_INVALID_PEER, isPreVote = 1
I20230427 07:03:07.337188 23610 RaftPart.cpp:1228] [Port: 9560, Space: 0, Part: 0] Receive response about askForVote from "ip":9560, error code is E_RAFT_INVALID_PEER, isPreVote = 1
I20230427 07:03:07.337194 23610 RaftPart.cpp:1255] [Port: 9560, Space: 0, Part: 0] Did not get enough votes from election of term 4690, isPreVote = 1
I20230427 07:03:07.337244 23613 RaftPart.cpp:1384] [Port: 9560, Space: 0, Part: 0] Wait for a while and continue the leader election
I20230427 07:03:07.337267 23613 RaftPart.cpp:1397] [Port: 9560, Space: 0, Part: 0] Schedule new task
I20230427 07:03:07.863301 23572 MetaDaemonInit.cpp:113] Leader has not been elected, sleep 1s

**Comment by QingZ11** [comment]
Please provide your nebulagraph core version, and let me know if the deployment is on a cluster or a single machine. If it's a cluster, how many machines are there? 

By the way, I suggest that you check whether the IP address mentioned in the error message is a private IP address, and pay attention to protecting sensitive information.

**Comment by porscheme** [comment]
- Please provide cluster configuration
- Make sure metad nodes are odd numbered (such as 1 or 3)

**Comment by FoolishWall** [comment]
- default configuration
- 3 machines 

It was working fine before

**Comment by luyade** [comment]
Do you have changed the ip address of metad machines?

**Comment by QingZ11** [comment]
@FoolishWall hi, I closed this issue because there hasn't been any update in over a month. If your problem is still not resolved, please feel free to reopen the issue and provide more information. We're here to help!
