### ISSUE TITLE
there is stuck when shortest path query

### ISSUE THREAD

**Issue by thewkgithub** [vesoft-inc/nebula#5544]
NebulaVersion：3.3.0
OS: UBuntuServer2204

在一个图空间,执行
FIND SHORTEST PATH 查询最短路径的时候.
服务器直接就DOWN机, SSH2都连接不了了.

**Comment by shanlai** [comment]
we run concurrently when query find path with num_path_thread configuration.
by default, num_path_thread=0 would use all workers, could try setting num_path_thread's value to the number of available threads - 1 or half of it.

**Comment by cangfengzhs** [comment]
ssh都连接不了。。。直觉上来说是内存用完了啊

**Comment by wey-gu** [comment]
Yes, this should be related to supernode/ or the average degree per node is in a level that the find path touched full graph, to consume all memories, we could leverage memtracker/cgroup to limit how much memory graphd could consume, in so cases like docker-compose, the OOM will not be triggered properly(we could use docker resource limitation capability to prevent from this situation)

I encountered exactly the same situation on my own server, had to reboot physically cos SSH was hang, too.

**Comment by QingZ11** [comment]
@thewkgithub hi, I closed this issue because there hasn't been any update in over a month. If your problem is still not resolved, please feel free to reopen the issue and provide more information. We're here to help!
