### ISSUE TITLE
Encountered a problem with disk IO surge when using Java SDK

### ISSUE THREAD

**Issue by yanyu88706** [vesoft-inc/nebula#5556]
机器磁盘IO飙高：为啥我通过java sdk存储十万个左右的边，切割成200条边一次，执行executeJson()批量插入，会导致机器磁盘IO飙高，这个频率不合适吗？

**Comment by yanyu88706** [comment]
飙满了超出磁盘瓶颈了

**Comment by wey-gu** [comment]
Then such writing throughput hit the limit of your system with HDD, one way to improve is to add more HDD(in case we cannot use NVMe SSD instead) and add multiple datapaths of storaged.

**Comment by QingZ11** [comment]
@yanyu88706 hi, I closed this issue because there hasn't been any update in over a month. If your problem is still not resolved, please feel free to reopen the issue and provide more information. We're here to help!

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。
