### ISSUE TITLE
Upgrade to v3.5.0 (from v3.4.0) never comples

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5562]
**Describe the bug (__required__)**
Nebula upgrade to v3.5.0 never completes, only metad upgrade to v3.5.0

- We tried to upgrade Nebula cluster t v3.5.0 from v3.4.0
- Below are the exact sequence of steps
-- Upgrade Nebula operator to v1.4.2
-- upgrade CRDs
-- Make sure Nebula operator is healthy
-- Upgrade to Nebula cluster to v3.5.0
- All the metad nodes upgraded successfully
- Notice storaged and graphd nodes never upgrade to v3.5.0, even after 24 hrs

@wey-gu can you help us.

**Comment by wey-gu** [comment]
@MegaByte875 what could possibly stop pod from updating?

**Comment by porscheme** [comment]
@wey-gu  Any update on this?

**Comment by wey-gu** [comment]
Sorry @porscheme, for the late response, I just checked with @MegaByte875 offline to know that 3.5.0 is not yet supported by the operator now, which will be done later.

**Comment by wey-gu** [comment]
Yes, we should roll back to the 3.4.0/3.4.1 image tag before it's supported.
