### ISSUE TITLE
What is the default password for the new createduser 

### ISSUE THREAD

**Issue by bigdata-spec** [vesoft-inc/nebula#5565]
Hello,
       I want to know  What is the default password for the new createduser ？
       for example：
       **nebula> CREATE USER user1;**
       so I don't know password  for user1？
       Thank you very much.

**Comment by wey-gu** [comment]
see also:

```
(root@nebula) [basketballplayer]> CREATE USER user1
Execution succeeded (time spent 2.889ms/5.088208ms)

Mon, 29 May 2023 17:30:38 CST

(root@nebula) [basketballplayer]> CHANGE PASSWORD user1 FROM 'nebula' TO 'nebula123';
[ERROR (-1005)]: Invalid password!

Mon, 29 May 2023 17:31:00 CST

(root@nebula) [basketballplayer]> CHANGE PASSWORD user1 FROM '' TO 'nebula123';
Execution succeeded (time spent 2.912ms/4.289375ms)

Mon, 29 May 2023 17:31:07 CST

```

**Comment by wey-gu** [comment]
- [x] docs fixed by @cooper-lzy via https://github.com/vesoft-inc/nebula-docs-cn/pull/2806 https://github.com/vesoft-inc/nebula-docs/pull/2110
