### ISSUE TITLE
How to fail fast on query syntax errors

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula#5569]
Hi @wey-gu 
How to fail fast on query syntax errors?
Is there a way check query before executing?

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
