### ISSUE TITLE
Nebula Seems do not support ssl two way authentication with thrift

### ISSUE THREAD

**Issue by mo-avatar** [vesoft-inc/nebula#5576]
Nebula seems do not support ssl two way authentication with thrift.  the ssl ability of thrift  is build with folly and wangle. and I can find no where of the documentation of such libraries to perfrom two way authentication.

**Comment by wey-gu** [comment]
Do we have some update on mutual tls verification on thrift? @wenhaocs

**Comment by QingZ11** [comment]
@mo-avatar hi, I closed this issue because there hasn't been any update in over a month. If your problem is still not resolved, please feel free to reopen the issue and provide more information. We're here to help!
