### ISSUE TITLE
如何使一条删除edge语句和一条插入edge语句同时生效

### ISSUE THREAD

**Issue by LETMECALM** [vesoft-inc/nebula#5581]
**General Question**

在业务中需要对一条边的src点 和dst点做修改，原生nGQL 不支持，请问如何实现。

**Comment by QingZ11** [comment]
对起始点作变更，不就是产生了一条新的边么？用 insert 插入新边，再 delete 原来的边吧。没有别的方式了

**Comment by LETMECALM** [comment]
已解决
