### ISSUE TITLE
When the data is inserted to a certain level, no new data will be inserted

### ISSUE THREAD

**Issue by A-pppp** [vesoft-inc/nebula#5589]
![image](https://github.com/vesoft-inc/nebula/assets/26647264/a9a23978-0985-4280-a054-806c08bd22f9)

**Comment by QingZ11** [comment]
ref: [https://discuss.nebula-graph.com.cn/t/topic/13321](https://discuss.nebula-graph.com.cn/t/topic/13321)

In this post, a user encountered a problem similar to yours, the main reason is that there is a lot of duplication in the original data. 

If this user is not in the same team as you, please update the information.

If you belong to a team, next time the same problem will be distributed to one place, so as to avoid the same problem in multiple places.

在这个帖子中，有个用户遇到了和你类似的问题，主要原因是原始数据存在有大量的重复。如果这个用户和你不是一个团队的话，欢迎更新下信息。

如果是你们是一个团队的，下次同一个问题分发到一个地方就好啦，这样可以避免多处出现同一个内容。
