### ISSUE TITLE
更改配置文件中heartbeat_interval_secs 不生效

### ISSUE THREAD

**Issue by LETMECALM** [vesoft-inc/nebula#5596]
- 使用场景：先新增Tag，然后同步再新增Vertex，由于新增Tag是异步操作，所以新增Vertex会失败，文档中调整heartbeat_interval_secs 但未生效
- 异常信息（message=SemanticError: No schema found for `点新增测试4'）
- Nebula配置
![image](https://github.com/vesoft-inc/nebula/assets/45167548/86e77533-3954-45cf-9695-f79a5ed9762d)

**Comment by wey-gu** [comment]
Show us how you "changed" the conf, i.e. lines of config files you modified?

**Comment by LETMECALM** [comment]
- nebula-graphd.conf
![image](https://github.com/vesoft-inc/nebula/assets/45167548/5e5efade-0e2b-4e01-81f8-c91005c7e036)

- nebula-metad.conf
![image](https://github.com/vesoft-inc/nebula/assets/45167548/0a4e3674-344f-4a52-b1d3-1d89115230a0)

- nebula-storaged.conf
![image](https://github.com/vesoft-inc/nebula/assets/45167548/9a5f6dd0-be4f-4908-8389-374803990073)

**Comment by LETMECALM** [comment]
重启服务的shell脚本
![image](https://github.com/vesoft-inc/nebula/assets/45167548/fc06a410-1866-490c-a9d5-32810d013491)

**Comment by wey-gu** [comment]
请问，您的不生效的意思是配置 60，检查（curl flag）还是 60 ？这是**生效**了的哈。

感觉你是理解错了这里，想要更短的心跳，做到 DDL 之后可以更快做依赖 Schema Change 的 DML？因为心跳时间调这么久(60 sec）意味着 DDL/Schema Change 要最多 120 秒才能生效。

如果你期待更快的同步时间，改短心跳是可以的，不过改短心跳也是会有代价的，可以观察看看进行取舍。

另外，推荐用代码块包裹的分享日志或者配置，这样好出多多哈，比如：

```
foo bar
--x=y
```

**Comment by LETMECALM** [comment]
好的谢谢，解决了
