### ISSUE TITLE
[nGQL question] temp variable question

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#560]
1.  pipeline | is not working with variable

The whole sentence is someting like: 
```
$temp=(go from 100 over like | go from $-.id over like);  go from $temp.id over like 
```
```
$temp="go from 100 over like | go from $-.id over like";  go from $temp.id over like 
```
I want (go from 100 over like | go from $-.id over serve) as a subquery, and named the result as $temp.
I tried both (query) and "query", but all failed.
either syntax error or variable  temp not defined.

2.  I'd like to separate 
```
$temp=go from 100 over like; go from $temp.id over like"
```
into two lines. But...
```
nebula> $temp=go from 100 over like;                                                                                                                  

Execution succeeded (Time spent: 1313/1820 us)                                                                                                        

nebula> go from $temp.id over like;                                                                                                                   

[ERROR (-8)]: Variable `temp' not defined    
```

**Comment by dutor** [comment]
This will make the graph service stateful. We won't consider to do this before the transaction feature.

**Comment by sherman-the-tank** [comment]
The variables in nGQL is local to one execution. It cannot across multiple executions
