### ISSUE TITLE
[nGQL] Chinese punctune ；make service crash

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#562]
It's better to check the string.
at least not make service crash.

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/60409066-6c21f100-9bf4-11e9-8d4a-5c70d0d4541f.png)

**Comment by whitewum** [comment]
SHOW SPACES；
DROP SPACE myspace_test；
-- type by hand
CREATE SPACE myspace_test (partition_num=10, replica_factor=1);
--type by hand;
SHOW SPACES;
USE myspace_test；
SHOW TAGS; 
SHOW EDGES;
-- type by hand
CREATE TAG player(name string, age int);

CREATE TAG team(name string);
CREATE EDGE serve (start_year int, end_year int);
CREATE EDGE like (likeness double)；
-- type by hand
SHOW TAGS; 
SHOW EDGES;
DESCRIBE TAG player; 
DESCRIBE TAG team; 
DESCRIBE EDGE serve; 
DESCRIBE EDGE like;
INSERT VERTEX player(name, age) VALUES 100:("Stoudemire", 36);
INSERT VERTEX player(name) VALUES 101:("Vicenta"); 
INSERT VERTEX player(name) VALUES 102:("jummy");
INSERT VERTEX team(name) VALUES 201:("Magic");

INSERT EDGE like (likeness) VALUES 100 -> 101:(90.02);
INSERT EDGE like (likeness) VALUES 101 -> 102:(10);
INSERT EDGE serve (start_year, end_year) VALUES 101 -> 201:(2002, 2010);
INSERT EDGE serve (start_year, end_year) VALUES 102 -> 201:(2003, 2022);
GO FROM 100 OVER like;
GO 2 STEPS FROM 100 OVER like; 
GO FROM 100 OVER like WHERE like.likeness >= 10;
GO FROM 100 OVER like WHERE $$[player].name=="Vicenta";

GO FROM 100 OVER like  |  GO FROM $-.id OVER serve ;

GO FROM 101 OVER serve YIELD serve._src AS start_vertex_id, $^[player].age AS start_vertex_age, serve.start_year as s_year; 

GO FROM 101 OVER serve YIELD serve._dst AS end_vertex_id, $$[team].name AS end_vertex_name;

$temp=GO FROM 100 OVER like; GO FROM $temp.id OVER like;

**Comment by whitewum** [comment]
try to run all the above sensences in console. (put in a file, cat file | console )

**Comment by sherman-the-tank** [comment]
I believe this is due to our parser cannot handle illegal character, not just the Chinese punctuation

@dutor What do you think?

**Comment by dutor** [comment]
> I believe this is due to our parser cannot handle illegal character, not just the Chinese punctuation
> 
> @dutor What do you think?

For now any non-ascii character would be considered illegal, except ones in quotes(i.e. string literals). This is supposed to be a bug, I think. I will try on this.

@whitewum Thanks for this reporting.

**Comment by dutor** [comment]
I cannot reproduce this issue.

Actually this involves two problems:
  1. iIlegal chars. When our lexer encounters a illegal char, it invokes `yyterminate`, which is a macro to `return YY_NULL`. This has the same effect with EOF. So if the previously parsed tokens could be parsed successfully, the whole query are parsed normally, with all characters following the illegal char omitted. This is the very point we need to resolve.
  2. crashing. I cannot imagine any error or misbehavior in the parser could cause the storaged crash. After a simple investigation, I think the reason of the crash might be that *metad* and *storaged* fall in a bad situation while dealing with `DROP` and `CREATE` the same space, over and over, rapidly.

I could give a quick fix on the first issue, and will try to reproduce the latter one.

Thanks, again.

**Comment by whitewum** [comment]
@dutor can you reproduce the crash by the above commands?

**Comment by laura-ding** [comment]
crash steps: 
```
step 1: create space
step 2: restart servers
step 3: after  servers start done, drop space
```
crash reason:
```
RocksEngine has partsNum_ to count parts, when storage restart, nebulaStore will scan the files and the partsNum_ of RocksEngine will be double add.
```

**Comment by dangleptr** [comment]
> crash steps:
> 
> ```
> step 1: create space
> step 2: restart servers
> step 3: after  servers start done, drop space
> ```
> 
> crash reason:
> `RocksEngine has partsNum_ to count parts, when storage restart, nebulaStore will scan the files and the partsNum_ of RocksEngine will be double add.`

Please check #586
