### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by EliuGit** [vesoft-inc/nebula#5632]
centeros 7.x 8核16G
一个数据空间

Tag | items | 57299
Edge | has | 289339

执行语句:
MATCH (n)-[*1..2]-(p) where n.name=='晕可平颗粒'   RETURN n,p

![image](https://github.com/vesoft-inc/nebula/assets/7508425/315ef47e-42cf-4969-9a8c-7cb3a61c02af)

内存一直涨,到最后卡死

**Comment by nevermore3** [comment]
It's not a memory leak, but the memory monitoring is invalid, and it has been fixed https://github.com/vesoft-inc/nebula/pull/5619
