### ISSUE TITLE
bash: bin/nebula: No such file or directory

### ISSUE THREAD

**Issue by LifeForSoftwore** [vesoft-inc/nebula#564]

**Comment by LifeForSoftwore** [comment]
how to run   "bin/nebula --port=3699 -u=user -p=password"? 

I got "bash: bin/nebula: No such file or directory"

**Comment by jude-zhu** [comment]
did you run nebula from docker? From docker, run _./start-console.sh_

**Comment by jude-zhu** [comment]
did you run nebula in docker? From docker, run ./start-console.sh

**Comment by LifeForSoftwore** [comment]
It works. Thanks!
