### ISSUE TITLE
[nGQL] Get properties from vertex/edge.

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula#565]
Here I propose a syntax about getting properties from vertex/edge:
```
fetch vertex on [_id:]<vertex_id> [yield ...]
```

```
fetch edge on [(_src,_dst,_type,_rank):](<src_vid>, <dst_vid>, <edge_type>, <rank>) [yield ...]
```

@dutor @sherman-the-tank @whitewum

**Comment by CPWstatic** [comment]
Subtask of #492

**Comment by sherman-the-tank** [comment]
We've already used ```srcId->dstId:ranking``` to represent an instance of an edge type, so I would suggest to keep it consistent. One possible way to represent any edge is using ```srcId-[edge_type]->dstId:Ranking```. This is also similar to how OpenCypher represents an edge

```
fetch prop[erties] on {<vid>}+ [YIELDS ...]
```
```
fetch prop[erties] on {<srcId>-[edge_type]-><dstId>:Ranking}+ [YIELDS ...]
```

**Comment by CPWstatic** [comment]
Thank you!

**Comment by sherman-the-tank** [comment]
Here are some examples
```
# Fetch first name and last name from the tag person on vertex 12345
FETCH PROP ON 12345 YIELDS person.first_name, person.last_name

# Fetch all properties from the tag on vertex 12345
FETCH PROP ON 12345 YIELDS person.*

# Fetch all properties from an edge which starts from vertex 123 and points to vertex 456. The edge type is Friend and the ranking is 1000
FETCH PROP ON (123)-[friend]->(456):1000 YIELDS friend.*
```

**Comment by whitewum** [comment]
what if a vertex with three tags. and I want to fetch two tag props.

FETCH PROP ON 12345 YIELD person.*, player.* (but not superman.*)

BTW, YIELD or YIELDS?

**Comment by sherman-the-tank** [comment]
> BTW, YIELD or YIELDS?

For verbs, we supports both

**Comment by whitewum** [comment]
> > BTW, YIELD or YIELDS?
> 
> For verbs, we support both

ref #438
