### ISSUE TITLE
Is it possible to run batch/analytic jobs on offline replica of the graph?

### ISSUE THREAD

**Issue by shay1bz** [vesoft-inc/nebula#5666]
**General Question**

Does the Spark connector read data from the online Nabula instance? If so, is this not a limiting factor? We are planning to execute many daily jobs that process the entire graph.

Is it possible to fetch the data from some offline replica/snapshot, similar to HBase SnapshotInputFormat?

**Comment by wey-gu** [comment]
> Does the Spark connector read data from the online Nabula instance? If so, is this not a limiting factor? We are planning to execute many daily jobs that process the entire graph.

Spark connector bypassed the NebulaGraph-GraphD, it reads from the storaged directly, but yes, it reads from the leader-shard of all parts indeed.

>  Is it possible to fetch the data from some offline replica/snapshot, similar to HBase SnapshotInputFormat?


As I know this is not doable for now as non-leader read was not allowed for now.

One approach was to implement some sort of double-write to enable another cluster for analytical purposes. Besides, the enterprise version of NebulaGraph supports cluster-syncing features to make this easier.

**Comment by shay1bz** [comment]
@wey-gu thanks for your answer. Do you know if Nabula+Spark was tested under multiple applications scanning the entire graph? The scale in question is ~200M vertices, ~20B edges

**Comment by QingZ11** [comment]
Here is a performance report for the LDBC dataset test. It might be useful for you. ref: https://github.com/vesoft-inc/nebula-spark-connector#performance

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
