### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Haisenbergyy** [vesoft-inc/nebula#567]
How can I install the systerm in addition to docker?

**Comment by jude-zhu** [comment]
https://github.com/vesoft-inc/nebula/blob/master/docs/get-started.md

**Comment by jude-zhu** [comment]
related to #547

**Comment by LifeForSoftwore** [comment]
Thank you for your reply!　And here is another question. I want to deploy this database as a cluster. Is there any way to do that?

**Comment by whitewum** [comment]
> Thank you for your reply!　And here is another question. I want to deploy this database as a cluster. Is there any way to do that?
Of course. We'll provide a doc to explain the steps very soon (with the beta release).
so far, you can try the console by commands: add hosts ip:port

**Comment by darionyaphet** [comment]
#746
