### ISSUE TITLE
java.lang.NullPointerException - while writing to Edges using pyspark

### ISSUE THREAD

**Issue by DOT-py-sys** [vesoft-inc/nebula#5693]
### Discussed in https://github.com/vesoft-inc/nebula/discussions/5691

<div type='discussions-op-text'>

<sup>Originally posted by **DOT-py-sys** August 26, 2023</sup>
I am trying to write to nebula graph edges using pyspark -

**edge_df.write.format("com.vesoft.nebula.connector.NebulaDataSource").mode(
                    "overwrite").option(
                    "srcPolicy", "").option(
                    "dstPolicy", "").option(
                    "type", "edge").option(
                    "randkField","").option(
                    "spaceName", "nebulapoc").option(
                    "label", "testedge").option(
                    "srcVertexField", "id1").option(
                    "dstVertexField", "id2").option(
                    "batch", 1).option(
                    "graphAddress", self.graph_address).option(
                    "metaAddress", self.meta_address).option(
                    "passwd", "nebula").option(
                    "user", "root").option(
                    "operateType", "write").option(
                    "writeMode", "insert").save()**

Hi , its an issue we are facing in production , our nebula is deployed in a k8 cluster . We are able to write to vertex but when we are trying to write to edges , its throwing this exception . Please someone help .

**structure of the edge_df is below** 

```
id	id1	id2	edge_prop1	edge_prop2
1	4	11	sample1		test1
2	0	2	sample2		test2
3	8	6	sample3		test3
```

there are two vertex ( testvertex1 and testvertex2 ) 
they have 5 properties each 

nebulapoc schema has vidType fixed string 
there are two index on the above mentioned two vertex ( testvertex1_index , testvertex2_index )

There is no null / nan record in edge_df . 

What could be the possible scenario for which this is happening . 

</div>

**Comment by koustreak** [comment]
There is a problem in spark option in the code ( it will be rankField not randkField ) . 
There is a similar typo in nebula-spark connector github ReadME . 

![image](https://github.com/vesoft-inc/nebula/assets/91667110/eaa06d76-ec09-4877-8004-7064a251b558)

Requesting @wey-gu - to change that .

**Comment by QingZ11** [comment]
> There is a problem in spark option in the code ( **it will be rankField not randkField** ) .
> 
> There is a similar typo in **[nebula-spark connector github ReadME](https://github.com/vesoft-inc/nebula-spark-connector)** .
> 
> ![image](https://private-user-images.githubusercontent.com/91667110/263527573-eaa06d76-ec09-4877-8004-7064a251b558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTQ5NzgsIm5iZiI6MTcwMTg1NDY3OCwicGF0aCI6Ii85MTY2NzExMC8yNjM1Mjc1NzMtZWFhMDZkNzYtZWMwOS00ODc3LTgwMDQtNzA2NGEyNTFiNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZjQ5Nzg4NzA5YTE5Y2YwZmMwMjE3ZDQ5ZmViNzhlMjgyZjEwZjUzMzdhN2YzYzNmNDgwMjE1ZjI3ZWZhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W1LIuxH-BMf7BuI_APL0G2AMRarwlAnwG73eb_96XkQ)
> 
> Requesting @wey-gu - to change that .

@koustreak Good catch! Would you be interested in submitting a PR to fix it?

**Comment by wey-gu** [comment]
OMG, I missed this notification!!!

@koustreak thanks so much!!

I know it's silly/small, but you are cordially invited to help PR on it, would you mind?

Thanks again!

**Comment by koustreak** [comment]
Hi , @wey-gu , raised a pull request , https://github.com/vesoft-inc/nebula-spark-connector/pull/143

Let me know what you are thinking. 

Also there is another problem, in nebula-spark-connector-3.0_3.6.0 the username and password is getting printed in the LOGS , will raise it in issues with proper screenshots.

**Comment by wey-gu** [comment]
> Hi , @wey-gu , raised a pull request , [vesoft-inc/nebula-spark-connector#143](https://github.com/vesoft-inc/nebula-spark-connector/pull/143)
> 
> Let me know what you are thinking.
> 
> Also there is another problem, in nebula-spark-connector-3.0_3.6.0 the username and password is getting printed in the LOGS , will raise it in issues with proper screenshots.

Got it, thanks @koustreak a lot!

For the credentials being printed in logs, it's confirmed to be fixed in the master :-D

cc @Nicole00

**Comment by wey-gu** [comment]
update:

Confirmed by @Nicole00 it's fixed in https://github.com/vesoft-inc/nebula-spark-connector/releases/tag/v3.4.2 already, and we don't have 3.6.0 release on spark connector, await for your issue on it :-)!

**Comment by koustreak** [comment]
I think this issue can be closed . @wey-gu

**Comment by wey-gu** [comment]
> I think this issue can be closed . @wey-gu

OK, thanks @koustreak !
