### ISSUE TITLE
Fail to create a new session from connection pool

### ISSUE THREAD

**Issue by guhao17** [vesoft-inc/nebula#5717]
我上次试还可以连接，这次就不行了，显示超时，请问怎么解决
![4 YQ(XO% _PJ0ZKSU4F~3 I](https://github.com/vesoft-inc/nebula/assets/116614355/9b8d7cc2-fbb6-4129-a20e-7b7748dd8d83)

**Comment by guhao17** [comment]
重启就行

**Comment by QingZ11** [comment]
@guhao17 If your problem is solved, would you like to close the issue? Thanks a lot for your contribution.

你的问题是不是解决了，🤔 如果解决了的话，可以帮忙关下 issue 么？谢谢 guhao17
