### ISSUE TITLE
The difference between neo4j and nebula in this optional match feature

### ISSUE THREAD

**Issue by penghs520** [vesoft-inc/nebula#5718]
![image](https://github.com/vesoft-inc/nebula/assets/52020193/55517575-cdba-4d35-b355-82df225c8c01)

The variable declared in the optional match of neo4j cannot filter the starting node effectively when it appears as a condition in the where. 
But in nebula, this works well, will nebula keep this feature? That's important to me

**Comment by wey-gu** [comment]
Interesting, could you explain more on "The variable declared in the optional match of neo4j cannot filter the starting node effectively"?

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
