### ISSUE TITLE
There is a small bug about the container name in quick start of docs

### ISSUE THREAD

**Issue by HaoXuan40404** [vesoft-inc/nebula#5725]
https://docs.nebula-graph.com.cn/3.6.0/2.quick-start/1.quick-start-overview/
3.6.0版本
NebulaGraph Console 容器名称应该为nebula-docker-compose_console_1，而不是nebuladockercompose_console_1
![image](https://github.com/vesoft-inc/nebula/assets/34049754/813e1ea3-d565-498e-b694-e797a76d0b0e)

**Comment by HaoXuan40404** [comment]
<img width="413" alt="image" src="https://github.com/vesoft-inc/nebula/assets/34049754/98a03ac2-d691-4cd6-8856-234cef1f0f8c">

**Comment by HarrisChu** [comment]
Good catch!
