### ISSUE TITLE
docker-compse based Nebula Studio is not able to be installed on Apple chip macBook 

### ISSUE THREAD

**Issue by chenrq2005** [vesoft-inc/nebula#5730]
**Introduction**

Any solution?
**Contents**

**Related work**

**Comment by wey-gu** [comment]
It's totally doable, and, we could install it directly via the docker extension with just on click.

ref: https://www.docker.com/blog/distributed-cloud-native-graph-database-nebulagraph-docker-extension/

**Comment by chenrq2005** [comment]
Thank you!!

**Comment by wey-gu** [comment]
Out of curiosity what failure have you encountered in plain docker compose for the studio? it should be working, too.
