### ISSUE TITLE
may --use_vertex_key option cause stats error?

### ISSUE THREAD

**Issue by xl-better** [vesoft-inc/nebula#5732]
consider this case:
We first set "--use_vertex_key" equals false, and some vertices is inserted, then restart service with "--use_vertex_key" equals true, Will this lead to incorrect vertex count statistics?

**Comment by wey-gu** [comment]
`use_vertex_key` with default false means to not enable/allow tagless vertices, search it from docs, and you will find more explanations.

tagless is not recommended to be used any more.

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
