### ISSUE TITLE
order by index;

### ISSUE THREAD

**Issue by Mr-LLLLL** [vesoft-inc/nebula#5739]
**General Question**

i have 1000w vertex in person tag; and i had build index for tag person(age), i use  `lookup on person yield properties(vertes).age as age | order by $-.age limit 10;` is spent a lot time about(44s), i want to know whether a way to optimize this?

**Comment by Mr-LLLLL** [comment]
used profile in ngql, i found nebula scan full index first. by the way, i want to know nebula index data strcuct is Hash, i can't find any doc talked about?

**Comment by QingZ11** [comment]
Sorry for the late reply. For an introduction to the principles of indexing, you can read this link: [https://www.nebula-graph.io/posts/how-indexing-works-in-nebula-graph](https://www.nebula-graph.io/posts/how-indexing-works-in-nebula-graph)

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
