### ISSUE TITLE
Used memory hits the high watermark(0.800000) of total system memory.

### ISSUE THREAD

**Issue by LETMECALM** [vesoft-inc/nebula#5745]
Question: Used memory hits the high watermark(0.800000) of total system memory.
版本：3.4，会出现周期性OOM问题，请问如何解决

**Comment by Nicole00** [comment]
https://docs.nebula-graph.com.cn/3.6.0/5.configurations-and-logs/1.configurations/3.graph-config/#memory
可以修改 nebula-graphd.conf 里的这个配置，然后重启graphd 
该值默认是 0.8 表示 80% ，可以改成 0.9999

**Comment by LETMECALM** [comment]
阈值的判断条件是 可用内存/(总内存 - 保留内存) ，改成 0.99 可用内存还是低于该阈值，应该是调低而不是调高吧，调阈值的方式应该是治标不治本吧。报该异常是进行 match query 命令是报错，其他图相关操作是正常的，match 操作会占用系统内存吗，默认开启了memory_purge_enabled = true 定期清理内存，为啥内存空间没有得到释放，这个问题是周期性出现的，望解答。

**Comment by wey-gu** [comment]
> OOM

"Memory Tracker" was introduced in 3.4.0, highly recommended to leverage it to help with this.

**Comment by LETMECALM** [comment]
How to use Memory Tracker ?

**Comment by wey-gu** [comment]
> How to use Memory Tracker ?

You could refer to docs and a blog post explaining about how to configure/leverage it :)

CN:
- https://docs.nebula-graph.com.cn/3.6.0/5.configurations-and-logs/1.configurations/4.storage-config/#memory_tracker
- https://discuss.nebula-graph.com.cn/t/topic/13128

EN:

- https://docs.nebula-graph.io/3.6.0/5.configurations-and-logs/1.configurations/4.storage-config/#memory_tracker_configurations
- https://www.nebula-graph.io/posts/memory-tracker-practices

**Comment by wey-gu** [comment]
> Why isn't the memory space being released? 

It's about storaged, not graphd, right?
There are caches(rocksDB) there, which are configurable, too(see storaged configuration docs, and rocksdb docs).

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

**Comment by peak-xu** [comment]
> > OOM
> 
> "Memory Tracker" was introduced in 3.4.0, highly recommended to leverage it to help with this.

Must it be a container environment to use memory tracker

**Comment by wey-gu** [comment]
> > > OOM
> 
> > 
> 
> > "Memory Tracker" was introduced in 3.4.0, highly recommended to leverage it to help with this.
> 
> 
> 
> Must it be a container environment to use memory tracker？

no , it's supported on both container and bare metal.
