### ISSUE TITLE
How to quickly query information on vertices without edges?

### ISSUE THREAD

**Issue by momoco530** [vesoft-inc/nebula#5746]
As title

**Comment by QingZ11** [comment]
https://discuss.nebula-graph.com.cn/t/topic/12818/

你去这个帖子里，ctrl + f 或者是 command + f 搜索下没有边（如图所示）你就可以看到对应的语句了。

<img width="1561" alt="image" src="https://github.com/vesoft-inc/nebula/assets/38887077/b0fef72c-2d48-4810-b002-d653d16e1d8e">

**Comment by wey-gu** [comment]
> As title

```
MATCH (v:TagA) where id(v) == "xxx" RETURN v
```

```
FETCH PROP ON player "player100" YIELD properties(vertex);
```

It may be tricky for the fresh user to know which CLAUSE to use, apart from walking through all nGQL overview chapters of the docs, you could also refer to my cheatsheet.

https://www.siwei.io/ngql-tutorial/ngql-cheatsheet.png

We'll add such all-in-one page of docs in docs as well, see https://github.com/vesoft-inc/nebula-docs/issues/2316

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
