### ISSUE TITLE
Unable to build UDFs

### ISSUE THREAD

**Issue by jjsimps** [vesoft-inc/nebula#5761]
**Describe the bug**

When I build the UDFs for centos7 (using the nebula-dev image), it builds fine. However, when try to use the UDF in nebula I get the error:

`/lib64/libstdc++.so.6: version 'CXXABI_1.3.9' not found`

It seems the UDF is being built with ABI 1.3.9, but that doesn't come included on the centos7 image for graphd:

```
[root@nebula-graphd-2 nebula]#  nm -D /lib64/libstdc++.so.6 | grep CXXABI
0000000000000000 A CXXABI_1.3
0000000000000000 A CXXABI_1.3.1
0000000000000000 A CXXABI_1.3.2
0000000000000000 A CXXABI_1.3.3
0000000000000000 A CXXABI_1.3.4
0000000000000000 A CXXABI_1.3.5
0000000000000000 A CXXABI_1.3.6
0000000000000000 A CXXABI_1.3.7
0000000000000000 A CXXABI_TM_1
```

I tried statically linking libstd++, but that's just causing memory leaks in graphd [see this issues](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70806).

So if I can't statically link it, then I must match the ABI version. But this doesn't seem possible without downgrading the buildtools.

**Your Environments (__required__)**

- Nebula graph 3.6.0 (and the pre-built images)
- Running on GKE 1.26
- Using nebula operator

**How To Reproduce(__required__)**

1. Startup nebula-dev image
2. build make UDF=standard_deviation
3. Load into nebula 3.6 using pre-built images
4. See error in logs

**Expected behavior**

No UDF error, no build error, no memory leaks.

I also noticed that It calls dlopen() every time the function is called, which seems like it would cause a huge performance overhead. Why not cache the function pointer?

**Comment by wey-gu** [comment]
- missing ABI dep, I used to do so with the binary package being installed from vanilla Ubuntu docker image like: https://github.com/wey-gu/nebulagraph-ai/blob/main/docker/Dockerfile-ngai-graphd , could you go with this way first?

- > I also noticed that It calls dlopen() every time the function is called, which seems like it would cause a huge performance overhead. Why not cache the function pointer?

@yixinglu could we decouple the dlopen() per non-first time UD function call?

**Comment by yixinglu** [comment]
@jjsimps Have you tried pulling the `vesoft/nebula-dev:centos7` image again? Locally I get the following output from your above command:

```
$ docker run --rm -ti vesoft/nebula-dev:centos7 bash                                                                                                                                                       130 ↵
[root@d0f41c1786bc ~]# nm -D /lib64/libstdc++.so.6 | grep CXXABI
0000000000000000 A CXXABI_1.3
0000000000000000 A CXXABI_1.3.1
0000000000000000 A CXXABI_1.3.10
0000000000000000 A CXXABI_1.3.11
0000000000000000 A CXXABI_1.3.12
0000000000000000 A CXXABI_1.3.2
0000000000000000 A CXXABI_1.3.3
0000000000000000 A CXXABI_1.3.4
0000000000000000 A CXXABI_1.3.5
0000000000000000 A CXXABI_1.3.6
0000000000000000 A CXXABI_1.3.7
0000000000000000 A CXXABI_1.3.8
0000000000000000 A CXXABI_1.3.9
0000000000000000 A CXXABI_FLOAT128
0000000000000000 A CXXABI_TM_1
[root@d0f41c1786bc ~]#
```

**Comment by wey-gu** [comment]
> @jjsimps Have you tried pulling the `vesoft/nebula-dev:centos7` image again? Locally I get the following output from your above command:
> 
> ```
> $ docker run --rm -ti vesoft/nebula-dev:centos7 bash                                                                                                                                                       130 ↵
> [root@d0f41c1786bc ~]# nm -D /lib64/libstdc++.so.6 | grep CXXABI
> 0000000000000000 A CXXABI_1.3
> 0000000000000000 A CXXABI_1.3.1
> 0000000000000000 A CXXABI_1.3.10
> 0000000000000000 A CXXABI_1.3.11
> 0000000000000000 A CXXABI_1.3.12
> 0000000000000000 A CXXABI_1.3.2
> 0000000000000000 A CXXABI_1.3.3
> 0000000000000000 A CXXABI_1.3.4
> 0000000000000000 A CXXABI_1.3.5
> 0000000000000000 A CXXABI_1.3.6
> 0000000000000000 A CXXABI_1.3.7
> 0000000000000000 A CXXABI_1.3.8
> 0000000000000000 A CXXABI_1.3.9
> 0000000000000000 A CXXABI_FLOAT128
> 0000000000000000 A CXXABI_TM_1
> [root@d0f41c1786bc ~]#
> ```

I guess @jjsimps is about to run graphd with udf folder attached in production, thus leveraging our graphd docker image rather than the dev one.

**Comment by yixinglu** [comment]
> * missing ABI dep, I used to do so with the binary package being installed from vanilla Ubuntu docker image like: https://github.com/wey-gu/nebulagraph-ai/blob/main/docker/Dockerfile-ngai-graphd , could you go with this way first?
> 
> * > I also noticed that It calls dlopen() every time the function is called, which seems like it would cause a huge performance overhead. Why not cache the function pointer?
>   
>   
>   @yixinglu could we decouple the `dlopen()` per non-first-time UD function call with some cache mechanism?

It is a very bad design to execute `dlopen` every time udf is called, which will cause serious performance problems, because udf will be called for each row at runtime. This feature comes from contributors in the community. In fact, it has been in an unreleased state. Could you request some enhancements from the contributor for that? If no one is willing to make improvements, we can consider making corrections, but this is not our current focus. We will completely solve this problem when we open source of the new version.

**Comment by yixinglu** [comment]
> > @jjsimps Have you tried pulling the `vesoft/nebula-dev:centos7` image again? Locally I get the following output from your above command:
> > ```
> > $ docker run --rm -ti vesoft/nebula-dev:centos7 bash                                                                                                                                                       130 ↵
> > [root@d0f41c1786bc ~]# nm -D /lib64/libstdc++.so.6 | grep CXXABI
> > 0000000000000000 A CXXABI_1.3
> > 0000000000000000 A CXXABI_1.3.1
> > 0000000000000000 A CXXABI_1.3.10
> > 0000000000000000 A CXXABI_1.3.11
> > 0000000000000000 A CXXABI_1.3.12
> > 0000000000000000 A CXXABI_1.3.2
> > 0000000000000000 A CXXABI_1.3.3
> > 0000000000000000 A CXXABI_1.3.4
> > 0000000000000000 A CXXABI_1.3.5
> > 0000000000000000 A CXXABI_1.3.6
> > 0000000000000000 A CXXABI_1.3.7
> > 0000000000000000 A CXXABI_1.3.8
> > 0000000000000000 A CXXABI_1.3.9
> > 0000000000000000 A CXXABI_FLOAT128
> > 0000000000000000 A CXXABI_TM_1
> > [root@d0f41c1786bc ~]#
> > ```
> 
> I guess @jjsimps is about to run graphd with udf folder attached in production, thus leveraging our graphd docker image rather than the dev one.

I checked that the implementation of the code does not execute `dlopen` every time. All udfs are loaded only at the beginning and then saved in the function manager, so the problem mentioned above should not exist.

**Comment by jjsimps** [comment]
Thanks for the input everyone! 

@wey-gu is exactly correct -- the UDFs are built using the nebula-dev image which has the builtools and `CXXABI_1.3.9`. But the prod image is the regular centos7 image which does not have it.

I also tried your suggestion of building using ubuntu2004 image and that seems to work. But that does require me to build my own graphd image using ubuntu2004 (not the worst, but not ideal of course). I expect the same would be fine if I build the graphd image using the nebula-dev:centos7 as the base image instead of just centos7.

As for calling dlopen, [please see here](https://github.com/vesoft-inc/nebula/blob/4c6a0a7dae7df0373b7e8eb7537e27f7de012422/src/common/function/FunctionUdfManager.cpp#L184). As you can see, the lambda, when called, will call dlopen(), create the UDF, call it, destroy, then call dlclose().

I do realize that this feature was kinda put in as a sealth feature (not fully documented, but referenced in release notes). I was looking forward to it as it allows me to run a bit more complex logic that would either otherwise manifest as a very complex query (with branch, bitwise operators, etc), or have to be taken back to the application level.

What would you say is the current outlook/roadmap for the serious UDF support? Is there anywhere I can find out this info? In the meantime, I think that the current implementation is 85% there for most of my use-cases. I would like to know the proper solution for dealing with the ABI (hopefully by changing the prod base image to something that has it), and also a fix for the performance issue when calling the UDF (I noticed query times jump from 10s of ms to 100s of ms when calling a cusom UDF which seems absurd).

Thank you :)

**Comment by jjsimps** [comment]
Awesome, thank you.

I tried the `rpath` method + shipping `libstdc++.6.so` and that seems to work.

I'll see about refactoring some of the code to bring it back up to a bit of a better level.
