### ISSUE TITLE
502 Bad Gateway Error on Certification Exam Page

### ISSUE THREAD

**Issue by yangtuooc** [vesoft-inc/nebula#5763]
**Describe the bug (__required__)**

When trying to access the NebulaGraph certification exam page at `https://academic.nebula-graph.io/certifications`, the server returns a 502 Bad Gateway error. This has been occurring consistently since [time/date you first noticed the issue], preventing access to the certification exam.

**How To Reproduce(__required__)**

1. Navigate to `https://academic.nebula-graph.io/certifications`
2. Observe the 502 Bad Gateway error presented by the browser

**Expected behavior**

The certification exam page should load properly without any server errors, allowing users to take the certification exam.

**Additional context**

The issue has been reproduced in multiple browsers including Chrome and Firefox, and after clearing the browser cache. Here is a screenshot of the error page: 
<img width="1073" alt="image" src="https://github.com/vesoft-inc/nebula/assets/125647696/4e424ff0-ac2f-4a46-8015-ce0e3113538d">

**Comment by QingZ11** [comment]
Engineers are currently investigating the issue and working on a fix. Thank you very much for your feedback. Once the issue is resolved, I will update with another comment.
