### ISSUE TITLE
The param: ”noloop“ in find path does not exclude ”self-loop“

### ISSUE THREAD

**Issue by lishihao97** [vesoft-inc/nebula#5764]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
在find path语句中使用noloop参数未排除自环情况
NGQL：
find noloop path from "nodea" to "nodea" over e1 YIELD PATH as p 

![image](https://github.com/vesoft-inc/nebula/assets/40377824/c6bc304b-b6cb-4536-8a7b-c4c07feb3b89)

The param: ”noloop“ in find path does not exclude ”Loop“

**Your Environments (__required__)**
nebula 3.6
* OS: `linux 3.10.0-1062.9.1.el7.x86_64`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

ref: [https://discuss.nebula-graph.com.cn/t/topic/14370](https://discuss.nebula-graph.com.cn/t/topic/14370)

**Comment by AntiTopQuark** [comment]
Is the issue definitively buggy, please?
If it needs to be fixed, can I be assigned this task?

**Comment by wey-gu** [comment]
Wow, thanks so much @AntiTopQuark !!!

Sure! I assigned this to you, let us know what help from us could be provided any time, and take your time!

cc @MuYiYong @yixinglu
