### ISSUE TITLE
NebularGraph just support english?

### ISSUE THREAD

**Issue by JinSeoung-Oh** [vesoft-inc/nebula#5765]
I'm building GraphRAG with nebular graph and Llama-index.
I made a module for extracting triplet from korean chunk data
And pass it Llama-index, it return english KG not korean KG.
I don't want translate my korean triplet. I just want to make korean KG.

I searched NebularGraph just only support English, but I cannot find out.

Basically, NebularGarph Query is English(at least, keyword)
So, maybe, because of this my korean triplet translate to english 
But, if I'm not wrong, the language used to create the graph doesn't matter. It's only a problem in queries.

So, I want know why my korean triplet translate english triplet
Does Nebula Graph have a function to translate the given text into English and save it?

Thanks!

**Comment by wey-gu** [comment]
Dear @JinSeoung-Oh , welcome to the NebulaGraph community!

We could override the prompt and (if openai was used, adding a system prompt to remind him to keep original languages may help, too).

In [this example](https://www.siwei.io/demo-dumps/local-llm/Graph_RAG_Local.html), I showed how to leverage models other than openai && how to override triplet extraction prompts for your reference(sorry it's in Chinese)!

Let us know your attempts and results!

Thanks!

**Comment by JinSeoung-Oh** [comment]
@wey-gu, Thanks! It is very helpful.
A few minutes ago, I re-run my code that has already failed dozens of times to return korean KG
and knowledgeGraphIndex return korean KG, suddenly

Maybe your right. It is Llama_index error, maybe..

Thank for your help and have a nice day!

Thanks!!

**Comment by wey-gu** [comment]
Yes, I encountered this when building chinese kg with local models and the way to mitigate was to override the prompts for triplets extraction as in above example link :D.

Feel free to ping me for anything I could help.

PS. will bring more optimization for knowledge graph index/text2cypher/graph rag to llamaindex next week!
