### ISSUE TITLE
[ disscuss - nGQL ] should nebula provide nGQL format style

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#577]
As we have more documents, pictures and ppts (and web-console) about nGQL, it's better to provide a recommended nGQL coding format style. -- Pictures can't be easily changed.

Here is an example.

```
GO FROM 123 OVER like_edge WHERE like_edge.Prop1  --like_edge is the edge type, Prop1 is a property
GO FROM 123 OVER ike_edge WHERE $$[player].Age >= 30  /* a comment */ YIELD --player is a tag
use -- and /* */ to comment, not recommend //
no ; at the end. Only used for separating two stmts.
```
@dutor @sherman-the-tank @dangleptr

**Comment by sherman-the-tank** [comment]
Agreed. We need a nGQL style guideline

@jude-zhu @Amber1990Zhang
