### ISSUE TITLE
$^,$$ value reversed

### ISSUE THREAD

**Issue by cjdxhjj** [vesoft-inc/nebula#5779]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

![image](https://github.com/vesoft-inc/nebula/assets/5616997/f2b433da-11f2-4b70-9cb1-08949ddafe89)
the edge begin from col:2615 to metric:f1ee2e6076724c8a9af40680d67ca549, but the id($^) return metric:f1ee2e6076724c8a9af40680d67ca549 and id($$) return col:2615

**Expected behavior**

**Additional context**

**Comment by cjdxhjj** [comment]
what the source and target mean?

**Comment by cjdxhjj** [comment]
![image](https://github.com/vesoft-inc/nebula/assets/5616997/b88c7f0b-ec69-48e0-a8de-d9851ae9df58)
the src(edge), and dst(edge) return correct

**Comment by QingZ11** [comment]
"src" and "dst" represent the starting point and the ending point of an edge, respectively, while `$^` and `$$` are reference symbols in the NebulaGraph query language nGQL, used to refer to the starting and ending points.

**Comment by wey-gu** [comment]
Great catch!

You are seeing the nature difference between `$$` and `dst`.

Each edge was persisted twice, one together its starting vertex and on the ending vertex(the inverse edge), and `dst` ensured the expected direction of this behavior.

You could add this `typeid(edge)` to better understand it, when typeid is negative, you are getting the edge that's the inverse edge.

```
go from "player100" over * bidirect yield dst(edge), src(edge), id($$), id($^), typeid(edge)
+-------------+-------------+-------------+-------------+--------------+
| dst(EDGE)   | src(EDGE)   | id($$)      | id($^)      | typeid(EDGE) |
+-------------+-------------+-------------+-------------+--------------+
| "player100" | "player101" | "player101" | "player100" | -5           |
| "player100" | "player102" | "player102" | "player100" | -5           |
| "player100" | "player104" | "player104" | "player100" | -5           |
| "player100" | "player105" | "player105" | "player100" | -5           |
| "player100" | "player107" | "player107" | "player100" | -5           |
| "player100" | "player108" | "player108" | "player100" | -5           |
| "player100" | "player109" | "player109" | "player100" | -5           |
| "player100" | "player113" | "player113" | "player100" | -5           |
| "player100" | "player125" | "player125" | "player100" | -5           |
| "player100" | "player144" | "player144" | "player100" | -5           |
| "post1"     | "player100" | "post1"     | "player100" | 9            |
| "post11"    | "player100" | "post11"    | "player100" | 9            |
| "player101" | "player100" | "player101" | "player100" | 5            |
| "player125" | "player100" | "player125" | "player100" | 5            |
| "addr_4"    | "player100" | "addr_4"    | "player100" | 14           |
| "team204"   | "player100" | "team204"   | "player100" | 4            |
+-------------+-------------+-------------+-------------+--------------+
Got 16 rows (time spent 3.472ms/12.645375ms)
```

**Comment by cjdxhjj** [comment]
thanks for your  replay, @wey-gu @QingZ11
