### ISSUE TITLE
Does NebulaGraph support semantic search yet ?

### ISSUE THREAD

**Issue by younes-io** [vesoft-inc/nebula#5785]
According to  @wey-gu in [this video](https://www.youtube.com/watch?v=hb8uT-VBEwQ&ab_channel=LlamaIndex) [1:24:05], this is work in progress 3 months ago, and research results are good. I'm just asking, do we have an implementation yet ?

Looking forward to getting an answer

**Comment by QingZ11** [comment]
@wey-gu could you provide any updates on this issue? If it has been resolved, could you share the solution and consider closing this issue?
