### ISSUE TITLE
Some ideas about performance optimization

### ISSUE THREAD

**Issue by xl-better** [vesoft-inc/nebula#5791]
I have some queries like 
"GO FROM "vid1" OVER edge YIELD edge._dst AS id | \
FETCH PROP ON tag $-.id YIELD tag.prop1, tag.prop2 \
UNION ALL
GO FROM "vid2" OVER edge YIELD edge._dst AS id | \
FETCH PROP ON tag $-.id YIELD tag.prop1, tag.prop2 \"
and i have some ideas like:
1. Start the subquery immediately after obtaining partial results in pipe sentence rather than execute after get all results;
2. "UNION/UNION ALL" sub sentence may be concurrent;
I'd like to ask will these ideas do help for performance and are they viable?

**Comment by Salieri-004** [comment]
1. The first question is actually a classic question about the database execution model, Nebula is currently using **materialization model**, so the operator "executes after get all results." We're also working on  **vectorization model** internally, which should be released sometime next year. You can think of this as what you say "start the subquery immediately after obtaining partial results in pipe sentence".
2. The second question, "sub sentence may be concurrent ". I think that's what Nebula is doing now, and you can use **explain statement** to view your execution plan.

**Comment by xl-better** [comment]
I see, thanks
