### ISSUE TITLE
Question about performance of the pipeline 

### ISSUE THREAD

**Issue by xl-better** [vesoft-inc/nebula#5792]
《NebulaGraph Database手册》管道对性能的影响中提到 “管道本身是需要序列化和反序列化的，这个是单线程执行的”。

"GO FROM "player127" OVER follow YIELD follow._dst AS fp | \
 GO FROM $-.fp OVER serve YIELD serve._dst AS team"
在此例子中，执行管道左边的GO语句后得到VID并存在`ectx_`中，在执行管道右侧语句时从`ectx_`中取出VID。请问此过程涉及序列化和反序列化吗？

**Comment by Salieri-004** [comment]
感谢您提供的问题。我认为这个阶段并不涉及多余的序列化和反序列化，这里的描述可能引起误导，我们会在之后对其进行修正。

**Comment by xl-better** [comment]
好的，谢谢
