### ISSUE TITLE
vertexId not exists, but return props are not null 

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#580]
First, I define the tag and edge schema
```
CREATE TAG student(name string, age int, gender string)
CREATE EDGE like(likeness double)
```

And then insert a vertex and an edge
```
INSERT VERTEX student(name, age, gender) VALUES 201:("Mike", 18, "male");
INSERT EDGE like (likeness) VALUES 201 -> 203:(93.2);
```
the dest. vertex is undefined. However, when I try
```
GO FROM 201 OVER like YIELD $^[student].name AS Student, $$[student].name AS Friend, $$[student].age AS Age, $$[student].gender AS Gender
```
the dest. props are not null

![20190704112851](https://user-images.githubusercontent.com/51590253/60638162-df736f00-9e4f-11e9-8072-766d358a5b1d.jpg)

**Comment by monadbobo** [comment]
When the storage layer performs a vertex lookup(QueryBoundProcessor::processVertex), if the  vertex does not exist, the vertex data should not be set at this time. And the query engine also needs to handle this situation, I will fix this problem.
