### ISSUE TITLE
How to export data?

### ISSUE THREAD

**Issue by zjx20** [vesoft-inc/nebula#5806]
## Question

The document https://docs.nebula-graph.io/3.6.0/import-export/write-tools/ only describes how to import data, but how to export data?

**Comment by QingZ11** [comment]
You can export the data by writing code and using the NebulaGraph Spark Connector.

* spark-connector docs: [https://docs.nebula-graph.io/3.6.0/connector/nebula-spark-connector/](https://docs.nebula-graph.io/3.6.0/connector/nebula-spark-connector/)

**Comment by zjx20** [comment]
Got it, thanks.
