### ISSUE TITLE
"no suitable node (unsupported platform on 1 node)"

### ISSUE THREAD

**Issue by Alohawsq** [vesoft-inc/nebula#5810]
**General Question**

image: vesoft/nebula-console:v3.3.0
paltform: arm

**Comment by wey-gu** [comment]
![Screenshot 2024-01-22 at 17 50 25](https://github.com/vesoft-inc/nebula/assets/1651790/fe4c1e28-25da-49b6-96eb-b7b52ebc454c)

https://hub.docker.com/r/vesoft/nebula-console/tags

NebulaGraph Console started support dual-arch(arm64) after 3.4.0.

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
