### ISSUE TITLE
edge type 出现大小写混乱

### ISSUE THREAD

**Issue by AntarcticPresident** [vesoft-inc/nebula#5813]
这是报错：
```
EdgeNotFound: EdgeName `http`
```
提示我http这个edge type不存在。
而实际上我的ngql是：
```
INSERT EDGE HTTP() VALUES "A"->"B":()
```
edge type 是HTTP。
如果我再创建一个edge type：http，这个报错就消失了，数据也可以正常写入。
我试了其他的edge type，例如：
tcp和TCP，udp和UDP。都是区分大小写的。
只有HTTP，都给给改成http了。
这是为啥？

**Comment by AntarcticPresident** [comment]
Here is error report:
```
EdgeNotFound: EdgeName `http`
```
It reminded me the edge type whose name is http didn't exist.
In fact, my ngql is 
```
INSERT EDGE HTTP() VALUES "A"->"B":()
```
My edge type is 'HTTP'.
if I create a new edge type which is http, the error report will disappear. The data inserted correctly.
I tried another edge types, for example:
tcp and TCP, udp and UDP. They both worked well.
Only HTTP, I have to create an edge type named http, otherwise, it will report error.
Why?

**Comment by QingZ11** [comment]
> 这是报错：
> 
> ```
> EdgeNotFound: EdgeName `http`
> ```
> 
> 提示我http这个edge type不存在。 而实际上我的ngql是：
> 
> ```
> INSERT EDGE HTTP() VALUES "A"->"B":()
> ```
> 
> edge type 是HTTP。 如果我再创建一个edge type：http，这个报错就消失了，数据也可以正常写入。 我试了其他的edge type，例如： tcp和TCP，udp和UDP。都是区分大小写的。 只有HTTP，都给给改成http了。 这是为啥？

https://docs.nebula-graph.com.cn/3.6.0/3.ngql-guide/1.nGQL-overview/keywords-and-reserved-words/

应该是保留字的缘故。

**Comment by AntarcticPresident** [comment]
非常感谢~
