### ISSUE TITLE
How to fetch the TTL info of the tag or edge?

### ISSUE THREAD

**Issue by haoxins** [vesoft-inc/nebula#5828]
**General Question**

Hi, I can't find a way to fetch the TTL info of a tag or an edge.
It seems that `DESC tag/edge` not returns the TTL info?

**Comment by QingZ11** [comment]
Try command `SHOW CREATE TAG tagName`, ref:https://docs.nebula-graph.com.cn/3.6.0/3.ngql-guide/7.general-query-statements/6.show/5.show-create-tag-edge/

**Comment by haoxins** [comment]
thanks a lot
