### ISSUE TITLE
Do you have a Vue component for displaying graphs?

### ISSUE THREAD

**Issue by papandadj** [vesoft-inc/nebula#5832]
最近想用vue展示下图数据库的内容，看过wey-gu做的展示，不知道是用什么组件画的还是直接自己写的

**Comment by QingZ11** [comment]
如果你要做数据话展示的话，你可以看下 Nebula 开源的可视化工具 nebula-studio：https://github.com/vesoft-inc/nebula-studio

If you are interested in visualizing data, you may want to explore Nebula's open-source visualization tool called nebula-studio: https://github.com/vesoft-inc/nebula-studio.

**Comment by papandadj** [comment]
好的

**Comment by QingZ11** [comment]
这个问题先行关闭了，你如果有其他的问题，可以再开一个 issue 来交流，谢谢 [papandadj](https://github.com/papandadj)。

This issue will be closed for now. If you have any other problems, please feel free to open another issue to discuss. Thank you.
