### ISSUE TITLE
Suggest contributing this project to the Apache Foundation

### ISSUE THREAD

**Issue by JinsYin** [vesoft-inc/nebula#5849]
This project is currently not as active, it is recommended to contribute to the Apache Foundation.

**Comment by QingZ11** [comment]
Thank you for your attention. According to your criteria, nebula may be considered an inactive project. However, this does not mean that the foundation, not just the Apache Foundation, will help to improve the project's activity. You can take a look at the Apache retired projects list: https://incubator.apache.org/projects/#retired

In fact, the core team of nebula is currently developing a major version, and the new version will be released soon.
