### ISSUE TITLE
Two different storage engine may contain same part when NebulaStore init.

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#585]
there is a problem that we config two data path like a and b, then there are two engines engine_a and engine_b, and engine_a has two parts 1 and 2, engine_b has 3. when call addPart with partId 1, then minIndex is engine_b, and the result cause that part 1 in two engine

**Comment by dangleptr** [comment]
Good catch!

**Comment by dangleptr** [comment]
The bug was introduced by #344
