### ISSUE TITLE
Unable to retrieve data.

### ISSUE THREAD

**Issue by AntarcticPresident** [vesoft-inc/nebula#5853]
![image](https://github.com/vesoft-inc/nebula/assets/12134408/28f8b23a-d648-4043-8e39-0974d35ce17b)
![image](https://github.com/vesoft-inc/nebula/assets/12134408/08d9025c-3c35-47eb-94a2-d6f9b9a67ab9)
统计显示有132条数据，查询缺一条都查不到

**Comment by QingZ11** [comment]
如果你要成功执行该语句的话，你得给 `listener_service` 这个边创建索引，并在创建之后进行 rebuild index 操作。

If you want to successfully execute this statement, you need to create an index on the `listener_service` edge and perform a "rebuild index" operation after the index creation.

**Comment by AntarcticPresident** [comment]
现在问题消失了。
我记得我是创建索引了的，索引问题我遇到几次了，应该不会忘。
不过现在没了，说不清了。。。
就这样吧，谢谢啦~
