### ISSUE TITLE
如果你要成功执行该语句的话，你得给 `listener_service` 这个边创建索引，并在创建之后进行 rebuild index 操作。

### ISSUE THREAD

**Issue by CyanMystery** [vesoft-inc/nebula#5929]
如果你要成功执行该语句的话，你得给 `listener_service` 这个边创建索引，并在创建之后进行 rebuild index 操作。

If you want to successfully execute this statement, you need to create an index on the `listener_service` edge and perform a "rebuild index" operation after the index creation.

_Originally posted by @QingZ11 in https://github.com/vesoft-inc/nebula/issues/5853#issuecomment-2051438445_
            

![image](https://github.com/user-attachments/assets/c8b9fbfb-18ef-43f3-879b-2fb16a1eae78)
创建索引也rebuild了还是查不到

**Comment by CyanMystery** [comment]
INSERT EDGE HAS_TEXT_UNIT () VALUES '举箸提笔，诸多不便是因为膀子疼痛利害'->'"7d673964baa617d3bb395f19e776435f"':();
Execution succeeded (time spent 4.009ms/4.443343ms)

**Comment by CyanMystery** [comment]
match (e)-[r]->(n) return e,r,n  没有更新图

**Comment by CyanMystery** [comment]
算了  几万数据就显示哪个几个  用neo4j去了  你们继续加油

**Comment by QingZ11** [comment]
根据你的 rebuild job 的执行速度，应该是没有实际执行（猜测的）。

> match (e)-[r]->(n) return e,r,n  

这个语句会扫描全盘数据，在之前的版本中是被禁止的（执行了不会有结果出来）。

因为我已经不就职了，所以我没怎么关注新版演进。 @MuYiYong  如果你有空可以和这个用户讲下具体的语句情况。

最后，为了方便区分各类 issue 😊 你提 issue 的时候可以加一个 question label 哦。

**Comment by MuYiYong** [comment]
Thanks @QingZ11 !
If it is convenient, you can share your NebulaGraph version, create index and rebuild index statements
