### ISSUE TITLE
Support utf8mb4 character set

### ISSUE THREAD

**Issue by steppenwolfyuetong** [vesoft-inc/nebula#593]
Support utf8mb4 character set
1) Support by default and only support the utf8mb4 character set.
2) Support utf8mb4_bin, utf8mb4_general_ci two kinds of collation, by default utf8mb4_general_ci
3) space, tag, edge support the default use of the character set and the collation
4) The character set is required when the server side and the client side are connected.

Note:
      In nebula, we can use utf8 as an alias for utf8mb4.

**Comment by steppenwolfyuetong** [comment]
> Support utf8mb4 character set
> 
> 1. Support by default and only support the utf8mb4 character set.
> 2. Support utf8mb4_bin, utf8mb4_general_ci two kinds of collation, by default utf8mb4_general_ci
> 3. space, tag, edge support the default use of the character set and the collation
> 4. The character set is required when the server side and the client side are connected.
> 
> Note:
>       In nebula, we can use utf8 as an alias for utf8mb4.

**Comment by sherman-the-tank** [comment]
We might want to support more charset in the future. So let's make sure the charset is a property on the graph space and can be set during space creation

**Comment by steppenwolfyuetong** [comment]
Yeah, when creating space/tag/edge, you can specify the character set.
Use the default character set if create space is not specified
If create tag/edge is not specified, use the character set that belongs to space

**Comment by steppenwolfyuetong** [comment]
v
