### ISSUE TITLE
Can tag name be identical to an edge type name within the same space

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#598]
I defined an edge type named _player2_ , then created a tag named _player2_ in the same space successfully.

![image](https://user-images.githubusercontent.com/51590253/60857940-04485780-a23f-11e9-9f54-07c463c733a7.png)

Should the name be unique within one space?

**Comment by sherman-the-tank** [comment]
Good point 👍 

I don't think we should allow tag name and edge type to share the same name.

One solution is to let the meta service check during the creation and return error if the name has been used

@dangleptr
