### ISSUE TITLE
support space() function to query the current space

### ISSUE THREAD

**Issue by steppenwolfyuetong** [vesoft-inc/nebula#599]
As title

**Comment by sherman-the-tank** [comment]
Do you want something like
```
YIELD space()
```

If so, I agree with you

**Comment by steppenwolfyuetong** [comment]
> Do you want something like
> 
> ```
> YIELD space()
> ```
> 
> If so, I agree with you

Yeah

**Comment by sherman-the-tank** [comment]
This is a dup of #427 , so closing this now

**Comment by whitewum** [comment]
#427 
#615 paritally fix this problem. But I do think
yield space() make sense.

**Comment by jude-zhu** [comment]
Duplicate of #427
