### ISSUE TITLE
Column type checks are ignored when create or alter tag | edge.

### ISSUE THREAD

**Issue by boshengchen** [vesoft-inc/nebula#600]
**Describe the bug**
In source `parser.yy`, the column_spec_list clause is used to create or alter tag | edge, column types require a validation check.

**How To Reproduce**
  1. CREATE TAG person(name, age, married bool)
  2. ALTER TAG person ADD (col1), CHANGE (married), DROP (age int)
  3. CREATE EDGE man(name, age)

**Expected behavior**
SyntaxError

**Comment by sherman-the-tank** [comment]
Can someone take care of this?

**Comment by laura-ding** [comment]
Has be solved, so close it.

**Comment by laura-ding** [comment]
Has solved, so close it.
