### ISSUE TITLE
insert edge failed after create edge immediately

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#608]
first create edge and then insert edge immediately, the edge schema not update to meta client, so insert edge failed.

log like:
I0710 22:42:09.191455 21061 ExecutionPlan.cpp:15] Parsing query: create edge like(likeness int);
I0710 22:42:09.191757 21061 ThriftClientManager.inl:21] Getting a client to 127.0.0.1:45508
I0710 22:42:09.191818 21061 ThriftClientManager.inl:37] There is no existing client to 127.0.0.1:45508, trying to create one
I0710 22:42:09.191889 21061 ThriftClientManager.inl:43] Connecting to 127.0.0.1:45508 for 5 times
I0710 22:42:09.194991 21132 AsyncSocket.cpp:1931] this=0x7f563f5a0010, AsyncSocket::handleRead() got 48 bytes
I0710 22:42:13.007736 21050 SessionManager.cpp:89] Try to reclaim expired sessions out of 1 ones
I0710 22:42:23.007897 21050 SessionManager.cpp:89] Try to reclaim expired sessions out of 1 ones
I0710 22:42:33.008082 21050 SessionManager.cpp:89] Try to reclaim expired sessions out of 1 ones
I0710 22:42:36.470036 21142 AsyncSocket.cpp:1931] this=0x7f5638399010, AsyncSocket::handleRead() got 82 bytes
I0710 22:42:36.470412 21061 ExecutionPlan.cpp:15] Parsing query: insert edge like(likeness) values 100->101:(20);
E0710 22:42:36.470736 21061 SequentialExecutor.cpp:30] Prepare executor `InsertEdgeExecutor' failed: Edge is no exist

when wait some time, insert edge successfully.

**Comment by sherman-the-tank** [comment]
This is due to the time lag between all hosts (pulling meta info from the Meta Service). It's a known issue, and I think in most cases, we should be able to live with it

**Comment by wadeliuyi** [comment]
All my service just have one node, so the client used one node to create schema and insert value, so I think can we just optimize the case that:
if client create edge and insert value from one node, then success?

**Comment by sherman-the-tank** [comment]
Agreed. Whenever we modify the meta data, we should always modify the local cached meta data

**Comment by whitewum** [comment]
By the way, for the periodical refresh issue, is it possible to `make meta client flush/sync/refresh once `before `any write operation`.
I know the only way is by transaction, but at least flush is better than wait --- much better for current stage users -- periodically refresh is too hard for beginners to try, they always got confused for the first taste.

**Comment by whitewum** [comment]
Begginers are easy to be frustrated by these bugs. 
Let's provide some walkaround if entire fix is a bit hard.
Please, for the begginers.

**Comment by sherman-the-tank** [comment]
@dangleptr What do you think to let MetaClient modify the local cached meta info after succeeding in modifying the info on the meta server?

**Comment by jude-zhu** [comment]
duplicate #1145
