### ISSUE TITLE
[bug] computation check make service crash

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#626]
nebula> yield TRUE + False 

                                                     E0712 05:15:17.060276 37145 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.                                                         [ERROR (-3)]:  

I believe it relates to the CHECK()

but It's better to add ut cover `TRUE + False`.

**Comment by wadeliuyi** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f98483e8895 in __GI_abort () at abort.c:79
#2  0x00007f98483e8769 in __assert_fail_base (fmt=0x7f984854fea8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x2068f80 "(isArithmetic(left) && isArithmetic(right)) || (isString(left) && isString(right))", file=0x2068cc0 "/home/wade.liu/rd/nebula/src/common/filter/Expressions.cpp", line=866, function=<optimized out>) at assert.c:92
#3  0x00007f98483f69f6 in __GI___assert_fail (assertion=0x2068f80 "(isArithmetic(left) && isArithmetic(right)) || (isString(left) && isString(right))", file=0x2068cc0 "/home/wade.liu/rd/nebula/src/common/filter/Expressions.cpp", line=866, 
    function=0x20694c0 <nebula::ArithmeticExpression::eval[abi:cxx11]() const::__PRETTY_FUNCTION__> "virtual nebula::VariantType nebula::ArithmeticExpression::eval() const") at assert.c:101
#4  0x0000000001a78498 in nebula::ArithmeticExpression::eval[abi:cxx11]() const (this=0x7f983bd46090) at /home/wade.liu/rd/nebula/src/common/filter/Expressions.cpp:865
#5  0x0000000001888e06 in nebula::graph::YieldExecutor::execute (this=0x7f983bd35180) at /home/wade.liu/rd/nebula/src/graph/YieldExecutor.cpp:40
#6  0x0000000001819779 in nebula::graph::SequentialExecutor::execute (this=0x7f983bd360e0) at /home/wade.liu/rd/nebula/src/graph/SequentialExecutor.cpp:65
#7  0x00000000018072ce in nebula::graph::ExecutionPlan::execute (this=0x7f983bd31100) at /home/wade.liu/rd/nebula/src/graph/ExecutionPlan.cpp:49
#8  0x000000000180441e in nebula::graph::ExecutionEngine::execute (this=0x7f9847d4f340, rctx=std::unique_ptr<class nebula::graph::RequestContext<nebula::graph::cpp2::ExecutionResponse>> = {...}) at /home/wade.liu/rd/nebula/src/graph/ExecutionEngine.cpp:48
#9  0x00000000017f8f90 in nebula::graph::GraphService::future_execute (this=0x7f9847e07250, sessionId=1, query="yield TRUE+False") at /home/wade.liu/rd/nebula/src/graph/GraphService.cpp:76
#10 0x00000000018a7488 in nebula::graph::cpp2::GraphServiceSvIf::<lambda()>::operator()(void) (__closure=0x7f9823493250) at /home/wade.liu/rd/nebula/src/interface/gen-cpp2/GraphService.cpp:52
#11 0x00000000018a9571 in folly::makeFutureWith<nebula::graph::cpp2::GraphServiceSvIf::async_eb_execute(std::unique_ptr<apache::thrift::HandlerCallback<nebula::graph::cpp2::ExecutionResponse> >, int64_t, const string&)::<lambda()> >(nebula::graph::cpp2::GraphServiceSvIf::<lambda()> &&) (func=...)
    at /home/wade.liu/rd/nebula/third-party/folly/_install/include/folly/futures/Future-inl.h:1324
#12 0x00000000018a8a5a in apache::thrift::detail::si::async_tm<nebula::graph::cpp2::GraphServiceSvIf::async_eb_execute(std::unique_ptr<apache::thrift::HandlerCallback<nebula::graph::cpp2::ExecutionResponse> >, int64_t, const string&)::<lambda()> >(apache::thrift::ServerInterface *, apache::thrift::detail::si::CallbackPtr, nebula::graph::cpp2::GraphServiceSvIf::<lambda()> &&) (si=0x7f9847e07258, callback=std::unique_ptr<class apache::thrift::HandlerCallback<nebula::graph::cpp2::ExecutionResponse>> = {...}, f=...) at /home/wade.liu/rd/nebula/third-party/fbthrift/_install/include/thrift/lib/cpp2/GeneratedCodeHelper.h:1211
#13 0x00000000018a7bbb in apache::thrift::detail::si::<lambda()>::operator()(void) (this=0x7f9823493240) at /home/wade.liu/rd/nebula/third-party/fbthrift/_install/include/thrift/lib/cpp2/GeneratedCodeHelper.h:1233
#14 0x00000000018ac066 in folly::detail::function::FunctionTraits<void()>::callBig<apache::thrift::detail::si::async_eb(apache::thrift::ServerInterface*, apache::thrift::detail::si::CallbackPtr<F>, F&&) [with F = nebula::graph::cpp2::GraphServiceSvIf::async_eb_execute(std::unique_ptr<apache::thrift::HandlerCallback<nebula::graph::cpp2::ExecutionResponse> >, int64_t, const string&)::<lambda()>]::<lambda()> >(folly::detail::function::Data &) (p=...) at /home/wade.liu/rd/nebula/third-party/folly/_install/include/folly/Function.h:319
#15 0x00000000014b0c51 in folly::detail::function::FunctionTraits<void ()>::operator()() (this=0x7f98234e5290) at /home/wade.liu/rd/nebula/third-party/folly/_install/include/folly/Function.h:328
#16 0x000000000158b5d2 in apache::thrift::concurrency::FunctionRunner::run (this=0x7f98234e5280) at /home/wade.liu/rd/nebula/third-party/fbthrift/_install/include/thrift/lib/cpp/concurrency/FunctionRunner.h:135
#17 0x0000000001ba8ea0 in apache::thrift::concurrency::ThreadManager::ImplT<folly::LifoSemImpl<std::atomic, folly::SaturatingSemaphore<true, std::atomic> > >::Worker<folly::LifoSemImpl<std::atomic, folly::SaturatingSemaphore<true, std::atomic> > >::run() ()
#18 0x0000000001c215ce in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
#19 0x00007f984859458e in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007f98484c3513 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by monadbobo** [comment]
fixed by #669 .
