### ISSUE TITLE
Create schema with default values

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#631]
`INSERT VERTEX player(name) VALUES 101:("Vicenta"); -- age is set to default value 0`
![image](https://user-images.githubusercontent.com/42762957/61204165-19c9ef80-a71f-11e9-9218-5b89402b3a38.png)
Docs says code above will set `age` to default value `0`, but actually nebula keeps setting the same error shown in the picture.
So I wonder if I can set default values for schema upon building it, thus the error won't be set again.

**Comment by darionyaphet** [comment]
```
(user@127.0.0.1) [nba]> INSERT VERTEX player(name) VALUES -8379929135833483044: ("Amar'e Stoudemire")
[ERROR (-8)]: Wrong number of props
```

I test it and catch a error message.

**Comment by dangleptr** [comment]
Typically,  if you want to a default value for one column.  You should specify it when creating the schema.  Currently, we haven't supported it yet.  But it is our design.
