### ISSUE TITLE
case sensitive search Keyword BINARY

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#645]
I noted Nebula Graph doesn't support case sensitive search right now, maybe a keyword like `BINARY` will be of great help.

**Comment by sherman-the-tank** [comment]
Do you mean searching from the property index? Or case insensitive comparison in filter?

**Comment by Amber1990Zhang** [comment]
> Do you mean searching from the property index? Or case insensitive comparison in the filter?

the latter one, I want the returned the results case insensitive, mysql use keyword `binary` to do that. For example, I want to return both `tom hanks` and `Tom Hanks` in a single query, cause they carry the same meaning.

**Comment by sherman-the-tank** [comment]
Got it
