### ISSUE TITLE
Set Operation

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula#667]
Subtask of #492 
union, intersect, minus

Would we use these key words?
Or make it sql-like:
union, left join, right join.

**Comment by laura-ding** [comment]
I prefer the former one

**Comment by CPWstatic** [comment]
Since we discussed this issue offline on July 25, let me make a note here:
1. The lhs and rhs of the set operator should have the same number of columns. 
2. The column names from the first statement are used as the column names for the results returned.
3. If the data types of corresponding columns do not match, we would do convert implicitly.
4. The default behavior for ```UNION``` is that duplicate rows are removed from the result.
5. The pipe have priority over set operator.
6. We would do filtering or returning via pipe for set operation.

If I have anything missing, please add it with comment.

**Comment by CPWstatic** [comment]
> 3. If the data types of corresponding columns do not match, we would do convert implicitly.

Notice that if the implicit conversion failed, the whole statement would failed and output an error.

**Comment by sherman-the-tank** [comment]
Sorry, clicked on the wrong button
