### ISSUE TITLE
[Doc]inconsistent names

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#672]
In Chapter 「Build Your Own Graph」here are two kinds of name, one is team，anther is student.

Link：https://github.com/vesoft-inc/nebula/blob/master/docs/get-started.md#create-a-graph-space

![image](https://user-images.githubusercontent.com/38887077/61614779-273f2680-ac97-11e9-8942-ca7d593cd4b5.png)

**Comment by Amber1990Zhang** [comment]
Thanks for your kind review. Fixed. @jude-zhu

**Comment by Amber1990Zhang** [comment]
#674
