### ISSUE TITLE
Support limit and group by

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula#676]
Subtask of #492
- LIMIT syntax: 
LIMIT size/LIMIT skip, size
- GROUP BY syntax
  - syntax
  GROUP BY COUNT(propName), SUM(propName) ……
  - functions
 COUNT、COUNT DISTINCT、 SUM、 AVG、 MIN、MAX、STD
BIT_AND(), BIT_OR(), and BIT_XOR()

**Comment by whitewum** [comment]
https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html 

ref to mysql
