### ISSUE TITLE
Potential data conflicts if partId is large enough

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#679]
Currently,  we have no limit for parts number. 

For our system key,  the prefix is ```__system__```  

So if partId large enough (larger than 2037604191),  it has conflicts with the system key.

Besides that, for system keys(we just check the first byte is '_' or not),  compaction will skip them.  They will never be deleted. 

Maybe we could set the max limit for the parts number and change the way about the part storing if we don't care about the old data consistency.

**Comment by sherman-the-tank** [comment]
Sorry that I don't quite understand why when partId > 2037604191, it will conflict with the system key.  Can you shred more light? Thanks

**Comment by dangleptr** [comment]
Closed via #914
