### ISSUE TITLE
[Raft] bugs about term.

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula#685]
I am doing some basic raft test recently, here is a bug which is hard to recur. I will show some key log as follows:

---

One candidate (call it A) receive a askForVoteRequest from B like this:
```
A Recieved a VOTING request from B: B.current_term = 185, B.lastLogId = 440, B.lastLogTerm = 159
```
and A rejected it because its proposed term 195 is bigger than Req.term 185 from B.
```
The partition is currently proposing term 195. The term proposed by the candidate is no greater, so it will be rejected.

A.proposedTerm_ = 195, A.currTerm_ = 179, Term of AskForVoteRequeset from B = 185
```

**But B get a vote from C, and become leader of term 185. When B send appendLogReq to A, strange things happen, because A's term 179 is smaller than B's term 185, it will turn into a follower and apply those request.**

```
A Received logAppend: B.current_term = 185, B.committedLogId = 439, B.lastLogIdSent = 440, B.lastLogTermSent = 159
The current role is Candidate.
The current role is Candidate. Will follow the new leader (which is B)
```

Then A will crash when rolling back wal. The key point is that we use proposed_term to compare in leader election, but current_term to compare in log replication. What do you think about this? Do we need to implement the pre-vote?

The ut is Figure8 in #681, recurs sometimes.

@dangleptr @sherman-the-tank

**Comment by critical27** [comment]
Here is another case. 
1. A B C, A is leader, all accept log 1.
2. A crash, B becomes leader, B C accept log 2.
3. B crash, no quorum.
4 A reboots, quorum arises. As expected, C would become leader, but none is elected. 

* A will reject C's vote request, because it is a candidate, and its proposedTerm is bigger than term in AskForVoteRequest (which is C's proposedTerm)
* C will always reject A's vote request because its lastLogTerm is bigger

**Comment by sherman-the-tank** [comment]
A's proposed term jumped ahead is usually due to it's been isolated for a while. In this case, A's last committed log id SHOULD NEVER greater than newly elected leader's last committed log id. If A crashes when rolling back uncommitted logs, then that should be a bug in WAL

**Comment by sherman-the-tank** [comment]
> Here is another case.
> 
> 1. A B C, A is leader, all accept log 1.
> 2. A crash, B becomes leader, B C accept log 2.
> 3. B crash, no quorum.
> 4. A reboots, quorum arises. As expected, C would become leader, but none is elected.
> 
> * A will reject C's vote request, because it is a candidate, and its proposedTerm is bigger than term in AskForVoteRequest (which is C's proposedTerm).
> * C will always reject A's vote request because its lastLogTerm is bigger
> 
> If we are lucky enough, say C send its AskForVoteRequest first, A may accept it. But when I run ut, always none is elected. The ut is LeaderCrashRebootWithLogs in #681, always recurs.

This is a valid scenario. The solution proposed in the original thesis is to make each candidate wait a little and eventually a new leader will be elected (in this case, C would be elected eventually, after some time)

**Comment by critical27** [comment]
> > Here is another case.
> > 
> > 1. A B C, A is leader, all accept log 1.
> > 2. A crash, B becomes leader, B C accept log 2.
> > 3. B crash, no quorum.
> > 4. A reboots, quorum arises. As expected, C would become leader, but none is elected.
> > 
> > 
> > * A will reject C's vote request, because it is a candidate, and its proposedTerm is bigger than term in AskForVoteRequest (which is C's proposedTerm).
> > * C will always reject A's vote request because its lastLogTerm is bigger
> > 
> > If we are lucky enough, say C send its AskForVoteRequest first, A may accept it. But when I run ut, always none is elected. The ut is LeaderCrashRebootWithLogs in #681, always recurs.
> 
> This is a valid scenario. The solution proposed in the original thesis is to make each candidate wait a little and eventually a new leader will be elected (in this case, C would be elected eventually, after some time)

I think it may have great effect on availability. In this case, C can only be elected when its proposed term is bigger than A's. That would be quite a long time.

**Comment by critical27** [comment]
> A's proposed term jumped ahead is usually due to it's been isolated for a while. In this case, A's last committed log id SHOULD NEVER greater than newly elected leader's last committed log id. If A crashes when rolling back uncommitted logs, then that should be a bug in WAL

Yeah, I agree with you that A's last committed log id SHOULD NEVER greater than newly elected leader's last committed log id, and so does it in log. I am stil trying to figure it out.
