### ISSUE TITLE
[feature] return value of function now()

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#693]
![image](https://user-images.githubusercontent.com/42762957/61934507-10604300-afbb-11e9-8ff2-5fc42b0aa902.png)
What is supposed to return is 
![image](https://user-images.githubusercontent.com/42762957/61934808-bd3ac000-afbb-11e9-9ae4-73f2a64cb065.png)

**Comment by whitewum** [comment]
let check what mysql do
