### ISSUE TITLE
[function] returned error message not understandable in pow()

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#694]
![image](https://user-images.githubusercontent.com/42762957/61935151-77cac280-afbc-11e9-87a2-8c583c53791e.png)
I didn't understand the returned error message, my suggestion:
Error: argument "y" is missing, with no default
the function needs two arguments

**Comment by whitewum** [comment]
let's check mysql

**Comment by sherman-the-tank** [comment]
Totally agreed. Error messages need to be human understandable :-)
