### ISSUE TITLE
Suggested returned message when NaNs are produced

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula#695]
![image](https://user-images.githubusercontent.com/42762957/61935830-e8261380-afbd-11e9-97e9-07f2c0621c9d.png)
When a NaN is produced, a warning message is suggested like this:
Warning message: NaNs produced

**Comment by sherman-the-tank** [comment]
We can follow what mysql does

**Comment by jude-zhu** [comment]
refer to #347
