### ISSUE TITLE
crash when using "FIND" command

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#712]
![1](https://user-images.githubusercontent.com/51590253/62279115-08514900-b47c-11e9-9925-9585ced3d45a.jpg)

**Comment by monadbobo** [comment]
The find sentence has not been implemented yet, so I think we need to return to the user an unimplemented error.

**Comment by sherman-the-tank** [comment]
Yes, we should never crash

**Comment by laura-ding** [comment]
Has been solved
