### ISSUE TITLE
algo - shortest, all paths

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula#720]
shortest， all paths

subtask #492

**Comment by CPWstatic** [comment]
We need to be more specific about this issue.
@sherman-the-tank @dutor @whitewum

**Comment by sherman-the-tank** [comment]
I think **shortest path** might be more desired than **all paths**

**Comment by CPWstatic** [comment]
> I think **shortest path** might be more desired than **all paths**

OK, I'll do **shortes path** first. But I am not quite sure about the the requirements, I'll talk to you offline.

**Comment by sherman-the-tank** [comment]
> > I think **shortest path** might be more desired than **all paths**
> 
> OK, I'll do **shortes path** first. But I am not quite sure about the the requirements, I'll talk to you offline.

Sure, I'll give you a call tomorrow

**Comment by CPWstatic** [comment]
Since we talked about this at 10/8/2019 morning, let me make some note here.
We would implement the shortest algorithm:
1. over single edge type or multi edge type or *.
2. give a step-out limit when navigation.
3. we should support filter in every step out, I think. This would make it much more flexible when users want do something about the edges.

**Comment by CPWstatic** [comment]
I propose a syntax here:
```
find path from <vid_list> to <vid_list> over <edge_type_list> upto N [where ...]
find shortest path from <vid_list> to <vid_list> over <edge_type_list> upto N [where ...]
```
_<edge_type_list>_ could be replaced by ```*```

**Comment by whitewum** [comment]
what about 
```
find all | shortest path ....
````

**Comment by CPWstatic** [comment]
> what about
> 
> ```
> find all | shortest path ....
> ```

I like it. 
But I found another problem, we have no properties on in-bound edge, that means we can't do the filter when we use in-bound edge.

**Comment by CPWstatic** [comment]
As we have no properties on in-bound edge, I would implement shortest path with two implementation:
```
Suppose we have 3 vertex, **v1** is the start, **v3** is the end, **v2** is the interim vertex.
### Unidirectional Algorithm
This algorithm will support filter,  example:
_v1 -> v2 -> v3_

### Bi-Directional Algorithm
As we have no properties on in-bound edge, this algorithm will be applied when users do not declare filters in query.  The search continues until an intermediate vertex are found.Example:
_v1 -> v2 <- v1_
```

**Comment by CPWstatic** [comment]
> > what about
> > ```
> > find all | shortest path ....
> > ```
> 
> I like it.
> But I found another problem, we have no properties on in-bound edge, that means we can't do the filter when we use in-bound edge.

I'm sorry, we could do filters by getting the out-bound edges.

**Comment by CPWstatic** [comment]
Question:
How do we represent the paths when we found the

**Comment by whitewum** [comment]
One suggestion is that: to implenment the path without any filter first.

**Comment by CPWstatic** [comment]
> One suggestion is that: to implenment the path without any filter first.
