### ISSUE TITLE
算法

### ISSUE THREAD

**Issue by 0xqq** [vesoft-inc/nebula#722]
支持哪些图算法

**Comment by Amber1990Zhang** [comment]
Title: Algorithm
Question: Which graph algorithms are supported?
Answer: Algorithms are not supported at the moment, thanks for your attention.

**Comment by yanchaoguo** [comment]
同问 经典10大图算法 都支持哪些 ？没有这些algorithm如何线上应用

**Comment by whitewum** [comment]
当前的目标偏OLTP。所以更希望提供高效的CRUD能力。

**Comment by Amber1990Zhang** [comment]
Q: Does Nebula support the ten main graph algorithm? If not, how to achieve on-line application?
A: We are mainly focusing on OLTP at present in the hope of providing efficient CRUD performance.

**Comment by yanchaoguo** [comment]
> 当前的目标偏OLTP。所以更希望提供高效的CRUD能力。

那最基本的图操作应该支持吧，请问，1：怎么进行逆序查找  就是给定一个节点 找出前面的所有节点；2：如何快速获取图的每层节点数量
