### ISSUE TITLE
Preheat the storage client

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#735]
Currently,  storage client will pick up one host randomly to send request,  and after a while,  all leader addresses will be saved in storage client.   During the time,  almost all requests failed.  

To solve the problem,  we could use one preheat request to get all leaders from server-side before storage client is ready to work.

**Comment by sherman-the-tank** [comment]
Good idea 👍

**Comment by whitewum** [comment]
can you provide a command such as `check ok` to test if the cluster is available (read and write some tmp keys)? -- instead of `show hosts` or `show parts`, and check by `human eyes`-- It sucks.

( return not available is better than sth like internal error, or fetch error)
