### ISSUE TITLE
Remove add/remove hosts steps

### ISSUE THREAD

**Issue by dangleptr** [vesoft-inc/nebula#736]
Now we discover hosts automatically. 
To avoid one host without registered disturb our cluster,  we support clusterID.

Now it's time to remove the  "add/remove hosts"  steps.
There are two actions:
1.  Set the flag --hosts_whitelist_enabled=false by default.  We need to adjust many UTs in this step. 
2.  Remove the code about add/remove hosts.

**Comment by dangleptr** [comment]
The first one action is in progress,  i will submit a pr recently.  The pr make a big refactor about clusterId manager and active host manager to make the logic correct on multi replicas cluster.

**Comment by sherman-the-tank** [comment]
Before we move further, let's have a quick brain storm

**Comment by dangleptr** [comment]
Now,   the next action is to remove add/remove hosts code.  It is not in hurry,  put the task here.
