### ISSUE TITLE
We should use the clang-format to format the code.

### ISSUE THREAD

**Issue by monadbobo** [vesoft-inc/nebula#738]
We should use the [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) to format the code.

**Comment by dangleptr** [comment]
Could we use it now.  What' the usage?

**Comment by monadbobo** [comment]
> Could we use it now. What' the usage?

First you must have clang (clang-format) installed on your machine, and the most editors or IDE have clang-format plugins, such as [vim ](https://github.com/rhysd/vim-clang-format) , [emacs](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format.el) and so on.

The principle of clang-format is to format your code according to the configuration (.clang-format). The describes of the configuration can be found [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

In #566 I made some changes based on google's code style.

**Comment by yixinglu** [comment]
@sherman-the-tank  @dangleptr 

`clang-format` has been a very popular tool for cpp developer and many editors have related plugins to integrate it. It not only checks code style but also helps developer to **FIX** some format errors. We can add a `cmake` target to call clang-format to format sources by `make format`. It will really improve our development experience.

I find the code style of nebula is inconsistent with Google code style in some aspects like indent with 4 spaces. We should determine configuration options of `clang-format` as soon as possible before merging the PR #566 . 

In addition, [clang-tidy](https://clang.llvm.org/extra/clang-tidy/), used by many open source projects,  also is very useful tool for cpp source code static analysis. I think we also need it.
