### ISSUE TITLE
We should implement log compaction in Raft

### ISSUE THREAD

**Issue by monadbobo** [vesoft-inc/nebula#743]
We should implement log compaction in Raft (InstallSnapshot RPC).

**Comment by dangleptr** [comment]
I have a pr locally,   i need some time to test it.  Thanks for opening this issue.

**Comment by monadbobo** [comment]
> I have a pr locally, i need some time to test it. Thanks for opening this issue.

It's awesome!

**Comment by whitewum** [comment]
ref #690
