### ISSUE TITLE
[question] put wal and rocksdb data in different disks

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#744]
The IO pattern for raft wal and rocksdb data are different. Is it an improvement to put them on two disks?

**Comment by darionyaphet** [comment]
We'll keep writing `WAL` and flush memory table into disk interval. IMO, it's reasonable to put them into same disk.

**Comment by whitewum** [comment]
> We'll keep writing `WAL` and flush memory table into disk interval. IMO, it's reasonable to put them into same disk.

Rocksdb has background compaction
wal has gc

**Comment by sherman-the-tank** [comment]
I think it makes sense to separate WAL and data. For example, WAL could be written on faster media, such as 3dXpoint disks

**Comment by darionyaphet** [comment]
I will add a flag to control WAL data path. It it's not setting,  will saving in data path.
