### ISSUE TITLE
"GO 2 STEP" crash storaged

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#747]
```
nebula> INSERT VERTEX student(name, age, gender) VALUES 200:("Monica", 16, "female");
Execution succeeded (Time spent: 3663/4415 us)
nebula> CREATE EDGE like(likeness double);
Execution succeeded (Time spent: 1684/2513 us)
nebula> INSERT VERTEX student(name, age, gender) VALUES 202:("Jane", 17, "female");
Execution succeeded (Time spent: 1938/2652 us)
nebula> INSERT VERTEX student(name, age, gender) VALUES 201:("Mike", 18, "male");
Execution succeeded (Time spent: 1644/2370 us)
nebula> INSERT EDGE like(likeness) VALUES 200 -> 201:(92.5);
Execution succeeded (Time spent: 2080/2873 us)
nebula> INSERT EDGE like(likeness) VALUES 201 -> 200:(85.6);
Execution succeeded (Time spent: 1445/2107 us)
nebula> INSERT EDGE like(likeness) VALUES 201 -> 202:(93.2);
Execution succeeded (Time spent: 1827/2484 us)
nebula> GO 2 STEPS FROM 100 OVER like;
Execution succeeded (Time spent: 2072/2891 us)
nebula> GO 2 STEPS FROM 200 OVER like;
```
F0809 15:54:10.118764 25411 RowReader.cpp:205] Check failed: !!schema_ A schema must be provided
*** Check failure stack trace: ***
    @          0x20206bd  google::LogMessage::Fail()
    @          0x2024ccc  google::LogMessage::SendToLog()
    @          0x20203bd  google::LogMessage::Flush()
    @          0x2020ba9  google::LogMessageFatal::~LogMessageFatal()
    @          0x1aa94a3  nebula::RowReader::RowReader()
    @          0x1aa8f02  nebula::RowReader::getEdgePropReader()
    @          0x156be2f  nebula::storage::QueryBaseProcessor<>::collectEdgeProps()
    @          0x1568d76  nebula::storage::QueryBoundProcessor::processVertex()
    @          0x153eac9  _ZZN6nebula7storage18QueryBaseProcessorINS0_4cpp219GetNeighborsRequestENS2_13QueryResponseEE18asyncProcessBucketENS0_6BucketEENUlvE_clEv
    @          0x1552c66  _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZN6nebula7storage18QueryBaseProcessorINS7_4cpp219GetNeighborsRequestENS9_13QueryResponseEE18asyncProcessBucketENS7_6BucketEEUlvE_EEvRNS1_4DataE
    @          0x1529ffd  folly::detail::function::FunctionTraits<>::operator()()
    @          0x159cd9a  apache::thrift::concurrency::FunctionRunner::run()
    @          0x1e1d373  apache::thrift::concurrency::ThreadManager::ImplT<>::Worker<>::run()
    @          0x1e8e9ae  apache::thrift::concurrency::PthreadThread::threadMain()
    @     0x7f3c9990458e  start_thread
    @     0x7f3c99833513  __GI___clone
[ERROR (-8)]: Get neighbors failed

**Comment by jude-zhu** [comment]
core dump file content

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
Core was generated by `/home/jude.zhu/nebula_build/bin/nebula-storaged --flagfile /home/jude.zhu/nebul'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
[Current thread is 1 (Thread 0x7f3c704e1700 (LWP 25411))]
Missing separate debuginfos, use: dnf debuginfo-install libgcc-8.3.1-2.fc29.x86_64 libstdc++-8.3.1-2.fc29.x86_64 libunwind-1.2.1-6.fc29.x86_64

**Comment by jude-zhu** [comment]
nebula-storaged.FATAL content:
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0809 15:54:10.118764 25411 RowReader.cpp:205] Check failed: !!schema_ A schema must be provided

**Comment by jude-zhu** [comment]
![1](https://user-images.githubusercontent.com/51590253/62764883-84254400-bac1-11e9-92cc-c18dc472e179.jpg)

**Comment by jude-zhu** [comment]
code version： commit a380bee6045e6222aaca2a7a2a9e86f790e33cc1

**Comment by dangleptr** [comment]
We should remove the check inside RowReader
