### ISSUE TITLE
"GO 2 steps" Get neighbors failed

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#751]
![1](https://user-images.githubusercontent.com/51590253/62778924-5d2c3980-bae4-11e9-8807-ca34d7d84d30.jpg)

the first time "Go 2 steps " works fine,  the second time, it returns `[ERROR (-8)]: Get neighbors failed`

**Comment by darionyaphet** [comment]
I stopped `storage` and restart it 3 times. Running this command `GO 2 steps FROM 200 OVER like` multi times.

Actually, I can't replay this issues.
