### ISSUE TITLE
distinguish about mutex and spin lock

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#753]
Is it possible to replace the mutex to spin lock about logsLock_ and raftLock_?
1、worker's number is limited resource to our system. if a worker schedule out by os when the lock conflict, it will cult down the throughput about the system.
2、the lock protected critical region is a little of memory operation, it just take a little of cpu time, maybe spin lock is more suitable

**Comment by dutor** [comment]
This is not a simple topic which we could quickly make conclusions. It depends on many factors to reason about:
  * The timing cost of critical section
  * Whether the lock contention is severe
  * Whether the number of involved threads exceeds the number of available cores
  * Whether the threads run independently, in terms of logics, resources, OS scheduling
  * Whether the task priority matters
  * Whether fairness matters
  * This list could go on and on

We shall make decisions on benchmarks, while benchmarking  on this topic is hard, harder beyond most people could imagine. But based on my experiences,  for most of complex userspace applications and systems, preferring mutex to spin lock is not a bad idea in most cases.

**Comment by wadeliuyi** [comment]
Thanks for answer, I get a lot of knowledge.
You are very right, we must take care about it,  the less lock in main path of code is just one method to get high performance.
