### ISSUE TITLE
graphd crashes

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#756]
when yield src prop, it works fine. However, when yield dst prop, graphd crashes. 
I build on the 
commit 90824399d7ec05391a2117c08b9a917409b338dd
Date:   Thu Aug 8 18:29:03 2019 +0800

![1](https://user-images.githubusercontent.com/51590253/62844819-6a207700-bcf6-11e9-92aa-811d085f29c8.jpg)
![2](https://user-images.githubusercontent.com/51590253/62844823-6f7dc180-bcf6-11e9-9f8f-56fc0f5ef526.jpg)

**Comment by CPWstatic** [comment]
Thank you!
This crash problem will occur when the dest vertex contains nothing. I think you might find it crash when the src vertex or edge contains nothing. To fix this, we need something to represent NULL or non-existing prop urgently. Or we could just give the default value first to avoid this kind of crash. I will talk to @monadbobo first, maybe he had do something in pr #697.

**Comment by CPWstatic** [comment]
Thank you!
This crash problem will occur when the dest vertex doesn't exist. I think you might find it crash when the src vertex  doesn't exist. To fix this, we need something to represent NULL or non-existing prop urgently. Or we could just give the default value first to avoid this kind of crash. I will talk to @monadbobo first, maybe he had do something in pr #697 that would fix this problem.

**Comment by whitewum** [comment]
I found another crash case: yield $$.not_exist_tag.not_exist_prop.
I think this case is covered by unittest, so I wonder why.
