### ISSUE TITLE
code style issue

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#771]
some function in nebula store is void, but in the function it return.
void NebulaStore::asyncMultiRemove(GraphSpaceID spaceId,
                                   PartitionID  partId,
                                   std::vector<std::string> keys,
                                   KVCallback cb) {
    auto ret = part(spaceId, partId);
    if (!ok(ret)) {
        cb(error(ret));
        return;
    }
    auto part = nebula::value(ret);
    return part->asyncMultiRemove(std::move(keys), std::move(cb));
}

**Comment by dangleptr** [comment]
Good catch
