### ISSUE TITLE
[2 bugs] about show variables

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#780]
1. the service has started for about an hour, but why `show variables graph` is empty
2. why `show variables graph` two times return different?  -- I can't reproduce the syntax error

![image](https://user-images.githubusercontent.com/50101159/63085075-3a37d480-bf7f-11e9-8663-7b7b55e7ec75.png)
![image](https://user-images.githubusercontent.com/50101159/63085397-01e4c600-bf80-11e9-97e5-b3c3d3511be8.png)

grep don't return any `update config in cache `

![image](https://user-images.githubusercontent.com/50101159/63086156-ccd97300-bf81-11e9-9c4e-bbc1c4454962.png)

**Comment by critical27** [comment]
Register gflags ok

**Comment by whitewum** [comment]
@laura-ding

**Comment by critical27** [comment]
Just as I said, graph only retry a few times to connect meta, then it goes on. That is the only reason why we can't show the variables of graph. The reason why we depend meta here is because some variables are used when we init other component.
