### ISSUE TITLE
[bug] insert empty prop errors

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#782]
I add two hosts (in fact they are the same machine)

If I add vertex with property, it's ok

If I add vertex with no property. It's internal error.

![image](https://user-images.githubusercontent.com/50101159/63087921-eaa8d700-bf85-11e9-8384-98e8d64c1825.png)

![image](https://user-images.githubusercontent.com/50101159/63088064-630f9800-bf86-11e9-9e77-02b71943c299.png)

I'm not sure it's about two hosts or empty prop, but it's easy to reproduce.

**Comment by laura-ding** [comment]
The reason is because of there has two hosts, and one of it doesn't work, so storageclient choose a random host to request, and the choose one is nonexistent. now the host doesn't need to be added by users, it auto add to the cluster. so we should delete the `add host` interface. @dangleptr
