### ISSUE TITLE
code stype about pass parameter by value, by reference and by rvalue reference

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#789]
I see that in function define:
MetaClient::alterEdgeSchema(GraphSpaceID spaceId,
                            std::string name,
                            std::vector < cpp2::AlterSchemaItem > items,
                            nebula::cpp2::SchemaProp schemaProp)

### the vector is pass by value, 

and when call the function in void HBaseStore::asyncMultiPut(GraphSpaceID spaceId,
                               PartitionID partId,
                               std::vector<KV> keyValues,
                               KVCallback cb) {
std::vector<std::pair<std::string, std::vector<KV>>> dataList;
// push some value to dataList
### ResultCode code = client_->multiPut(tableName, dataList); // pass by value directly.
...
}

and in Metaclient unit test, it pass by value too.

maybe there other place is not right too.

what more: I think pass by rvalue reference is better than pass by value, it can less one rvalue constructor called.

**Comment by darionyaphet** [comment]
It's like what I talk to @wadeliuyi offline. It's a good suggestion :)
