### ISSUE TITLE
Nebula crash when configure firewall to accept raft election port

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#815]
**Describe the bug(__must be provided__)**

Nebula processes crash after accepting raft election port.
  

**Your Environments(__must be provided__)**
  * OS: CentOS
  * Compliler: Installed by RPM

**How To Reproduce(__must be provided__)**
  1. Make firewall block the raft election port(`metad_port + 1`).
  2. Configure metad multiple peers in `nebula-metad.conf`, set `wal_ttl` default value, start nebula processes.
  3. Then update firewall rule to accept the election port. 
  4. Nebula processes crash

**Expected behavior**

Nebula metad work well.

**Additional context**

Clean the meta data and restart all nebula processes to fix it.

![metad-crash](https://user-images.githubusercontent.com/2520865/63401120-d1ca7680-c408-11e9-86d0-e4e254c8e0c3.png)

**Comment by dangleptr** [comment]
The reason is that WALs has been removed during this time.  Leader has to send snapshot when catching up data,  and the logic will be implemented in #795
