### ISSUE TITLE
graph client for java exists problems

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#816]
**Describe the bug(__must be provided__)**

The following problems are coming from `src/client/java`

1.  In pom.xml file, the scope of the `thrift` artifact should be `compile`.
```
<dependency>
            <groupId>com.facebook</groupId>
            <artifactId>thrift</artifactId>
            <version>1.0.0-SNAPSHORT</version>
            <scope>system</scope>
            <systemPath>${JAVA_FBTHRIFT_JAR}</systemPath>
</dependency>
```

2.  In GraphClient.java file, the `executeQuery` method should throw exceptions to `caller` instead of hiding when the return-value is empty caused by some exceptions. User can do something(ps: retry) accroding the exception.
```
 @Override
    public ResultSet executeQuery(String stmt) {
        ExecutionResponse executionResponse = internalExecuteQuery(stmt);
        if (Objects.isNull(executionResponse)) {
            return new ResultSet();
        } else {
            return new ResultSet(executionResponse.getColumn_names(),
                    executionResponse.getRows());
        }
    }
```

**Comment by darionyaphet** [comment]
`system` : This scope have to provide the JAR which contains it explicitly.

**Comment by zlcook** [comment]
> `system` : This scope have to provide the JAR which contains it explicitly.
We want to be able to download all dependencies from the remote repository.
We will firstly install `thrift` JAR into mvn respository(local or remote), then `compile` scope will be ok. So, in order to use java client, we need `graph-client-xxx.jar` and `JAVA_FBTHRIFT_JAR`.

**Comment by darionyaphet** [comment]
#819
