### ISSUE TITLE
For a directory document, convenient index and learning framework

### ISSUE THREAD

**Issue by walter211** [vesoft-inc/nebula#830]
**Is your feature request related to a problem? Please describe.**
Need a easy way to handle or understand the project architecture.

**Describe the solution you'd like**
Make a better reading doc blog.

**Describe alternatives you've considered**
For now, can just add a index md files at the doc root directory.

**Additional context**
Good project!

**Comment by whitewum** [comment]
Great suggestion. Thank you.
