### ISSUE TITLE
Chinese Guideline shows error when try to insert

### ISSUE THREAD

**Issue by walter211** [vesoft-inc/nebula#831]
**Describe the bug(__must be provided__)**
Follow the guideline, when try to execute this

> INSERT VERTEX student(name, age, gender) VALUES 200:("Monica", 16, "female");

shows error:

> [ERROR (-8)]: No schema found for `student'

**Your Environments(__must be provided__)**
  * OS: `18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`
  * Compliler: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  * CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz

**How To Reproduce(__must be provided__)**
  1. Just follow the chinese guideline step by step
  2. try to execute command 'INSERT VERTEX student(name, age, gender) VALUES 200:("Monica", 16, "female");'
  3. shows error above

**Expected behavior**
Should execute success or shows error meta is not ok

**Additional context**
first launch
When you execute some other command，it wiil be ok， not sure if it caused by meta problme

**Comment by whitewum** [comment]
Thank you for your report. 

I think this is due to the meta refresh issue (https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/get-started.md see the bottom part)

By default, it takes about 2min to refresh meta change. ( Of cause, this is a bad choice for the beginners)

Can you try in the console:

```
 get variables graph:load_data_interval_secs
```

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/63571727-a3d56580-c5b3-11e9-951a-91767189ecff.png)
