### ISSUE TITLE
Get inconsistent results when stop/restart 1 storaged replica multiple times

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#839]
**Describe the bug(__must be provided__)**
Get inconsistent results and different error message after stop/restart different storaged replica.

**Your Environments(__must be provided__)**
  * OS: CentOS 7
  * Compliler: Installed By RPM with recent commits
  * CPU: Test in virtual machines

3 nodes `192.168.8.{14 | 15 | 16}` deployed all nebula services: `graphd`, `metad` and `storaged`

**How To Reproduce(__must be provided__)**
  1. create 3 spaces:

    create space sp0(partition_num=1, replica_factor=3);
    create space sp1(partition_num=3, replica_factor=3);   
    create space sp2(partition_num=5, replica_factor=3);

  2. use space `sp0` and create some tags and edges, refer to [this document(named A)](https://github.com/vesoft-inc/nebula/blob/master/docs/get-started.md#create-a-graph-space) steps. 
  3. use space `sp1` and create some tags and edges, refer to [another document(named B)](https://github.com/vesoft-inc/nebula/blob/master/docs/nGQL-tutorial.md#graph-administration) steps
  4. stop `storaged` service in `192.168.8.15` by nebula bash script
  5. use `sp0` and execute some queries in document A
  6. restart `storaged` service in `192.168.8.15`
  7. use `sp1` and execute some queries in document B
  8. stop `storaged` service in `192.168.8.14` by script
  9.  use `sp0` and execute some queries in document A
  10. get inconsistent results and different error causes.

**Expected behavior**

Get consistent results.

**Additional context**

Error Message:
```text
[ERROR (-8)]: Get dest props failed
[ERROR (-8)]: vertex was not found 101
[ERROR (-8)]: Get neighbors failed
```

![inconsistent-results](https://user-images.githubusercontent.com/2520865/63577292-a9857800-c5c0-11e9-9ec6-dfdb217b467c.png)

**Comment by yixinglu** [comment]
When restart `storaged` service in `192.168.8.14` again, right results are there.

**Comment by critical27** [comment]
You'd better test with only one space here, and kill/restart one storage randomly, and do some query and insert. Otherwise, some appearance is irrelevant to the the essential, but also it is hard to reproduce the problem.

**Comment by critical27** [comment]
Working on it.
