### ISSUE TITLE
Add CODEOWNERS for nebula repo

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#842]
I suggest we can use `CODEOWNERS` to define some individuals who are responsible for codes or modules in nebula repository. So when some codes/modules are changed by PR, their owners can be notified to review.

In addition, we can also easily select some **owners** to review our PR when contributing to nebula.

References:

- [About code owners](https://help.github.com/en/articles/about-code-owners)
- [Tensorflow CODEOWNERS](https://github.com/tensorflow/tensorflow/blob/master/CODEOWNERS)

**Comment by darionyaphet** [comment]
When you commit the pull request, github will support a suggest review which include the owner and latest modifier.
