### ISSUE TITLE
Add `meta_server_addrs` option to default meta configuration file

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#844]
Now in [`etc/nebula-metad.conf.default`](https://github.com/vesoft-inc/nebula/blob/master/etc/nebula-metad.conf.default) default configuration file, miss the important option `meta_server_addrs` which configures how many peers this metad service has. The option default value is `""`.

**Comment by laura-ding** [comment]
has complete it, so close it.
