### ISSUE TITLE
Fix variable syntax document examples about `load_config_interval_secs`

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#845]
**Describe the bug(__must be provided__)**

`load_config_interval_secs` has been replaced with `load_data_interval_secs`.

**Additional context**

![load-config-variables](https://user-images.githubusercontent.com/2520865/63670936-d4fea180-c810-11e9-8687-27128a841c67.png)

**Related documents**
- [variables-syntax-en](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md)
- [variables-syntax-cn](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md)

**Comment by dangleptr** [comment]
Very good catch.  Do you want to give a pr for it?   @yixinglu
