### ISSUE TITLE
Support multi line string in console

### ISSUE THREAD

**Issue by critical27** [vesoft-inc/nebula#856]
So we have some output which is multi line string, and the format in console will become weird.
For example, `show create tag`,
![image](https://user-images.githubusercontent.com/13706157/63766383-a1e60c00-c8fd-11e9-91e3-9924bc57c9ed.png)

This one is generally ok, but if the string becomes longer, it will be harder to figure out. See example below:
![image](https://user-images.githubusercontent.com/13706157/63766445-bf1ada80-c8fd-11e9-8e3c-dcabebea6e53.png)

I think maybe we can support something like multi line string, put them in to a single cell without occupying other cells.

**Comment by Shylock-Hg** [comment]
It's ok now
