### ISSUE TITLE
Server crash caused by inappropriate YIELD Sentence

### ISSUE THREAD

**Issue by GuleonSeon** [vesoft-inc/nebula#866]
If I type a `$` back then an alphabet such as: `a` , `abc` or `hjd` , the server will crash.
But in other case, such as `$~` or `$1bd` , the server will report a syntax error normally.
eg:
`(user@127.0.0.1) [(none)]> yield $a;`
`E0829 14:44:02.767930  3212 GraphClient.cpp:85] Thrift rpc call failed: Channel got EOF. Check for server hitting connection limit, server connection idle timeout, and server crashes.
[ERROR (-3)]:`
`(user@127.0.0.1) [(none)]> quit`
`[root@e4daa5a54647 nebula]# scripts/nebula.service status all`
`[INFO] nebula-metad: Running as 2963, Listening on 45500`
`[INFO] nebula-graphd: Exited`
`[INFO] nebula-storaged: Running as 3088, Listening on 44500`
![bug](https://user-images.githubusercontent.com/45303862/63951409-460fb480-cab0-11e9-80a3-922e846cfa90.png)

**Comment by CPWstatic** [comment]
Thank you! This crash problem would be resolved after pr#745 being merged.

**Comment by whitewum** [comment]
@somexavior Do you want to fix the issue?
