### ISSUE TITLE
3rdparty build issue

### ISSUE THREAD

**Issue by charint** [vesoft-inc/nebula#878]
**Describe the bug(__must be provided__)**
I have setup the environment following the guide: https://docs.nebula-graph.io/manual-CN/how-to-build/  on centos 7.6 , at the step: build 3rdparty, I got the following issue:

[chenfeng@localhost nebula-3rdparty]$ cmake ./
-- SKIP_JAVA_JAR = ON
-- Set macro _FORTIFY_SOURCE=2
-- CMAKE_BUILD_TYPE = Release (Options are: Debug, Release, RelWithDebInfo, MinSizeRel)
-- THIRDPARTY_PATH = /opt/nebula/third-party
-- Specified NEBULA_KRB5_ROOT: /home/engshare/krb5
-- Specified NEBULA_LIBUNWIND_ROOT: /home/engshare/libunwind
-- Specified NEBULA_OPENSSL_ROOT: /home/engshare/openssl
-- Specified NEBULA_FLEX_ROOT: /home/engshare/flex
-- Specified NEBULA_GPERF_BIN_DIR: /home/engshare/gperf/bin
-- CMAKE_INCLUDE_PATH: /home/engshare/flex/include:/home/engshare/boost/include:/home/engshare/openssl/include:/home/engshare/libunwind/include:/home/engshare/krb5/include
-- CMAKE_LIBRARY_PATH: /home/engshare/flex/lib:/home/engshare/boost/lib:/home/engshare/openssl/lib:/home/engshare/libunwind/lib:/home/engshare/krb5/lib
-- CMAKE_PROGRAM_PATH: /home/engshare/gperf/bin:/home/engshare/flex/bin:/home/engshare/krb5/bin
-- Boost version: 1.67.0
-- found krb5-config here /home/engshare/krb5/bin/krb5-config
-- Found kerberos 5 headers: /home/engshare/krb5/include
-- Found kerberos 5 libs:    /home/engshare/krb5/lib/libgssapi_krb5.a;/home/engshare/krb5/lib/libkrb5.a;/home/engshare/krb5/lib/libk5crypto.a;/home/engshare/krb5/lib/libcom_err.a;/home/engshare/krb5/lib/libkrb5support.a
-- Could NOT find ncurses (missing: NCURSES_INCLUDE_DIR NCURSES_LIBRARY)
-- Could NOT find LibLZMA (missing: LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)
-- Glibc version is 2.17
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCURSES_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd

-- Configuring incomplete, errors occurred!
See also "/home/chenfeng/nebula-3rdparty/CMakeFiles/CMakeOutput.log".

**Your Environments(__must be provided__)**
  * OS: `uname -a`
  * Compliler: `g++ --version` or `clang++ --version`
  * CPU: `lscpu`

OS: Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Compiler: 
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

CPU: 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    12
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              44
型号名称：        Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
步进：              2
CPU MHz：             3065.794
BogoMIPS：            6131.58
超管理器厂商：  KVM
虚拟化类型：     完全
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           12288K
NUMA 节点0 CPU：    0-11

**How To Reproduce(__must be provided__)**
  1. Step 1
bash> git clone https://github.com/vesoft-inc/nebula-3rdparty.git
bash> cd nebula-3rdparty
bash> cmake ./

**Expected behavior**

[chenfeng@localhost nebula-3rdparty]$ cmake ./
-- SKIP_JAVA_JAR = ON
-- Set macro _FORTIFY_SOURCE=2
-- CMAKE_BUILD_TYPE = Release (Options are: Debug, Release, RelWithDebInfo, MinSizeRel)
-- THIRDPARTY_PATH = /opt/nebula/third-party
-- Specified NEBULA_KRB5_ROOT: /home/engshare/krb5
-- Specified NEBULA_LIBUNWIND_ROOT: /home/engshare/libunwind
-- Specified NEBULA_OPENSSL_ROOT: /home/engshare/openssl
-- Specified NEBULA_FLEX_ROOT: /home/engshare/flex
-- Specified NEBULA_GPERF_BIN_DIR: /home/engshare/gperf/bin
-- CMAKE_INCLUDE_PATH: /home/engshare/flex/include:/home/engshare/boost/include:/home/engshare/openssl/include:/home/engshare/libunwind/include:/home/engshare/krb5/include
-- CMAKE_LIBRARY_PATH: /home/engshare/flex/lib:/home/engshare/boost/lib:/home/engshare/openssl/lib:/home/engshare/libunwind/lib:/home/engshare/krb5/lib
-- CMAKE_PROGRAM_PATH: /home/engshare/gperf/bin:/home/engshare/flex/bin:/home/engshare/krb5/bin
-- Boost version: 1.67.0
-- found krb5-config here /home/engshare/krb5/bin/krb5-config
-- Found kerberos 5 headers: /home/engshare/krb5/include
-- Found kerberos 5 libs:    /home/engshare/krb5/lib/libgssapi_krb5.a;/home/engshare/krb5/lib/libkrb5.a;/home/engshare/krb5/lib/libk5crypto.a;/home/engshare/krb5/lib/libcom_err.a;/home/engshare/krb5/lib/libkrb5support.a
-- Could NOT find ncurses (missing: NCURSES_INCLUDE_DIR NCURSES_LIBRARY)
-- Could NOT find LibLZMA (missing: LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)
-- Glibc version is 2.17
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCURSES_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/bzip2
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/double-conversion
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fatal
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/fbthrift
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/folly
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/gflags
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/glog
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/googletest
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/jemalloc
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/libevent
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/mstch
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/proxygen
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/rocksdb
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/snappy
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/wangle
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zlib
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd
   used as include directory in directory /home/chenfeng/nebula-3rdparty/third-party/zstd

-- Configuring incomplete, errors occurred!
See also "/home/chenfeng/nebula-3rdparty/CMakeFiles/CMakeOutput.log".

**Additional context**
-- Could NOT find ncurses (missing: NCURSES_INCLUDE_DIR NCURSES_LIBRARY)
-- Could NOT find LibLZMA (missing: LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET)
-- Glibc version is 2.17

It looks like I need to export these 2 libs

**Comment by laura-ding** [comment]
Your environment has not `ncurses` and `lzma`, you can use yum to install them. Don't need to do export.

Thanks for your feedback!

**Comment by yixinglu** [comment]
seems solved it. So close the issue.
