### ISSUE TITLE
[manual] I need some help about docs

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula#883]
@laura-ding @CPWstatic @monadbobo @dutor @darionyaphet @dangleptr 
I'm working on the RC1 doc. please help me with the following secitons:

data-types/string-types.md timestamp-types.md

functions-and-operators/type-conversion.md string-operations.md #841

server-administrations/bulk-load.md balance.md

In next release
language-structure/literal-values/NULL-values.md string-literals.md

**Comment by critical27** [comment]
For leader balance, you can refer to #731.

**Comment by whitewum** [comment]
I hope you can provide a short but enough .md file first since I can't follow all your updates.

**Comment by dangleptr** [comment]
For server-administrations module,  @darionyaphet will give a doc ASAP.   
leader-balance.md and snapshot.md could be replaced by balance usage
