### ISSUE TITLE
The backspace problem in nebula console

### ISSUE THREAD

**Issue by somexavior** [vesoft-inc/nebula#886]
**Describe the bug**
There seems to be some confusion ,when I want delete some characters in the console 

**Your Environments**
  * OS: `uname -a`
`Linux Xavior-PC 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
  * Compliler: `g++ --version` or `clang++ --version`
`Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Compiled Nebula Version**
 * `bin/nebula -version`
`nebula version Git: 5e87a42, Build Time: Sep  1 2019 20:32:50
This source code is licensed under Apache 2.0 License, attached with Common Clause Condition 1.0.`
**How To Reproduce**
Open the nebula console, and input whatever you want and then delete some of them by `backspace key`, you will find the charactors are still in your console, but they are deleted in fact.

**Here is the screen shot**
![backspace](https://user-images.githubusercontent.com/45303862/64138902-9df04780-ce31-11e9-917c-48aab7977774.png)

**Comment by laura-ding** [comment]
Thank you for your feedback. 
step1: delete 

```
-DNEBULA_READLINE_ROOT=/home/engshare/readline -DNEBULA_NCURSES_ROOT=/home/engshare/ncurses
```
from **~/.bashrc** 

step2: `source ~/.bashrc`

**Comment by somexavior** [comment]
Thanks for your reply, but it doesn't seem to work by your method.

**Comment by laura-ding** [comment]
you can install readline and ncurses through yum

**Comment by somexavior** [comment]
Thank's very much！By your way, the problem have been solved. @laura-ding

**Comment by somexavior** [comment]
The issue have been solved.
