### ISSUE TITLE
code style about RaftPart

### ISSUE THREAD

**Issue by wadeliuyi** [vesoft-inc/nebula#892]
If I want storage some value in raft part, the function stack as follow:
appendLogAsync() 
-> appendLogsInternal()
->replicateLogs()
all of the functions do same thing that check the part status at begin, but I think it is useless and waste cpu resource because need raft_lock_.
It is need to simply check the status.
the simply way is just check status at begin of appendLogAsync and after collect all response from other nodes.

**Comment by critical27** [comment]
We would rewrite the raft later, 👍
