### ISSUE TITLE
wal dir is not used in meta server

### ISSUE THREAD

**Issue by wenzhenghu** [vesoft-inc/nebula#893]
according to rocksdb log, wal and data is in the same dir. 
```
2019/09/04-16:42:02.391629 7f8353d37b40 SST files in data/meta/nebula/0/data dir, Total Num: 0, files: 
2019/09/04-16:42:02.391631 7f8353d37b40 Write Ahead Log file in data/meta/nebula/0/data: 
...
2019/09/04-16:42:02.391655 7f8353d37b40                                 Options.wal_dir: data/meta/nebula/0/data
```
by there still have a wal dir . maybe the setting is wrong, wal should move to wal dir.
```
[root@nebula2 0]# ls
data  wal
[root@nebula2 0]# pwd
/usr/local/nebula/data/meta/nebula/0
[root@nebula2 0]# ls wal/
0
[root@nebula2 0]# ls wal/0/
[root@nebula2 0]# 
```

**Comment by critical27** [comment]
Just as you said, wal and data is in the same dir (see NebulaStore::newPart). We may clean outdated wal in background. Default TTL is 86440s.

**Comment by wenzhenghu** [comment]
@critical27  did you mean that outdated wal will first move to data/meta/nebula/0/wal ？

**Comment by zhangguoqing** [comment]
In fact, when meted is a cluster, the **wal** will be used. :)
