### ISSUE TITLE
3rd party folly compilation error

### ISSUE THREAD

**Issue by breezeflutter** [vesoft-inc/nebula#900]
**Describe the bug(__must be provided__)**

**Your Environments(__must be provided__)**
  * OS: ubuntu 16.04
  * Compliler: g++ 5.4.0
  * CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

Scanning dependencies of target tgt_zstd
Scanning dependencies of target tgt_snappy
Scanning dependencies of target tgt_jemalloc
Scanning dependencies of target tgt_bzip2
Scanning dependencies of target tgt_zlib
Scanning dependencies of target tgt_fatal
Scanning dependencies of target tgt_gflags
Scanning dependencies of target tgt_libevent
Built target tgt_fatal
Scanning dependencies of target tgt_double-conversion
Built target tgt_bzip2
Scanning dependencies of target tgt_mstch
Built target tgt_zlib
Built target tgt_double-conversion
Built target tgt_snappy
Built target tgt_gflags
Built target tgt_mstch
Built target tgt_libevent
Scanning dependencies of target tgt_glog
Built target tgt_zstd
Built target tgt_glog
Scanning dependencies of target tgt_folly
Scanning dependencies of target tgt_googletest
third-party/folly/CMakeFiles/tgt_folly.dir/build.make:57: recipe for target 'third-party/folly/CMakeFiles/tgt_folly' failed
make[2]: *** [third-party/folly/CMakeFiles/tgt_folly] Error 1
CMakeFiles/Makefile2:650: recipe for target 'third-party/folly/CMakeFiles/tgt_folly.dir/all' failed
make[1]: *** [third-party/folly/CMakeFiles/tgt_folly.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Built target tgt_jemalloc
Built target tgt_googletest
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by laura-ding** [comment]
Can you provide `nebula-3rdparty/third-party/folly/_build.log`, thanks!

**Comment by breezeflutter** [comment]
> Can you provide `nebula-3rdparty/third-party/folly/_build.log`, thanks!

Start building folly-2018.08.20.00 with /usr/bin/c++ (5.4.0-6ubuntu1~16.04.11))

./build.sh: line 38: ((: 5 > 8 || 5 == 8 && 4 > 2 || 5 == 8 && 4 == 2 && 0-6ubuntu1: value too great for base (error token is "6ubuntu1")
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /home/engshare/cmake/share/cmake-3.11/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_6a959/fast"
    make[3]: Entering directory '/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp'
    /usr/bin/make -f CMakeFiles/cmTC_6a959.dir/build.make CMakeFiles/cmTC_6a959.dir/build
    make[4]: Entering directory '/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_6a959.dir/testCXXCompiler.cxx.o
    /usr/bin/c++    -Wno-array-bounds -Wno-class-memaccess -fPIC -DPIC -DFOLLY_HAVE_LIBDWARF_DWARF_H -DFOLLY_HAVE_MEMRCHR -Wno-noexcept-type -Wno-error=parentheses -Wno-error=shadow=compatible-local  -O2 -g    -o CMakeFiles/cmTC_6a959.dir/testCXXCompiler.cxx.o -c /home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    cc1plus: error: -Werror=shadow=compatible-local: no option -Wshadow=compatible-local
    cc1plus: warning: unrecognized command line option '-Wno-noexcept-type'
    cc1plus: warning: unrecognized command line option '-Wno-class-memaccess'
    CMakeFiles/cmTC_6a959.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_6a959.dir/testCXXCompiler.cxx.o' failed
    make[4]: *** [CMakeFiles/cmTC_6a959.dir/testCXXCompiler.cxx.o] Error 1
    make[4]: Leaving directory '/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_6a959/fast' failed
    make[3]: *** [cmTC_6a959/fast] Error 2
    make[3]: Leaving directory '/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeTmp'
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


-- Configuring incomplete, errors occurred!
See also "/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeOutput.log".
See also "/home/ai/nebula-3rdparty/third-party/folly/_build/folly-2018.08.20.00/CMakeFiles/CMakeError.log".

### folly-2018.08.20.00 failed to configure the build ###

**Comment by laura-ding** [comment]
I think you have no use the package which is download from `wget https://nebula-graph.oss-cn-hangzhou.aliyuncs.com/build-deb/ubuntu1804.tar.gz`.
the doc has show it [how_to_build.md](https://github.com/vesoft-inc/nebula/blob/master/docs/how-to-build.md)

**Comment by laura-ding** [comment]
@breezeflutter  does it has been resolved?
