### ISSUE TITLE
java importer --help error

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula#903]
java Importer to load csv file. 

When I type `./run.sh`, it works fine and lists help message.

![image](https://user-images.githubusercontent.com/51590253/64416682-39034e80-d0ca-11e9-9795-18c2d227c1fc.png)

however `./run.sh "-h"` and `./run.sh "--help"` don't.

![image](https://user-images.githubusercontent.com/51590253/64416469-cf834000-d0c9-11e9-816b-ae8cc68f4f84.png)

**Comment by darionyaphet** [comment]
# 915
