### ISSUE TITLE
document ubuntu add unzip dependencies

### ISSUE THREAD

**Issue by LiFool** [vesoft-inc/nebula#913]
### **Expected behavior**
**Just add unzip dependency** at ubuntu **Install dependencies** part in nebula/docs/how-to-build.md .  Or during the 3rd-party Libraries installment ,  it's really bothered to check **functions.sh** .    

**The error log without unzip package :**
third-party/proxygen/CMakeFiles/tgt_proxygen.dir/build.make:57: recipe for target 'third-party/proxygen/CMakeFiles/tgt_proxygen' failed
make[3]: *** [third-party/proxygen/CMakeFiles/tgt_proxygen] Error 1
CMakeFiles/Makefile2:1237: recipe for target 'third-party/proxygen/CMakeFiles/tgt_proxygen.dir/all' failed

**Comment by jude-zhu** [comment]
We will add it. Thank you for your advice.

**Comment by laura-ding** [comment]
Has been completed
