### ISSUE TITLE
Support to use cpp client

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula#956]
Now the `cpp client` can't use it separate nebula source code, we should package it to an rpm/deb package

Step1 :  we should wrap a layer out of `cpp client` , make it to a .so file
Step2:  package it to rpm/deb

**Comment by darionyaphet** [comment]
We are plan to change the client to golang.

**Comment by laura-ding** [comment]
- `python client` issue:  #871 
- `go client ` repo: https://github.com/vesoft-inc/nebula-go

**Comment by doublex** [comment]
Are there still plans to add a C++ client?

**Comment by jude-zhu** [comment]
yes, we r working on it.
https://github.com/vesoft-inc/nebula/pull/1013

**Comment by jude-zhu** [comment]
refer to https://github.com/vesoft-inc/nebula-cpp
