### ISSUE TITLE
Installed with docker, `SHOW SPACES` throws error

### ISSUE THREAD

**Issue by xieceinhe** [vesoft-inc/nebula#979]
**Describe the bug(__must be provided__)**
使用docker安装并连接Nebula Graph 后
bin/nebula -u=user -p=password

列出已有的 Space报错：
>SHOW SPACES;
[ERROR (-8)]: RPC failure in MetaClient: N6apache6thrift9transport19TTransportExceptionE: Channel is !good()

**Your Environments(__must be provided__)**
  * OS: `uname -a`
  * Compliler: `g++ --version` or `clang++ --version`
  * CPU: `lscpu`
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 32
On-line CPU(s) list: 0-31
Thread(s) per core: 2
Core(s) per socket: 8
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 45
Model name: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
Stepping: 7
CPU MHz: 2390.744
CPU max MHz: 2800.0000
CPU min MHz: 1200.0000
BogoMIPS: 3990.29
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 20480K
NUMA node0 CPU(s): 0-7,16-23
NUMA node1 CPU(s): 8-15,24-31

**How To Reproduce(__must be provided__)**
  1. Step 1
>docker run -it vesoft/nebula-graph:latest /bin/bash
  2. Step 2
> cd /usr/local/nebula/
  3. Step 3
> scripts/nebula.service start all
  4. Step 4
> bin/nebula -u=user -p=password
  5. Step 5
> SHOW SPACES;

**Expected behavior**
没有错误

**Additional context**
no.

**Comment by jude-zhu** [comment]
请问下 ./scripts/nebula.service status all 的输出是？

**Comment by xieceinhe** [comment]
[root@ab7e3abd5d4d nebula]# scripts/nebula.service  status all
[INFO] nebula-metad: Exited
[INFO] nebula-graphd: Running as 44, Listening on 3699 
[INFO] nebula-storaged: Exited
[root@ab7e3abd5d4d nebula]# bin/nebula -u=user -p=password

Welcome to Nebula Graph (Version 1.0.0-beta)

(user@127.0.0.1) [(none)]> SHOW SPACES;
[ERROR (-8)]: RPC failure in MetaClient: N6apache6thrift9transport19TTransportExceptionE: Channel is !good()

**Comment by Amber1990Zhang** [comment]
> [root@ab7e3abd5d4d nebula]# scripts/nebula.service status all
> [INFO] nebula-metad: Exited
> [INFO] nebula-graphd: Running as 44, Listening on 3699
> [INFO] nebula-storaged: Exited
> [root@ab7e3abd5d4d nebula]# bin/nebula -u=user -p=password
> 
> Welcome to Nebula Graph (Version 1.0.0-beta)
> 
> (user@127.0.0.1) [(none)]> SHOW SPACES;
> [ERROR (-8)]: RPC failure in MetaClient: N6apache6thrift9transport19TTransportExceptionE: Channel is !good()

metad and storaged are dead.

**Comment by monadbobo** [comment]
Hello, the possible reason here is that the listening address in our default configuration is fixed, so you may need to modify the default configuration. For details, you can read our [documentation](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/get-started.md#使用docker启动后执行命令时报错).

**Comment by laura-ding** [comment]
Thank you for your feedback! Please download the docker image again, we had fixed it, the reason is CPU instruction set incompatibility

**Comment by xieceinhe** [comment]
Yes, this bug is really fixed。thanks.

**Comment by Echo0117** [comment]
> Hello, the possible reason here is that the listening address in our default configuration is fixed, so you may need to modify the default configuration. For details, you can read our [documentation](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/get-started.md#%E4%BD%BF%E7%94%A8docker%E5%90%AF%E5%8A%A8%E5%90%8E%E6%89%A7%E8%A1%8C%E5%91%BD%E4%BB%A4%E6%97%B6%E6%8A%A5%E9%94%99).

Hi, I got the same problem here, but this document has expired, can I find it somewhere else?
