### ISSUE TITLE
I don't know how to use it by python. Anyone can help me ?

### ISSUE THREAD

**Issue by xieceinhe** [vesoft-inc/nebula#980]

**Comment by laura-ding** [comment]
We haven't wrapped the python interface yet, but you can use the compiled files `interface/gen-py/*` to communicate with graphd.

**Comment by xieceinhe** [comment]
Is it now only available on the command line?

**Comment by darionyaphet** [comment]
Thanks  Currently, we have supported C++, Java and Golang client.

**Comment by dangleptr** [comment]
https://github.com/vesoft-inc/nebula/pull/984

The pr is about python client.  You could check it out and try it.
