### ISSUE TITLE
 What do ws_http_port,ws_h2_port and meta_server_addrs mean in nebula-metad.conf? Why are there so many ports?

### ISSUE THREAD

**Issue by xieceinhe** [vesoft-inc/nebula#982]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by darionyaphet** [comment]
The difference between `ws_http_port` and `ws_h2_port`, one is the `HTTP` protocol and another is the `HTTP2` protocol.

`meta_server_addrs` is the meta services' addresses.

**Comment by dangleptr** [comment]
Could we unify them?
