### ISSUE TITLE
Support Wisckey for nebula general storage

### ISSUE THREAD

**Issue by windshg** [vesoft-inc/nebula#995]
wisckey paper:  
https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf

production-proved implementation from pingcap:
https://github.com/pingcap/titan

**Comment by dangleptr** [comment]
Good one.  For pure KV,   it could give a better perf.

**Comment by whitewum** [comment]
We've discussed long time ago whether to use the wisckey or pure key, and we think for the graph case, pure key is better.  (we may support wisckey later)

**Comment by windshg** [comment]
> We've discussed long time ago whether to use the wisckey or pure key, and we think for the graph case, pure key is better. (we may support wisckey later)

yeap, graph scan keys all the time.  Wisckey is not suitable.
